### ISSUE TITLE
Crashes (segfaults) on Wayland

### ISSUE THREAD

**Issue by mirenradia** [IsmaelMartinez/teams-for-linux#1001]
**Describe the bug**
Ever since the last update (from v1.3.12 to v1.3.14), I am fairly frequently getting crashes when running on Wayland (often when I am in a call). Although the crashes can occur randomly, I can reproduce it fairly consistently using the steps below.

**To Reproduce**
1. Launch in a terminal with the following command
   ```
   teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland
   ```
2. Quickly maximise the application before it has time to load fully.
3. It will crash and and I see this output in my terminal
   ```
   [ERROR] net::ERR_CONNECTION_REFUSED
   [1]    52878 segmentation fault (core dumped)  teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland 
   ```

**Expected behavior**
No crash or segfault like in v1.3.12.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Fedora 38 
 - Installation package: RPM
 - Version: 1.3.14
 - Desktop Environment: KDE Plasma 5.27.8
 - Kernel Version: 6.5.8-200.fc38.x86_64 (64-bit)
 - Graphics Platform: Wayland

**Additional context**
I've been experiencing a similar issue with VSCode which is also electron based under certain conditions (microsoft/vscode#184124) which has been blamed on this upstream electron issue (electron/electron#37531) and I think this might be the same issue. For now, I will stick with v1.3.12.

**Comment by Senshi111** [comment]
same here

**Comment by kudlatyamroth** [comment]
same here... it sometimes also happen after win+left window move...

**Comment by herbiejhopkins** [comment]
Same here. Downgrading to 1.3.12 seems to resolve the issue to I assume it's related to the electron 27 upgrade.

**Comment by herbiejhopkins** [comment]
Played around with a few different electron packages. I can reproduce the crash easily with all the 27.0.x versions just by launching and maximising/unmaximising a few times. The 28.0.0-beta.4 release seems stable though so hopefully we can upgrade to v28 when it's released in a few weeks.

**Comment by IsmaelMartinez** [comment]
has any of you tried the suggestions in this comment?

https://github.com/electron/electron/issues/37531#issuecomment-1723724293

Basically, starting the app with `--disable-sandbox` and or `--disable-gpu-sandbox` (the comment says `-disable-gpu-sandbox` but I suspect that is incorrect).

**Comment by karjonas** [comment]
> has any of you tried the suggestions in this comment?
> 
> [electron/electron#37531 (comment)](https://github.com/electron/electron/issues/37531#issuecomment-1723724293)
> 
> Basically, starting the app with `--disable-sandbox` and or `--disable-gpu-sandbox` (the comment says `-disable-gpu-sandbox` but I suspect that is incorrect).

Does not work for me at least

**Comment by kudlatyamroth** [comment]
neither --disable-gpu-sandbox nor --disable-sandbox work for me either

**Comment by karjonas** [comment]
I noticed that the crash does not actually happen on startup but rather on login, of course if you have auto login then it happens on startup.

**Comment by jeremiah-miller** [comment]
```
~ $ /opt/teams-for-linux/teams-for-linux --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --ozone-platform=wayland --disable-sandbox --disable-gpu-sandbox
[117847:1129/091702.465313:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/teams-for-linux/chrome-sandbox is owned by root and has mode 4755.
fish: Job 1, '/opt/teams-for-linux/teams-for-…' terminated by signal SIGTRAP (Trace or breakpoint trap)
~ [SIGTRAP]$ /opt/teams-for-linux/teams-for-linux --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --ozone-platform=wayland
[117881:1129/091708.850934:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/teams-for-linux/chrome-sandbox is owned by root and has mode 4755.
fish: Job 1, '/opt/teams-for-linux/teams-for-…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by andreaippo** [comment]
Hi folks, I reached this issue from #1016.

My _flatpak_ teams for linux crashes on my a couple of seconds into startup.

This is what I get if I run the command mentioned in the .desktop file in a shell:

```shell
andrea@andromeda:~> /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=teams-for-linux --file-forwarding com.github.IsmaelMartinez.teams_for_linux @@u %U @@
[2:1130/102537.353402:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
[2:1130/102537.552996:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1130/102537.553048:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1130/102537.583896:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1130/102537.583921:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1130/102537.583939:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[ERROR] net::ERR_CONNECTION_REFUSED
[47:1130/102542.973866:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
``` 

Am I in the right place? Is this what's being discussed here?

I'm running version 1.3.19 as a flatpak under opensuse Tumbleweed (kernel 6.6.2).
As a workaround I'm using the appimage which is thankfully working fine (version 1.3.23)

Thanks

**Comment by jonatasrs** [comment]
On wayland and last version of teams-for-linux code (tag: v1.3.23) crash:
* With ozone backend x11 it work fine.
* teams-for-linux 1.3.12 work with ozone backend wayland.

```
$ yarn start --ozone-platform-hint=wayland
yarn run v1.22.19
$ yarn install && electron ./app --ozone-platform-hint=wayland
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder  version=24.6.4
  • loaded configuration  file=package.json ("build" field)
[DEBUG] configPath:,/home/jonatasers/.config/Electron
[DEBUG] configFile:,[object Object]
[INFO] Running under Wayland, switching to PipeWire...
[DEBUG] Fetching custom background configuration from 'http://localhost:9000/config.json'
[DEBUG] Custom background service url is 'http://localhost:9000'
[DEBUG] processArgs:,/home/jonatasers/src/teams-for-linux/node_modules/electron/dist/electron,./app,--ozone-platform-hint=wayland
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
[DEBUG] Language codes pt-BR set for spellchecker
[DEBUG] Custom background service remote configuration stored at '/home/jonatasers/.config/Electron/custom_bg_remote.json'
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[DEBUG] Network test successful with method https
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-frame-finish-load,[object Object],false
/home/jonatasers/src/teams-for-linux/node_modules/electron/dist/electron exited with signal SIGSEGV
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by herbiejhopkins** [comment]
Tested latest git but with electron updated to newly released v28.0.0 - seems stable to me.

**Comment by mirenradia** [comment]
> Tested latest git but with electron updated to newly released v28.0.0 - seems stable to me.

@herbiejhopkins, maybe it's worth commenting this on the upstream electron issue (electron/electron#37531)?

**Comment by mirenradia** [comment]
Can we update to Electron v28 to fix this (v28 reportedly fixes electron/electron#37531)?

Tagging @jijojosephk as he seems to have done most of the previous electron upgrade PRs.

**Comment by IsmaelMartinez** [comment]
I will wait until tomorrow to see if the open PR we got is done and do the upgrade, otherwise it gets a bit annoying for the person doing the other PR as they need to rebase etc (and it is almost ready)

**Comment by jonatasrs** [comment]
Version 1.4.1 work fine with ozone backend wayland. Thanks.

**Comment by jirutka** [comment]
Why has this still not been released on [Flathub](https://flathub.org/apps/com.github.IsmaelMartinez.teams_for_linux)?

**Comment by IsmaelMartinez** [comment]
1.4.1 is now stable. @jijojosephk does the flathub releases.

**Comment by jijojosephk** [comment]
Thanks @IsmaelMartinez, I'll work on `1.4.1' for flatpak.

**Comment by hadogenes** [comment]
when the deb version in repo (repo.teamsforlinux.de) will be updated?
Thanks
