### ISSUE TITLE
Camera Not Accesible When Built From Source

### ISSUE THREAD

**Issue by shnee** [IsmaelMartinez/teams-for-linux#1002]
I don't have the ability to configure my audio, mic. and camera before a call.  The "device" settings seems to be missing and only accessible when I'm already in a meeting or on a call.

When I'm on a call I get an error that the camera is not accessible. The camera does appear in the "Device" settings when I'm on a call, however, the camera does not work in a call.

The camera does work in web app.

## Environment

Manjaro, installed via the AUR. It appears that the AUR package installs from source.
X11

## Warnings

I do get the following warnings when running:
> Warning: loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
> Warning: vkCreateInstance: Found no drivers!>
> Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
>     at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
>     at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
>     at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
>     at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
>     at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)

**Comment by shnee** [comment]
Is it normal to not have "Device Setting" while not on a call?

Is there anything I can to provide more information?

**Comment by jijojosephk** [comment]
@shnee The is a wrapper around the teams web app. Like the web, this does not provide any device settings before call. You can change the settings only just before the call or during the call. No settings like the official desktop app.

**Comment by pvagner** [comment]
I am also seeing this when building teams-for-linux package from the AUR. My issue is that I can't think of a way on how to diagnose this. Other apps handling audio can see the microphone and capture the audio including teams running in the web browser such as firefox and chromium.

**Comment by IsmaelMartinez** [comment]
have you tried another aur package that also needs microphone and/or audio capture? maybe is a local system config. (this tends to be the case with aur, flathub and snap specially)

**Comment by pvagner** [comment]
On my end it turned out to be a network configuration issue. It's interesting that in the browser I was able to join meetings though.

**Comment by IsmaelMartinez** [comment]
can we check if this is still a problem in 1.4.1? Closing until I heard back
