### ISSUE TITLE
Connecting multiple accounts in the application

### ISSUE THREAD

**Issue by n0where3an** [IsmaelMartinez/teams-for-linux#1005]
Two different organizations launched Teams. It is necessary that two accounts are to open (not simultaneously) in the application (that is, so as not to constantly go through the authorization procedure again when switching between accounts). The Windows application already has this. Please add .

**Comment by petrmanek** [comment]
I discovered that the `partition` flag can be used to conveniently keep two separate sessions/cookie jars, which contain auth information for different organizations. The problem is that teams-for-linux will only allow at most one instance of the program to run at any given time, so launching another instance (albeit in a different partition) will only bring up a window owned by the already running counterpart.

It would be great if the partition was considered when looking for already running instances. For now, I am mitigating this by running teams-for-linux inside firejail (the same strategy works for launching multiple zoom clients simultaneously btw).

**Comment by Stav88** [comment]
There is a workaround for that : 
* Create a new folder inside `$HOME/snap/teams-for-linux/current/.config/`
* Copy `/var/lib/snapd/desktop/applications/teams-for-linux_teams-for-linux.desktop` into `$HOME/.local/share/applications/`
* Rename and edit it in `HOME/.local/share/applications/`
  * Change `Exec` by adding `--customUserDir=` parameter using folder created previously
  * Change `StartupWMClass` by adding some charaters at end of class
  * (optional) Change `Name` and/or `Icon` to make difference in menu
* Maybe restart your session tu update menu

**Comment by dagmoller** [comment]
> I discovered that the `partition` flag can be used to conveniently keep two separate sessions/cookie jars, which contain auth information for different organizations. The problem is that teams-for-linux will only allow at most one instance of the program to run at any given time, so launching another instance (albeit in a different partition) will only bring up a window owned by the already running counterpart.
> 
> It would be great if the partition was considered when looking for already running instances. For now, I am mitigating this by running teams-for-linux inside firejail (the same strategy works for launching multiple zoom clients simultaneously btw).

Take a look at BrowserView of Electron...
Is possible to run 2 or more browserviews at same time and swap then..
I'm using this on my whatsapp-electron app...
https://github.com/dagmoller/whatsapp-electron

**Comment by IsmaelMartinez** [comment]
Feel free to put a PR with the changes needed. Many people will appreciate it 😃 

The solution @Stav88 posted is what is currently preferred as it is the simplest way to configure and manage multiple sessions.

**Comment by callegar** [comment]
What would be the equivalent with flatpak?

**Comment by aabittner** [comment]
I dont really know much about all the different releases of teams, teams-free and what not microsoft offered and released during all those recent years, but how about the actual current real multiple account feature and possibility microsoft talks about for teams-free at their own page at:
<https://support.microsoft.com/en-us/office/add-another-account-within-microsoft-teams-free-8ada567f-909a-413f-8259-0d7d76d2f4b0#id0ebf=desktop>

will this be possible inside this teams-for-linux project? I am not really sure how your project encapsulates teams/web resources from microsoft and how all of this works together. thanks for considering and explaining? thanks.

**Comment by IsmaelMartinez** [comment]
Hi, 

We wrap around the web version, so if they start supporting this in the web version, we will get it for free. Microsoft doesn't support a Linux client, teams-free and the other clients seem to be only for Windows or MacOS.

It has been explored in the past to implement this using tabs and other ways, but never got enough traction and the current way of having multiple clients running seems to be the simplest/best use of effort. It is not an easy task.

I keep asking for people to write down how they use it, to be able to document it and see if there are ways to make it better, but got conflicting and/or contradictory ways, so waiting for more data.

By the way, version 1.14.0 gets rid of the customUserDir (as electron don't support anymore camelCase for those properties). People will need to replace it with an ELECTRON_USER_DATA_PATH environment variable, but it should work the same way.

Hope that helps.
Ismael

**Comment by ntrsrts** [comment]
Using --user-data-dir instead of --customUserDir seems to work just fine for versions >=1.14.0 .
