### ISSUE TITLE
Whata about teams 2.0 and beyond

### ISSUE THREAD

**Issue by je-vv** [IsmaelMartinez/teams-for-linux#1006]
Hello !

This is more sort of a question rather than a query for action or something.  Its purpose is to understand what will be the teams-for-linux status now that [teams 2.0 is out](https://windowsreport.com/microsoft-teams-2-0-download).  Teams 2.0 is not electron based, and although they stopped supporting the electron Team for gnu+linux some time ago, the windows/mac desktop app was still electron.

The thing is that teams 2.0 is now based on webView 2.0 instead of electron, and react instead of angular.  The big part of it is not developing for electron:
- [Teams 2.0 Moves Away from Electron to Embrace Edge WebView2](https://techcommunity.microsoft.com/t5/microsoft-teams/teams-2-0-moves-away-from-electron-to-embrace-edge-webview2/m-p/2484565)
- [Stop saying Microsoft Teams is being rewritten from Electron to React](https://blog.thoughtstuff.co.uk/2021/08/stop-saying-microsoft-teams-is-being-rewritten-from-electron-to-react)
- [Electron to WebView2 – What does it really mean for the Teams desktop client, and for a Client SDK?](https://blog.thoughtstuff.co.uk/2021/06/electron-to-webview2-what-does-it-really-mean-for-the-teams-desktop-client-and-for-a-client-sdk)

Now, there's hope to eventually, with really low priority webview2 gets support for gnu+linux, and there's a [linux support issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/645) about it.  Mac already gained support, and actually the windows report at the beginning shows that the recently release teams 2.0 includes Mac clients, and there's also a [mac support issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1314#issuecomment-1751265475) on which it's mentioned the support for Mac is there.  All this just to say, as usual for MS stuff, gnu+linux is not part of their priorities.

Coming back to teams-for-linux, as it's based on electron, what's the status and plan?  Will teams-for-linux support only pre 2.0 teams technology, components and/or webapp?  I guess at some point being based on old versions on teams stuff might become difficult, given compatibility issues and the like, but can't really tell.

So just wondering what'll happen with teams-for-linux.  Not sure if we'll be able to use web browser (we should), but so far, at least for me, on Firefox, Librewolf and ungoogled chromium, there's no way to connect to meetings, whether something just fails (Firefox/Librewolf), or I get into an infinite loop without connecting (ungoogled chromium).  So I really enjoy teams-for-linux being available...

Greetings !

**Comment by LinAGKar** [comment]
Correct me if I'm wrong, but this app basically wraps the web version. So as long as the web version keeps working in Chrome, it should keep working in this app.

**Comment by jijojosephk** [comment]
Like @LinAGKar said, it would work as long as the web version stays in `angular`. But as soon as they release the `react` version to web, this would possibly break. We all anticipate the problem. So keeping our fingers crossed. Be a part of this chat group in matrix https://matrix.to/#/#teams-for-linux_community:gitter.im as soon as you find issues, kindly report. We'll try to make it up and running.

**Comment by LinAGKar** [comment]
I have actually gotten the "new Teams" toggle (which I assume switches to the React version) in this app since yesterday, and I haven't noticed any issues so far. But I'll be on the lookout.

**Comment by je-vv** [comment]
Well, if you look at the teams 2.0 changes, they are doing both:

- Moving from electron to webview2
- Moving from angular to react

And I guess the web version will still work, but I can't really tell.  All those changes on teams 2.0 for sure affect the web app, not just the desktop app, but I wasn't able to foresee if that would affect 3rd party electron based apps.  Perhaps not.

If you feel like the question doesn't make sense, and eventually a new issue can be filed if something goes wrong, please feel free to close this issue.

Thanks !

**Comment by Thaodan** [comment]
I've looked into the situation regarding WebView2 vs Electron. I wonder how can teams 2.0 replace this app really? Teams isn't foss, you can't just package and drop it into your favorite distro. 
Even if you ignore that factor usually with Electron apps you can use your own Electron with some effort, you can't do that with WebView2  it's closed source..

**Comment by jorgeperezlara** [comment]
I'm sorry, but WebView2 is basically Edgium instead of Chromium. I don't understand how or why would a move between frameworks and rendering engines make it any less possible to have Teams 2.0 on Linux. You just repackage it again, and given WebView2 is Chromium, unless there's some extensions for which we require workarounds, it should work. In the end, there's Edge on Linux as well...

**Comment by cs96and** [comment]
> Like @LinAGKar said, it would work as long as the web version stays in `angular`. But as soon as they release the `react` version to web, this would possibly break.

Why would it break?  If it can run in a browser then it can run in Electron can't it?

**Comment by jijojosephk** [comment]
I'm not saying it won't function. Of course it will, but we had written some code that uses `angular` modules. `Ex: Notification count`. Like small things that used to work might stop all of a sudden.

**Comment by cs96and** [comment]
> I'm not saying it won't function. Of course it will, but we had written some code that uses `angular` modules. `Ex: Notification count`. Like small things that used to work might stop all of a sudden.

Ah OK. Thanks for the explanation.

**Comment by Thaodan** [comment]
Jorge Pérez Lara ***@***.***> writes:

> I'm sorry, but WebView2 is basically Edgium instead of Chromium. I
> don't understand how or why would a move between frameworks and
> rendering engines make it any less possible to have Teams 2.0 on
> Linux. You just repackage it again, and given WebView2 is Chromium,
> unless there's some extensions for which we require workarounds, it
> should work. In the end, there's Edge on Linux as well...

WebView2 is closed source you don't know what extension are there,
besides WebView2 doesn't work like the Java Runtime in the way Electron
does as the app can use WebView2 in a way that first calls C++ code and
then JavaScript and not just pure JavaScript that can have native NodeJS
modules.

**Comment by jorgeperezlara** [comment]
> Jorge Pérez Lara ***@***.***> writes:
> I'm sorry, but WebView2 is basically Edgium instead of Chromium. I don't understand how or why would a move between frameworks and rendering engines make it any less possible to have Teams 2.0 on Linux. You just repackage it again, and given WebView2 is Chromium, unless there's some extensions for which we require workarounds, it should work. In the end, there's Edge on Linux as well...
> WebView2 is closed source you don't know what extension are there, besides WebView2 doesn't work like the Java Runtime in the way Electron does as the app can use WebView2 in a way that first calls C++ code and then JavaScript and not just pure JavaScript that can have native NodeJS modules.

I agree we don't know what's exactly in WebView2, but I honestly would be very surprised if there's any kind of native code running in there apart from a pure Electron in-house alternative that could easily be replaced. I don't even think they're using any kind of especial, native code for calls at all...

I might be wrong, though.

**Comment by jijojosephk** [comment]
https://www.electronjs.org/blog/webview2

**Comment by IsmaelMartinez** [comment]
To be honest, the move from angular to react is the only main issue we got, and as @jijojosephk points out, is not a huge amount of logic we got on that are. I don't expect big issues happening from the electron to webview2 move, as we wrap around the browser version. If they remove the web version then we are screwed, but I doubt that will happen any time soon (if ever)

**Comment by cs96and** [comment]
It wouldn't surprise me if they make the web version Edge only at some point in the future.

**Comment by jorgeperezlara** [comment]
That'd be solved with some kind of user-agent faking...

@IsmaelMartinez gracias por tu trabajo, Ismael! If I can be of any help repackaging Teams 2.0, I'm not super proficient, but we can get in touch and I kind do my best.

**Comment by cs96and** [comment]
> That'd be solved with some kind of user-agent faking...

Not if they start using some undocumented parts of Edge

**Comment by jorgeperezlara** [comment]
> > That'd be solved with some kind of user-agent faking...
> 
> Not if they start using some undocumented parts of Edge

Is there any indication of that? Because I seriously doubt it. It'd be a burden for the development team, plus I don't think there's anything in particular that would require such a thing.

**Comment by IsmaelMartinez** [comment]
If they do, they would make Salesforce(Slack) extremely happy. And I
suspect Google and Apple lawyers will have a word or two to say

**Comment by geckolinux** [comment]
> @IsmaelMartinez gracias por tu trabajo, Ismael!

I just came to say the same thing. Teams-for-Linux is massively important for the Linux community. Even for those of us that hate Teams and Microsoft in general, many many pragmatic people have to use Teams whether they like it or not. I suspect that this project is what makes it possible for a lot of us to continue using Linux on our workstations. Thanks a ton Ismael.

**Comment by IsmaelMartinez** [comment]
Not me, the community. As an example, @jijojosephk deserves lots of that credit. 

It only works because the contributions many make. 

From bug fixes, improving documentation, reporting problems and everything else. 

We extremely appreciated every and any help.

**Comment by jorgeperezlara** [comment]
> I have actually gotten the "new Teams" toggle (which I assume switches to the React version) in this app since yesterday, and I haven't noticed any issues so far. But I'll be on the lookout.

How did you get it? I'm not able to get the 2.0 version yet.

Does it work for you properly still?

**Comment by jorgeperezlara** [comment]
> I'm using teams 2.0 daily in teams for linux, it works for me. Actually I don't think that a switch to webview2 is mandatory. And as soon as it is ported to linux, Microsoft might be working on a linux port too (low prio of course ;) ). For the time beeing I would hold on to the current course and see what the future holds (until it breaks :) )

That's fantastic news then. Glad it's working properly. I guess someday I'll get the same toggle.

**Comment by divico** [comment]
Here https://learn.microsoft.com/en-us/microsoftteams/new-teams-web it says

| Date              | Availability                                                                                                                |
|-------------------|-----------------------------------------------------------------------------------------------------------------------------|
| 1st Quarter, 2024 | <ul > <li > New Teams for Web for Firefox and Safari. </li > <li > Progressive Web App (PWA) support on Linux </li > </ul > |

As well as
>The new Teams web client offers near feature parity with the new Desktop client thanks to a new, cross-client infrastructure.

But unfortunatly it also says
>The following notable features aren't available on new Teams or classic Teams clients:
>- Simultaneous availability and notifications across multiple accounts and tenants
>- Popout windows for chat and channel content
>- Avatars and video background effects, except for background blur

**Comment by nerumo** [comment]
> > I'm using teams 2.0 daily in teams for linux, it works for me. Actually I don't think that a switch to webview2 is mandatory. And as soon as it is ported to linux, Microsoft might be working on a linux port too (low prio of course ;) ). For the time beeing I would hold on to the current course and see what the future holds (until it breaks :) )
> 
> That's fantastic news then. Glad it's working properly. I guess someday I'll get the same toggle.

the toggle disappeared for me somehow. I hacked my way around:
- right click on the task icon from the desktop
- select debug -> dev tools open
- goto the console
- enter `document.location.href = 'https://teams.microsoft.com/v2/'`
- the page reloads in v2 (if company policy allows it)

**Comment by zainin** [comment]
Same here, although to make it work I had to _first_ set `localStorage` in the console, and then go to the v2 URL.  
Otherwise it just reloaded back to the v1.

So far seems to work fine, except that the icon in the tray now permanently shows one unread notification.

**Comment by qdrop17** [comment]
A small additional hint: I use the new Teams flawlessly as a Chromium Webapp on Linux. I just have to fake the UserAgent to Windows in order for the toggle to show up. Funny (or sad?) but true.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/42340241/bbd54525-fe4b-4230-a25e-2e09edb65b4d)

**Comment by D-MLink** [comment]
> > > > I'm using teams 2.0 daily in teams for linux, it works for me. Actually I don't think that a switch to webview2 is mandatory. And as soon as it is ported to linux, Microsoft might be working on a linux port too (low prio of course ;) ). For the time beeing I would hold on to the current course and see what the future holds (until it breaks :) )
> > > 
> > > 
> > > That's fantastic news then. Glad it's working properly. I guess someday I'll get the same toggle.
> > 
> > 
> > the toggle disappeared for me somehow. I hacked my way around:
> > ```
> > * right click on the task icon from the desktop
> > 
> > * select debug -> dev tools open
> > 
> > * goto the console
> > 
> > * enter `document.location.href = 'https://teams.microsoft.com/v2/'`
> > 
> > * the page reloads in v2 (if company policy allows it)
> > ```
> 
> For me it was needed to also "opt-in" for Teams2. This can be done by `window.localStorage.setItem("tmp.isOptedIntoT2Web", true)` in the console. My guess is that this "Try Teams2" toggle button also simply was setting this value in the `localStorage`.

This could be a toggle/option for teams for linux, to use the newer teams

**Comment by IsmaelMartinez** [comment]
> A small additional hint: I use the new Teams flawlessly as a Chromium Webapp on Linux. I just have to fake the UserAgent to Windows in order for the toggle to show up. Funny (or sad?) but true.
> 
> ![image](https://private-user-images.githubusercontent.com/42340241/298505237-bbd54525-fe4b-4230-a25e-2e09edb65b4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDA4MzIsIm5iZiI6MTcwNTk0MDUzMiwicGF0aCI6Ii80MjM0MDI0MS8yOTg1MDUyMzctYmJkNTQ1MjUtZmU0Yi00MjMwLWEyNWUtMmUwOWVkYjY1YjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE2MjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZWQ2YTU2Y2U4NmMzMGQ3N2EwYjI3NmQ3OWFiY2RhMDFkNzllODA1YzhkYjNiZTI3Njc1MDE2OWYyMzM1NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dAsWuBVbe-iku2wujz6A9Ms0TqDqzRPHI5XcAQg4V-0)

We do something similar https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/index.js#L66 but we add a few extra functionality.

**Comment by Cybso** [comment]
I've opted in to v2 using the localStorage trick.

incomingCallCommand doesn't work anymore. However, the popup notification still works, so I think this should not be very hard to fix?

**Comment by Zahrun** [comment]
Background effects are working: blur or Microsoft’s choice of background images. I don’t see any option to set a custom image in v1 nor v2.

**Comment by jijojosephk** [comment]
@Zahrun please read this. https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md#custom-backgrounds

**Comment by storm9c1** [comment]
This warning (appearing at the top of the chat window) is new...

![teams-for-linux-msg](https://github.com/IsmaelMartinez/teams-for-linux/assets/16827398/f8ec03d2-0a7c-4217-adbe-184ac58eda29)

Should we be concerned?

**Comment by IsmaelMartinez** [comment]
I don't think so, but can you send the link of the requirements? Thanks!

**Comment by storm9c1** [comment]
> I don't think so, but can you send the link of the requirements? Thanks!

I already closed the banner by pressing the "X". 

But I did click on that link and was put off by it since it was all Windows talk.

Looking in my browser history, this may be the link but I am not 100% sure.  Sorry.

https://learn.microsoft.com/en-us/microsoftteams/new-teams-deploy-using-policies?tabs=teams-admin-center#prerequisites

**Comment by storm9c1** [comment]
I guess my concern is the "update your browser to meet requirements" part.  Feels like MS is doing some type of browser check and displaying that banner?  Will teams-for-linux continue to work after the deadline?

**Comment by Zahrun** [comment]
Well v2 is already working in teams-for-linux (apart maybe for custom backgrounds) with only a small tweak to activate it, so I’d say yes, it will continue to work. Only have to update everyone to v2 by March 31st. I imagine that change will come in a teams-for-linux release by then.

**Comment by storm9c1** [comment]
> I imagine that change will come in a teams-for-linux release by then.

And that's the concern, because it wasn't clear if it was known we had a deadline. `:-)`
Thanks!

**Comment by Cybso** [comment]
Does the availability detection work for anyone in v2? In my case it always changes to absent after a few minutes if the window does not have the focus.

**Comment by woernsn** [comment]
> Does the availability detection work for anyone in v2? In my case it always changes to absent after a few minutes if the window does not have the focus.

No, I have the same behavior - if focus is lost for some minutes, the status is set to absent.

**Comment by jijojosephk** [comment]
This automatic away/absent was fixed by tweaking `angular` code. Since the new one is all about `react` it would be a bug. But I'm still seeing the v1 of the webapp. I don't know when the org will switch to new. If someone else having the new version they can probably debug.

**Comment by Cybso** [comment]
> This automatic away/absent was fixed by tweaking `angular` code. Since the new one is all about `react` it would be a bug. But I'm still seeing the v1 of the webapp. I don't know when the org will switch to new. If someone else having the new version they can probably debug.

Have you tried to use `window.localStorage.setItem("tmp.isOptedIntoT2Web", true)` in Console after starting teams-for-linux with the `´--webDebug` parameter?

**Comment by Cybso** [comment]
> > No, I have the same behavior - if focus is lost for some minutes, the status is set to absent.
> 
> I don't like how that sounds. For example, managers may think I'm not working. Will there be an override for this? Somehow?

The raw progressive web app suffers from the same flaw, even with Microsoft Edge for Linux. So don't worry about this.  For me the main issue is that I get thrown out from telephone queues when I'm away and don't see our support calls :-)

**Comment by jijojosephk** [comment]
> > This automatic away/absent was fixed by tweaking `angular` code. Since the new one is all about `react` it would be a bug. But I'm still seeing the v1 of the webapp. I don't know when the org will switch to new. If someone else having the new version they can probably debug.
> 
> Have you tried to use `window.localStorage.setItem("tmp.isOptedIntoT2Web", true)` in Console after starting teams-for-linux with the `´--webDebug` parameter?

I'll try that. Thanks!

**Comment by jijojosephk** [comment]
@Cybso thanks, I did try that and it switched to v2. But I can say that though the app would continue to work, many tweaks we did in the past would not and we can expect a lot of issues raised :laughing: I don't think easy like how it was with `angular`.

**Comment by ChristoSnake** [comment]
> > So far seems to work fine, except that the icon in the tray now permanently shows one unread notification.
> My tray icon doesn't show unread notifications..

My tray icon stopped displaying any notifications whatsoever, and from the above quotes it seems that its behaviour is somewhat unpredictable at present.  Is this part of the "New Teams" behaviour, or should I be looking for an issue with my distro/desktop/etc?

It's easier to glance at the taskbar to see if I missed anything when returning from a break than opening the app...

Teams for Linux: v1.4.10 rpm (not sure there were any possible fixes in 1.4.12?)
Operating System: openSUSE Tumbleweed 20240216
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.7.4-1-default (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-3740QM CPU @ 2.70GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4000

**Comment by woernsn** [comment]
> My tray icon stopped displaying any notifications whatsoever, and from the above quotes it seems that its behaviour is somewhat unpredictable at present. Is this part of the "New Teams" behaviour, or should I be looking for an issue with my distro/desktop/etc?
> 

It's the same for me. I guess, it is one of the many missing features with the "New" Teams at the moment.

**Comment by IsmaelMartinez** [comment]
The tray icon might be still using the "angular" hack that will need to be
reimplemented in react. (ms is moving from one to the other).

**Comment by jijojosephk** [comment]
@ChristoSnake many of the features we added were solely dependent on `angular` based MS -Teams. But in new it's all `react`. Though the app would continue to work many such features will be broken. Is it a bug? yes. But we can't really fix it immediately until we figure out how the react code works.

**Comment by julian-alarcon** [comment]
This is a question, but you are right, multiple bugs will show up related to the change. Maybe we can set a new label to the bugs related to the new behavior (react instead of angular).

**Comment by rlees85** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/issues/1129

Anyone else using new Teams with this found a huge memory leak/core dumps after using for a while on a busy server?

**Comment by geckolinux** [comment]
I just got a notification from the IT Department that Classic Teams will soon stop working after July 1, 2024. But I don't see any banner or toggle to switch to the new version. I assume that Microsoft will do a progressive rollout for different user accounts, or will I have to do something manually in teams-for-linux to switch to v2?

And regarding v2, what is the current list of limitations with v2 on teams-for-linux?

Huge thanks to the teams-for-linux devs for taking on this massive task of doing the job that Microsoft should be doing.

**Comment by woernsn** [comment]
> I just got a notification from the IT Department that Classic Teams will stop working after July 1, 2024. But I don't see any banner or toggle to switch to the new version. I assume that Microsoft will do a progressive rollout for different user accounts, or will I have to do something manually in teams-for-linux to switch to v2?

See https://github.com/IsmaelMartinez/teams-for-linux/issues/1006#issuecomment-1895555921
This is still working for me.

**Comment by storm9c1** [comment]
Today I've noticed that Teams for Linux now shows the "Try the new Teams" switch at the top left.  That's interesting.

Also based on this thread, it seems like some people/orgs are being forced to v2 at different times.  My company is still making the switch March 31, 2024.  I'm uneasy because it's already a struggle to get Teams and Outlook notifications these days.  Unrelated to TfL: I just switched to (trying) Outlook on Firefox since notifications seem suddenly broken in Outlook on Chromium.  Frustrating to miss meetings due to lack of reliable meeting notifications all around.

**Comment by Cybso** [comment]
As far as it concerns Outlook, have a look at Evolution. It has excellent EWS support for Mail, Calendar and Contacts

**Comment by storm9c1** [comment]
Thanks for the updates.  I've been trying out v2 for the past few days since the toggle switch appeared for me.

Can't say I love it.  It crashes daily (Ubuntu 22.04 snap, with 32GB of RAM), as others have mentioned (#1129).  Likely due to the memory issues (already known and discussed).  I just upgraded to 1.4.14 today.  We'll see if that helps.

So far I'm using it in a separate VM for testing.  I haven't yet tried to do any heavy lifting with it (no actual meetings yet, no screen sharing, no phone calls, just using it for chats so far).  Been using v1 in my primary session since stability is required for my full-time job.  I've been tempted to try out the PWA again.  But I believe in this TfL project and I'm staying loyal.

I'm an old school Unix/Linux guy who does specialized work.  I'm a depth guy, not a breadth guy.  Which unfortunately means I'm not up on angular/react JS code, and already have trouble with work/life balance, so I'm sorry that I can't contribute by learning any of that right now.  But thanks everyone for all the hard work.  Much appreciated that the TfL option even exists!  If you need me to do any testing, let me know.  Thanks.

**Comment by IsmaelMartinez** [comment]
@storm9c1 , can you try snap edge? (or [v1.4.15](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.15) pre-release? I have added some small logic to stop trying to get the electron instance every few seconds. Hopefully that reduces the memory issues.

**Comment by storm9c1** [comment]
> @storm9c1 , can you try snap edge? (or [v1.4.15](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.15) pre-release? I have added some small logic to stop trying to get the electron instance every few seconds. Hopefully that reduces the memory issues.

Sure, just did that now.  I'm done working for the weekend, but will leave it running and see if it holds up through Monday.

I'd leave v1 run for weeks straight with no crashes, only restarting when I got trapped in a login loop or after a snap refresh.

**Comment by IsmaelMartinez** [comment]
There might be more leaks, but having a recurring call to a function forever tends to add up. That part should hopefully be sorted as we now bail out after 5 tries.

**Comment by IsmaelMartinez** [comment]
Ok, I just had a quick look in teams v2 and it looks like they are still using angular, what means things should still work as before, but maybe they are moving people to react in batches (behind feature flags) and I am still in their "old" angular teams v2.

**Comment by storm9c1** [comment]
> > @storm9c1 , can you try snap edge? (or [v1.4.15](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.15) pre-release? I have added some small logic to stop trying to get the electron instance every few seconds. Hopefully that reduces the memory issues.
> 
> Sure, just did that now. I'm done working for the weekend, but will leave it running all weekend in the VM and see if it holds up through Monday.
> 
> Previously (for comparison) I'd leave v1 run for weeks straight with no crashes, only restarting when I got trapped in a login loop or after a snap refresh. Even more contrast, the defunct "Teams Insiders" app on Linux direct from Microsoft was even more stable. I'd leave it running for months, not even getting forcibly logged out! I miss those days.

Update: my session didn't crash all weekend.  Also notable, my session also stayed logged in all weekend.  Didn't throw back into the "Can you please sign in again?" page.  That's a first.

**Comment by IsmaelMartinez** [comment]
Looks like the theme preferences stuff in under:

```
document.getElementById('app')._reactRootContainer._internalRoot?.current?.updateQueue?.baseState?.element?.props.coreServices.clientPreferences.clientPreferences
```

That should fix the "theme" and I suspect some "settings" will be around that area.

<img width="1430" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/faa0a861-05d5-4385-ac99-a016c0257bf6">


> I had a wee look at "what can be affected" and there are a few areas:
> 
>     * [activityHub.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/activityHub.js) will not work once angular is gone. That does, quite a lot including incoming calls status, activities count updated, meeting started, change of status, setting the title, pretending we are running on windows, calendar events... and really a lot of thing I didn't know we where doing. So this will take some time and require some HELP!! But we will get there.
> 
>     * [customBackgrounds.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/customBackgrounds.js): custom background functionality ain't gonna work until we move away from angular
> 
>     * [instance.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/instance.js) will not work. We probably can refactor it out.
> 
>     * [settings.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/settings.js) is also broken.
> 
>     * [theme.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/theme.js) is also kaput. so the follow dark of light theme will need a tweak. (this might be a small job)
> 
> 
> The positives:
> 
>     * [chromeApi.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/chromeApi.js) the video calls should work as well as the [disableAutogain.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/disableAutogain.js)
> 
>     * [shortcuts.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/shortcuts.js) should also still working.
> 
>     * [trayIconChooser.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/trayIconChooser.js) and [trayIconRenderer.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/trayIconRenderer.js) should still work.
> 
>     * [wakeLock](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/wakeLock.js) and [zoom.js](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/zoom.js) functionalities should still be working.
> 
> 
> So quite a bit of work but I think the essential and some extras should be working. I will see first if having that effectively dead code might be creating problems with memory and see if we can, at least, start by fixing that part.

**Comment by jkrysakowski** [comment]
@IsmaelMartinez 

I see that I can access the new version of Teams by entering this address: https://teams.cloud.microsoft/
Is it possible to switch teams-for-linux to wrap this version?

**Comment by IsmaelMartinez** [comment]
You can use the config option (URL) either as a command line option or ina config file. Check the config section (there is a readme)

**Comment by jkrysakowski** [comment]
Thanks, it works, but I see some first problems, for example Join button in the calendar does not work.

Error in the console:

```
Unhandled error/rejection {"isTrusted":true}
(index):3
```

**Comment by IsmaelMartinez** [comment]
Can you open another issue with as much detail as possible? It is nearly
impossible to track multiple issues in one issue. I will probably close
this issue and we can start tackling them individually. Ta

**Comment by jkrysakowski** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/issues/1162

**Comment by IsmaelMartinez** [comment]
I am going to convert this into a conversation
