### ISSUE TITLE
Error when opening Teams for Linux when using "--proxy-pac-url" or "--proxyServer" command line option

### ISSUE THREAD

**Issue by guerini** [IsmaelMartinez/teams-for-linux#1010]
**Describe the bug**
When using one of the two command line options "--proxy-pac-url" or "--proxyServer" Teams for Linux shows an error message (please see screenshot below). Clicking on OK button closes the window and then Teams for Linux asks login/password for proxy and runs normally

**To Reproduce**
1. Run comand "teams-for-linux --proxy-pac-url=http://xxx.yyy.zzz/wpad_fsp.pac
2. Popup window appears with the error message
3. Click on OK
4. Provide Login/password for the proxy

**Expected behavior**
Not showing the error message window

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/1402982/3e2a8b87-4cb4-443f-b570-a74a08365dbf)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Installation package: deb
 - Version 1.3.19 (problem occurs since 1.3.14 I think)

**Additional context**

**Comment by IsmaelMartinez** [comment]
can you check if this is still a problem in 1.4.1? Might be related to the electron version bump around 1.3.11

**Comment by guerini** [comment]
Same problem with 1.4.1:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/1402982/c84d6b9e-c436-424e-a34f-17555b9b2dc9)

**Comment by IsmaelMartinez** [comment]
I wonder if that proxy configuration has changed how it works in electron since the version upgrade around 1.3.11

**Comment by IsmaelMartinez** [comment]
have you been able to dig around latest electron changes around that area? That is the only think I can think of.

**Comment by guerini** [comment]
Command line option "--proxyServer" is now "--proxy-server" but it causes the same error message

**Comment by IsmaelMartinez** [comment]
in 1.3.14 we increased the version of electron to 27.0.0 (from 24.8.5)

I have check the open/close issues since then, and I can't see anything related to this. I have also check the Breaking changes and I can't see anything around this.

I will see if I find something in https://github.com/electron/electron/compare/v27.0.0...v24.8.5 ...

**Comment by IsmaelMartinez** [comment]
This seems related https://github.com/electron/electron/issues/39773 but is a closed issue, and this other one https://github.com/electron/electron/issues/24948. 

I really think this is an electron issue and/or configuration. Hope helps!

**Comment by IsmaelMartinez** [comment]
Closed due inactivity
