### ISSUE TITLE
Teams-for-linux not starting on Ubuntu 22.04.3 LTS 

### ISSUE THREAD

**Issue by ewen-r** [IsmaelMartinez/teams-for-linux#1011]
**Describe the bug**
Teams-for-linux not starting on Ubuntu 22.04.3 LTS 

**To Reproduce**
1. teams-for-linux is in my startup programs
2. No application window is seen.
3. Starting from command line produces no output and still no application window is seen.
4. Uninstall and re-install was required to start the application.
5. This has happened now on 2 consecutive days. 

**Expected behavior**
Application should start or provide output to assist debugging reason for failure.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Ubuntu 22.04.3 LTS 
 - Installation package snap
 - Version 1.3.19

**Additional context**

**Comment by nudgegoonies** [comment]
I am using Debian 12 and debian package of Version 1.3.19. Starts and shows empty window with this message in the console:
```
❯ teams-for-linux 
[224625:1109/152555.224499:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[224625:1109/152555.224579:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[224625:1109/152555.224627:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[224625:1109/152555.224671:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[224625:1109/152555.225025:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[ERROR] net::ERR_CONNECTION_REFUSED
```

**Comment by nudgegoonies** [comment]
I had to revert to 1.3.12. This version still works for me. And forget the error messages above. These are also shown on 1.3.12.

**Comment by amenk** [comment]
I upgraded from 1.0.83 to 1.3.19 and it's not starting with

```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Expected double-quoted property name in JSON at position 43
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/opt/teams-for-linux/resources/app.asar/node_modules/conf/dist/source/index.js:67:43)
    at get store [as store] (/opt/teams-for-linux/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
    at new Conf (/opt/teams-for-linux/resources/app.asar/node_modules/conf/dist/source/index.js:131:32)
    at new ElectronStore (/opt/teams-for-linux/resources/app.asar/node_modules/electron-store/index.js:69:3)
    at new AppConfiguration (/opt/teams-for-linux/resources/app.asar/app/appConfiguration/index.js:15:49)
    at Object.<anonymous> (/opt/teams-for-linux/resources/app.asar/app/index.js:15:19)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1296:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

Is that message more helpful?

Reverting to 1.0.83 worked.
Reverting to 1.3.12 did also not work for me. If it is helpful I can try to identify the exact version which does not work for me anymore.

**Comment by IsmaelMartinez** [comment]
Hi @ewen-r , did you get it working? Can you try using something else rather than snap? Like with flathub, it can be a bit temperamental

@nudgegoonies and @amenk, that is strange. I do suspect maybe some config options have changed (or user agent). Check if the following instructions are still valid and/or help:

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#blank-page

**Comment by jijojosephk** [comment]
> I upgraded from 1.0.83 to 1.3.19 and it's not starting with
> 
> ```
> A JavaScript error occurred in the main process
> Uncaught Exception:
> SyntaxError: Expected double-quoted property name in JSON at position 43
>     at JSON.parse (<anonymous>)
>     at Conf._deserialize (/opt/teams-for-linux/resources/app.asar/node_modules/conf/dist/source/index.js:67:43)
>     at get store [as store] (/opt/teams-for-linux/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
>     at new Conf (/opt/teams-for-linux/resources/app.asar/node_modules/conf/dist/source/index.js:131:32)
>     at new ElectronStore (/opt/teams-for-linux/resources/app.asar/node_modules/electron-store/index.js:69:3)
>     at new AppConfiguration (/opt/teams-for-linux/resources/app.asar/app/appConfiguration/index.js:15:49)
>     at Object.<anonymous> (/opt/teams-for-linux/resources/app.asar/app/index.js:15:19)
>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1296:10)
>     at Module.load (node:internal/modules/cjs/loader:1096:32)
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> ```
> 
> Is that message more helpful?
> 
> Reverting to 1.0.83 worked.
> Reverting to 1.3.12 did also not work for me. If it is helpful I can try to identify the exact version which does not work for me anymore.

Can you share your `settings.json`

**Comment by ewen-r** [comment]
Thanks for the reply. For now I have decided to go with the PWA.

**Comment by jijojosephk** [comment]
@ewen-r I would suggest you to use either `flatpak` or other native package.

**Comment by IsmaelMartinez** [comment]
I will leave it open until @amenk and @nudgegoonies reply, but otherwise close it.

**Comment by amenk** [comment]
@IsmaelMartinez I had the following config.json present:

```
{
	"enableDesktopNotificationsHack": true,
}
```

After deleting it, teams works well with teams-for-linux_1.3.20_amd64.deb

I did not have / need to delete the application cache folder.

Thank you very much.

**Comment by jijojosephk** [comment]
I think the `,` after `true` was causing the crash with the library.

**Comment by IsmaelMartinez** [comment]
@nudgegoonies I think your problem is the other "wayland" issue, so I will close this one. TLDR, some electron problem means this app doesn't work in wayland. electron 28 might have a solution for it.

**Comment by nudgegoonies** [comment]
Sorry, for the delay, i was ill.
I use MATE Desktop and thus Xorg and not Wayland.
I have no config.json file.
Removing Application Cache and also completely removing ~/.config/teams-for-linux does not help.

**Comment by IsmaelMartinez** [comment]
@nudgegoonies , that reads like a different issue. Can you check if it isn't any of the already opened issues and/or create a new one following the template? Thanks
