### ISSUE TITLE
MS Teams Avatars support?

### ISSUE THREAD

**Issue by erkexzcx** [IsmaelMartinez/teams-for-linux#1012]
Hello,

MS Teams has introduced avatars: https://support.microsoft.com/en-us/office/join-a-meeting-as-an-avatar-in-microsoft-teams-5384e7b7-30c7-4bcb-8065-0c9e830cc8ad

I am able to "install" Avatars app to MS Teams and create an avatar, but there is no way I can use it.

I assume it should look like this:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/5955795/62aea6fe-7481-4974-a4a6-11bc7d02bd4f)

But I see this:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/5955795/ec31c61b-18ce-46a0-9f05-1d9a16ca5c76)

Is it limitation and not available in web-version of MS Teams?

**Comment by IsmaelMartinez** [comment]
yeah, sorry but we are only wrapping around the web version. Thanks for reporting and checking.
