### ISSUE TITLE
Custom CSS does not work for Teams v2

### ISSUE THREAD

**Issue by Tasssadar** [IsmaelMartinez/teams-for-linux#1013]
**Describe the bug**
The --customCssLocation loading does not work for the new Teams version.

**To Reproduce**
1. Start teams with `--customCSSLocation` with some css
2. The custom CSS that works in Edge with the Stylus extension does nothing in teams-on-linux.

**Expected behavior**
Custom CSS is applied.

**Desktop (please complete the following information):**
 - OS: Linux
 - Installation package: deb
 - Version 1.3.19

**Additional context**
The problem is with v2 only, and I have updated my css for v2 teams - the problem seems to be that v2 teams use `iframe`, and the `webContents.insertCss` does not work for it.

I have tried to call the insertCSS for frame's webContents in various ways but none if it worked, so I have done this on my local PC, but it's rather ugly and I assume that you don't want this as PR:

```diff
diff --git a/app/mainAppWindow/index.js b/app/mainAppWindow/index.js
index 40447dd..67a0127 100644
--- a/app/mainAppWindow/index.js
+++ b/app/mainAppWindow/index.js
@@ -1,5 +1,16 @@
 require('@electron/remote/main').initialize();
-const { shell, BrowserWindow, ipcMain, app, session, nativeTheme, powerSaveBlocker, dialog } = require('electron');
+const {
+  shell,
+  BrowserWindow,
+  ipcMain,
+  app,
+  session,
+  nativeTheme,
+  powerSaveBlocker,
+  dialog,
+  webContents,
+  webFrameMain,
+} = require("electron");
 const isDarkMode = nativeTheme.shouldUseDarkColors;
 const windowStateKeeper = require('electron-window-state');
 const path = require('path');
@@ -298,6 +309,24 @@ function addEventHandlers() {
        window.webContents.session.webRequest.onBeforeSendHeaders(getWebRequestFilterFromURL(), onBeforeSendHeadersHandler);
        login.handleLoginDialogTry(window);
        window.webContents.on('did-finish-load', onDidFinishLoad);
+
+       window.webContents.on("did-frame-finish-load", (event, isMain, frameProcessId, frameRoutingId) => {
+               const wf = webFrameMain.fromId(frameProcessId, frameRoutingId);
+
+               const fs = require("fs");
+
+               fs.readFile(config.customCSSLocation, "utf-8", (error, data) => {
+                       if (!error) {
+                               wf.executeJavaScript(`
+                                       var style = document.createElement('style');
+                                       style.innerHTML = \u0060${data}\u0060;
+                                       document.head.appendChild(style);
+                               `);
+                       }
+               });
+       });
        window.on('closed', onWindowClosed);
        window.webContents.addListener('before-input-event', onBeforeInput);
 }
```

**Comment by amenk** [comment]
Out of curiosity: How to switch to teams v2 / see which teams version is in use?

**Comment by Tasssadar** [comment]
It's a server-side switch it seems, one day Teams simply looked different. I don't know if there is version specified somewhere, but for example the top right corner looks differently in V2:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/120108/7ba3d500-979e-40f7-8468-f6a4ffd1d163)

**Comment by IsmaelMartinez** [comment]
Hi @Tasssadar , I think that is a valid PR. Unfortunately MS doesn't really help around here, so we have to come with workarounds for making things work. 

As long as that insertCss is behind the `customCSSLocation` and/or `customCSSName` (as shown in https://github.com/IsmaelMartinez/teams-for-linux/blob/32c5ddcd91891a40b6f608d22818d7f34c6581c0/app/customCSS/index.js#L10) then is fine. 

Default should be not to apply either, so `customCSSLocation` and `customCSSName` should still be empty, and the code should live around this area https://github.com/IsmaelMartinez/teams-for-linux/blob/32c5ddcd91891a40b6f608d22818d7f34c6581c0/app/customCSS/index.js

Thanks for reporting and also for providing a solution!

**Comment by Tasssadar** [comment]
Okay, I cleaned it up and submitted in #1017

**Comment by IsmaelMartinez** [comment]
released in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.20. Thanks again for the contribution!
