### ISSUE TITLE
Can not revert entering wrong email address

### ISSUE THREAD

**Issue by ErikOrjehag** [IsmaelMartinez/teams-for-linux#1018]
**Is your feature request related to a problem? Please describe.**
When I enter an email address and get directed to the next step to enter the password there is no way to go back and change the email address. Actually, sometimes there is a back button to the left of the email address that takes you back to change it, but if I input for example "asdasd" there is not back button.

**Describe the solution you'd like**
Not sure... Maybe a button to clear the browser cache and refresh the page (maybe in the activities meny?).

**Describe alternatives you've considered**
Un-install and reinstall did not work. `rm -rf ~/.config/teams-for-linux` did work.

**Additional context**

**Comment by jijojosephk** [comment]
How does it behave on regular browsers?

**Comment by IsmaelMartinez** [comment]
I think you can clean the cache from the taskbar menu. I think is called "Clear Storage"

**Comment by ErikOrjehag** [comment]
> I think you can clean the cache from the taskbar menu. I think is called "Clear Storage"

Ah thank you, on ubuntu 22.04 i found it by `teams icon in task bar menu > Quit > Clear Storage`. It solved my problem, but not so easy to find
