### ISSUE TITLE
Question: connect to Lync?

### ISSUE THREAD

**Issue by denvist** [IsmaelMartinez/teams-for-linux#102]
Hello!

I have a question: is it possible teams-for-linux connect to selfhosted LyncServer (Skype4Business)?

Reason: i'm looking alternative lync-client for linux users.

**Comment by IsmaelMartinez** [comment]
I don't think so, This is an electron wrapper (so website wrapper). 

Check in the MS uservoice page to see if there is anything for you. 
https://microsoftteams.uservoice.com/forums/555103-public?query=lync

Hope helps
