### ISSUE TITLE
Enable cookieEncryption fuse for electron

### ISSUE THREAD

**Issue by anguswilliams** [IsmaelMartinez/teams-for-linux#1021]
**Is your feature request related to a problem? Please describe.**

At the moment, cookies for teams-for-linux (access tokens etc) are stored in plain-text in a sqllite db on disk, this is the default for electron.

**Describe the solution you'd like**

Enable the cookieEncryption fuse to make use of the built-in cookie encryption option.

https://www.electronjs.org/docs/latest/tutorial/fuses#cookieencryption

**Additional context**

The official MS Teams client had similar issues, which have since been mitigated.

https://www.vectra.ai/blog/undermining-microsoft-teams-security-by-mining-tokens

**Comment by IsmaelMartinez** [comment]
Hi @anguswilliams , thanks for your feature request. 

I would invite you to create an MR and we can help you get it over the line. Thanks again!

**Comment by anguswilliams** [comment]
Thanks @IsmaelMartinez, pull request submitted!

**Comment by IsmaelMartinez** [comment]
pre-released in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.23.  Thanks for your contribution! 

I wonder if this will require cleaning the cache of applications, but we will see this if people start complaining.
