### ISSUE TITLE
System audio devices list differs from Teams list

### ISSUE THREAD

**Issue by AndreaRicchi** [IsmaelMartinez/teams-for-linux#1024]
**Describe the bug**
The list of supported input/output audio devices differs from the one shown in the OS.

**Expected behaviour**
Lists should match.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64
 - Installation package: **flatpak**
 - v1.3.19

https://github.com/IsmaelMartinez/teams-for-linux/assets/17642033/eb1b1be2-71f4-4dda-8122-1a3e538ff801

**Comment by IsmaelMartinez** [comment]
Hi @AndreaRicchi , can you check if you get that seams devices:

* Login into teams using the chrome(ium) browser.
* Using a deb, rpm or other package. 

Thanks

**Comment by AndreaRicchi** [comment]
Thanks for the reply @IsmaelMartinez.

Also on the browser, I have the same issue. :disappointed:

**Comment by IsmaelMartinez** [comment]
I suspect then is either MS (https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472) or Chromium. I would 1st check in the MS feedback portal to see if there is anything there. I leave it open in case you find something. Good luck!
