### ISSUE TITLE
Enhanced second_ringer.sh script for Linux and MacOS

### ISSUE THREAD

**Issue by holle** [IsmaelMartinez/teams-for-linux#1025]
This is a solution (for me) that solves the problem of Teams not ringing audible when earphones are plugged in.
My suggestion is based on the example from @93Sprinter, that was included in the release notes of version 1.3.21.

Here is my alternative script "second_ringer.sh" for use under Linux:
```bash
#!/bin/bash
export PULSE_SINK=1
/usr/bin/cvlc --play-and-exit --aout --intf=rc /usr/share/sounds/Oxygen-Im-Phone-Ring.ogg
```
This works under MacOS Sonoma for me, builtin speakers, homebrew under/usr/loca on a Intel Mac, may need tweaking with different headphones and/or installations:
```bash
#!/bin/bash
# alternative path: /Applications/VLC.app/Contents/MacOS/VLC
# alternative path (brew M1/M2/M3): /opt/homebrew/bin/vlc
/usr/local/bin/vlc --play-and-exit --aout --intf=rc <your path to the soundfile>/Oxygen-Im-Phone-Ring.ogg
```

Explanations (Linux):

1. I have to user PULSE_SINK=1 since my speaker shows up as device 1 and my headset as device 0, ymmv
   * run `pacmd list-sinks` to determine you outputs
2. Switched from vlc to cvlc which is the CLI variant and does not open any window
3. Added the play and exit parameter in order to make vlc quit after playing the sound
4. My desktop environment is KDE Plasma 5 thus I can rely on already installed sound files, ymmv ;-)

Cheers,
Holger

**Comment by Cybso** [comment]
Here's a Pipewire variant for this:

```
paplay -d DEVICE_NAME /usr/share/sounds/Oxygen-Im-Phone-Ring.ogg
```

You can list the available device names with pactl:

```
pactl list sinks | grep -A1 "Name: "
```

**Comment by holle** [comment]
Hi @Cybso,

I can confirm, this also works for me under Linux + Plasma5 + KDE, nice tip, thanks

**Comment by IsmaelMartinez** [comment]
Can we check if this still works in 1.4.1 ? We have tidy up a bit that area and increase the version of electron, but I don't have a way to test it myself. Thanks!

**Comment by Cybso** [comment]
Tested it with 1.4.1, still works
