### ISSUE TITLE
Blurry window when using wayland with integer scaling

### ISSUE THREAD

**Issue by bfsgr** [IsmaelMartinez/teams-for-linux#1027]
**Describe the bug**
Recently chrome introduced a [new feature that enables fractional scaling on wayland](https://bugs.chromium.org/p/chromium/issues/detail?id=1356014), however that features makes windows appear blurry on integer scaled screens. To fix this we can use the disable-features switch with WaylandFractionalScaleV1.
However the application does not allow for arbitrary values in the --disable-features switch, therefore I'm stuck with a blurry teams since version 1.3.14.

**To Reproduce**
1. If you use gnome, disable 'scale-monitor-framebuffer' experimental feature
2. Set your screen to use an integer scale bigger than 1
3. Open teams
4. You should get a blurry window

**Expected behavior**
You should be able to pass custom flags to --disable-features, allowing to disable WaylandFractionalScaleV1

**Screenshots**
Blurry window at 200% scale in a 4k monitor
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/38868063/ed597f81-9ecc-415b-bf0c-bdaeeded6659)

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Installation package: flatpak
 - Version 1.3.23

**Comment by bfsgr** [comment]
I submitted a PR allowing custom disable-features which makes me able to disable WaylandFractionalScaleV1 and get a correctly scaled window again

Before:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/38868063/fcc8e25e-3960-4da4-a36f-fa24caa57c97)

After:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/38868063/5e3407f7-df16-4cc0-a62f-40ebb2bfbeb5)

**Comment by IsmaelMartinez** [comment]
Fixed in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.24
