### ISSUE TITLE
Vaapi video acceleration?

### ISSUE THREAD

**Issue by AlfaSierra92** [IsmaelMartinez/teams-for-linux#1029]
Is it possible to enable vaapi acceleration for videos which are supported by vaapi engine on the current system? I have already enabled it on chromium powered browsers such as Brave or Chrome.

**Comment by IsmaelMartinez** [comment]
you should be able to pass the same command tools to it than to brave/chrome. Do share here the command if you get it running but, yeah, it should be possible.

**Comment by AlfaSierra92** [comment]
I have tried the same command line parameters and they works.
`--ignore-gpu-blocklist --enable-features=VaapiVideoDecoder,VaapiVideoEncoder,VaapiVideoDecodeLinuxGL,VaapiIgnoreDriverChecks`
You have to consider that these parameters could work only in some hardware configurations (GPU Intel 620).

**Comment by IsmaelMartinez** [comment]
closing as completed
