### ISSUE TITLE
Teams debian package does not start on Debian 11 since Version 1.3.13

### ISSUE THREAD

**Issue by nudgegoonies** [IsmaelMartinez/teams-for-linux#1035]
**Describe the bug**
An empty window opens with window title "Teams for Linux".
With parameters `--webDebug --disableGpu --appLogLevels debug` it gets a bit further and the window title shows "Checking Credentials" and then "Sign in with your account" but the window is still empty all the time. This is the console output:
```
[DEBUG] configPath:,/home/awirooks/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[DEBUG] Fetching custom background configuration from 'http://localhost/config.json'
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--webDebug,--disableGpu,--appLogLevels,debug
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
[DEBUG] Spellchecker is disabled!
[182861:1201/111756.294107:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[182861:1201/111756.294168:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[182861:1201/111756.294204:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[182861:1201/111756.294239:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[182861:1201/111756.294574:ERROR:browser_main_loop.cc(275)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[DEBUG] Network test successful with method https
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] did-frame-finish-load,[object Object],false
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 3s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 13s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 23s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 33s, IdleState: 'active'
Lots of those with higher idle times until i quit after several minutes waiting:
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] window close
[DEBUG] window closed
[DEBUG] before-quit
[DEBUG] will-quit
[DEBUG] quit
```

**To Reproduce**
Start teams-for-linux, all config removed beforehand with the parameters above.

**Expected behavior**
Starts and shows login like 1.3.12 which i have to use because all higher versions until 1.3.23 crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Installation package deb
 - Version 1.3.13-1.3.23

**Additional context**

**Comment by RolandRosenfeld** [comment]
For me that 1.3.22 Debian package works without problems on Debian 11 (and Debian 12).
I still have the classic version enabled and I use X11.
I do not use --disableGpu (no problems with Intel onboard graphics).

**Comment by nudgegoonies** [comment]
Thank you for the feedback. I am now on Debian 12 with X11. Same issue. I use an integrated intel too.
@RolandRosenfeld What do you mean with classic version enabled?

**Comment by IsmaelMartinez** [comment]
Hi all, I have been noticing teams (in official client in macos) taking a long time to open (like a few minutes). This might be the same problem we are experiencing here. I tend to see also a long delay in meetings. I can hear the other end but video takes a looooong time to appear. TL;DR this might be unrelated and maybe just a Microsoft problem. Let us know more details to see if it is the same problem

**Comment by IsmaelMartinez** [comment]
can you try the pre-release 1.4.1? Thanks!

**Comment by jmergy** [comment]
Was also unable to launch it in Debian 12.x on XFCE but after pre-release 1.4.1 I'm okay. Thank you.

**Comment by nudgegoonies** [comment]
Sorry for the late reply. I can confirm with kernel package linux-image-6.1.0-17-amd64 version 6.1.69-1 the problem is gone for Teams for Linux 1.3.26. So i think the kernel update caused the fix. I had a similar problem with Signal as you can see in the linked issue. Both applications uses Electron/Chromium and maybe Chromium itself had trouble which i cannot confirm, because i use Firefox.

**Comment by IsmaelMartinez** [comment]
closing as complete
