### ISSUE TITLE
Crash when maximize on Wayland

### ISSUE THREAD

**Issue by adro79** [IsmaelMartinez/teams-for-linux#1036]
**Describe the bug**
Teams crashes when maximizing or tiling the window on KDE Wayland, haven't tried other desktop environments.

**To Reproduce**
1. Install teams-for-linux from [AUR](https://aur.archlinux.org/packages/teams-for-linux)
2. Launch teams-for-linux with `--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer`
3. Maximize or Tile the window.
4. `33133 segmentation fault (core dumped)`

**Expected behavior**
Maximize or tile without crashing.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - [AUR Package](https://aur.archlinux.org/packages/teams-for-linux)
 - Version 1.3.22
 - Nvidia RTX 3090

**Comment by herbiejhopkins** [comment]
duplicate of #1001 ?

**Comment by adro79** [comment]
Seems like it is, thanks
