### ISSUE TITLE
Inhibit keyboard shortcuts (via command line flag?)

### ISSUE THREAD

**Issue by r-cdriscoll** [IsmaelMartinez/teams-for-linux#1037]
I had posted this in the teams-for-linux Matrix chat, but it'd be useful if there was a way to prevent the CTRL+SHIFT+C shortcut from calling someone in Teams, as this shortcut is often used by Linux users to copy output in a terminal window.

I've accidentally called co-workers at least a dozen times out of habit of pressing CTRL+SHIFT+C to copy text in a chat rather than CTRL+C :).

I kind of assumed the easiest method might be a command line flag to disable a shortcut?  Maybe something along the lines of this PR https://github.com/IsmaelMartinez/teams-for-linux/pull/1028.

**Comment by IsmaelMartinez** [comment]
I haven't had the time to look into this, but I can understand the annoyance. I will put it as an enhancement and see if someone can pick this up. Thanks!

**Comment by IsmaelMartinez** [comment]
maybe something like in here? https://stackoverflow.com/questions/69348406/disable-all-keyboard-shortcuts-in-electron-js Not sure if you would want all shortcuts disabled or better having a re-mapping shortcuts.

**Comment by IsmaelMartinez** [comment]
This is now possible from version [1.7.2](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.7.2). The config option `disableGlobalShortcuts` provides an array of shortcuts to disable while the app is on focus.

Information on what accelerators you can use can be found in electron https://www.electronjs.org/docs/latest/api/accelerator page.
