### ISSUE TITLE
Zoom setting does not persist between app restarts

### ISSUE THREAD

**Issue by bbascarevic** [IsmaelMartinez/teams-for-linux#1038]
**Describe the bug**
Zoom setting does not persist between app restarts.

**To Reproduce**
1. Change the Zoom level (Ctrl +/- or via the menu).
2. Restart the app.

**Expected behavior**
The zoom level should be restored

**Desktop (please complete the following information):**
 - OS: Linux
 - Installation package: AUR
 - Version: 1.3.22

**Comment by IsmaelMartinez** [comment]
Can you check if this works in 1.3.21? I wonder if this change in 1.3.22 caused the issue https://github.com/IsmaelMartinez/teams-for-linux/issues/987

**Comment by jijojosephk** [comment]
Is it still a problem? I see it's functioning well.
