### ISSUE TITLE
Exception when running second ringer script

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#1039]
When I run my second ringer script I get the following exception n incoming calls:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/17568624/5c981e04-d0ce-41da-8bf9-585da330ad3d)

What is going wrong here?

**Comment by 93Sprinter** [comment]
Hi @elhennig ,
unfortunately you can't use ~ in the Electron child_process.spawn command which is used to execute the command.
You need to use the absolute path to your file.

best regards

**Comment by elhennig** [comment]
Cool! Nice finding and good news as this is very easy to fix ;-)
