### ISSUE TITLE
Ctrl+click to open external link freezes teams main window

### ISSUE THREAD

**Issue by betonetotbo** [IsmaelMartinez/teams-for-linux#1041]
**Describe the bug**
Ctrl+click to open external link freezes teams main window. 

I'm using this feature (ctrl+click) to open team live urls, but when I ctrl+click and allow it to open in same context of teams app, the main window freezes (disables).

**To Reproduce**
1. Open an event in your calendar
2. Expand the event schedule to see details/description
3. The description must has a link to a teams live, example: https://teams.microsoft.com/l/meetup-join/19%3ameeting_Yj......
4. Click on the link pressing ctrl 
5. Teams for linux will ask you to "Allow" open the link in application context, allow it!
6. The main window of "teams for linux" will no more respond to actions like clicks and key presses.
7. I need to close the popup of the live/meetup to be able to interact again with the main window.

**Expected behavior**
I expect that the main window continues to work and responding my inputs. While I'm watching a live/meetup, to be able to respond other chats for example.

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/5444923/ad583c50-5357-4c52-9b2b-87ee28a4657b)

> Ignore the fact in the screenshot that the popup is requesting for my microsoft credentials, at the moment I recorded this screen the live was ended.

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Installation package: snap
 - Version 1.3.10, 1.3.19, 1.3.22, 1.3.24, 1.3.25

**Comment by IsmaelMartinez** [comment]
worth trying with something other than snap and see if you have the same problem. Also with a older version (like 1.3.10 or so) to check it is not electron and/or one of the latest changes.

**Comment by betonetotbo** [comment]
Tested with 1.3.19 from flatpack. Same problem.

**Comment by betonetotbo** [comment]
Also tested with teams-for-linux_1.3.10_amd64.deb, same problem too.

**Comment by IsmaelMartinez** [comment]
another new mayor release. I do not expect to fix it but can you try 1.4.1 ? (is a pre-release). Thanks and hopefully this one does fix it

**Comment by robertoneto-senior** [comment]
1.4.10 , and problem continues.

**Comment by jijojosephk** [comment]
This is how it is designed. You can't have multiple windows opened. CTRL + CLICK is only for handling SSO (Single Sign On). And in the process the parent window is waiting for you to finish the task.
