### ISSUE TITLE
"Stay connected" doesn't work

### ISSUE THREAD

**Issue by Kalytis** [IsmaelMartinez/teams-for-linux#1042]
**Describe the bug**
I select "Stay connected" every time, in order to avoid authentication, but it doesn't work, and upon every app start, it asks my credentials.

**To Reproduce**
1. Connect
2. Click on "Stay connected"
3. Quit the app
4. Start it again.

**Expected behavior**
Logging in automatically

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Installation package : snap
 - Version 1.3.23

**Additional context**
I'm logging in through my organization.

**Comment by IsmaelMartinez** [comment]
Hi, can you try with something else other than snap? it could be the snap sandboxing that is blocking this. Thanks

**Comment by Kalytis** [comment]
Hi @IsmaelMartinez, it seems to be fixed with APT ! Thank you

**Comment by Kalytis** [comment]
Okay, I talked too fast : issue happens again with APT after a PC reboot

**Comment by IsmaelMartinez** [comment]
I suspect this is due your company policy. If you can check how often they force you to re-authenticate that can explain this as not working.

**Comment by Kalytis** [comment]
That's weird, because on my company-provided PC running Win10, auto-connection works perfectly since september

**Comment by IsmaelMartinez** [comment]
I really don't know then. Sorry

**Comment by Kalytis** [comment]
No problem! Thank you for your work, have a nice end of year ✌️
