### ISSUE TITLE
For some time now, you no longer see any notifications under KDE/Plasma

### ISSUE THREAD

**Issue by boospy** [IsmaelMartinez/teams-for-linux#1048]
Hello all, 

for some time now, you no longer see any notifications under KDE/Plasma. Normaly if you geht an message, or you get a call, Plasma show you this with notifications on the bottom right side. But since about 1,5 month this no longer works. This means you have to have Teams open on at least a second screen to see incoming calls, especially if no audio is activated (office).

I use here KDE NEON (based on Ubuntu 22.04). 

Best Regards
Boospy

**Comment by IsmaelMartinez** [comment]
Hi @boospy, I think this is a MS issue as I have the same problem in the official macOS app.

**Comment by boospy** [comment]
> Hi @boospy, I think this is a MS issue as I have the same problem in the official macOS app.

Well, at least it works on Windows devices. Once again, we are probably not so important with other operating systems...

**Comment by IsmaelMartinez** [comment]
actually, this might be duplicated with #937 . I think this changed from version 1.1.11 (electron change) that we can't fix. That issue has some hacks and workarounds. Closing this as duplicated.
