### ISSUE TITLE
quick suggestion re ubuntu install

### ISSUE THREAD

**Issue by jdpipe** [IsmaelMartinez/teams-for-linux#1049]
Some quick suggestions regarding the Ubuntu installation process
(https://github.com/IsmaelMartinez/teams-for-linux#debianubuntu-and-other-derivatives)

```lang=sh
wget -qO - https://repo.teamsforlinux.de/teams-for-linux.asc | sudo apt-key add -
echo "deb [arch=$(dpkg --print-architecture)] https://repo.teamsforlinux.de/debian/ stable main" | sudo tee /etc/apt/sources.list.d/teams-for-linux.list
sudo apt update
sudo apt install teams-for-linux
```
It doesn't seem to be necessary to store the key with a specified filename, because the correct key gets identified automatically.
I thought it might be posible to remove the `dpkg --print-architecture` option as well, but this didn't work, because on my system, it attempts to access an `i386` version of the package. This doesn't seem to happen with other repos, so maybe there is some other config issue on the deb repo server.

**Comment by IsmaelMartinez** [comment]
Thanks for your contribution! You might even be able to create a PR with this changes even using the UI. I don't fully get the second part of the message. Thanks in advance!
