### ISSUE TITLE
Desktop Notification for incoming call not working - Ubuntu 22.04.3/GNOME 42.9/X11 

### ISSUE THREAD

**Issue by KKomara62** [IsmaelMartinez/teams-for-linux#1050]
Was using the official Team for Linux from MS
But my company enabled 2FA and now the MS Teams App in Linux makes me log in 15-20 times a day.
Since this app is no longer supported - no hope to get it fixed.

Tried the NEW MS PWA.
This forced me to use Chrome (I use FireFox on Linux)
MS PWA App had same issues with incoming Call Notifications too.  
Plus I hate Chrome and the PWA app is a web app and I just don't like the look and feel.

So I just installed the latest version of Teams for Linux.
Looks AWESOME - looks and feels like the no longer supported MS App for Linux !!

No real bad issue out-of-the-box.
Only thing that does not work is incoming Call notification on the desktop.
I can hear the incoming call ringing.
But no Desktop notification so I can easily answer the call

If I get a call I do the following when I hear the ringing.
I can then select the app
Make it visible
THEN - I see the incoming call message 
THEN I can answer the call.
So call answering from INSIDE the App works fine.

I dug around in the settings a bit - could not get OS notifications to work.
I know there are known issues in this area.
Should this work on my system ?
Can I tweak anything ?

Thanks !!

**Comment by IsmaelMartinez** [comment]
Hi @KKomara62 , it is usually better to use the template when filling up issues. 

This could be related to the new version of MS Teams, I use the official app in macOS and do NOT get notifications, so I am afraid is a MS issue.

**Comment by IsmaelMartinez** [comment]
check this conversation https://github.com/IsmaelMartinez/teams-for-linux/discussions/1019 you might be able to use the same script to trigger the notifications.

**Comment by IsmaelMartinez** [comment]
this is duplicated with #937 and #1019. Please use those instead of this.
