### ISSUE TITLE
Property name failed

### ISSUE THREAD

**Issue by alexbruxel** [IsmaelMartinez/teams-for-linux#1052]
**Describe the bug**

(teams-for-linux:18605): Gtk-WARNING **: 13:18:20.561: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

teams-for-linux release 1.3.27

**To Reproduce**

1. Go to ./teams-for-linux

**Expected behavior**
open team for application ubuntu

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/61985206/21695d09-9097-4fbe-abde-68883422b24e)

**Desktop (please complete the following information):**
 - OS: UBUNTU
 - Installation package snap
 - Version 1:9.18.18-0ubuntu0.22.04.1

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi, can you use another packaging system? that looks like a snap configuration (either in our electron-builder commands or your side)

**Comment by alexbruxel** [comment]
> Hi, can you use another packaging system? that looks like a snap configuration (either in our electron-builder commands or your side)

Sorry, I don't know if I understood you correctly, because of the English.
Do you want me to use another way to install?
I used dkpg with the previous version 1.3.27 and it worked, but the new one doesn't work

**Comment by IsmaelMartinez** [comment]
Version 1.3.27 do not work.

If version 1.3.26 or 1.4.1 works for you within other packaging systems, it suggests an issue with your OS configuration, particularly within the Snap environment. Exploring alternative packaging systems or seeking assistance within the Snap forums might be advisable to address this concern effectively.
