### ISSUE TITLE
teams for linux 1.3.27 does not start

### ISSUE THREAD

**Issue by abysso2** [IsmaelMartinez/teams-for-linux#1053]
**Describe the bug**
teams for linux 1.3.27 does not start

**To Reproduce**
1. start teams-for-liux 1.3.27 via console

**Expected behavior**
teams-for-linux starts

**Additional context**
error message in console:

(node:12969) UnhandledPromiseRejectionWarning: ReferenceError: incomingCallCommandKill is not defined
    at assignEventHandlers (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/index.js:450:45)
    at createWindow (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/index.js:435:2)
    at Object.onAppReady (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/index.js:66:17)
    at App.handleAppReady (/opt/teams-for-linux/resources/app.asar/app/index.js:163:16)
    at App.emit (node:events:514:28)
(Use `teams-for-linux --trace-warnings ...` to show where the warning was created)
(node:12969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[ERROR] net::ERR_CONNECTION_RESET

**Comment by abysso2** [comment]
Btw: 1.3.26 works like a charm..

**Comment by sekurilabs** [comment]
I can confirm. 1.3.27 on Ubuntu 23.10 not starting with an error:
```
(node:7823) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Server returned error code '404'
Warning: terminator_CreateInstance: Failed to CreateInstance in ICD 3.  Skipping ICD.
```

**Comment by IsmaelMartinez** [comment]
ops, I see the error (mainAppWindow). 

PR incomming but I will put it as a pre-release with 1.4.0 (as 1.4.1) to include the electron upgrade.

**Comment by IsmaelMartinez** [comment]
Fixed in https://github.com/IsmaelMartinez/teams-for-linux/pull/1054 . Building

**Comment by IsmaelMartinez** [comment]
can you try in here https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.1 ? Thanks and apologies

**Comment by archenroot** [comment]
@IsmaelMartinez - and for users using ppa repository should we revert back to 1.3.26

**Comment by IsmaelMartinez** [comment]
I think ppa gets whatever is the latest build... so they will be now in 1.4.1. I expect the electron version to NOT break anything but... lets see.

**Comment by archenroot** [comment]
ok, I don't see 1.4.1 in ppa, so downgraded by:
`sudo apt install teams-for-linux=1.3.26` for time being and it works.

**Comment by IsmaelMartinez** [comment]
closing as that release is been marked as broken. 1.3.26 or 1.4.1 should work. Thanks for reporting and apologies for the issue
