### ISSUE TITLE
Cropped screensharing of windows

### ISSUE THREAD

**Issue by qdrop17** [IsmaelMartinez/teams-for-linux#1055]
**Describe the bug**
When sharing a screen from a window using Teams-for-Linux, the displayed view is cropped at the top and bottom. This issue is specific to Teams-for-Linux and does not occur with other applications that utilize the Wayland screen-sharing backend.

**To Reproduce**
1. Share a screen by selecting a window within Teams-for-Linux.

**Expected behavior**
The entire window should be shared without any cropping.

**Screenshots**
Actual window:
![original_window_censored](https://github.com/IsmaelMartinez/teams-for-linux/assets/42340241/a61e598c-3894-4863-a78a-c0f6f12afd0c)

View on Client:
![client_view_censored](https://github.com/IsmaelMartinez/teams-for-linux/assets/42340241/1cf674c4-da8a-4ead-8b1c-b62ff88d931d)

**Host Desktop**
 - OS: Fedora 39 with Gnome and Wayland
 - Installation package: Flathub
 - Version 1.3.19

**Additional observations**
- The issue does not occur when sharing a window through https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/#2653888812629166, despite using the same sharing backend. This suggests that Teams-for-Linux might be cropping the image.
- When the window is made very wide, the entire window can be shared without cropping, indicating a possible relation to the aspect ratio of the shared stream.
- Sharing a 21:9 screen does not present this issue, and this aspect ratio does not cause issues with window sharing either.
- A related issue may be found in this post: [Issue Comment](https://github.com/IsmaelMartinez/teams-for-linux/issues/961#issuecomment-1857139209), where a user mentions a similar cropping problem.

Further debugging information can be provided upon guidance. Any assistance is greatly appreciated.

**Comment by IsmaelMartinez** [comment]
Hi, can you try the latest pre-release version? (1.4.1) I don't think the people in flathub has release this yet.

I think this issue is duplicated by a couple of other issues, but I will leave it open to see what people find out.

**Comment by IsmaelMartinez** [comment]
closing as duplicated with #912
