### ISSUE TITLE
Desktop Stream wrong size

### ISSUE THREAD

**Issue by BlueCase** [IsmaelMartinez/teams-for-linux#1056]
**Describe the bug**
For every type of Screenshare (Monitor, Window only) the receiver get only a 4:3 cutout of my screen (See Screenshot). 
I have a setup with 3 Monitors (See Screenshot)
Only a Problem with teams-for-linux. When I use the the PWA with e.g. Brave the Screenshare work normally.

**To Reproduce**
Share the screen. No special.

**Expected behavior**
Al my Monitors have a resolution of 2560x1440. Ratio for the receiver of the Stream should be correct.

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/784375/9d468b03-0f95-4a7c-80ce-bd8ab8c5823c)
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/784375/f4ab8d36-ad28-475c-9baf-f068576138ba)

**Desktop (please complete the following information):**
- OS - Manjaro
- PKG - Flatpak and AUR Build (Same failure with both)

**Additional context**

**Comment by IsmaelMartinez** [comment]
This is duplicated. Check the open issues
