### ISSUE TITLE
Opening a meeting link logs the user out

### ISSUE THREAD

**Issue by kitserve** [IsmaelMartinez/teams-for-linux#1059]
**Describe the bug**
When logged into Teams, I used to be able to open meeting links, but now when I do so, it tells me that I'm joining as an anonymous user.

**To Reproduce**
1. Open Teams for Linux.
2. Log in.
3. Run a second Teams command, with the https://teams.microsoft.com/l/meetup-join/XXXXXX meeting link as the final argument.
4. Teams for Linux opens its main window and takes me to the meeting, but as an anonymous user. I have to enter a screen name, and when I click Join, someone already in the meeting has to approve my join request. When the meeting is over, I get a generic screen rather than my usual home screen in Teams. I have to quit the application and log in again in order to access chat etc. On the guest join screen, there is a link to sign in, but when I click it, I get a white screen of death.

**Expected behavior**
Previously, Teams for Linux would open its main window and take me straight to the meeting with my currently logged in account. When I left the meeting, I was still logged in.

**Screenshots**
<img width="960" alt="1-NEW-icon-when-opening-meeting-link" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/7717488/65843576-abe4-4c11-9d71-a6584b94bec7">
<img width="960" alt="2-guest-details-prompt-when-joining-meeting" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/7717488/b01aedb6-aa4b-4fa8-af18-77b773f72feb">
<img width="960" alt="3-white-screen-after-clicking-sign-in-link" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/7717488/9c4ef964-36e8-49a0-a86b-deba26046fba">

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Installation package: deb
 - Version: 1.3.26

**Additional context**
Installed via Debian repo per the README instructions. Due to corporate policy, I'm having to run it over a SOCKS5 proxy with the `--proxy-server=` argument. I'm not a part of the corporate group, instead I'm using a personal account that they added as a guest to the organisation.

**Comment by kitserve** [comment]
Ah, that's an interesting thought. Yes, I confirm that logging into Teams in Vivaldi, then opening a separate Vivaldi process from the command line with the meeting link, results in the same behaviour. In that instance I get a new tab for the meeting, but in the new tab I'm logged out, despite being logged in the original tab. Weirdly, if I close the meeting tab, the original tab is still logged in. I've no idea what changed with the corporate policy, but if that's the cause then it's not worth looking into any further. Thanks for looking at this and coming back to me about it.

**Comment by IsmaelMartinez** [comment]
maybe check if you can use certificates for login. That might be able to keep you authenticated when opening a new "tab"

https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config

**Comment by IsmaelMartinez** [comment]
Assumed solved. Closed due inactivity
