### ISSUE TITLE
Desktop sharing isn't supported in your browser...

### ISSUE THREAD

**Issue by avodonosov** [IsmaelMartinez/teams-for-linux#106]
**Describe the bug**
When trying to share the screen, I see the "Desktop sharing isn't supported in your browser..."

**To Reproduce**
1. Join a meeting
2. Try to share the screen
3. See the error

**Expected behavior**
A choice of screens and windows should be presented

**Screenshots**
![image](https://user-images.githubusercontent.com/2444/56049443-29b5ea00-5d52-11e9-84d4-5446d7b6a3fb.png)

**Desktop (please complete the following information):**
 - OS: 
    $ uname -a
    Linux xxxxxxxxxx 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 - Installation package deb
 - Version 0.2.0

**Additional context**
I have successfully used the same version of teams-for-linux on another machine. I thought the teams-for-linux configures the embedded Chrome so that UserAgent and other settings are recognized by Teams code as supported. For some reason that doesn't work in that case.

**Comment by IsmaelMartinez** [comment]
Hi,

The user Agent only to another version of chrome. 

Did that user had a previous version installed? 
Can you clear the `~/.config/teams-for-linux` folder and try again?

I have seen similar occasionally, but tend to go away by stopping the call and starting it again. 

Not really looking into changing/improving much that area as MS itself is planning to add support to it, so not worth the extra effort. Let me know how you get on.

**Comment by IsmaelMartinez** [comment]
Closing, reopen if you still have the issue.

**Comment by avodonosov** [comment]
Thanks for the response.

Removed ~/.config/teams-for-linux, unfortunately, doesn't help, the issue remains.

>  as MS itself is planning to add support to i
Do you have a link? On the forums I saw MS just closed the ticket. People were complaining so MS reopened the ticket, but without any promise to work on it.

**Comment by avodonosov** [comment]
>  reopen if you still have the issue.

There is no button to reopen.

**Comment by IsmaelMartinez** [comment]
I think this is the same as #64 .

Can you try with the argument explain in there? (using another "desktop")

**Comment by IsmaelMartinez** [comment]
Also, I think is the same as #100

**Comment by IsmaelMartinez** [comment]
Closing as it does smell like duplicate.

**Comment by avodonosov** [comment]
The ticket was reported from LXDE. Now I also tried XFCE and Unity - still doesn't work.

At the same time, on another machine screen sharing works OK under LXDE.

**Comment by IsmaelMartinez** [comment]
Can you try running from code? I can only suspect on the delay. Can you try to find differences between the env? Like, does both have cameras?

**Comment by Fmstrat** [comment]
I'm getting this issue now as well in Ubuntu 18.04 with Gnome. It was working fine, I stopped sharing, then when I tried to start again this error started coming up. I can't seem to get around it with any of the recommended fixes (using teams-for-linux_0.4.0_amd64.deb from here in GitHub).

**Comment by rojaro** [comment]
Screensharing worked for me yesterday, but today i also get this message ... running Archlinux and Gnome.

**Comment by IsmaelMartinez** [comment]
@rojaro and @Fmstrat , can you check in #100 as is where the more things we tried. It does smell like system configuration. Also, open another bug issue if you seek more help and reference this old issues.

**Comment by rojaro** [comment]
Tried removing ~/.config/teams-for-linux
Tried building 0.4.0 from code using AUR
Removed package and ran AppImage from release page
Still no success with screensharing :(

**Comment by rojaro** [comment]
FYI ... my configuration has not changed at all. No updated packages, nor reboot. Yesterday it worked, today it doesn't.

**Comment by IsmaelMartinez** [comment]
see #194 . MS has changed something on their side and f###d us
