### ISSUE TITLE
Notifications show the app's icon and not the sender's profile picture

### ISSUE THREAD

**Issue by AchillesBoi** [IsmaelMartinez/teams-for-linux#1060]
**Describe the bug**
When a notification is received, the icon displayed in the notification banner is the Microsoft Teams app icon. Normally, the notification should include the profile picture of the message sender.

**To Reproduce**
1) Receive a message
2) Observe the notification banner

**Expected behavior**
Notification banner should show the sender's profile picture

**Screenshots**
Expected behavior (official PWA):
![Screenshot from 2024-01-05 18-00-32](https://github.com/IsmaelMartinez/teams-for-linux/assets/55808665/09082ed6-dcd2-4bb9-adc7-8aa06ea8c105)

Current behavior (teams-for-linux):
![Screenshot from 2024-01-05 17-59-56](https://github.com/IsmaelMartinez/teams-for-linux/assets/55808665/8f3fbba7-885d-43a1-a4d2-ec1ad2abc348)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 (Ubuntu 22.04.3)
 - Installation package: Flatpak
 - Version 1.3.26

**Additional context**
Thank you for your hard work, you magnificent bastard.

**Comment by IsmaelMartinez** [comment]
This will require a re-work of the notifications to be able to add whatever we want. That might be part of version 2.0 if we ever get there.

**Comment by jijojosephk** [comment]
Thanks @AchillesBoi for reporting. `1.4.6` must have it fixed. Please try when it is released soon.
