### ISSUE TITLE
Webcam stretched with background enabled

### ISSUE THREAD

**Issue by andreacocci95** [IsmaelMartinez/teams-for-linux#1061]
Hi, when I apply a webcam background (blur or some images) I see my image stretched. If nothing is selected my images is ok. How can I solve this problem? Thanks!

**Comment by IsmaelMartinez** [comment]
Can you check if 1.4.3 improve the situation? That area has been reworked in https://github.com/IsmaelMartinez/teams-for-linux/pull/1064 .  pre-release incomming

**Comment by IsmaelMartinez** [comment]
closing this as other people are reporting this to be solved.

**Comment by andreacocci95** [comment]
Tried with 1.4.3 but same problem

**Comment by IsmaelMartinez** [comment]
can you create a new issue using the template? That way we can understand your problem better. 

Opening an issue with a single sentence gives us far too many variables to consider. Thanks
