### ISSUE TITLE
When using the `--appTitle` flag, the app title is not applied to the hover tip in the tray icon

### ISSUE THREAD

**Issue by DeflateAwning** [IsmaelMartinez/teams-for-linux#1062]
**Describe the bug**
When using the multi-tenant capability, as described in [this comment](https://github.com/IsmaelMartinez/teams-for-linux/issues/438#issuecomment-1750270198), the specified app title (provided via the `--appTitle` CLI flag) is not displayed in the hover tip over the tray icon (the item with the right-click menu). 

Related to #438 (multi-tenant).

**To Reproduce**
1. Start two instances, like in the linked instructions above.
2. See that there are two icons in the tray. Here, the tray refers to the screen which shows persistent background tools, near where the date is traditionally shown). 
3. Hover over each of the icons, and see that each of them shows "Microsoft Teams" instead of whatever is supplied via the appTitle arg.

**Expected behavior**
Hovering over the tray icons should show the value from the `--appTitle` arg.

**Screenshots**
This is the section of the screen I'm refering to ("tray"):
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11021263/d7e7599b-58cc-40ab-a767-45adfb9980b0)

**Desktop (please complete the following information):**
 - OS: Linux Mint 22.1 with Wayland
 - Installation package: deb, I think
 - Version: 1.3.26

**Additonal request:**
In the right click menu on each tray icon, it'd be cool if there was a grayed out (disabled) "menu item" which displays the app title right in the app. This would be helpful so that you can make sure you're "quitting" the correct instance when you quit Teams via the tray icon.

**Comment by IsmaelMartinez** [comment]
I would suggest you just use a new icon? You should be able to get a similar outcome (know what is for each tenant)

See appIcon in  https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config (full path)

**Comment by DeflateAwning** [comment]
That would be a good workaround for now. I still think that this should be done nonetheless.

**Comment by IsmaelMartinez** [comment]
Is a bit more complicated as there are a lot of different permutations and I don't think that option is possible in electron. But I will have a look

**Comment by IsmaelMartinez** [comment]
Ok, looks like you might be able to do it using this https://www.electronjs.org/docs/latest/api/tray#traysettooltiptooltip

maybe just changing this line https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/menus/tray.js#L13C13-L13C23 to `this.tray.setToolTip(config. appTitle);`

And passing the config in https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/menus/index.js#L123 (like this.config or something similar)

That might work but only if you are already getting a 'Microsoft Teams' tooltip in the tray already. Otherwise the Tray they refer is a different tray.

**Comment by DeflateAwning** [comment]
I already get the tooltip, so it looks like this might be the way! Good finds!

**Comment by IsmaelMartinez** [comment]
Ok, got a PR open. I will make 1.4.3 a proper release tomorrow once #1071 is confirmed not to be related to that small change, and then do a pre-release of this. If you can test it, that would be excellent, but you will need to build from source. Do you know how to do that?

**Comment by IsmaelMartinez** [comment]
this should be ready in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.4 . Can you test @DeflateAwning ?

**Comment by DeflateAwning** [comment]
Good fix! Looks like it's working as expected in the v1.4.4 pre-release. Sorry for the delay checking it! Thanks again for implementing this.

**Comment by IsmaelMartinez** [comment]
fixed
