### ISSUE TITLE
Incorrect Time Zone used in Calendar

### ISSUE THREAD

**Issue by hoppersoft** [IsmaelMartinez/teams-for-linux#1063]
**Describe the bug**
I am in the Eastern time zone (GMT-5) and have system settings configured as such, but the Teams calendar is showing events using Central (GMT-6). See below screen shot showing Teams indicating the current time (red line) is an hour earlier than local time (lower-right corner).

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2077889/2c3f6005-c50e-48f1-acd8-347b0b930731)

**To Reproduce**
1. Open calendar
2. Note that events are shown an hour earlier than local time.

**Expected behavior**
Calendar should use the system timezone.

**Desktop (please complete the following information):**
 - OS: Zorin OS 17
 - Flatpak: com.github.IsmaelMartinez.teams_for_linux
 - Version 1.4.1

**Comment by hoppersoft** [comment]
> Hi, can you check if this is the same situation on the browser? thanks

Looks like my browser is reporting the correct time:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2077889/497ba715-9b0e-48fc-b1c1-cbacab0c31ae)

**Comment by IsmaelMartinez** [comment]
sorry, I mean login in MS teams via the browser and checking if the calendar shows the same.

Also check other packaging options (deb, rpm tend to work a wee bit better).

**Comment by hoppersoft** [comment]
Oh, got it. Yes, the time in the Web-based version of Teams is correct.

**Comment by IsmaelMartinez** [comment]
did you try with another package? that looks/sounds like a flatpak configuration shenanigans

**Comment by jijojosephk** [comment]
@hoppersoft can you try installing the browser through flatpak and see if the problem present. Make sure you're trying, `google-chrome`, `chromium`, or `brave` etc. Because `electron` and these uses the same thing.

**Comment by hrk** [comment]
FWIW this is a long standing issue for Electron and not this particular app. The solution is to add the TZ variable before launching the app, e.g.:
```TZ="Europe/Rome" yarn start```
