### ISSUE TITLE
How to change my input device in team-for-linux?

### ISSUE THREAD

**Issue by orbitalchicken** [IsmaelMartinez/teams-for-linux#1066]
There is no "Devices" section in the Settings dialog ? How do I change my input device (mic) in teams-for-linux?

**Comment by woernsn** [comment]
You can change the input device when joining a meeting or from within a call.
To check the available settings you can also navigate to `Calendar` and use the `Meet now` button which will also open the device settings.

**Comment by orbitalchicken** [comment]
Thank you very much!
