### ISSUE TITLE
Restrict focus stealing please.

### ISSUE THREAD

**Issue by RobLW** [IsmaelMartinez/teams-for-linux#1069]
**Is your feature request related to a problem? Please describe.**
Every single message I get, the Teams-for-Linux "steals" focus. I even run it on a separate virtual desktop in Gnome, and as soon as a message comes in, my v-desktop switches over and the app is grabbing focus. This is not only annoying, but has caused me serious issues where I've pasted into teams by mistake, or used hotkeys which then makes teams react when I wasn't planning for it.

**Describe the solution you'd like**
If possible, an option to allow users to stop the app taking focus please, or just disable it all together! 

**Describe alternatives you've considered**
Using the web client in a browser under a pinned tab.

**Additional context**
N/A

**Comment by IsmaelMartinez** [comment]
Can you check if any of the config options regarding notifications does work for you?

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md

<img width="1033" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/374c90ff-d71c-4152-84b6-f4bc950f034c">

Specially the disableNotificationWindowFlash and disableNotifications

**Comment by jijojosephk** [comment]
I assume you're on `gnome`

**Comment by IsmaelMartinez** [comment]
I close this as we haven't had any response for a while. I suspect is the notification window flash that can be disabled using the disableNotificationWindowFlash config option. Please comment back if that, nor the other messages, doesn't work

**Comment by RobLW** [comment]
Hi there,
Apologies for the delay (busy with family, work and priorities).

@jijojosephk is correct, I am using Gnome, I mentioned this in my original message.

I have tried using **disableNotificationWindowFlash** but it continues stealing user input.

It is quite a serious issue as I've been caught out a number of times when typing in confidential information in other apps, or inputting a password and then suddenly it appears in Teams. 

At the moment my only solution is to close the app to the systray. 
Thanks

**Comment by Bitals** [comment]
> Are you using dash-to-dock?

I have the same problem and I do.

**Comment by RobLW** [comment]
OK, it's being caused by a different extension all together. https://github.com/jirkavrba/noannoyance
The extension was designed to stop those silly popups which say "window ready" each time you receive a teams message (not a teams issue I believe). Turning this off seems to stop the focus stealing, a tiny sacrifice to make :) 

Thank you for your help, patience and time. Problem isn't yours to deal with.

**Comment by Bitals** [comment]
@RobLW I disagree. This extension saves a lot of time for everything else, also makes notifications actually functional. Without it (actually JustPerfection with the same exact function enabled, but doesn't matter) clicking on any notifications actually just produces another one with "Window is ready", which you have to click again, and 80% of the time that opens the app. But not always.
This is a very bad experience, and I don't have any other software that triggers focus stealing on notifications with that option enabled.
Fundamentally it's a Gnome problem for sure, but that kind of extensions have been the de-facto solution to that for years.

**Comment by CaptainQuirk** [comment]
I'm using i3 on Ubuntu 13.10 and facing the same issue.

It is very annoying indeed I must say !

I was expecting notifications in the form of what `notify-send` would create, unobtrusive and non interactive.
