### ISSUE TITLE
No more taskbar icon, notifications, sound or incoming call/text notifications on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by emotiv8it** [IsmaelMartinez/teams-for-linux#1071]
**Describe the bug**
Since several iterations of this client, I cannot see any taskbar icon anymore in the notification area, so the teams icon is not available anymore, so I cannot switch to a closed window anymore. 
Also, the notifications seem to be either displaying not at all, or sometimes delayed (? not sure why)
Also the VIEW button in the notifications popup does not work, and does not open the (minimized) teams window

If the window is in the background (not closed, put in background or minimized), no notification is shown at all. There is only a faint glow in the icon in the drawer, or in the active window bar. But no popup of a message is shown. Only when the main window is closed.

Incoming call sound is not playing, and also no notification for incoming calls are not shown as popup. Cannot receive any calls.

**To Reproduce**
This is happening since the last 4 or 5 updates of MS client
Start latest iteration of teams-for-linux  (1.4.3)  on Ubuntu 20.04.6 LTS  (Budgie desktop)

**Expected behavior**
Show notification icon + show incoming call 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.6 -  Budgie desktop
 - Installation package =  deb
 - Version : 1.4.3

**Comment by IsmaelMartinez** [comment]
If you can remove the cache and see what happens? I suspect is a change unrelated to 1.4.3 but probably related to 1.3.14 

can you let us know if you could see this in previous versions? 1.4.2 and 1.4.1. Then 1.3.26 and 1.3.12. 

1.3.14 had a big electron version change, while 1.4.1 had another version change. (some number jumps are because those are broken versions like 1.4.0 and 1.3.13 that should be avoided)

Hope helps!

**Comment by Rosnerv** [comment]
Neither release is integrated into the XFCE panel systray.

**Comment by IsmaelMartinez** [comment]
I think this is duplicated with #937. If you can check if version 1.1.11 works, then we know is the same issue (unfortunately unrelated to this software but to do with electron/chromium/linux). 

Check if the solutions provided in the links solves the problem https://github.com/IsmaelMartinez/teams-for-linux/issues/937#issuecomment-1703656873

**Comment by emotiv8it** [comment]
Hello. I tried by removing the cache. But did not help. tried with installing 1.1.11

Version 1.1.11 -> there is a taskbar icon
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/101925622/7f400d39-f6a5-411c-8eaf-5cd283a590e2)

Version 1.4.4 (&1.4.3)
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/101925622/94db63a6-eb73-43ff-ad1a-233c6bbee3bb)
No more taskbar icon. & also issues as described above.

Is this only due to an electron version ? and the combination with specific linux version ? Am i the only one having this problem with this version then ?

**Comment by IsmaelMartinez** [comment]
electron and linux, and unfortunately we can't do anything in here. I close it as won't fix as this can continue in #937
