### ISSUE TITLE
No se integra con la bandeja de sistema del escritorio XFCE

### ISSUE THREAD

**Issue by Rosnerv** [IsmaelMartinez/teams-for-linux#1073]
El icono de la bandeja de sistema no se integra con el escritorio XFCE y su panel

Al instalar e iniciar no aparece el icono en la bandeja de sistema XFCE

Uno espera a que aparezca el icono como en los otros entornos KDE, GNOME, etc. para activar la aplicacion al tenerla oculta

OS: Linux Lite
Package: .deb
Version: 1.4.2

Esperando su ayuda o instrucciones para solucionar.

Saludos.

**Comment by IsmaelMartinez** [comment]
Hola @Rosnerv , esto es un problema conocido desde que cambiamos la version de electron. Puedes probar a ver si la version 1.3.12 funciona? Si es asi, es una limitacion de electron con tu sistema.

Agradeceria si mensajes aqui son en ingles para facilitar compartir informacion. Tambien el uso de los templates porque simplifican y facilitan encontrar soluciones. 

Hope helps!

**Comment by IsmaelMartinez** [comment]
duplicated in #1071

**Comment by Rosnerv** [comment]
> Hola @Rosnerv , esto es un problema con desde que cambiamos la versión de electron. Puedes probar a ver si la versión 1.3.12 funciona? Si es asi, es una limitación de electron con tu sistema. Sigue la conversación en [# 1071](https://github.com/IsmaelMartinez/teams-for-linux/issues/1071)
> 
> Agradeceria si mensajes aqui son en ingles para facilitar la información del reparto. Tambien el uso de los plantillas porque simplifican y facilitan encontrarás soluciones.
> 
> La esperanza ayuda!

Sigue sin funcionar, no se integra a la bandeja del sistema XFCE

**Comment by IsmaelMartinez** [comment]
creo que es esto https://github.com/IsmaelMartinez/teams-for-linux/issues/937#issuecomment-1703656873 Mira si la solucion en ese link te funciona, pero no es relacionado con este software sino que con electron y linux. Espero que ayude.
