### ISSUE TITLE
Show "away" when I lock my screen

### ISSUE THREAD

**Issue by ModProg** [IsmaelMartinez/teams-for-linux#1081]
**Is your feature request related to a problem? Please describe.**
I want to have Teams show as "away" when I lock my screen, this doesn't happen due to my choice in window manager / screen lock.

**Describe the solution you'd like**
add a cli option to either:
- send a http request as if it was from inside the app, this would enable me to simply extract the correct request using dev tools and do e.g.: `teams-for-linux curl 'https://presence.teams.microsoft.com/v1/me/forceavailability/' -X 'PUT' --data-raw '{"availability":"Away"}'
- dedicated function for this, and maybe other things in the future, e.g.: `teams-for-linux set-availibility away`

**Describe alternatives you've considered**
Manually set my self to `away` every time I lock my screen and unset it afterward.

**Comment by jijojosephk** [comment]
Which `wm` are you on? doesn't it support session lock/unlock messages?

**Comment by jijojosephk** [comment]
Start `teams-for-linux` from shell like this.

`teams-for-linux --appLogLevels debug` and wait for you to see this.

```console
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
```

Then lock your machine and unlock. Let us know what do you see in the terminal. Since the poll interval is 10 seconds, wait for more than 10 seconds before you unlock.

**Comment by ModProg** [comment]
> Which `wm` are you on? doesn't it support session lock/unlock messages?

I am using  `sway` I'm gonna try tomorrow

**Comment by ModProg** [comment]
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11978847/2238d0a0-7d3f-4b4b-b300-ca87483477f0)

Didin't change during locked with `swaylock`.

Though having some `curl` that automatically gets the correct authorization would be pretty neat for e.g. a global key bind to set one to away and even other stuff.

**Comment by ModProg** [comment]
my JS is pretty crusty but if you'd be able to give me some hints on what would need to happen to enable this, I'd be also happy to work on this myself.

**Comment by jijojosephk** [comment]
`teams-for-linux set-availibility away` would be a possibility. But the app is not designed to work like a CLI. I don't know how much work is involved. But we surely understand your requirement. I'll add more logs to the console so that with `sway` and `swaylock` what messages the app gets is important too. If it gets, our work will be a bit more easier.

**Comment by IsmaelMartinez** [comment]
you can probably try extending the use of [yargs](https://yargs.js.org/), or implement it with something else like https://github.com/tj/commander.js (I haven't use it myself) or https://github.com/SBoudrias/Inquirer.js (I have use it in the past). The Yargs logic is in the https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/index.js 

The only concern would be a bit of a clash with the current options configuration, so I will 1st try just doing it with yargs and see if it works, and that the app detects if is already running and that part might play with you https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L89

**Comment by jijojosephk** [comment]
@ModProg I guess you're on `wayland` that's why your idle time is always 0.

Can you start from terminal with  --enable-features=UseOzonePlatform --ozone-platform=wayland should give you idle time. I'm not sure this will affect your window decorations. Let us know the results. This is just get some idea on where to add the fix. We might something working without command line interface.

**Comment by IsmaelMartinez** [comment]
renaming the enhancement as it keeps confusing me. I am adding a new issue https://github.com/IsmaelMartinez/teams-for-linux/issues/1307 to support "watch" the config file.

**Comment by IsmaelMartinez** [comment]
Hi @ModProg , do you still have this issue with the latest versions? There where a couple of changes in version 1.8.1 this one been the one that might have fix your issue https://github.com/IsmaelMartinez/teams-for-linux/pull/1335.

I will close this to keep things tidy, but do reach out to let us know if you still have the same issue. Do put your config file (if you got any) and logs, as they help enormously.
