### ISSUE TITLE
Add `latest-linux-x86_64.AppImage` and `latest-linux-aarch64.AppImage` download link

### ISSUE THREAD

**Issue by leukimi** [IsmaelMartinez/teams-for-linux#1087]
**Is your feature request related to a problem? Please describe.**
It's very useful to have a direct download link to the latest AppImage version for both `x86_64` and  `aarch64`, not having to research which version the file name contains and adapt scripts manually. There is already a `latest-linux.yml` but no `latest-linux.AppImage`. 

**Describe the solution you'd like**
I would like to have a `latest-linux-x86_64.AppImage` and `latest-linux-aarch64.AppImage` (like Fedora Asahi Remix OS uses) which maybe is the same as `latest-linux-arm64.AppImage`.

**firejail sandbox**
How to properly invoke execution via sandbox firejail for the different types of packages offered. Examples of what could work:

```
firejail --appimage --profile=/etc/firejail/teams-for-linux.profile teams-for-linux.AppImage
firejail --profile=/etc/firejail/teams-for-linux.profile electron "/usr/share/teams-for-linux"

```

**Describe alternatives you've considered**
Using manual download/install scripts to detect architecture and set the file name version to latest version manually.

**Comment by jijojosephk** [comment]
Sorry, I didn't get this requirement. Did you @IsmaelMartinez? I'm not so experienced in packaging. Could you elaborate?

**Comment by IsmaelMartinez** [comment]
No idea how to do that. We use electron-build for creating packages, but I have no clue how to archive this

**Comment by IsmaelMartinez** [comment]
More info in https://www.electron.build/configuration/appimage.html 

Whoever i can see in that page this message:
<img width="962" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/0bc830d9-33ec-42fa-84b2-405ee79cec8e">

This line shows how we build AppImage https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L89 maybe we need to change the way we do it. Have a play and shout if you get any questions. Any contributions are greatly welcome.

**Comment by IsmaelMartinez** [comment]
also, you can invoke the build of the app image by using `yarn run dist:linux:appimage`  (see https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L31 ) 

The https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/CONTRIBUTING.md has more info on how to build it from source if you want to validate anything.

**Comment by IsmaelMartinez** [comment]
A wee idea but you might be able to archive the same by querying the github api. You can get the latest version assets location https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release and then get the location of the file playing with the release-asset https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#get-a-release-asset . You can use jq to parse the json response, etc. 

That should get you there, I think. Ta

**Comment by IsmaelMartinez** [comment]
Closed as workaround is provided
