### ISSUE TITLE
No mouse interactions when i enter a meeting

### ISSUE THREAD

**Issue by andrewff2** [IsmaelMartinez/teams-for-linux#1088]
It' happens when i always enter in some meetings

The keybord works (shortcuts) or writing in chat. 

But the mouse doesn't work inside the teams app... 
Even if i close app and enter again for some reason the mouse doesn't at all.

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Installation package [rpm]
 - Version [teams-for-linux-1.4.6-1.x86_64]

**Comment by IsmaelMartinez** [comment]
This is really strange. Can you check another electron app and see if you got the same problem? Just to see if it is an issue around your configuration. 

Can you also check on the browser? Also... do you have another mouse you can try?  Hope helps

**Comment by IsmaelMartinez** [comment]
last, but not least, are you sure this is not related to memory usage? There has been reports that moving to the teamsv2 version can "drain" your memory, so we might have a wee leak and you might be just experiencing it a bit worse than others. 

Joining a meeting does take more memory as you need to share audio/video, so maybe that is just taking your computer to the limit. Mouse movement can well be one of the 1st things that go. Ta

**Comment by IsmaelMartinez** [comment]
Please try 1.4.15 (pre-release currently) to see if this solves your problem

**Comment by IsmaelMartinez** [comment]
close due inactivity
