### ISSUE TITLE
Screen sharing problem with vertical monitor

### ISSUE THREAD

**Issue by rkozlo** [IsmaelMartinez/teams-for-linux#1090]
When using two monitors - one horizontal and other vertical, screen sharing horizonal monitor is broken. It looks like application took width of vertical monitor and applied it while sharing and showing only part of monitor.

1. Use at least 2 monitors - vertical + horizontal
2. Share horizontal screen

Displays proper resolution

**Screenshots**
![Screenshot_20240202_123947](https://github.com/IsmaelMartinez/teams-for-linux/assets/44550015/37e2ae8e-69a5-4849-a0dd-ae14ce1c1fab)

Desktop (please complete the following information):**
 - OS: Fedora, OpenSUSE - probably any
 - Installation package Flatpak
 - Version 1.4.6 - but happened in earlier versions also
 - Resolution 1920x1080 + 1080x1920

**Comment by ghaith** [comment]
I had the same problem when using 2 monitors with different vertical resolutions. I think the problem is related to wayland. Switching back to X11 solved it for me, but that's not a real solution. I was not able to find similar issues reported online so I can't be sure if this is a general wayland issue or just the combination of electron/teamsforlinux with wayland.

**Comment by rkozlo** [comment]
I have switched recently to X11 and this problem persists. So probably not related with x.org or wayland itself. On my side KDE5 as DE

**Comment by jijojosephk** [comment]
> I have switched recently to X11 and this problem persists. So probably not related with x.org or wayland itself. On my side KDE5 as DE

In X11 you'll be prompted with a different screen sharing dialog (custom built). That has an option to choose the resolution. Can you change and see what happens. It might not solve, but something interesting.

**Comment by rkozlo** [comment]
Recently have an oportunity to share screen with new version 1.4.10 and it seems like on X11 is working. I'll try to test it on wayland

**Comment by IsmaelMartinez** [comment]
Closing due inactivity
