### ISSUE TITLE
Font changes when copying text to clipboard

### ISSUE THREAD

**Issue by hendrikiseke1979** [IsmaelMartinez/teams-for-linux#1093]
**Describe the bug**
Whenever I select some random text in chats and press Ctrl+C (or use the context menu), the application font changes to slightly denser version

**To Reproduce**
1. Pick any message from a chat or a team and select some text.
2. Press Ctrl+C or right click on selection and pick 'Copy'.
3. Watch the font change.

**Expected behavior**
Copying text to the clipboard does not change the application font.

**Screenshots**
Before:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/53309111/480f7b08-948e-4ad1-92ab-b68314a826b7)

After:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/53309111/be4d75b9-54d4-4006-a530-95b84bc8bbdc)

**Desktop:**
 - OS: Debian GNU/Linux trixie/sid
 - Installation package: deb
 - Version: 1.4.10

**Additional context**
When clicking 'Refresh'  from the task tray context menu or hitting Ctrl+R, the "original" font comes up again.

**Comment by Shadowfury22** [comment]
Wow, all this time I thought this issue was probably due to some scuffed OS config since I never saw anyone else in the same boat. Can confirm, it's also been happening to me ever since I first installed teams-for-linux on my Ubuntu 22.04 machine 1 year ago 👀

**Comment by IsmaelMartinez** [comment]
This is wild. Do you see the same problem in the web version?

**Comment by hendrikiseke1979** [comment]
> This is wild. Do you see the same problem in the web version?

Yes, but different. :wink: The font seems get smaller, not just denser.

#### Before
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/53309111/62bcb1fa-1f93-48b3-8c20-02d33023aa22)

#### After
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/53309111/38ffc65e-e9f1-49b3-95b4-a63ea2160e80)

Browser: Version 121.0.6167.160 (Official Build) built on Debian trixie/sid, running on Debian trixie/sid (64-bit)

I cannot reproduce with https://teams.microsoft.com/v2/ or while using Firefox.

**Comment by IsmaelMartinez** [comment]
This looks like a chromium shenanigans. Electron uses it under the hood...
