### ISSUE TITLE
[Feature request] Create code/preformated/Monspaced block with ```

### ISSUE THREAD

**Issue by DenisBY** [IsmaelMartinez/teams-for-linux#1094]
"Official" old Teams client is able to insert code/preformated/Monspaced block if ``` are entered on the channel:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/1147703/0aa21b4c-829f-431a-bb10-8f887ee6ae06)

It would be nice to have the same functionality here as well.

**Comment by IsmaelMartinez** [comment]
Hi @DenisBY, unfortunately that is depended on MS web implementation. Unfortunately they have removed that feature in the new version of teams and, by the look of it, in the web version. I would suggest filling a feature request to MS. Hope helps!
