### ISSUE TITLE
Unable to open Teams on Ubuntu 20.04

### ISSUE THREAD

**Issue by omkarnathsingh** [IsmaelMartinez/teams-for-linux#1095]
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/12734027/9c903c50-4d51-49cc-a4d7-df602eabd295)

Getting above page directly, sometimes its showing cookies error and then redirecting here. Any solution?

**Comment by NaimadTheOne** [comment]
Try closing the application through the "Clear Storage" action.

![clear_storage](https://github.com/IsmaelMartinez/teams-for-linux/assets/33543835/6fc552b0-1a2b-4c96-9d43-2c8c284c4b45)

**Comment by IsmaelMartinez** [comment]
@omkarnathsingh I assume this is now sorted and was related to the cache so I will close the issue. 

Thanks @NaimadTheOne for suggesting the "clear storage" 👍
