### ISSUE TITLE
Better contrast of selected text on dark theme

### ISSUE THREAD

**Issue by dxps** [IsmaelMartinez/teams-for-linux#1096]
**Is your feature request related to a problem? Please describe.**
Can we please have a setting or just improve a bit the existing dark theme, so that the selected text has a lighter background (as an example) to have a better contrast when seeing it, please? On some monitors where the blue filter is on, this looks very fade (hardly can see the distinction)

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/14140226/c82093ca-b886-4fa8-a1d2-19ade86ac944)

Many thanks in advance! :pray: 

PS In the screenshot, this may look good, but that's only because it's size is bigger than what's shown on the app.

**Comment by jijojosephk** [comment]
Stylesheets are provided by Microsoft, we might need to find someway to override. It's not easy.

**Comment by dxps** [comment]
Indeed.

Tried to identify both CSS rules (when the app window has focus and when it doesn't have the focus). Found out just for the latter this rule:
  ```css
  .ck.ck-editor__editable_inline.ck-blurred ::selection {
      background-color: blue;
  }
  ```
  with such result (as an example, when setting it as standard blue):
  ![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/14140226/bd870a47-4291-48e9-b588-f20461ed1a85)

**Comment by IsmaelMartinez** [comment]
hey, you should be able to use the "customCSSLocation" option then documented in https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config . There are a bunch of customCSSName's available but I suspect they will be broken in the react version (latest MS version), but just stick that css ina file and use the customCSSLocation to inject it. 

That use to work fine a while back but maybe is also broken with the MS angular to react move.

**Comment by IsmaelMartinez** [comment]
Closing as a workaround is provided. Styling changes otherwise need to be reported to Microsoft directly. Ta
