### ISSUE TITLE
problem on wayland in new version  1.4.10

### ISSUE THREAD

**Issue by Senshi111** [IsmaelMartinez/teams-for-linux#1097]
**To Reproduce**
on start up its just broken

**Screenshots**
![240209_15h56m10s_screenshot](https://github.com/IsmaelMartinez/teams-for-linux/assets/40372242/408e24f1-b239-43fd-85d2-b2776351ab8a)

**Desktop (please complete the following information):**
 - OS Fedora 39
 - Installation package rpm
 - Kernel 6.7.4
 - GPU  Radeon RX 6800

**Comment by jijojosephk** [comment]
Could be related to graphics card. But can you try without `ozone-platform=wayland` ? `gnome` or `kde` ?

**Comment by jijojosephk** [comment]
No major change in `1.4.10` which could break the application.

**Comment by Senshi111** [comment]
Works on 1.4.9 fine, maybe at beginning of start up there some "frames" showing but then displays normal. Older ones started up normally without those small ticking at startup

**Comment by ChristoSnake** [comment]
Works for me too (with rpm install):
Operating System: openSUSE Tumbleweed 20240205
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.7.2-1-default (64-bit)
Graphics Platform: Wayland
Graphics Processor: Mesa Intel® HD Graphics 4000

**Comment by RobLW** [comment]
Just wanted to tag on to this issue a question,
Are there issues with Teams-For-Linux and screensharing on wayland?
Every time I try any of the options for sharing my screen everyone tells me it's just a "grey/black screen". 
This is on Fedora 39
Gnome,
Wayland,
Intel i915 graphics drivers.

**Comment by IsmaelMartinez** [comment]
@RobLW , if you are using snap of flathub, try deb or rpm.

**Comment by RobLW** [comment]
> @RobLW , if you are using snap of flathub, try deb or rpm.

Hi @IsmaelMartinez ,
Things are working great again now in the latest version. When I raised the initial question I had tried both flathub and RPM. 
At the time the latest version wasn't in Fedora repo so I downloaded 1.4.12 from here and it's magical :) :+1:

**Comment by jijojosephk** [comment]
Closing this as the issue seems to be resolved.
