### ISSUE TITLE
Electron starting args in config.json not honoured

### ISSUE THREAD

**Issue by zeitounator** [IsmaelMartinez/teams-for-linux#110]
**Describe the bug**

Our linux users must declare a proxy with basic authentication in their system settings to work conveniently in our internal environment.

Using such settings with team-for-linux is not expected to work as Electron does not allow basic auth for proxy in the url. (Note: this causes teams-for-linux to enter an infinite respawning loop for which I might open an other ticket, or reopen the existing one for the same kind of issue).

To overcome this, we have a working solution which is to override proxy settings in Electron to use the enterprise provided proxy pac file.

There is absolutely no issue using this from the command line:
```bash
teams-for-linux --proxy-pac-url=https://pac.server.com/file.pac
```
However, putting this parameter in the config.json file for a fresh install is not taken into account (I get stuck in infinite respawning loop).

To be noted: once TFL has been started successfully once from the command line (and has created its partition, etc...), next start without params (e.g. from the start menu) is ok

**To Reproduce**

Note: this will unfortunatelly need a proxy *really* requiring authentication + a proxy pac file available to be tested (a very simple local squid install + a fake proxy pac file answering always "DIRECT" should do)
1. Cleanup config dir `rm -rf /home/user/.config/teams-for-linux/!(config.json)`
1. Make sure you have a `proxy-pac-url` param in `/home/user/.config/teams-for-linux/config.json`
    ```json
    {
        "proxy-pac-url": "http://proxy.pac.com/file.pac"
    }
    ```
1. Make sure your system proxy settings are pointing to a proxy-url with basic auth required
1. Start teams-for-linux normally (e.g. by clicking its icon in applications)

Result => TFL enters an infinit respawning loop which means that the proxy-pac-url was not taken into account.

**Expected behavior**
TFL start correctly taking into account the proxy-par-url parameter in config.json

**Desktop (please complete the following information):**
 - OS: Ubuntu bionic 18.04
 - Installation package: reproduced on both deb package and from source
 - Version: 0.2.0

**Comment by IsmaelMartinez** [comment]
Hi, as far as I know, the config.json is only useful for the arguments that we have added. Maybe yargs package can provide ways to configure those arguments in the config file.

It will be possible to add that as an option, so I will put this as an enhancement.

**Comment by zeitounator** [comment]
OK so I misunderstood how config.json was used. Sorry for the confusion. For time being we have been able to overcome this with a custom launcher script. Thanks for your quick reply (aren't you supposed to be off for aws certification ? :laughing: )

**Comment by IsmaelMartinez** [comment]
I will be closing this. If needs must, we can add those extra arguments, not a big deal. Create a feature request if so.

**Comment by jmayday** [comment]
Just found this issue as I have an issue with config.json which seems to be in correct location and its contents are according to https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config correct:

```
➜  ~ cd .config/teams-for-linux 
➜  teams-for-linux ls
config.json
➜  teams-for-linux cat config.json 
{
	"closeAppOnCross": true
}

```

Unfortunately this setting is not being applied.

**Comment by IsmaelMartinez** [comment]
Hi @jmayday 

Can you open a bug? Fill the template as it provides us with valuable info that eases the process to solve the issue.

Sorry to hear you are having problems.

**Comment by jmayday** [comment]
@IsmaelMartinez bug created: https://github.com/IsmaelMartinez/teams-for-linux/issues/183
