### ISSUE TITLE
Notifications for Meetings created in a Team are mixed up

### ISSUE THREAD

**Issue by MrLast98** [IsmaelMartinez/teams-for-linux#1100]
DESCRIPTION:
The bug present itself when a meeting is created inside a team.
If any chat message is sent in those meetings, whether they are still happening or not, the notification shows as if a new meeting has started, so it's a wrong notification and it does not point out which meeting specifically, but a generic "a meeting has started" with the name of another re-occurring meeting of the same channel (but not the correct one where the message was sent), considering teams allows for more than one meeting in the same team.

STEPS TO REPRODUCE:
1. Open Teams
2. Click on "Teams" from the left sidebar
3. Select any channel from one of the Teams you're in
 3.a This steps assume a Team exists, with a channel already created, and that two or more people are in this team and channel 
3. On the top-right corner, press the "Meet Now" button to create a meeting
5. Now, if anybody who was or is in that meeting writes a message the meeting's chat, the notification received by other people will be the one described above.

EXPECTED BEHAVIOUR:
Show the name of the meeting (custom names can be set) and the chat message instead of "a meeting has started"

SYSTEM:
 - OS: ArchLinux
 - Installation package: Archlinux AUR Package
 - Version: 1.4.10-1
 - Using Wayland and Mako to handle notifications

**Comment by awilkins** [comment]
Basically all my chat notifications produce a generic "Microsoft Teams is Ready (1)" kind of notification
(X1 / GNOME Shell / Ubuntu 20.04)

**Comment by jijojosephk** [comment]
This is a GNOME shell issue. You must use this extension. 
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/08448805-238e-4d38-9fb5-bf8bc3ea157a)

**Comment by jijojosephk** [comment]
This is a DE specific problem. Hence closing.
