### ISSUE TITLE
File dialog with empty rectangles instead of characters

### ISSUE THREAD

**Issue by HackerBaloo** [IsmaelMartinez/teams-for-linux#1105]
**Describe the bug**
When I try to download a file I get a file dialog with empty rectangles instead of characters

**To Reproduce**
1. Go to chat
2. Click on download file, on a file shared by the one you are chatting with
3. See error

**Expected behavior**
A normal file dialog, which I get if I run teams in Chrome

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/121866/6fcbe8d3-f0a5-42d5-b5f3-d501fb529a8b)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (Desktop plain and simple)
 - Installation package snap
 - Version 1.4.10 (and 1.4.11)

**Additional context**
It works for teams in Chrome.

**Comment by IsmaelMartinez** [comment]
Can you try another package system like deb ? Snap configuration can create
this sort of issues. Hope helps!

**Comment by jijojosephk** [comment]
@HackerBaloo  this is a snap issue, if you don't want native package go for `flatpak`

**Comment by jijojosephk** [comment]
This works for me at least.
```terminal
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by jijojosephk** [comment]
Workaround provided hence closing.

**Comment by HackerBaloo** [comment]
Yes, deb package works, but I wouldn't say that this issue is solved. It is still a problem with the snap package. Does the snap package need to include some font?

**Comment by IsmaelMartinez** [comment]
Is snap configuration. Check around the closed issues as I believe there
might be some pointers in there. I don't remember where/what but you should
be able to find something. Hope helps!

**Comment by HackerBaloo** [comment]
The solution from this video works: https://www.youtube.com/watch?v=_n2J40xCQH0
```
fc-cache -r
rm ~/.cache/fontconfig/*
sudo rm -f /var/cache/fontconfig/*
```
