### ISSUE TITLE
Screen sharing in Ubuntu does not work

### ISSUE THREAD

**Issue by AntoninSlejska** [IsmaelMartinez/teams-for-linux#1108]
**Describe the bug**
When I try to share my screen, I get the following error message: "Your video isn't working. We couldn't access your camera." But the camera/video is working. (My colleagues can see me.)

**To Reproduce**
1. Try to share your screen.
![Screenshot from 2024-02-16 12-38-59](https://github.com/IsmaelMartinez/teams-for-linux/assets/833218/7cfe9ef4-4153-40ae-9033-df6ac745b721)
2. The error message will be displayed.
![Screenshot from 2024-02-16 12-01-41](https://github.com/IsmaelMartinez/teams-for-linux/assets/833218/102e023c-93e8-4aa6-8c44-56e0e88f646e)

**Desktop**
 - OS: Ubuntu 22.04.3 LTS (with Wayland)
 - Installation package: snap (from Ubuntu Software)
 - Version: 1.4.10

**Additional context**
In the browser (Vivaldi) works the Screen Sharing.

**Comment by jijojosephk** [comment]
@AntoninSlejska it's a problem with `snap` and the way `sandboxing` done in it. Can you try `flatpak` ?

**Comment by AntoninSlejska** [comment]
@jijojosephk Thanks. I have installed the deb package. It seems to work.

**Comment by stephanecodes** [comment]
Hi, I have exactly the same problem with latest version (1.4.11).
Mine is installed with the deb package, I'm using Ubuntu 22.04 with gnome 42.9, no Wayland.
It's also working in a Web Browser.

**Comment by woernsn** [comment]
> Hi, I have exactly the same problem with latest version (1.4.11). Mine is installed with the deb package, I'm using Ubuntu 22.04 with gnome 42.9, no Wayland. It's also working in a Web Browser.

Same here.
- Version: teams-for-linux: 1.4.11
- Distribution: Kubuntu 23.10 x86_64
- DE: Plasma 5.27.8
- X11

**Comment by holle** [comment]
> Hi, I have exactly the same problem with latest version (1.4.11). Mine is installed with the deb package, I'm using Ubuntu 22.04 with gnome 42.9, no Wayland. It's also working in a Web Browser.

Same here:

- Version: teams-for-linux: 1.4.11
- Distribution: openSUSE Leap 15.4
- DE: Plasma 5.24.4
- X11

It did work with the 1.4.7 or 1.4.8 version I was using before without a problem.
I will try to downgrade and see if I can get it to work.

**Comment by mkozina-gk-software** [comment]
Same on Manjaro:

- Version: teams-for-linux: 1.14.11
- Distribution: Manjaro Linux
- DE: Plasma desktop 5.27.10 (KDE frameworks 5.113.0-1)
- X11

It worked last week with teams-for-linux: 1.14.10; Today I have upgraded just teams-for-linux, no big global upgrade.

**Comment by torbendury** [comment]
Hi, I'm facing the same problem, `teams-for-linux` is installed via deb package.

System Info:
- Linux Mint 21.2
- Cinnamon 5.8.4

**Comment by dagmoller** [comment]
Same here:

Slackware 15.0
KDE Plasma
Version 1.4.10 and 1.4.11 (last working version is 1.4.9) (tar.gz)

**Comment by BzSpi** [comment]
Reverting to version 1.4.10 make it works :shrug: 

```
sudo snap revert teams-for-linux --revision 523
```

**Comment by frazzaglia** [comment]
Hi, if I try to install 1.4.10 from apt on linux mint I get this error:

**E: Version "1.4.10" "teams-for-linux" not found**

The command is:
**sudo apt-get install teams-for-linux=1.4.10**

Thanks.

**Comment by woernsn** [comment]
> Hi, if I try to install 1.4.10 from apt on linux mint I get this error:
> 
> **E: Version "1.4.10" "teams-for-linux" not found**
> 
> The command is: **sudo apt-get install teams-for-linux=1.4.10**
> 
> Thanks.

That's because only the latest release is provided on the debian repo: https://repo.teamsforlinux.de/debian/pool/main/t/teams-for-linux/
You can download the `.deb` file from the GitHub release and then install the local `.deb` file via `sudo apt install ~/Downloads/eams-for-linux_1.4.10_amd64.deb` for example.

**Comment by jijojosephk** [comment]
There is nothing in the latest release that could break screen sharing. I'm not sure what's happening

**Comment by holle** [comment]
> > Hi, I have exactly the same problem with latest version (1.4.11). Mine is installed with the deb package, I'm using Ubuntu 22.04 with gnome 42.9, no Wayland. It's also working in a Web Browser.
> 
> Same here:
> 
>     * Version: teams-for-linux: 1.4.11
> 
>     * Distribution: openSUSE Leap 15.4
> 
>     * DE: Plasma 5.24.4
> 
>     * X11
> 
> 
> It did work with the 1.4.7 or 1.4.8 version I was using before without a problem. I will try to downgrade and see if I can get it to work.

FYI:
- Clearing the cache and restarting / re-logging in using 1.4.11 did not fix the problem
- Downgraded to the 1.4.10 RPM on my openSUSE and it worked perfectly afterwards

**Comment by jijojosephk** [comment]
@holle when you say you can't share screen, are you getting the same error mentioned in the issue?

**Comment by holle** [comment]
> @holle when you say you can't share screen, are you getting the same error mentioned in the issue?

@jijojosephk yes, correct. I am (was) seeing the same message telling me it could not access the could not access the camera albeit I was already having my camera running and happily chatting with a colleague.

**Comment by woernsn** [comment]
@jijojosephk, for me it also is the same error as in the original issue description.
I tried the last versions
- 1.4.9: working
- 1.4.10: working
- 1.4.11: 
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6933385/82a6f180-14d4-41dd-a249-8ae5087cb86d)

**Comment by jijojosephk** [comment]
This could have been causing this issue: https://github.com/IsmaelMartinez/teams-for-linux/pull/1102#issuecomment-1952653009

I'm on wayland so can't debug the same problem. Once `pre-release` ready for `1.4.12`, kindly test.

**Comment by jijojosephk** [comment]
@holle and @woernsn can you try `1.4.12` ?

**Comment by dschrempf** [comment]
1.4.12 fixed the screen sharing issue for me on NixOS (unstable).

**Comment by jijojosephk** [comment]
Sorry for the chaos. I believe `1.4.12` fixes the problem hence closing.

**Comment by woernsn** [comment]
> @holle and @woernsn can you try `1.4.12` ?

Also on my site, `1.4.12` fixes the issue.
Thanks.

**Comment by holle** [comment]
> @holle and @woernsn can you try `1.4.12` ?

@jijojosephk will try later today. But I guess from the others feedback it will work :wink:
Thanks for the quick reply, the quick fix and the effort :+1:

**Comment by z1atk0** [comment]
Yup, 1.4.12 works fine again here as well. Thanks! :+1: :smiley:

**Comment by AntoninSlejska** [comment]
I have installed 1.4.12 the **deb** package. My colleages have then complained, they hear me twice, when I start to share my desktop.
I have installed 1.4.12 the **snap** package. The screen sharing did not work then anymore.
I have installed 1.4.12 with the following **commands**:
```
sudo mkdir -p /etc/apt/keyrings
sudo wget -qO /etc/apt/keyrings/teams-for-linux.asc https://repo.teamsforlinux.de/teams-for-linux.asc
echo "deb [signed-by=/etc/apt/keyrings/teams-for-linux.asc arch=$(dpkg --print-architecture)] https://repo.teamsforlinux.de/debian/ stable main" | sudo tee /etc/apt/sources.list.d/teams-for-linux-packages.list
sudo apt update
sudo apt install teams-for-linux
```
The screen sharing **works perfect now**. I will write an update, if there are any other problems.

**Comment by jijojosephk** [comment]
Thanks @AntoninSlejska ! `snap` package has been a pain since a few months.
