### ISSUE TITLE
The New Microsoft Teams

### ISSUE THREAD

**Issue by rbrinson-extron** [IsmaelMartinez/teams-for-linux#1109]
**Is your feature request related to a problem? Please describe.**
Microsoft has announced that Classic Teams will no longer be available after March 31, 2024. Currently, in the teams-for-linux application, there is a banner at the top with the text:

> Classic Teams won't be available for use after March 31, 2024. To use the new Teams, update your browser to meet requirements or contact your IT admin. See requirements

**Describe the solution you'd like**
I would like to see the teams-for-linux application support the New Teams implementation. However, I don't know if that is technically possible, or if this update is already on your roadmap.

**Describe alternatives you've considered**
An alternative would be to not use the teams-for-linux application. However, since the only other desktop application option for Linux is the teams preview app, which hasn't been updated in the Arch Linux AUR since March 2023, my only other option would be to use a browser to access the web interface for Teams.

**Additional context**

**Comment by jijojosephk** [comment]
Some functionalities might be broken. Closing this as we have another one discussing the same. #1006
