### ISSUE TITLE
Unable to Authenticate using NTLMv2

### ISSUE THREAD

**Issue by andybissen** [IsmaelMartinez/teams-for-linux#111]
**Describe the bug**
The company I work for has disabled NTLMv1 and requires NTLMv2 only.
Since this change, I have been unable to authenticate in teams-for-linux 0.2.1, but am able to login using Chromium 73.0.3683.103

I've attempted manually running **teams-for-linux --ntlmV2enabled true** and have tried enabling the setting in **.config/teams-for-linux/config.json**.  No success in either case.

Attempts to authenticate with teams-for-linux locks out my account.

**To Reproduce**
1. Enter the username/password when prompted
2. Hit 'Submit'
3. The teams-for-linux interface refreshes, and prompts for credentials again

**Expected behavior**
Should be able to login successfully after entering credentials

**Screenshots**
Nothing useful via screenshot

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.0.7-arch1-1-ARCH
 - Installation package https://aur.archlinux.org/packages/teams-for-linux/
 - Version 0.2.1

**Comment by IsmaelMartinez** [comment]
Hi. Have you tried to clean the ~/.config/teams-for-linux folder? The ntlmv2 should be enabled. Otherwise, start with --webDebug , check the "persist logs" and see if you can get more info in here. Sorry but I am not much available at the moment.

**Comment by andybissen** [comment]
Hi!  I've done a fresh install (cleared out all of ~/.config/teams-for-linux, as well)
I've also enabled the --webDebug option and checked the 'Preserve Log' option (didn't see 'persist logs')
But, when prompted for the username and password, the application reloads itself.  the Debug menu is still enabled, but the 'Preserve Log' box is unchecked and all history is cleared.  It might not be of much use, but here's a screenshot of the debug menu right before it reloads
![Screenshot from 2019-04-18 07-52-34](https://user-images.githubusercontent.com/33384718/56362890-85e49800-61b0-11e9-807d-f3d100a8d897.png)

I'm not sure what exactly to search for in the filter, but searching for 'ntlm' returns no results so far.

The terminal repeats the following error quite a bit when webDebug is enabled:
[12329:0418/075217.761125:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)
[12329:0418/075217.761151:ERROR:CONSOLE(108)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/shell.js (108)

Thanks!

**Comment by IsmaelMartinez** [comment]
Can you try version 0.1.17? I did change a couple of things in the last build that should not affect that but always good to discount them. (suspicious of the certificate part changes that could be causing your issue)

Apologies for the persist/preserve log. Sometimes the replies are from my mobile.

**Comment by andybissen** [comment]
Not a problem.  I've tried rolling back to 0.1.17 and am having the same issue.  Receiving an identical screenshot and the same terminal output.

Thanks!

**Comment by IsmaelMartinez** [comment]
I don't think I can help more then, at this moment. It's like been blind and trying to guess the colour someone sees hole they are colour blind.

Sorry, maybe ask the network people to see if they can help. Try to disable the ntlmv2 instead of enable in it? 

Sorry

**Comment by IsmaelMartinez** [comment]
Hi, I am going to close due inactivity, just to keep things tidy. Do please comment if needs reopen. Hopefully you have found a solution. I am fairly certain at my company we use ntlmv2 and all have work fine since I implemented that part.

**Comment by pini-edf** [comment]
@IsmaelMartinez Hi, our IT service has just disabled NTLMv1 authentication a few days ago and we're stuck with this very same problem. Any way to re-open the ticket?

**Comment by IsmaelMartinez** [comment]
Does look like no-one will help on this issue, I will close it but, if anyone is interested on trying to fix it, then I am happy to reopen it. Apologies
