### ISSUE TITLE
Support downgrading version of deb package

### ISSUE THREAD

**Issue by torbendury** [IsmaelMartinez/teams-for-linux#1110]
**Is your feature request related to a problem? Please describe.**
When issues like #1108 happen, I'm not able to downgrade to the last working version using `apt`.

**Describe the solution you'd like**
I'd like to access older versions of `teams-for-linux` using the apt repo.

**Describe alternatives you've considered**
An alternative would be installing the `deb` manually from the GitHub release, but that's kinda awkward and breaks the intention of the apt repo.

**Additional context**
Right now, only the latest released version is available in the apt repo to me:
```bash
$ apt list -a teams-for-linux
Listing... Done
teams-for-linux/stable,now 1.4.11 amd64 [installed]
```

Edit: If you can pinpoint me to where the deb release happens I'd happily help out (and learn)!

**Comment by jijojosephk** [comment]
@nbuechner is this possible?

**Comment by nbuechner** [comment]
Currently only the latest stable release is in the repo. If you want to keep an older version please download the Github release until the problem in the latest version is fixed.

**Comment by r-cdriscoll** [comment]
You can always download one of the .deb packages from the release page and install that via apt or dpkg.

**Comment by jijojosephk** [comment]
We're not able to provide downgrading the version using `deb` or `rpm` repo at the moment. Kindly go to github releases pages do get an older version of the app.
