### ISSUE TITLE
Cannot share files from /tmp directory

### ISSUE THREAD

**Issue by jnkroy** [IsmaelMartinez/teams-for-linux#1111]
When I'm trying upload file from /tmp directory, it shows: "some files couldn't be uploaded because they're missing necessary data"

**To Reproduce**
1. Just try to copy file from /tmp directory (drag and drop or upload)

**Expected behavior**
upload should work

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package: snap

**Additional context**
It looks it's not new problem: https://answers.microsoft.com/en-us/msteams/forum/all/error-dragging-photos-from-outlook-to-teams-some/3e548eba-5846-4540-9f76-df514fee74e8?page=1

**Comment by jijojosephk** [comment]
It's mostly snap related. We can't fix much of the snap problems. Can you try a native package?

**Comment by jnkroy** [comment]
yep, on browser it works - I can share a file from /tmp

**Comment by IsmaelMartinez** [comment]
Try another packaging system and see if it works. I do suspect it is snap configuration (or limitations due containment)

**Comment by jnkroy** [comment]
yep, installed from repository is ok. So it's snap problem
