### ISSUE TITLE
Add LanguageTool (a fantastic spelling and grammar checker)

### ISSUE THREAD

**Issue by emericv** [IsmaelMartinez/teams-for-linux#1113]
LanguageTool is a multilingual spelling, style, and grammar checker that helps correct or paraphrase texts.

On Chromium/Firefox an extension https://languagetool.org/ is available, and it can be integrated into this app.

**Comment by jijojosephk** [comment]
There's already a spell checker. Have you used it?

**Comment by emericv** [comment]
@jijojosephk Yes, but the native spell checker is only a basic syntax-based spell checker. LanguageTool is really more powerful.
It can :
* dynamically autodetect the language.
* perform grammar check
* ... and other useful features

You can test the Firefox/Chrome browser extension :)

**Comment by jijojosephk** [comment]
@emericv Maintaining it will be difficult because it's only available as chrome extension.

**Comment by jijojosephk** [comment]
It has licensing. That can create problems in the future. We must see their license agreement.

**Comment by emericv** [comment]
> @emericv Maintaining it will be difficult because it's only available as chrome extension.

@jijojosephk I understand this.

I better idea is probably a generic way to add features like this as a plugin in all Electron-based applications…

**Comment by IsmaelMartinez** [comment]
I had a look at adding support for plugging (like in chrome) but I didn't
get far with it. Electron was limiting what sort of plugging you could
connect a lot (in functionality and support). But that was a few electron
versions ago.

If you or anyone have the time to have a look, that would be great.

**Comment by IsmaelMartinez** [comment]
closing and I will be following he issue in languagetool and re-open if required. Thanks for the suggestion and languagetool is a great tool
