### ISSUE TITLE
Another blank page issue after redirect to organization sign-in

### ISSUE THREAD

**Issue by crove** [IsmaelMartinez/teams-for-linux#1114]
**Describe the bug**
Redirection from the login-window doesn't work and ends up in a white screen. Known solutions for blank page issue did not help.

**To Reproduce**
1. Start teams-for-linux
2. Fill in your organisations email and press enter
3. wait around 3 to 5 minutes

**Expected behavior**
Being redirected to my organizations sign-in

**Screenshots**
![teams_issue_sign-in](https://github.com/IsmaelMartinez/teams-for-linux/assets/44267977/0cb62ed0-ae91-4c45-addf-8b091562d772)
![teams_issue_redirect](https://github.com/IsmaelMartinez/teams-for-linux/assets/44267977/c29f0de9-9d5a-4939-8a3c-f7f8fcf795a2)
![teams_issue](https://github.com/IsmaelMartinez/teams-for-linux/assets/44267977/c0adf4eb-3322-4946-b018-60ea9ce2f599)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Installation package .deb
 - Version 1.4.12

**Additional context**
Using the debug feature, these were the errors that showed up after it failed the redirect.
``
node:electron/js2c/renderer_init:2 Unable to load preload script: /opt/teams-for-linux/resources/app.asar/app/browser/index.js
(anonymous) @ node:electron/js2c/renderer_init:2
node:electron/js2c/renderer_init:2 
``  

``
TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at /opt/teams-for-linux/resources/app.asar/app/browser/index.js:43:9
    at Object.<anonymous> (/opt/teams-for-linux/resources/app.asar/app/browser/index.js:79:2)
    at Object.<anonymous> (/opt/teams-for-linux/resources/app.asar/app/browser/index.js:95:3)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at s._load (node:electron/js2c/renderer_init:2:30758)
``

Refreshing the page via icon did not work at all. 
Deleting the application cache folder also wasn't possible because there was no such folder:
![ls_teams_for_linux1](https://github.com/IsmaelMartinez/teams-for-linux/assets/44267977/a8e69e1d-89ee-479f-b9cf-a6a285d7c0e2)
I tried deleting the Cache folder but it didn't solve the issue

**Comment by jijojosephk** [comment]
Is it still a problem? did you try deleting the `~/.config/teams-for-linux` folder?

**Comment by jijojosephk** [comment]
Interesting. What do you see in console when you execute the below command?

`navigator.serviceWorker` and hit enter.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/7e906d82-63d7-40f3-a86d-3eac3068a252)

**Comment by dawaldow** [comment]
> Interesting. What do you see in console when you execute the below command?
> 
> `navigator.serviceWorker` and hit enter.
> 
> ![image](https://private-user-images.githubusercontent.com/11662148/311807245-7e906d82-63d7-40f3-a86d-3eac3068a252.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODE3MzIsIm5iZiI6MTcxMDE4MTQzMiwicGF0aCI6Ii8xMTY2MjE0OC8zMTE4MDcyNDUtN2U5MDZkODItNjNkNy00MGYzLWE4NmQtM2VhYzMwNjhhMjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE4MjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwM2Y2Y2Q4MzY4ODQ2ODAyNzFiOTQyMDQxZTQ0MTE3NjJmMjFhNTM5ZDE0MjkzZTNiMWM0MzY3MTBlODU4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MiuwG-ijQ5F8JI_ljj1OSDRxNi1bMXJ3sWjG7N0WuzA)

![Screenshot from 2024-03-11 11-23-45](https://github.com/IsmaelMartinez/teams-for-linux/assets/57457955/d289004d-0256-4e21-838f-4c6e6a003076)

**Comment by IsmaelMartinez** [comment]
can you try deleting the teams-for-linux folder ? The one bellow "Partition" in this image you posted.

It is usually under `~/.config/teams-for-linux` but you did mention is not there.

Just the whole folder that is parent of Partition. Ta

<img width="1012" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/409adf7d-3f63-4c82-afb7-72de6e6dc483">

**Comment by dawaldow** [comment]
Mine is found under .var (nothing under .config).  I removed that directory and restarted the app.  It recreates it but still a blank screen.

[Screencast from 2024-03-29 09-21-43.webm](https://github.com/IsmaelMartinez/teams-for-linux/assets/57457955/b783f866-7d41-4159-853b-20d776cf6b2c)

**Comment by dawaldow** [comment]
Update: I uninstalled the flatpak installation and ran the command line installation and it is now working.  I think maybe something was missing around the keyrings with the flatpak install.  But anyway, it is working now and happy to see that it even runs Team v2.  thanks for your help.
