### ISSUE TITLE
Option --appTitle "MyTeamsWindow" does not work in Appimage version

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#1117]
In the latest Appimage 1.4.12 (and I guess in the past versions, too) the option to set the window title did not work. The window title was not displayed at all.

The flatpak version shows the correct (and changed) window title, though.

**Comment by IsmaelMartinez** [comment]
Hi @elhennig, appreciate you letting us know. Unfortunately maintaining and trying to fix all types of packages has become an impossible task, specially as most cases is a configuration related to the packaging system. 

I normally recommend going down to more traditional packaging systems like deb or rpm that tend to report less issues. In some systems snap, flatpak and/or appimage can be a pain in the b... AUR has a great community and they manage the packaging what is amazing.

I will close it and hope Flatpak works for you. Again, thanks for reporting!
