### ISSUE TITLE
teams-for-linux not starting on kubuntu 22.04

### ISSUE THREAD

**Issue by JohnySimi** [IsmaelMartinez/teams-for-linux#1118]
**Describe the bug**

I am on Kubuntu 22.04 - using teams-for-linux from SNAP 
When i try to open application from Task manager or from "start" menu - application very often starts and quit immediatelly,
i mean, icon disappear in task manager and changes to "opened application" for half a second and disappears and nothing happens - sometime after minute, 10 minutes or so .. when i try it again like 20 times for some reason application starts

**To Reproduce**

command of the shortcut:
env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/teams-for-linux_teams-for-linux.desktop /snap/bin/teams-for-linux %U

cat /var/lib/snapd/desktop/applications/teams-for-linux_teams-for-linux.desktop
[Desktop Entry]
X-SnapInstanceName=teams-for-linux
Name=Teams for Linux
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/teams-for-linux_teams-for-linux.desktop /snap/bin/teams-for-linux %U
Terminal=false
Type=Application
Icon=/snap/teams-for-linux/527/meta/gui/icon.png
StartupWMClass=teams-for-linux
Comment=Unofficial Microsoft Teams client for Linux using Electron. It uses the Web App and wraps it as a standalone application using Electron.
MimeType=x-scheme-handler/msteams;
Categories=Chat;Network;Office;

cat .xsession-errors 
diff between last action and after execution of teams-for-linux 
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 36683, resource id: 39846263, major code: 18 (ChangeProperty), minor code: 0
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:370: Unable to assign [undefined] to QString
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 36691, resource id: 39846264, major code: 18 (ChangeProperty), minor code: 0
file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:370: Unable to assign [undefined] to QString
/user.slice/user-1000.slice/user@1000.service/app.slice/app-teams\x2dfor\x2dlinux_teams\x2dfor\x2dlinux-4fb5e805981a49f08d6abc79ab5c375b.scope is not a snap cgroup

**Expected behavior**
Application starts correctly

**Workarounds**
ive tried 2 things already, but i am not satisfied with outcome :)
clear cache by:
mv /snap/teams-for-linux/current/.config/teams-for-linux/ /snap/teams-for-linux/current/.config/teams-for-linux-bck/

nohup teams-for-linux &
- starts application correctly, but when i close terminal, application terminate with it,
- when application is closed and i try to execute it again from taskbar, it doesnt work again 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Installation package 
snap info teams-for-linux 
channels:
  latest/stable:    1.4.12 2024-02-20 (527) 89MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      1.4.12 2024-02-19 (527) 89MB -
installed:          1.4.12            (527) 89MB -

 - Version 1.4.12

**Comment by jijojosephk** [comment]
`snap` had always been a pain for us. Can you try other packages? `flatpak` or native `deb` ?

**Comment by JohnySimi** [comment]
Ok, installed it from apt and for now, it seems that it works as expected (i use it for like a week and havent noticed mentioned problem)

**Comment by jijojosephk** [comment]
Closing as reported working fine.
