### ISSUE TITLE
Screen sharing stopped working between 1.4.3 and 1.4.11 (KDE, X11)

### ISSUE THREAD

**Issue by equaeghe** [IsmaelMartinez/teams-for-linux#1119]
**Describe the bug**
After updating from 1.4.3 to 1.4.11, screensharing stopped working. When trying to share, I get an error message saying that there is no access to my camera (whilst camera is working). Downgrading to 1.4.3 restores screen sharing functionality.

**To Reproduce**
1. Update from 1.4.3 to 1.4.11
2. Try to share screen
3. Error message appears (screen not shared)

**Expected behavior**
Screensharing is possible, i.e., the screen/window selection functionality is shown and one can select one to share.

**Desktop (please complete the following information):**
 - OS: Gentoo Linux using KDE on X11
 - Installation package: rpm
 - Version 1.4.11

**Comment by jijojosephk** [comment]
It's already fixed in 1.4.12
