### ISSUE TITLE
Messages marked as read when window is not focused

### ISSUE THREAD

**Issue by abmantis** [IsmaelMartinez/teams-for-linux#112]
**Describe the bug**
Lets say I send a message to Frank and change the focus to another app (leaving ms teams on frank's chat). When Frank replies, there will be no icon badge or notification. This also happens in team rooms.

**To Reproduce**
1. Send a message to Someone.
2. Change the focus to another app.
3. Receive reply from Someone.
4. No red dot on the app's icon or notification.

**Expected behavior**
A red dot should appear on the app's icon and a notification.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10
 - Installation package: deb, snap
 - Version: 0.2

**Additional context**
It looks like it is simply not aware that the window lost focus, so it marks chats as read. If I change to another chat before unfocusing, it works. Also, if I "hide" the window using the tray menu, it works. Minimizing the window also solves the issue.

**Comment by IsmaelMartinez** [comment]
Hi @abmantis,

Thanks for reporting. This is an issue with electron itself. Check this comment:

https://github.com/IsmaelMartinez/teams-for-linux/issues/15#issuecomment-436585081

Apologies but a bit too much work for me to start fixing electron also.

**Comment by abmantis** [comment]
Thanks @IsmaelMartinez but the issues you linked on the #15 doesn't seem related to the app not loosing focus. They are related to focus, but different situations.
Also, how do other electron apps work correctly with this?

**Comment by IsmaelMartinez** [comment]
Did you check the electron links? It does smell to the same limitaion. This is a wrapper around the browser. Meaning, there are some cases where the electron app do loose focus but doesn’t propagate this to the browser part that is viewing. So the browser (or the angular page that is dealing with teams stuff, still things is on focus.

Other apps are probably just implementing their own html stuff, and not wrapping the browser window itself. Maybe try version 0.1.16. There was a change on how we get the unread messages. If the issue still persist, then is surely this issue.

Hope that clarifies it.

**Comment by abmantis** [comment]
@IsmaelMartinez Yes, I did. That's why I said they are related. 
I was trying to see if I could get my hands on this, maybe by forcing the unfocus signal to propagate somehow, but this is not easy to test without bothering someone to send me messages on teams...

**Comment by abmantis** [comment]
Well, it seems that even on the browser, if I leave the Teams tab open and change focus to another window, the same bad behavior happens :( 
If I change to another tab, everything works. @IsmaelMartinez  Maybe we could fake something when electron receives the blur event?

**Comment by IsmaelMartinez** [comment]
Probably best then report it in ms uservoice channel. Search as there might be already an issue for it.
https://microsoftteams.uservoice.com/forums/555103-public?query=focus%20browser%20notification

**Comment by abmantis** [comment]
Yeah, I did. But we could work around it anyway... not sure how soon it will be fixed :)

**Comment by abmantis** [comment]
I've been using a workaround that works but is inconvenient: automatically minimizing the app when it looses focus, as you mentioned in #15 .
@IsmaelMartinez  Do you have an ideia why this works? Also, could we probably "trick" teams into thinking that it is minimized without really minimizing it?

I know you don't want to spend time on this, but I can try to work it out if you have some idea. :)

**Comment by IsmaelMartinez** [comment]
I think is because that is the way it works on the browser (Chrome) so it doesn't really know the screen is not on focus.

**Comment by abmantis** [comment]
@IsmaelMartinez but why does minimizing the window "solves" it? Also, on Chrome, changing to another tab also works.

**Comment by IsmaelMartinez** [comment]
I have no idea, some internal chrome/electron thing. Check this out: https://github.com/electron/electron/issues/5900
