### ISSUE TITLE
please support proxy config; like set 127.0.0.1:7890

### ISSUE THREAD

**Issue by newyorkthink** [IsmaelMartinez/teams-for-linux#1120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...]
 - Version [e.g. 0.1.17]

**Additional context**

**Comment by RolandRosenfeld** [comment]
Why not use `--proxy-server=http://localhost:7890` option?
See https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md

**Comment by newyorkthink** [comment]
> --proxy-server=http://localhost:7890

can you make backup settings and add port config in gui

like ferdium is can

**Comment by jijojosephk** [comment]
Proxy support is already there. Isn't that working?

**Comment by IsmaelMartinez** [comment]
closing due inactivity
