### ISSUE TITLE
Open chat in new window

### ISSUE THREAD

**Issue by dxps** [IsmaelMartinez/teams-for-linux#1121]
**Is your feature request related to a problem? Please describe.**
I remember that last time I used Microsoft's app it had the option to open a certain chat in a new window.
Obviously, that's extremely handy when you have to talk in multiple chats/topics.
This version does not have it and I really miss it.

Is this planned for a future release?

Thanks in advance for considering it! :pray:

**Comment by jijojosephk** [comment]
Not possible at the moment because it's not in our control.
