### ISSUE TITLE
Mute conversation notifications

### ISSUE THREAD

**Issue by vamts** [IsmaelMartinez/teams-for-linux#1123]
It would be great if it is possible to disable specific conversation notifications similar to the web browser client.

![2024-02-27_08-07](https://github.com/IsmaelMartinez/teams-for-linux/assets/141237006/8d6005db-8256-4cca-9e72-8c20325f4689)

**Comment by jijojosephk** [comment]
Can you describe your problem in detail?

**Comment by vamts** [comment]
There is currently no option for turning off the notifications on a specific conversation. The screenshot above shows the option, available in the web interface. Ideally, there should be a similar functionality implemented in teams-for-linux.

**Comment by IsmaelMartinez** [comment]
If that is available in the web interface, it should be available in the app without us needing to implement anything. Are you not seeing this in teams-for-linux?

**Comment by vamts** [comment]
![teams_no_notification_mute](https://github.com/IsmaelMartinez/teams-for-linux/assets/141237006/8f8d5fbb-a4dd-4d05-be8e-7e33a951b6fa)
No, currently the option "Turn off notifications" is missing.

**Comment by IsmaelMartinez** [comment]
This is a MS side option that we don't have control. We only control what goes around the browser, but not what goes in it. I suspect this is a teamsv2 change. Sorry, but we can't do much on this.
