### ISSUE TITLE
Does not open Security Window when authenticating via security key

### ISSUE THREAD

**Issue by timur-tabi** [IsmaelMartinez/teams-for-linux#1126]
**Describe the bug**
Our company switched to using a USB "YubiKey" device for authentication.  When logging in via Teams PWA, a second browser window opens where I need to key in my PIN and then touch a sensor on the YubiKey.

This doesn't work in teams-for-linux.  The app says:

"Face, fingerprint, PIN or security key
Your device will open a security window. Follow the instructions there to sign in."

But that window never appears, so I'm not prompted to enter my PIN.

**To Reproduce**
1. Set up YubiKey
2. Try to log in

**Screenshots**
This is what I see when I start teams-for-linux:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/1065860/1dca3078-5dc1-41d7-8ff0-0939ea97289a)

When I select "Face, fingerprint, PIN, or security key", I get this window:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/1065860/50e70efa-572d-4323-a9ae-9707061cc54c)

Compare that with Teams PWA:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/1065860/076f8901-1400-4e2e-838c-dea0c7a5af8f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...] apt package as per instructions
 - Version [e.g. 0.1.17] 1.4.12

**Comment by jijojosephk** [comment]
@timur-tabi electron does not support this API yet. As far as I know. Hence we have a limitation at the moment to implement this.

**Comment by jijojosephk** [comment]
Have a look at these #972 #802
