### ISSUE TITLE
ARM64 / AARCH64 Fedora Screen Sharing Is Upside Down

### ISSUE THREAD

**Issue by changyp6** [IsmaelMartinez/teams-for-linux#1130]
**Describe the bug**
Install teams-for-linux from repo.teamsforlinux.de using command
`sudo dnf install teams-for-linux`
in `Fedora 39 aarch64 KDE` desktop

Start a conversation, then start "sharing", select whole desktop or window, the shared screen is shown upside-down

**Desktop (please complete the following information):**
 - OS: [Fedora 39 aarch64]

**Comment by IsmaelMartinez** [comment]
Can you provide the version information? I believe there was a bug for a bit so this might be solved in the latest version (1.4.12 ?)

**Comment by changyp6** [comment]
> Can you provide the version information? I believe there was a bug for a bit so this might be solved in the latest version (1.4.12 ?)

Thank you for your reply!
I believe I installed the latest version, because I installed it from the software repo.
https://repo.teamsforlinux.de

**Comment by jijojosephk** [comment]
Are you on `wayland` ?

**Comment by jijojosephk** [comment]
Is this related to #1090

**Comment by jijojosephk** [comment]
@changyp6 did you check #1090

**Comment by changyp6** [comment]
> @changyp6 did you check #1090 

My AARCH64 box cannot work with X11, so I can't test it in X11 KDE.

**Comment by jijojosephk** [comment]
It might be difficult to find the issue. If you can try and build locally, that would be great.

**Comment by IsmaelMartinez** [comment]
closing due inactivity (trying to keep the list of issues manageable). I do hope you did find a solution.
