### ISSUE TITLE
Teams stuck on "checking your credentials" message

### ISSUE THREAD

**Issue by jac77600** [IsmaelMartinez/teams-for-linux#1131]
Hello teams,

On ubuntu 22.04, I installed teams-for-linux 1.4.10.
But when I launch it, Teams stuck on "checking your credentials" message.

Can you help me?

Thank you in advance.

**Comment by jijojosephk** [comment]
Can you provide system info and package used?

**Comment by jac77600** [comment]
I have :

# uname -a
Linux xxxxxx 6.1.0-1033-oem #33-Ubuntu SMP PREEMPT_DYNAMIC Thu Feb  1 19:38:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy


# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


# snap info teams-for-linux
name:      teams-for-linux
summary:   Teams for Linux
publisher: ismael (ismaelmartinez)
store-url: https://snapcraft.io/teams-for-linux
license:   GPL-3.0
description: |
  
snap-id: IIAJhVGfBhm393UTagoW5awtZlPDGqHd
channels:
  latest/stable:    1.4.10 2024-02-05 (523) 89MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      1.4.10 2024-02-05 (523) 89MB -


Thank you !

**Comment by jac77600** [comment]
Hello,

I have this error :
teams.microsoft.com/:1         Unrecognized Content-Security-Policy directive 'prefetch-src'.

Does that remind you of something ?

Thank you

**Comment by jijojosephk** [comment]
@jac77600  can you try any other package? `deb` or `rpm` depending on which distribution you're using.

https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.13

**Comment by jac77600** [comment]
Hello @jijojosephk,

I installed the package ".deb", it works.

Thank you very much !!

**Comment by jijojosephk** [comment]
Closing this as the native package works.
