### ISSUE TITLE
Cannot access View settings in a meeting

### ISSUE THREAD

**Issue by tomk3003** [IsmaelMartinez/teams-for-linux#1135]
Using the latest version 1.4.13 under linux mint cinnamon.

When in a meeting clicking on "View" does not show the dropdown where i could select e.g. "Turn off incoming video".
Clicking on "React" also does nothing.

I already deleted `~/.config/teams-for-linux/` without effect.

**Comment by jijojosephk** [comment]
Is it still a problem. I see it's working.

**Comment by tomk3003** [comment]
Yes it is. Clicking on "View" does nothing at all.

**Comment by jijojosephk** [comment]
It would be good to specify which desktop environment , distro and installed package type and version.

**Comment by jijojosephk** [comment]
I didn't face this issue.

**Comment by tomk3003** [comment]
I am using Linux Mint Cinnamon (latest Version) with the latest Version from the Mint Repo, which seems to be the latest Version from Flathub (1.4.13).

**Comment by jijojosephk** [comment]
ok. I assume you're talking about this one. It works for me. Are you saying you're not able to see this list at all?

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/99050326-2830-4357-ae3f-c2ed0d5d72ff)

**Comment by tomk3003** [comment]
Exactly. When in a meeting klicking on "View" does not show the drop down menu. Nothing happens.

**Comment by tomk3003** [comment]
Joining the meeting produces:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/15907646/2e9ac56e-4e3d-400e-b2ee-856b384d54f3)
in console. Clicking on View does not add anything new.
Besides that: the console is full of errors (69) and warnings (691).

**Comment by IsmaelMartinez** [comment]
can you try with rpm/deb packages? it can perfectly be a configuration shenanigans of flatpack. Saying this as 403's as normally permissions and flatpack, like snap, does some confinement that can be iffy in some configurations/systems.

Regarding the errors in the console they normally are in MS land, specially the warnings.

**Comment by tomk3003** [comment]
Nope, the Debian package shows exactly the same behavior.
I checked with the web version and everything is working as expected there.

**Comment by IsmaelMartinez** [comment]
Can you confirm if you are using teams v2? Some things are probably broken as MS moved from Angular to React and we had a few hacks with angular. See https://github.com/IsmaelMartinez/teams-for-linux/issues/1006#issuecomment-2015990266

**Comment by tomk3003** [comment]
How can I check that? I did the switch on my Windows Teams at work.
Does this affect the Linux version too?

**Comment by IsmaelMartinez** [comment]
More info in here.

https://github.com/IsmaelMartinez/teams-for-linux/issues/1006#issuecomment-1895555921

Basically, open the debug, and enter `document.location.href`

If it starts with  'https://teams.microsoft.com/v2/' then you are in v2.

I suspect a lot of people will be already in v2

**Comment by IsmaelMartinez** [comment]
More info in here.

https://github.com/IsmaelMartinez/teams-for-linux/issues/1006#issuecomment-1895555921

Basically, open the debug, and enter `document.location.href`

If it starts with  'https://teams.microsoft.com/v2/' then you are in v2.

I suspect a lot of people will be already in v2

**Comment by IsmaelMartinez** [comment]
I think this is the same as #1150 . The menu is there but just far too high so you don't see it

**Comment by IsmaelMartinez** [comment]
Closing as a duplicate (and the duplicate has a workaround). 

If you can try starting with the `teams-for-linux --force-device-scale-factor=1.1` option and see if that works, we might have a PR with that as a config option soonish

**Comment by tomk3003** [comment]
Yes, adding this to config.json worked. The menu opens as expected.
Thanks!

**Comment by IsmaelMartinez** [comment]
How did you add it to the config.json file? I am confused as the other person asked if we can add this as a config option so they don't need to add it to the command line argument 😂

**Comment by tomk3003** [comment]
Yes adding this to config.json fixes it.
Thanks!

**Comment by IsmaelMartinez** [comment]
not a problem. We will see if we can add that as a config option so people can just have it in their config file.
