### ISSUE TITLE
Configuration file has to be a regular file, and can not be a symbolic link

### ISSUE THREAD

**Issue by dschrempf** [IsmaelMartinez/teams-for-linux#1137]
**Describe the bug**
The configuration file `config.json` is silently ignored, when the file is not regular, but, for example, a symbolic link.

The following `info` message is printed (but the log level has to be amended so the message is visible):

    [INFO] No config file found, using default values

**Expected behavior**
Either the configuration file is read and interpreted, or a warning log message is printed so the message is visible by default.

**Comment by jijojosephk** [comment]
We can change INFO to WARN

**Comment by dschrempf** [comment]
Thank you!

**Comment by SuperTux88** [comment]
>  The configuration file `config.json` is silently ignored, when the file is not regular, but, for example, a symbolic link.

I can't reproduce that, my `config.json` is a symbolic link and it works perfectly fine. Maybe check if your symbolic link points to the correct location or if something else prevents reading it (permissions?).

**Comment by jijojosephk** [comment]
@dschrempf `1.4.14` is released.

**Comment by dschrempf** [comment]
> > The configuration file `config.json` is silently ignored, when the file is not regular, but, for example, a symbolic link.
> 
> I can't reproduce that, my `config.json` is a symbolic link and it works perfectly fine. Maybe check if your symbolic link points to the correct location or if something else prevents reading it (permissions?).

That's weird. I am using Home-Manager to manage my configuration files, and so the location must have been correct. The only difference is maybe that the link points out of the user home directory. Could this be the reason? @SuperTux88

**Comment by SuperTux88** [comment]
I don't know, my symlink points to inside the home directory, but outside of the teams-for-linux folder.
