### ISSUE TITLE
Tweaks to reduce RAM usage?

### ISSUE THREAD

**Issue by joakim-tjernlund** [IsmaelMartinez/teams-for-linux#1142]
**Is your feature request related to a problem? Please describe.**
Is it possible to tweak build and/or run time options to lower Teams RAM usage?

**Describe the solution you'd like**
Project applies build options lowering RAM usage or specify  run time options.

**Additional context**
Also, ffmpeg and mesa are bundled in the app.
Would be great if release notes and/or About window could report which upstream versions of
these are bundled so one can replace these with matching system versions .

**Comment by IsmaelMartinez** [comment]
Hi @joakim-tjernlund , Thanks for the request. 

I would appreciate if you can replace this issue with the feature request template, as it helps getting a better understanding of the request. 

This application is an electron base app, that uses electron-builder(https://www.electron.build/index.html) for the bundling. I am not sure if there are ways of using the ffmpeg and mesa you system has, as those will probably part of the electron bundle, but I have no idea. 

Looking around I can only see references on how to include your own ffmpeg in electron-builder like in here https://stackoverflow.com/questions/47848621/how-can-i-bundle-ffmpeg-in-an-electron-application what makes me think it might just be related to the packaging system you are using.

Can you let us know what bundling you got? Can you try with deb or rpm? It could be you are seeing snap or flapak playing around, so its always worth a shot. Hope helps!

**Comment by joakim-tjernlund** [comment]
> Hi @joakim-tjernlund , Thanks for the request.
> 
> I would appreciate if you can replace this issue with the feature request template, as it helps getting a better understanding of the request.

Did some edits in that direction.

> 
> This application is an electron base app, that uses electron-builder(https://www.electron.build/index.html) for the bundling. I am not sure if there are ways of using the ffmpeg and mesa you system has, as those will probably part of the electron bundle, but I have no idea.

One can replace ffmpeg/mesa libs with a symlink to system libs. This has been done before in Gentoo
electron pkgs, the former ms-teams had this option  

> 
> Looking around I can only see references on how to include your own ffmpeg in electron-builder like in here https://stackoverflow.com/questions/47848621/how-can-i-bundle-ffmpeg-in-an-electron-application what makes me think it might just be related to the packaging system you are using.
> 
> Can you let us know what bundling you got? Can you try with deb or rpm? It could be you are seeing snap or flapak playing around, so its always worth a shot. Hope helps!

I am not building myself, just want to explore the above options.

**Comment by joakim-tjernlund** [comment]
I fond runtime options ```CHROMIUM_FLAGS="--lite-mode --optimize-for-size"``` but that didn't have much impact.
```
ps -ax -o comm,rss | grep teams
teams-for-linux 224896
teams-for-linux 49908
teams-for-linux 50348
teams-for-linux  8748
teams-for-linux 156664
teams-for-linux 82256
teams-for-linux 683836
teams-for-linux 60884
```

**Comment by IsmaelMartinez** [comment]
I wonder if the MS version didn't include ffmpeg had this option as it wasn't using the full webview we use. See if you can find an example on how to disable ffmpeg/mesa with the symlinks (and/or even open an PR with it if you are brave enough )

**Comment by joakim-tjernlund** [comment]
> I wonder if the MS version didn't include ffmpeg had this option as it wasn't using the full webview we use. See if you can find an example on how to disable ffmpeg/mesa with the symlinks (and/or even open an PR with it if you are brave enough )

This was done i Gentoo simple by doing:
```
	# Use system ffmpeg, if wanted. Might crash MS Teams!
	if use system-ffmpeg; then
		rm -f "${D}"/${dest}/share/teams-insiders/libffmpeg.so
		dosym "../../$(get_libdir)/chromium/libffmpeg.so" "${dest}/share/teams-insiders/libffmpeg.so"
	else
		# Otherwise keep the executable bit on the bundled lib
		doexe "${S}"${dest}/share/teams-insiders/libffmpeg.so
	fi

	# Use system mesa, if wanted. Might Crash MS Teams!
	if use system-mesa; then
		rm -f "${D}"/${dest}/share/teams-insiders/libEGL.so
		rm -f "${D}"/${dest}/share/teams-insiders/libGLESv2.so
		rm -f "${D}"/$dest/share/teams-insiders/swiftshader/libEGL.so
		rm -f "${D}"/$dest/share/teams-insiders/swiftshader/libGLESv2.so
	else
		# Otherwise keep original executable flag
		doexe "${S}"/${dest}/share/teams-insiders/libEGL.so
		doexe "${S}"/${dest}/share/teams-insiders/libGLESv2.so
		doexe "${S}"/${dest}/share/teams-insiders/swiftshader/libEGL.so
		doexe "${S}"/${dest}/share/teams-insiders/swiftshader/libGLESv2.so
	fi
```
There was not difference i function for MS Teams when using system libs

I did a quick test doing the same for teams-for-linux and it crashed. I guess it could be
that you use ffmpeg 6.x? I am still stuck on ffmpeg-4.x

Knowing what versions you build against is required for this king of thing, hence this ticket.

**Comment by IsmaelMartinez** [comment]
we are using version 29.1.x (I think is 1) that I believe it uses chromium 122.0.6261.95 and I think in https://chromium.googlesource.com/chromium/src/+/refs/tags/122.0.6261.95 you will have the ffmpeg version that I do suspect is going to be newer than 4.x . Hope helps and let us know what you find!

**Comment by joakim-tjernlund** [comment]
Yes it does, ATM I have ffmpeg 4.x so I need to move on to v6 then.
Any clue about mesa? I tried mesa 23.3.x but that failed.

**Comment by IsmaelMartinez** [comment]
No idea but it should be in that repo I linked, or googling that chrome
version you should be able to find it

**Comment by joakim-tjernlund** [comment]
Some initial finding:
ffmpeg-6.1.x appear to work.
mesa-24.0 trows errors in console but starts teams-for-linux:
```
[18233:0424/224444.534895:FATAL:gpu_init.cc(578)] Passthrough is not supported, GL is angle, ANGLE is 
[18190:0424/224444.759217:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=5
[18190:0424/224444.777013:ERROR:browser_main_loop.cc(280)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[18190:0424/224444.777177:ERROR:browser_main_loop.cc(280)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[18190:0424/224444.777230:ERROR:browser_main_loop.cc(280)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[18190:0424/224444.777277:ERROR:browser_main_loop.cc(280)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[18190:0424/224444.778286:ERROR:browser_main_loop.cc(280)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[ERROR] Failed to fetch custom background remote configuration. net::ERR_CONNECTION_REFUSED
[18255:0424/224444.821265:FATAL:gpu_init.cc(578)] Passthrough is not supported, GL is angle, ANGLE is 
[18190:0424/224444.824721:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=5
[18263:0424/224444.890616:FATAL:gpu_init.cc(578)] Passthrough is not supported, GL is angle, ANGLE is 
[18190:0424/224444.893965:ERROR:gpu_process_host.cc(997)] GPU process exited unexpectedly: exit_code=5
[18270:0424/224444.957604:ERROR:gl_display.cc(515)] EGL Driver message (Error) eglCreateContext: eglCreateContext
[18270:0424/224444.957679:ERROR:gl_display.cc(515)] EGL Driver message (Error) eglCreateContext: eglCreateContext
[18270:0424/224444.957717:ERROR:gl_context_egl.cc(396)] eglCreateContext failed with error EGL_BAD_ATTRIBUTE
[18270:0424/224444.960333:FATAL:gpu_init.cc(578)] Passthrough is not supported, GL is angle, ANGLE is swiftshader
```

Any idea why? (Using teams V2)

**Comment by IsmaelMartinez** [comment]
sorry, I have no idea about mesa. I know it means table in spanish but that is a much as I can help. I leave it open to see if someone else can help.

**Comment by IsmaelMartinez** [comment]
@joakim-tjernlund , did you manage to get more insights on the Mesa ? Does the RAM consumption is lower by using the script to use your local ffmpeg-6.1.x , instead of the one electron provides? If you can put a resume of the status that would be great. Thanks in advance!

**Comment by joakim-tjernlund** [comment]
Didn't get that far. system ffmpeg 6.1.x appeared to work but microphone was just silent.
System mesa 24.0.x works but I lost HW accel .

**Comment by IsmaelMartinez** [comment]
Closing this as I don't know what else to do. Do share if you get anywhere. Ta
