### ISSUE TITLE
Cannot allow webcam

### ISSUE THREAD

**Issue by XargonWan** [IsmaelMartinez/teams-for-linux#1143]
**Describe the bug**
When I turn on the camera it asks for the allowance on the ominbar, but there is no omnibar so I cannot allow the camera, therefore the camera cannot work.

**To Reproduce**
1. Enter in a call
2. Click on Webcam to enable it

**Expected behavior**
I should be able to reach that "ominbar" (or similar) and enable the webcam.

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6771419/bc117da4-78c9-411d-9dbb-f96fa36b9302)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Installation package: Flatpak
 - Version 1.4.13

**Comment by IsmaelMartinez** [comment]
This looks duplicated by https://github.com/IsmaelMartinez/teams-for-linux/issues/989 , can you have a look at the workaound? This is probably related to flatpak configuration. Can you use another packaging type? Thanks

**Comment by XargonWan** [comment]
I'm still on flatpak, I tried the workaround and it's working. thanks!
Is there any fix planned?

**Comment by IsmaelMartinez** [comment]
I will leave this open for a bit and see if anyone can do a bit of investigation and/or fix it. I had a quick look but couldn't find where to set that "secure": true in electron code.

**Comment by IsmaelMartinez** [comment]
I will close it as there is a working workaround and we got plenty of other issues on the plate (and couldn't find anything interesting). Sorry!
