### ISSUE TITLE
Fails to start with flatpak

### ISSUE THREAD

**Issue by llem00n** [IsmaelMartinez/teams-for-linux#1144]
**Description**
Fails to start using flatpak

**To Reproduce**
Run
`$ flatpak run com.github.IsmaelMartinez.teams_for_linux`

See the following output:
```
LaunchProcess: failed to execvp:
xdg-settings
[2:0318/130221.460924:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
[2:0318/130221.460944:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
```

**Expected behavior**
Application starts and opens a new window

**Desktop**
 - OS: Arch Linux
 - Flatpak
 - Version 1.4.13
 - Desktop: Plasma 6
 - Desktop session: Wayland

**Additional info**
Started happening to me after i ran the following commands:
```
$ flatpak --user override --filesystem=/home/$USER/.icons/:ro
$ flatpak --user override --filesystem=/usr/share/icons/:ro
```
As suggested in [This](https://www.reddit.com/r/kde/comments/yi6kfu/comment/iuig6c9/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) Reddit answer about a bad cursor question.

But the error message was different, something about flatpak not sharing /usr/share/icons. Then I ran 
```
$ flatpak --user override --reset
```
And the problem with desktop appeared instead.

**Comment by IsmaelMartinez** [comment]
This looks like a flatpak config issue. Can you try another packaging system? Ta

**Comment by Mikaela** [comment]
I think your solution is running `flatpak run com.github.IsmaelMartinez.teams_for_linux --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations` especially the `--ozone-platform-hint=auto` part which you could also replace with `--ozone-platform-hint=wayland`

Assuming enough recent Electron is used, you could also `flatpak override com.github.IsmaelMartinez.teams_for_linux --env=ELECTRON_OZONE_PLATFORM_HINT=auto`

**Comment by llem00n** [comment]
Does the trick, thank you!
