### ISSUE TITLE
Teams doesn't remember the setting "disable notification sound"

### ISSUE THREAD

**Issue by TheRolf** [IsmaelMartinez/teams-for-linux#1146]
**Describe the bug**
Teams doesn't remember to turn off notification sound, I have to turn them off after every single startup.

**To Reproduce**
1. Right click -> Notifications -> Disable notification sound
2. Right click -> Settings -> Save settings
3. Notification sounds are disabled
4. Restart teams-for-linux
5. Notifications have sound again

**Expected behavior**
It should remember the last setting and not turn back notification sound again.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Ubuntu 22.04

**Additional context**
N/A

**Comment by IsmaelMartinez** [comment]
This is probably related to teams v2. See the affected areas in https://github.com/IsmaelMartinez/teams-for-linux/issues/1006#issuecomment-2015990266

**Comment by IsmaelMartinez** [comment]
Actually, checked and MS hasn't changed anything that makes me think this is probably snap containment. Are you using snap? If so, can you try deb? Ta

**Comment by IsmaelMartinez** [comment]
This is more of an enhancement than a bug. If you want to keep those preferences then you should apply them via a config.json file. Arguably it will be nice if changing settings in the UI creates a config.json file with the new settings, so keeping it open on that propose.

**Comment by jijojosephk** [comment]
@TheRolf new version has your requested changes. Kindly test it.

**Comment by TheRolf** [comment]
YES it works, thanks a lot! 

(sorry didn't get notifications from this thread)
