### ISSUE TITLE
Notification urgency control

### ISSUE THREAD

**Issue by Kommynct** [IsmaelMartinez/teams-for-linux#1147]
**Is your feature request related to a problem? Please describe.**
Right now the urgency of the notifications is set to low, which, in my config, causes them to disappear promptly

**Describe the solution you'd like**
Literally every single messaging app uses the normal urgency instead of low, this should either be matched or configurable

**Comment by IsmaelMartinez** [comment]
Hi @Kommynct,

Appreciate the request. Do you have more info on how to archive this? We are a small community and appreciate PRs and/or any info that can help us understand how to solve/identify problems.

I have no idea where to look at, at the moment.

Can you give us some help? Ta

**Comment by Kommynct** [comment]
You can take a look at the notify-send code https://github.com/GNOME/libnotify/blob/master/tools/notify-send.c

notify-send --urgency=low/normal/critical

currently teams is set to low.

**Comment by jijojosephk** [comment]
@Kommynct currently the app does not use electron's `Notification` module. It uses the default. We can consider an enhancement to it.

**Comment by mozo78** [comment]
>Now app lets user choose the notification method and notification urgency.

Excuse me but I can't see where I can switch it from. Can you help me?

**Comment by jijojosephk** [comment]
You can use `config.json` or from command line. Please read https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/7c486a40-f1fc-4697-99bd-342b69fb6a17)

```json
{
"notificationMethod" : "electron",
"defaultNotificationUrgency": "normal"
}
```

**Comment by jijojosephk** [comment]
@mozo78 You can't do that from UI yet. Try with the config values.

**Comment by mozo78** [comment]
Thank you! Can we expect an UI option in the future?

**Comment by jijojosephk** [comment]
Yes, we can have one under `Menu`->`Notifications`->`Urgency`

**Comment by jijojosephk** [comment]
Please check version `1.4.26`

**Comment by mozo78** [comment]
Thank you very much!
