### ISSUE TITLE
Trying to download an attachment makes the app freeze

### ISSUE THREAD

**Issue by callegar** [IsmaelMartinez/teams-for-linux#1148]
**Describe the bug**

When someone uses the chat to send a file, trying to download it (by using the three-dots) makes the application hang.

**To Reproduce**
1. Go to the chat
2. Open a chat where there is a file sent to you
3. Press the three dots and download
4. See application hang

**Expected behavior**
Download dialog should open asking you where to download or at least the file should be downloaded to the default location

**Screenshots**
A completely black window appears.

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...] flatpak
 - Version [e.g. 0.1.17] 1.4.13

**Additional context**
The same operation succeeds when using teams classic on the web in Firefox.

**Comment by IsmaelMartinez** [comment]
can you try with another packaging system? flatpak, like snap, can create funny situations due confinement. Ta

**Comment by jijojosephk** [comment]
@callegar  if you're on GNOME probably the save dialog is behind the app window. Its a known issue with GNOME for quite sometime.

**Comment by hackguy25** [comment]
Can confirm the bug on Fedora 39 with KDE, installed via Flathub. There is no save dialog window anywhere. The window can be moved around, but the contents are completely frozen, and one CPU thread is pegged at 100% utilization.

**Comment by IsmaelMartinez** [comment]
Can you try another packaging system? Snap and flatpack can be iffy on their configurations, meaning this can be a side effect of an issue with your flatpack/hub config

**Comment by hackguy25** [comment]
I have restarted my computer, and the issue went away: Now a save dialog appears, and the file can be saved to disk. It seems to be intermittent on my machine.
