### ISSUE TITLE
Feature request: Sync microphone mute with audio source

### ISSUE THREAD

**Issue by c0d3z3r0** [IsmaelMartinez/teams-for-linux#1149]
**Is your feature request related to a problem? Please describe.**
Having no mic mute indicator on OS level or hw level (mute LED hidden, because lid closed) makes it hard to determine if you're currently muted or not. Other people don't see you as muted as well.
On Windows the button is synced.

**Describe the solution you'd like**
It would be great if there was a way to sync the teams mute button with the currently used audio source mute status.
At least teams detects that the microphone is muted on OS level so it might be possible to intercept that and toggle the mute button.

**Describe alternatives you've considered**
Currently I'm using a custom mute indicator on OS level based on dzen2. It's just a weird hack, though.

**Additional context**
none

**Comment by jijojosephk** [comment]
@c0d3z3r0 Kindly use the template when raising issues. Nonetheless, the requirement seems impossible to achieve. Kindly understand that this application is a wrapper around the web app and we're working on our limits.

**Comment by IsmaelMartinez** [comment]
Hi @c0d3z3r0 , feel free to have a wee look around in electron and see if you can find a way to archive this. 

I do agree on the using the template for issues/enhancements as it saves us a lot of back and forward conversations and, sometimes, they drive people to a solution.

**Comment by c0d3z3r0** [comment]
Yeah sorry for the template thing. I usually do it, just dropped it because it was a feature request :) Fixed now!

**Comment by IsmaelMartinez** [comment]
I think this is duplicated by https://github.com/IsmaelMartinez/teams-for-linux/issues/1149
