### ISSUE TITLE
Account Verification code authentication not possible

### ISSUE THREAD

**Issue by mohc** [IsmaelMartinez/teams-for-linux#115]
Where the user account is a guest account there is no dialog for the 'Account verification code'.  Instead the authentication goes to the password entry dialog.  This is no use because the account has no password.

(Note. Microsoft bizarrely does not allow work email addresses to be used to create accounts, so it is not possible to register the account and set a password outside of teams).

**To Reproduce**
Login as new user or user with no Azure AD account.
Password dialog is displayed

**Expected behavior**
Enter Code dialog should be displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/1655735/56806601-48bd7d00-6824-11e9-8949-f9a1b5b64fc9.png)

![image](https://user-images.githubusercontent.com/1655735/56806551-27f52780-6824-11e9-9419-baafc86911e0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18-04
 - Snap
 - Version 0.1.18

**Comment by IsmaelMartinez** [comment]
Hi @mohc ,

That looks like an issue for MS itself:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35611051-bug-when-logging-in-as-guest-with-2-step-validatio

Maybe not that one, but check on their uservoice channel.

Thanks,
