### ISSUE TITLE
"View" and "More" buttons not working

### ISSUE THREAD

**Issue by c0d3z3r0** [IsmaelMartinez/teams-for-linux#1150]
**Describe the bug**
In a call clicking "View" or "More" triggers buttons but the menus don't show up. "People", "Apps" and other buttons work fine. For a very short amount of time it looks like the menu pops out to the top.
https://github.com/IsmaelMartinez/teams-for-linux/assets/6205797/48668a05-82cc-48a6-b347-d83b9ae435ac

Edit:
The menu is there and I can move it down \o/

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6205797/889f2889-9e7f-48bd-bccb-1fdbe8915383)
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6205797/3020e90a-9063-4116-8e74-b36e5bc44664)

**To Reproduce**
In a call click "View" or "More"

**Expected behavior**
Web app:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6205797/2144c0f1-4163-476b-b63a-c44dbd02dc7a)

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Installation package: deb
 - Version 1.4.14

**Additional context**
Clearing storage via menu and `rm -r .config/teams-for-linux` did not help.

**Comment by IsmaelMartinez** [comment]
Can you confirm if you are using teams v2? Some things are probably broken as MS moved from Angular to React and we had a few hacks with angular. See https://github.com/IsmaelMartinez/teams-for-linux/issues/1006#issuecomment-2015990266

**Comment by c0d3z3r0** [comment]
Looks like v1, but one weird thing I just noticed is that during a call, Teams switches from light theme to dark theme o.O Maybe that's related.
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6205797/1315e28b-a271-49e3-b1d1-9c194668ad35)

**Comment by IsmaelMartinez** [comment]
I tried on mine and v1 and works fine. Can you provide the desktop env? GNOME is a bit iffy with dialogs.

**Comment by c0d3z3r0** [comment]
XFCE 4.18, GTK 3.24.41, Debian testing

**Comment by IsmaelMartinez** [comment]
can you check if you got the same problem just using the browser? Just checking if it is not an OS config problem. Ta

**Comment by c0d3z3r0** [comment]
No, it's fine in the Browser. See "Web app" screenshot in the first post

**Comment by IsmaelMartinez** [comment]
Are you using the CSS themes? Those might be broken and/or need a wee tweak.

**Comment by c0d3z3r0** [comment]
No, nothing special. Clean install. I also tested the AppImage today which doesn't make any difference.

**Comment by IsmaelMartinez** [comment]
This is really odd... I can only thing that your chrome client is playing with us, or that the 1.4.14 is iffy. Can you try 1.4.9 and then the pre-release 1.4.15? Really strange. 

A hack would be to add whatever you want to alter in CSS in a file and use the customCSSLocation option to load the file. Really dirty but I can't think of anything else it could be playing with this. Sorry.

**Comment by c0d3z3r0** [comment]
1.4.15 has the problem as well. However, now the More button works but React and View is broken :rofl:
Will do some more tests later...

**Comment by IsmaelMartinez** [comment]
The workaround will be to move those buttons with CSS... Really hacky but I can't think of anything else. 

Can you change the size of your screen and see if that affects the positioning?

**Comment by c0d3z3r0** [comment]
It's totally indeterministic... sometimes "More" works, sometimes not... :laughing: I will try to track down the issue when I have some time...

**Comment by c0d3z3r0** [comment]
I found a solution... not nice but works for now: setting the custom DPI in XFCE appearance settings to 107 instead of 108 makes the buttons work as expected.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6205797/159e0017-119b-4d5c-bf7f-14f8b10493a8)

**Comment by IsmaelMartinez** [comment]
What a legend ! Thanks a lot for finding a solution.

Aye, we got similar options implemented like the `config.ntlmV2enabled`

It does something like:

`app.commandLine.appendSwitch('enable-ntlm-v2', config.ntlmV2enabled);` so adding something similar should just work. 

If someone can open a wee PR I will be happy to review it. Otherwise it will need to wait a wee bit

**Comment by jijojosephk** [comment]
> I found a solution... not nice but works for now: setting the custom DPI in XFCE appearance settings to 107 instead of 108 makes the buttons work as expected.
> 
> ![image](https://private-user-images.githubusercontent.com/6205797/319099803-159e0017-119b-4d5c-bf7f-14f8b10493a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTM4OTMsIm5iZiI6MTcxMjk5MzU5MywicGF0aCI6Ii82MjA1Nzk3LzMxOTA5OTgwMy0xNTllMDAxNy0xMTliLTRkNWMtYmY3Zi0xNGY4YjEwNDkzYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTNUMDczMzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM0YTIxY2YxYTIyZjJhNWY4YWVhMThhYjQ2N2MxYWJkNjRjOGRlNTU5YTI2YmMxMWE3Y2YzZGU4ZWIxMWZjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MpJ0WLEslzzR6aXFBsJWnFx_OziefXa4ZZSKOWxRzH4)
> 
> There might be a bug in electron, since Teams works fine in Browser
> 
> **Edit:** `--force-device-scale-factor=1.1` instead of changing XFCE dpi solves all button problems. `config.js` currently does not recognize any native electron command line arguments. Could that be implemented?

`1.4.24` has it now. `pre-release`ed. https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.24

**Comment by jijojosephk** [comment]
@c0d3z3r0 you can add this to your `config.json`
```json
"electronCLIFlags":[["force-device-scale-factor",1.1]]
```

**Comment by c0d3z3r0** [comment]
Awesome, guys! Thanks :)
