### ISSUE TITLE
1.4.14 not available on Flathub

### ISSUE THREAD

**Issue by koelle25** [IsmaelMartinez/teams-for-linux#1151]
On [Flathub](https://flathub.org/de/apps/com.github.IsmaelMartinez.teams_for_linux) the latest version is still 1.4.13. Maybe you can push the new release there?

**Comment by dwbotsch** [comment]
Just checked and it's still at 1.4.13  on flathub. Thanks!

**Comment by IsmaelMartinez** [comment]
Hi, yes. This is a manual process that only one person does at the moment. Ideally we can automate it or at least get 2 people to be able to do it. I am waiting for @jijojosephk to, when he has the time, explain how it works. 

Lately we have been extremely busy with MS moving to react from angular, and to a new version of teams and breaking quite a few things.

Please use another package system in the meantime (we publish many). Ta

**Comment by jijojosephk** [comment]
Had a few challenges with the latest flathub builds. Just merged waiting for the build to complete. `1.4.16`. I'l update once it's done. Sadly it's a manual process. At least we need to have the `*appdata.xml` shared or automatically downloaded from the github repo. Could be an interesting work. But I'm severely lacking time. 

Please go to https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux and fork it.

Send a PR by changing the 2 files.

1. `com.github.IsmaelMartinez.teams_for_linux.appdata.xml` which contains release information. Currently flathub and this repo are having duplicate files. This is something we need to improve.
2. `com.github.IsmaelMartinez.teams_for_linux.yml`. This is the flatpak build manifest file. Usually this is modified 

```js
 sources:
      - type: file
        url: https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.4.16/teams-for-linux_1.4.16_amd64.deb
        sha256: 8507a00f3a562abafa8382d235027eb361fb0464ae01db242266e17e226cd968
```

**Comment by jijojosephk** [comment]
Just published the latest build. Flathub portal is super slow. But it's done from my end. Should be available for public in some time.

**Comment by IsmaelMartinez** [comment]
you are a legend! I will put that as a enhancement in another ticket and see if we can automate it once the storm calms down :) One issue at a time and take it easy.

**Comment by IsmaelMartinez** [comment]
Created an enhancement  in https://github.com/IsmaelMartinez/teams-for-linux/issues/1174 . I suspect it will take a long time until this happens but @koelle25 and @dwbotsch , do you want to give it a go for 1.4.17 (once it becomes a release today) and see if we can move from having only one person to having multiple people been able to do this? Always when you got time. Any help is extremely appreciated

**Comment by Bartwillemsen** [comment]
Thank you so much for working on all this, you are all legends <3

**Comment by IsmaelMartinez** [comment]
flathub now has 1.4.16 https://flathub.org/apps/com.github.IsmaelMartinez.teams_for_linux

<img width="647" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/353cf9d1-e1d3-4fa2-b4e4-51754faa107c">
