### ISSUE TITLE
Custom Background shows up as black

### ISSUE THREAD

**Issue by derekatkins** [IsmaelMartinez/teams-for-linux#1159]
**Describe the bug**
I followed the instructions at https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md#custom-backgrounds to add a custom background.  The thumb image shows up in the list.  However, when I select the image and either Preview or Apply, I get a black background.
The HTTP server logs show that the download succeeded for the main image, but it is not applied correctly.

**To Reproduce**
1. Start a call or meeting with video
2. Go to Bacground Filters
3. Click on my custom image
4. Scroll down to Preview
5. See error

**Expected behavior**
I expected it to show my image in the background.  It's a standard Jpeg, 1920 x 1080 size

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2531900/ef16a885-f374-4856-bce0-18d1b99501f5)

**Desktop (please complete the following information):**
 - OS: Linux -- Fedora 38
 - Installation package: RPM
 - Version teams-for-linux-1.4.13-1.x86_64

**Additional context**
The background is a custom corporate background so I don't feel like I can share it publicly.

**Comment by derekatkins** [comment]
Hi @IsmaelMartinez -- I don't have a desktop icon, so cannot use that to test if I'm on v2.
I did see message about asking to upgrade a week or so ago, but I clicked it away without approving it.  (Or maybe it was a warning that the old interface was going away).
I'll note that the thumbnail image DOES show up in the list correctly...  It's only the primary version that doesn't work.
I'm curious what is so different about the react version that background images wouldn't work?  You just need to supply an image, right?  Maybe it needs to be a PNG and not a JPG?

**Comment by IsmaelMartinez** [comment]
Is a bit more complex. We need to overwrite the image MS finds. https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/customBackgrounds.js#L29 so if angular is not there that line will fail. 

Do you get any errors in the web debug console? Something like 'Failed to override MS Method' or even a 'Failed to get app objects after 5 tries' would indicate it is not finding the angular component.

**Comment by derekatkins** [comment]
By "web debug console" do you mean the terminal where I run "teams-for-linux --customBGServiceBaseUrl=https://my.custom/url" ??  
If so, then no, no error messages.

**Comment by IsmaelMartinez** [comment]
Try with this

`teams-for-linux --customBGServiceBaseUrl=https://my.custom/url --webDebug`

**Comment by derekatkins** [comment]
Aha, that helped me track it down to the lack of Access-Control-Allow-Origin "*" header..  I thought I could set it in the htaccess file, but apparently not.  It appears to be working now.  
Thanks.
