### ISSUE TITLE
Teams 2.0 - Join button does not work

### ISSUE THREAD

**Issue by jkrysakowski** [IsmaelMartinez/teams-for-linux#1162]
**Describe the bug**
I run the new version of Teams, by providing the URL: `teams-for-linux --url=https://teams.cloud.microsoft/`
Application loads, everything displays, but the Join button in calendar does not work so I can't join any meeting.

In the dev tools I see:

![Przechwycenie obrazu ekranu_2024-03-29_13-30-29](https://github.com/IsmaelMartinez/teams-for-linux/assets/3762758/545e6f0a-2713-4413-b0e2-49d9d12a048f)

**To Reproduce**
1. Run `teams-for-linux --url=https://teams.cloud.microsoft/`
2. Go to calendar
3. Click "Join" on any meeting
4. Meeting window should open, but nothing happens.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 Ubuntu 22.04.4 LTS x86_64
 Desktop Environment: Xfce
 Window Manager: Xfwm4
 - Installation package:  Snap, latest/edge
 - Version: 1.4.16

**Comment by IsmaelMartinez** [comment]
hi, can you try with  `teams-for-linux --url=https://teams.microsoft.com/v2` ? I suspect this regex might be blocking that other url but https://teams.microsoft.com/v2 should take you to the same place

**Comment by jkrysakowski** [comment]
My answer was to quick, now I see the banner about the classic version again, so it's probably not V2

**Comment by IsmaelMartinez** [comment]
I don't think the banner is that cleaver but you can check if the changes implemented in https://github.com/IsmaelMartinez/teams-for-linux/pull/1160 does the trick for you. 

Basically open the web debug console, run `localStorage.setItem("tmp.isOptedIntoT2Web", true);` and then do a refresh (I think Alt+R or just refresh in the menu)

**Comment by IsmaelMartinez** [comment]
closing as the banner is duplicated by https://github.com/IsmaelMartinez/teams-for-linux/issues/1156
