### ISSUE TITLE
Not getting meeting notifications in version 1.4.16 with new Teams version (v2)

### ISSUE THREAD

**Issue by emailstorbala** [IsmaelMartinez/teams-for-linux#1164]
**Describe the bug**
Today I upgraded to Teams-for-linux v1.4.16. After this upgrade, I am not receiving notifications when a meeting is started. In version 1.4.15 with the new teams (v2), I was able to get the 'join' button but this is not happening in version 1.4.16.

**To Reproduce**
1. Migrate to new teams (v2)
2. Upgrade teams-for-linux to 1.4.16 version.
3. Whenever there is a meeting started by someone for which you are recipient, meeting notification is not coming.

**Expected behavior**
Whenever a meeting is started by someone, a notification should be received with a `join` button as like in 1.4.15 version.

**Screenshots**
I don't have a working screen shot from 1.4.15 version.

**Desktop (please complete the following information):**
 - OS: Debian/testing
 - Installation package - deb
 - 1.4.16

**Additional context**

**Comment by IsmaelMartinez** [comment]
I think this might be related to moving to V2 rather than the version update .

Can you:

* Close with "Clean the cache" option 
* Start from the terminal with `teams-for-linux --webDebug`

Then put any logs from both, the terminal and the browser debug screens in here, as that can be invaluable.

It can also be that MS Teams v2 doesn't have that pop up anymore.

**Comment by ChristoSnake** [comment]
My experience with v2 (across all Linux wrapper versions) is that sound notifications work under all circumstances - when Teams is closed, minimised to the taskbar or when the app is open with/without focus.

Visual notifications work **only when the Teams window has focus**:

![Screenshot_20240403_100006](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/5d15bdcd-3b26-498e-b66c-a3f7a932e2e9)

I have set up notifications for the Teams app in my KDE desktop as a workaround until the devs can assist us.  This works even when the app is minimised or closed (running in the background):

![Screenshot_20240403_095943](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/4dbe7035-e19a-48dd-9918-3b2ad8e3b278)

PS: The person who started this meeting does not have an avatar, but it will show if he did.

**Comment by emailstorbala** [comment]
@IsmaelMartinez  Yes you are correct. I am not seeing notifications for new calls in 1.4.15 version also. I am reverting back to the latest teams version as there is no difference.
I did like the 'Join' button in the notification window else I need to go to the calendar and join.

**Comment by IsmaelMartinez** [comment]
Hopefully they add it back. Ta
