### ISSUE TITLE
optInTeamsV2 does nothing

### ISSUE THREAD

**Issue by pulsar895** [IsmaelMartinez/teams-for-linux#1165]
**Describe the bug**

I tried to use the `optInTeamsV2` option to switch to the new version of Teams, but without success.

**To Reproduce**

  - Stop Teams
  - Edit `~/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux/config.json`
```json
{
  "closeAppOnCross": true,
  "minimized": true,
  "optInTeamsV2": true,
}
```
  - Start Teams
  - See the warning about Teams Classic

**Expected behavior**

From what I understand from the README, this option should force the switchover to the new Teams.

**Desktop (please complete the following information):**
 - OS: Fedora Workstation 39
 - Installation package: FlatPak
 - Version: 1.4.13

**Additional context**

I was able to solve the problem by specifying the `url` option like that:

```json
{
  "closeAppOnCross": true,
  "minimized": true,
  "optInTeamsV2": true,
  "url": "https://teams.cloud.microsoft"
}
```

**Comment by IsmaelMartinez** [comment]
Thanks for the info!

I think the 1st config option has an extra , and it should be like this

```
{
  "closeAppOnCross": true,
  "minimized": true,
  "optInTeamsV2": true
}
```

Currently we only support the URLs that are as  https://teams.microsoft.com/v2 the new format will probably give you problems with meeting links and the like.

**Comment by pvagner** [comment]
Hello,
I don't seem to be able to make it work as well.
I am on arch linux with electron 29 and teams-for-linux 1.4.14 installed.
My config is located at ~/.config/teams-for-linux/config.json 
and it reads:
```
{
	"spellCheckerLanguages": [
		"sk"
	],
	"optInTeamsV2": true,
	"url": "https://teams.microsoft.com/v2"
}
```

Have you got some more tips?

**Comment by sonnatager** [comment]
Unfortunately, the flatpak version is still on 1.4.13, although 1.4.16 was released last week. Maybe you can also release the new version to flatpak?

**Comment by IsmaelMartinez** [comment]
Regarding flatpack, that has been managed by @jijojosephk . @jijojosephk , do you mind sharing the steps to promote a flatpack build? Thanks!

**Comment by IsmaelMartinez** [comment]
Closing as that option is only available from the current pre-release 1.4.17.

**Comment by jijojosephk** [comment]
@sonnatager flatpak will have the latest version when it's marked stable here. It's a manual process though.

**Comment by pulsar895** [comment]
> Thanks for the info!
> 
> I think the 1st config option has an extra , and it should be like this
> 
> ```
> {
>   "closeAppOnCross": true,
>   "minimized": true,
>   "optInTeamsV2": true
> }
> ```
> 
> Currently we only support the URLs that are as https://teams.microsoft.com/v2 the new format will probably give you problems with meeting links and the like.

Okay, thanks for the feedback, but this URL also uses Teams Classic. Is there any way to force the use of the latest version of Teams?

**Comment by lurtz** [comment]
You need to use at least version 1.4.17 to be able to use Teams v2. With older versions I got still Teams Classic regardless how my config.json looked like.

**Comment by IsmaelMartinez** [comment]
I just marked 1.4.17 as latest release. If someone can follow the steps in https://github.com/IsmaelMartinez/teams-for-linux/issues/1174 to release it in flathub, and make any extra comments in that issue, that would be lovely and will help a lot.
