### ISSUE TITLE
U2C auth does not work

### ISSUE THREAD

**Issue by zhum** [IsmaelMartinez/teams-for-linux#1166]
**Describe the bug**
If U2C (fido2 yubikey) auth is required, it does not work.

**To Reproduce**
1. Need any U2C-enabled account, e.g. google, with yubikey authorized.
2. Insert your yubikey into working machine/laptop.
3. Try to auth using this account, after entering email press 'Use another auth method'
4. Select 'Face, fingreprint, ...'
5. The auth windows waits for the yubikey infinite time.

**Expected behavior**
After all steps there should a window, requesting yubikey device PIN, after entering the pin - asking you to press the button on the device and then authorize you.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - Installation package: deb
 - Version: 1.4.16

**Comment by IsmaelMartinez** [comment]
this is duplicated and unfortunately block by electron . See https://github.com/IsmaelMartinez/teams-for-linux/issues/1126
