### ISSUE TITLE
Classic Teams will soon be unavailable for use. To use the new Teams, update your browser to meet requirements or contact your IT admin. See requirements - Banner popping up

### ISSUE THREAD

**Issue by Dave172** [IsmaelMartinez/teams-for-linux#1168]
**Describe the bug**
A banner shows:
Classic Teams will soon be unavailable for use. To use the new Teams, update your browser to meet [requirements](https://teams.microsoft.com/_) or contact your IT admin. See requirements

**To Reproduce**
Open the App

**Expected behavior**
No banner should be shown, as "new teams" should be used

**Desktop (please complete the following information):**
Ubuntu 22.04 with latest snap version

**Comment by wojtekadams** [comment]
I'm observing the same thing in version 1.4.17

**Comment by Drezir** [comment]
I get same message even in firefox itself

**Comment by marchidaniele** [comment]
Me too this morning just opened with version 1.4.16 and Debian 12

**Comment by IsmaelMartinez** [comment]
Duplicated with https://github.com/IsmaelMartinez/teams-for-linux/issues/1156#issue-2207835928
