### ISSUE TITLE
Classic Teams stopped working

### ISSUE THREAD

**Issue by Bartwillemsen** [IsmaelMartinez/teams-for-linux#1169]
**Describe the bug**
Today I was working on Classic Teams, when suddenly the application forced me to login again to continue. After that, instead of going to Teams, the applcation redirects to the general Teams download page. See the included screenshot below.

**To Reproduce**
Open Teams. You're greeted with the above page instead of Teams.

**Expected behavior**
I want to be properly redirected to the Teams V2 environment.

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/1550822/65e43f03-0763-44db-a57c-0aab43e1cab9)

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Installation package: Flatpak
 - Version: 1.4.13

**Comment by Bartwillemsen** [comment]
Looks like the V2 fix should be released ASAP for all users as the Classic environment is officially dead and buried. :)

**Comment by IsmaelMartinez** [comment]
Can you try providing the URL as this?

`teams-for-linux --url=https://teams.microsoft.com/v2` and see if that does the trick? 

Otherwise see if there is a "continue in the browser" or similar link. MS likes to hide and change that link

**Comment by LoveSponge** [comment]
I have managed to move to the new microsoft teams via chromium by using a user-agent switcher to trick it into believing i'm using Edge (v118) on Windows.

The "continue in the browser" was not visibly an option for me at all to switch until i did this, and i was being redirected when i tried to go directly to `https://teams.microsoft.com/v2`

**Comment by Bartwillemsen** [comment]
@IsmaelMartinez I fixed it by redirecting to the new teams via the debug window. when undoing that, I also suddenly got the normal message that I was able to switch to the new Teams without using the "hack" to force it. Just mentioning it here as the "Out of the box experience" seems to get unstable sometimes while we are now in this transition period. This could cause confusion for new users so might be something to be aware of.

On the Download page there seems to be no "continue in the browser" window on that page particular page.

**Comment by stratosgear** [comment]
How did you redirect from the debug window? 

Thanks

**Comment by Bartwillemsen** [comment]
@stratosgear Open the web console: Click on Teams for Linux tray icon > Debug

Then enter this command: `document.location.href = 'https://teams.microsoft.com/v2'`

**Comment by codethief** [comment]
@stratosgear I suppose you could execute `window.location = "https://teams.microsoft.com/v2"` on the JavaScript console.

However, when I try that, I still see the yellow banner "The classic Teams will soon no longer be available […]" and on the console I see a message

```
[T1->T2 auto-redirection] Loading T1 - reason: 'User has not opted into T2'
```

So I guess, it's not as easy as opening some URL through the debug window.

**Comment by Bartwillemsen** [comment]
@codethief You then still need to add this to your localstorage first: `window.localStorage.setItem("tmp.isOptedIntoT2Web", true)` 

And then try to redirect again

**Comment by Bartwillemsen** [comment]
Yeah this fix is a known workaround as already discussed in #1156 .

**Comment by uksolidbeans** [comment]
> How did you redirect from the debug window?
> 
> Thanks
> 
> **Edited**: Apparently there was a flurry of issues the last days due to this "issue" and I failed to check them all. What worked for me was:
> 
> ```
> window.localStorage.setItem("tmp.isOptedIntoT2Web", true)
> document.location.href = 'https://teams.microsoft.com/v2/'
> ```
> 
> Sorry for the noise
> 
> **Edited2**: Also running on i3 and lacking a windowbar/toolbar (how is that called?), with a CTRL+SHIFT+I you can also open the debug console!!!

This helped me to get it working.

**Comment by jijojosephk** [comment]
Since the same discussion is there in #1156, closing this thread.
