### ISSUE TITLE
Voice and Video calls not working

### ISSUE THREAD

**Issue by pawelboh** [IsmaelMartinez/teams-for-linux#117]
**Describe the bug**
When i try to call there is info:
![image](https://user-images.githubusercontent.com/50030787/56832565-a37ac700-686c-11e9-8f2f-716d5a071168.png)

**To Reproduce**
1. Go to chat
2. Click on call
3. See error

**Desktop (please complete the following information):**
Gentoo Linux
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...] 
source
 - Version [e.g. 0.1.17]
0.2.0

**Comment by IsmaelMartinez** [comment]
Duplicated #100

**Comment by IsmaelMartinez** [comment]
As you are running from source, can you try:
* Changing the 3000 value in the following file/line to 5000?
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/index.js#L36

Also, can you translate the message? I assume something down the lines "the video is not supported in your browser"

Otherwise, try the following argument to be added to the starting arguments:
https://github.com/IsmaelMartinez/teams-for-linux/issues/35#issuecomment-474760816

Not closing just yet but I think is duplicated so no worth repeating myself over different issues that are the same. Thanks!

**Comment by pawelboh** [comment]
![image](https://user-images.githubusercontent.com/50030787/56835721-52230580-6875-11e9-85e2-47fa4c7deef6.png)

**Comment by pawelboh** [comment]
Didn't helped.

**Comment by IsmaelMartinez** [comment]
This seems to be also a MS one. Check in their uservoice page.
https://microsoftteams.uservoice.com/forums/555103-public

for example this one might be related:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/34872958-calling-to-a-external-party-which-is-busy

Hope helps,

**Comment by pawelboh** [comment]
No, person which i'm calling is not busy, also i'm not busy and no one can't call to me.

**Comment by IsmaelMartinez** [comment]
I don't think is related to the client.

By the way, when you say source, do you mean you are running `yarn start` don't you? If is snap you need to enable the camera. (Check the collaboration or known issues).. hope helps

**Comment by pawelboh** [comment]
I think i have found issue. App don't see any sound devices:
![53](https://user-images.githubusercontent.com/50030787/56943870-ad792000-6b21-11e9-90ce-98c0bb6f89b2.png)

Brak = None
Glosnik = Speaker
Mikrofon = Microphone
Kamera = Camera

Also, please take a look to the console window, an error occurs:
`[18149:0430/081730.510564:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.`

But, all system sounds works like a charn.

**Comment by pawelboh** [comment]
Ok, i have configured pulseaudio. It works fine now.

**Comment by dawheela** [comment]
> Ok, i have configured pulseaudio. It works fine now.

@pawelboh I've actually the same issue. So I'm interested to know: What did you have to configure in pulseaudio to get it work?

**Comment by pawelboh** [comment]
I've just installed pulseaudio package in my system (gentoo) and sound started working
