### ISSUE TITLE
Teams v2: Broken taskbar notifications icon

### ISSUE THREAD

**Issue by IncandescentChrysalis** [IsmaelMartinez/teams-for-linux#1172]
**Describe the bug**
In #1156, @IsmaelMartinez [mentioned](https://github.com/IsmaelMartinez/teams-for-linux/issues/1156#issuecomment-2026896821):
> [The notification icon issue is related to the] Move to react and I prefer if we make small incremental changes, and that notification one is probably going to take a bit of time/investment. But we will get there

**To Reproduce**
1. Start `teams-for-linux` in Teams v2 mode
2. Receive a notification (ie chat)
3. Not notification indicator appears on the taskbar icon

**Expected behavior**
Notifications to resume working, as they are in v1

**Desktop (please complete the following information):**
 - OS: Debian
 - Installation package: `deb`
 - Version: `1.4.16`

**Comment by gianlucapiccolo** [comment]
Thank you for reporting this issue, it does not work also in Gnome on Fedora 39 with the Tray Icon - reloaded extension.

**Comment by Diabsou** [comment]
Hello, 

Same here, using KDE Plasma 5.27.11 Xorg X11 Manjaro Linux

cheers,

**Comment by IsmaelMartinez** [comment]
has any of you checked this? https://github.com/IsmaelMartinez/teams-for-linux/issues/1164#issuecomment-2034173329

**Comment by frazzaglia** [comment]
Hi, same for me on Linux Mint 21.3 Cinnamon and  app v1.4.16

**Comment by IgorKvasn** [comment]
> has any of you checked this? [#1164 (comment)](https://github.com/IsmaelMartinez/teams-for-linux/issues/1164#issuecomment-2034173329)

Hi, this solution does not work for me on Ubuntu

**Comment by jijojosephk** [comment]
I would encourage people to join the chat group https://matrix.to/#/#teams-for-linux_community:gitter.im

**Comment by geckolinux** [comment]
For me this is currently the biggest issue that prevents me from switching to v2. (Fortunately my account still works with classic Teams, and our IT department says we have until the end of June to switch.) Thanks to @ChristoSnake for the workaround via native desktop environment notifications. That's not really an option for me though, as I use Cinnamon and it distracts me to have a bunch of notifications from different sources with different levels of urgency all grouped together under a single counter. I don't even have the Cinnamon notifications counter applet loaded. I prefer to see the count of unread messages just for Teams in the Teams tray icon, and another counter for my personal IM account, and another counter for my email. But I'm sure the great people in this project will figure something out eventually. Thanks again to everyone.

**Comment by jijojosephk** [comment]
seems like cracking the react is tough. I was able to get to the event that is showing the notification count. Nothing beyond that. Need to figure out how the pub/sub pattern works with react. I think someone with react knowledge would be able to crack it.

Temporary solution might be looking at the title bar.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/d28265b6-fae4-4a2f-8d2f-5aec390faf10)

**Comment by IsmaelMartinez** [comment]
Aye, I was looking at using a mutator option . I started some work in https://github.com/IsmaelMartinez/teams-for-linux/tree/feature/teams-v2-activityhub-changes but had to stop because of work. 

That unfortunately breaks the angular option, so I wanted to tidy it up and put it behind a feature flag/config option. I doubt I will manage to do that today but feel free to continue

**Comment by IsmaelMartinez** [comment]
The main part for the notifications in under app/browser/tools/mutationTitle.js but wanted to move the trayIconRenderer into his own object and have it react to events, instead of being inside the activityHub/activityManager files.

**Comment by IsmaelMartinez** [comment]
pre-release in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.19 that should hopefully fix the tray icon number. You will need to use the --useMutationTitleLogic config option . That will show the number of unread messages as before, but it might be a bit more unreliable. For example if the window is minimized.

**Comment by geckolinux** [comment]
@IsmaelMartinez The 1.4.19 pre-release is looking pretty good. This is my `config.json` :

```
{
    "optInTeamsV2":true,"useMutationTitleLogic":true
}
```

It's properly updating the tray icon when the number of unread chats increases >=0 or decreases down to 1. The only issue is that when I have no more unread chats it still shows 1 unread in the tray icon. Only after I close and restart the app then it shows no unread in the tray icon.

Here are my logs from this process:
1. Open app with zero unread chats, and none showing in tray
2. Mark one chat as "unread", taskbar increases to **(1)**, tray increases to **1**
3. Read the unread chat, taskbar does not show any unread, tray stays at **1**
4. Close the app

I truncated the Electron app log to a reasonable size that I could inspect and redact for privacy reasons, so it only shows the beginning and the end. Please let me know if you need to see more of it. Thanks!
- [terminal.log](https://github.com/IsmaelMartinez/teams-for-linux/files/14894319/terminal.log)
- [truncated.log](https://github.com/IsmaelMartinez/teams-for-linux/files/14894321/truncated.log)

**Comment by jijojosephk** [comment]
I suppose it's because the when all notifications are read, the app title will not have any digits. Hence the logic fails.

```js
const regex = /^\((\d+)\)/;
const match = window.document.title.match(regex);
// Probably this condition is not required, if no match, no notifications or the notifications are cleared.
if (match) {
	const number = match[1];
	console.log(number);
	const event = new CustomEvent('unread-count', { detail: { number: number } });
	window.dispatchEvent(event);
}
```

**Comment by jijojosephk** [comment]
I merged my changes. `1.4.20` should have this fixed @geckolinux

**Comment by jijojosephk** [comment]
@geckolinux checkout `1.4.20` `pre-release`, looks fine in my testings.

**Comment by IsmaelMartinez** [comment]
I told you it could be iffy :D glad to see it is more or less working. Thanks @jijojosephk for the fix

**Comment by geckolinux** [comment]
Thanks to both of you! The `1.4.21` pre-release seems to be working well. I haven't had any actual new activity yet, but I'm wondering if the tray count will update when the app is minimized to the tray. I'll report back.

**Comment by jijojosephk** [comment]
At least in `GNOME`, it works.

- Window visible
- Window minimized
- Window closed to tray

It covers the above 3. Of course, like I mentioned the behavior might differ in different DEs.

**Comment by gobalius** [comment]
FWIW, I'm using flatpak version 1.4.17 and when I start teams-for-linux I get all the **missed** notifications and the **missed** messages count on my tray icon. I'm using GNOME 3.28.3 and Tray icons extension.
Even when I then read all the messages, the count on the tray icon doesn't change.
Maybe it's useful to know that it is correct on startup though...

**Comment by zelimir86** [comment]
Not working on Cinnamon (Linux Mint 21.3) with 1.4.20 nor 1.4.21.

**Comment by geckolinux** [comment]
> Not working on Cinnamon (Linux Mint 21.3) with 1.4.20 nor 1.4.21.

It's working for me with Cinnamon on Debian Stable. Did you enable the new tray notification method either in your [config.json](https://github.com/IsmaelMartinez/teams-for-linux/issues/1172#issuecomment-2041143977) or with the `--useMutationTitleLogic` switch when launching teams-for-linux?

**Comment by zelimir86** [comment]
> > Not working on Cinnamon (Linux Mint 21.3) with 1.4.20 nor 1.4.21.
> 
> It's working for me with Cinnamon on Debian Stable. Did you enable the new tray notification method either in your [config.json](https://github.com/IsmaelMartinez/teams-for-linux/issues/1172#issuecomment-2041143977) or with the `--useMutationTitleLogic` switch when launching teams-for-linux?

Yes, sorry, I missed that. It's ok now.

**Comment by gobalius** [comment]
Thanks! Can't wait for the flatpak version to catch up! :)

**Comment by IncandescentChrysalis** [comment]
I just tested `1.4.21` with the new
```json
{
    […]
    "useMutationTitleLogic": true
}
```
configuration, and so far (only a few notifications received here or there) it seems to work on XFCE 4.16 (Debian 11 Bullseye)

**Comment by rangerzhou** [comment]
> I just tested `1.4.21` with the new
> 
> ```json
> {
>     […]
>     "useMutationTitleLogic": true
> }
> ```
> 
> configuration, and so far (only a few notifications received here or there) it seems to work on XFCE 4.16 (Debian 11 Bullseye).
> 
> Congratulations & kudos to all who provided handwork to this fix!

Where is the config.json?

**Comment by rangerzhou** [comment]
> > I just tested `1.4.21` with the new
> > ```json
> > {
> >     […]
> >     "useMutationTitleLogic": true
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > configuration, and so far (only a few notifications received here or there) it seems to work on XFCE 4.16 (Debian 11 Bullseye).
> > Congratulations & kudos to all who provided handwork to this fix!
> 
> Where is the config.json?

I know, ~/.config/teams-for-linux/config.json

**Comment by rangerzhou** [comment]
I have config like:
```
{
    "optInTeamsV2":true,"useMutationTitleLogic":true
}
```

The tray show count, but taskbar cannot show

**Comment by jijojosephk** [comment]
This works in most cases, we can release the latest one to public.

**Comment by ps-spark** [comment]
It does not work for me but I continue testing tomorrow.

My config.json
```json
{
	"optInTeamsV2": true,
	"url": "https://teams.microsoft.com/v2",
	"useMutationTitleLogic": true
}
```
I guess, the tray notification is independent from the notification settings in Teams.
![Screenshot from 2024-04-10 22-02-46](https://github.com/IsmaelMartinez/teams-for-linux/assets/19947879/c605f508-3c03-41f5-a880-7d10fb5994a0)

Teams for Linux: v1.4.21
Ubuntu Cinnamon 22.04
kernel: 6.5.0-27
Cinnamon: v5.2.7

**Comment by ps-spark** [comment]
Hi Guys,

Works for me as well on Ubuntu Cinnamon! Thank you for your effort!

**Comment by jijojosephk** [comment]
Closing as this is currently working with teams v2.
