### ISSUE TITLE
Network Issues using wireless interface

### ISSUE THREAD

**Issue by Dudek-AMS** [IsmaelMartinez/teams-for-linux#1173]
**Describe the bug**
I have no clue to trace it further down. Whenever I'm on LAN the app works fine. If I'm connected with my wireless adapter the app reports "No Internet Connection". All the same network

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/100142218/0c7d20c1-768f-4d9c-a953-3deab133f51e)

```
/opt/teams-for-linux/teams-for-linux --appLogLevels error,warn,debug,info
[DEBUG] configPath:,/home/dudek/.config/teams-for-linux
[WARN] No config file found, using default values
[DEBUG] configFile:,[object Object]
[INFO] App already running
[7798:0404/085800.545265:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[7798:0404/085800.549827:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
```

**Desktop (please complete the following information):**
 - OS: Debian 12.5
 - Kernel: `Linux dudek-ams 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux`
 - Installation: apt repo https://repo.teamsforlinux.de/debian/
 - Version 1.4.16

**Interfaces**
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp0s31f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether f4:ee:08:e4:dc:b4 brd ff:ff:ff:ff:ff:ff
3: enxf4ee08e4dcb5: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether f4:ee:08:e4:dc:b5 brd ff:ff:ff:ff:ff:ff
4: wlp113s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 04:56:e5:e0:46:1a brd ff:ff:ff:ff:ff:ff
    inet 192.168.200.56/24 brd 192.168.200.255 scope global dynamic noprefixroute wlp113s0
       valid_lft 861525sec preferred_lft 861525sec


[.....] many docker bridges here
```

**Comment by IsmaelMartinez** [comment]
I think you either got an extremely low connection or you don't have an internet connection at all. I don't think this is related to our app. Can you check if you can log in with a fresh browser session? Ta

**Comment by Dudek-AMS** [comment]
I have internet connection. Stable and still 100MBit. Teams in the browser does work - Even sharing screen without any issues. It also happens when I'm close to the router. It only bugs on the teams-for-linux app
Removing (purge) teams-for-linux and reinstalling didnt help either

**Comment by Dudek-AMS** [comment]
Also I've test already all onlineCheckMethod params like none

**Comment by Dudek-AMS** [comment]
Never mind, i was able to track it down. Changing onlineCheckMethod does work, but only dns
