### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by sebastienmorand-loreal** [IsmaelMartinez/teams-for-linux#1175]
Hi,

As we are in an embedded navigator, I was expecting to be able to zoom on the page because it's too small to be read properly, but the zoom standard shortcuts are not working, how can we make a global zoom as we do in standard browser?

Thanks by advance,

**Comment by IsmaelMartinez** [comment]
Hi @sebastienmorand-loreal , please can you use the template? I can see the zoom working fine in my version of the client.

**Comment by jijojosephk** [comment]
@sebastienmorand-loreal kindly use the template. We don't want to be harsh and close the issues. The dev is bombarded with a lot of queries, issues, duplicate issues. Help us to help you.

**Comment by jijojosephk** [comment]
zoom is working as expected.
