### ISSUE TITLE
I'm using v.1.4.19 but Teams aks for browser update and gives a warning

### ISSUE THREAD

**Issue by mozo78** [IsmaelMartinez/teams-for-linux#1179]
**Describe the bug**
Hello,
I'm using v.1.4.19 but Teams aks for browser update and gives a warning that "Classic Teams will soon be unavailable for use". Is it expected behaviour or I'm missing something?

**To Reproduce**
1. Start Teams
2.  View the message on the upper part of the chat.

**Expected behavior**
It should not warn me for I'm using v.1.4.19 which AFAIK is v2?

**Screenshots**
![Screenshot_20240405_214357](https://github.com/IsmaelMartinez/teams-for-linux/assets/38666396/34d169fc-a943-4db7-accc-9874fd173ed4)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Installation package - AppImage
 - Version 1.4.19

**Additional context**
I tried with --url=https://teams.microsoft.com/v2 but it doesn't help.

**Comment by IsmaelMartinez** [comment]
Duplicated #1156
