### ISSUE TITLE
 Teams v2: Can't join meeting using the calendar/meeting button

### ISSUE THREAD

**Issue by Zenkibou** [IsmaelMartinez/teams-for-linux#1182]
**Describe the bug**

When using Teams v2, I can not join meetings from the regular "Join" button (from the calendar view or from the meeting view)

It works from the in-app notification, but not from the regular button.

**To Reproduce**
1. Enable Teams v2
2. Go to the calendar
3. Click on "Join"

**Expected behavior**
The meeting is joined

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - .deb
 - Version 1.4.21

**Debug**
Opened the debug pane and this is shown in the console when clinking on the "Join" button:

    (index):3 Unhandled error/rejection {"isTrusted":true}
    error @ (index):3
    (anonymous) @ (index):3

**Comment by IsmaelMartinez** [comment]
Are you using the 'optInTeamsv2' config option? (name might be different)

**Comment by Zenkibou** [comment]
I think so, I'm using this config.json file:

    {
        "optInTeamsV2": true,
        "url": "https://teams.cloud.microsoft"
    }

**Comment by raverecursion** [comment]
@Zenkibou I had the same issue when I used the url from your config, but it works fine without:

```
{
  "optInTeamsV2": true
}
```

**Comment by IsmaelMartinez** [comment]
Change the URL to https://teams.microsoft.com/v2 (or just don't provide it)
and it should work. The cloud URL is for apps as far as I am aware of.

**Comment by ps-spark** [comment]
Hi Guys,

I tried to use the following two settings in the Debug/Console:
```
window.localStorage.setItem("tmp.isOptedIntoT2Web", true)
document.location.href = 'https://teams.microsoft.com/v2/'
```

and the Join button did not work. Then I created the config.json file and it solved the issue. Strange ...

Ubuntu Cinnamon 6.5.0-27-generic

**Comment by Zenkibou** [comment]
> Change the URL to https://teams.microsoft.com/v2 (or just don't provide it) and it should work. The cloud URL is for apps as far as I am aware of.

This indeed makes it work, thank you !

**Comment by manoo2k** [comment]
Hello Guys,

Have the same issue - none of the answers above helps :(. Using snap, apt, flatpak or web-app (chrome or edge) does not matter, can not join to a meeting from calendar. using ubuntu 24.04 / teams 2.0.8. The only error message I have in the console is:

(index):3 Unhandled error/rejection {"isTrusted":true}
error @ (index):3
(anonymous) @ (index):3
