### ISSUE TITLE
No notification number when switch to new teams

### ISSUE THREAD

**Issue by rangerzhou** [IsmaelMartinez/teams-for-linux#1186]
There is no notifications number like below when switch to new teams

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/29405216/ec598026-6b59-4942-85fd-79b1d253e824)

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/29405216/a9a90b32-282c-41ad-a046-a2c21bcf27ed)

**Comment by rangerzhou** [comment]
Also no number in Ubuntu taskbar
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/29405216/c9151cad-537f-43fb-8b5a-2f50c778f7a4)

Version: 1.4.20 and 1.4.21

**Comment by ps-spark** [comment]
Duplicate, see https://github.com/IsmaelMartinez/teams-for-linux/issues/1172
