### ISSUE TITLE
"Your org is switching to the new Teams, and it's ready for you to use"

### ISSUE THREAD

**Issue by ViktorWalter** [IsmaelMartinez/teams-for-linux#1189]
**Describe the bug**
Since today, our Teams is displaying the prompt in screenshot.
There is no "close" or "opt-out" button.
I am, however, able to bypass this by selecting Debug (from the right-click menu on the tray icon) and deleting the element. The system works fine, showing that the transition is not necessary.
I would suggest adding an automated procedure to delete said element - either triggered by default or upon user choice.

**To Reproduce**
Run teams-for-linux. May not happen when you have a self-hosted server.

**Expected behavior**
The window not appearing and the user directly accessing Teams.

**Screenshots**

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/21334530/e4a501d2-31a0-4993-9724-c1b36839d80a)
Element to delete:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/21334530/d95b1629-92dc-45c1-8fce-4d0c2fd8cfdb)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 20.04), but I suspect this is happening in general on "classic" teams.

**Debug**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/21334530/092e8c20-9fc0-499e-b683-54e8e7b27a40)
Though, I suspect it doesn't help here.

**Additional context**
Switching to the new UI leads to the new UI upon reload. Top-right corner menu allows me to switch back, but I get this window again.

**Comment by jijojosephk** [comment]
You must switch to new teams.

**Comment by jijojosephk** [comment]
Follow this issue: 

https://github.com/IsmaelMartinez/teams-for-linux/issues/1156

**Comment by ViktorWalter** [comment]
> You must switch to new teams. We don't have control on this behavior.
I see no reason why I "must" or why I would even want to switch away from a system that otherwise works fine so far, just because Microsoft said so. Though I applaud your efforts to pre-emptively adjust to the changes so that the project can continue, as I'm demonstrating here the old teams still works fine once you bypass the window. So I'll have to make a fork of my own just to automate a single action upon startup I guess.

**Comment by jijojosephk** [comment]
What I'm saying is we can't really control the message shown. Just a warning to switch to new teams. You'll have to do it anyway in couple of months. So the effort to delete the warning html element is unnecessary for this app. You can fork and add your own code to delete it.

**Comment by IsmaelMartinez** [comment]
Hi @ViktorWalter , feel free to put a PR with the change you will put in a fork and we can put it as an option in here. We tend to put this sort of changes on the back of config options as then people can opt in to them, and we only make them default if/when they make sense. 

I don't think Microsoft will keep teams v1 for a long time, as they want people to move to V2. Meaning, at some point (probably in not long) all users will be moved to V2.

**Comment by TamaMcGlinn** [comment]
Any update on this? I can't find the "tray icon" to right click, but would happily switch to a fork that fixes this.
