### ISSUE TITLE
IncomingCallCommand not working for Teams V2

### ISSUE THREAD

**Issue by Flofler** [IsmaelMartinez/teams-for-linux#1195]
**Describe the bug**
After switching to Teams V2 the IncomingCallCommand won't be executed anymore, even with enabled  "optInTeamsV2" flag.

**To Reproduce**
1. Switch to Teams V2
2. Command won't be executed anymore

**Expected behavior**
I would like to have my command being executed after Teams Classic is not available anymore.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Installation package deb
 - Version 1.4.21

```bash
teams-for-linux --incomingCallCommand command.sh
```

**Additional context**
My command is in my PATH, so the application should be able to find it.

**Comment by jijojosephk** [comment]
This may not be possible in `react` based new version of teams.

**Comment by IsmaelMartinez** [comment]
I believe this is one of those parts now broken because the move from angular to react by microsoft.

**Comment by elhennig** [comment]
Is there a wy to fix this very useful functionality?

**Comment by IsmaelMartinez** [comment]
Aye, but currently it is pretty different. I basically have no clue how to listen to those events in react as we did in angular, but I do suspect MS will be following a similar pattern. Basically, once we find the way to listen to these events, it will be easy to implement

**Comment by cs96and** [comment]
Would love a solution to this too

**Comment by IsmaelMartinez** [comment]
I had a few check and keep trying to think of alternatives, but I haven't been lucky. React is not my strongest area and the angular solution was brought by the community. Lets see if someone with those expertise can have a look at this.

**Comment by IsmaelMartinez** [comment]
Waiting to see if someone from the community can look into this. I did try finding alternative ways of doing this but haven't managed.

**Comment by Cybso** [comment]
Please re-open this bug. Either the problem must be resolved, or this feature be removed.

**Comment by Cybso** [comment]
> Please re-open this bug. Either the problem must be resolved, or this feature be removed.

Nevermind, was still on 2.0.8. The feature was removed in 2.0.9.
