### ISSUE TITLE
Diacritics broken on file download

### ISSUE THREAD

**Issue by Templayer** [IsmaelMartinez/teams-for-linux#1196]
**Describe the bug**
Using Teamsv2 - if I download a file from a team in Teams, the filename encoding breaks in Teams v2 (this didn't occur with v1).
In the first printscreen - the right part is the file in the team, the left part is the resulting downloaded file in the file manager (Nemo).

**Expected behavior**
Diacritics / character encoding should be preserved

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11728067/12b2ff52-d21c-4ad9-9c02-536b0babf398)

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11728067/68a98e3c-55a7-489d-a2eb-8a0e5d61fe9f)

**Desktop (please complete the following information):**
 - OS: Linux Mint" 21.3 (Virginia) with Cinnamon GUI
 - Installation package: Debian
 - Version: 1.4.26

**Comment by jijojosephk** [comment]
May be not related to the app, but will investigate.

**Comment by IsmaelMartinez** [comment]
Hi, Can you try if you get the same problem using a web browser ? Otherwise I think this one is an electron one and I would suggest to investigate in their issues to see if you find something there. https://github.com/electron/electron/issues . I do not think is related to the app, I am afraid.

**Comment by Templayer** [comment]
I'm using Brave on a daily basis. I would have noticed that behaviour in an up-to-date chromium browser.

**Comment by IsmaelMartinez** [comment]
That is strange as we are using electron, that basically runs the core of Chrome under the hood (Chromium). 

Can you check https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632446994 and see if that does anything to you?

**Comment by Templayer** [comment]
> That is strange as we are using electron, that basically runs the core of Chrome under the hood (Chromium).
> 
> Can you check [#357 (comment)](https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632446994) and see if that does anything to you?

Nope. Tried that, restarted Teams, the result is the same.

By the way, I have seen this before - this happens when you convert diacritics between Unicode and something else (forgot the direction) in a bad way.

I have recorded a video of this - https://www.youtube.com/watch?v=SnMfAYm4vrM

**Comment by Templayer** [comment]
> I suspect is a electron issue. Can you try with version https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.33 ? That uses 30.0.1 electron version, that we had to revert, but maybe does solve that issue (it might have other problems). But I do suspect this is an electron issue and/or local configuration, and not a Teams-for-linux issue, but hopefully we can find a solution nevertheless.

Not really. I'm using a package manager. Also, this is on a laptop used for working, so when I have access to it... I usually do not have the time to build applications myself to test them. I would have to fill out a work report for that. If I wasn't forced by the company, I wouldn't be using MS Teams at all!

**Comment by IsmaelMartinez** [comment]
Sorry but I don't know how much we can help. 

If you edit the issue and fill the template details with the logs and package information, that can give us more information. 

Without them we are a bit blind tbh, and just guessing, but there are a lot of variables in play. 

Having another guess I would check providing the LANG env variables. Maybe is using the wrong ones due to the desktop link you got or the package you are using. 

Specially if you are using SNAP or Flatpak as their confinement CAN cause this sort of problems. We provide the app in many packaging systems for that reason.

**Comment by Templayer** [comment]
> Specially if you are using SNAP or Flatpak as their confinement CAN cause this sort of problems. We provide the app in many packaging systems for that reason.

That has been a part of the issue from the moment I have created it. Check under the printscreen section. The version has obviously changed in the meanwhile, with no discerning changes to the Issue. The information about the packaging system used is there and always has been there.

> Having another guess I would check providing the LANG env variables. Maybe is using the wrong ones due to the desktop link you got or the package you are using.

```
printenv LANG
cs_CZ.UTF-8
```

If you want more, specify the command. I quite dislike the terminal (and that is why I have been using Mint with Cinnamon for the past 3+ years... everything that I have to do day to day has a GUI)

LOGS:

[teams.microsoft.com-1716964530887.log](https://github.com/IsmaelMartinez/teams-for-linux/files/15479940/teams.microsoft.com-1716964530887.log)
[Terminal log for MS Teams.txt](https://github.com/IsmaelMartinez/teams-for-linux/files/15479941/Terminal.log.for.MS.Teams.txt)

**Comment by IsmaelMartinez** [comment]
Sorry but still not clear what packaging system you are using.  Debian can be in many ones (deb, snap, flatpak). 

I would suspect is snap that is playing with your settings. You should be able to install it using apt like in the https://github.com/IsmaelMartinez/teams-for-linux?tab=readme-ov-file#debianubuntu-and-other-derivatives 

Unfortunately I don't see anything on the logs, but I do suspect is snap that messing with the diacritics.

**Comment by IsmaelMartinez** [comment]
Sorry but still not clear what packaging system you are using.  Debian can be in many ones (deb, snap, flatpak). 

I would suspect is snap that is playing with your settings. You should be able to install it using apt like in the https://github.com/IsmaelMartinez/teams-for-linux?tab=readme-ov-file#debianubuntu-and-other-derivatives 

Unfortunately I don't see anything on the logs, but I do suspect is snap that messing with the diacritics.

**Comment by Templayer** [comment]
> Sorry but still not clear what packaging system you are using. Debian can be in many ones (deb, snap, flatpak).
> 
> I would suspect is snap that is playing with your settings. You should be able to install it using apt like in the https://github.com/IsmaelMartinez/teams-for-linux?tab=readme-ov-file#debianubuntu-and-other-derivatives
> 
> Unfortunately I don't see anything on the logs, but I do suspect is snap that messing with the diacritics.



> Sorry but still not clear what packaging system you are using. Debian can be in many ones (deb, snap, flatpak).
> 
> I would suspect is snap that is playing with your settings. You should be able to install it using apt like in the https://github.com/IsmaelMartinez/teams-for-linux?tab=readme-ov-file#debianubuntu-and-other-derivatives
> 
> Unfortunately I don't see anything on the logs, but I do suspect is snap that messing with the diacritics.

By the way, you have dual posted.

.deb is the Debian packaging system. SNAP and FLATPACKs are sandboxed packaging systems meant for other systems too, not only for Debian and its derivatives.

It was installed using apt.

```
jboksa1@JB-PC:~$ apt show teams-for-linux
Package: teams-for-linux
Version: 1.5.0
Priority: optional
Section: net
Maintainer: Ismael Martinez <ismaelmartinez@gmail.com>
Installed-Size: 269 MB
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
Recommends: libappindicator3-1
Homepage: https://github.com/IsmaelMartinez/teams-for-linux
License: GPL-3.0-or-later
Vendor: Ismael Martinez <ismaelmartinez@gmail.com>
Download-Size: 73,9 MB
APT-Manual-Installed: yes
APT-Sources: https://repo.teamsforlinux.de/debian stable/main amd64 Packages
Description: Teams for Linux
  Unofficial Microsoft Teams client for Linux using Electron. It uses the Web App and wraps it as a standalone application using Electron.

```

**Comment by IsmaelMartinez** [comment]
I really don't know what else to look at. It might be an specific bug in the chromium version we use. I will try to update the electron version to 30.0.9 that uses `Chromium to 124.0.6367.233` but I will release that as a pre-release 1st as we will be moving from 29.3.x to 30.0.x

**Comment by Templayer** [comment]
Update: still occurs after updating to 1.6.1

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11728067/47bfee3b-ff61-4aff-9391-e55bddc85a3d)

Bollocks.

**Comment by IsmaelMartinez** [comment]
I am trying to do some work around that and release with the new electron in 1.7.0. I don't know when this will be ready but I will ping you in here to see if that solves this for you.

**Comment by Templayer** [comment]
> I am trying to do some work around that and release with the new electron in 1.7.0. I don't know when this will be ready but I will ping you in here to see if that solves this for you.

Thank you for your patience. Unfortunately for me, Czech is a language that contains diacritics in almost every word in a sentence.

Děkuji vám za vaši trpělivost. Bohužel pro mne, čeština je jazykem, který obsahuje diakritiku skoro v každém slově ve větě.

https://www.youtube.com/watch?v=B_VccIbKwFI

I love the reason why he had to go to the hospital at the end of the video...

**Comment by IsmaelMartinez** [comment]
Strange. I just copied that line you put in there as the name of an excel file, upload it, and downloaded fine (keep the same name). Do you have any colleague that can try the same file? Can you send an example file in here?

**Comment by Templayer** [comment]
> Strange. I just copied that line you put in there as the name of an excel file, upload it, and downloaded fine (keep the same name).

Wait, please don't tell me... that SharePoint is creating a non-Unicode download response.

In that case, sending a file won't help much. OneDrive does it too, but those are connected in our company.

I found a test file and made it into a temporarily accessible-to-all file, it doesn't screw up on download.

https://vincic-my.sharepoint.com/:u:/g/personal/jan_boksay_1_vinci-construction_com/EXr1QmLSlitDvCDuseil87oBXOCcPDIbuUSy09TdiaQ0QQ?e=pgaG8t

Could you try triggering a download response in Teams that would act as if it was accessed via... I do not know whow to call it...

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11728067/0069348f-6423-4ad0-af09-991dea791225)

> Do you have any colleague that can try the same file? Can you send an example file in here?

I'm the only one using Teams on Linux. This issue only occurs in Teams for Linux and nowhere else.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11728067/368819fd-6c1d-45b5-8dc0-8c77a2e011a8)

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11728067/088d2613-c240-45dc-ace3-690a9c40c18a)

**Comment by IsmaelMartinez** [comment]
I see, is when you are using one drive in within teams. 

I cant' seem to be able to reproduce. I have tried with that file and many ways but still get the right text.

Maybe try to remove the one drive app and add it again?

**Comment by Templayer** [comment]
> I see, is when you are using one drive in within teams.
> 
> I cant' seem to be able to reproduce. I have tried with that file and many ways but still get the right text.
> 
> Maybe try to remove the one drive app and add it again?

That doesn't sound like a good potential solution. I fail to see how that would change anything for unicode conversions when the dialog is triggered.

Besides, I am not the one who has added that in the first place. If I do that, and for whatever reason I am unable to add it back in, what will I tell the company? That some dude on the internet told me so? I would get sacked.

Again, I am forced to use Teams. I am not using it out of my own volition.

**Comment by Templayer** [comment]
As a workaround, I will be using the browser version directly to download files for now, until (and if) it ever gets fixed.

**Comment by IsmaelMartinez** [comment]
If you aren't the admin of your computer I would suggest reaching out to
your administrator, updating them with the issue and bringing them to this
issue channel. They might be able to help fix your issue.

Unfortunately, it is fairly difficult as I can't reproduce the issue from
my end with the file and instructions you have given me, which makes me
think that this is an os config issue.

Can you try copying the link to the file into a team chat and download it
from there and see if you still have the same problem?

If you want to continue searching for the why, do reach out. Again, I am
just trying to help here.

**Comment by Templayer** [comment]
> If you aren't the admin of your computer I would suggest reaching out to your administrator, updating them with the issue and bringing them to this issue channel. They might be able to help fix your issue. Unfortunately, it is fairly difficult as I can't reproduce the issue from my end with the file and instructions you have given me, which makes me think that this is an os config issue. Can you try copying the link to the file into a team chat and download it from there and see if you still have the same problem? If you want to continue searching for the why, do reach out. Again, I am just trying to help here.

I do have admin rights on the OS (my laptop with Linux Mint), but I have limited permissions on my Teams/Microsoft account. And OneDrive/Sharepoint. Our IT is clueless and useless in almost every regard, unfortunately.

> Can you try copying the link to the file into a team chat and download it
from there and see if you still have the same problem?

I'll try that when I'm back at work (i.e. Tuesday, I'm having a vacation on Monday).

**Comment by Templayer** [comment]
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11728067/58e4ce8d-73c7-4cfa-a8f9-bf1418c01ca3)

**Comment by IsmaelMartinez** [comment]
Sorry, I don't know what else to try. I keep it open for a while in case someone else reports a similar problem and/or can think of other options. As mentioned, I can't reproduce the issue in my computer.

**Comment by IsmaelMartinez** [comment]
maybe is related to https://github.com/electron/electron/issues/33662 ? If so, can you try the options in there and/or described in https://github.com/logseq/logseq/issues/9744 ? They might work.

**Comment by Templayer** [comment]
> maybe is related to [electron/electron#33662](https://github.com/electron/electron/issues/33662) ? If so, can you try the options in there and/or described in [logseq/logseq#9744](https://github.com/logseq/logseq/issues/9744) ? They might work.

I do not have Wayland enabled.

**Comment by IsmaelMartinez** [comment]
Have you tried with another gui, even if just to confirm is not around that area.

**Comment by Templayer** [comment]
> Have you tried with another gui, even if just to confirm is not around that area.

Define UI. System UI? No, I can't really switch from Cinnamon. x.org? Wayland causes way too many screen glitches for me to be usable.

**Comment by Templayer** [comment]
I just tested it and it seems that the issue has resolved itself.

![Uploading image.png…]()

**Comment by IsmaelMartinez** [comment]
lovely, glad is working. It was probably unrelated to the app and a OS library update probably fixed it.

**Comment by Templayer** [comment]
> lovely, glad is working. It was probably unrelated to the app and a OS library update probably fixed it.

Or an electron update.
