### ISSUE TITLE
appIdleTimeout doesn't work anymore with 'new teams'

### ISSUE THREAD

**Issue by kooskaspers** [IsmaelMartinez/teams-for-linux#1198]
**Describe the bug**
The 'new teams' doesn't respect the appIdleTimeout variable in config.json. 'old teams' did.

**To Reproduce**
set `appIdleTimeout` to 300000

**Expected behavior**
Teams away status based on 300000 seconds

**Screenshots**

**Desktop (please complete the following information):**
 - OS: arch
 - Installation package: source
 - Version: 1.4.14

**Comment by IsmaelMartinez** [comment]
I believe this is one of those parts now broken because the move from angular to react by microsoft.

**Comment by IsmaelMartinez** [comment]
Can you try https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.35 and see if that fixes your issue? Thanks

**Comment by mdallaire** [comment]
1.4.35 fixes this issue for me. Thanks!
