### ISSUE TITLE
easier "Quit normally"

### ISSUE THREAD

**Issue by atommaki** [IsmaelMartinez/teams-for-linux#1199]
**Is your feature request related to a problem? Please describe.**
Quitting (normally) from the app requires one more click than really needed. The "Quit" in the menu (on the system tray icon) opens a submenu where I can chose the real "Quit"
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/14099928/6f2c6e9b-ab6f-4bc6-92d8-df65225d235c)

**Describe the solution you'd like**
There is enough space, the "Quit Normally" and the "Quit with storage cleanup" could be directly in the menu, not in a submenu.

**Describe alternatives you've considered**
Additionally or alternatively the Gnome app right click menu (on the task bar), could have a "Quit Normally" item. Even more confusing the "Quit" item visible there just closing the window, totally not quitting (but I guess that comes with Gnome).
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/14099928/1a681bc3-7e64-4591-a63b-fcbb477c706b)

**Comment by jijojosephk** [comment]
We're with you. We'll have it changed. The `GNOME` dash quit is same as `close` button which hides to tray by default.

**Comment by jijojosephk** [comment]
`1.4.27` implements this.
