### ISSUE TITLE
Ozone Platform Wayland 

### ISSUE THREAD

**Issue by nerumo** [IsmaelMartinez/teams-for-linux#1201]
**Describe the bug**
I'm using the ozone platform wayland flag as in the description. If I start the application, the screen stays white, even though the webview is starting (I see it based on the title).

**To Reproduce**
1. Use this config
```
{
	"optInTeamsV2": true,
	"followSystemTheme": true,
	"awayOnSystemIdle": true,
	"electronCLIFlags": [
		["ozone-platform","wayland"]
	]
}
```
2. Start app

**Expected behavior**
Screen stays white 

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/8597645/7088a806-9541-4033-b56f-17d6f08231cc)

**Desktop (please complete the following information):**
 - OS: Kubuntu 23.10
 - Installation package deb
 - Version 1.4.27

**Debug**

```
/opt/teams-for-linux/teams-for-linux --webDebug  --appLogLevels=error,info,warn,debug


[DEBUG] configPath:,/home/marco/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[INFO] Running under Wayland, switching to PipeWire...
[INFO] Disabling GPU support...
[DEBUG] Adding electron CLI flag 'ozone-platform' with value 'wayland'
[DEBUG] Fetching custom background configuration from 'http://localhost/config.json'
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--webDebug,--appLogLevels=error,info,warn,debug
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
[DEBUG] Spellchecker is disabled!
[ERROR] Failed to fetch custom background remote configuration. net::ERR_CONNECTION_REFUSED
[39301:0416/082018.176709:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
[DEBUG] Network test successful with method https
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[39301:0416/082018.641121:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] did-frame-finish-load,[object Object],false
[39301:0416/082018.810151:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)

```

**Additional context**
I also tried disabling software rasterizer and disable GPU, had no effect. Tried to run it on the internal Intel GPU and on the Nvidia GPU (550 driver), both with the same result.

**Comment by jijojosephk** [comment]
@nerumo you don't have to provide ozone platform. It was just an example. Remove those entries and try. It should be working. Also remove `awayOnSystemIdle` as it is not working with new teams.

**Comment by nerumo** [comment]
I just reviewed the electron flags and the example was using an outdated flag.

With this the app starts
```
{
	"optInTeamsV2": true,
	"followSystemTheme": true,
	"electronCLIFlags": [
		["ozone-platform-hint","wayland"],
		["enable-features","WaylandWindowDecorations"]
	]
}

```

unfortunatly, xlsclients still reports that teams is using xwayland

**Comment by jijojosephk** [comment]
Is app working?
`WebRTCPipeWireCapturer` and `use-fake-ui-for-media-stream` are automatically added. You don't have to specify it in `config.json`

**Comment by nerumo** [comment]
yes, it's working. It's just still rendering under xwayland instead of native wayland.

**Comment by jijojosephk** [comment]
ok. Sorry I don't know about that part. Since it's working, I'm closing. Please report back if you find something new. Thank you!

**Comment by rcepeda95** [comment]
I was able to get it working on native wayland setting the environment variable [ELECTRON_OZONE_PLATFORM_HINT](https://github.com/electron/electron/blob/main/docs/api/environment-variables.md#electron_ozone_platform_hint-linux) to `auto`.

**Comment by victornoel** [comment]
Hey, just FYI, I had the same problem as OP:
- setting ozone-platform-hint=wayland in config.json is just ignored and electron runs on xwayland
- setting ozone-platform=wayland in config.json results in the app showing that blank page as in the screenshots above
- setting the ELECTRON_OZONE_PLATFORM_HINT to wayland works and electron does run on wayland natively
