### ISSUE TITLE
Allow multiple window

### ISSUE THREAD

**Issue by babs** [IsmaelMartinez/teams-for-linux#1203]
**Is your feature request related to a problem? Please describe.**

Partly for multi tenancy and development, but also for convenience/multi-tasking, it would be nice to be able to start multiple instances/windows.

**Describe the solution you'd like**

Maybe a cli option to allow a new window of the app instead of raising the currently launched one (which is a quite nice behavior actually)

**Comment by IsmaelMartinez** [comment]
Hi,

I think there is another similar open issue (or it was). This will require a lot of work to implement it the right way, as using the current way it will kill people's machines memory (if we add many browser windows).

The current multi tenancy option is basically that. You run a new instance of the app with a different storage location (and sometimes logo)

Last time I checked the web view option was still in beta, but would you (or someone else) have a look? Ta

**Comment by babs** [comment]
I'll take a look at https://github.com/IsmaelMartinez/teams-for-linux/issues/438#issuecomment-1750270198 and plug multiple instances on my account to give it a try

**Comment by jijojosephk** [comment]
Closing as there is a workaround.
