### ISSUE TITLE
Window Transparency

### ISSUE THREAD

**Issue by mastery-benjamin-palko** [IsmaelMartinez/teams-for-linux#1204]
**Is your feature request related to a problem? Please describe.**
when applying custom styles to the UI, you are unable to create a transparent window.

Changing all background css in-app to transparent results in a white-background

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/154342014/63066de0-abd2-4530-923c-b60f0d2f67ea)

This MAY be due to the absence of the transparency option in the BrowserWindow constructor

[See Electron docs](https://www.electronjs.org/docs/latest/tutorial/window-customization#create-transparent-windows)

[BrowserWindow code](https://github.com/IsmaelMartinez/teams-for-linux/blob/5d3d2baf81c00ae445a0cb8976ec1f78a2d909c4/app/mainAppWindow/index.js#L528)

This might be wrong and the solution could be something else, I'm no Electron expert

**Describe the solution you'd like**
Would like window to be transparent underneath the app css

**Describe alternatives you've considered**
N/A

**Additional context**
Running on Ubuntu 22.04 with wayland + gtk, app is running through the deb install

**Comment by IsmaelMartinez** [comment]
Hi, would you be able to explain the use case ? Electron transparent window is a bit of a pain as you can't resize it etc (as they say in the limitations in the link you have put).

We can add that as an option to the browser window construct but it will just be all the time transparent and no click through. Ta

**Comment by IsmaelMartinez** [comment]
closing due inactivity and also because I don't think electron has this capability.
