### ISSUE TITLE
RPM fails to install on FIPS enabled system.

### ISSUE THREAD

**Issue by bviviano** [IsmaelMartinez/teams-for-linux#1205]
**Describe the bug**
I am trying to install teams-for-linux from the yum repo on a RHEL9 system with FIPS mode enabled, it fails the digest because of the version of rpmbuild used.

**To Reproduce**
1. Boot a RHEL or CentOS 8+ system with `fips=1` on the kernel command line
2. Download latest teams-for-linux RPM
3. run `rpm -ihv teams-for-linux-1.4.27.x86_64.rpm`

**Expected behavior**
RPM should install without error

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux 9 w/[FIPS](https://www.redhat.com/en/blog/how-rhel-8-designed-fips-140-2-requirements) mode
 - Installation package RPM
 - Version 1.4.27-1

**Debug**

$ sudo rpm -ihv teams-for-linux-1.4.27.x86_64.rpm 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:teams-for-linux-1.4.27-1         ################################# [100%]
error: unpacking of archive failed on file /opt/teams-for-linux/LICENSE.electron.txt;662108f4: cpio: Digest mismatch
error: teams-for-linux-1.4.27-1.x86_64: install failed
$

**Additional context**
See RH KB article: https://access.redhat.com/solutions/4460971

This is a pretty common issue and other maintainers have run into it as well https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5938

I can manually download and install if I ignore Digest settings:

$ sudo rpm -ivh --nodigest --nofiledigest teams-for-linux-1.4.27.x86_64.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:teams-for-linux-1.4.27-1         ################################# [100%]
update-alternatives is /sbin/update-alternatives
$

But this means I will be unable to automatically install updates using the yum/dnf repository.

I am requesting the build team look into providing an RPM version that includes the SHA256 Digest that is FIPS compatible, this requires the use of rpmbuild version 4.14 or later, which is standard in RHEL/CentOS 8+.

Thanks!

**Comment by bviviano** [comment]
Taking a closer look, it appears it does heave the correct Digest infomation
```
$ rpm --checksig -v teams-for-linux-1.4.27.x86_64.rpm 
teams-for-linux-1.4.27.x86_64.rpm:
    Header V4 RSA/SHA512 Signature, key ID e6a6e47d: OK
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
```

So I am not exactly sure why I am getting the 
```
error: unpacking of archive failed on file /opt/teams-for-linux/LICENSE.electron.txt;662108f4: cpio: Digest mismatch
```
message.

**Comment by IsmaelMartinez** [comment]
Can you check if this is not the same as https://github.com/IsmaelMartinez/teams-for-linux/issues/958 ? A bit lost on this ones, sorry

**Comment by bviviano** [comment]
I don't think it is, since this is a CPIO Digest problem, which indicates the issue has to do with how the RPM is being built.

Do you know what rpmbuild version is being used to build the Teams-for-linux RPM?

**Comment by bviviano** [comment]
I took a closer look at the links in #958, looking at the FPM docs:

https://fpm.readthedocs.io/en/latest/cli-reference.html

 and understanding the issue is Digest related, I think setting the `fpm` option

`--rpm-digest sha256`

Should resolve the issue for FIPS and be backwards compatible to older systems like RHEL/CentOS 7, but if there is a way for you to build a one-off RPM of 1.4.27 with `--rpm-digest sha256`, I will be glad to test installing it on a RHEL[7-9] system at our site, to ensure it installs without error on all 3 RHEL versions.

Thanks!

**Comment by IsmaelMartinez** [comment]
https://github.com/electron-userland/electron-builder/issues/8198 .

I tried to add that option to release 1.5.0 but failed (so revert it). I might try again later on. Maybe it was the order of commands.

**Comment by IsmaelMartinez** [comment]
See if you can try the [pre-release 1.5.2](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.5.2)? I added that rpm-digest flag. Ta

**Comment by bviviano** [comment]
It's not signed:
```
# yum update ./teams-for-linux-1.5.2.x86_64.rpm 
Updating Subscription Management repositories.
Last metadata expiration check: 0:04:51 ago on Tue 28 May 2024 01:31:51 PM EDT.
Dependencies resolved.
========================================================================================================================
 Package                          Architecture            Version                   Repository                     Size
========================================================================================================================
Upgrading:
 teams-for-linux                  x86_64                  1.5.2-1                   @commandline                   71 M

Transaction Summary
========================================================================================================================
Upgrade  1 Package

Total size: 71 M
Is this ok [y/N]: y
Downloading Packages:
Package teams-for-linux-1.5.2.x86_64.rpm is not signed
Error: GPG check FAILED
# 
```
Can you sign it with the normal GPG key and re-deploy?

**Comment by bviviano** [comment]
I went ahead and signed the RPM with our local signing key that we use for our own RPM's so I could test it without having to `--nogpgcheck`, so it was more consistent with a normal update, and it installed without error:
```
$ sudo yum update ./teams-for-linux-1.5.2.x86_64.rpm 
Updating Subscription Management repositories.
Last metadata expiration check: 1:15:36 ago on Tue 28 May 2024 01:31:51 PM EDT.
Dependencies resolved.
========================================================================================================================
 Package                          Architecture            Version                   Repository                     Size
========================================================================================================================
Upgrading:
 teams-for-linux                  x86_64                  1.5.2-1                   @commandline                   71 M

Transaction Summary
========================================================================================================================
Upgrade  1 Package

Total size: 71 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                1/1 
  Upgrading        : teams-for-linux-1.5.2-1.x86_64                                                                 1/2 
  Running scriptlet: teams-for-linux-1.5.2-1.x86_64                                                                 1/2 
update-alternatives is /sbin/update-alternatives

  Cleanup          : teams-for-linux-1.5.0-1.x86_64                                                                 2/2 
  Running scriptlet: teams-for-linux-1.5.0-1.x86_64                                                                 2/2 
/usr/bin/teams-for-linux has not been configured as an alternative for teams-for-linux
warning: %postun(teams-for-linux-1.5.0-1.x86_64) scriptlet failed, exit status 2

Error in POSTUN scriptlet in rpm package teams-for-linux
  Verifying        : teams-for-linux-1.5.2-1.x86_64                                                                 1/2 
  Verifying        : teams-for-linux-1.5.0-1.x86_64                                                                 2/2 
Installed products updated.

Upgraded:
  teams-for-linux-1.5.2-1.x86_64                                                                                        

Complete!
$ rpm -q teams-for-linux
teams-for-linux-1.5.2-1.x86_64
$ 
```
So, I think you've resolved the issue I was having.  I'd say leave this ticket open until the next release (whichever one comes out after 1.5.2) and I'll install it via `dnf` from the normal repo and verify its working as expected.

Thanks!

**Comment by IsmaelMartinez** [comment]
I assume this is sorted. please report back otherwise and I can re-open. Trying to keep the list of issues manageable
