### ISSUE TITLE
System tray icon does not show new chats badge anymore (ver. 1.4.27 on Linux / GNOME)

### ISSUE THREAD

**Issue by dxps** [IsmaelMartinez/teams-for-linux#1207]
**Describe the bug**
With the recent updates, the system tray icon does not show that new entries exists.
See the screenshot below.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS (up to date)
 - Installation package: deb
 - Version: 1.4.27

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/14140226/a5128545-15ad-419b-b02f-0eebe729ad00)

Thanks!

**Comment by IsmaelMartinez** [comment]
Hi,

This is probably related to the angular to react move that MS have done. 

If you use the config option `useMutationTitleLogic` you should get those notifications again.

See in:
https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config 

duplicated from https://github.com/IsmaelMartinez/teams-for-linux/issues/1172

**Comment by IsmaelMartinez** [comment]
closing as this is solved by that config option as explained in #1172 , so this can be considered as duplicated.

**Comment by dxps** [comment]
@IsmaelMartinez As always, many thanks for the great feedback! :pray: 

Sorry, for the duplicate. As nothing related found in the first page of issues, I thought the issue is pretty new.

To others that might get into the same problem, I ended up having the following config:
```shell
~ ❯ cat .config/teams-for-linux/config.json 
{
	"disableNotificationSound": true,
	"useMutationTitleLogic": true
}
~ ❯ 
```

**Comment by IsmaelMartinez** [comment]
we should probably make this as default. I will have a look tomorrow or later tonight, but it the useMutationTitleLogic can just be a default value as it should just work either way. (and is a recurrent issue reported)

**Comment by IsmaelMartinez** [comment]
I have made useMutationTitleLogic default to true in version [1.4.30](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.30) and mark it as a pre-release. Can you check if it does work for you? Thanks

**Comment by dxps** [comment]
@IsmaelMartinez  Thanks! :pray:  Sure! 

Just installed it, removed that flag from the config (since now it's true by default) and started the new version.
It looks fine for now. It correctly refrlected the initial updates on systray icon.
