### ISSUE TITLE
Feature Request: Add configuration option to disable in-app notifications for "electron" notificationMethod

### ISSUE THREAD

**Issue by vapdrs** [IsmaelMartinez/teams-for-linux#1208]
**Is your feature request related to a problem? Please describe.**

I find the in-app notification windows in TeamsV2 to be distracting, and when they appear in the bottom right of the screen they block screen real estate of the message typing bar and the send button. 

**Describe the solution you'd like**

I would like a configuration option, documented in the config README which disables the display of these in-app notification windows, without affecting the system notifications delivered by the `"notificationMethod": "electron"` config option.

**Describe alternatives you've considered**

An alternative to this for me would be to move these notification windows to the top left of the screen where they are less in the way, and use a less bright color scheme. However these notifications would still be redundant with the system notifications I already get.

**Additional context**

An example notification window which I would like to disable:
![TeamsNotificationBlur](https://github.com/IsmaelMartinez/teams-for-linux/assets/48334845/6742135c-4b6e-48ad-be53-a26a7c8b31ce)

**Comment by IsmaelMartinez** [comment]
Hi @vapdrs , have you tried the different config options? specially the `disableNotifications` as described in https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config . Hope helps

**Comment by vapdrs** [comment]
I tried a test with,

```json
{                                                                                                                                                                                            
"disableNotifications": "true",                                                                                                                                                    
"notificationMethod" : "electron",                                                                                                                                                           
"defaultNotificationUrgency": "normal",                                                                                                                                                      
"optInTeamsV2" : "true"                                                                                                                                                                      
}    
```

which disabled the "electron" system notifications that get displayed in my toolbar, but that in-app notification window still persists. 

I also tested with,

```json
{                                                                                                                                                                                            
"disableNotificationWindowFlash": "true",                                                                                                                                                    
"notificationMethod" : "electron",                                                                                                                                                           
"defaultNotificationUrgency": "normal",                                                                                                                                                      
"optInTeamsV2" : "true"                                                                                                                                                                      
}    
```

which had no effect on the system notifications, nor the in-app notification window.

**Comment by IsmaelMartinez** [comment]
what happens if you use the notificationMethod as 'web'? I think the disableNotifications part might only be working for the web notificationMethod... but I might be wrong.

**Comment by vapdrs** [comment]
I tested with `"web"`, and then `"disableNotifications"` does prevent the in-app notification window from popping up. So that is good.

I initially switched to the `"electron"` notification method such that I could reliably get system notifications in GNOME.

![SystemNotificationBlur](https://github.com/IsmaelMartinez/teams-for-linux/assets/48334845/1500f6a3-4dad-4c51-80b1-c7857bb2faae)

**Comment by skoruppa** [comment]
Yeah, It would be cool to have normal system notifications but to disable (hide) those new in app notifications

**Comment by jijojosephk** [comment]
This is extremely difficult but let's consider as an enhancement.

**Comment by vapdrs** [comment]
FYI, I would consider this fairly low priority.

**Comment by IsmaelMartinez** [comment]
I think we can apply some of the config options into https://github.com/IsmaelMartinez/teams-for-linux/blob/d0b86a2fa73a028818242d3a538ca14ca4bb16a6/app/index.js#L154 . This "might" help the situation but I am surprised the disableNotifications doesn't disable the electron part as it should be catch in https://github.com/IsmaelMartinez/teams-for-linux/blob/d0b86a2fa73a028818242d3a538ca14ca4bb16a6/app/browser/index.js#L23
