### ISSUE TITLE
snap can no longer connect to camera

### ISSUE THREAD

**Issue by zigford** [IsmaelMartinez/teams-for-linux#121]
Previously the snap version would see my camera as I had done this after first installing:
sudo snap connect teams-for-linux:camera core:camera

However, teams-for-linux no longer sees my camera and the command now produces this error:

`error: snap "teams-for-linux" has no plug named "camera"`

I wondered if commit 226f21a had something to do with it, as 'camera' is no longer a child of the plugs property on snapcraft.yaml

**Comment by pplu** [comment]
Same behaviour here

**Comment by julian-alarcon** [comment]
Which version are you using of the client? And are you building it or using the one available in the Store?

**Comment by pplu** [comment]
> Which version are you using of the client? And are you building it or using the one available in the Store?
I'm using the snap from the store. Here you have relevant info:

```
$ snap info teams-for-linux
name:      teams-for-linux
summary:   teams-for-linux
publisher: Julian Alarcon (alarconj)
contact:   https://github.com/IsmaelMartinez/teams-for-linux
license:   unset
description: |
  Unofficial Microsoft Teams client for Linux using Electron. It uses the Web App and wraps it as a
  standalone application using Electron.
commands:
  - teams-for-linux
snap-id:      IIAJhVGfBhm393UTagoW5awtZlPDGqHd
tracking:     edge
refresh-date: yesterday at 12:17 CEST
channels:
  stable:    –                          
  candidate: –                          
  beta:      0.2.0 2019-04-25 (4) 128MB -
  edge:      0.2.1 2019-04-28 (6) 128MB -
installed:   0.2.1            (6) 128MB -
```

**Comment by IsmaelMartinez** [comment]
Hi all,

Thanks for reporting. Use 0.2.0 in the meantime. The change you mention should not be related as that was just a try to get it working with build.snapcraft.org (but we can't as we need to recompile some stuff ).

I suspect is the change from development to strict.. maybe we need to specify camera in the electron-builder (package.json). By default picks up lots of stuff but I don't think it does for the camera.

**Comment by julian-alarcon** [comment]
I can confirm this issue, is related with some new stuff to automate the deployment to Snap Store.

**Comment by IsmaelMartinez** [comment]
ok, edge should be working again as soon as the next development build happens.

This was the PR. 
https://github.com/IsmaelMartinez/teams-for-linux/pull/120

@julian-alarcon , thanks for checking it and finding the missing plugs.

Can you guys test it? it will not be release probably until 30 minutes from now... the build takes a bit of time as it builds a bizilion types of packages.

**Comment by julian-alarcon** [comment]
Just confirmed that this bug is fixed. 0.2.1 snap version (rev 8) works with the camera with no issues after adding the permissions.
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#use-camera-using-the-snap-build

**Comment by pplu** [comment]
@julian-alarcon @IsmaelMartinez : confirmed that the camera is working again after refreshing the snap :)
