### ISSUE TITLE
Chats list panel didn't change size between the small and full size window

### ISSUE THREAD

**Issue by jpurpleman** [IsmaelMartinez/teams-for-linux#1210]
**Describe the bug**
When I start the Teams for Linux app in a small window mode, the list of chats takes the entire space top to bottom.  When I maximise the app, the area for the chats list panel didn't change size between the small and full size window.

This just started after I updated microsoft-edge-stable:amd64 from 123.0.2420.81-1 to 123.0.2420.97-1

**To Reproduce**
1. Open Teams for Linux in a small window
2. While in Teams section, using CTRL + Mouse wheel, zoom out and make the text smaller.
3. Go to Chat section
4. Make the Teams for Linux window full screen
5. Please look at where the chat list ends

**Expected behavior**
The chat panel to scale with the size as per the window size.

**Screenshots**
This is a screenshot of the initial small window.
![2024-04-18_22:13:11](https://github.com/IsmaelMartinez/teams-for-linux/assets/8206604/587f89cc-dbbd-4393-8cd3-ec31bd74e495)

Here is my full screened window.
![2024-04-18_22:13:39](https://github.com/IsmaelMartinez/teams-for-linux/assets/8206604/86d7c24c-722e-4dc3-8667-5612f564417a)

![2024-04-18_22:28:29](https://github.com/IsmaelMartinez/teams-for-linux/assets/8206604/ef72259c-38c4-44a8-8330-b2a73b2d9315)

**Desktop (please complete the following information):**
 - OS: Linux Mint 23.1
 - Installation package: deb
 - Version : 1.4.27 on 2024-04-15 @ 10:29:19

**Debug**
[DEBUG] configPath:,/home/jperlman/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[DEBUG] Fetching custom background configuration from 'http://localhost/config.json'
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--webDebug,--appLogLevels=error,info,warn,debug
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
[DEBUG] Language codes en set for spellchecker
[ERROR] Failed to fetch custom background remote configuration. net::ERR_CONNECTION_REFUSED
[DEBUG] Network test successful with method https
[418360:0418/224014.887237:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[418360:0418/224014.891618:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[418360:0418/224018.127421:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] did-frame-finish-load,[object Object],false
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 1s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] window close
[DEBUG] window close
[DEBUG] window closed
[DEBUG] before-quit
[DEBUG] will-quit
[DEBUG] quit

**Comment by jpurpleman** [comment]
I updated to 1.4.28 and the issue was still there.

I closed Teams and I cleared Storage and it seems, * crossing fingers *, to be gone.

**Comment by IsmaelMartinez** [comment]
sometimes the storage can get a bit corrupted, specially when we upgrade the electron version. I will close it but do reach out if you experience the same issue. Ta
