### ISSUE TITLE
teams-for-linux.desktop Ignored Soft Link

### ISSUE THREAD

**Issue by changyp6** [IsmaelMartinez/teams-for-linux#1213]
**Describe the bug**
`teams-for-linux` rpm package created a soft link using `alternatives`
This soft link is installed to `/usr/bin/teams-for-linux`
However, in the `teams-for-linux.desktop`, it is still
`Exec=/opt/teams-for-linux/teams-for-linux %U`
It should be
`Exec=/usr/bin/teams-for-linux %U`

Because I use Wayland KDE as my desktop, I need to add
`--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime`
parameters when starting teams-for-linux

So I created a `/usr/local/bin/teams-for-linux-wayland` script containing
```
#!/usr/bin/bash
/opt/teams-for-linux/teams-for-linux --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime $@
```
Then use command
`sudo alternatives --install /usr/bin/teams-for-linux teams-for-linux /usr/local/bin/teams-for-linux-wayland 0`
to install it.

So I need teams-for-linux.desktop to open my script

Please help fix this issue.

**Comment by IsmaelMartinez** [comment]
Can this be related to https://github.com/IsmaelMartinez/teams-for-linux/issues/958 ? I have no idea, but things failing during the postscript might be creating oddities. Hope helps!
