### ISSUE TITLE
Teams does not start from time to time

### ISSUE THREAD

**Issue by jrevillard** [IsmaelMartinez/teams-for-linux#1216]
**Describe the bug**

Teams is stuck and do not start

**To Reproduce**
1. Start your computer
2. Start teams-for-linux.... it's stuck (it never start nor crash/timeout

>❯ teams-for-linux --appLogLevels debug
[DEBUG] configPath:,/home/jerome/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[DEBUG] Fetching custom background configuration from 'http://127.0.0.1:81/config.json'

3.  of course the url 'http://127.0.0.1:81/config.json' is accessible but even with the default value or something completely wrong the behavior is the same:

>❯ teams-for-linux --appLogLevels debug --customBGServiceBaseUrl xxx://fake
[DEBUG] configPath:,/home/jerome/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[DEBUG] Fetching custom background configuration from 'xxx://fake/config.json'

**Expected behavior**
teams-for-linux should start.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Installation package: deb
 - Version: 1.4.29

**Comment by neoiarst** [comment]
I've been getting a similar issue for a couple of days,

OS:

- Debian trixie (Linux 6.6.15-amd64) (testing)
- Installation package: snap
- $teams-for-linux --version
    1.4.25

Currently it won't open at all.

I am guessing this is related to Microsoft's Teams rollout timeframe (a staff member had issues with Teams Classic today for the first time and I had to shift him over to New Teams on Win10)

**Comment by jrevillard** [comment]
I don't know if this is the same issue... it seems that the process in my case is blocked in the custom background management isn't it ?

I'm also using Teams V2 and I did not clear the storage. In my case, the teams-for-linux user interface even do not show.

Best,
Jerome

**Comment by jijojosephk** [comment]
If you're facing issue with `snap`, try `deb` or `rpm` or may be `flatpak`

**Comment by jijojosephk** [comment]
@jrevillard is it when you give custom background url? leave the defaults and try.  Another reason could be you're using a proxy to connect to internet.

**Comment by IsmaelMartinez** [comment]
Hi @jrevillard , can you try to start the command with `--appLogLevels=error,info,warn,debug` and put the output in here?

That appLogLevels doesn't use a hierarchical logic. I suspect you are right and the custom background might be doing something funny. I mean, they aren't working and we know that, but they should not stop the app from starting. 

@neoiarst , I also think is a different issue. Check https://github.com/IsmaelMartinez/teams-for-linux/issues/1156 and see if using those config options works (they can also be run as command options)

**Comment by jrevillard** [comment]
No more logs....:

~ ❯ teams-for-linux --webDebug --appLogLevels=error,info,warn,debug --optInTeamsV2                                                                                                     
[DEBUG] configPath:,/home/jerome/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[DEBUG] Fetching custom background configuration from 'http://127.0.0.1:81/config.json'

The web page is working:

~ ❯ curl http://127.0.0.1:81/config.json
[
        {
                "filetype": "jpg",
                "id": "image",
                "name": "image",
                "src": "/Teams_Background_thumbnail_1920x1080.jpg",
                "thumb_src": "/Teams_Background_thumbnail_280x158.jpg"
        }
]

With default url, same issue... it never timeout.

Best,
Jerome

**Comment by jijojosephk** [comment]
What if you give `http://localhost:81` ?

**Comment by jrevillard** [comment]
> What if you give `http://localhost:81` ?

I will tell you as soon as it blocks again :-)... since a couple of minutes, now it works:

```
~ ❯ teams-for-linux --webDebug --appLogLevels=error,info,warn,debug --optInTeamsV2                                                                                                        12s
[DEBUG] configPath:,/home/jerome/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[DEBUG] Fetching custom background configuration from 'http://127.0.0.1:81/config.json'
[DEBUG] Custom background service url is 'http://127.0.0.1:81'
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--webDebug,--appLogLevels=error,info,warn,debug,--optInTeamsV2
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
....
```

Strange the order of those 2 lines isn't it ?:

```
[DEBUG] Fetching custom background configuration from 'http://127.0.0.1:81/config.json'
[DEBUG] Custom background service url is 'http://127.0.0.1:81'
```

Best,
Jerome

**Comment by jb-lopez** [comment]
I'd like to add that for me at least there is some issue with the `snap` version. I can run the `snap` when initially installed. But when I exit teams and relaunch it, it fails to launch with this:
```
$>teams-for-linux 
[WARN] No config file found, using default values
dbus-send: /snap/teams-for-linux/567/lib/x86_64-linux-gnu/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.12.20' not found (required by dbus-send)

(teams-for-linux:1458369): Gtk-WARNING **: 08:57:44.811: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
Gtk-Message: 08:57:44.819: Failed to load module "colorreload-gtk-module"
Gtk-Message: 08:57:44.819: Failed to load module "window-decorations-gtk-module"

(teams-for-linux:1458369): Gtk-WARNING **: 08:57:44.900: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
Illegal instruction (core dumped)
```
The `deb` version does not have this issue. Thanks for the great work!

**Comment by jrevillard** [comment]
> What if you give `http://localhost:81` ?

Ok so starting my computer today and same issue again... localhost does not change anything:

```
> ~ ❯ teams-for-linux --webDebug --appLogLevels=error,info,warn,debug --optInTeamsV2 --customBGServiceBaseUrl http://localhost:81
[DEBUG] configPath:,/home/jerome/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[DEBUG] Fetching custom background configuration from 'http://localhost:81/config.json'
```

**Comment by IsmaelMartinez** [comment]
custom background is not working currently for teams v2 so this might be making this fail. 

If you still need custom background, I would recommend using OBS or similar until we get it fixed in here. 

Also, the command tends to work better if you put a = instead of a space between customBGServiceBaseURL and the http...

`teams-for-linux --webDebug --appLogLevels=error,info,warn,debug --optInTeamsV2 --customBGServiceBaseUrl=http://localhost:81` , but again, I think that part of the code is just broken.

**Comment by IsmaelMartinez** [comment]
Ok, this could be related to the move to electron 30.0.0. We have reverted this. Can you try https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.34 ?

**Comment by IsmaelMartinez** [comment]
Hi, there is a possible fix for the custom background logic under https://github.com/IsmaelMartinez/teams-for-linux/pull/1226 Is is possible one of you can check if that works? If so we can expedite its delivery. Thanks!

**Comment by jijojosephk** [comment]
Upstream issue [41839](https://github.com/electron/electron/issues/41839).

**Comment by jrevillard** [comment]
> Hi, there is a possible fix for the custom background logic under #1226 Is is possible one of you can check if that works? If so we can expedite its delivery. Thanks!

Sorry for the late reply... I just reboot and it's stuck:

```
~ ❯ teams-for-linux --version 
1.4.37
~ ❯ teams-for-linux --webDebug --appLogLevels=error,info,warn,debug --optInTeamsV2 --customBGServiceBaseUrl=http://localhost:81
[DEBUG] configPath:,/home/jerome/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
```

I cannot abort anymore using `Ctrl+C` or anything else... I have to kill it from another terminal.

Wouldn't it be possible to add a new option to simply bypass all this logic ?

Best,
Jerome

**Comment by IsmaelMartinez** [comment]
Hi @jrevillard , do you mean disable the background logic? It should be disabled by default in 1.4.37 as we changed the default value of `isCustomBackgroundEnabled` to be false. If you want to use customBackground you will need to enable that in your config file and/or command line.

Something to notice is that the custom background images do require you to put a prefix `/evergreen-assets/backgroundimages/` as shown in:

 https://github.com/jonatasrs/teams-for-linux/blob/develop/app/config/README.md#configuring-list-of-images

Can you put the content the config.json file and the curl http://127.0.0.1:81/config.json ? Thanks

**Comment by jrevillard** [comment]
Hello,

Sorry for the silence... I was quite busy during the last weeks and the problem did not occur anymore until.... this morning  :-( .  I just updated from 1.5.2 to 1.5.3 and it's stuck again (disable GPU just to try to figure out where it is stuck exactly....):

> ~ ❯ teams-for-linux --webDebug --appLogLevels=error,info,warn,debug --optInTeamsV2 --isCustomBackgroundEnabled=false --disableGpu
[DEBUG] configPath:,/home/jerome/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[INFO] Running under Wayland, switching to PipeWire...
[INFO] Disabling GPU support...

Of course, Teams was not the only updated package.

Best,
Jérôme

**Comment by IsmaelMartinez** [comment]
I will close this then, do shout if you start getting this again.

**Comment by jrevillard** [comment]
Hello @IsmaelMartinez ,

back again..... still using the deb installation. Since a week or a bit more, I again face this issue:

```
~ ❯ teams-for-linux --webDebug --appLogLevels=error,info,warn,debug --optInTeamsV2 --isCustomBackgroundEnabled=false                                                                  
[DEBUG] configPath:,/home/jerome/.config/teams-for-linux
[WARN] No config file found, using default values
[DEBUG] configFile:,[object Object]
[INFO] Running under Wayland, switching to PipeWire...

```

I cannot Ctrl+c, I have to `kill -9`

Best,
Jérôme
