### ISSUE TITLE
followSystemTheme not effective anymore since teams v2 - UI stuck in light mode

### ISSUE THREAD

**Issue by andreaippo** [IsmaelMartinez/teams-for-linux#1217]
I'm using 1.4.27 as a flatpak, and synced theming with the OS was working fine until recently.

I suppose it stopped working when I switched to teams v2.

This is my config.json:

```
{
	"followSystemTheme": true,
	"optInTeamsV2": true,
	"url": "https://teams.microsoft.com/v2/",
	"disableNotificationSound": true
}
```

Has the name of the feature flag changed, do I need to change something here?

Thanks! :)

EDIT: ok it didn't take long to run some more tests.

Indeed it's a v2 regression.
I temporarily switched back to v1, toggled back and forth between the (KDE) Breeze and Breeze dark themes, and with v1 the teams UI is repainted. With v2 it stays in the light mode.

**Comment by ChristoSnake** [comment]
This works as intended with the rpm install.  I'm running Breeze Dark, and my v2 follows the OS nicely:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/2c5b73da-c37c-4bb1-b9a9-140f8bd6bb34)

PS:  I'm on SUSE Tumbleweed, so latest KDE Plasma, KDE Frameworks, QT, etc.

**Comment by jijojosephk** [comment]
@ChristoSnake I think you're talking about the in-app setting provided by Microsoft. @andreaippo is behind `teams-for-linux` provided setting.

**Comment by ChristoSnake** [comment]
Interesting...

I am not using the "followSystemTheme" startup option and its default is false, which means by not specifying the option in my config.json my Teams should not follow the system theme.  Yet it does exactly that!

I've just switched it using the GUI, and it works as dictated by the in app GUI:

- Dark = dark
- Light = light
- Classic = seems the same as Light
- High contrast = ouch, my poor eyes!
- Follow system theme = immediately follows my (dark) system theme.

**Comment by andreaippo** [comment]
Thanks for the feedback everyone.

I had added that config option when I was still on v1, and hadn't thought that it might be useless (or actually, counterproductive) when moving to v2.

I'll try removing it and will report back.

**Comment by andreaippo** [comment]
> Interesting...
> 
> I am not using the "followSystemTheme" startup option and its default is false, which means by not specifying the option in my config.json my Teams should not follow the system theme. Yet it does exactly that!
> 
> I've just switched it using the GUI, and it works as dictated by the in app GUI:
> 
>     * Dark = dark
> 
>     * Light = light
> 
>     * Classic = seems the same as Light
> 
>     * High contrast = ouch, my poor eyes!
> 
>     * Follow system theme = immediately follows my (dark) system theme.

I guess that having that flag enabled was breaking things for me on v2. You had it working perfectly because you never set it, and teams v2 must have done something to finally play nice with Linux OS theming, so that the flag isn't needed anymore, and if you had it set (like me) it was actually breaking stuff.

Imma mention this in the configuration documentation.

**Comment by andreaippo** [comment]
Closing
