### ISSUE TITLE
No notification on tray icon in Teams V2 mode.

### ISSUE THREAD

**Issue by giaur500** [IsmaelMartinez/teams-for-linux#1218]
Recently, I got popup banner to switch to new Teams, so I chose to switch to new Teams. After that, Teams V2 loads all the time by default. It works, however I'm not getting any notification on tray icon, for example for incoming unread messages/chats.

Is there any way to make it working? Is it known issue? Problem is only on new Teams, legacy mode was ok.

**Comment by jijojosephk** [comment]
check this thread https://github.com/IsmaelMartinez/teams-for-linux/issues/1207

**Comment by jijojosephk** [comment]
Re open if you don't get a solution.

**Comment by giaur500** [comment]
Thanks for info, I will test that. Also, you could add mention about this issue in readme (or enable that option by default)

**Comment by IsmaelMartinez** [comment]
Aye, I was thinking the same about making it default. 

To anyone! Feel free to check and/or open a PR to change it. 
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L3

It should be a simple change to change this value to true https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/index.js#L237 and create an PR increasing this number https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L3 from 1.4.29 to 1.4.30 .  

Then we can release it as a pre-release.

Had a quick look around and it should not break anything but a pre-release will tell us.

**Comment by giaur500** [comment]
Hmm please clarify, do I really need to disable notification sound? Is that related to this issue?

**Comment by IsmaelMartinez** [comment]
no, but you might experience that issue also. For the notifications what needs to be enabled is the `useMutationTitleLogic` flag

**Comment by IsmaelMartinez** [comment]
I have made useMutationTitleLogic default to true in version [1.4.30](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.30) and mark it as a pre-release. Can you check if it does work for you? Thanks

**Comment by giaur500** [comment]
I can't confirm it's enabled by default. But I can confirm it solves the problem.
