### ISSUE TITLE
Crash error using electron 5.0.0 on snap build

### ISSUE THREAD

**Issue by julian-alarcon** [IsmaelMartinez/teams-for-linux#122]
**Describe the bug**
I'm trying the new electron version, 5.0. Has new Chromium, Node 12 and V8 engine.
https://electronjs.org/blog/electron-5-0

**To Reproduce**
Steps to reproduce the behaviour:
1. Remove yarn.lock file to generate a new one
2. Change electron version on package.json to 5.0.0
3. Build the snap package and install it
4. Run it on from a terminal, it will crash and show this message:
```
julian@mypc:~/Code/teams-for-linux$ teams-for-linux 
[31893:0502/075604.540153:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/teams-for-linux/x1/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

**Expected behavior**
It should run with no issues

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04/1904
 - Installation package snap
 - Version 0.2.1

**Additional context**
Build on .deb works with no issues

**Comment by IsmaelMartinez** [comment]
we should not be in electron 5.0.0. Drop back to 4.x.x.

There are many changes in node12 that affect the spellchecker and other libraries, so worth waiting until is more stable.

**Comment by julian-alarcon** [comment]
https://github.com/electron/electron/issues/17972

**Comment by julian-alarcon** [comment]
https://github.com/travis-ci/travis-ci/issues/8836
