### ISSUE TITLE
Advantages compared to the PWA version

### ISSUE THREAD

**Issue by res1st** [IsmaelMartinez/teams-for-linux#1222]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm currently using the PWA version and it work's fine.
What is the advantage to use this team wrapper?
It should be documented in the README file

**Comment by LeeRoyManea** [comment]
@res1st  Before Teams 2.0 you could set and use CustomBackgroundWallpaper.
Something Microsoft dont want you to do with the Web Version.

**Comment by IsmaelMartinez** [comment]
Hi, closing this as there is already an open discussion in https://github.com/IsmaelMartinez/teams-for-linux/discussions/622
