### ISSUE TITLE
Crash on Apple Silicon Macs because of unsigned code

### ISSUE THREAD

**Issue by Tasssadar** [IsmaelMartinez/teams-for-linux#1225]
Hello, the Mac build is now universal, but because it is unsigned, it crashes on Apple Silicon macs on startup:
<img width="1042" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/120108/91492ac4-8104-4015-b622-58b5c1c6b7cd">

It [appears](https://code.videolan.org/videolan/vlc/-/issues/26432) that Apple Silicon Macs simply can't run unsigned code (not sure about that, but I was not able to find a workaround). A build from this repo signed with my developer certificate works, but that is trusted only on my machine.

I'm not about to accept Apple's $99 extortion to _checks notes_ be able to run code on my HW, so I guess we're looking for somebody willing to do that.

In the meantime, the universal build now crashes on start on Apple Silicon macs, instead of just being slow - I suppose we should revert  #1212?

**Comment by jijojosephk** [comment]
Dealing the Apple is a costly affair. I doubt someone will do it. @IsmaelMartinez please comment.

**Comment by IsmaelMartinez** [comment]
Hi @Tasssadar , did you install it like for unverified apps? https://support.apple.com/en-gb/guide/mac-help/mh40616/mac If that is breaking the mac installs even when doing that, then we should revert. But I run it in my mac no bother (but from source)

**Comment by Tasssadar** [comment]
Yes, I did. The exception is there and works, it's just that the Apple Silicon Mac has that requirement for signature and it crashes on start. If I run it under rosetta (the x86 emulation layer), it works.

Will prepare a PR to revert.

**Comment by IsmaelMartinez** [comment]
I will se if I can add code signing without needing to pay the $99, but I doubt I will have much time and we got quite a few other open issues. Thanks for reporting!

**Comment by kblaschke** [comment]
> I will se if I can add code signing without needing to pay the $99

As you need an Apple Developer ID for distribution, sadly, there isn't a way to get around that - only if you're running [a registered non-profit organization](https://developer.apple.com/support/fee-waiver/) or educational/governmental institution. Apple could just add open-source projects to that exclusion list to solve the issue, but well...

After clearing the quarantine bit, the latest (1.4.33) build works fine on my M2 MacBook though.

**Comment by IsmaelMartinez** [comment]
closing this as complete. Thanks @Tasssadar and @kblaschke
