### ISSUE TITLE
Multiple instances?

### ISSUE THREAD

**Issue by giaur500** [IsmaelMartinez/teams-for-linux#1231]
Not sure it it's already possible or not. I want to run multiple instances, my case is appimage files. I tried to move appimage file to other directory + rename file. But it still won't start as second instance, it will redirect to already running one.

 Is this possible to make it to run from other directory as completly separate instance and separate settings? I need that to login to 2 accounts at the same time, which is not supported by Teams itself. 

Usually, it's enough to rename appimage file and it will create separate config, but not in this case.

**Comment by IsmaelMartinez** [comment]
closing as duplicated. See https://github.com/IsmaelMartinez/teams-for-linux/issues/438#issuecomment-1750270198 on how to archive this.
