### ISSUE TITLE
Spell check not enabled

### ISSUE THREAD

**Issue by benjdevries** [IsmaelMartinez/teams-for-linux#1235]
**Describe the bug**
Spell checking seems to be disabled completely. I haven't worked with electron personally before, but my understanding is that it should have access to Chromium's spell checker by default.

**To Reproduce**
1. Start any draft message, chat, etc.
2. Spell something wrong
3. Notice no red squiggles appear

**Expected behavior**
Spell check catches typos 

**Screenshots**
Behavior in teams-for-linux client:
![Screenshot from 2024-04-29 10-44-47](https://github.com/IsmaelMartinez/teams-for-linux/assets/55499121/8299ccb7-a1b9-4a52-abd8-2757eed5fb1a)

Behavior in browser client (PWA using Chrome 124.0.6367.60)
![Screenshot from 2024-04-29 10-45-36](https://github.com/IsmaelMartinez/teams-for-linux/assets/55499121/daa598b7-1c4c-44d4-8620-99b88e02c46e)

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Installation package: flatpak
 - Version: 1.4.30

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
```

**Additional context**

**Comment by jijojosephk** [comment]
It's a feature not enabled by default because we can't set a default language for a user also when `sandboxed` like `snap` or `flatpak` app fails to detect the locale correctly. 

When you right click on an text area you would see a menu with that option. You can choose your language(s) and will be persisted between restarts.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/7e71bf2a-32dc-4897-80de-8016e93fd490)

**Comment by jijojosephk** [comment]
Closing, let us know if you face challenges.

**Comment by benjdevries** [comment]
Thanks for the quick response! That did indeed fix my issue. And I'm just now seeing it listed in `KNOWN_ISSUES.md`, so my apologies for not looking there first!

Not sure if you get many false reports of this issue, but it may be helpful to include a specific call out in `README.md` for enabling spell check for these installation methods. Since spell check is such a vital QoL feature, it would be nice to see it specifically mentioned in the installation steps rather than having to search for a solution after installation.

**Comment by jijojosephk** [comment]
> Thanks for the quick response! That did indeed fix my issue. And I'm just now seeing it listed in `KNOWN_ISSUES.md`, so my apologies for not looking there first!
> 
> Not sure if you get many false reports of this issue, but it may be helpful to include a specific call out in `README.md` for enabling spell check for these installation methods. Since spell check is such a vital QoL feature, it would be nice to see it specifically mentioned in the installation steps rather than having to search for a solution after installation.

Sure. We'll update the readme. Thank you!
