### ISSUE TITLE
Application crashes on startup

### ISSUE THREAD

**Issue by lxndrdnxl** [IsmaelMartinez/teams-for-linux#1237]
**Describe the bug**
After starting the application the window shows for a moment and shuts down almost immediately. There is no process in the process list.

**To Reproduce**
1. Start the application

**Expected behavior**
The application starts successfully.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2 Cinnamon
 - Installation package:  flatpak
 - Version: 1.4.30

**Debug**

```bash
09:25:49 alex@alex-workmachine ~ → flatpak run com.github.IsmaelMartinez.teams_for_linux --webDebug  --appLogLevels=error,info,warn,debug
[2:0430/092551.721511:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[DEBUG] configPath:,/home/alex/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux
[WARN] No config file found, using default values
[DEBUG] configFile:,[object Object]
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 09:25:51.972: Failed to load module "xapp-gtk3-module"
[2:0430/092552.040602:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0430/092552.040642:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[DEBUG] Fetching custom background configuration from 'http://localhost/config.json'
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/app/teams-for-linux/teams-for-linux,--webDebug,--appLogLevels=error,info,warn,debug
[2:0430/092552.198274:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0430/092552.198333:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0430/092552.198384:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
[DEBUG] Spellchecker is disabled!
```

**Comment by IsmaelMartinez** [comment]
can you check if starting the app with the following flag solves your crash? `--useMutationTitleLogic=false` 

It might be the case that because you are still in teamsv1 this new logic is making the app crash. I think is the same issue as https://github.com/IsmaelMartinez/teams-for-linux/issues/1232

**Comment by IsmaelMartinez** [comment]
can you try using https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.27 version and see if that one still fails? My suspicion now moves to the electron version update. (I am not sure how you can use older version in flathub)

**Comment by lxndrdnxl** [comment]
I downgraded to v1.4.25 (I didn't see 1.4.27 in the version log) and it's working fine!

**Comment by IsmaelMartinez** [comment]
so it must be the electron upgrade. Can you clean your flatpack cache after updating to 1.4.30 (or later if has make it there) and see if that works? 
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#blank-page Sometimes electron upgrades can mess up with the cache, specially a big upgrade like 30.0.0

**Comment by lxndrdnxl** [comment]
I didn't have the directory 'Application Cache' but I deleted all content of /home/alex/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux/Partitions/teams-4-linux/Cache and it works with the latest version installed through flatpak (which is still 1.4.30)!

**Comment by lxndrdnxl** [comment]
I now installed it through apt. 
I restarted it a few teams and it crashed every other time.

**Comment by jijojosephk** [comment]
Can you try the latest `1.4.34` `pre-release` ?

**Comment by Gundalf72** [comment]
I can try this.

Could you give me the _flatpak_ command please - I'm not familiar enough with it.

Thanks

**Comment by jijojosephk** [comment]
`flatpak` builds are not automated from the `stable` github release. You can't have a test version of `flatpak` package at the moment. `1.4.34` is released as stable now. You would see the updated flatpak version soon.

**Comment by Gundalf72** [comment]
1.4.34 update works ... thanks folks!

**Comment by mikehaertl** [comment]
I suffered the same problem: app crashed often on startup - had to retry a couple of times until it succeeded.

With `1.4.34` this is no longer the case: app starts fine again.

FWIW I'm also on Linux Mint 21.3 Virginia.

**Comment by jijojosephk** [comment]
`electron` `30` was the culprit. But I still wonder it worked in fine in `GNOME`

**Comment by IsmaelMartinez** [comment]
electron new version releases can be a bit brutal and accept that a few things will not work until fixed. I tend to prefer to wait until x.1.x (so 30.1.x) rather than go with the x.0.x ones. They seem a bit more stable.

**Comment by jijojosephk** [comment]
Upstream issue [41839](https://github.com/electron/electron/issues/41839).
