### ISSUE TITLE
give some information of the app name in the popup of appdicator

### ISSUE THREAD

**Issue by lidaobing** [IsmaelMartinez/teams-for-linux#1238]
For example:

could you change "Open" to "Open Teams for Linux"
or change "About" to "About Teams for Linux"

so we can get the name of the app, especially when the tray icon is not clear or we are not familiar with the icon.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/27529/508fe038-f86c-44c5-82bc-f4d7a1911a48)

**Comment by jijojosephk** [comment]
We'll brainstorm what's the best approach.

**Comment by IsmaelMartinez** [comment]
The top menu icon had the name as "application". I have changed this to "Teams for Linux".

Depending on your UI, you should now get that info by hoovering over the icon. 

This has been released in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.2 (well, pre-release now)

Closing this as completed, but let me know if this is not working for you and we can see if we can modify the menu
