### ISSUE TITLE
calling does not work when run from source

### ISSUE THREAD

**Issue by m27315** [IsmaelMartinez/teams-for-linux#124]
**BUG**
When running the latest from source, the app appears.  I can login, chat, and do everything I would do from web app in Chrome on Linux.  However, initiating a chat produces the exact same messages as when run from Chrome on Linux:

```
Try a different browser
This feature isn't available yet for your browser. Try the web app with Microsoft Edge or Google Chrome, or switch to the desktop app.
```

**To Reproduce**
1. clone teams-for-linux repo
2. Install missing npm modules:
```
npm install --save electron-window-state
npm install --save yargs
npm install --save electron-native-notification
```
3. Run from source:  `yarn start`
4. After logging into Teams from newly opened app window, select a buddy in "Chat" and click on "Call" (telephone) icon.

**Expected Behavior**
To make calls with audio & video using my web-cam.

**Desktop**
 - OS: Gentoo (current)
 - Installation package: source
 - Version:  a895dfc
- yarn:  1.15.2
- electron:  v4.0.7

**Additional**
I verified that my web-cam works using a native Linux app, Kamoso.

**Comment by m27315** [comment]
I dropped back from the tip of the `develop` branch at `a895dfc` to the `v0.20.0` release, and it worked!  The app also started with very different stdout text in the terminal:

`develop - a895dfc`:
```
 $ yarn start
yarn run v1.15.2
$ electron ./app



^C
```
Versus, `v0.20.0`:
```
$ yarn start
yarn run v1.15.2
yarn install && electron ./app
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ electron-builder install-app-deps
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=spellchecker
[9594:0502/102513.102133:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
[OpenH264] this = 0x0x3c19c35ec4b0, Warning:Change QP Range from(0,51) to (12,42)
[OpenH264] this = 0x0x3c19c35ec4b0, Warning:Change QP Range from(0,51) to (12,42)
[OpenH264] this = 0x0x3c19c3e14ea0, Warning:Change QP Range from(0,51) to (12,42)
[OpenH264] this = 0x0x3c19c3e14ea0, Warning:Change QP Range from(0,51) to (12,42)
[9594:0502/102715.239620:ERROR:stunport.cc(87)] Binding request timed out from 172.22.182.x:37462 (tun0)
[9594:0502/102715.239697:ERROR:stunport.cc(87)] Binding request timed out from 192.168.78.x:36934 (vboxnet22)
[OpenH264] this = 0x0x3c19c5768db0, Warning:Change QP Range from(0,51) to (12,42)
...
```

Does this represent a bug in the tip of develop, or is some special magic performed only for releases?

**Comment by IsmaelMartinez** [comment]
the "yarn start" should be performing "yarn install" 

https://github.com/IsmaelMartinez/teams-for-linux/blob/v0.2.0/package.json#L20

I did remove that `yarn install` to accelerate my testing but seems like I forgot to put it back.

Thanks for finding this, it should be fix just now.
