### ISSUE TITLE
Can't use ibus input method(like ibus-latext or ibus-pinyin) inside teams for linux

### ISSUE THREAD

**Issue by lidaobing** [IsmaelMartinez/teams-for-linux#1240]
**Describe the bug**

**To Reproduce**
1. open teams for linux
2. switch to ibus-latex input method
3. type "\"
4. expect input method activated, but only insert the \ to the chat box

**Expected behavior**
1. the latex input method popup, like
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/27529/c435083d-c983-4d64-bb3a-6c79eb72df20)

**Screenshots**
as above

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 22.04
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...] snap
 - Version [e.g. 0.1.17] 1.4.31

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
```

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi @lidaobing , I think this is an electron issue rather than an app issue.

Can you check in their issues and see if you can find a solution in there? https://github.com/electron/electron/issues

Hope you find it. I keep this open for a while to see if someone else have found the issue and/or a solution.

**Comment by lidaobing** [comment]
I got one url for snap: https://forum.snapcraft.io/t/compatibility-with-cjkv-input-method-frameworks/7788

hope it can help

**Comment by IsmaelMartinez** [comment]
I tried adding this into the build, but it looks like it is already included in the default packages (the build failed indicating we where trying to include it twice).

**Comment by IsmaelMartinez** [comment]
closing as, unfortunately, i don't think we can do anything from here. 

There is a similar issue reported in Microsoft Teams in https://feedbackportal.microsoft.com/feedback/idea/1079b1df-78bd-ed11-83ff-002248273995?q=latex+teams . I would suggest following that issue as that would apply into here once they add the support.
