### ISSUE TITLE
Question: how to use "Apps" (e.g. Azure Boards) with teams-for-linux

### ISSUE THREAD

**Issue by NeilsC** [IsmaelMartinez/teams-for-linux#1241]
Is there a way to use the add-on "Apps"? I've tried using the Azure Boards app, but it requires signing in. Clicking the sign-in link opens the page in my default browser (Firefox), so that doesn't work.

For reference, here's a screenshot demonstrating what happens when I paste a link to an Azure DevOps work item in a message:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/1214412/4946f4c4-2f6d-4338-887f-8e2a789f1b61)

**Comment by jijojosephk** [comment]
You need to use `CTRL` + `Click`. That will give you a dialog like this.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/016836a0-28f4-4817-8928-a1c5f70b5bc6)

Click allow which would open a small window in the same context. You can login there and it should be fine.

**Comment by IsmaelMartinez** [comment]
a bit more explanation of why you need ctrl + click. That "tells" the app to open the link into the same context/session we are in the app. What you are seeing is that the app is opening in the browser, and that is starting a new session (as electron/the app/ can't share the session with the browser). 

Unfortunately there isn't an easy way currently to decide when to open in the browser and what to open in the app. We do it for a few urls we know, but can't do for each app available, as it really depends on their implementation.
