### ISSUE TITLE
the "About" window is broken (missing fonts?)

### ISSUE THREAD

**Issue by atommaki** [IsmaelMartinez/teams-for-linux#1242]
**Describe the bug**
This is a screenshot of the "About" window on my Ubuntu 24.04 desktop
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/14099928/92f08457-908c-4c62-b061-ea9bfab26f9c)
I don't see any missing fonts anywhere else in Teams or elsewhere on the system.

**Desktop:**
 - OS: Ubuntu 24.04
 - Installation package: snap
 - Version: 1.4.31

**Comment by atommaki** [comment]
I've installed the latest 1.4.34 (still as snap), the issue is the same.

**Comment by jijojosephk** [comment]
This is a snap issue. Try the below.

```console
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by IsmaelMartinez** [comment]
yep, we have seen this in the past and been related to snap configuration. 

Marking it as duplicated of https://github.com/IsmaelMartinez/teams-for-linux/issues/357

**Comment by atommaki** [comment]
Thanks, indeed, the fontconfig cache cleanup solved the issue.

**Comment by atommaki** [comment]
It is good it is not an issue in this project, but it will come back time to time as it did already. I don't know what to report and where to have a real fix for this. :/

**Comment by IsmaelMartinez** [comment]
is one of those that keeps appearing every now an then. We normally pin those sort of issues but we only got 3 pins and those are issues that repeat more often :)
