### ISSUE TITLE
Video hardware acceleration on Linux (on Intel Comet Lake)

### ISSUE THREAD

**Issue by donjan** [IsmaelMartinez/teams-for-linux#1246]
**Describe the bug**
Running a meeting with a moderate amount of participants (4-6) causes full CPU usage on a Intel-based laptop, which gets busy with video encoding/decoding. This dramatically slows down any other operations and drains the battery. Additionally encoding a shared screen causes further slowdowns: typing in an IDE comes to a crawl of one character every two to three seconds.
Screensharing on Intel hardware is a painful experience.

**To Reproduce**
1. Start a meeting with 3+ participants
2. Share the screen or window of an IDE (e.g. VSCode with Pylance running)
3. Type some code into the IDE, do some simple copy&paste
4. Observe UI reaction speed

**Expected behavior**
The screenshared meeting should not put the system into a crawl.

**Screenshots**
The hardware & OS supports hardware encoding/decoding, as shown in chromium-browser:
![Screenshot from 2024-05-03 16-33-04](https://github.com/IsmaelMartinez/teams-for-linux/assets/1126467/fc6b7f49-93bc-4ce8-877b-24913677d218)

**Laptop**
 - OS: Ubuntu 22.04.4 LTS, Xorg session
 - Installation package: from this project's apt repo
 - Version: 1.4.35
 - Hardware: Thinkpad X1C 8th, Core i7-10510U Comet Lake (with Quickysnc supporting VP8, VP9, H.264 and HEVC in mpv)

**Additional context**
`intel_gpu_top` shows the GPU being used for rendering by X, but nothing on Video.
`htop` shows high percentages across all cores being used for teams alongside VSCode. Only these two open cause a load of 3+ even after letting them "settle" for a minute.

`renice -n 19 -p $(pidof teams-for-linux)` doesn't noticeably improve the experience.

VSCode without Teams behaves fast enough (for a heavy Electron app...)

Chromium has been supporting [hardware acceleration](https://discourse.ubuntu.com/t/chromium-hardware-accelerated-build-for-intel-based-platforms-available-for-beta-testing/35625) for a year now. Either by default or forcing it with
`chromium-browser --ignore-gpu-blocklist --enable-features=VaapiVideoDecoder,VaapiVideoEncoder,VaapiVideoDecodeLinuxGL,VaapiIgnoreDriverChecks`

Launching `teams-for-linux` with the same arguments doesn't help. Assuming it's not based on a modern Chromium version, could this still be ported?

**Comment by jijojosephk** [comment]
You must look for GPU related `chromium` flags. You can pass it to this app as well. 

Like
`teams-for-linux --<chrome-flag>` 

You'd probably need a bit of research on that front on `chromium` forums or documentations.

**Comment by IsmaelMartinez** [comment]
Hi, thanks for reporting. Could you update the template with some logs? The template has explanations on it, but is basically this:

```bash
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
```

We are currently based on electron 29.3.0. 

The chromium versions are in this image (with the nodejs also there) 
<img width="1272" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/b87090f4-a517-4390-a584-e910ec30bb40">
Link https://releases.electronjs.org/

VSCode will probably be a few versions behind in electron. But if you check your version in this line https://github.com/microsoft/vscode/blob/main/package.json#L151 .

A few things to check:

* We got a few config options (more like feature flags) that might be worth checking here https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config . Check things like the disableGpu, isCustomBackgroundEnabled, etc. 
* Report it in VSCode https://github.com/microsoft/vscode/ and maybe MS ends up indirectly contributing. 

It could also be a MS thing specially if you are using MS Teams v2, but hopefully the previous list will help. I do suspect the config options.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity

**Comment by donjan** [comment]
Bug still persists: do you want to reopen or shall I make a new one? (either way, I won't be able to show frequent activity)

Here's a log from launching, joining a meeting without other participants and sharing the screen:
```
$ /opt/teams-for-linux/teams-for-linux --webDebug --appLogLevels=error,info,warn,deb --disableGpu
[DEBUG] configPath:,/home/donjan/.config/teams-for-linux
[WARN] No config file found, using default values
[DEBUG] configFile:,[object Object]
[INFO] Disabling GPU support...
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--webDebug,--appLogLevels=error,info,warn,debug,--disableGpu
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
[DEBUG] Spellchecker is disabled!
[DEBUG] Network test successful with method https
[1146060:0625/163537.972234:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 1s, IdleState: 'active'
[1146060:0625/163537.975252:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] Badge count set to '0'
[DEBUG] Badge count set to '0'
[DEBUG] Badge count set to '0'
[1146060:0625/163547.658859:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] did-frame-finish-load,[object Object],false
[DEBUG] Badge count set to '0'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] Badge count set to '0'
[1146060:0625/163555.072735:ERROR:CONSOLE(1)] "Request Target.setAutoAttach failed. {"code":-32601,"message":"'Target.setAutoAttach' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[1146060:0625/163555.206069:ERROR:CONSOLE(1)] "Request Target.setAutoAttach failed. {"code":-32601,"message":"'Target.setAutoAttach' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
```

Since my first post, I've tested with teams-for-linux 1.6.1 and with the current version:
```
$ /opt/teams-for-linux/teams-for-linux --version
1.7.4
```
My installed VSCode uses this (but why do we care about VSCode's Electron?):
```
$ grep electron /usr/share/code/resources/app/package.json
    ...
    "electron": "29.4.0",
```

The observed performance (CPU graph, `intel_power_top`) is the same with or without the `--disableGpu` flag.
`--isCustomBackgroundEnabled` helps a bit insofar the CPU doesn't have to calculate the blurring (which I prefer on), but it's not a significant improvement.
Running with:
```$ /opt/teams-for-linux/teams-for-linux --webDebug --appLogLevels=error,info,warn,debug --ignore-gpu-blocklist --enable-features=VaapiVideoDecoder,VaapiVideoEncoder,VaapiVideoDecodeLinuxGL,VaapiIgnoreDriverChecks```
doesn't produce any additional entries in the log, so I'm not sure the arguments get consumed. Still no difference in performance.

Not sure reporting issues from this fork to MS makes sense? I could give the PWA a shot (haven't managed to get audio to work properly on that, though).
Teams v2 is that button which gives the slightly revamped UI, right? I clicked that once it popped up.

@jijojosephk the flags in the OP are what I came up with for GPU-related Chromium flags. Primarily from https://peter.sh/experiments/chromium-command-line-switches/ and various forums. If I have missed something, insight is welcome!
