### ISSUE TITLE
Custom Backgrounds in v2 still not working with 1.4.37

### ISSUE THREAD

**Issue by derekatkins** [IsmaelMartinez/teams-for-linux#1248]
**Describe the bug**
Short issue:  my custom background (and thumbnail) are both black.  NOTE:  I am using jpg, not png.. Is that a problem? 

I am running with `teams-for-linux --customBGServiceBaseUrl=https://my.host.name/my_base_url --isCustomBackgroundEnabled=true --webDebug=true` and the system starts up..  But it does not appear to be reaching out to my.host.name to pull the config.json.  It DID reach out ONCE, but didn't do it again even after I changed the config.json.  So it must be caching the data.

Also, I do see an error in the debug log that implies something is not being overridden:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2531900/69f60258-ad34-46d4-a1bf-3c75ca9b22e6)

And another error that seems to imply that SOME URL is not being overridden properly because it is pulling my thumb from statics.teams.cdn instead of my base url:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2531900/46f8c5d0-b22e-4a76-8809-3c5eb0049a4e)

**To Reproduce**
1. Run the application
2. Trying to join a meeting
3. Try to set the backgroun

**Expected behavior**
I would expect Teams to try to read my config.json on every startup, or at least attempt to see if it changed.  And I would expect the graphics to show.

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2531900/39c6a80d-e778-4a83-8540-e1324b5b054e)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Installation package RPM
 - Version teams-for-linux-1.4.37-1.x86_64

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
```

**Additional context**

**Comment by RolandRosenfeld** [comment]
For me 1.4.37 works with custom background, when I start 
```
teams-for-linux --customBGServiceBaseUrl=https://my-server/baseurl --isCustomBackgroundEnabled=true --appLogLevels error,warn,info,debug
```
In the debug output I see the following relevant messages:
```
[DEBUG] Fetching custom background configuration from 'https://my-server/baseurl/config.json'
[DEBUG] Custom background service url is 'https://my-server/baseurl'
[...]
[DEBUG] Custom background service remote configuration stored at '/home/username/.config/teams-for-linux/custom_bg_remote.json'
[...]
[DEBUG] Forwarding 'https://statics.teams.cdn.office.net/evergreen-assets/backgroundimages/myimage.jpg' to 'https://my-server/baseurl/myinage.jpg'
```
The file /home/username/.config/teams-for-linux/custom_bg_remote.json is a stripped down (one-line) version of config.json.

Did you make sure, that your web server adds an "Access-Control-Allow-Origin: *" header to all responses? You can check this with
```
curl -I https://my-server/baseurl/config.json
```

**Comment by derekatkins** [comment]
Yes, I fixed the server to add that header (it was working just fine with teams v1).
```
curl -I https://my-server/baseurl/config.json
```
returns:
```
HTTP/1.1 200 OK
Date: Sat, 04 May 2024 17:11:36 GMT
Server: Apache/2.4.41 (Fedora) OpenSSL/1.1.1d mod_perl/2.0.11 Perl/v5.28.2
Last-Modified: Sat, 04 May 2024 13:58:53 GMT
ETag: "de-617a13c8aeeb4"
Accept-Ranges: bytes
Content-Length: 222
Access-Control-Allow-Origin: *
Content-Type: application/json
```

I think it DOES cache the config.json, because this time it DID pull it down (and it had done it about 30m before my testing for this bug report).  HOWEVER, while it is pulling down the config.json correctly from my site, it does NOT pull down the images from my site.  And indeed the webDebug still shows me that it is trying to GET from https://statics.teams.cdn.office.net:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2531900/62967db8-9869-46e1-b79d-4fa0fbea60ac)

My config.json reads:
```
{
    "videoBackgroundImages": [
	{
		"filetype": "jpg",
		"id": "Veridify_Office_F_2405",
		"name": "Veridify Office F 2024-05",
		"src": "/veridify_office_f.jpg",
		"thumb_src": "/veridify_office_f_thumb.jpg"
	}
    ]
}
```
So it is pulling the correct file name from the config, but it is not pulling the image from the custom URL location.

**Comment by RolandRosenfeld** [comment]
Now I see your fault: You have to prefix the src and thumb_src values with /evergreen-assets/backgroundimages
So this should be:
```json
{
        "videoBackgroundImages": [
                {
                        "filetype": "jpg",
                        "id": "Custom_bg01",
                        "name": "Veridify Office F 2024-05",
                        "src": "/evergreen-assets/backgroundimages/veridify_office_f.jpg",
                        "thumb_src": "/evergreen-assets/backgroundimages/veridify_office_f_thumb.jpg"
                }
        ]
}
```
I'm not sure, whether a custom "id" field is allowed, so I used Custom_bg01 (counting up) there.

**Comment by derekatkins** [comment]
> Now I see your fault: You have to prefix the src and thumb_src values with /evergreen-assets/backgroundimages 

Ahh.. This was not at all clear from the documentation.  I would recommend that this be explicitly stated, that the src and thumb_src MUST START with the explicit, static string `/evergreen-assets/backgroundimages', and everything after that is based on the custom URL.

Once I fixed that, it definitely made it further.  I DO see this in my webDebug:
```
[Report Only] Refused to load the image 'https://my.server.name/veridify_office_f_thumb.jpg' because it violates the following Content Security Policy directive: "img-src 'self' blob: data: *.asm.skype.com *.asyncgw.teams.microsoft.com *.office.net *.giphy.com *.officeapps.live.com *.sharepoint-df.com *.sharepoint.com https://statics.teams.cdn.office.net bot-framework.azureedge.net connectoricons-prod.azureedge.net content.powerapps.com docs.botframework.com i.vimeocdn.com i.ytimg.com local.teams.office.com:* marketplacecdn.azureedge.net media.licdn.com outlook.office.com pbs.twimg.com raw.githubusercontent.com skypeteamsbotstorage.blob.core.windows.net statics.teams.microsoft.com substrate.office.com teams.microsoft.com urlp.sfbassets.com".
```
However the image preview appears to be working properly.

It may be unrelated, but the next line in the webDebug says:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2531900/d07ca29c-53d9-427b-b29e-9d03bfbe0523)

**Comment by DerXteMensch** [comment]
I also have problems to get it working with Teams v2, using 1.4.37

The json looks like this:

`{
	"videoBackgroundImages": [
		{
			"filetype": "jpg",
			"id": "Teamshintergrund",
			"name": "Teamshintergrund",
			"src": "/evergreen-assets/backgroundimages/Teamshintergrund.jpg",
			"thumb_src": "/evergreen-assets/backgroundimages/Teamshintergrund_thumb.jpg>"
		}
	]
}`

I start teams with 

`teams-for-linux --isCustomBackgroundEnabled=true --optInTeamsV2=true --customBGServiceBaseUrl=http://localhost --appLogLevels error,warn,info,debug`

In the debug output I get:

`[DEBUG] Fetching custom background configuration from 'http://localhost/config.json'
[DEBUG] Custom background service url is 'http://localhost'
...
[ERROR] Fetched custom background remote configuration but failed to save at '/home/malte/.config/teams-for-linux/custom_bg_remote.json'. Unexpected non-whitespace character after JSON at position 168 (line 10 column 1)
[DEBUG] Forwarding 'https://statics.teams.cdn.office.net/evergreen-assets/backgroundimages/config.json?v=6' to 'http://localhost/config.json?v=6'
`

**Comment by RolandRosenfeld** [comment]
I tried out your setup and it works for me (after removing the ">" at the end of thumb_src. But also with this typo, it works for me, only the thumbnail of the background is broken (black), but the background itself does work as expected.

I cannot reproduce the "failed to save" error with your config.json (with and without the ">").  So there may be some invisible character in your config.json, that wasn't copied here.

Did you make sure, that your webserver adds the "Access-Control-Allow-Origin: *" header?

**Comment by DerXteMensch** [comment]
Yes, that header is added.

I removed the whole folder .config/teams-for-linux. Then started teams-for-linux again. And now it works! Don't know what was the problem, but probably some old configuration...
