### ISSUE TITLE
Snap unresponsive on Fedora

### ISSUE THREAD

**Issue by thebigtoona** [IsmaelMartinez/teams-for-linux#125]
**Describe the bug**
Snap package is not responsive on Fedora 30.  On start the application launches but the user is unable to click or type into inputs in the windows.  The user also cannot exit the application and must kill the process or exit with the terminal if launched with the terminal.

**To Reproduce**
1. build the snap with the dockerfile 
2. install the snap  
3. launch the snap from the terminal 
4. attempt to type, click, or exit the program 

**Expected behavior**
ability to type and click on buttons  

**Desktop (please complete the following information):**
 - OS: Fedora 30 
 - snap 
 - 0.2.1

**Comment by IsmaelMartinez** [comment]
Hi @thebigtoona ,

Thanks for reporting this and apologies.

Can you try either the one released to the snapcraft store or the one in the release folder?

https://snapcraft.io/teams-for-linux/releases
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.2.0

The release snap is build with electron-builder so that docker container might be missing some stuff. @benyanke or @julian-alarcon , can you have a look?

**Comment by shoffmeister** [comment]
I can confirm the Fedora issues on Fedora 30, with KDE desktop.

**Comment by IsmaelMartinez** [comment]
@shoffmeister , can you confirm the packaged snaps? Also, can you use other package (rpm) and see if that still the case?

**Comment by thebigtoona** [comment]
Yes @IsmaelMartinez I'll give the snapcraft release a try now.  Also I tried it on both Deepin and Gnome desktop environments before I reported the bug

**Comment by shoffmeister** [comment]
RPM works fine (on my one and only attempt) on Fedora 30 / KDE - I honestly do not remember why I went AppImage / snap.

With respect to the snap, "back then" I went to the edge release a couple of days ago - this would have been the one and only release on the snap store?

I prefer to be on a package coming from a repository, so by that account, snap from the snapstore would be really nice. (And an rpm from a repo server would be even better - rpmfusion?)

**Comment by shoffmeister** [comment]
Let me try to be more explicit about versions:
AppImage == rpm == the 0.2.0 release from releases
snap == whatever was on the snapstore 2-3 days ago, on edge

**Comment by thebigtoona** [comment]
@IsmaelMartinez  I attempted to use the snap for 0.2.0 in the releases, as I could not locate the one in the snapcraft store.  It was also unresponsive on Fedora 30. I will attempt the RPM next and tell you if this is working

**Comment by IsmaelMartinez** [comment]
@shoffmeister , feel free to investigate the rpmfusion. I, honestly, don't have time currently to look into that (also use ubuntu at the moment...) 

@thebigtoona , I hope the rpm does work for you. The snap still a WIP. It should be fairly stable but not even me can use it... so I depend on @julian-alarcon and @benyanke on that area.

The edge channel in the snap store matches the development branch in this repo. 
The stable channel, will match the master branch... but as you gather from this comment still in process.

**Comment by thebigtoona** [comment]
I haven't been able to try it out yet but I will when I get the chance and
let you know how it goes. I'll do some research on it if I get the time. It
could be dependency related too maybe which might explain it being a Fedora
related issue.

Also, probably a separate issue but a colleague of mine running Ubuntu got
the snap working but couldn't screen share just as a heads up.

**Comment by julian-alarcon** [comment]
Hi @thebigtoona can you try again the last build in the edge channel of the snap store? I added some changes related with Wayland. I know that Fedora uses Wayland by default so maybe thos could work.

Also, can you run the teams-for-linux client from console and see if you get any message?

BTW, normally on edge channel I remove the snap, remove the snap path (~/snap/teams-for-linux) and then reinstall it.

**Comment by IsmaelMartinez** [comment]
Any updates on this? Otherwise we can assume that this is solved/close

**Comment by thebigtoona** [comment]
I haven't been able to test again

**Comment by IsmaelMartinez** [comment]
No problem. I will keep it open but might close it for inactivity ina few weeks just to keep things tidy. Just comment back and I will reopen.

**Comment by IsmaelMartinez** [comment]
I will close this to keep things tidy. Do please comment if is not solved and I will reopen. Thanks!
