### ISSUE TITLE
No notification badgets in KDE 6 

### ISSUE THREAD

**Issue by javiergarber** [IsmaelMartinez/teams-for-linux#1254]
**Describe the bug**
No notification badgets on KDE Plasma 6.0.4
I don't know if this is exactly a bug o needs finer configuration for plasma.

**To Reproduce**
Receive a message or any other kind of notification

**Expected behavior**
A sound is reproduced, the tray icon includes a number with the number of notification, a new badget is added to the KDE notification system. 
The notification badget is not created, resulting in difficult to track new messages

**Desktop :**
 - OS: KDE neon 6.0
 - Flatpak installation
 - Version 1.4.37

**Comment by jijojosephk** [comment]
I'm not familiar with `Plasma` but is it something that you can find in the bottom panel? hide or show icon something like that?

**Comment by javiergarber** [comment]
No, that works good so far, as shown in the image
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/45274337/763fe14e-b491-4d25-9be2-e43faa94fc8f)
but they are not show as over screen badgets, neither in the "Notification history", something similar to this one 
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/45274337/6e916c83-cd70-4f36-87e8-caf8cd62293b)

**Comment by jijojosephk** [comment]
Since you're using flatpak, I'm not sure how can you revert an older version and test. If you can try [1.4.32](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.32) `deb` and let us know if that works.

**Comment by javiergarber** [comment]
Hi, as i couldn't find version 1.4.32 as flatpak, I downgraded to 1.4.30 (as I guessed that you were trying to ensure that the 1.4.33 update didn't break the notifications system, right?) , and seems that the error exists in that version too. Seems that kde desktop notifications are not integrated in the app.

**Comment by IsmaelMartinez** [comment]
can you try the `deb` version? it could be some flatpak permissions/configuration playing around. Or just a problem between electron and KDE

**Comment by javiergarber** [comment]
Just tried the `deb` version and seems to work properly now. I think that the flatpak version needs some more work to configure (probably from my side), but using the deb one is just straight forward. Ty very much @IsmaelMartinez

**Comment by IsmaelMartinez** [comment]
I will then close it and tag it as "workaround provided". Snap and flatpak can be a bit of a pain.
