### ISSUE TITLE
Tabs maybe possible?

### ISSUE THREAD

**Issue by Gunstick** [IsmaelMartinez/teams-for-linux#1256]
I am referring to #973 
in the browser (firefox) the right button menu on a teams tab shows "open in new window"
whereas in the teams-for-linux app it shows "go to website" and "open in desktop app".

So somehow microsoft's knows that it's not a real browser?
Can maybe one of the two be catched to open another browser tab or window? Or have a way to open a second window for the same tenant (ctrl-T / ctrl-N)? Example use is to have a window/tab with the chat and another with the planner.

**Comment by jijojosephk** [comment]
@Gunstick  if you're referring to #973, sadly we can't do. otherwise, please use issue template and provide more details.

**Comment by jijojosephk** [comment]
Kindly respond otherwise, we may close it in a few days.

**Comment by IsmaelMartinez** [comment]
Hi @Gunstick , I don't believe is possible with the current implementation. IF we wanted to allow tabs, we will need to re-implement the whole application. While that might be something we explore in the future, it is not something we are going to be looking at the moment, but thanks for sharing your learning! I close it to keep things tidy.
