### ISSUE TITLE
AppImage of 0.2.0 occasionally hangs on startup.

### ISSUE THREAD

**Issue by shoffmeister** [IsmaelMartinez/teams-for-linux#126]
The AppImage of 0.2.0 very occasionally hangs on startup, with this lovely blueish background screen that Teams has.

Note that my account on Microsoft Teams is protected by mandatory two-factor authentication (I have no idea whether this applies to all Teams accounts). My second factor is Microsoft Authenticator on Android, where I typically respond within a second or two to the authentication request. The hang takes place _after_ I successfully confirmed with the second factor.

If the process hangs, terminating the process and simply restarting the AppImage will ask for the second factor again, will then proceed to success.

After that, it seems to be very smooth sailing.

Steps:
* download 0.2.0 AppImage; chmod u+x
* start AppImage
* enter credentials (email, password) for account on Microsoft Teams
* get asked for authentication for second factor (on Microsoft Authenticator on Android)
* successfully approve with second factor
* AppImage hangs

Terminating the AppImage and starting again so far seems to always have succeed so far (with the exact same steps after startup - credentials, 2FA)

**Comment by IsmaelMartinez** [comment]
I have seen a similar situation before. I think is related to redirects not reaching the app, but is pretty tricky to debug as it doesn't happen all the time.

I suggest using the refresh (Ctrl+R) as does get over the issue. Apologies for the dirty workaround but is a pretty sporadic issue normally only after 1st install (or cleaning the cache)

**Comment by shoffmeister** [comment]
FWIW, this happens to me almost every day.

**Comment by IsmaelMartinez** [comment]
Strange, it might be related to the MFA screen. I can't test that unfortunately. Those the Ctrl+R work for you? Does it happen only on 1st login?
