### ISSUE TITLE
Provide way of disabling the automatic volume adjustment

### ISSUE THREAD

**Issue by lunarwtr** [IsmaelMartinez/teams-for-linux#1263]
Teams is notorious for trying to auto adjust the microphone.  The teams client has a toggle to turn this off but it seems to be missing from web version.   I believe chromium has a experimental flag that might assist with this, but I am unsure how to set for the electron app.

chrome://flags/#enable-webrtc-allow-input-volume-adjustment

**Comment by IsmaelMartinez** [comment]
Check the config section. You can pass an array of flags to the app, or you can just use them from the command line.

**Comment by dicamarques14** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md
There's support for that in here: disableAutogain

Just create a config according to the install type you have

**Comment by IsmaelMartinez** [comment]
Thanks @dicamarques14. I think is slightly different request, but give it a try @lunarwtr and see if it works for you (and report back please). Thanks!

**Comment by IsmaelMartinez** [comment]
Hi @lunarwtr , I will close this issue as I don't think we can help much. Electron doesn't allow doing much around sound and that flag is not currently available. 

I would suggest to check that is not your system audio settings that are playing with you. I used to get really annoying as my audio settings were auto adjusted in Ubuntu. 

Do please let us know if the disableAutogain did something to you. It might just be what you need. 

Also, we appreciate (I am tempted to make it mandatory) to use the templates to fill feature requests or bugs. It does save us a lot of time going back and forwards with issues.

**Comment by IsmaelMartinez** [comment]
Actually, something to try (using --webDebug) is to see if the https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/autoGainControl does anything. If MS is following the standards, then it should just work. Chances are they aren't, but if that works we can add it as an option.

**Comment by lunarwtr** [comment]
Sorry for late reply.  I could not find an electron flag that matches the particular chromium one I mentioned in description.  But I will see about testing the two Auto Gain properties you mentioned.

**Comment by gorillapower** [comment]
Im also experiencing the same issue, I believe disabling the autogain as mentioned has solved my issue. I will confirm.

**Comment by IsmaelMartinez** [comment]
closing as workaround provided (or at least it should work). Do report back if that is not working and we can re-open the issue

**Comment by dim-geo** [comment]
Hello, tried `--disableAutogain true` with both teamsv1 and v2 but without any improvement

**Comment by IsmaelMartinez** [comment]
Sorry to hear, unfortunately this is blocked by electron. I would suggest you request that flag feature to be supported on their side. Otherwise trying that autogain mention I put on the comment https://github.com/IsmaelMartinez/teams-for-linux/issues/1263#issuecomment-2136648972 it "might" work, but I do not have much hope on Microsoft and Google both following those standards.

**Comment by DevBey** [comment]
this is real deal breaker, we can easily turn this off in pwa chrome. otherwise my mic volume is all over the place

**Comment by jijojosephk** [comment]
There is a flag disableAutogain turn that off. Please read the config section of read me.

**Comment by jijojosephk** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/blob/main/app%2Fconfig%2FREADME.md

**Comment by DevBey** [comment]
apologies yes this works thanks @jijojosephk

**Comment by jijojosephk** [comment]
@DevBey Glad to know it works. I hope you're using `config.json`

```json
{
"disableAutogain": true
}
```
should do.

**Comment by DevBey** [comment]
yes that's correct inside snaps, works great !!

**Comment by devloberto** [comment]
I'm using the appimage and I was facing the same issue. This config fixed it:

![Image](https://github.com/user-attachments/assets/cd5d1a90-010a-4d6e-9c2b-cd5887acb757)

![Image](https://github.com/user-attachments/assets/4c1dcd60-08d8-4775-8e30-db66db4fd545)

some info about my system:
```
Operating System: TUXEDO OS 
KDE Plasma Version: 6.3.2
KDE Frameworks Version: 6.11.0
Qt Version: 6.8.2
Kernel Version: 6.11.0-107009-tuxedo (64-bit)
Graphics Platform: X11
Processors: 12 × 13th Gen Intel® Core™ i7-1355U
Memory: 31.0 GiB of RAM
Graphics Processor: Intel® Iris® Xe Graphics
Manufacturer: LENOVO
Product Name: 21HD004RGE
System Version: ThinkPad T14 Gen 4
```

**Comment by devloberto** [comment]
FYI I also tested the config using the flatpak version and it works as well 🙂 

```bash
flatpak install flathub com.github.IsmaelMartinez.teams_for_linux
# installation

flatpak list | grep teams
# Portal for Teams        com.github.IsmaelMartinez.teams_for_linux       1.12.7  stable  flathub system
```

I just created a symlink pointing from
```
~/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux/config.json

```
to
```
.config/teams-for-linux/config.json
```
