### ISSUE TITLE
Screen share does not work on  Fedora 39

### ISSUE THREAD

**Issue by tibz7** [IsmaelMartinez/teams-for-linux#1265]
**Describe the bug**
The screen share does not work on fedora 39 ( KDE/Wayland). 

**To Reproduce**
1. Start a screen share
2. Screen shared is said to be working on both clients
3. the shared screen is not shown to the client

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - Installation package: snap or flatpak
 - Version: 1.4.37

**Debug**
9: Could not create a backing OpenGL context.
ERR: Display.cpp:1052 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[381071:0521/090450.937900:ERROR:gl_display.cc(515)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[381071:0521/090450.937957:ERROR:gl_display.cc(786)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[381071:0521/090450.938013:ERROR:gl_display.cc(820)] Initialization of all EGL display types failed.
[381071:0521/090450.938061:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.
[381071:0521/090450.939974:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
MESA-LOADER: failed to open iris (search paths /snap/teams-for-linux/584/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: iris
MESA-LOADER: failed to open kms_swrast (search paths /snap/teams-for-linux/584/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /snap/teams-for-linux/584/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load swrast driver

```bash
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
```

**Additional context**

**Comment by IsmaelMartinez** [comment]
snap and flatpak can be a pain and other users have reported problems with screenshare using either (example https://github.com/IsmaelMartinez/teams-for-linux/issues/1184 )

Those are normally local configuration complexities. Can you try with rpm form https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.37 ? If that works, then we know is some configuration at your side.

**Comment by IsmaelMartinez** [comment]
closing due inactivity. Happy to re-open if more info provided (after trying rpm package)
