### ISSUE TITLE
AppImage of 0.2.0 does not terminate cleanly, ever

### ISSUE THREAD

**Issue by shoffmeister** [IsmaelMartinez/teams-for-linux#127]
The AppImage of 0.2.0 does not terminate cleanly, ever, hangs dead on shutdown.

This was on Fedora 29 and KDE, but also applies to Fedora 30 and KDE.

Steps:
* download AppImage
* open terminal in location where AppImage is located
* chmod u+x
* ./<the>.AppImage <- launch the AppImage from the terminal
* (proceed to successfully use the AppImage)
* click on "X" button in upper right corner of (main) window
//exp: AppImage terminates cleanly, terminal prompt reappear
//act: AppImage never terminates cleanly; terminal is blocked for entry by the AppImage

At this stage, note that process resources still linger (ps -ef from other console)

* Press Ctrl-C on terminal where AppImage hangs on shutdown
-> AppImage processes terminate, resources get cleaned up
-> terminal becomes unblocked for entry

I am using a terminal above, because that makes the effect much more observable; it seems to happen, too, if / when integration with the desktop environment is used (launch through KDE app launcher / menu)

**Comment by shoffmeister** [comment]
FWIW, I understand that this is an Electron app, with community effort going into (re)packaging online Microsoft resources.

I have been and am successfully using Microsoft Visual Code on the exact same system, with any of these symptoms. Microsoft Visual Code is also an Electron app.

**Comment by IsmaelMartinez** [comment]
Hi,

The app does what is intended, but I suspect you don't have a tray bar (or it doesn't show in it).

You can change the behavior of the close button by using the config argument (--closeAppOnCross=true)

https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config

You can either pass it as an argument or create a config file in `~/.config/teams-for-linux/config.json` . This might be different for appimage's

Hope helps,

**Comment by IsmaelMartinez** [comment]
marking it as "not an issue" as is pretty specific on not having a tray. 

We "minimize" the app on close as to follow the same as happens in Windows and Mac. Agree, it might have been better to "close" on the cross, but inverting that change will probably bombard this with negative comments. I consider having the config option been enough. 

Hope helps!
