### ISSUE TITLE
1.5.0: generic window icon instead of Teams application icon shown in taskbar and Alt-Tab task switcher window

### ISSUE THREAD

**Issue by z1atk0** [IsmaelMartinez/teams-for-linux#1279]
**Describe the bug**
As of 1.5.0, the usual Teams application icon is no longer shown in the taskbar and in the `Alt-Tab` application switcher. Instead, the generic Adwaita window icon is shown. Going back to 1.4.37, the usual Teams icon is shown again. This happens with both the linux-x64_64 tarball install and the AppImage. The _systray_ icon is _not_ affected, it shows the normal Teams icon as usual.

I'm running GNOME 46.2 with a GNOME-flashback session.

**To Reproduce**
1. upgrade from 1.4.x to 1.5.0
2. look at the taskbar icon, or the icon shown in the `Alt-Tab` app switcher window
3. scratch your head wondering where the Teams icon has gone :wink: 

**Expected behavior**
I would expect the normal Teams icon to be shown as usual.

**Screenshots**
Taskbar with 1.5.0:
![Screenshot from 2024-05-30 13-03-52](https://github.com/IsmaelMartinez/teams-for-linux/assets/12568948/3002370f-e126-4516-b11b-dcc8394d68de)
Taskbar with 1.4.x:
![Screenshot from 2024-05-30 13-05-43](https://github.com/IsmaelMartinez/teams-for-linux/assets/12568948/f8640d18-af1e-449d-9ccb-1480241012fc)

**Desktop (please complete the following information):**
 - OS: Slackware64-15.0
 - Installation package: tar.gz, AppImage
 - Version: 1.5.0

If you need any further information please let me know.

Thanks for listening,
Thomas

**Comment by IsmaelMartinez** [comment]
This is strange. Can you check if cleaning the cache solves this? This normally can happen when we increase the electron version, but we haven't done that for longer than those versions.

**Comment by z1atk0** [comment]
Ie. quit my running Teams session, then `rm -rf ~/.config/teams-for-linux/*Cache*`, then start Teams again? Or is there any other cache I should clean instead or in addition? Will try this after work today, currently I "need" :roll_eyes: my Teams running. :wink:

**Comment by IsmaelMartinez** [comment]
I would remove the whole `~/.config/teams-for-linux/` folder, just to make sure, but you can also do "right click" on the menu and do `Quit (Clear Storage)` if you only want to clean the cache. 

The location might be different for AppImage as it is with other packaging systems https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#config-folder-locations

**Comment by z1atk0** [comment]
`[x] done` that (removed the whole `~/.config/teams-for-linux/`, didn't find any menu to click on that would allow me to quit (I always hit `Ctrl-Q`)), but that didn't change anything ... well, except for asking for my login credentials again. :wink: Still, only the Adwaita default window icon is shown in the taskbar instead of the Teams icon.

Anything else that I could try? :thinking:

**Comment by harridu** [comment]
metoo. Using fvwm3 it shows only the default icon.

**Comment by IsmaelMartinez** [comment]
The changes that are between those versions are in here: https://github.com/IsmaelMartinez/teams-for-linux/compare/v1.4.37...v1.5.0 

Can you try [1.4.40](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.40) I think is related to the `Adding the config option trayIconEnabled that defaults to true` 

I think the https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L73 depends on the https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L571 iconChooser. That basically will always be undefined.

I might see if I can fix this bug later tonight, but I might not have the time. Thanks for reporting!

**Comment by z1atk0** [comment]
1.4.40 also works fine for me, the Teams application icon is shown properly just as in 1.4.37.

**Comment by RolandRosenfeld** [comment]
I also observed a change with 1.5.0.
The icon worked as expected with 
`teams-for-linux --appIcon=$HOME/icons/teams48x48.png`
before.
Since 1.5.0 my fvwm shows the default icon.
But the following entry in fvwm config solves this for me:
`Style "teams-for-linux" Icon teams48x48.png`
(my icon-path in fvwm is $HOME/icons, so no other path is needed).

**Comment by z1atk0** [comment]
For me, the `--appIcon` option only affects the _systray_ icon (which still works fine in 1.5.x anyway), not the _taskbar_ and _app switcher_ icons. This is true for both 1.4.x and 1.5.x.

**Comment by IsmaelMartinez** [comment]
Fix released under https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.6.1

**Comment by z1atk0** [comment]
I'd just like to
1. confirm that 1.6.1 fixes the problem for me on both Slackware64-15.0 (tarball install) and FC39 (AppImage install), and
2. thank you for the quick fix! :slightly_smiling_face:

**Comment by harridu** [comment]
The icons are back. Thank you. I highly appreciate your work for this project.
