### ISSUE TITLE
Add packaging type info to user interface

### ISSUE THREAD

**Issue by shoffmeister** [IsmaelMartinez/teams-for-linux#128]
It would be really nice if there was a way in the UI of the application to cleanly identify the exact version of the packaging and the type of packaging (snap, appimage) that is running.

I appreciate that this might require patching Microsoft resources; I have no idea how administratively and technically difficult this would be.

**Comment by IsmaelMartinez** [comment]
Hi,

You can see the package version number by clicking "Alt". That shows the menu (that we hide as normally don't really need to be seen). Alternatively, you can also run `teams-for-linux --version`

Knowing the type of package might sound easier than what it is... so doesn't really have much priority on my limited time. 

Feel free to explore that part (package type). Maybe change this issue title to be the package type instead.

Contributions are more than welcome. Thanks!

**Comment by IsmaelMartinez** [comment]
An option might be modifying electron builder to create a file for each package type is creating. The downside will be that other package systems like arch and flatpack will not know about it as they don't build with electron builder.

**Comment by IsmaelMartinez** [comment]
This is far too complex for the limited time I got. Closing as, even if it might be nice to have, I don't have the time (nor seems like people are that bother)
