### ISSUE TITLE
Teams v2 meeting links are always sent to an external brower rather than captured

### ISSUE THREAD

**Issue by pablob127** [IsmaelMartinez/teams-for-linux#1289]
Teams for Linux used to (somehow) process links to join meetings so that the meeting will run inside the app.
Since the the change to Teams v2 (or at least it feels like), links to join meetings always open in an external browser, and I have not been able to find a way to join a meeting in the app.

**To Reproduce**
1. Enter a link in a chat of the form: [https://teams.microsoft.com/l/meetup-join/19%3ameeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting), the old Teams style.
2. When you click on the link, nothing happens (maybe because the link is not correct?)
3. The debug output says: `[DEBUG] DEBUG - captured meetup-join url`
4. Enter instead a new-style link: [https://teams.microsoft.com/v2/?meetingjoin=true#/l/meetup-join/19:ameeting](https://teams.microsoft.com/v2/?meetingjoin=true#/l/meetup-join/19:ameeting)
5. When you click on the link, it always opens it in an external browser.
6. The debug output now says `[DEBUG] Requesting to open 'https://teams.microsoft.com/v2/?meetingjoin=true#/l/meetup-join/19`

**Expected behavior**
When clicking on a new-style meeting join link, I would expect the "meetingjoin" URL to be captured so it is opened inside the app, not in an external browser.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux v12
 - Installed from the repository at repo.teamsforlinux.de
 - Version 1.5.1

**Comment by pablob127** [comment]
Note that this breaks the workaround discussed in #675 (that I used to use).

**Comment by IsmaelMartinez** [comment]
If you paste that link into a channel and click from it, does it work?

**Comment by pablob127** [comment]
No, if I paste the link into a channel, and then click it is also opened straight into the external browser. The debug log says `[DEBUG] Requesting to open 'https://teams.microsoft.com/v2/?meetingjoin=true#/l/meetup-join/19'`

**Comment by IsmaelMartinez** [comment]
Seems like they have changed the URL again, so the regex will need updating.

**Comment by IsmaelMartinez** [comment]
I think is this regex https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L209

**Comment by pablob127** [comment]
> If you start teams passing the meeting link as the URL, it should open the meeting.
> 
> `teams-for-linux --url="https://teams.microsoft.com/v2/?meetingjoin=true#/l/meetup-join/19"` (or something like that)

That does seem to work. The UI got a bit confused when I cancelled my joining (after all the meeting link was old).
It did not work to do that if teams-for-linux was already running, though.
I agree with you, it seems the same regex should be applied in both places.

**Comment by IsmaelMartinez** [comment]
Can you check the [pre-release 1.7.1](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.7.1)? It should be able to handle the regEx a bit better or at least now we have the option to handle it in a config option.

**Comment by pablob127** [comment]
> Can you check the [pre-release 1.7.1](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.7.1)? It should be able to handle the regEx a bit better or at least now we have the option to handle it in a config option.

It did not work. I get an error window. For some reason I cannot copy the message, so I am pasting a screenshot.
![Screenshot_2024-06-13_13-42-59](https://github.com/IsmaelMartinez/teams-for-linux/assets/25541487/842fb92d-bdc0-42be-9177-43ac281fa254)
That happens for every link I click, so I imagine it is something a bit more general that broke when trying to fix this.

**Comment by IsmaelMartinez** [comment]
yep, that would be me having added a bug while trying to fix this. I don't know when I will have time to look into this. Probably just use 1.7.0 (or 1.6.1)

**Comment by IsmaelMartinez** [comment]
Hi, can you try 1.7.1 again? @jonatasrs just fixed that issue you were seeing and it might improve that area.

**Comment by pablob127** [comment]
I tried the new 1.7.1, and now clicking on the links (or ctrl-clicking, or right-clicking and selecting "open link") does not do anything. Could you point me again to the command-line arguments for debugging? I tried with --webDebug, and that did not show anything when trying to open the links, and I could not find where I found arguments before.

**Comment by IsmaelMartinez** [comment]
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug

**Comment by pablob127** [comment]
Ok, I have more precisions now:

1) When opening regular (non-meeting links), those work well and are sent to an external browser.
2) When clicking on the meeting links (either v1 or v2), nothing happens but the debug log says:
`[DEBUG] testing RegExp onNewWindow true`
`[DEBUG] DEBUG - captured meetup-join`

So the regex is working, but somehow when it is true it does not lead to opening the join meeting widget.

**Comment by IsmaelMartinez** [comment]
Is it putting the app in focus? (I wonder if it is now filtering it...)
That area of logic is fairly complex and when we change one part, another
might "react" to it.

**Comment by pablob127** [comment]
Somehow I lost version 1.7.1, but when I tried the focus seems to stay in the Teams-for-Linux window (or at least that's what I remember).

**Comment by PauloGDPeixoto** [comment]
I have the exact same behaviour that @pablob127 is reporting. I have some calendar entries where I manually inserted the meeting link, and I'm not able to join directly by clicking on the link. Observing the debug log I can see those lines (testing RegExp and captured meetup-join) being written when I click the link.

**Comment by PauloGDPeixoto** [comment]
Poking around I found that, if the meeting details window collapses the join info (by displaying a "Show join info" link), the link works, otherwise, it doesn't.

**Comment by IsmaelMartinez** [comment]
This is a current limitation we have. Closing this in favor of https://github.com/IsmaelMartinez/teams-for-linux/issues/1098 as the original issue is now solved, but the one that stays is a duplicated one. Thanks
