### ISSUE TITLE
Chat looses posts

### ISSUE THREAD

**Issue by ZYZ64738** [IsmaelMartinez/teams-for-linux#129]
**Describe the bug**
See Screenshot:
- Left half: teams-for-linux (Chat)
- Right half: MS-Teams App (Chat) inside Chromium-Browser

**To Reproduce**
Not sure how. Missbehave happens once a while - (this is my 3dt time)
Restart teams does not help, Ctrl+R does not help 

**Expected behavior**
Just show all posts

**Screenshots**
![image](https://user-images.githubusercontent.com/9817678/57277417-6bf9ef00-70a4-11e9-9df3-48a8a3415c20.png)

**Desktop (please complete the following information):**
 OS: Arch Linux 
 Kernel: x86_64 Linux 5.0.13-arch1-1-ARCH
 Uptime: 19m
 Packages: 867
 Shell: bash 5.0.3
 Resolution: 5760x1200
 DE: XFCE4
 WM: Xfwm4
 WM Theme: Arc-Dark
 GTK Theme: Ultimate-Dark-Flat-Red [GTK2]
 Icon Theme: Papirus-Dark
 Font: Noto Sans 10
 CPU: Intel Core i7-4770 @ 8x 3.9GHz [27.8°C]
 GPU: GeForce GT 630
 RAM: 2041MiB / 15968MiB

**Additional context**
None so Far

**Comment by julian-alarcon** [comment]
HI @ZYZ64738 which version are you using? Snap? Arch Linux AUR? Source Code build?

Also please check this known issue:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#no-history

**Comment by ZYZ64738** [comment]
I am using the AUR-Package:
teams-for-linux 0.2.0-1

Today i got a newer version:
teams-for-linux 0.2.0-2

I will try the fix which is described under your posted link. Thnx

**Comment by ZYZ64738** [comment]
I tried suggested fix and it worked for me.
