### ISSUE TITLE
Set status message from command line

### ISSUE THREAD

**Issue by sarvasana** [IsmaelMartinez/teams-for-linux#1298]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem.

**Describe the solution you'd like**
I would like to be able to set my teams status from the command line.
This saves me from opening the application.
It also allows me to pipe status information from other apps to teams.
It would be great if this feature could be used even while teams is already running.
If the feature is used when teams is already running, no other visual teams instance will appear.
The teams instance used for setting the status will set the status and terminate.

**Describe alternatives you've considered**
There is no alternative found.

**Additional context**
The commands could look like this:

`teams --set-status "having lunch" --clear-after 1h`
`teams --set-status "playing: the weeknd - blinding lights" --emoji 1f929`

**Pseudo Pipe examples:**
`mprisctl current | xargs -I{} teams --set-status "playing: {}"`
`build_status | xargs -I{} teams --set-status "build: {}"`
`task current | xargs -I{} teams --set-status "working on: {}"`
`calendarctl next | xargs -I{} teams --set-status "next meeting: {}"`
`batteryctl status | xargs -I{} teams --set-status "battery: {}"`
`weatherctl current | xargs -I{} teams --set-status "weather: {}"`
`uptime | awk '{print $10}' | xargs -I{} teams --set-status "load average: {}"`
`pomodoroctl status | xargs -I{} teams --set-status "pomodoro: {}"`
`git rev-parse --abbrev-ref HEAD | xargs -I{} teams --set-status "working on branch: {}"`
`docker ps --filter "status=running" --format "{{.Names}}" | xargs -I{} teams --set-status "containers running: {}"`
`vpnctl status | xargs -I{} teams --set-status "VPN: {}"`

You get the picture!

**Comment by IsmaelMartinez** [comment]
can you use the "feature request" template? Thanks

**Comment by sarvasana** [comment]
I updated the contents.

**Comment by IsmaelMartinez** [comment]
I had a wee look and it doesn't seem to be that easy. The side effect is an authenticated call to `https://presence.teams.microsoft.com/v1/me/publishnote` using a jwt. 

I suspect this is going to be pretty complex but maybe someone can have a dig around and see if they find something.

**Comment by IsmaelMartinez** [comment]
maybe this could be done by using [powerautomate](https://www.microsoft.com/en-gb/power-platform/products/power-automate).

**Comment by wwp** [comment]
Oh yes, a way to change the status (and status message) of a running TFL from the command-line (and when starting), please!

**Comment by IsmaelMartinez** [comment]
Hi @wwp, extremely difficult for us to add that (as far as I am aware). I would suggest trying powerautomate (or workflows) that are "ok" and should give you this sort of features with a few clicks.
