### ISSUE TITLE
Double notifications

### ISSUE THREAD

**Issue by maximbaz** [IsmaelMartinez/teams-for-linux#13]
For every message I get two desktop notifications, one is personalized (with sender's photo, message, etc), the other one is generic useless one.

![image](https://user-images.githubusercontent.com/1177900/47846886-b9319700-ddc9-11e8-85ac-812a45fda446.png)

I tracked the generic notification to this piece:

https://github.com/IsmaelMartinez/teams-for-linux/blob/99621c5f8e9942aabdc36a96bc7a7e9585da4361/app/lib/index.js#L65-L78

Commenting out that entire block solves the issue for me, now I just have one beautiful notification.

Arch Linux, dunst notifications manager, running with ` yarn start --partition persist:teams-for-linux`

**Comment by IsmaelMartinez** [comment]
Hi,

I have added the ability to disable the desktop notifications as I can see this is mainly related to your pretty awesome desktop notifications client. 

version 0.1.9 will default to persist the session (to teams-4-linux) but you will need to run it with:
`teams --disableDesktopNotifications`.

You can test it in here: 
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.1.9

Cheers,

**Comment by maximbaz** [comment]
Why not encourage everyone to switch to a good desktop notifications client, i.e. disable that fake notification by default, and only enable it with flag on demand? 😉

**Comment by maximbaz** [comment]
Also, this extra notification wasn't part of upstream, you added it yourself, correct? Just curious, why did you do that?

**Comment by IsmaelMartinez** [comment]
The upstream system had a notification but didn't work neither in Fedora or Ubuntu. I added it to support notifications for base installations, otherwise I will get more people saying that the notifications don't work. 

If it was just a rpm/Deb/appimage install I will not mind telling people to move, but it's a bit more complex (I might move anyway at it looks pretty sweet.

All of this will not be a problem if Microsoft had implemented it's notifications following the HTML5 specification, they will just work in most cases.. but hey, they want to have clients for everything.

**Comment by maximbaz** [comment]
Alright, up to you. Maybe consider renaming the flag to `disableBasicNotifications`, because `disableNativeNotifications` is quite confusing, native notifications work and work well 😉

**Comment by IsmaelMartinez** [comment]
Feel free to create a pull request. I will personally prefer something like `disableNotificationsHack` ;)

**Comment by maximbaz** [comment]
I'll leave it up to you, as I said I in general disagree with having this hack enabled by default, but as long as there is an option to disable it (how ever it is named), I'm reasonably satisfied.

**Comment by IsmaelMartinez** [comment]
I will change the name if I end up doing another release. To be honest, maybe in a couple of months redhat and ubuntu notification manager are as good as dunst ;) Then I will disable it by default :)
