### ISSUE TITLE
Appreciation Issue

### ISSUE THREAD

**Issue by mccarthyryanc** [IsmaelMartinez/teams-for-linux#130]
This isn't an issue, but I didn't see any other place to thank the contributors to this project!

I'm so happy I can use full-featured Teams from Linux! Thanks for all the hard work!

:clap:

**Comment by julian-alarcon** [comment]
Thank you! I'll close this one!

**Comment by IsmaelMartinez** [comment]
@mccarthyryanc , thanks for the appreciation. It does really help knowing people appreciate. @julian-alarcon , thanks for closing the issue. I am still mostly offline at the moment.
