### ISSUE TITLE
Flathub package not updated

### ISSUE THREAD

**Issue by sonnatager** [IsmaelMartinez/teams-for-linux#1304]
It seems that the package on flathub is about 2 Month old (4th of May)

https://flathub.org/apps/com.github.IsmaelMartinez.teams_for_linux

Can you also release it on flathub on a regulary base?

**Comment by IsmaelMartinez** [comment]
The release is automatically done when a package is marked as released. But they are complaining about the name including the word "Teams" that they think is the trademark of Microsoft. I disagree but releases there are blocked at the moment. Just use one of the other many packaging systems while this legal issue is resolved.

**Comment by IsmaelMartinez** [comment]
This is now updated
