### ISSUE TITLE
apt cannot locate package, but snap can install

### ISSUE THREAD

**Issue by nirist** [IsmaelMartinez/teams-for-linux#1305]
Was unable to install using apt, but could install via snap.

I did the steps as mentioned in the "Debian/Ubuntu and other derivatives" part of README. After updating and attempting to install via apt by running "sudo apt install teams-for-linux" no apt package was found but a snap package was found. The terminal further instructed me to try to install via snap and it worked by running "snap install teams-for-linux". Below is the screenshot.

OS: Ubuntu 22.04.4

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/32228659/689e5b2f-36a6-44fe-8662-95a472288816)

**Comment by IsmaelMartinez** [comment]
Did you follow the guidelines in the readme? You need to add another source to it. Ta

**Comment by IsmaelMartinez** [comment]
closing as this is just probably not following the documentation. Do reach out if the guidelines don't solve your problem
