### ISSUE TITLE
Video background is not persisted between calls

### ISSUE THREAD

**Issue by mikehaertl** [IsmaelMartinez/teams-for-linux#1308]
**Describe the bug**
When I select a background for video calls it is not persisted: I have to set it again on every new meeting.

**To Reproduce**
Steps to reproduce the behavior (translated from German - actual wording may be different in english):
1. Open a video call
2. Click on "Video effects & settings"
3. Select a background
4. Click on "Apply"
5. Close the call
6. Start a new call

**Expected behavior**
The background selected in the first call should be reused.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 Virginia
 - Installation package: deb
 - Version: 1.6.1

**Debug**
Running with `--webDebug` gives me a core dump:

```
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
[DEBUG] configPath:,/home/mike/.config/teams-for-linux
[WARN] No config file found, using default values
[DEBUG] configFile:,[object Object]
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--webDebug,--appLogLevels=error,info,warn,debug
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
[DEBUG] Spellchecker is disabled!
[mutex.cc : 452] RAW: Lock blocking 0xdfc01010111   @ 0x55ae948f4cac 0x55ae948f4429 0x55ae948f42de 0x55ae94accf4b 0x55ae94abf398 0x55ae94abeb54 0x55ae94ac6602 0x55ae94aadd53 0x55ae94a1b38e 0x55ae94a027eb 0x55ae94a30063 0x55ae97fea585 0x55ae97fea0e2 0x55ae97fe9f0a 0x55ae97f8fa0d 0x55ae97f5548d 0x55ae97fb3ba8 0x55ae96f8bfbf 0x55ae97fb3d4c 0x55ae97fc6cb5 0x7f790ecebac3
[mutex.cc : 452] RAW: Lock returning 0xdfc01010111   @ 0x55ae948f4429 0x55ae948f42de 0x55ae94accf4b 0x55ae94abf398 0x55ae94abeb54 0x55ae94ac6602 0x55ae94aadd53 0x55ae94a1b38e 0x55ae94a027eb 0x55ae94a30063 0x55ae97fea585 0x55ae97fea0e2 0x55ae97fe9f0a 0x55ae97f8fa0d 0x55ae97f5548d 0x55ae97fb3ba8 0x55ae96f8bfbf 0x55ae97fb3d4c 0x55ae97fc6cb5 0x7f790ecebac3
Segmentation fault (core dumped)
```

**Comment by IsmaelMartinez** [comment]
Hi @mikehaertl , I put this as an enhancement that we can work towards getting implemented. One question, do you use the customBackground option explained in https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config or just the MS default customBackground? To see where to look at. Ta

**Comment by mikehaertl** [comment]
I use the blurred background provided by MS, if that's what you mean. Never messed with custom backgrounds.

**Comment by mikehaertl** [comment]
Additional note: This has worked before until recently when the client switched to the new version (that's teams v2 I think?).

**Comment by IsmaelMartinez** [comment]
ahh, then probably ask Microsoft as it would be better if they implement it. Anything we do will be a hack that will easily break when they change their internal specification.

**Comment by mikehaertl** [comment]
Hmm, ok, too bad then. IMO asking MS for a fix is as usually completely pointless. So I will have to live with it.

**Comment by mikehaertl** [comment]
@IsmaelMartinez Actually it also affects my audio settings which is really annoying: It resets to the microphone of my external webcam instead of my USB headset. So I have to fix the audio settings on every second call.

Is there really nothing we can do about it? Or should I create another issue for the audio problem?

**Comment by IsmaelMartinez** [comment]
pretty difficult but I leave it open to see if anyone has an idea on how to implement/solve this, even if it will probably break as soon as MS tries to fix it.

**Comment by mikehaertl** [comment]
It seems like the issue healed itself. At least for a couple of meetings it remembered my background settings.

So maybe this issue can be closed then.

**Comment by IsmaelMartinez** [comment]
Glad to hear
