### ISSUE TITLE
Screen share doesn't work since last update (1.7.3)

### ISSUE THREAD

**Issue by andjelatomic** [IsmaelMartinez/teams-for-linux#1313]
**Describe the bug**
I am not able to do screen share anymore during the video call.
I am using Linux Mint Cinnamon (with X11 and Xorg), as it was for all previous versions.

**To Reproduce**
1. Join the video call
2. Click on Screen share
3. Nothing is happening on click (no list of screens / applications )
4. 

**Expected behavior**
It is supposed to have list of screens/applicaitons where you can select one to share

**Desktop (please complete the following information):**
 - OS: Linux Mint Cinnamon 
 - Installation package [deb]
 - Version [e.g. 1.7.3]

**Debug**

[32623:0624/090904.070133:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] Badge count set to '1'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] Badge count set to '1'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] Badge count set to '1'
[32623:0624/090917.474849:ERROR:CONSOLE(1)] "Request Target.setAutoAttach failed. {"code":-32601,"message":"'Target.setAutoAttach' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[32623:0624/090917.692479:ERROR:CONSOLE(1)] "Request Target.setAutoAttach failed. {"code":-32601,"message":"'Target.setAutoAttach' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'

```bash
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
```

**Comment by limes007** [comment]
Same problem here. Is there a workaround? Will a rollback to 1.7.2 help?

**Comment by KlausMehling** [comment]
Same on Ubuntu 5.14.0-1051-oem

**Comment by antonioabajo** [comment]
It's not possible select the Screen you want to share. In record video clips, selecting screen sharing to record, the same problem happems.

When I click in select your screen to record this alert is shown and the window selector is not shown.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/88318188/abc7905d-68bb-4088-adcb-974ab6acb15a)

**Comment by sprudel79** [comment]
Same issue for me with Linux Mint 21.3, also the app is crashing sometimes in the background. This didn't happen with previous release so there must be a recent change triggering this.

**Comment by TomSp** [comment]
howto allow it in sandbox ?

**Comment by pavellisy** [comment]
last working flatpak build is this:
    Commit: 186db042383e237fff9e6136a59a7f389a9fba247ce85f4748b9f25f50c7b45d
   Subject: Update 2 modules (6dbef8d0)
      Date: 2024-06-21 23:05:07 +0000

**Comment by z1atk0** [comment]
+1 ... same here, Slackware64-15.0, X11 & GNOME 46. :unamused: Reverting back to 1.6.1 allows sharing again.

**Comment by Usaamah99** [comment]
+1 ... Same Here. Arch Linux. Using teams-for-linux 1.7.3 from the AUR

**Comment by bundi78** [comment]
Also, with 1.6.1, screen share is working, with 1.7.[1..3] not

**Comment by mcichocki** [comment]
I don't know if anyone else is having trouble receiving incoming calls because the message 'calling...' appears, and after answering, nothing happens. The latest release is a disaster; did anyone even test it beforehand?

**Comment by banholzer** [comment]
> I don't know if anyone else is having trouble receiving incoming calls because the message 'calling...' appears, and after answering, nothing happens. The latest release is a disaster; did anyone even test it beforehand?
this is another issue I guess. Please separate one issue from another. I realized this problem already on the pre-release but was not able to file an issue/look into the details --> this is Open Source. Everybody is encouraged to support and test pre-releases.

**Comment by jbauerrfid** [comment]
Can confirm screen share is broken in 1.7.3

The new Teams version came from snap today. Since then, no screen or window can be selected for sharing.

Client is Ubuntu 22.04 with x11 (since screen share wayland isn't working on wayland as well, but that is another issue).

**Comment by adriandelgg** [comment]
SAame here Debian 12

**Comment by gwozniak** [comment]
The same issue on Debian 12 X11 KDE and Debian testing  X11 KDE, reverting to 1.6.1 resolves issue.

**Comment by arbexmb** [comment]
Same here. I am using Ubuntu 22.04.4 LTS.
Not only that, I can't open my camera in calls aswell.

**Comment by casta** [comment]
By the way, screen sharing is only broken under x11. It’s working perfectly fine when under wayland.

**Comment by gwozniak** [comment]
> By the way, screen sharing is only broken under x11. It’s working perfectly fine when under wayland.

Yes and no on my side, I re-logged with kwin wayland on trixie  and I saw separate window allowing to choose desktop/window to share, but after clicking share I saw that (both v.1.6.1 and v.1.7.3):
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/848953/3fd1024d-858c-423e-b9ea-9e9b8c5253d0)

I'm glued to pulse on this PC due to problems with usb camera's mic under pipewire, I will recheck it tomorrow on my work PC with bookworm  where I'm using pipewire.

**Comment by IsmaelMartinez** [comment]
Thanks for reporting. I will put back 1.7.3 as pre-release and go back to 1.6.1 as the latest. I did thought it has been tested as a pre-release enough, but obviously it wasn't. 

I suspect the issue is around the refactoring on this area 

<img width="367" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/677d058e-afdd-48d1-8f8c-f0b9366dff68">

Around this file https://github.com/IsmaelMartinez/teams-for-linux/pull/1291/files#diff-33922750afb4f00fe72934ba21d348e07c9eda191fddcdf19954f3b1efa36b8d but I don't know when I will have time to have a look at it. 

If you got a problem with 1.6.1, that would be another issue. Apologies for the issue! Refactoring sometimes do create problems.

**Comment by camspiers** [comment]
I think I see what the issue is.

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/browserWindowManager.js#L72

We are no longer calling assignSelectSourceHandler.

So line 72 should be:

```javascript
ipcMain.on('select-source', this.assignSelectSourceHandler());
```

**Comment by dzaghal** [comment]
Sorry if not related, but this morning my v1.7.something got "updated" to 1.6.1 by snap. It was intentional to solve this problem?

BTW, yesterday screen share was working nicely (I have to login Ubuntu in Xorg instead of Wayland to make it work)

**Comment by gwozniak** [comment]
> So line 72 should be:
> 
> ```js
> ipcMain.on('select-source', this.assignSelectSourceHandler());
> ```

Confirming fix works on Debian 12 X11 KDE :)

**Comment by IsmaelMartinez** [comment]
> Sorry if not related, but this morning my v1.7.something got "updated" to 1.6.1 by snap. It was intentional to solve this problem?
> 
> BTW, yesterday screen share was working nicely (I have to login Ubuntu in Xorg instead of Wayland to make it work)

Aye, I did revert the snap latest to 1.6.1 as 1.7.3 was broken. Once 1.7.4 is out, I will probably leave it a couple of days until I mark it as stable.



> I think I see what the issue is.
> 
> https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/browserWindowManager.js#L72
> 
> We are no longer calling assignSelectSourceHandler.
> 
> So line 72 should be:
> 
> ```js
> ipcMain.on('select-source', this.assignSelectSourceHandler());
> ```
> 
> EDIT: I have opened #1315 with a fix.

Thanks for the fix! I left a couple of small changes needed. Basically increase release number etc. Thanks again!

**Comment by IsmaelMartinez** [comment]
This should be fixed in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.7.4

**Comment by IsmaelMartinez** [comment]
@camspiers is who deserves the credit!  (and the community of contributors that keeps this alive).

He did found the problem and put a PR for it. A true legend ;)

**Comment by adriandelgg** [comment]
Thank you both @camspiers & @IsmaelMartinez!

**Comment by thekk1** [comment]
Thanks for your good work guys! I really appreciate it.
Is it possible to release a new flatpak, too?

**Comment by thekk1** [comment]
@camspiers & @IsmaelMartinez 
Thanks for your good work guys! I really appreciate it.
Is it possible to release a new flatpak, too?

**Comment by IsmaelMartinez** [comment]
Flatpack should be already out. But they can take a few/many hours. Their way of releasing stuff to people is "unique"

**Comment by thekk1** [comment]
> Flatpack should be already out. But they can take a few/many hours. Their way of releasing stuff to people is "unique"

Understood. Thx for your time and the information.

**Comment by IsmaelMartinez** [comment]
confirmed it was released yesterday. It should probably be out tomorrow https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/pull/117

**Comment by f3270** [comment]
I'm having problems trying to share screen on Teams using Fedora 40.

I tried both the web and the @IsmaelMartinez versions on Wayland and X11.

Pls help!

**Comment by IsmaelMartinez** [comment]
Hi @f3270 ,

If you have problems on the web, better check at the Microsoft forums. We wrap around their web version and add features on top. If it doesn't work there, we can't really fix it from our side, but hopefully they got the solution.

You can open a new issue and provide logs if you want me to have another look, but do provide logs as otherwise it is pretty difficult to guess what the problem can be.

Again, if it doesn't work on the web... Check with MS.

**Comment by f3270** [comment]
I upgraded my fedora to 41 and the problem persist with google-chrome ... but with brave-browser it works as expected

**Comment by IsmaelMartinez** [comment]
If it doesn't work in chrome, it will not work in the app. Reach out to MS as they should be able to help you.
