### ISSUE TITLE
App not opening with guest login -- We've run into an issue

### ISSUE THREAD

**Issue by riyazashik07** [IsmaelMartinez/teams-for-linux#1316]
**Describe the bug**
App not opening -- Error Message - We've run into an issue

**To Reproduce**
1. Open the App
2. Sign in as guest login, facing the error

**Expected behavior**
It is supposed to have list of chats.

**Screenshots**

![teams error](https://github.com/IsmaelMartinez/teams-for-linux/assets/98971324/707ec64a-bb5a-4d92-b421-7b88a86c922d)
![teams](https://github.com/IsmaelMartinez/teams-for-linux/assets/98971324/961d7c00-58e4-420d-91aa-d5cb2bf4f5d4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package [snap]
 - Version 1.6.1

**Debug**
v2/:6 {"graphQLErrors":[{"message":"Cannot return null for non-nullable field AuthenticationUserProfile.upn.","locations":[],"path":["authenticationUsers",1,"profile","upn"]}],"clientErrors":[],"networkError":null,"message":"Cannot return null for non-nullable field AuthenticationUserProfile.upn.","originSlotName":"main","originAppId":"com.microsoft.teams.integrated-auth"}

```bash
teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
```

**Comment by IsmaelMartinez** [comment]
Can you log in as guest using the browser? Microsoft did use to have a bug related to guest login with MFA, and this just must be again the same issue.

**Comment by riyazashik07** [comment]
in browser also facing the same
![Screenshot from 2024-06-25 19-01-50](https://github.com/IsmaelMartinez/teams-for-linux/assets/98971324/d776ef2b-d91d-4630-99c7-673d653db218)

**Comment by IsmaelMartinez** [comment]
Sorry to hear. That means is a Microsoft issue that we can't do much from here. 

I believe is here that you need to go https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472 Hope you find a solution in there.
