### ISSUE TITLE
Audio/video calls suddenly unsupported

### ISSUE THREAD

**Issue by vonrotting** [IsmaelMartinez/teams-for-linux#132]
Hi,

First of all, thank you for working so hard on the Teams client.  I have been using it for quite some time and have been very happy to see the development done on it.

The last days I did however discover a strange thing:  When trying to call someone in the chat view, I get the "this feature is not yet implemented, please download the desktop app" message.  At the same time it works fine to join a teams meeting with audio and video.

Version is 0.2.1 installed from a deb built from git sources yesterday (i did not work on the previous build I had either).  Host is running Ubuntu 18.10.

I do not know if electron has dependencies on the system Chrome browser but it struck me today that I recently uninstalled a home brew chromium build installed from deb and replaced it with a development version supplied as a snap package. However, uninstalling the snap did not improve things and the regular Chrome browser i have had installed from the official Chrome repo has not been changed.

I also tried deleting ".config/Teams for Linux", should it contain anything that did not agree with new components to no avail.

I guess that Microsoft may have changed something as well but as I do no longer have the old built debs I cannot go back to verify.

Best regards,
/Erik

**Comment by IsmaelMartinez** [comment]
Hi @vonrotting , 

Thanks for the message. 

The teams app should be packing whatever it needs so I don't think your Chrome version can have any dependency on this... But I might be wrong and/or missing something.

Can you check if version 0.1.19 also shows this issue? 0.2.x mean moving to electron 4 that might/or might not have an issue with this. 

Also, those the problem persists or is only sometimes? Does switch from that chat to a group chat and back allows you to do the call?

The way we activate teh button is by running some JavaScript after the page is loaded... Maybe we aren't waiting long enough, or MS have changed something.

Tha ks

**Comment by vonrotting** [comment]
Hi, @IsmaelMartinez 

Thanks for the feedback.  Electron 4 you say? I believe that client is build with Electron 5.0.1 in my case.  Am i using the wrong build method?  One thing I need to do every time is to "yarn add electron" as "yarn run dist:linux" will fail on electron-builder not being available.  Does that yield a too new electron version?

**Comment by julian-alarcon** [comment]
@vonrotting  We have some issues with Electron 5 and with NodeJS 12
https://github.com/IsmaelMartinez/teams-for-linux/issues/122
https://github.com/IsmaelMartinez/teams-for-linux/issues/123

Please use Electron 4 and NodeJS 10.

**Comment by vonrotting** [comment]
Thank you @julian-alarcon using electron 4.2.1 solved this issue as well as #133 . Lesson learned. :)

Forgive me for being a bit of a noob but is there a way to call yarn to install the correct versions of devDependencies automatically?

**Comment by IsmaelMartinez** [comment]
Closing to keep things tidy as we don’t really support electron 5 at the moment

**Comment by uocxp** [comment]
i am using the snap package how can i choose which Electron and node version to use ? I am unable to do videocalls its greyed out.

**Comment by julian-alarcon** [comment]
The current releases and the Snap release is build with electron 4. You don't need to do anything.

Can you describe what is the grey status? Is your cam or the other members of the call?

Also, did you check this?: https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md

Please add permissions to access the Camera from TeamsForLinux

**Comment by uocxp** [comment]
i didn't know, I need to add permissions for the snap :/ it worked after that. Thanks :)
