### ISSUE TITLE
appIdleTimeout not respected?

### ISSUE THREAD

**Issue by Julien76** [IsmaelMartinez/teams-for-linux#1320]
**Describe the bug**

Hi,

I am using Teams-for-Linux on NixOS and with Hyprland, I have set the following config in `.config/teams-for-linux/config.json`:

```JSON
{
  "appActiveCheckInterval": 6000,
  "appIdleTimeout": 6000,
  "appIdleTimeoutCheckInterval": 6000,
  "awayOnSystemIdle": false,
  "optInTeamsV2": true
}
```

With the following settings, I would expect the status not to go idle before 6000s (1.6h) but the app goes to idle after 300s.

If I launch the app via the terminal with the following command:

`teams-for-linux --appLogLevels debug --enableDesktopNotificationsHack --enable-features=UseOzonePlatform --ozone-platform=wayland`

The terminal output:
```bash
[DEBUG] GetSystemIdleState => IdleTimeout: 6000s, IdleTimeoutPollInterval: 6000s, ActiveCheckPollInterval: 6000s, IdleTime: 0s, IdleState: 'active'
```
However, teams go to idle after 300s (the default value). I check with a stopwatch, and regardless of my activity on my pc, as long as I leave the mouse cursor out of the teams app, my status will turn from available to idle after 300ms.

I tested by setting appIdleTimeout to 100s either in the config.json or via passing as an argument when launching teams via the terminal. Teams only go idle after 300s thus not respecting the 100s.

**Expected behavior**
Teams should go idle after the appIdleTimeout value, so in my case 6000s.

**Desktop (please complete the following information):**
 - OS: Nixos
 - Installation package Nix packages
 - Version 1.4.27

**Comment by IsmaelMartinez** [comment]
It looks like you are using a fairly old version. We did solve the problem
of the appIdleTimeout with teams V2 but I don't recall what version.

Just released 1.7.4 and I would recommend if you update to it and check
again.

**Comment by Julien76** [comment]
Actually I am reopening the issue because I tested with version 1.7.4 on nixos, and the behavior is the same:
- AppIdleTimeout = 6000s -> goes idle after 300s
- AppIdleTimeout = 100s -> goes idle after 300s

**Comment by Julien76** [comment]
I did more test using a Gnome 46 session instead of Hyprland and the results are the same:
-    AppIdleTimeout = 6000s -> goes idle after 300s
-     AppIdleTimeout = 100s -> goes idle after 300s

**Comment by IsmaelMartinez** [comment]
if you open the app with --webDebug (or right click on the menu and see `debug` option). Can you check if you get any of this logs?

`setUserStatus teams2 status=${status}`
`'Failed to set teams2 User Status'`
`'Failed to set User Status'`

And, if you can, put the logs in here (also console ones) but start with all the log levels, not only debug. Is not determining the logs hierarchically, but only printing the ones listed.

`teams-for-linux -appLogLevels=error,info,warn,debug --enableDesktopNotificationsHack --enable-features=UseOzonePlatform --ozone-platform=wayland --webDebug`

**Comment by IsmaelMartinez** [comment]
It can also be that the `appIdleTimeoutCheckInterval` and `appActiveCheckInterval` are far too high. 

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/a2a58c88-78a5-4692-a200-044527b2f624)

I would use the default values for those, otherwise the activityHub doesn't check often enough. I suspect is around that area otherwise there will be a lot of people complaining that this isn't working 😄

**Comment by IsmaelMartinez** [comment]
I don't know if it would be possible to handle the "lock" functionality. As I wasn't the developer that implemented that functionality, it might take me some time to find out. If you could open a separated ticket with that as an enhancement that would be great, as it is not related to this issue. Thanks!

**Comment by IsmaelMartinez** [comment]
actually @kindofblues , isn't this what you are asking for? https://github.com/IsmaelMartinez/teams-for-linux/issues/1081

**Comment by IsmaelMartinez** [comment]
open then a new ticket. Not sure how can be done to be honest so that might influence if there is a new flag or just use the same one. Probably best re-using the same flag as otherwise it can create conflicts.

**Comment by IsmaelMartinez** [comment]
closing. Reopen if the solution doesn't work.
