### ISSUE TITLE
Using a smartcard to login

### ISSUE THREAD

**Issue by EvilWatermelon** [IsmaelMartinez/teams-for-linux#1322]
I want to authenticate via my smartcard reader but there is no possibility to add a security device or something similar. I found the issue #645 but that didn't answers the question on how to use teams-for-linux with a smartcard.

**Comment by IsmaelMartinez** [comment]
Not possible as it is a limitation of the electron framework. Sorry

**Comment by agemuend** [comment]
Dear @IsmaelMartinez, 
could we maybe re-open this? 
Electron 33 has added the necessary callbacks for unlocking Smartcards on Linux with app.setClientCertRequestPasswordHandler():

https://www.electronjs.org/blog/electron-33-0#notable-changes
https://github.com/electron/electron/pull/41205

You set the handler to a dialog that asks for the User PIN. Then the app needs to listen to the 'select-client-certificate' event to present and let the user choose the correct certificate to use for authentication. 

Here is an example that I cobbled together using the docs and AI: https://gist.github.com/agemuend/8fd859ee074517188744f8c6fc11c9a4

**Comment by agemuend** [comment]
Just to clarify, I verified with a small test application that this actually works with our Smartcards and it does.

**Comment by IsmaelMartinez** [comment]
Hi, can you open a new issue as this one was closed in 2024? thanks in advance!

**Comment by agemuend** [comment]
Sure
