### ISSUE TITLE
Teams doesn't open on Ubuntu 24.04 using Wayland

### ISSUE THREAD

**Issue by drungrin** [IsmaelMartinez/teams-for-linux#1323]
**Describe the bug**
Teams doesn't open on Ubuntu 24.04 using Wayland

**To Reproduce**
1. Run via command line `ELECTRON_OZONE_PLATFORM_HINT=wayland teams-for-linux`

**Expected behavior**
Teams open 

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Installation package snap
 - Version 1.7.4

**Debug**

```$ ELECTRON_OZONE_PLATFORM_HINT=wayland teams-for-linux --webDebug --appLogLevels=error,info,warn,debug
MESA-LOADER: failed to open radeonsi (search paths /snap/teams-for-linux/635/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: radeonsi
MESA-LOADER: failed to open kms_swrast (search paths /snap/teams-for-linux/635/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /snap/teams-for-linux/635/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load swrast driver
[DEBUG] configPath:,/home/michel/snap/teams-for-linux/635/.config/teams-for-linux
[WARN] No config file found, using default values
[DEBUG] configFile:,[object Object]
[INFO] Running under Wayland, switching to PipeWire...
dbus-send: /snap/teams-for-linux/635/lib/x86_64-linux-gnu/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.12.20' not found (required by dbus-send)
[36467:0628/112322.526210:ERROR:wayland_connection.cc(196)] Failed to connect to Wayland display: No such file or directory (2)
[36467:0628/112322.526240:ERROR:ozone_platform_wayland.cc(264)] Failed to initialize Wayland platform
[36467:0628/112322.526242:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
```

**Comment by drungrin** [comment]
The issue is on the snap. The apt package works fine.

**Comment by lanthean** [comment]
Hi Guys,
I have encountered the same exact situation with .deb packages (v1.9.2 and v1.9.5).

PS: Please advice where else can I post this note, if closed issue is not the correct place.
BR,
lan

**Comment by IsmaelMartinez** [comment]
If you can open a new issue and fill the bug/issue template, then we can have a look. Ta

**Comment by piperfw** [comment]
For those still having this issue with the snap package, this workaround from the same issue on the [bitwarden snap](https://github.com/bitwarden/clients/issues/12119) worked for me:

```
snap connect teams-for-linux:wayland
export WAYLAND_DISPLAY="${XDG_RUNTIME_DIR:-"/run/user/$(id -u)"}/${WAYLAND_DISPLAY}"
teams-for-linux
```
Still can't get screenshare to work (#1508), so maybe the .deb is the only way to go.

**Comment by programista-zacny** [comment]
Did anybody find general solution for this? I have the same on Ubuntu 24.04.2.

**Comment by IsmaelMartinez** [comment]
is probably a snap configuration. Use deb or search in snap to see if you can find a solution. Hope helps!
