### ISSUE TITLE
can't share my screen in a meeting

### ISSUE THREAD

**Issue by syahbes** [IsmaelMartinez/teams-for-linux#1327]
While on a meeting when clicking the share button it open the menu for sharing
but when clicking on Screen / Window nothing happen

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/99732661/4c20e935-24d1-455c-b8f5-fa934806c9ab)

is this known issue? is there any walk around?

**Comment by IsmaelMartinez** [comment]
please use the issue template as otherwise I need to guess the questions. I guess you are using snap and haven't give the right permissions to the share the screen.

**Comment by Ryushin** [comment]
Not sure if I'm having the same symptom, but I also can't share my screen.   I'm using the deb package.  I can click the "Screen, window, or tab" and it shows the view at the bottom of the screen:
![Teams_Share_Screen](https://github.com/IsmaelMartinez/teams-for-linux/assets/4388558/55547ad4-43db-496b-95cb-efa550f6a613)

I click on "Entire Screen" but it never shares my screen.  In fact, I can't even close that share screen window any longer and the only way to close it is to shut down TFL.

**Comment by syahbes** [comment]
> please use the issue template as otherwise I need to guess the questions. I guess you are using snap and haven't give the right permissions to the share the screen.

thank you for the fast reply !


**Describe the bug**
on a meeting can't share my screen. I dont get any error it just doesnt work

**To Reproduce**
Steps to reproduce the behavior:
1. Go to calendar
2. Click on meet now > start meeting > join now
3. click on 'x' on the 'Invite people to join you' dialog
4. click on share > share screen

**Expected behavior**
choose which screen to share and share it

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/99732661/c6b863d6-c5f6-418a-955c-aef0d204d721)

**Desktop (please complete the following information):**
 - OS: Linux mint
 - Installation package .deb
 - Version 1.7.1

**Debug**
```
shlomi@T470:~$ teams-for-linux --webDebug
[80048:0703/214404.240258:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[80048:0703/214404.270242:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[80048:0703/214421.904142:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[80048:0703/214458.491875:ERROR:CONSOLE(1)] "Request Target.setAutoAttach failed. {"code":-32601,"message":"'Target.setAutoAttach' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[80048:0703/214458.600972:ERROR:CONSOLE(1)] "Request Target.setAutoAttach failed. {"code":-32601,"message":"'Target.setAutoAttach' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/99732661/577caffb-31b8-4842-b778-7e3f04000858)

**Additional context**
Thank you !

**Comment by IsmaelMartinez** [comment]
Out of curiosity, can you share your screen on the browser? I do remember a few weeks ago some users reporting that issue, but it was a company policy blocking it.

**Comment by syahbes** [comment]
yes, in the browser I can share my screen

**Comment by IsmaelMartinez** [comment]
would you be able to test with version 1.6.1 and 1.7.5? There was some heavy refactoring on 1.7.x and I suspect a few things are might still be broken for 1.7.5

**Comment by syahbes** [comment]
yes sure, I will try other versions

**Comment by IsmaelMartinez** [comment]
maybe try 1.7.5. There was another fix in 1.7.2 or 3? (I don't remember)

**Comment by cim--** [comment]
I have a similar problem to Ryushin - also with the .deb package, still happening in 1.7.5 (and has been happening for quite a while, maybe since 1.4.x?, though I don't share screens very often so it's hard to be precise) 

In my case, it works about half the time:
 - start Teams
 - join meeting
 - try to share screen
...half the time it works with no issues, half the time clicking does nothing and the "share screen" bar becomes unclosable. I've not yet found any obvious pattern as to which half of the time it works.

**Comment by Ryushin** [comment]
> I have a similar problem to Ryushin - also with the .deb package, still happening in 1.7.5 (and has been happening for quite a while, maybe since 1.4.x?, though I don't share screens very often so it's hard to be precise)
> 
> In my case, it works about half the time:
> 
>     * start Teams
> 
>     * join meeting
> 
>     * try to share screen
>       ...half the time it works with no issues, half the time clicking does nothing and the "share screen" bar becomes unclosable. I've not yet found any obvious pattern as to which half of the time it works.

That is mostly what is happening to me.  Though I've never been able to share my screen and it has never worked.  I have to start up the old v1.5 Microsoft Teams if I need to share my screen in a meeting.

**Comment by IsmaelMartinez** [comment]
Oh dear, that is really strange. If you manage to pinpoint the version this started to happen then it would be easier to find the cause. It could be a library update or code changes, but I would have expected the 1.7.0 refactoring to be the culpit, not changes from before that. 

@Ryushin, when you say "old Microsoft Teams" do you mean the one MS released officially but then abandoned? Both of your @cim--  and @Ryushin do look different than the one in here by @syahbes , so I will close this issue as I believe it was related to this https://github.com/IsmaelMartinez/teams-for-linux/issues/1313 fixed in 1.7.3.

Can you open another issue with your specific problem? Morphing issues are really difficult to track, understand and follow. Thanks

**Comment by Ryushin** [comment]
> @Ryushin, when you say "old Microsoft Teams" do you mean the one MS released officially but then abandoned? Both of your @cim-- and @Ryushin do look different than the one in here by @syahbes , so I will close this issue as I believe it was related to this #1313 fixed in 1.7.3.
> 
> Can you open another issue with your specific problem? Morphing issues are really difficult to track, understand and follow. Thanks

Opened #1331.

**Comment by syahbes** [comment]
> Oh dear, that is really strange. If you manage to pinpoint the version this started to happen then it would be easier to find the cause. It could be a library update or code changes, but I would have expected the 1.7.0 refactoring to be the culpit, not changes from before that.
> 
> @Ryushin, when you say "old Microsoft Teams" do you mean the one MS released officially but then abandoned? Both of your @cim-- and @Ryushin do look different than the one in here by @syahbes , so I will close this issue as I believe it was related to this #1313 fixed in 1.7.3.
> 
> Can you open another issue with your specific problem? Morphing issues are really difficult to track, understand and follow. Thanks

_'If you manage to pinpoint the version this started to happen then it would be easier to find the cause.'_
yes its the 1.7.0 version.
after it worked for me in - 1.6.1 - I upgraded to 1.7.0 and again it happned.
do you need me to open an issue? or any more detalis?

thank you !

**Comment by IsmaelMartinez** [comment]
@syahbes, I think I had a quick finger there closing the issue before you confirmed it works on 1.7.5. Can you check that version or even the just newly pre-released https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.8.0 ? Thanks

**Comment by syahbes** [comment]
yes sure, will do it later and update you 👍

**Comment by syahbes** [comment]
YES !
in tis version (tag v1.80) its working great ! can share my screen
thank you !

**Comment by jeertmans** [comment]
Hi @IsmaelMartinez, I have the same issue on `latest/stable 1.11.0` (snap), under Ubuntu 24.04.1 LTS.

The first time I click on "share screen" I get this message:

![image](https://github.com/user-attachments/assets/d0545881-ceb8-4e6a-ba27-aa8096e7744f)


But nothing appears, and the camera gets remove. Then further clicks do not display anything.

I installed the `amd64.deb` version from https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.8.0, and it works, but it would be nice that the version available on the Snapstore has working screen sharing feature :-)

**Comment by IsmaelMartinez** [comment]
Have you check your permissions? Snap requires you to give it access to the screen. I suspect that would be the issue in your case.

It would be great if snap allowed us to ping the user for the permissions, but they don't.

**Comment by jeertmans** [comment]
Some permissions were unchecked (but didn't seem related): recording audio, access to hardware information, etc. I check them all, restarted Teams, and still the same issue (didn't restart my computer though).

**Comment by IsmaelMartinez** [comment]
strange, but seeing it works with the deb package means it is something with the snap itself (probably specific to your OS configuration). It might be best to ask in snap forums to see if someone had a similar issue (with other packages)

**Comment by jeertmans** [comment]
Thanks, I will report the bug to their forum when I have time

**Comment by VShkaberda** [comment]
@jeertmans Did you report the bug in the `snapd` forum? I got the same issue and resolved it the same way—by `apt install` from .deb.

**Comment by syahbes** [comment]
That issue solved for me he released new version since the reported issue

**Comment by VShkaberda** [comment]
> That issue solved for me he released new version since the reported issue

Weird. I updated via `snap` to `2.15.0` and still had the same issue. Maybe I should have removed it beforehand. 🤔 Well, Ok than.

**Comment by IsmaelMartinez** [comment]
snap can be a bit "funny" in some systems. If deb works for you is probably a confinement issue and that is snap world... hope helps!

**Comment by jeertmans** [comment]
Hi @VShkaberda, yes, here: https://forum.snapcraft.io/t/teams-for-linux-cannot-share-screen/43396

**Comment by IsmaelMartinez** [comment]
Maybe is the core22/24 change. keep track of it on https://github.com/IsmaelMartinez/teams-for-linux/pull/2758 .

I will probably release that on the 2.18.0 (2.17.0 has already plenty in it, and 2.16.0 is 50% out).

Low confidence that would change anything but is a base building stuff change so it might affect it (probably break it for old systems that is why I am holding it off...)
