### ISSUE TITLE
Status shown as "Away" when locking the screen with awayOnSystemIdle = false

### ISSUE THREAD

**Issue by kindofblues** [IsmaelMartinez/teams-for-linux#1329]
**Describe the bug**
When locking the screen, status is set to "Away" when `awayOnSystemIdle = false`, see https://github.com/IsmaelMartinez/teams-for-linux/issues/1081.

**To Reproduce**
1. Open teams-for-linux, make sure the status is set to "Available".
2. Lock the screen and wait for the set `IdleTimeout` to elapse.
3. Unlock the screen.
4. Status is set to "Away" and transitions to "Available" shortly after.

**Expected behavior**
Status remains "Available" if `awayOnSystemIdle = false`.

**Desktop (please complete the following information):**

- OS: Fedora 40 x86_64
- Installation package: RPM
- Version: 1.7.5

**Debug**

```
[DEBUG] GetSystemIdleState => IdleTimeout: 3600s, IdleTimeoutPollInterval: 30s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 3600s, IdleTimeoutPollInterval: 30s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'locked'
```

**Additional context**
Copied discussion from https://github.com/IsmaelMartinez/teams-for-linux/issues/1320#issuecomment-2202185148.

I have traced this logic to the following code path:

* When the screen is locked, this will evaluate to `activityHub.setMachineState(2)`:

https://github.com/IsmaelMartinez/teams-for-linux/blob/9d2c1ddf4f447898db5a290b0fe608e98936ea51/app/browser/notifications/activityManager.js#L22

* Which in turn will transition to idle:

https://github.com/IsmaelMartinez/teams-for-linux/blob/9d2c1ddf4f447898db5a290b0fe608e98936ea51/app/browser/tools/activityHub.js#L45

I am not sure of the logic here so apologies if I am mistaken, but the outcome is that `awayOnSystemIdle` does not work when locking the screen.

Thanks for taking a look at this :wink:

**Comment by IsmaelMartinez** [comment]
Thanks for reporting @kindofblues . I will see when we can have a look, however, this might be really difficult to implement.

**Comment by IsmaelMartinez** [comment]
that "might" work but I wonder is if this would not trigger as the app would be "sleeping", but you should be able to put a PR. 

The https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/CONTRIBUTING.md should have enough info for you to apply those changes and test them (and even put a PR!)

There are a couple of wee code errors, that I can see:
*  in the last else `const timeOut = self.config.appActiveCheckInterval) * 1000;` should not have the extra ).
*  Also, unlike python where you can create variables inside if/else statements, you can't in javascript. I would change timeOut to be a `let` (so the value can be modified) and declare it before the 1st if.

Something like this:

```
watchSystemIdleState() {
	const self = this;
	self.ipcRenderer.invoke('getSystemIdleState').then((state) => {
		let timeOut;
		if (this.config.awayOnSystemIdle) {
			/*
				Same logic as before: 
					awayOnSystemIdle = true, sets status "Away" when screen is locked.
			*/
			activityHub.setMachineState(state.system === 'active' ? 1 : 2);
			timeOut = (state.system === 'active' ? self.config.appIdleTimeoutCheckInterval : self.config.appActiveCheckInterval) * 1000;

			if (state.system === 'active' && state.userIdle === 1) {
				activityHub.setUserStatus(1);
			} else if (state.system !== 'active' && state.userCurrent === 1) {
				activityHub.setUserStatus(3);
			}
		} else {
			/*
				Handle screen locked: 
					awayOnSystemIdle = false, keeps status "Available" when locking the screen.
			*/
			if ((state.system === 'active') || (state.system === 'locked')) {
				activityHub.setMachineState(1);
				timeOut = self.config.appIdleTimeoutCheckInterval;
			} else {
				activityHub.setMachineState(2);
				timeOut = self.config.appActiveCheckInterval * 1000;
			}			
		}

		setTimeout(() => self.watchSystemIdleState(), timeOut);
	});
}
```

And while you check it, I can have a think about if we should add yet another flag. This would be the default value and affect the majority of people.

**Comment by IsmaelMartinez** [comment]
This has been pre-released as https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.8.1. Closing but we can re-open if it doesn't work. Thanks again for reporting and contributing!!
