### ISSUE TITLE
Basic HTTP auth popup dialog cannot be completed

### ISSUE THREAD

**Issue by vonrotting** [IsmaelMartinez/teams-for-linux#133]
Hi,

I have another issue that just started manifesting itself. 

The issue is that I am working in a corporate environment where we have an internal authentication server doing basic HTTP auth followed by requiring O365 2FA which has been working flawlessly until now (since it was fixed like a year ago).

What is happening is that I do get the basic auth popup in the client and can fill in username and password but nothing happens when I try to submit.  I do not remember if the OK button in the pop up should give visual feedback when being clicked but it certainly does not now.

I can work around this by logging in outside the corporate network using the normal O365 login procedure complete with 2FA.

Best regards,
/Erik

**Comment by IsmaelMartinez** [comment]
Hi @vonrotting , 

That seems odd. Sounds a bit tedious but could you test an older version (like 0.1.19 or even a pretty old one) and see if we can track down the issue?

It might be related to new changes or even to issues with electron 4. Thanks!

**Comment by IsmaelMartinez** [comment]
Closing as electron 5 is not yet supported
