### ISSUE TITLE
Missing Font on save file on Ubuntu 24.04

### ISSUE THREAD

**Issue by sc0rp1t** [IsmaelMartinez/teams-for-linux#1336]
**Describe the bug**
Save dialogue when downloading a file is corrupted -- looks like the font is missing somewhere.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Click to download the file anywhere in Teams  
2. When dialogue pops up no text just boxes appearing 

**Expected behaviour**
Readable font 

**Screenshots**
![Screenshot from 2024-07-10 15-01-21](https://github.com/IsmaelMartinez/teams-for-linux/assets/21171199/ae5d1257-e7ac-4f85-b272-321ce2a86434)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Installation package: snap
 - Version: Latest/stable -- 1.7.5 -- snap-id: IIAJhVGfBhm393UTagoW5awtZlPDGqHd
 
**Debug**
There are few issues showing -- when download clicked nothing changes in the log. 

If required can be provided on PM. 

**Additional context**
--

**Comment by IsmaelMartinez** [comment]
This is some local config. I think this is the same as https://github.com/IsmaelMartinez/teams-for-linux/issues/1105 and https://github.com/IsmaelMartinez/teams-for-linux/issues/1245 (and a few others)

This works in most cases https://github.com/IsmaelMartinez/teams-for-linux/issues/1105#issuecomment-1947728319

**Comment by andremetelo** [comment]
I have the same issue after upgrading to 24.04 recently.

I tried the fix from #1105, but it did not work.

**Comment by IsmaelMartinez** [comment]
@andremetelo , I would recommend then using another packaging system. Check the release folder, but you are the only person I have heard that solution don't work. If that doesn't work, then open a new issue and put as many information as you can and I can have a look. Thanks for reporting!
