### ISSUE TITLE
Fido key + pingID auth not working correctly

### ISSUE THREAD

**Issue by aminekun90** [IsmaelMartinez/teams-for-linux#1338]
**Describe the bug**
Fido Key on Ping ID, password prompt is not showing and the screen is stuck on the change auth device screen
**To Reproduce**
1. Have an account with fido key activated with a password
2. Try to sign in
3. See the auth screen without password prompt

**Expected behavior**
When authenticating with Fido key a password prompt is shown to enter it and then the authenticator asks to touch the key 

**Screenshots**
This is the fido key tutorial and example of behaviour https://www.youtube.com/watch?v=sI7yWHim-2Y

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Version 1.7.5

**Comment by IsmaelMartinez** [comment]
Unfortunately fido keys and similar aren't supported by electron. You can use certificates if that works for you or other available authenticated mechanisms that are in the config area. 

Apologies but I would suggest reporting it into electron issues instead as the more noise we make there, the more possible they would add the support. This one is the issue I keep tracking https://github.com/electron/electron/issues/24573

See https://github.com/IsmaelMartinez/teams-for-linux/issues/1126 and a few previous ones. 

Closing as duplicated and as work we can't do unfortunately
