### ISSUE TITLE
Deal with https://teams.live.com/ URLs

### ISSUE THREAD

**Issue by rakotomandimby** [IsmaelMartinez/teams-for-linux#1339]
### The problem
When a correspondant sends me a meeting link like https://teams.live.com/meet/9444802028296?p=N4IzETWmG2, I dont know how to join it with **teams-for-linux**

###  Solution I'd like

It would be nice if I can joina a meeting by issuing the following command line:
```
teams-for-linux 'https://teams.live.com/meet/9444802028296?p=N4IzETWmG2'
```

**Comment by IsmaelMartinez** [comment]
this should work, you only need to change the config option that is called url and use the teams.live.com, but maybe you are suffering what some users are suffering https://github.com/IsmaelMartinez/teams-for-linux/issues/1098.

If you can use the issue template and fill the information, then we might be able to determine if it is the same issue, another issue and/or if we know why is happening. Without that information we can only guess and there are far too many variables in play. Thanks
