### ISSUE TITLE
cannot run fcitx5 input method for appimage format 

### ISSUE THREAD

**Issue by newyorkthink** [IsmaelMartinez/teams-for-linux#1340]
![Peek 2024-07-14 14-11](https://github.com/user-attachments/assets/9e2f1cbd-b0b5-4961-bb37-427e3b1af633)

i using the fcitx5 to input chinese 

i using the typora to compare teams

the teams cannot input chinese but typora it can using

the bug is your appimage not full gtk lib file

**Comment by newyorkthink** [comment]
and you need 
export QT_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx

add appimage apprun

**Comment by IsmaelMartinez** [comment]
Hi @newyorkthink, thanks for reporting.

Can you use the template and try with another packaging system? This is to ease finding the problem and solution (if there is any).

I suspect it's related to https://github.com/electron/electron/issues/33662 and that would mean we are fairly blocked.

**Comment by newyorkthink** [comment]
> Hi @newyorkthink, thanks for reporting.
> 
> Can you use the template and try with another packaging system? This is to ease finding the problem and solution (if there is any).
> 
> I suspect it's related to [electron/electron#33662](https://github.com/electron/electron/issues/33662) and that would mean we are fairly blocked.

you need add this

# Detect input method framework
if pgrep -x "fcitx5" > /dev/null; then
    export QT_IM_MODULE=fcitx
    export GTK_IM_MODULE=fcitx
    echo "Using fcitx5"
elif pgrep -x "fcitx" > /dev/null; then
    export QT_IM_MODULE=fcitx
    export GTK_IM_MODULE=fcitx
    echo "Using fcitx"
elif pgrep -x "ibus-daemon" > /dev/null; then
    export QT_IM_MODULE=ibus
    export GTK_IM_MODULE=ibus
    echo "Using ibus"
else
    echo "No fcitx, fcitx5, or ibus detected, falling back to default"
fi

**Comment by newyorkthink** [comment]
```
# Detect input method framework
if pgrep -x "fcitx5" > /dev/null; then
    export QT_IM_MODULE=fcitx
    export GTK_IM_MODULE=fcitx
    echo "Using fcitx5"
elif pgrep -x "fcitx" > /dev/null; then
    export QT_IM_MODULE=fcitx
    export GTK_IM_MODULE=fcitx
    echo "Using fcitx"
elif pgrep -x "ibus-daemon" > /dev/null; then
    export QT_IM_MODULE=ibus
    export GTK_IM_MODULE=ibus
    echo "Using ibus"
else
    echo "No fcitx, fcitx5, or ibus detected, falling back to default"
fi

```

**Comment by newyorkthink** [comment]
in you AppRun

**Comment by newyorkthink** [comment]
> Hi @newyorkthink, thanks for reporting.
> 
> Can you use the template and try with another packaging system? This is to ease finding the problem and solution (if there is any).
> 
> I suspect it's related to [electron/electron#33662](https://github.com/electron/electron/issues/33662) and that would mean we are fairly blocked.

I try to change AppRun
![image](https://github.com/user-attachments/assets/2036eee1-65aa-460b-8ccd-d0316786fd0c)
![image](https://github.com/user-attachments/assets/a0ae0c99-f615-4db0-96b2-d849ba3035b5)
![Peek 2024-07-14 16-45](https://github.com/user-attachments/assets/62e13a98-daf6-4540-853f-58e0e97c6bec)

and it work , but the appimage always show loss the ibus , please merge full library file for the team appimage

is my test, please fixed and review it , i just simple operate.

**Comment by IsmaelMartinez** [comment]
Thanks for the info! I got a few changes on the go, and holidays will slow things down for a bit, but I will try to add it at some point.

If anyone needs it faster, I would appreciate a PR.

I mark it as a 'workaround available'. Thanks for reporting and providing a workaround!

**Comment by xulongwu4** [comment]
@liruohrh Yes, `--enable-wayland-ime` is the flag that is needed to make it work. Thank you!
