### ISSUE TITLE
Video vertical stripes on new Version

### ISSUE THREAD

**Issue by itouchdennis** [IsmaelMartinez/teams-for-linux#1341]
**Describe the bug**
If I start / join a meeting and people sharing their webcam, the video has vertical stripes on the current version. Downgraded to the version before and everything works fine.

**To Reproduce**
1. Go to Teams (v1.8.0)
2. Click on existing (even old) Meeting
3. Share your webcam
4. Move a bit around and see the stripes 
5. Downgraded to the Version 1.7.5 on Flatpak "resolved" this issue as a workaround for me

**Expected behavior**
Clear image, no stripes

**Screenshots**
![image](https://github.com/user-attachments/assets/48d04ee2-992f-4bda-9e02-1eeeb56a437a)

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Installation package deb / flatpak
 - Version 1.8.0

**Comment by IsmaelMartinez** [comment]
Thanks for reporting @itouchdennis. I think this is the same as #1342 and it is probably due moving to electron 30 (that was the main change in 1.8.0. I will move it to that one as there as logs in there what might provide me with more info. I close this one just to not having 2 brains. If you can reply there if you got wayland or what GUI you got that would be great.
