### ISSUE TITLE
Please add regular unicode emojis :pray: 

### ISSUE THREAD

**Issue by urosjarc** [IsmaelMartinez/teams-for-linux#1343]
**Describe the solution you'd like**

I would really like to use regular unicode emojis in microsoft teams: https://unicode.org/emoji/charts/full-emoji-list.html
Currently unicode emojis looks like they are not displayed as they should be... On mobile app emojis are rendered correctly...

![image](https://github.com/user-attachments/assets/f06c2a2d-980a-4ec9-9283-a78a54bbcd26)

It would be awesome if there would be setting where you can choose which emojis you would like to use while pressing on emoji button.

![image](https://github.com/user-attachments/assets/3998a2cc-e9cf-49f7-987a-d8d8208ac2bb)

**Comment by IsmaelMartinez** [comment]
Thanks for the feature request. If I understand you well, you would like us to change the emojis MS provides. 

Unfortunately we can't do much about it. You should ask in the [MS forums](https://answers.microsoft.com/en-us/msteams/forum). Hope helps!
