### ISSUE TITLE
problems with backticks

### ISSUE THREAD

**Issue by luxzeitlos** [IsmaelMartinez/teams-for-linux#1345]
**Describe the bug**
When typing a backtick (`) for me it does not trigger an inline code, not does typing triple-backticks trigger a code block.
It's especially relevant, that my keyboard requires me to type shift+^ for the backtick, and then followed by the space to "finalize" the backtick.
It works in the web app. Just not in this electron app. So it could be related.

**Comment by IsmaelMartinez** [comment]
Sorry but I can recreate this. 

I tried with ` then my text and ` (without spaces like `something`) and it works fine in chats. 

If I you add spaces (like `something ` or ` something` or ` something `) then MS doesn't detect that as a code block neither in the web app, the mac app or this client.

**Comment by newfylox** [comment]
I also have a problem with this... before, doing 3 backtips and hitting space triggered a code block but not anymore. But I have to say that my inline code wasn't working before, only the code block, but now nothing.

Upgraded from 1.5.2 to 1.8.1 yesterday after my vacations.

**Comment by IsmaelMartinez** [comment]
are you still experiencing this issue? If so, can you fill the template and provide more info @luxzeitlos ? lt could be related to the package you are using or others.

**Comment by discordier** [comment]
Having the same problem here.

Nothing is visible in the dev console.

How can I provide logs that help to pinpoint this issue? I suspect the chat window is entirely handled on client side in Javascript, therefore I doubt there will be anything of value in application logs?

**Comment by IsmaelMartinez** [comment]
Hi @discordier , if you can provide the logs that would be great. My suspicion lies on the hardware acceleration. It can generate this sort of issues. If you have notice that your laptop is "accelerating" (fan going bananas) when joining a meeting and the like, you might need to use the `disableGpu` config option. But the logs might give a hint.

Get the latest (1.9.1) and run the app with the following options:

```
teams-for-linux --webDebug --logConfig='{}'
```

Then paste the logs (remember to mask any PII if there is any)

**Comment by IsmaelMartinez** [comment]
closing due inactivity (and to keep things clean), do report back with logs if you still facing the issue.

**Comment by dceee** [comment]
> ```
> teams-for-linux --webDebug --disableGpu --logConfig='{}'
> ```
> 
> Then paste the logs (remember to mask any PII if there is any)

I could not generate any useful log output when using these options. However, I found a workaround by disabling dead keys on my keyboard. For quite a while, I still could initiate a code block with dead keys enabled by using Teams in Firefox but even this stopped working suddenly.

**Comment by IsmaelMartinez** [comment]
glad you found a solution.

**Comment by IsmaelMartinez** [comment]
Hi @Marvin-Szyperski,  If you can open a new issue, we might be able to see why it is not working for you. This app works in electron that wraps chromium. Check before opening the other issue if this also happens in your chromium browser, as I think this is an issue with it, and not the app (as we don't do anything around this area).

**Comment by discordier** [comment]
you are right. Just checked on https://teams.microsoft.com/v2/?clientexperience=t2 and the problem is already present there.
Nothing you can do here - sorry about the fuzz.

**Comment by Marvin-Szyperski** [comment]
@IsmaelMartinez i dont have Chromium or Chrome on my Machine. I only use Firefox and it works fine in firefox. Should I download Chromium, to test it there? Depending on that outcome, creating a new issue would be unnecessary. 

@discordier Well, if i open that link the backticks work perfectly fine for me?

**Comment by discordier** [comment]
@Marvin-Szyperski For me the backticks do not work at all.

**Comment by IncandescentChrysalis** [comment]
I am also facing an issue with backtips not triggering code blocks, either:
* Inline: \`foo`\<space>
* Block: \```\<space>

Sending the message does not format either.

I am using `v1.11.5`.
Which logs (console / `Debug` or file-s) would you require @IsmaelMartinez?

**Comment by IsmaelMartinez** [comment]
Sorry but this is a Microsoft issue as it happens also in the browser. I would suggest you reach out to Microsoft instead. Hopefully they fix it soon.

**Comment by dceee** [comment]
This is a known issue with Teams documented here:
https://github.com/MicrosoftDocs/msteams-docs/issues/9126

You can try to work around by switching to a keyboard layout with dead keys disabled.
