### ISSUE TITLE
Feater Request: Add Web Debug to right click menu

### ISSUE THREAD

**Issue by Fmstrat** [IsmaelMartinez/teams-for-linux#135]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In the icon's right click menu where `Open/Refresh/...` are located, add the `Web Debug` option if it is enabled on the command line. Or just move it there completely.

**Comment by IsmaelMartinez** [comment]
See comment in PR. Thanks for your contribution! Basically I prefer to add the option to the menu, instead of moving it. Both are useful cases

**Comment by Fmstrat** [comment]
I can move it to a `--webDebugMenu` option if that is preferable.

**Comment by IsmaelMartinez** [comment]
I think that just adding the webdebug option to the menu will be enough.

Not sure if we need to make it configurable (to appear there) .

If you got that use case, then yes, just add that option but probably call it ‘showWebDebugInMenu’ or similar .
