### ISSUE TITLE
Widow size not persisted after system restart

### ISSUE THREAD

**Issue by cvetan** [IsmaelMartinez/teams-for-linux#1350]
**Describe the bug**
After system restart window size of teams is not persisted and is reset to very small one

**To Reproduce**
1. Open Teams and set prefered window size
2. Reset the system
3. Open Teams again
4. See  the reset windows size, back to small one

**Expected behavior**
Set window size should be persisted 

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 Cinnamon
 - Installation package deb
 - Version 1.9.0

**Comment by IsmaelMartinez** [comment]
Thanks for reporting. Can you check if this happens on older versions? Just
to see if it is something introduced in the latest versions. Thanks

**Comment by IsmaelMartinez** [comment]
closing due inactivity and to keep the amount of issues manageable. Please re-open with more info if you are still facing the issue.

**Comment by cvetan** [comment]
Appearantly what works you need to gracefully exit application for this not to be reproducuble. I configured desired window size, and quit application (system tray option quit). After that next start of application, even after reboot had desired window size.

**Comment by IsmaelMartinez** [comment]
it might have been some caching issue. Sometimes when we increase the version of electron strange issues happen, like this one. Glad it is working for you again and thanks for reporting (both, the issue and it been fixed)
