### ISSUE TITLE
this happened when my teacher tried to show me a whiteboard on your app, im on the appimage version

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [IsmaelMartinez/teams-for-linux#1352]
**Describe the bug**
when she screenmirrored the whiteboard it didn't worked and instead showed me this message
![Captura de pantalla -2024-08-01 18-57-08](https://github.com/user-attachments/assets/781f2889-348d-477c-b09b-f1dd72718daa)

**To Reproduce**
1. 'Screenmirror any whiteboard as a teacher'
2. 'your student will not see nothing'

**Expected behavior**
the whiteboard should work like when you use it in your browser.

**Screenshots**
![Captura de pantalla -2024-08-01 18-57-08](https://github.com/user-attachments/assets/644159bb-e1c2-4074-902d-118be12f5d60)
.

**Desktop (please complete the following information):**
 - OS: Slackel Linux 64 bit
 - Installation package: Appimage
 - Version 1.8.1

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --logConfig='{}'
```

*IMPORTANT:* Ensure that you mask any sensitive information before posting the output.

**Additional context**

**Comment by soyDESKTOP68A2MRFT** [comment]
also i installed it through [am package manager, it is a package manager which manages appimages](https://portable-linux-apps.github.io/#how-to-install-quotamquot)

**Comment by soyDESKTOP68A2MRFT** [comment]
the thing is this appimage manager install only stable versions of the apps

**Comment by IsmaelMartinez** [comment]
Is it possible for you to provide some logs using the --webDebug? Thanks

**Comment by IsmaelMartinez** [comment]
closing due inactivity and to keep the number of issues manageable. If you can provide some logs that would be great as it would give me more info on why the issue is happening. I can't reproduce on my side. Thanks
