### ISSUE TITLE
Execute a command on call join

### ISSUE THREAD

**Issue by utrack** [IsmaelMartinez/teams-for-linux#1353]
Hi there! Thanks for the client :)

**Is your feature request related to a problem? Please describe.**
I want to get the details of the current meeting every time I join a call for my journaling.

**Describe the solution you'd like**
An option like incomingCallCommand (joinCallCommand?) would work if I could put the meeting's JSON to the args (or at least the meeting ID/join link)

**Describe alternatives you've considered**
MS Graph APIs won't let me see the call I've joined.

**Additional context**
Ideally, that would be a JSON like the one provided by MS APIs, but even a meetingID or a join link would work. With ID or a join link I could query the Graph API to get the data.

MS call JSON object:
https://learn.microsoft.com/en-us/graph/api/call-get?view=graph-rest-1.0&tabs=http

**Comment by utrack** [comment]
just checked - keys of msTeamsCalling[RANDOM_ID?].deref().activeCallsService.activeCalls are the conversation/meeting IDs which can be used to get the participants

**Comment by IsmaelMartinez** [comment]
yes, moving to react have broken all of that. If you have time to look around that that would be amazing, as it would allow us to add more magic to this app (and resurrect the incomingCallCommand scripts options).

**Comment by IsmaelMartinez** [comment]
Basically, blocked by https://github.com/IsmaelMartinez/teams-for-linux/issues/1195 :/

**Comment by utrack** [comment]
gotcha!

so, first change is:
```
function getAppObjects() {
	if (typeof msteamscalling == "undefined") {
		return null;
	}

	let dref = msteamscalling.deref();

	return {
		controller: dref,
	};
}
```

this will allow for most of the stuff to work; you just need to replace `inst.injector.get('presenceService').setMyStatus(status, null, true)` with
`inst.controller.presenceService.setMyStatus(status, null, true);` and the likes.

events:

`inst.controller.eventingService.asObservable` will now give you access to all the internal events. 

maybe `...asObservable.subscribe` will work?

**Comment by utrack** [comment]
I see there's a dictionary of those names somewhere in the minified code:

![image](https://github.com/user-attachments/assets/e58db5be-88f9-4913-9545-b7bf7de7d0ba)

**Comment by IsmaelMartinez** [comment]
I will see when I have time to have a look at this, but that looks promising!

**Comment by utrack** [comment]
```
bar.eventingService.asObservable.subscribe((e, data) => {
		console.dir(data);
	});
```

- I see data.signalingSession.isIncomingCall in `data`! so assignIncomingCallCreatedHandler seems to be working now

I can't find the event key yet though

**Comment by utrack** [comment]
useful for debugging events, how to snoop on the events

```
let controller = msteamscalling.deref(); 
let subStub = controller.eventingService.asObservable.trigger;
controller.eventingService.asObservable.trigger = function(a,b,c) { console.log(a,b,c); subStub(a,b,c);}
```

Here's the fix for most of the calling events (note some commented-out stuff marked by TODO), but you probably don't want an MR - my editor autoformatted the code :S

**Comment by IsmaelMartinez** [comment]
oh wait, that would only work in the teams-v1 (angular) isn't ? MS is deprecating that part pretty soon unfortunately.

**Comment by IsmaelMartinez** [comment]
it does look ms does use a similar pattern in react.

<img width="803" alt="image" src="https://github.com/user-attachments/assets/fae6a400-33ef-4ce5-92c2-8548ebd095b3">

most of the interesting stuff is under 
`document.getElementById('app')._reactRootContainer.current.updateQueue.baseState.element.props.coreServices`

not sure if that helps anyone

**Comment by IsmaelMartinez** [comment]
Hi @utrack , did you manage to get some time to look into this? Just curious as I haven't had luck with it. (not that proficient in react)
