### ISSUE TITLE
Show shared content by a peer in full screen mode

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [IsmaelMartinez/teams-for-linux#1354]
It would be great to have the chance to show the content shared during a call (e.g. shared screen during a presentation) in full screen, without buttons or overlays covering what's received.

**Comment by IsmaelMartinez** [comment]
I would appreciate if you can use the template. This was requested in the past but it would require a lot of work that might not be suitable currently. (we are a bit busy with the teams-v2 migration), but I leave it open as I do understand this is a bit of a pain. Hopefully electron does improve this area, as currently is not fully supported and we have to implement a custom solution on the top.

**Comment by IsmaelMartinez** [comment]
This is blocked until we move away from BrowserView (now deprecated) to webcontentsview
