### ISSUE TITLE
Window controls are located on left side despite the system settings when ELECTRON_OZONE_PLATFORM_HINT=auto/wayland

### ISSUE THREAD

**Issue by serzhi0** [IsmaelMartinez/teams-for-linux#1363]
**Describe the bug**

**To Reproduce**
1. Set env variable ELECTRON_OZONE_PLATFORM_HINT equal to "auto" or "wayland"'
2. Start the application

**Expected behavior**
The window controls (minimize, maximize, close) should be located at right (according to the system settings)

**Screenshots**
![image](https://github.com/user-attachments/assets/f81692a7-4f20-4cd1-902a-ed0466284f92)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Installation package: deb
 - Version: 1.18.1

**Debug**
teams-for-linux --webDebug
[DEBUG] configPath:,/home/siarhei_matsevich/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
[INFO] Running under Wayland, switching to PipeWire...
[DEBUG] Adding electron CLI flag 'ozone-platform-hint' with value 'wayland'
[DEBUG] Adding electron CLI flag 'enable-features' with value 'WaylandWindowDecorations'
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--webDebug
[DEBUG] testing RegExp processArgs false
[DEBUG] testing RegExp processArgs false
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
[DEBUG] Spellchecker is disabled!
[DEBUG] Network test successful with method https
[42522:0814/180719.650864:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[42522:0814/180719.655027:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] Badge count set to '0'
[DEBUG] Badge count set to '0'
[DEBUG] Badge count set to '0'
[42522:0814/180726.020302:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[DEBUG] did-frame-finish-load,[object Object],false
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
^C[DEBUG] before-quit
[DEBUG] window close
[DEBUG] window closed
[DEBUG] will-quit
[DEBUG] quit

** Additional info **
This can be fixed by switching the Placement in Windows Titlebars in Tweaks app to left and then back to right

**Comment by IsmaelMartinez** [comment]
Hi! Can you elaborate on the "workaround" you mentioned in the additional info? It does sound like an electron issue or limitation, and knowing more about that workaround might make it possible to find what it is and if we can fix it. Thanks!

**Comment by serzhi0** [comment]
> Hi! Can you elaborate on the "workaround" you mentioned in the additional info? Is this now solved for you or you need to apply the same fix every time?
> 
> It does sound like an electron issue or limitation, and knowing more about that workaround might make it possible to find what it is and if we can fix it. Thanks!

Sure!

Right after adding ELECTRON_OZONE_PLATFORM_HINT=auto or wayland and log out/log in and launch the application. The controls are displayed on the left side even if other windows have right alignment (as displayed on the screenshot). 

If you go to the **Tweaks** application and then navigate to **"Window Titlebars"** on the left navigation menu, then change **"Placement"** parameter to **left**, then back to **right** -> now the issue is fixed and you do not need to do it each time after log in to system, so the **fix is permanent**

I hope this helps, but if not - feel free to request any other details :)

**Comment by IsmaelMartinez** [comment]
I am not sure if we can do much about it, but glad the workaround only needs to be done once. I keep it open for a bit, but will probably close to keep the backlog manageable

**Comment by IsmaelMartinez** [comment]
I had a further look and I can't recreate it, what makes it pretty difficult then to try to find a solution. I would close this as it is a one off and there is a workaround, but will keep in on the back of my head.

Trying to keep the backlog manageable. Ta
