### ISSUE TITLE
JavaScript error in writeOut

### ISSUE THREAD

**Issue by ismagulb** [IsmaelMartinez/teams-for-linux#1367]
**Describe the bug**

Teams deb 1.8.1 under Debian 12, running since 12 days, window in background. When idle, a window with the following contents pops up:

Error

A JavaScript error occurred in the main process

Uncaught Exception:
Error: write EIO
  at afterWriteDispatched (node:internal/stream_base_commons:161:15)
  at writeGeneric (node:internal/stream_base_commons:152:3)
  at Socket._writeGeneric (node:net:953:11)
  at Socket._write (node:net:965:8)
  at writeOrBuffer (node:internal/streams/writable:564:12)
  at _write (node:internal/streams/writable:493:10)
  at Writable.write (node:internal/streams/writable:502:10)
  at console.value (node:internal/console/constructor:304:16)
  at console.warn (node:internal/console/constructor:384:26)
  at writeOut (node:internal/process/warning:65:3)

Ok

After clicking on "Ok", the window appears again. After clicking "Ok" again, teams continues to work normally.

**To Reproduce**

I couldn't identify specific steps to trigger the issue. Happens about once a week. The process started from GNU screen. The starting pty may or may not be open, not sure. This time this happened some minutes after resume in a different net.

**Expected behavior**
No unhandled exceptions.

**Screenshots**
![20240817-javascript_exception](https://github.com/user-attachments/assets/65a4025e-c1c6-44af-901c-48d712f795ff)

**Desktop (please complete the following information):**
 - OS: Debian
 - Installation package: deb
 - Version: 1.8.1

**Debug**

As I don't know how to reproduce this, I've restarted teams-for-linux with --webDebug --logConfig='{}' and will comment if the problem occurs.

**Additional context**
None

**Comment by IsmaelMartinez** [comment]
that is pretty strange, can you upgrade to 1.9.0? The --logConfig option is only available from 1.9.0

Maybe that was a blip on MS?

**Comment by ismagulb** [comment]
Thanks Ismael for your response,
I've upgraded to 1.9.2 and started with --webDebug --logConfig='{}'.
The issue hasn't occurred for a week. I'm closing the issue and would reopen if the issue occurs again.

**Comment by IsmaelMartinez** [comment]
I think this is related to the file handler from electron-log. If you keep getting this, try changing the handler to `console` in logConfig config option https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config

**Comment by IsmaelMartinez** [comment]
did you manage to test with the console config option? If this happens again, can you provide me with the logs (not just the error message, that unfortunately gives me not much) . Thanks

**Comment by IsmaelMartinez** [comment]
Closing due inactivity, please come back with more info if this happens again and we can reopen it. Thanks!

**Comment by ismagulb** [comment]
Thanks Ismael for driving this! Right, I've run 1.9.2 with --webDebug --logConfig=console, the issue didn't occur anymore.

**Comment by IsmaelMartinez** [comment]
Glad to hear that works for you. Maybe there is something on the electron-log that was driving this issue, but hopefully is gone.

I keep it closed but will reopen (or link it) if I see others start to report it.
