### ISSUE TITLE
When simultaneously connected on android and Linux, many discussion elements are not displayed

### ISSUE THREAD

**Issue by EricV** [IsmaelMartinez/teams-for-linux#1368]
When simultaneously connected on android and Linux, many discussion elements are not displayed

**To Reproduce**

Started a discussion with a contact today on PC. Most of its answer were not displayed in Linux version but correctly on android. If writing things myself on android, it did not appear.

If I clode and restart, then I get the full exchange. 

**Expected behavior**
See all exchanged things on both displays.

**Desktop (please complete the following information):**
 - OS: Linux
 - Installation package deb
 - Version 1.9.0
 - 
dpkg -s teams-for-linux 
Package: teams-for-linux
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 285661
Maintainer: Ismael Martinez <ismaelmartinez@gmail.com>
Architecture: amd64
Version: 1.9.0
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
Recommends: libappindicator3-1
Description: Teams for Linux
  Unofficial Microsoft Teams client for Linux using Electron. It uses the Web App and wraps it as a standalone application using Electron.
License: GPL-3.0-or-later
Vendor: Ismael Martinez <ismaelmartinez@gmail.com>
Homepage: https://github.com/IsmaelMartinez/teams-for-linux

**Additional context**
Was working correctly before 1.9.0

**Comment by IsmaelMartinez** [comment]
Hi @EricV , can you try cleaning the cache and starting the application again? sometimes when we increase the electron version number issues like this one (or failing to load screens) happen. I guess due corrupt cache. 

Yo should be able to do it just by right click on the icon (and quit cleaning cache) or just be removing the whole config folder https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#config-folder-locations

**Comment by EricV** [comment]
Tried quit and clean storage. I had to login again but still no change. I can remove the whole folder but will need to reconfigure a few things...

**Comment by EricV** [comment]
Did rm -rf .config/teams* ,no change. Exactly the same behavior. I'm affraid there is something more than just a cache issue.

**Comment by IsmaelMartinez** [comment]
ok, just to see if it is not a browser/MS issue, can you check if you get the same issue in the browser? https://teams.microsoft.com/v2

**Comment by EricV** [comment]
Bad news : I had simultaneously teans-for Linux, the URL in microft-edge and the android version opened and  I did post something on android. It immediately appeared on the microsoft edge web version, and not on teams-for-linux. One minute later it is still not displayed on teams-for-linux.

**Comment by IsmaelMartinez** [comment]
that is strange, can you put your config file (if you got any) and the logs?

**please redact any sensitive info**

The changes from 1.8.0 to 1.9.0 should not affected this area, but who knows. Looking at the logs maybe helps. 

Try also previous versions to see if any is working. You might be able to run them without install using the tar.gz or AppImage (just to test).

Otherwise try a different packaging system if possible, but that is normally not the issue as deb or rpm normally do the job better than other packaging systems.

Let me know what you find to see if there is anything in the app. I suspect this is a limited issue to you as otherwise there would be a lot of people complaining 😄

**Comment by EricV** [comment]
Looked at the log. Did not see anything special. Will try to run a ^revious version if I manage to find one. Thanks for the support anyway.

**Comment by EricV** [comment]
This is fixed with 1.9.1. Let you find what you did...

**Comment by IsmaelMartinez** [comment]
If you aren't using `disableGpu` option, nothing really changed, but I am glad is working again for you. Maybe some MS issues, but glad to heard it all worked. 

You can see the changes between versions in here https://github.com/IsmaelMartinez/teams-for-linux/compare/v1.9.0...v1.9.1 

Mostly REAME changes 😄
