### ISSUE TITLE
We are having trouble loading your messages. Try refreshing

### ISSUE THREAD

**Issue by coelhogonzalo** [IsmaelMartinez/teams-for-linux#1374]
**Describe the bug**
When I open teams I get the following message "We are having trouble loading your messages. Try refreshing"

**To Reproduce**
1. Open Teams for Linux

**Expected behavior**
The web version of Teams works as always.

**Screenshots**
![image](https://github.com/user-attachments/assets/17e78d8a-238f-44b8-b977-57d5dcc7f894)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - Installation package: Snap
 - Version 1.9.1

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --logConfig='{}'

No config file found, using default values
all good with appLogLevels you aren't using them
Initialising logger with config: "{}"
Logger initialised with transports: {}
08:28:55.110 › File logging at /home/gonzalocoelho/snap/teams-for-linux/655/.config/teams-for-linux/logs/main.log with level silly
08:28:55.113 › Console logging enabled with level silly
08:28:55.114 › Logger initialised
08:28:55.114 › configPath: /home/gonzalocoelho/snap/teams-for-linux/655/.config/teams-for-linux
08:28:55.115 › configFile: {}
dbus-send: /snap/teams-for-linux/655/lib/x86_64-linux-gnu/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.12.20' not found (required by dbus-send)
08:28:55.257 › App already running

(teams-for-linux:650599): Gtk-WARNING **: 08:28:55.299: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(teams-for-linux:650599): Gtk-WARNING **: 08:28:55.307: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(teams-for-linux:650599): Gtk-WARNING **: 08:28:55.309: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name

(teams-for-linux:650599): Gtk-WARNING **: 08:28:55.593: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(teams-for-linux:650599): Gtk-WARNING **: 08:28:55.600: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(teams-for-linux:650599): Gtk-WARNING **: 08:28:55.602: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
cp-frontend $


```

*IMPORTANT:* Ensure that you mask any sensitive information before posting the output.

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi, thanks for reporting.

Is this a new issue or your 1st time using teams-for-linux? Can you try cleaning the cache (right click o the icon and click the menu option) and see if then works?

Otherwise try another packaging system. Snap can be a bit "iffy" sometimes, and the cache sometimes get corrupt creating that sort of issues.
