### ISSUE TITLE
system crash when clicked on raise hand

### ISSUE THREAD

**Issue by arvindautar** [IsmaelMartinez/teams-for-linux#1375]
**Describe the bug**
In a meeting when clicking on raise hand my systenm crashed and the entire background green and the system froze

**To Reproduce**
1. Go to '.teams meeting.'
2. Click on '.raise hand.'

**Expected behavior**
system not crashing

**Screenshots**

**Desktop (please complete the following information):**
Linux gebruiker-pc 6.10.4-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Aug 11 15:32:50 UTC 2024 x86_64 GNU/Linux
gebruiker@gebruiker-pc:~$ cat /etc/os
os-release  ostree/     
gebruiker@gebruiker-pc:~$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="40 (Forty)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Forty)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13

 - Installation package flatpack
 - Version 1.9.0

**Debug**
           PID: 20105 (teams-for-linux)
           UID: 1000 (gebruiker)
           GID: 1000 (gebruiker)
        Signal: 6 (ABRT)
     Timestamp: Tue 2024-08-20 20:35:01 CEST (1 day 17h ago)
  Command Line: /app/teams-for-linux/teams-for-linux
    Executable: /app/teams-for-linux/teams-for-linux
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-com.github.IsmaelMartinez.teams_for_linux-20081.scope
          Unit: user@1000.service
     User Unit: app-flatpak-com.github.IsmaelMartinez.teams_for_linux-20081.scope
         Slice: user-1000.slice
     Owner UID: 1000 (gebruiker)
       Boot ID: ad76f96398b142e58dbb9f3ef3e89734
    Machine ID: 30e7639d42ed465ebf62a84ba5fae9d1
      Hostname: gebruiker-pc
       Storage: /var/lib/systemd/coredump/core.teams-for-linux.1000.ad76f96398b142e58dbb9f3ef3e89734.20105.1724178901000000.zst (present)
  Size on Disk: 4.1M
       Message: Process 20105 (teams-for-linux) of user 1000 dumped core.
                
                Stack trace of thread 2:
                #0  0x00007f53cbdbae14 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x90e14)
                #1  0x00007f53cbd68dce n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x3edce)
                #2  0x00007f53cbd5083f n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2683f)
                #3  0x000055abc289a21b n/a (/app/teams-for-linux/teams-for-linux + 0x9f8c21b)
                #4  0x000055abbc112b12 n/a (/app/teams-for-linux/teams-for-linux + 0x3804b12)
                #5  0x000055abbc2e0848 n/a (/app/teams-for-linux/teams-for-linux + 0x39d2848)
                #6  0x000055abbc2be7eb n/a (/app/teams-for-linux/teams-for-linux + 0x39b07eb)
                #7  0x000055abbc2beeee n/a (/app/teams-for-linux/teams-for-linux + 0x39b0eee)
                #8  0x000055abbca6d188 n/a (/app/teams-for-linux/teams-for-linux + 0x415f188)
                #9  0x000055abbc6cc2d6 n/a (/app/teams-for-linux/teams-for-linux + 0x3dbe2d6)
                #10 0x000055abbc6f2a6b n/a (/app/teams-for-linux/teams-for-linux + 0x3de4a6b)
                #11 0x000055abbc6f218a n/a (/app/teams-for-linux/teams-for-linux + 0x3de418a)
                #12 0x000055abbc6f11e5 n/a (/app/teams-for-linux/teams-for-linux + 0x3de31e5)
                #13 0x000055abbc713b5d n/a (/app/teams-for-linux/teams-for-linux + 0x3e05b5d)
                #14 0x000055abba9bf9f6 n/a (/app/teams-for-linux/teams-for-linux + 0x20b19f6)
                #15 0x000055abbaa47300 n/a (/app/teams-for-linux/teams-for-linux + 0x2139300)
                #16 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #17 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #18 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #19 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #20 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #21 0x000055abe0024965 n/a (n/a + 0x0)
                #22 0x000055abe001d097 n/a (n/a + 0x0)
                #23 0x000055abe0020f43 n/a (n/a + 0x0)
                #24 0x000055abe0017b5f n/a (n/a + 0x0)
                #25 0x000055abe001dfe8 n/a (n/a + 0x0)
                #26 0x000055abe0031ffc n/a (n/a + 0x0)
                #27 0x000055abe0035a85 n/a (n/a + 0x0)
                #28 0x000055abe003585a n/a (n/a + 0x0)
                #29 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #30 0x000055abe0026e84 n/a (n/a + 0x0)
                #31 0x000055abe0028873 n/a (n/a + 0x0)
                #32 0x000055abe0025e45 n/a (n/a + 0x0)
                #33 0x000055abe001e646 n/a (n/a + 0x0)
                #34 0x000055abe0031ffc n/a (n/a + 0x0)
                #35 0x000055abe0035a85 n/a (n/a + 0x0)
                #36 0x000055abe003585a n/a (n/a + 0x0)
                #37 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #38 0x000055abe0026e84 n/a (n/a + 0x0)
                #39 0x000055abe0028873 n/a (n/a + 0x0)
                #40 0x000055abe0025e45 n/a (n/a + 0x0)
                #41 0x000055abe001e646 n/a (n/a + 0x0)
                #42 0x000055abe0031ffc n/a (n/a + 0x0)
                #43 0x000055abe0035a85 n/a (n/a + 0x0)
                #44 0x000055abe003585a n/a (n/a + 0x0)
                #45 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #46 0x000055abe0026e84 n/a (n/a + 0x0)
                #47 0x000055abe0028873 n/a (n/a + 0x0)
                #48 0x000055abe0025e45 n/a (n/a + 0x0)
                #49 0x000055abe001e646 n/a (n/a + 0x0)
                #50 0x000055abe0031ffc n/a (n/a + 0x0)
                #51 0x000055abe0035a85 n/a (n/a + 0x0)
                #52 0x000055abe003585a n/a (n/a + 0x0)
                #53 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #54 0x000055abba9208ff n/a (/app/teams-for-linux/teams-for-linux + 0x20128ff)
                #55 0x000055abbaab3994 n/a (/app/teams-for-linux/teams-for-linux + 0x21a5994)
                #56 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #57 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #58 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #59 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #60 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #61 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #62 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                #63 0x000055abba91fd67 n/a (/app/teams-for-linux/teams-for-linux + 0x2011d67)
                
                Stack trace of thread 18:
                #0  0x00007f53cbdb5709 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x8b709)
                #1  0x00007f53cbdb8089 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x8e089)
                #2  0x00007f53cb8e9a30 n/a (/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.32 + 0xe9a30)
                #3  0x00007f53cdbf454c n/a (/app/lib/libzypak-preload-host-spawn-strategy.so + 0xba54c)
                #4  0x00007f53cdbf42b8 n/a (/app/lib/libzypak-preload-host-spawn-strategy.so + 0xba2b8)
                #5  0x00007f53cdbf4037 n/a (/app/lib/libzypak-preload-host-spawn-strategy.so + 0xba037)
                #6  0x00007f53cdbf1828 n/a (/app/lib/libzypak-preload-host-spawn-strategy.so + 0xb7828)
                #7  0x00007f53cdbe913f n/a (/app/lib/libzypak-preload-host-spawn-strategy.so + 0xaf13f)
                #8  0x000055abbe641190 n/a (/app/teams-for-linux/teams-for-linux + 0x5d33190)
                #9  0x000055abbe642bb0 n/a (/app/teams-for-linux/teams-for-linux + 0x5d34bb0)
                #10 0x000055abbe6266e5 n/a (/app/teams-for-linux/teams-for-linux + 0x5d186e5)
                #11 0x00007f53cbdb8e39 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x8ee39)
                #12 0x00007f53cbe409c4 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x1169c4)
                ELF object binary architecture: AMD x86-64

**Comment by IsmaelMartinez** [comment]
oh dear, that sounds like a strong power to crash your laptop by raising your hand. 

Can you start teams with the following commands and put the logs in here?

```
teams-for-linux --webDebug --logConfig='{}'
```

I suspect is a gpu issue, but the logs might give more info. If it is a hardware acceleration issue, you should be able to run the app with the following command without crashes:

```
teams-for-linux --disableGpu --logConfig='{}'
```

**Comment by arvindautar** [comment]
Hi Ismael,

I think your spot on with the GPU issue, recently Fedora 40 upgraded amd gpu to amd-gpu-firmware-20240811-2. I never had this crash before. I will try to start it with --disableGpu next time.

NOt sure if the logs are still relevant, but here they are:

usr/bin/flatpak run --branch=stable --arch=x86_64 --command=teams-for-linux --file-forwarding com.github.IsmaelMartinez.teams_for_linux --webDebug --logConfig='{}'
[2:0822/150836.782780:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Bestand of map bestaat niet
No config file found, using default values
all good with appLogLevels you aren't using them
Initialising logger with config: "{}"
Logger initialised with transports: {}
15:08:37.221 › File logging at /home/gebruiker/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux/logs/main.log with level silly
15:08:37.224 › Console logging enabled with level silly
15:08:37.225 › Logger initialised
15:08:37.225 › configPath: /home/gebruiker/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux
15:08:37.226 › configFile: {}
15:08:37.232 › Running under Wayland, switching to PipeWire...
LaunchProcess: failed to execvp:
xdg-settings
15:08:37.292 › App already running
[2:0822/150837.358822:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Bestand of map bestaat niet
[2:0822/150837.358918:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Bestand of map bestaat niet

**Comment by IsmaelMartinez** [comment]
Those logs also seem to indicate something wrong with your flathub install. Maybe try one of the other packaging options we have, so you know is around that area. https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.9.1

**Comment by IsmaelMartinez** [comment]
did you get any results with the disableGpu @arvindautar ?

**Comment by arvindautar** [comment]
Hi Ismael,

I wasn’t able to replicate the bug with version 1.9.1. It’s likely
resolved. I had the green screen popup randomaly another time, outside of
using teams. Fedora has had 3 updates ever since and it seems to be the
stable environment i am used too.

Thank you for your work and support. This issue can be closed.

Op do 29 aug 2024 om 10:17 schreef IsmaelMartinez ***@***.***
