### ISSUE TITLE
msteams URIs are not opened (for instance for online Microsoft Teams meetings) 

### ISSUE THREAD

**Issue by shoffmeister** [IsmaelMartinez/teams-for-linux#138]
msteams URIs - which are, for instance, produced by calendar invites for Microsoft Teams meetings - are not "opened". 

One example of such an msteams URI is
msteams:/l/meetup-join/19:meeting_MmQ5NmViYjktOGU5Zi00Mjc3LWFlNDAtYWZkMmZmZjM3MmE1@thread.v2/0?context=%7B%22Tid%22%3A%228947597c-56ab-40dc-8bc2-yyyyyyyyyyyyy%22%2C%22Oid%22%3A%224b885135-a86e-45d9-acdc-zzzzzzzzzzzz%22%7D&anon=true&deeplinkId=xxxxxxxxxx-5035-4a1e-a907-fe766d6a7161&launchAgent=join_launcher&type=meetup-join&directDl=true&msLaunch=true&enableMobilePage=true&fqdn=teams.microsoft.com

I extracted this URI from Chromium's internal handling of the calendar request, with some random redacting (xx, yy, zz) in the above sample.

Going through Firefox on Linux, and a (redacted) calendar event (for the above) of https://teams.microsoft.com/l/meetup-join/19%3ameeting_MmQ5NmViYjktOGU5Zi00Mjc3LWFlNDAtYWZkMmZmZjM3MmE1%40thread.v2/0?context=%7b%22Tid%22%3a%228947597c-56ab-40dc-8bc2-yyyyyyyyyy%22%2c%22Oid%22%3a%224b885135-a86e-45d9-acdc-zzzzzzzzzzz%22%7d I get the "open link with ..." xdg-open request.
Directing this request towards teams-for-linux (RPM, 0.2), brings the Teams client to front correctly, but does not switch to the online meeting session.

**Comment by shoffmeister** [comment]
Chromium on Linux handles the plain calendar invite (warning: redacted, changed UUID)  https://teams.microsoft.com/l/meetup-join/19%3ameeting_MmQ5NmViYjktOGU5Zi00Mjc3LWFlNDAtYWZkMmZmZjM3MmE1%40thread.v2/0?context=%7b%22Tid%22%3a%228947597c-56ab-40dc-8bc2-yyyyyyyyyy%22%2c%22Oid%22%3a%224b885135-a86e-45d9-acdc-zzzzzzzzzzz%22%7d fine.

**Comment by shoffmeister** [comment]
Regrettably, right now, I do not know how to produce a working calendar invite which can be used as a target for reproducing this on any other system.

**Comment by IsmaelMartinez** [comment]
Have you tried Ctrl+click ? There is a PR that might solve this also. You can test it and comment on it if it fixes your issue. Thanks!

**Comment by shoffmeister** [comment]
There is nothing to click inside the Microsoft Teams for Linux "fat" client.

I can launch the (raw) URL through the browser and the Microsoft Teams for Linux comes to front - but nothing happens inside.

Also, I am not aware of any means to directly browse to some URL (such as msteams://... ) inside the client.

**Comment by shoffmeister** [comment]
I am not set up to create local builds at the moment, I am afraid.
I'll be happy to revisit builds (beta releases?) which contain the PR you mentioned merged.

**Comment by IsmaelMartinez** [comment]
I think then what you are trying is part of the #89 . Closing as this is a duplicated feature request.
