### ISSUE TITLE
Failure to reconnect after suspend (permanent black window)

### ISSUE THREAD

**Issue by raul-klg** [IsmaelMartinez/teams-for-linux#1381]
**Describe the bug**

I run and use the application normally. Sometimes I close laptop lid and I go elsewhere. Laptop suspends to ram. When I open the laptop lid teams-for-linux reconnects correctly, but sometimes (like this time) it does not reconnect.

**To Reproduce**
1. Run application
2. Wait for connection and load.
3. Suspend to ram
4. Open and reconnect in a different network (mobile data or other WLAN)
5. See error

**Expected behavior**
After wake up from suspend to ram, the application should reconnect normally.

**Screenshots**

![t4l_waiting_for_network](https://github.com/user-attachments/assets/09d611bf-0b9c-4fb4-8f79-8698362d5678)

**Desktop (please complete the following information):**
 - OS: Debian bookwork
 - Installation package targz (tweaked for correct integration with plasma desktop)
 - Version 1.9.1

**Debug**

```
12:11:28.963 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:13:03.167 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:03.172 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:04.183 › Network test failed with method https
12:13:04.184 › Waiting for network...
12:13:04.185 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:04.187 › Network test failed with method https
12:13:04.188 › Waiting for network...
12:13:04.188 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:05.196 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:05.198 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:06.210 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:06.213 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:07.221 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:07.222 › Testing network using net.request() for https://teams.microsoft.com/v2/
12:13:07.425 › Network test successful with method https
12:13:07.431 › Network test successful with method https
<RED>12:13:09.495 › assignOnDidFailLoadEventHandler : {} - -21 - 
12:13:09.527 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'locked'
<Problem arises>
12:13:19.534 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:13:29.536 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:13:39.538 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
```

**Additional context**

It looks like the following line, in red, as an error I assume:
```
12:13:09.495 › assignOnDidFailLoadEventHandler : {} - -21 - 
```
may point out the problem

Thanks for your continuous effort on this application.

**Comment by IsmaelMartinez** [comment]
Hi,

It does look like it does detect the network changes, but we don't do anything around that. 

https://source.chromium.org/chromium/chromium/src/+/main:net/base/net_error_list.h;l=91

What happens if you click on the menu -> refresh? While it might be possible to trigger a refresh, it might not work as you might need a different onlineCheckMethod from here:

https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config

If the refresh just works, we can add another flag to refresh on did-fail-load if the code is in a list (or something similar)

**Comment by raul-klg** [comment]
Thanks for the reply. I had this situation again. Somehow I got to the menu bar and pressed reload, as you suggested. The application reload the page correctly and I could reuse the same application instance again.
BTW, this time I use the default onlineCheckMethod (no config.json) even though I can't tell just now what it exactly is.
HTH,

**Comment by IsmaelMartinez** [comment]
ok, we could add a trigger to refresh if we get that code ('-21') but I am not sure when I will have time to add that. I will add it as a config option, but hopefully the workaround does it for you (at the moment)

**Comment by raul-klg** [comment]
No worries and no rush here. I don't think this is an urgent issue, even less when we already have a workaround. Thanks for caring.

**Comment by raul-klg** [comment]
I have some more information related to this issue. In this case I resumed computer on the following day and also a network change was detected but the application did not reload as expected. I'm attaching a webdebug screenshot in case it helps:
![image](https://github.com/user-attachments/assets/bd93e741-4201-42d9-9e62-d07b72db2a14)

**Comment by IsmaelMartinez** [comment]
I will see if I can add that 'auto refresh if' option. I leave it open until I get time to implement it

**Comment by akorn** [comment]
FWIW, I used to get this relatively often with earlier versions, also after resuming (not necessarily a black screen; sometimes the Teams logo, with "something went wrong, please refresh" or similar underneath, but clicking "refresh" had no effect and I had to restart the app). However, I don't think I saw it happen in the past month or so.

**Comment by IsmaelMartinez** [comment]
I have this network method issue when jumping from my wifi to my repeater. Maybe is a different one but glad to hear things are better for you @akorn , and that the Ctrl-R works for you @raul-klg . Hope to work on some better handling of the network connection.

**Comment by IsmaelMartinez** [comment]
Hello! Can you test https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.1 ? I think that might solve the issue, but I might be all wrong. 

Otherwise I can also add that "trigger refresh if code 21" I was mentioning a few comments ago. Thanks

**Comment by IsmaelMartinez** [comment]
Closing this then. I never liked the previous way, and it is always nice to remove a config option, as we got far too many!!
