### ISSUE TITLE
Support for creating + using Custom Emojis

### ISSUE THREAD

**Issue by torbendury** [IsmaelMartinez/teams-for-linux#1382]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when my colleagues can slack around creating and spamming their own emojis while I can't. According to the [Microsoft Documentation](https://support.microsoft.com/en-us/office/use-custom-emoji-in-microsoft-teams-84feb1c4-6d2b-4ecd-8e55-a93c828fc53a), I should be able to, however I suspect the current `teams-for-linux` client doesn't seem to implement it.

**Describe the solution you'd like**

I want to be able to manage my organizations' emojis via `teams-for-linux`.

**Describe alternatives you've considered**

Cry in awe of not being able to party-parrot inside Teams.

**Additional context**

I've also tried it in my browser using `teams.microsoft.com` however it also won't work there.

**Comment by IsmaelMartinez** [comment]
Hi @torbendury, thanks fro the suggestion. 

We are wrapping around the web browser, so I am afraid this will work once Microsoft allows it to work on the website. 

I would ask them directly on their uservoice (or whatever name they call it now)

**Comment by torbendury** [comment]
Hi @IsmaelMartinez, thanks for your answer! I opened a feedback suggestion [here](https://feedbackportal.microsoft.com/feedback/idea/8eb03e9a-5a64-ef11-a4e6-000d3a02a3a1) by randomly choosing one portal out of the ~10 they offer. Should we keep this GH issue here open or close it?

**Comment by IsmaelMartinez** [comment]
Ok, I got some good news and bad news.

The good news is that this feature is already available in the web. The bad news is that is up to your administrator to add it.

Just ping your admin this page:
https://insider.microsoft365.com/en-us/blog/custom-emojis-and-reactions-in-microsoft-teams

If you still don't have it, it might just be that the roll-out hasn't reach your org, but I can confirm it works fine with my msteams version (in MacOS and using this electron app)

So, yey and sorry

**Comment by MarcGoekce** [comment]
PSA: If you see the custom animated emojis, but they are not moving in your teams but in your browser, go to:
`settings > apprearance and accessibility > Animations > Turn off animations > off`
