### ISSUE TITLE
Feature Request: Add Logfile option

### ISSUE THREAD

**Issue by karloff10** [IsmaelMartinez/teams-for-linux#1386]
It would be helpful to have the option of writing the application output to a log file.
There are already a option to adjust log level `appLogLevels`but you can currently not write it to a file.
For example, it happens that meetings have a notification about the start in the electron UI, but no notification arrives at the notification daemon of the os.

If there is an option to write program output to a file, you could react to events while parsing the log file with an other process.

Unfortunately `teams-for-linux 2>&1 >> logfile` is not really an option, as there can be problems here depending on the start method of teams-for-linux. For example, if you start it with a key combo in window managers like i3 there will be no log because of how its started by the wm.

**Comment by IsmaelMartinez** [comment]
Hi @karloff10. This should be already available. 

I added electron-log a few weeks ago and I think the default configuration already writes to a file.

https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config#logconfig-option

There might be some limitations as mentioned in the README.md file
