### ISSUE TITLE
Emulate Windows Hosting System

### ISSUE THREAD

**Issue by 3wweiweiwu** [IsmaelMartinez/teams-for-linux#1387]
**Is your feature request related to a problem? Please describe.**
My company IT enable 2 factor authentication. The authentication application we used only allow windows, Mac. For browser version of teams, I can emulate my browser as Windows. However, I cannot do the same in team for linux. As a result, I cannot use team client.

**Describe the solution you'd like**
Add a option to allow user to set for connection string so that we can emulate windows system.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by IsmaelMartinez** [comment]
you can set the chromeUserAgent as for the https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config , but I don't think that would solve mfa authentication if it uses security keys. 

There are other options in that config section, including the use of intune, or keys. Hope helps
