### ISSUE TITLE
The left settings, chat etc. window covers the half of the screen and it's not resonsive

### ISSUE THREAD

**Issue by linuxrulezgames** [IsmaelMartinez/teams-for-linux#1390]
**Describe the bug**
The left settings, chat etc. window covers the half of the screen when Teams is not maximized and it's not resonsive. The only way to fix it is to clear storige but after you exit Teams on the second start it's again like that. 

**To Reproduce**
1. Just start Teams

**Expected behavior**
The left pane should be responsive as it was after a few weeks.

**Screenshots**
![Screenshot_2024_02_09_14_48](https://github.com/user-attachments/assets/a65e48fd-1978-4a96-a52c-9da227888fb3)

**Desktop (please complete the following information):**
Operating System: Arch Linux 
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.6-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 32 × Intel® Core™ i9-14900KF
Memory: 62.6 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4090/PCIe/SSE2
Manufacturer: ASUS

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --logConfig='{}'
```
Terminal output:
https://pastebin.com/vafEqMaf

Teams browser debug console:
I don't know how to get it, there are too many elements and I don't know which one is needed but if you tell me I'll be happy to provide it.

**Comment by linuxrulezgames** [comment]
It should be as it used to be:
![Screenshot_2024_02_09_19_39](https://github.com/user-attachments/assets/3d8e49c8-c9ae-4f05-b53a-7e23c430a32e)
![Screenshot_2024_02_09_19_34-1](https://github.com/user-attachments/assets/e8c0ffd1-02c0-4de8-a67e-705e76db8626)

Now I just quit Teams and on the second start the problem is here. The left pane cannot be hidden and I tried hard:
![Screenshot_2024_02_09_19_34](https://github.com/user-attachments/assets/5f6be2a4-a435-4e70-8ad0-dbaea10dee0c)

**Comment by IsmaelMartinez** [comment]
Hi @linuxrulezgames , have you tried in the browser to see what you get? I suspect is a browser issue, not our app, but awaiting to see what you say, and we can investigate further.

**Comment by linuxrulezgames** [comment]
Which browser I should test? In Firefox it's ok and it's as it should be. It's not ok with Chromium.

**Comment by IsmaelMartinez** [comment]
This app uses electron to wrap around Chromium. What means the issue is probably on your Chromium configuration. As you say is unresponsive, I wonder if it is a gpu acceleration issue. Can you try --disableGpu on startup? There is more info on how to use config options in the config section https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config 

If that still doesn't help, I would check with the people that package this in arch https://aur.archlinux.org/packages/teams-for-linux and/or try on of the packaging options we provide, but if it is happening in Chromium, your problem is probably in there. Hope helps!

**Comment by linuxrulezgames** [comment]
Hello,
Thanks for your answer! 
I tried with `--disableGpu` but it doesn't help. I tried a clean Chromium profile and even uninstalled it completely and the problem is still here. If I ununstall Chromium where the app takes it from? I'm using the Appimage version if this is of some help. And Chromium is in the official repo, not in AUR but I don't think it matters given I don't have it even installed now. It's a backu browser and I don't need it really so I uninstalled it.

**Comment by linuxrulezgames** [comment]
Hello,
Just tried it on a clean Mint 22.0 install and it's the same - at first start it's ok and on the second start the problem is here so it's not an Arch problem.

**Comment by IsmaelMartinez** [comment]
Then it is maybe a ms teams issue. Worth reporting in there? Thanks

**Comment by linuxrulezgames** [comment]
Yes, it might be. I even tried older versions of the Appimage like 1.7.x and it's still there.
Does this doesn't on your end?
Can you point me where I should report it?
Thank you.

**Comment by IsmaelMartinez** [comment]
I think is either https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472 or https://techcommunity.microsoft.com/t5/microsoft-teams/bd-p/MicrosoftTeams , but isn't that clear where you should report it. 

The chat panel works fine for me. Show if it is full screen, but if I make the screen smaller it behaves as it should be (becoming just the icons when the screen is smaller)

**Comment by IsmaelMartinez** [comment]
oh, one thing to try is the scale factor. `teams-for-linux --force-device-scale-factor=1.1`. It might be related to the scale factor (tends to make responsiveness funny in some use cases) It might be something to do with it if is not working also in the browser. I would open the problem mentioning is in the browser, otherwise they will not even bother to reply. Hope helps and that you find a solution

**Comment by linuxrulezgames** [comment]
Unfortunately `--force-device-scale-factor=1.1` doesn't help. I have to make the window very small to hide the chat windows and I don't know why it's just me...

Thank you very much for your help, appreciated!
