### ISSUE TITLE
Teams crash on download of a zip file

### ISSUE THREAD

**Issue by pebueno** [IsmaelMartinez/teams-for-linux#1394]
**Describe the bug**
When I try to download a .zip file from any Teams chat, I get disconnected from the call and the app restart.

**Desktop:**
 Using Pop!_OS 22.04 LTS, kernel 6.6.10-76060610-generic.

**Comment by IsmaelMartinez** [comment]
can you fill the template please? there are too many variables to take in to account to be able to help you. Thanks
