### ISSUE TITLE
The organizational structure is displayed abnormally

### ISSUE THREAD

**Issue by rangerzhou** [IsmaelMartinez/teams-for-linux#1397]
The organizational structure is displayed abnormally, the parent ogranizational cannot be displayed
Version：1.10.0
OS：Ubuntu 20.04

Screenshot 1
![2024-09-06_13-30](https://github.com/user-attachments/assets/460875d3-1619-4462-b7d4-4a6dd4c7f98d)

Screenshot 2
![2024-09-06_14-33](https://github.com/user-attachments/assets/5963e3cf-9c9e-4a71-aea6-e0159754c7d2)

**Comment by IsmaelMartinez** [comment]
Hi @rangerzhou , this would be a MS teams issue, not this app. Please report to MS. Thanks

**Comment by rangerzhou** [comment]
> Hi @rangerzhou , this would be a MS teams issue, not this app. Please report to MS. Thanks

Thanks, now is ok
