### ISSUE TITLE
FATAL:credentials.cc(127)] Check failed: . : Permission denied (13)

### ISSUE THREAD

**Issue by chWagnr** [IsmaelMartinez/teams-for-linux#1401]
**Describe the bug**
Teams for Linux does not start. Getting this error when calling from terminal: 

```
[303386:0910/165234.028885:FATAL:credentials.cc(127)] Check failed: . : Permission denied (13)
Trace/breakpoint trap (core dumped)
```

**To Reproduce**
1. Open Terminal
2. enter 'teams-for-linux'
3. See error

**Expected behavior**
Teams for Linux should start/open

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS
 - Installation package deb
 - Version 1.10.1

**Additional context**
Since the upgrade from Ubuntu 22.04 to 24.04.1 this error message occurs. I removed (purge) the package, installed different versions or rename the .config folder with no success.

**Comment by IsmaelMartinez** [comment]
I think this is an OS issue. Checking on stackoverflow seems to indicate is some sort of issue with your root/user permissions.

You will probably have more luck asking in there tbh.

https://stackoverflow.com/questions/76165512/fatalcredentials-cc127-check-failed-permission-denied-13-trace-breakpo

(and this [post](https://bbs.archlinux.org/viewtopic.php?id=258632)).

Hope helps. Closing as it is not app related.

**Comment by chWagnr** [comment]
@IsmaelMartinez thank you

setting `kernel.apparmor_restrict_unprivileged_userns=0` worked

**Comment by IsmaelMartinez** [comment]
Glad to hear and thanks for sharing what worked for you. That can help others in the future. Cheers!

**Comment by Varuna3656** [comment]
> @IsmaelMartinez thank you
> 
> setting `kernel.apparmor_restrict_unprivileged_userns=0` worked

This works only once for me. After restart again you'll have to do run this command

**Comment by IsmaelMartinez** [comment]
Have you check if the apparmour solution in https://github.com/IsmaelMartinez/teams-for-linux/issues/1426 works for you? This is a Ubuntu change that is affecting all Electron apps, not only us. Creating an apparmour profile for the app should solve your problem going forward.
