### ISSUE TITLE
Unable to open multiple windows

### ISSUE THREAD

**Issue by ziabytes** [IsmaelMartinez/teams-for-linux#1402]
**Describe the bug**
Unable to open multiple windows

**To Reproduce**
Steps to reproduce the behavior (in Ubuntu):
1. Right click icon in taskbar
2. Click on 'New Window'
3. See error

**Expected behavior**
Opens a new window of Teams application.

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS

 - Installation package [flatpak]
 - Version [1.10.1]

**Comment by IsmaelMartinez** [comment]
Hi @ziabytes, we don't support multiple windows. Closing as it is not an issue.
