### ISSUE TITLE
Setting for disabling automatic mic sensitivty adjustment

### ISSUE THREAD

**Issue by dvbeek** [IsmaelMartinez/teams-for-linux#1404]
**Is your feature request related to a problem? Please describe.**
My microphone input level gets reduced constantly by the app, even though I would like to control it myself.
It gets reduced to a level where no one in the call can hear me, so this is not very practical.

I'm using this app (and love it by the way, thanks for making Teams workable again :smile:), but I'm not sure if this is fixable here.

**Describe the solution you'd like**
I would like a possibility to disable automatic adjustment of the microphone sensitivity.

**Additional context**
On the Windows-app, it would look like this:
![image](https://github.com/user-attachments/assets/3ddda073-51f3-4c9e-8a2d-0ae27139fbbf)

**Comment by IsmaelMartinez** [comment]
Hi @dvbeek , have you tried the disableAutogain option https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config ?

**Comment by IsmaelMartinez** [comment]
Closing. Come back with more info if disableAutogain didn't work. Trying to get the backlog under control. Thanks!
