### ISSUE TITLE
Disable GPU ownership of dGPU?

### ISSUE THREAD

**Issue by waltercool** [IsmaelMartinez/teams-for-linux#1408]
Is it possible to provide a way to avoid using dGPU for Teams?

By some reason, by opening MS Teams, my dGPU card is being in use. It has the same behavior if I use DRI_PRIME=0 at Flatpak Env.

Not sure if a bug or a feature, so adding this as a Feature Request

dGPU normally: D3cold state
![Screenshot_20240913_134029](https://github.com/user-attachments/assets/3ec8f3c9-89e2-4b86-8479-24dddbd4d7ce)

dGPU when I open MS Teams: D0 state
![Screenshot_20240913_134118](https://github.com/user-attachments/assets/3e5ab750-277f-43da-b832-2872e6ef65c3)

I'm assuming this is something from ElectronJS, but if wants to use GPU acceleration, then it should use only the default GPU instead. Right now it's using both. iGPU and dGPU.

Current version: 1.10.2
Node: 20.15.1
v8: 12.4.254.20-electron.0
electron: 30.4.0
chrome: 124.0.6367.243

**Comment by waltercool** [comment]
FYI will keep this as related: https://github.com/electron/electron/issues/41389

There are ways to prevent this looks like, but involves disabling the whole GPU acceleration.

**Comment by IsmaelMartinez** [comment]
Hi @waltercool , if you want to play with chrome flags, we do support them. I believe there is some info in the config options.

**Comment by waltercool** [comment]
Closing issue, it's connected to the dGPU, but looks like doesn't draw any power at normal use

**Comment by IsmaelMartinez** [comment]
Did you try with the --disableGpu config option? https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config That should disable the GPU acceleration and might make your card behave.

**Comment by waltercool** [comment]
> Did you try with the --disableGpu config option? https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config That should disable the GPU acceleration and might make your card behave.

Yep, it does nothing, it still binds the GPU, but seems like the D3cold still happens.

I can see all my electron-based apps connected to GPU, but not actually using it.

sh-5.2# cat /sys/bus/pci/devices/0000:03:00.0/power_state
D3cold

**Comment by waltercool** [comment]
Just a small update about this.

I been getting the same behavior again using kernel 6.14+, likely happened with some previous kernels too, and disableGpu works perfect for me.

It still wakes up GPU one time at start, but then goes back to D3cold.

For anyone experiencing the same issue:

Edit the config.json as explained here https://github.com/IsmaelMartinez/teams-for-linux/tree/main/app/config, then add disableGpu there, like my config:

```
{
        "spellCheckerLanguages": [
                "en"
        ],
        "disableGpu": true
}
```
