### ISSUE TITLE
Tray icon is missing padding

### ISSUE THREAD

**Issue by Ubiquitine** [IsmaelMartinez/teams-for-linux#141]
**Is your feature request related to a problem? Please describe.**
Tray icon is missing some padding, so it looks larger then the rest of tray icons and also sticked to the neighbors.
**Describe the solution you'd like**
Add some padding to the tray icon

![image](https://user-images.githubusercontent.com/3274951/58451626-cab40500-8146-11e9-9f9c-482c89420642.png)

**Comment by julian-alarcon** [comment]
Hi @Ubiquitine . Can you describe your system? I'm using Ubuntu 18.04 with the communitytheme (https://snapcraft.io/communitheme) and I see no issues, a padding is in place.

![image](https://user-images.githubusercontent.com/30119472/58493157-f1b70a80-8137-11e9-819b-f7a438f67c17.png)

**Comment by Ubiquitine** [comment]
I have Kubuntu 18.04 with default Kubuntu theme. 
I've added 5% padding to app/assets/icons/icon-96x96.png and now it looks better. 
![icon-96x96](https://user-images.githubusercontent.com/3274951/58523236-4ae57380-81f6-11e9-84de-ca295210cd58.png)
![image](https://user-images.githubusercontent.com/3274951/58523268-65b7e800-81f6-11e9-968b-f8472eea1b61.png)
I would make it 7% even...
I used imagemagic BTW.

**Comment by julian-alarcon** [comment]
Keep in mind that this may affect other Distros/Desktops.

If you think that is possible to add this changes without affecting other current working scenarios please work on it!

**Comment by IsmaelMartinez** [comment]
Worth checking the previous image and see if there was a padding. Adding a small one (a pixel or 2) might be a good compromise for all the envs.

**Comment by IsmaelMartinez** [comment]
Added bug and enhancement as is sort of an UI bug... But not really a bug, as nothing is broken.

**Comment by IsmaelMartinez** [comment]
Ok, previous image didn't had a padding https://raw.githubusercontent.com/IsmaelMartinez/teams-for-linux/c0359beb805be974121e475fa6de5e4779c22adf/build/icons/96x96.png so I assume this is either a configuration in your system or something else. 

Can you let us know what is the package that you are using? if snap, can you try deb (or the other way round otherwise)

Thanks.

**Comment by Ubiquitine** [comment]
I'm using deb packaging.
I tried snap with same result.
This might be related to my Plasma appearance configuration and theme, at least regarding panel height, but horizontal padding should not be affected.
Also, I'm not sure which icon is displayed in systray, but the issue with padding was fixed for me when I added padding to app/assets/icons/icon-96x96.png .

**Comment by IsmaelMartinez** [comment]
@Ubiquitine , could you try version 0.2.0 and see if you had the same issue with the spacing?

**Comment by IsmaelMartinez** [comment]
I am going to be closing this as I don't think is a app issue. Meaning smells pretty related to your system configuration
