### ISSUE TITLE
Camera Flickering with Wayland on Electron 30.*

### ISSUE THREAD

**Issue by pschichtel** [IsmaelMartinez/teams-for-linux#1411]
**Describe the bug**
In meetings with cameras the camera picture flickers (it looks like it partially interlaces a couple of previews frames with the current one).

This only happens when setting `ELECTRON_OZONE_PLATFORM_HINT=auto` for teams-for-linux. It doesn't happen with xwayland it also doesn't happen in chromium 129 with wayland.

I have two independent systems that observe this, both are on Arch with KDE and have Intel graphics (`Intel(R) Core(TM) Ultra 7 155U`).

**To Reproduce**
1. Set `ELECTRON_OZONE_PLATFORM_HINT=auto`
2. Start teams-for-linux
3. Join a call with someone that has the camera active
4. Let them waive at the camera

I assume this might behave differently on differently on different GPUs and/or desktops

**Expected behavior**
Clean video feeds

**Screenshots**
I don't have screenshots, but it's very noticable when it happens, especially with fast horizontal movement.

**Desktop (please complete the following information):**
 - OS: Arch (non-testing)
 - Installation package: AUR teams-for-linux package (fyi, I'm one of the maintainers)
 - Version: 1.10.2

**Additional context**

Given that no issue exists in chromium 129 and that it seems to be wayland/ozone specific, I just tried building teams-for-linux with electron 32.1.2 and that actually fixes the issue.

**Comment by IsmaelMartinez** [comment]
I will see what I can do to migrate to a newer version. I thought there are
a few breaking changes, but they might not be as breaking as I
initially thought.

**Comment by pschichtel** [comment]
teams took a short while (10-20 seconds) to load up the first time with the new version, but worked without issuer afterwards, however I'm not using any special features

**Comment by IsmaelMartinez** [comment]
I have put a pre-release with version 32.1.2 (https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.0).

As it is a big(ish) version jump, I will leave it a few days for people to test. It is sometimes normal to see a delay on the initial startup when big version jumps of electron. Sometimes people need to clean their cache or even the .config folder.

Thanks again for reporting

**Comment by pschichtel** [comment]
thanks, I the version running on my machine now, looks good so far. I'll report back if I see issues

**Comment by SRCGremlin** [comment]
Many thanks, confirm the issues with teams-for-linux on Arch w/ presentations/ RDP session recording frames out-of-order are now completely resolved with the new pre-release version. These have been major issues present for a good 6 or more months. Fantastic. Thank you.

**Comment by IsmaelMartinez** [comment]
Great to hear and thanks you all at arch for handling the bundling process.  I wish snap and flathub did similar 😄 

I leave it a few more days but hopefully release it full by the end of the week, or early next week.

**Comment by IsmaelMartinez** [comment]
Ok, this is now live so I close it as complete. Thanks for your help and thanks @pschichtel for maintaining the AUR package.

**Comment by pschichtel** [comment]
I updated the package as well, thanks for your quick support!
