### ISSUE TITLE
[Feature Request] Join via Meeting-ID

### ISSUE THREAD

**Issue by fschaupp** [IsmaelMartinez/teams-for-linux#1412]
**Is your feature request related to a problem? Please describe.**

Currently, when I want to join a Microsoft Teams meeting from within the Linux desktop application, I need to access the meeting by clicking on a meeting invite link that was sent to me via email or another method. This can be 
cumbersome if I don't have access to my email client at the time or if I simply forgot the link.

Additionally, as mentioned in issue #1370, there is already an existing workaround (installing a Firefox plugin to redirect the Teams link to msteams://) that only works for users with Mozilla Firefox installed and configured 
correctly. This solution still requires additional steps and might not be practical for everyone.

**Describe the solution you'd like**

I would like to see two additional options in the teams-for-linux application:

1. An option to join a Microsoft Teams meeting using only the Meeting ID and User PIN (or other authentication methods), allowing me to quickly look up the meeting details, enter the Meeting ID and PIN, and instantly join the 
meeting without needing to access any other apps or websites.
2. A simple input field, maybe in the tray icon menu, where I can manually paste the meeting invite link and have it automatically join the meeting

**Describe alternatives you've considered**

As mentioned earlier, installing a Firefox plugin (issue #1370) is an existing workaround that doesn't cover all users' needs and requires additional configuration. This feature request aims to improve the user experience for both 
new and existing teams-for-linux users.

**Additional context**

This feature would be particularly useful for Linux users who frequently participate in Microsoft Teams meetings from their desktop environment or especially if you are in a hurry to join the meeting. Having a seamless experience within the teams-for-linux application would greatly enhance our productivity and reduce frustration caused by the current workflow.

A further step would be to suggest, maybe one time only?, to install the e.g. Firefox plugin afterwards or on first launch.

**Comment by Thyrador** [comment]
> Additionally, as mentioned in issue #1370, there is already an existing workaround (installing a Firefox plugin to redirect the Teams link to msteams://) that only works for users with Mozilla Firefox installed and configured
> correctly. This solution still requires additional steps and might not be practical for everyone.

You can use similar ad-ons for chromium based browsers as well. Like [Redirector](https://chromewebstore.google.com/detail/redirector/ocgpenflpmgnfapjedencafcfakcekcd) for example.

You just add:
Include pattern: `^(https://)(teams.microsoft.com/l/meetup-join/)(.*)`
Redirect to: `msteams://$2$3`
Pattern type: `Regular Expression`

and done.
Your links now should open teams-for-linux instead of the teams web application.

**Comment by IsmaelMartinez** [comment]
There is a "Join with an ID" button in the calendar view.

![image](https://github.com/user-attachments/assets/10163882-4714-4277-9a9c-0b52428f39d3)

![image](https://github.com/user-attachments/assets/c79f6a88-71cc-47c7-8883-5d9d62b7afff)

I haven't use it but maybe you can give it a go?

**Comment by KPS-MWT** [comment]
> There is a "Join with an ID" button in the calendar view.
> 
> I haven't use it but maybe you can give it a go?

This works as designed, I think this FR can be closed.
