### ISSUE TITLE
Configure User-Agent to circumvent block?

### ISSUE THREAD

**Issue by cbotmk3** [IsmaelMartinez/teams-for-linux#1414]
Today I noticed T4L is not working any more, the sign-in page in my company says "You cannot access this right now" and Microsoft's error code is 53003. It seems like there is a new policy preventing me from logging in.

After some research, I found out:

- Login via Browser (Vivaldi / Chrome / Firefox) does also not work.
- Browser in Windows (Vivaldi) works, strange...
- When I use Vivaldi on Linux and spoof my user agent as "Chrome 122 on Windows", it works (I am using a browser extension to do this).

Can we somehow spoof the User Agent in teams-for-linux or make this configurable in a future release?
IMHO the problem is my company not allowing some user agents...

**Comment by cbotmk3** [comment]
Oops, I just found out there is already such an option, sorry! I will try that.

**Comment by cbotmk3** [comment]
It works using the following config:
`"chromeUserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"`

But I'm not sure if it's the Windows part or that the default UA is a too old Chrome version.

**Comment by IsmaelMartinez** [comment]
Hi @cbotmk3 , yes, it is probably your company policy trying to block you. 

You can also use the emulateWinChromiumPlatform option. I didn't add it but there is more info in here https://github.com/IsmaelMartinez/teams-for-linux/pull/1395

**Comment by NklsCh** [comment]
Hi, im currently on `1.11.2` and i think it might be broken again, the bypass doesnt work for me

**Comment by cbotmk3** [comment]
I'm on 1.11.3 and it still works.

**Comment by NklsCh** [comment]
> It works using the following config: `"chromeUserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"`

Did you wrote that in your config file in `.config/teams-for-linux/config.json` ?
