### ISSUE TITLE
Meeting window doesn't appear during group calls

### ISSUE THREAD

**Issue by WayneChangCA** [IsmaelMartinez/teams-for-linux#1417]
**Describe the bug**
The meeting window doesn't appear during group calls, but works fine for one-on-one calls.
The issue occurs only when I join an ongoing call.

**To Reproduce**
1. Go to any group chat
2. Ask a group member to initiate a call
3. Join the phone call
4. The call connects successfully, but the meeting window does not appear.

**Expected behavior**

The group call functions like a one-on-one call

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.1
 - Installation package deb
 - Version 1.9.6

**Debug**

Unhandled error/rejection {"isTrusted":true}
error @ v2/?clientexperience=t2:1
(anonymous) @ v2/?clientexperience=t2:1
656899-dfe6f4a6af3f990c.js:1 
        
        
       GET https://graph.microsoft.com/v1.0/organization/134b7bd0-df93-45b9-bb1c-4e2461753bed/serviceProvisioningInfo 403 (Forbidden)
timeoutMs @ 656899-dfe6f4a6af3f990c.js:1
s @ 656899-dfe6f4a6af3f990c.js:1
i @ 656899-dfe6f4a6af3f990c.js:1
c @ 656899-dfe6f4a6af3f990c.js:1
a @ 656899-dfe6f4a6af3f990c.js:1
p @ 656899-dfe6f4a6af3f990c.js:1
await in p (async)
g @ 656899-dfe6f4a6af3f990c.js:1
c @ 656899-dfe6f4a6af3f990c.js:1
(anonymous) @ 638918-1f740db6a52ef73d.js:1
ae @ 638918-1f740db6a52ef73d.js:1
await in ae (async)
se @ 638918-1f740db6a52ef73d.js:1
await in se (async)
(anonymous) @ 638918-1f740db6a52ef73d.js:1
he @ 638918-1f740db6a52ef73d.js:1
le @ 638918-1f740db6a52ef73d.js:1
de @ 638918-1f740db6a52ef73d.js:1
ue @ 638918-1f740db6a52ef73d.js:1
(anonymous) @ 552331-d2cc0c2c55b88be2.js:1
await in (anonymous) (async)
(anonymous) @ 552331-d2cc0c2c55b88be2.js:1
li @ 638637-20856706a13e593e.js:1
xs @ 638637-20856706a13e593e.js:1
ss @ 638637-20856706a13e593e.js:1
Hl @ 638637-20856706a13e593e.js:1
cs @ 638637-20856706a13e593e.js:1
Oa._executeBatchedUpdate @ core-essentials-38452c59347f1421.js:8
t.schedule.priority @ core-essentials-38452c59347f1421.js:8
execute @ async-entry-244a09efc491d125.js:30
execute @ async-entry-244a09efc491d125.js:30
(anonymous) @ async-entry-244a09efc491d125.js:30
wasmaec-worklet-v1.js:1 [Report Only] Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-ex1KZ87Fma9y5GXlucNIQA==' 'report-sample' https://statics.teams.cdn.office.net browser.events.data.microsoft.com local.teams.microsoft.invalid c1-powerpoint-15.cdn.office.net c4-powerpoint-15.cdn.office.net c5-powerpoint-15.cdn.office.net cdn.dev.fluidpreview.office.net cdn.fluidpreview.office.net ch5.fluidpreview.office.net dev.loop.microsoft.com powerpoint.cdn.office365.us res.cdn.office.net res-1.cdn.office.net res-2.cdn.office.net res-gcch.cdn.office.net res-sdf.cdn.office.net www.bing.com r.bing.com t.ssl.ak.dynamic.tiles.virtualearth.net dev.virtualearth.net whiteboard.office.com app.whiteboard.microsoft.com az725175.vo.msecnd.net lpcres.delve.office.com midgardbranches.blob.core.windows.net web.vortex.data.microsoft.com".

(anonymous) @ wasmaec-worklet-v1.js:1
(anonymous) @ wasmaec-worklet-v1.js:1
E @ wasmaec-worklet-v1.js:1
U @ wasmaec-worklet-v1.js:1
wasmdns-worklet-v1.js:1 [Report Only] Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'nonce-ex1KZ87Fma9y5GXlucNIQA==' 'report-sample' https://statics.teams.cdn.office.net browser.events.data.microsoft.com local.teams.microsoft.invalid c1-powerpoint-15.cdn.office.net c4-powerpoint-15.cdn.office.net c5-powerpoint-15.cdn.office.net cdn.dev.fluidpreview.office.net cdn.fluidpreview.office.net ch5.fluidpreview.office.net dev.loop.microsoft.com powerpoint.cdn.office365.us res.cdn.office.net res-1.cdn.office.net res-2.cdn.office.net res-gcch.cdn.office.net res-sdf.cdn.office.net www.bing.com r.bing.com t.ssl.ak.dynamic.tiles.virtualearth.net dev.virtualearth.net whiteboard.office.com app.whiteboard.microsoft.com az725175.vo.msecnd.net lpcres.delve.office.com midgardbranches.blob.core.windows.net web.vortex.data.microsoft.com".

**Comment by gwozniak** [comment]
Confirming  problem on Debian 12 and deb: teams-for-linux=1.10.2

**Comment by zeduperes** [comment]
I have this same issue, using Ubuntu 24.04

**Comment by WayneChangCA** [comment]
After some testing, I found that this issue also occurs in the web version of Teams, so it may not be a bug in the app. The problem might come from Teams itself.

**Comment by enzotorrs** [comment]
same issue on archlinux, version 1.10.2

**Comment by IsmaelMartinez** [comment]
Hi @WayneChangCA, thanks for reporting.

If this happens on the browser version, then we will be having the same behavior in our app. We are wrapping around the browser version and adding extra features, but this one would be flaky to support, and difficult to implement.

Apologies to all but this is a MS issue and should be reported on their uservoices/support/forums. Closing it.
