### ISSUE TITLE
When attempting to join a Microsoft Teams meeting, I get the following error: "...Make sure you're connected to the internet..."

### ISSUE THREAD

**Issue by miguelvallentte** [IsmaelMartinez/teams-for-linux#1419]
When attempting to join a Microsoft Teams meeting, you may encounter the following error:
"Sorry we couldn't connect your call. Make sure you're connected to the internet and try again."

This issue can occur even when you have a working internet connection.

Solution:
The problem can often be resolved by changing your DNS (Domain Name System) settings. Here's how to do it on both Linux and Windows systems:

For Linux (Ubuntu/Debian):

1. Open a terminal.
2. Edit the resolv.conf configuration file:
   ```
   sudo nano /etc/resolvconf/resolv.conf.d/head
   ```
3. Add the following lines:
   ```
   nameserver 8.8.8.8
   nameserver 8.8.4.4
   ```
4. Save and exit the file (Ctrl+X, then Y, then Enter).
5. Update the system's resolv.conf:
   ```
   sudo resolvconf -u
   ```
6. Verify the changes:
   ```
   cat /etc/resolv.conf
   ```

For Windows:

1. Open the Control Panel.
2. Go to Network and Internet > Network and Sharing Center.
3. Click on "Change adapter settings" on the left side.
4. Right-click on your active network connection and select "Properties".
5. Select "Internet Protocol Version 4 (TCP/IPv4)" and click "Properties".
6. Select "Use the following DNS server addresses".
7. Enter the following:
   Preferred DNS server: 8.8.8.8
   Alternate DNS server: 8.8.4.4
8. Click OK to save the changes.
9. Open Command Prompt as Administrator.
10. Run the following command to flush the DNS cache:
    ```
    ipconfig /flushdns
    ```

After making these changes, restart your Microsoft Teams application and try joining the meeting again. The connection issue should be resolved.

Note: The DNS servers used in this solution (8.8.8.8 and 8.8.4.4) are Google's public DNS servers. They are generally reliable and fast, but you can use other public DNS servers or your ISP's DNS servers if preferred.

If you continue to experience issues, please contact your IT support team or Microsoft Teams support for further assistance.

Citations:
[1] https://learn.microsoft.com/en-us/windows-server/networking/dns/troubleshoot/troubleshoot-dns-client
[2] https://www.ricmedia.com/tutorials/set-permanent-dns-nameservers-ubuntu-debian-resolv-conf
[3] https://learn.microsoft.com/en-US/windows-server/networking/dns/troubleshoot/troubleshoot-dns-server
[4] https://www.tecmint.com/set-permanent-dns-nameservers-in-ubuntu-debian/
[5] https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/manually-configuring-the-etc-resolv-conf-file_configuring-and-managing-networking
[6] https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/troubleshoot-dns-guidance
[7] https://answers.microsoft.com/en-us/microsoftedge/forum/all/dns-isnt-working-on-my-pc/86a6b382-2bf2-4263-b059-e816554a1897
[8] https://answers.microsoft.com/en-us/msteams/forum/all/dns-resolution-failed-microsoft-teams-network/ba79627c-d39f-421b-9d5e-afa770c8ac3a

**Comment by IsmaelMartinez** [comment]
Hi @miguelvallentte,

I suspect your network is blocking the network check we do.

Can you try the onlineCheckMethod with dns, native or none?

More info in:
https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config

**Comment by IsmaelMartinez** [comment]
closing as duplicate with https://github.com/IsmaelMartinez/teams-for-linux/issues/1405 and partly https://github.com/IsmaelMartinez/teams-for-linux/issues/1381 . I hope to improve that area/logic in the near future. Follow those issues instead and do report back with whether the onlineCheckMethod did work or not.
