### ISSUE TITLE
Add Sound notifications

### ISSUE THREAD

**Issue by Bican007** [IsmaelMartinez/teams-for-linux#142]
Thank you for all the great work. I use the teams for linux daily.

**Is your feature request related to a problem? Please describe.**
Do not get any sound notification for incoming messages, meeting invites etc. I have sound notifications enabled.

**Describe the solution you'd like**
To have sound notifications in the incoming messages. Notification sound be played.

**Describe alternatives you've considered**
Not available

**Comment by IsmaelMartinez** [comment]
I don't have/use sound notifications but it should be libnotify that deals with the notifications. 

Maybe check down that route. Not sure if electron needs to add anything to it. 

By the way, can you edit this bug using the templates (https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md). It helps for us not to ask questions repeatably.

**Comment by IsmaelMartinez** [comment]
It might be related to this... https://github.com/electron/electron/issues/7258

**Comment by Bican007** [comment]
I just realized that I'm running Wavebox for other MS Office365 apps (https://wavebox.io/) and I'm getting sound notifications from it.

**Comment by IsmaelMartinez** [comment]
They have probably implement it on top. I will put this as an enhancement and see if someone has the time to add it. Thanks for your request!

**Comment by Bican007** [comment]
Actually the sound notification for the meeting started event works. So I think we can close it now.

**Comment by IsmaelMartinez** [comment]
I don't use notifications but, if you are happy, then lets just close it. :) If someone else finds there is a general issue with notifications, we can reopen this or do the work another one. 

It might be that the issue was that you don't get notifications if the screen still focus, so they only work when you click minimize... electron is a bit funny with loosing focus.

**Comment by tunix** [comment]
Hi @IsmaelMartinez , thank you for this package! I'm able to see notifications just fine but there's no sound. I'm able to listen to Spotify and able to hear notification sounds with Slack app. Does Teams for Linux come with a sound file (to play with notifications)?

**Comment by IsmaelMartinez** [comment]
Hi @tunix, We don't have a sound file. We should be reusing whatever sound the web app does... but unfortunately, MS has an "issue" on that area: https://techcommunity.microsoft.com/t5/Microsoft-Teams/Audio-Notifications/m-p/386653
