### ISSUE TITLE
Screen Share doesn't work on first time (blurry picture), but it works on second time

### ISSUE THREAD

**Issue by andyrozman** [IsmaelMartinez/teams-for-linux#1421]
**Describe the bug**
When I share my screen, person on other side only gets blurry picture. If I cancel "share" and try again picture is ok. It doesn't happen always (sometimes people on other side see picture on first try).

**To Reproduce**
1. Start screen sharing

**Expected behavior**
Person on other side can see my screen.

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS
 - Installation package:  deb
 - Version: 1.10.2

**Comment by IsmaelMartinez** [comment]
Hi @andyrozman , 

Can you provide some logs? It could be due hardware acceleration (logs normally give a nice hint).

Another thing to try is if the 1.11.0 (pre-release) improves your situation. I have updated the version of electron on it, and sometimes electron people fixes this sort of issues (or break others).

Thanks for reporting.

**Comment by IsmaelMartinez** [comment]
closing due inactivity, do come back with more logs and we can re-open an have a further look. (trying to keep the backlog manageable)

**Comment by baderdean** [comment]
Same issue here with Manjaro on Plasma / X11. But what do you mean by logs?! Which software do you want logs from? I digged into ~/.config/teams-for-linux but didn't find any logs.

**Comment by IsmaelMartinez** [comment]
Hi @baderdean , Can you open a new issue? The whole screensharing functionality has been re-written in 2.3.0 (pre-release) so this might not be an issue anymore.

That version do have a few other issues that I want to fix before it is stable.

**Comment by dlecan** [comment]
@IsmaelMartinez 

> The whole screensharing functionality has been re-written in 2.3.0 (pre-release) so this might not be an issue anymore.

I have many issues with blurred screen sharing with 2.2.1 (and earlier), but they're gone with 2.5.2, thanks.
I reverted to 2.2.1 as 2.5.2 has too many regressions, but you're on the way to fix blurred screen sharings!

**Comment by yasntrk** [comment]
Same issue

<img width="305" height="222" alt="Image" src="https://github.com/user-attachments/assets/e7ac9fb7-89dd-4c68-9f94-f9e5943e4f51" />

**Comment by IsmaelMartinez** [comment]
Hi @yasntrk , this should be fixed in the latest pre-release. I might make it stable soon. Thanks for reporting
