### ISSUE TITLE
The SUID sandbox helper binary was found, but is not configured correctly.

### ISSUE THREAD

**Issue by ondrej-simon** [IsmaelMartinez/teams-for-linux#1427]
**Describe the bug**

After updating to version 1.11.0, the following error appears, when trying to launch the application: 

[25746:0930/073047.604531:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/teams-for-linux/chrome-sandbox is owned by root and has mode 4755.

Seems to be caused by the Electron update and related to this issue: https://github.com/electron/electron/issues/42510

**To Reproduce**

1. Install Teams for Linux v1.11.0 on Ubuntu 24.04.
2. Try to launch the application.
3. Error.

**Expected behavior**

I launch the application and it launches.

**Desktop:**
 - OS: Ubuntu 24.04.1 LTS
 - Installation package: deb
 - Version: 1.11.0

**Debug**

Does not output anything extra besides the error mentioned at the beginning.

**Additional context**

Can be worked around by lifting Ubuntu's restrictions: https://github.com/electron/electron/issues/42510#issuecomment-2171583086, I am however pretty sure this is not the correct solution.

**Comment by IsmaelMartinez** [comment]
Thanks for reporting. I think is ok to do the 'no-sandbox' as modern Linux's now deal with sandboxing at a process level, but I need to read more about it before I just add it to everyones.

**Comment by piesarmin** [comment]
I've got this error last week.
I had to adapt the permissions of /opt/teams-for-linux/chrome-sandbox to 4755.
After the last update the error reoccurred.
So I had to adapt that again.
I don't understand why this issue is closed although it still exists.

**Comment by IsmaelMartinez** [comment]
@piesarmin , this issue is duplicated by https://github.com/IsmaelMartinez/teams-for-linux/issues/1426 . It is an ubuntu change that affects all electron apps. https://github.com/IsmaelMartinez/teams-for-linux/issues/1426#issuecomment-2453340003 explains this in more details.
