### ISSUE TITLE
App not launching 

### ISSUE THREAD

**Issue by mmouhib** [IsmaelMartinez/teams-for-linux#1429]
**Describe the bug**

**To Reproduce**
1. click on the app icon
2. nothing happens

**Expected behavior**
The app opens either as a tray icon or a window

**Desktop (please complete the following information):**
 - OS: ubuntu 24.04
 - Installation package: deb
 - Version 1.11.0

**Comment by IsmaelMartinez** [comment]
Hi @mmouhib , it is probably https://github.com/IsmaelMartinez/teams-for-linux/issues/1426 .

**Comment by mmouhib** [comment]
yes, [this](https://github.com/IsmaelMartinez/teams-for-linux/issues/1426#issuecomment-2381363601) solved it

**Comment by IsmaelMartinez** [comment]
closing. We might do some more work on the other ticket.
