### ISSUE TITLE
Don't change icon

### ISSUE THREAD

**Issue by youknow16** [IsmaelMartinez/teams-for-linux#1432]
Could you please NOT change the icon on every update?
Since the app doesn't have a proper notification system, I have another code that regularly checks the icon and if it looks like there's a red notification number on it, sends me a signal.
Every time you change the icon or the location of the red dot, it breaks my system.

Here are some examples of the changes you make:

![teams-o](https://github.com/user-attachments/assets/e52785c1-3442-4dbd-83f0-8bb5e94fe06d)
![teams-old](https://github.com/user-attachments/assets/32216a12-c169-4e44-b13c-536c8b118abb)
![teamsold](https://github.com/user-attachments/assets/40695a36-4352-4daa-972d-c7e94827a6ba)
![teams](https://github.com/user-attachments/assets/f99920b4-bbbd-42b9-9151-9d494b415dc7)

**Comment by IsmaelMartinez** [comment]
Hi @youknow16 , I am sorry to hear this is causing you problems, but there was a legal dispute on the icon so I had to change it, or kill the app. 

I am not planning to make a change on the icon for as long as I can. Hopefully years if not for ever. 

With regards the notifications, have you tried the other options available? Is the `notificationMethod` config option. 

The default is `web` but you can try `electron` that also has the `defaultNotificationUrgency` option. 

See https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config for more info.

Hope helps and closing as hopefully this icon is there to stay for ever... or until MS do a proper linux client.
