### ISSUE TITLE
2FA authentication window does not show up

### ISSUE THREAD

**Issue by upcycleist** [IsmaelMartinez/teams-for-linux#1433]
**Describe the bug**
I changed my settings for the microsoft account to another 2FA method (YubiKey).
I logged out from the microsoft account and restarted ms-teams.
When I want to login, I type in my account e-mail and go on.
I guess a window should open now where I can enter my PIN and the Token to get access to the account, but nothing shows up.

After a while the process recognized, that something is wrong and offered me to use my password.
Using this, I could log in myself just using the password.

**To Reproduce**
1. Enable a 2FA method using a YubiKey or something similar
2. Log out from ms-teams account
3. Restart ms-teams
4. Follow the login process, which will stuck after entering the account e-mail

**Expected behavior**
I would expect a pop up window to open where I can enter the login credentials (YubiKey Pin and access token)

**Screenshots**
Screenshot showing the last state where the process stucks.
No browser window is opened and nothing else happens for like 5 minutes.
![Bildschirmfoto vom 2024-10-04 09-52-55](https://github.com/user-attachments/assets/2abaff87-539a-4aa6-b2c8-bc703619c060)

**Desktop**
 - OS: Linux Ubuntu 22.04
 - Installation package snap via Ubuntu Software Center
 - Version 1415/24081700421

**Debug**
Debug execution lets teams quit after several seconds.

**Additional context**
Nothing to add.

**Comment by trigat** [comment]
I just wanted to add that I've never been able to get this functionality to work either.  I've tried several types of keys that normally work in the browser.  This same issue occurs when using Brave, Firefox, and Chrome as my default browser.  I use Ubuntu 22.04 and 24.04 LTS.

**Comment by IsmaelMartinez** [comment]
Unfortunately electron doesn't have support for yubikeys, so we are stuck
on this.

You can use certificates or intune if that works for you, but we can't do
anything about yubikeys and similar. Sorry about that!

**Comment by upcycleist** [comment]
@IsmaelMartinez, thanks for your reply.
That sounds not so good.
At the end I was able to use the password and authenticator app, but it would be nice to use the YubiKey version.

Nevertheless, I don't understand, why YubiKeys are not supported. The problem is the hardware communication between the YubiKey and the Electron "backend" at this point?

**Comment by IsmaelMartinez** [comment]
We use electron as our framework to wrap around the browser, and add some extra functionality. 

Electron just don't support this. They got an open issue so hopefully this gets priority on their side. 

I do keep an eye on it, but dunno when they will sort it. Apologies.

**Comment by IsmaelMartinez** [comment]
closing this as duplicated with https://github.com/IsmaelMartinez/teams-for-linux/issues/1299, https://github.com/IsmaelMartinez/teams-for-linux/issues/1166 and https://github.com/IsmaelMartinez/teams-for-linux/issues/1126.

This is the issue I keep an eye on https://github.com/electron/electron/issues/24573 Someone did reply from this area.

**Comment by trigat** [comment]
That's understandable.  Thank you for addressing this.
