### ISSUE TITLE
Multiple link widgets 'edits?)

### ISSUE THREAD

**Issue by IncandescentChrysalis** [IsmaelMartinez/teams-for-linux#1434]
**Describe the bug**
On inserting a link to a GitHub issue in a channel message, multiple widgets popped up.

Restarting Teams seems not to have an effect, hence does it not seem to be a display issue but rather recorded server-side? Or if so it is, the problem reproduces itself everytime that message is displayed.

It is important to note I edited the message several times, and each time new occurrences of the widgets were added to the list

**To Reproduce**
1. Insert a link to a GitHub issue in a channel message and send it
2. Edit the message, removing and adding the link again, and send it again
3. New occurrences of the widgets appear

**Expected behavior**
Well… :rofl: 

**Screenshots**
![teams_link-widget](https://github.com/user-attachments/assets/ac942d31-0ca9-4f3c-992f-46c47c0fc230)

**Desktop (please complete the following information):**
 - OS: `Debian 11 Bullseye`
 - Installation package: `deb`
 - Version: `1.11.0`

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --logConfig='{}'
```

*IMPORTANT:* Ensure that you mask any sensitive information before posting the output.

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi @IncandescentChrysalis , can you check if this also happens on the browser? Just to make sure this is not a MS issue instead of the app.  Thanks

**Comment by IsmaelMartinez** [comment]
nope, you should report it into the ms forums, but they do tend to be fairly slower to reply than us... even if they got thousands of people on them 😄 . Sorry!
