### ISSUE TITLE
Screen sharing (originating on linux) not visible in meetings, visible in direct calls

### ISSUE THREAD

**Issue by PauloGDPeixoto** [IsmaelMartinez/teams-for-linux#1437]
**Describe the bug**
If I join a meeting and someone using linux shares the screen, all I see is black.
If I call the same person directly, and they share the screen on that direct call, I can see the screen share as usual.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Installation package: rpm
 - Version 1.11.'

**Debug**
I tried to get debug logs, but nothing relevant to the issue showed up

**Comment by IsmaelMartinez** [comment]
Can you share the logs. This could be a gpu issue so a --disableGPU might solve this. Either that or permissions.

**Comment by PauloGDPeixoto** [comment]
Tried the flag, didn't work:

`$ teams-for-linux --disableGPU
No config file found, using default values
all good with appLogLevels you aren't using them
Initialising logger with config: "{}"
Logger initialised with transports: {}
14:14:37.094 › File logging at /home/ppeixoto/.config/teams-for-linux/logs/main.log with level silly
14:14:37.095 › Console logging enabled with level silly
14:14:37.095 › Logger initialised
14:14:37.095 › configPath: /home/ppeixoto/.config/teams-for-linux
14:14:37.095 › configFile: {}
14:14:37.299 › processArgs: [ '/opt/teams-for-linux/teams-for-linux', '--disableGPU' ]
14:14:37.300 › testing RegExp processArgs false
14:14:37.301 › testing RegExp processArgs false
14:14:37.302 › Testing network using net.request() for https://teams.microsoft.com
14:14:37.304 › Spellchecker is disabled!
14:14:47.744 › Network test successful with method https
14:14:48.054 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 2s, IdleState: 'active'
[294568:1011/141448.059645:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
14:14:48.392 › did-frame-finish-load {} true
14:14:48.393 › did-finish-load
14:14:49.816 › Badge count set to '0'
14:14:49.828 › Badge count set to '0'
14:14:50.976 › Badge count set to '0'
14:14:53.811 › Badge count set to '2'
14:14:53.881 › did-frame-finish-load {} false
14:14:56.254 › Badge count set to '2'
14:14:58.144 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:15:02.146 › Badge count set to '2'
14:15:08.146 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:15:18.147 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 4s, IdleState: 'active'
14:15:28.155 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 4s, IdleState: 'active'
14:15:38.157 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 2s, IdleState: 'active'
14:15:48.158 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:15:58.159 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:16:08.161 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 5s, IdleState: 'active'
14:16:18.164 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
^C14:16:27.782 › before-quit
14:16:27.782 › window close
14:16:28.265 › window closed
14:16:28.265 › will-quit
14:16:28.266 › quit
`

`$ teams-for-linux --disableGPU=true
No config file found, using default values
all good with appLogLevels you aren't using them
Initialising logger with config: "{}"
Logger initialised with transports: {}
14:16:31.852 › File logging at /home/ppeixoto/.config/teams-for-linux/logs/main.log with level silly
14:16:31.853 › Console logging enabled with level silly
14:16:31.853 › Logger initialised
14:16:31.854 › configPath: /home/ppeixoto/.config/teams-for-linux
14:16:31.854 › configFile: {}
14:16:32.035 › processArgs: [ '/opt/teams-for-linux/teams-for-linux', '--disableGPU=true' ]
14:16:32.036 › testing RegExp processArgs false
14:16:32.036 › testing RegExp processArgs false
14:16:32.037 › Testing network using net.request() for https://teams.microsoft.com
14:16:32.039 › Spellchecker is disabled!
14:16:42.446 › Network test successful with method https
14:16:42.878 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[296066:1011/141642.880992:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
14:16:43.185 › did-frame-finish-load {} true
14:16:43.186 › did-finish-load
14:16:44.613 › Badge count set to '0'
14:16:44.629 › Badge count set to '0'
14:16:45.941 › Badge count set to '0'
14:16:48.444 › Badge count set to '2'
14:16:48.674 › did-frame-finish-load {} false
14:16:52.992 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:17:03.353 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:17:13.355 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:17:23.357 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:17:33.358 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:17:43.359 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 10s, IdleState: 'active'
14:17:53.360 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 20s, IdleState: 'active'
14:18:03.362 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 2s, IdleState: 'active'
14:18:13.370 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 12s, IdleState: 'active'
14:18:23.372 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 6s, IdleState: 'active'
14:18:33.373 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 1s, IdleState: 'active'
14:18:43.376 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 8s, IdleState: 'active'
14:18:53.378 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 18s, IdleState: 'active'
14:19:03.384 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 28s, IdleState: 'active'
14:19:13.389 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
`

**Comment by IsmaelMartinez** [comment]
did you try with disableGpu (lowercase the p and u) I did put the wrong value initially but corrected it

**Comment by PauloGDPeixoto** [comment]
Tried now, same result. In any case, I also tested with ferdium (https://ferdium.org/), and the result is exactly the same: in direct calls, the screen sharing works, in a shared call, it doesn't. Only when the person sharing the screen is also using linux.

**Comment by IsmaelMartinez** [comment]
does this happen also just using the browser? Just curious if this is just
a MS issue. (We had quite a few lately)

**Comment by PauloGDPeixoto** [comment]
Tested with Edge, same issue.

**Comment by PauloGDPeixoto** [comment]
Another test I just did: after calling one linux user directly, and having him share the screen with me, as soon as I add another user to the call, the sceen sharing turns black.

**Comment by IsmaelMartinez** [comment]
dammit, I think this is a MS issue. Maybe report it into their uservoice/channel .

I think they are https://feedbackportal.microsoft.com/feedback and https://techcommunity.microsoft.com/t5/microsoft-teams/ct-p/MicrosoftTeams
