### ISSUE TITLE
Giphy GIFs are not displayed

### ISSUE THREAD

**Issue by SimonIT** [IsmaelMartinez/teams-for-linux#1438]
**Describe the bug**
GIFs from Giphy are not displayed

**Expected behavior**
The GIF is embedded

**Screenshots**
![image](https://github.com/user-attachments/assets/02641bfd-3193-4849-b96f-57c19fee2a75)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Installation package flatpak
 - Version 1.11.0

**Comment by IsmaelMartinez** [comment]
Hi,

I suspect this is a MS issue, or even a flatpack one. 

Can you check if you got that same behaviour in the browser? 


Can you try with another package type?

Thanks!

**Comment by SimonIT** [comment]
You're right, it's also not working in the normal web version

![image](https://github.com/user-attachments/assets/74689b86-77c1-47c7-ad07-64ec76b719d0)

**Comment by preslavpetkov** [comment]
I fixed it by turning `Optional connected experiences` `on`

<img width="1149" height="521" alt="Image" src="https://github.com/user-attachments/assets/2b6dab6f-e10d-445a-af2d-c26c11e081b5" />
