### ISSUE TITLE
Settings > presentation and accessibility = empty page

### ISSUE THREAD

**Issue by suther** [IsmaelMartinez/teams-for-linux#1439]
**Describe the bug**
In Settings > presentation and accessibility there is no content at all!

**Screenshots**
![image](https://github.com/user-attachments/assets/bbd6b7e1-ece9-42c1-bdb8-14ef48107f63)

Manjaro Linux, KDE,

**Comment by IsmaelMartinez** [comment]
Hi, can you try clearing the cache (close the app clearing cache menu option) and check you don't have the same issue in the browser.

**Comment by suther** [comment]
@IsmaelMartinez can you show where to find `close the app clearing cache menu option`? Don't find anything like that

**Comment by IsmaelMartinez** [comment]
From your message I don't really know what packaging system you are using, but you should be able to clean the cache following the instructions https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#no-history
