### ISSUE TITLE
Need to kill the process after closing the window

### ISSUE THREAD

**Issue by kw-at-oocl** [IsmaelMartinez/teams-for-linux#144]
In version 0.3.0, we found on our system we need to kill the process after closing the window.  If we don't kill the process, we can't restart Teams for Linux from the launcher.

- Open the app by: Go to Unity launcher, search 'teams', click on 'Teams for Linux'
(note Teams for Linux opens)
- log in
- Click on red x icon in the window title bar to close Teams for Linux
(Note that the app window closes)
- Open the app again by: Go to Unity launcher, search 'teams', click on 'Teams for Linux'
(Note that nothing happens.  No window opens.)
- Open terminal and enter:

`ps -x | grep teams`

(Note that 5 related processes are found)
` 3457 ?        Sl     1:36 /snap/teams-for-linux/15/teams-for-linux`

`3600 ?        S      0:00 /snap/teams-for-linux/15/teams-for-linux --type=zygote --no-sandbox`

` 3857 ?        Sl     0:00 /snap/teams-for-linux/15/teams-for-linux --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --service-request-channel-token=9971161000485549725`

 `3858 ?        Sl     0:02 /snap/teams-for-linux/15/teams-for-linux --type=renderer --no-sandbox --enable-features=SharedArrayBuffer --service-pipe-token=10248881762839586933 --lang=en-US --app-path=/snap/teams-for-linux/15/resources/app.asar --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TeamsforLinux/0.3.0 Chrome/69.0.3497.128 Electron/4.2.0 Safari/537.36 --node-integration=true --webview-tag=true --no-sandbox --background-color=#fff --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=10248881762839586933 --renderer-client-id=5 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101`

`31279 ?        Sl     0:10 /snap/teams-for-linux/15/teams-for-linux --type=renderer --no-sandbox --enable-features=SharedArrayBuffer --disable-gpu-compositing --service-pipe-token=4062787146318338780 --lang=en-US --app-path=/snap/teams-for-linux/15/resources/app.asar --user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TeamsforLinux/0.3.0 Chrome/69.0.3497.128 Electron/4.2.0 Safari/537.36 --enable-plugins --node-integration=false --webview-tag=false --no-sandbox --native-window-open --preload=/snap/teams-for-linux/15/resources/app.asar/app/browser/index.js --background-color=#fff --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=4062787146318338780 --renderer-client-id=13 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101`
`

- In terminal, enter:
`kill -9 3457`
- Open the app by:  Go to Unity launcher, search 'teams', click on 'Teams for Linux'
(Note that app opens now)

Desktop:

OS: [Linux]
Installation package [Ubuntu 16.0.4 LTS]
Version [0.3.0]

We did not have this issue in version 0.2.1.

**Comment by IsmaelMartinez** [comment]
Hi, Can you fill the bug with the template? https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by kw-at-oocl** [comment]
Edited the initial Post to use the template.  Cheers

**Comment by IsmaelMartinez** [comment]
The application doesn't kill itself once click the cross. It basically hides itself.

You should be able to use `yargs` in order to archive what you need. Check the https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config for more info. There is a `closeAppOnCross` that you should be able to use.

**Comment by joh4nd** [comment]
> The application doesn't kill itself once click the cross. It basically hides itself.
> 
> You should be able to use `yargs` in order to archive what you need. Check the https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config for more info. There is a `closeAppOnCross` that you should be able to use.

`teams-on-linux --closeAppOnCross true` did not work for me.
I had to create the config.json and insert {"closeAppOnCross": true}
