### ISSUE TITLE
Icon system tray

### ISSUE THREAD

**Issue by luiser8** [IsmaelMartinez/teams-for-linux#1440]
There could be the possibility of returning to the original Teams icon because this new one is horrible or the possibility of changing it in the file settings.
![image](https://github.com/user-attachments/assets/2db314ea-367c-42f0-b10e-5ccf7f66ba9f)

go back to this innocuous original
![image](https://github.com/user-attachments/assets/cc25ac7a-d960-452e-812d-cfcad2d6f8f9)

**Comment by IsmaelMartinez** [comment]
Not possible to return to the original icon, for legal reasons. You can choose whatever icon you want with the config option appIcon (check in the config like readme, that is referenced from the main readme)

**Comment by luiser8** [comment]
I have the flatpak version and that command does not work for me, what would I do for that version

**Comment by IsmaelMartinez** [comment]
You need to thank flatpak that we had to change the icon, I would try the config file.

See under https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config for more info.
