### ISSUE TITLE
Perhaps, reduce quality of incoming video?

### ISSUE THREAD

**Issue by RicardoPQ-com** [IsmaelMartinez/teams-for-linux#1441]
**Is your feature request related to a problem? Please describe.**
If there are more than 3 people with their webcams active, Teams starts to consume a lot of CPU, and my outgoing video and sound start to fail

**Describe the solution you'd like**
Maybe reduce incoming video quality? I've noticed that if I explicitly disable incoming video, Teams functions fine again, but it's boring not seeing anyone :smiling_face_with_tear: 

**Describe alternatives you've considered**
I can't think of anything else, sorry

**Additional context**
I'm not an expert in video nor programing, so maybe this is just impossible :sweat_smile:

**Comment by IsmaelMartinez** [comment]
have you tried --disableGpu ? More details in https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config
