### ISSUE TITLE
Links to meetings open in browser instead of teams-for-linux

### ISSUE THREAD

**Issue by RicardoPQ-com** [IsmaelMartinez/teams-for-linux#1442]
**Describe the bug**
If I click a link in a Teams chat, which points to a Teams meeting, the link opens in Firefox, instead of entering the meeting directly.

**To Reproduce**
1. Go to chat with a link to a meeting
2. Click on link
3. The link opens in Firefox instead of teams-for-linux

**Expected behavior**
I'd expect the link to open in teams-for-linux

**Screenshots**
I can't share a screenshot that shows this behavior

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Installation package: chaotic repository
 - Version: 1.11.0-1

**Debug**
I think the relevant part would be this:
13:00:42.472 › testing RegExp onNewWindow false
13:00:42.473 › Requesting to open 'https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html?url=https%3A%2F%2Fteams.microsoft.com%2Fv2%2F%3Fmeetingjoin%3Dtrue%23%2Fl%2Fmeetup-join%2F19%3Ameeting_MjEw... (I'm leaving out the rest of the link)

**Comment by IsmaelMartinez** [comment]
duplicated by https://github.com/IsmaelMartinez/teams-for-linux/issues/1410
