### ISSUE TITLE
No Call Window within a Group Chat

### ISSUE THREAD

**Issue by chwiget** [IsmaelMartinez/teams-for-linux#1443]
**Describe the bug**
If i join a call within a group chat, no call windows appears, but I can hear the others and the others hear me.

**To Reproduce**
1. Go to 'a Group Chat'
2. Click on 'join or Start Call'

4. No call windows appears

**Expected behavior**
a call windows shoud appear where i can see the other members of the call and the buttons end call, mute, cam off/on and cast display

**Desktop (please complete the following information):**
 - Linux Mint Cinnamon
 - Version 6.2.9

**Comment by IsmaelMartinez** [comment]
hi @chwiget , can you provide what packaging version you are using and the logs? Thanks

**Comment by chwiget** [comment]
Can you please tell me how to do this?

**Comment by IsmaelMartinez** [comment]
The template has the command, but basically you need to stop the app, and execute it from the terminal with something like

`teams-for-linux -logConfig={}`

I am not in my laptop so the command might be slightly different. Is in the template, so if you open a new issue you will see it (you can then copy/paste it).

But as important is to know what packaging you are using. Snap/flatpack/deb/rpm/aur , and the package version. They all have their own caveats and normally issues like this are more related to their configuration on your system than the problems with the app.

Hope helps!

**Comment by chwiget** [comment]
It happen with the online version, I am not using the application, i use teams in the browser, so you need the log from the browser?

**Comment by IsmaelMartinez** [comment]
Sorry, if this is in the online version you need to report it to Microsoft. Look for Microsoft teams uservoice. It should show you a page with 2 places they replace that uservoice with. 

No Microsoft people here. Hope helps.

**Comment by chwiget** [comment]
I have the same problem with the teams client, I will try provide the logs

**Comment by IsmaelMartinez** [comment]
The app wraps around the web version. If it happens there, we rarely can do much to fix it. It is normally a MS issue but do send the logs and see if there is anything in there.
