### ISSUE TITLE
No small meeting settings window shows up when joining via "Meet now" button

### ISSUE THREAD

**Issue by peterge-misoft** [IsmaelMartinez/teams-for-linux#1445]
**Describe the bug**
When I join a meeting for a channel, the small black window doesnt appear which allows you to mute, share or view anyone others screen.
It does work when I am the first person who starts a meeting, but not if I join an ongoing meeting.
I have tried the flatpak version and the snap version on Fedora 40.

**To Reproduce**
1. Go to group chat where meeting is started
![image](https://github.com/user-attachments/assets/fb74baa6-fcf1-477b-97ec-0ef31d0c07fe)
2. Click on this button:
![image](https://github.com/user-attachments/assets/f5010f73-fc02-4aaf-b06a-72a72635d17a)
3. I join the audio of the meeting but I am unable to mute or to share/view someones screen because the box is missing.

**Expected behavior**
This window is not showing up in the teams-for-linux application. I captured this image from the teams client on my macbook:
![image](https://github.com/user-attachments/assets/a1e0919a-041b-433f-be8b-0bf5287b5106)

**Screenshots**
above

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40
 - Installation package: flatpak & snap
 - Version: Portal for Teams                    com.github.IsmaelMartinez.teams_for_linux          1.11.0

**Comment by gwozniak** [comment]
isn't it the same issue as  #1443 which seems to be a bug inside web version of teams not teams-for-linux app.

**Comment by IsmaelMartinez** [comment]
Thanks for reporting @peterge-misoft , and for checking @gwozniak . 

I agree on this looking like #1443 that is a microsoft problem. 

We do have another ticket open for showing the shared screen on a similar window, but in that case we are more in control (even if it is difficult currently to implement) #1354 

Unfortunately this is a MS bug and we can't do much. I would suggest reporting it to MS and hopefully they will fix it.
