### ISSUE TITLE
Ability to select default browser for links

### ISSUE THREAD

**Issue by Andrew-Cha** [IsmaelMartinez/teams-for-linux#1446]
**Is your feature request related to a problem? Please describe.**
When I open links it always opens Google Chrome. I use Firefox.

**Describe the solution you'd like**
I'd like an option / an explanation of how to pick a default browser for my links.

**Describe alternatives you've considered**
I have tried looking through the Issues on GitHub / the settings in the app and nothing is seemingly respecting the default browser of my OS (Ubuntu 24)

**Comment by IsmaelMartinez** [comment]
Hi,

You can use the defaultURLHandler config option to define what browser to use.

See https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config

Hope helps,

**Comment by IsmaelMartinez** [comment]
That might not work with snap due to content isolation. I would recommend using deb instead to verify if that is the case.

**Comment by Andrew-Cha** [comment]
Thanks for the clarification.

**Comment by cw-dimedis** [comment]
Yay! I can confirm it works when I install the app via apt.

I had to go the extra step to give "chrome-sandbox" the -s flag to get it running, though.

Many thanks!
