### ISSUE TITLE
Custom Virtual Background

### ISSUE THREAD

**Issue by andresparilli** [IsmaelMartinez/teams-for-linux#1447]
**Choosing a virtual background for meetings can be helpful for several reasons:**

- **Professionalism**: A virtual background can help create a more professional and polished appearance for your meetings, even if you are working from home or in a less-than-ideal environment.
- **Focus**: A virtual background can help you stay focused on the meeting by minimizing distractions in your background.
- **Brand consistency**: If your organization has a standard virtual background, using it can help create a consistent brand image for your meetings.
- **Engagement**: A virtual background can help make your meetings more engaging by adding a touch of personality or creativity.

Allowing users to add a custom background to meetings would be a great feature because it would give users more flexibility and control over their meeting experience. This could be especially helpful for users who want to represent their brand, hobbies, or interests in their virtual background.

**Comment by glitchsys** [comment]
This seems to be a limitation from Microsoft's web client and when it detects Linux.

**Comment by IsmaelMartinez** [comment]
Hi, 

You can have a custom background, but you need to serve the images from a server.

We got an example in https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/customBackground/example

More info in the https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config

Thanks

**Comment by SauceMan8** [comment]
Those links are broken. I found them here. Hopefully save someone a bit of time
https://github.com/IsmaelMartinez/teams-for-linux/tree/main/app/customBackground/example
https://github.com/IsmaelMartinez/teams-for-linux/tree/main/app/config
