### ISSUE TITLE
Share screen isn't working

### ISSUE THREAD

**Issue by shady236** [IsmaelMartinez/teams-for-linux#1448]
I'm using Ubuntu 24.04 LTS, share screen isn't working, it shows this error message.

![image](https://github.com/user-attachments/assets/eff13b22-b7be-4ec6-b610-d37c7e9fb9d6)

However, Teams can access the camera and can start the video. Also sharing white board works fine. the problem is in sharing desktop window or some app screen.

**Comment by IsmaelMartinez** [comment]
hi, can you fill the issue template? otherwise it makes it pretty difficult to narrow down why the problem happens. Thanks
