### ISSUE TITLE
node module "spellchecker" isn't getting pulled in any more

### ISSUE THREAD

**Issue by jsteel44** [IsmaelMartinez/teams-for-linux#145]
**Describe the bug**
When running a "yarn start" with an empty node_modules, the spellchecker module isn't pulled in.

**To Reproduce**
1. rm -rf node_modules
2. yarn start

**Expected behavior**
node_modules/spellchecker used to exist

**Desktop (please complete the following information):**
 - OS: Linux
 - Installation package source
 - Version 0.1.19 (or 0.1.18)

**Comment by IsmaelMartinez** [comment]
Hi, 

Can you provide the versions of electron and others?

Thanks

**Comment by IsmaelMartinez** [comment]
I will close this as duplicated of #123.
