### ISSUE TITLE
Ubuntu 24.04 - Screen sharing not possible

### ISSUE THREAD

**Issue by mibeon** [IsmaelMartinez/teams-for-linux#1455]
**Describe the bug**
It is not possible to share screen on Ubuntu 24.04.1.

**To Reproduce**
1. Open Teams
2. Enter any meeting
3. Try to share your screen
4. See the error "We couldn't access your camera"

**Expected behavior**

**Screenshots**
![teams_sharing_ubuntu](https://github.com/user-attachments/assets/40c29902-f1e3-42fe-bbd9-4218c97bb315)

**Desktop (please complete the following information):**
 - OS: Ubuntu LTS 
 - Installation package: snap
 - Version 24.04.1

**Teams Info**
![teams_info](https://github.com/user-attachments/assets/f5ef0b26-4624-44b4-a230-a0dda129197e)

**Teams Video is generally working**
![teams_video](https://github.com/user-attachments/assets/f271d57e-3b18-4711-aae7-371fde0f279f)

**Permissions**  
All App-Permissions are on.
![teams_permissions_snap](https://github.com/user-attachments/assets/89384ab9-7d20-4ae7-b1b6-29133559c21a)

**Comment by hhoefener** [comment]
Same here on ubuntu 22.04

**Comment by IsmaelMartinez** [comment]
Hi, can you check with other packaging system that is not snap? just to make sure is not an snap issue with your ubuntu configurations

**Comment by hhoefener** [comment]
can confirm this. apt install seems to work!

**Comment by IsmaelMartinez** [comment]
Closing this as it is probably an issue with snap. Most snap installations seem to work, but there is certainly a combination (sometimes with wayland but not only that) that make it not behave. Maybe one day we find the reason and/or this issues become less often.

**Comment by raknerak** [comment]
Hello;

I'm using 24.04.2 LTS and I installed debian version, but still not able to perform screen-sharing. Should I do additional setting somewhere in the system. Please note that, I'm using wayland and screensharing is working fine under x11

![Image](https://github.com/user-attachments/assets/fbbec40b-5f35-4b6e-b6ee-ef2ea1d83588)

**Comment by IsmaelMartinez** [comment]
@raknerak , it is better to open a new issue, but before that, check the closed issues. 

If you're using Wayland, some people need to pass a few extra arguments to get it to work. (Some ozone stuff). 

Hope helps
