### ISSUE TITLE
Double notification sounds - what config change did I need to do again?

### ISSUE THREAD

**Issue by andreaippo** [IsmaelMartinez/teams-for-linux#1458]
Hi, long time Teams for Linux user here (love it! <3), but I recently reinstalled my system including the home partition, and Teams' config.json was something I forgot to backup.

Could someone please remind me how to avoid the annoying double notification sound at a fraction of a second one from another?

![image](https://github.com/user-attachments/assets/62908d8f-c750-403e-b525-c307fb7ef7b6)

Thanks :)

**Comment by andreaippo** [comment]
Seems like it was `Disable Notification Sounds`. I checked that box and now I only get the sound once.

**Comment by IsmaelMartinez** [comment]
Glad you found it. Apologies for the delay on my reply

**Comment by JacekLacnyAmartus** [comment]
Can it be fixed on Electron/app side @IsmaelMartinez ?
I fresh installed TFL on my Manjaro KDE and I'm receiving double notification sound.
If I check `Disable Notification Sounds` is there a change that I miss some notifications? :)

**Comment by programista-zacny** [comment]
Can it be fixed on Electron/app side @IsmaelMartinez ?
I fresh installed TFL on my Manjaro KDE and I'm receiving double notification sound.
If I check `Disable Notification Sounds` is there a change that I miss some notifications? :)

**Comment by IsmaelMartinez** [comment]
Hi @programista-zacny , is a bit more complicated but in principle you should not miss a notification, if you got the app out of focus, but there is an issue with electron that doesn't understand at some points that the app has lost focus (see https://github.com/IsmaelMartinez/teams-for-linux/issues/1234) 

It is a quite annoying issue that have tried to fix many times but it always come back. But if you are getting a double notification, disabling that notifications sound should do the trick.
