### ISSUE TITLE
Change task bar icon when getting signed out

### ISSUE THREAD

**Issue by yantarou** [IsmaelMartinez/teams-for-linux#1459]
**Is your feature request related to a problem? Please describe.**

I'm getting signed out of my account periodically, but only can notice it by looking at the Teams window.
It would be helpful to indicate this status in the task bar icon.

**Describe the solution you'd like**

When getting signed out, the task bar icon should indicate this, e.g. by showing the red dot icon (or even better a dedicated icon with a red X or so).

**Additional context**

Screenshot of the current behavior:

![sign_in_again](https://github.com/user-attachments/assets/6241cf10-264e-4a78-acfd-f338bcb0e0d6)

OS: Debian 12

Teams version:

```
$ apt-cache policy teams-for-linux 
teams-for-linux:
  Installed: 1.11.1
  Candidate: 1.11.1
  Version table:
 *** 1.11.1 500
        500 https://repo.teamsforlinux.de/debian stable/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by IsmaelMartinez** [comment]
Hi @yantarou ,

Thanks for the suggestion. I am looking to see if we can identify when this happens from within the app, to see if we can handle it better.

Unfortunately so far there isn't much info I can see that is useful, but we will keep digging.

Leaving it open but might merge it with the other issue if I see they are converging.

**Comment by yantarou** [comment]
@IsmaelMartinez thanks for looking into this!

**Comment by IsmaelMartinez** [comment]
Merging this with https://github.com/IsmaelMartinez/teams-for-linux/issues/1357
