### ISSUE TITLE
Just came here to say thanks :D

### ISSUE THREAD

**Issue by abelsromero** [IsmaelMartinez/teams-for-linux#146]
I usually do this kind of things on twitter but since I could not locate your id, I just do here.
Many thanks for this project. Using Teams on my company is a must now for video calls and screen sharing and this distribution allows those features (firefox on linux does not ootb).
This means -> more ppl able to use Linux at work!

Special thanks for stepping in while those being payed to do so are not able or willing to do so :+1:

**Comment by IsmaelMartinez** [comment]
Thanks @abelsromero , we really appreciate it. Hopefully one day ms creates a proper client for Linux and start caring about the Linux user community. Thanks again
