### ISSUE TITLE
App lets you click through it on Wayland

### ISSUE THREAD

**Issue by joaquinvacas** [IsmaelMartinez/teams-for-linux#1461]
**Describe the bug**
Application lets click through the window's border (both titlebar and app's content) instead of receiving the input itself.
Check video, it should be explanatory enough :)

**To Reproduce**
1. Use Wayland
2. Open app
3. Try to click on the outer border of the app (like 10px more-less)
4. App or object behind (on Z axis) receives the input

**Expected behavior**
App should receive the input, not what's behind it.

**Screenshots**

https://github.com/user-attachments/assets/9408e6e5-174c-4e30-8bdd-c08a29158749

https://github.com/user-attachments/assets/f0a5a2e4-ef99-4159-b316-159b3d668da5

**Desktop (please complete the following information):**
 - OS: Fedora 41 Workstation
 - Installation package: RPM
 - Version 1.11.2

**Debug**
Debug doesn't output anything

*IMPORTANT:* Ensure that you mask any sensitive information before posting the output.

**Additional context**
Tested on GNOME and Weston, it does show the same behavior.

**Comment by IsmaelMartinez** [comment]
Hi @joaquinvacas , thanks for reporting.

That is strange and looks more of an electron issue than the app itself. Maybe report it at https://github.com/electron/electron 1.11.2 uses electron 32.2.0

Might be worth also checking if this use to happen in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.1 Used electron 32.1.2

Also maybe try with the pre-release (https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.2), that uses electron 33.0.2 (latest as of today)

**Comment by joaquinvacas** [comment]
> Hi @joaquinvacas , thanks for reporting.
> 
> That is strange and looks more of an electron issue than the app itself. Maybe report it at https://github.com/electron/electron 1.11.2 uses electron 32.2.0
> 
> Might be worth also checking if this use to happen in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.1 Used electron 32.1.2
> 
> Also maybe try with the pre-release (https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.2), that uses electron 33.0.2 (latest as of today)

It did happen on 1.11.1 but tomorrow will try 1.11.3 with 33.x then :)

**Comment by joaquinvacas** [comment]
> Hi @joaquinvacas , thanks for reporting.
> 
> That is strange and looks more of an electron issue than the app itself. Maybe report it at https://github.com/electron/electron 1.11.2 uses electron 32.2.0
> 
> Might be worth also checking if this use to happen in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.1 Used electron 32.1.2
> 
> Also maybe try with the pre-release (https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.2), that uses electron 33.0.2 (latest as of today)

Tried it, still happening 🥲

**Comment by IsmaelMartinez** [comment]
:/ I suspect this is an electron issue . Do report it on their side as we don't do anything fancy with the windows border. Sorry

**Comment by jijojosephk** [comment]
Is it `window manager` causing it?

**Comment by RokeJulianLockhart** [comment]
@jijojosephk, that may well have been the cause, per [`discuss.kde.org/t/34583`](https://discuss.kde.org/t/occasionally-i-can-right-click-through-windows-to-windows-beneath-them/34583?u=rokejulianlockhart).

**Comment by IsmaelMartinez** [comment]
Did you try the later versions of the app? I keep track with the electron updates (more or less) and there was a fix for the border (I don't recall what version, but this might be fixed).
