### ISSUE TITLE
Video from own webcam is low resolution and pixelated

### ISSUE THREAD

**Issue by trr** [IsmaelMartinez/teams-for-linux#1465]
**Describe the bug**

When in a teams meeting, my video from my own webcam is at a very low resolution and quite pixelated.
It looks like it's at a much lower resolution than 360p, and downscaled using a poor scaling.  I checked with other people and they also see my video quality is poor and pixelated, consistent with the way I'm seeing myself.

My webcam is 1080p capable.  There are no settings for choosing resolution in teams.  This problem only started happening a few weeks ago; previously it was fine.  Due to difficulties reproducing this unless I'm in a meeting with multiple people I haven't had much of a chance to test.

The webcam is a HiCamera UVC Camera.  In Cheese, it defaults to 1280x720 but I can set it as high as 1920x1080 and it works.  Interestingly, even at 360p, its lowest option, my camera looks fine, just soft, not pixelated like the problematic behavior I'm seeing in Teams.

Other people in the meeting appear normal (their video from their webcam is clear, not pixely, and high resolution).

If I turn off my webcam and turn it on again, while still in the meeting, for the first 1-2 seconds my video is normal and high resolution without the pixely effect then it starts.

**To Reproduce**

1. Join an existing meeting that multiple other people are already in (I couldn't reproduce this in a meeting I started with myself as the only participant)
2. When joining, observe the video preview on the left
3. After joining, observe the view of your own webcam video in the meeting

I tend to use a background effect on my video but when I was testing it happened both with and without the background effect enabled.

**Expected behavior**
Video is clear and looks like it would in any other app (eg in the "cheese" app)

**Actual behavior**

Low resolution poorly scaled pixelated video for me and everyone else's video looks normal.

**Screenshots**
Difficult to add a screenshot without privacy issues

**Desktop (please complete the following information):**
 - OS: Linux Mint 21 (Ubuntu 22.04)
 - Installation package: flatpak
 - Version: 1.11.2

**Debug**
Was unable to reproduce in a meeting with myself.  Will

**Comment by IsmaelMartinez** [comment]
Hi @trr,

A few things to try are:

* another package system as flatpak (like snap) can create odd issues
* an older version (1.10.x) to see if it is related to the electron update
* running the app with --disableGpu, if you provide some logs (even without the meeting) normally I can see if there is a GPU acceleration issue.

Hopefully one of this steps works and either provides us with more info on how to fix this. My suspicions are around those 3 areas. 

Hope helps!

**Comment by PiotrStrzelecki-TomTom** [comment]
happens also here, started since week(s), month - not sure about the exact date but it wasn't there a half year ago (if that helps to narrow down anything)

Desktop (please complete the following information):
    OS: KUbuntu 22.04
    Installation package: apt deb package
    Version: 1.11.3 (was there in 1.11.2 - updated today)

**Comment by IsmaelMartinez** [comment]
Can any of you check order versions of the app and see if you don't get
this? It could be related to and electron version upgrade

**Comment by PiotrStrzelecki-TomTom** [comment]
sure, installed 1.9.6 for now

**Comment by IsmaelMartinez** [comment]
Can one of you provide some logs?Start the app with --logConfig={} from the terminal. You will need to close the app if it is already running (menu option/close)

Also, worth checking if this also happens in the browser version. It might well be a MS Issue, if it wasn't an electron one.

**Comment by PiotrStrzelecki-TomTom** [comment]
switched to web version and will observe if it happens here

**Comment by rNNdom** [comment]
I'm also having this problem on fedora 40-41, when the meeting starts my camera looks kind of fine but after a couple seconds it starts pixelating like with visible squares, tested it on discord and other applications and it works fine.
At first i thought it could be an issue from Dell Latitude 5450 but it seems it's related to teams-for-linux instead.

**Comment by PiotrStrzelecki-TomTom** [comment]
@rNNdom I'd rather be thinking this is MS related issue as I was able to reproduce it in a browser, not team-for-linux, but I am not into details of this soft so probably only @IsmaelMartinez can confirm.
btw - I started to observe a lot of pixelization from time to time also on my peers cameras, ingoing and outgoing, like MS started to play with some compression for the videos

**Comment by IsmaelMartinez** [comment]
If you can reproduce this in the browser I am afraid is a Microsoft issue. Please report it to their forums, but I suspect they are already looking into this. Sorry but there is little we can do from here so I will close the issue, but feel free to put updates and, if we discover there is something we can do, we can re-open the issue.

**Comment by D7Torres** [comment]
I installed the latest stable Ubuntu (Ubuntu 24.04.2 LTS) on a new laptop and went into `Google Meets`. The camera was very pixilated, but I kind of could tell it was not something to do with the hardware, but not using the right video encoding.

- I installed `pinhole` and the image was just as blurry.
- I installed `Cheese` and the image was perfect.
- Then I used `Google Meets` again, and the image was perfect.

So, I suspect installing Cheese also installed some codecs that were necessary to have a good image.

Sorry about the random facts, I hope they can help shed some light.

**Comment by HariTrigger** [comment]
Hi,
This is also happening to me.
I see myself ok in Cheese and the system itself on the Camera app.
But whenever I go into teams, either on the app or in the browser I get completely pixelated, and from my side there is no problem at all, is the other people that let me know of this.

System:
<img width="843" height="434" alt="Image" src="https://github.com/user-attachments/assets/bea55fa1-585c-43da-ae09-313caa17e4f2" />

**Comment by IsmaelMartinez** [comment]
Hi @HariTrigger , thanks for reporting but as this issue happens also in the browser this should be reported to Microsoft and/or Chrome as the issue is on their side. We wrap around the browser to inhered its features (and issues).

**Comment by aroggeband** [comment]
I have the same problem. A workaround I found is to click the camera dropdown once the call has started, and toggle "Adjust Brightness" . This will clear it up. I have a feeling that the connection is negotiating the bandwidth before the call is stable, and choosing a lower quality. Toggling the control either way forces it to reset the video, and probably renegotiate the bandwidth. I will check the settings in Teams to see if it is possible to set the minimum bandwidth.
