### ISSUE TITLE
Explicitly setting "ssoInTuneAuthUser" is broken

### ISSUE THREAD

**Issue by pazepaze** [IsmaelMartinez/teams-for-linux#1466]
**Describe the bug**
When explicitly specifying `ssoInTuneAuthUser` in the config, the inTune account will not be found even if it exists.

**To Reproduce**
1. set `ssoInTuneEnabled` to `true` and `ssoInTuneAuthUser` to an account that exists

**Expected behavior**
The account is found.

**Desktop:**
 - OS: Ubuntu 24.04 with working InTune
 - deb Installation
 - Version 1.11.2

**Debug**
When setting `ssoInTuneAuthUser`:

```
09:12:17.139 › Failed to find matching InTune account for myname@mycorp.de.
```

When only setting `ssoInTuneEnabled` to `true` and not specifying the user, so it uses the first one found:

```
09:58:14.080 › Using first available InTune account (myname@mycorp.de)
```

**Additional context**

It seems to be a bug in this part of `app/index.js`:

```javascript
		for (const account in response.accounts) {
			if (account.username == ssoInTuneAuthUser) {
				inTuneAccount = account;
				console.debug('Found matching InTune account (' + inTuneAccount.username + ')');
				break;
			}
		}
```

I will just quote our friend GitHub Copilot here:
The behavior you are observing is due to the way the `processInTuneAccounts` function is implemented. Here is a brief explanation:

**When `ssoInTuneAuthUser` is specified:**
   - The function iterates over the `response.accounts` array to find an account with a username that matches `ssoInTuneAuthUser`.
   - The loop uses `for (const account in response.accounts)`, which iterates over the keys (indices) of the `response.accounts` array, not the actual account objects.
   - As a result, `account.username` is `undefined`, and the comparison `account.username == ssoInTuneAuthUser` always fails.

**Comment by IsmaelMartinez** [comment]
you need to run the intune app https://learn.microsoft.com/en-us/mem/intune/user-help/microsoft-intune-app-linux but that one is not available yet in Ubuntu. 

This was a feature added by the community in https://github.com/IsmaelMartinez/teams-for-linux/pull/1280 , so I don't really fully know how it works tbh. 

I would follow this issue in MS land but I believe this is not an issue with the app unfortunately. Good luck https://learn.microsoft.com/en-us/answers/questions/1665760/intune-portal-availability-for-ubuntu-24-04-lts

**Comment by IsmaelMartinez** [comment]
This seems to be a workaround that people use https://panther.kapsi.fi/posts/2024-09-03_ubuntu_intune 

Hopefully this helps!

**Comment by pazepaze** [comment]
@IsmaelMartinez OK, but I pointed out a specific bug where an `app/index.js` where an iteration over array indices is done instead of iterating over the values leading to account names not being found even if they exist.

The feature seems to partially work, otherwise. I am still testing this.

Just wanted to point out that specific bug.

The workaround I am using right now is to not specify a `ssoInTuneAuthUser`, but still setting `ssoInTuneEnabled` to `true`, so it will find the first account automatically.

**Comment by fmoessbauer** [comment]
@IsmaelMartinez Please reopen this. The bug in https://github.com/IsmaelMartinez/teams-for-linux/blob/main/app/intune/index.js#L17 is still there. This is not related to InTune itself, but a simple logic error in the for-each loop.

**Comment by IsmaelMartinez** [comment]
Apologies that I didn't see the error. Trying to manage that many issues sometimes makes me misunderstand issues, and or forget about them. Thanks for putting an MR @fmoessbauer . I will have a look once I get sometime (extremely busy day at work). But check you have updated the package.json file and the appmetadata (the info is in the CONTRIBUTING md file)
