### ISSUE TITLE
Deb package for Amd64 has doubled in size

### ISSUE THREAD

**Issue by 0xffccff** [IsmaelMartinez/teams-for-linux#1468]
**Describe the bug**
teams-for-linux_1.11.3_amd64.deb is 187 MB.
teams-for-linux_1.11.2_amd64.deb was 85.4 MB.
Older packages always had more or less the same size.
Other packages have retained the size, but this one has more than doubled. Same for AppImage and tar.gz.

**Additional context**
Sorry if it's intentional or necessary, I just thought something might be redundant in the packages.

**Comment by IsmaelMartinez** [comment]
Interesting. This might be because we did push a couple of changes after the release so maybe it has include it twice? Not sure but I will keep it open and see what happens in the next release. Thanks for reporting!

**Comment by jpandre** [comment]
Same surprise about the rpm for x86-64, but not about the one for aarch64. Digging further, I see that the decompressed executable /opt/teams-for-linux/teams-for-linux occupies 1075MB on x86-64, which is 6 times more than 178MB on aarch94.

The main difference is that the rpm for x86-64 contains 777MB of debug information, whereas the one for aarch64 has none.

**Comment by IsmaelMartinez** [comment]
Really strange. I haven't changed the build process but electron version
when up. I will check if if they got something open. Thanks for digging
into this.

**Comment by IsmaelMartinez** [comment]
It must be something to do with the new version of electron as I can see similar big sizes in release 1.11.4. 

It could be it not working nicely with electron-builder (that didn't change) as electron-builder should be not pushing the dev logs, but I will see if I can find something aroudn that area. Really strange

**Comment by IsmaelMartinez** [comment]
Maybe disabling this https://www.electron.build/publish#publishautoupdate ? seems to be enabled by default but we don't use it, so I will see if we can disable it and see if the size reduces.

**Comment by IsmaelMartinez** [comment]
Ok, looks like https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.5 is back to the normal size. It would have been something to do with electron as I just updated to version 33.2.0 and the size is back to normal. Thanks for reporting!
