### ISSUE TITLE
Can't attach local files

### ISSUE THREAD

**Issue by Frodoking21** [IsmaelMartinez/teams-for-linux#1469]
**Describe the bug**
same as title. just get spinning wheel (Drag n' drop also doesn't work)

**To Reproduce**
1. Enter DM
2. Click on '+'
3. Click on 'Attach file'

**Expected behavior**
Open file finder window

**Screenshots**
![image](https://github.com/user-attachments/assets/2ef1ba82-bebe-47c9-9173-d9c099c53474)

**Desktop (please complete the following information):**
 - OS: Linux Mint 22 Wilma
 - Installation package: deb from repo
 - Version: 1.11.3

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
No config file found, using default values
all good with appLogLevels you aren't using them
all good with onlineCheckMethod you aren't using them
Initialising logger with config: "{}"
14:07:03.863 › File logging at /home/fred/.config/teams-for-linux/logs/main.log with level silly
14:07:03.867 › Console logging enabled with level silly
14:07:03.868 › Logger initialised
14:07:03.868 › configPath: /home/fred/.config/teams-for-linux
14:07:03.868 › configFile: {}
14:07:04.088 › processArgs: [
  '/opt/teams-for-linux/teams-for-linux',
  '--webDebug',
  '--logConfig={}'
]
14:07:04.090 › testing RegExp processArgs false
14:07:04.090 › testing RegExp processArgs false
14:07:04.090 › testing RegExp processArgs false
14:07:04.090 › Waiting for network...
14:07:04.091 › Testing network using net.request() for https://teams.microsoft.com
14:07:04.092 › Spellchecker is disabled!
[158530:1106/140704.244159:ERROR:nss_util.cc(345)] After loading Root Certs, loaded==false: NSS error code: -8018
14:07:04.316 › Network test successful with method https
14:07:05.448 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 1s, IdleState: 'active'
[158530:1106/140705.449494:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[158530:1106/140706.065701:ERROR:service_worker_storage.cc(2072)] Failed to delete the database: Database IO error
14:07:09.825 › did-frame-finish-load {} true
14:07:09.826 › did-finish-load
14:07:10.607 › did-frame-finish-load {} false
14:07:11.105 › assignOnDidFailLoadEventHandler : {} - -3 - 
14:07:12.770 › cookie changed cause: overwrite 
 removed?: true 

14:07:12.771 › cookie: authtoken 
 expirationDate: 1731010582.895439 
 domain: teams.microsoft.com
14:07:12.771 › cookie changed cause: explicit 
 removed?: false 

14:07:12.771 › cookie: authtoken 
 expirationDate: 1731010786.770506 
 domain: teams.microsoft.com
14:07:12.987 › Badge count set to '0'
14:07:12.997 › Badge count set to '0'
14:07:19.323 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 15s, IdleState: 'active'
14:07:29.325 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 25s, IdleState: 'active'
14:07:39.327 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 35s, IdleState: 'active'
14:07:49.329 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 45s, IdleState: 'active'
14:07:54.000 › Badge count set to '0'
14:07:56.113 › did-frame-finish-load {} false
14:07:59.332 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 55s, IdleState: 'active'
14:08:09.334 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:08:16.618 › window close
14:08:20.211 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
14:08:22.589 › window close
14:08:22.792 › window closed
14:08:22.793 › before-quit
14:08:22.793 › will-quit
14:08:22.793 › quit
```

**Comment by IsmaelMartinez** [comment]
Hi @Frodoking21 , Thanks for reporting this. 

Can you check if trying the same in the browser this works? If not, can you check with version 1.11.2 ? There was a change on electron version, the framework we use, those are my two main suspects.

Let me know how you get on.

**Comment by Frodoking21** [comment]
HI @IsmaelMartinez , thanks for the quick response.

For whatever reason, the web app refuses to boot in my browser (lbrewolf) so I cant test there. i downgraded to 1.11.2 and unfortunately got the same behavior. This really surprises me since I'm pretty sure that was the version I was on when I last used this feature on Oct 24

**Comment by IsmaelMartinez** [comment]
Hi @Frodoking21, 

Are you able to install a chromium base browser to do a test? You can remove it afterwards.

I can see Linux Mint 22 Wilma is based on Ubuntu 24.04. I wonder if this is again a side effect of this https://github.com/IsmaelMartinez/teams-for-linux/issues/1426 .  In some OS the app uses the installed chromium version, maybe is trying to do this but some libraries have changed and got a bit confused. I would suggest checking if the --no-sandbox option works and, if that is the case, then create an appArmour profile for the app (as mention in the other issue).

Wild guess this second one, but I have seen wildest issues.

**Comment by IsmaelMartinez** [comment]
@Frodoking21 I haven't got any news from you. If you can check the previous commend and the latest [pre-release 1.12.3](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.12.3) (or higher) and let us know if you can't still attach local files. I will close this to keep the issue numbers manageable, but can reopen once I get news from your side.

**Comment by NikMel** [comment]
Update...
Deleting the folder `.config/teams-for-linux` seems to have fixed all of the above!
