### ISSUE TITLE
Unable to share only one screen

### ISSUE THREAD

**Issue by ericch1** [IsmaelMartinez/teams-for-linux#147]
Hi,

I have 2 monitors and I use X11 with applications on each monitor, resizing correctly into each screen.  However, when I want to share a screen with teams, it proposes only to share my "whole" 2 screens into the same image, not only one screen...

I know the windows version to work well.. Is there any hope to have the linux version working well too?

Thanks,

Eric

**Comment by IsmaelMartinez** [comment]
duplicated:
https://github.com/IsmaelMartinez/teams-for-linux/issues/108

Unfortunately is not really possible with the current Chrome implementation.
