### ISSUE TITLE
Installation does not work on Linux Mint

### ISSUE THREAD

**Issue by dvbeek** [IsmaelMartinez/teams-for-linux#1475]
**Describe the bug**
When following the Ubuntu-instructions on Mint, it ends up in an error:
> deb [signed-by=/etc/apt/keyrings/teams-for-linux.asc arch=amd64] https://repo.teamsforlinux.de/debian/ stable main
> Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
> Ign:2 https://mirrors.evoluso.com/linuxmint-packages/linuxmint-packages wilma InRelease         
> Get:3 https://repo.teamsforlinux.de/debian stable InRelease [10,8 kB]                           
> Hit:4 http://archive.ubuntu.com/ubuntu noble InRelease    
> Hit:5 https://mirrors.evoluso.com/linuxmint-packages/linuxmint-packages wilma Release
> Hit:6 http://archive.ubuntu.com/ubuntu noble-updates InRelease
> Err:3 https://repo.teamsforlinux.de/debian stable InRelease
>   Unknown error executing apt-key
> Hit:7 http://archive.ubuntu.com/ubuntu noble-backports InRelease
> Reading package lists... Done
> W: GPG error: https://repo.teamsforlinux.de/debian stable InRelease: Unknown error executing apt-key
> E: The repository 'https://repo.teamsforlinux.de/debian stable InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**To Reproduce**
https://github.com/IsmaelMartinez/teams-for-linux?tab=readme-ov-file#debianubuntu-and-other-derivatives

**Expected behavior**
apt update will refresh without errors

**Desktop (please complete the following information):**
 - OS: Linux Mint 22 Cinnamon
 - Cinnamon Version: 6.2.9
 - Linux Kernel: 6.8.0-48-generic

**Work around**
> sudo apt update --allow-insecure-repositories

**Comment by IsmaelMartinez** [comment]
Hello @dvbeek ,

Can you try the image in the release section? I don't manage that repo that I believe is @nbuechner created. Maybe the GPG changed or the instructions for Linux Mint 22 are different.

You can probably ask this into the [matrix](https://matrix.to/#/#teams-for-linux_community:gitter.im) room as others might be able to help you there.  

Hope helps

**Comment by nbuechner** [comment]
Hi. I tested this on a fresh Mint 22 installation and followed the instructions on https://teamsforlinux.de/.
No error here.

```
user@mint:~$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="22 (Wilma)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 22"
VERSION_ID="22"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=wilma
UBUNTU_CODENAME=noble
```

```bash
user@mint:~$ sudo mkdir -p /etc/apt/keyrings
[sudo] password for user:          
user@mint:~$ sudo wget -qO /etc/apt/keyrings/teams-for-linux.asc https://repo.teamsforlinux.de/teams-for-linux.asc
user@mint:~$ echo "deb [signed-by=/etc/apt/keyrings/teams-for-linux.asc arch=$(dpkg --print-architecture)] https://repo.teamsforlinux.de/debian/ stable main" | sudo tee /etc/apt/sources.list.d/teams-for-linux-packages.list
deb [signed-by=/etc/apt/keyrings/teams-for-linux.asc arch=amd64] https://repo.teamsforlinux.de/debian/ stable main
user@mint:~$ sudo apt update
Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Ign:4 http://packages.linuxmint.com wilma InRelease
Hit:5 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:6 http://packages.linuxmint.com wilma Release
Get:7 https://repo.teamsforlinux.de/debian stable InRelease [10,8 kB]
Get:9 https://repo.teamsforlinux.de/debian stable/main amd64 Packages [683 B]
Fetched 11,4 kB in 1s (16,0 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
274 packages can be upgraded. Run 'apt list --upgradable' to see them.
user@mint:~$ apt install teams-for-linux
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  teams-for-linux
0 upgraded, 1 newly installed, 0 to remove and 274 not upgraded.
Need to get 88,8 MB of archives.
After this operation, 299 MB of additional disk space will be used.
Get:1 https://repo.teamsforlinux.de/debian stable/main amd64 teams-for-linux amd64 1.11.5 [88,8 MB]
Fetched 88,8 MB in 8s (11,2 MB/s)                                                                                            
Selecting previously unselected package teams-for-linux.
(Reading database ... 454917 files and directories currently installed.)
Preparing to unpack .../teams-for-linux_1.11.5_amd64.deb ...
Unpacking teams-for-linux (1.11.5) ...
Setting up teams-for-linux (1.11.5) ...
update-alternatives is /usr/bin/update-alternatives
update-alternatives: using /opt/teams-for-linux/teams-for-linux to provide /usr/bin/teams-for-linux (teams-for-linux) in auto 
mode
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for mate-menus (1.26.1+mint1) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
```

**Comment by dvbeek** [comment]
Sorry, I just fixed the problem!

Apparently there was something wrong with the file permissions of the keyring.
I fixed it like this: `sudo chmod o+r /etc/apt/keyrings/teams-for-linux.asc`.

**Comment by IsmaelMartinez** [comment]
not a problem and thanks for reporting it. Surely it might help someone else in the future.

**Comment by waagbo** [comment]
The chmod instructions should preferrably be added do the manual instructions on https://teamsforlinux.de/ (@nbuechner)
