### ISSUE TITLE
Is it technically possible to manage breakout rooms in teams-for-linux?

### ISSUE THREAD

**Issue by kupiqu** [IsmaelMartinez/teams-for-linux#1476]
The basic idea is to split participants of a meeting in different rooms. In teaching this is useful for practical team work

Here is official info about breakout rooms:

https://support.microsoft.com/en-us/office/use-breakout-rooms-in-microsoft-teams-meetings-7de1f48a-da07-466c-a5ab-4ebace28e461

Apparently it's supported only in Windows and Mac systems but I don't know if this is due to some technical constraint or it could be somehow workarounded.

Thank you for your help and time invested in teams-for-linux, very appreciated!

**Comment by IsmaelMartinez** [comment]
This would need to be a feature MS provides in the browser. If they do, then we might be able to support it. Sorry but we can't do much about it.
