### ISSUE TITLE
Use of native file picker

### ISSUE THREAD

**Issue by Damglador** [IsmaelMartinez/teams-for-linux#1478]
**Is your feature request related to a problem? Please describe.**
Currently the app uses gtk file picker that doesn't even follow system theme and just blinding white for me, --followSystemTheme=true doesn't seem to do anything about that. In addition, pins from KDE Dolphin aren't pressent in gtk file picker.

**Describe the solution you'd like**
Use xdg portals if possible

**Additional context**
DE: KDE Plasma
Teams installed from flatpak

**Comment by IsmaelMartinez** [comment]
Hi @Damglador ,

I have the suspicion this is a flatpak issue more than anything. https://docs.flatpak.org/en/latest/sandbox-permissions.html 

I would 1st check one of the other packing options we provide to narrow it down to flatpak, and if this is the case then try searching around it. 

A quick search got me to this https://www.reddit.com/r/kde/comments/lcob3x/file_picker_in_apps/ 

This was implemented in electron a few years ago https://github.com/electron/electron/issues/2911

**Comment by Damglador** [comment]
Yes, that's flatpak being flatpak. I tested all my flatpak apps before sending issue, and they had the native picker, I didn't think that's electron specific problem. Thanks for pointing me in the right direction.
