### ISSUE TITLE
Permission denied errors

### ISSUE THREAD

**Issue by neilunderwood** [IsmaelMartinez/teams-for-linux#148]
I keep having to remove and reinstall this snap package.  Everything will be fine for a few days and then all of a sudden, usually in the middle of a video conference, because that's my luck, things will stop functioning (i.e. selecteable/clickable items aren't responding).  I will restart the client but it fails to launch.  Launching from the command line yields:

`/home/local/DOMAIN/USERNAME/snap/teams-for-linux/15: Permission denied`

Everything worked fine when this was in the beta channel and using the `--classic` option when installing.  Now I get this:

`Warning: flag --classic ignored for strictly confined snap teams-for-linux`
`teams-for-linux 0.3.0 from Julian Alarcon (alarconj) installed`
`Channel beta for teams-for-linux is closed; temporarily forwarding to stable.`

This may be a snap issue and not an issue with this project but I'm brand new to the snap game.  My apologies if this is not the right avenue for this.

I'm running Linux Mint 18.3 if that makes any difference.

Cheers and thanks for your time spent on this project.

**Comment by IsmaelMartinez** [comment]
Hi @neilunderwood ,

Can you check if you have the same issues with the Deb package? 

Snap packages can be a bit temperamental. @julian-alarcon might be able to help with the snap package, time depending.

**Comment by neilunderwood** [comment]
Pardon my ignorance but would you have a link to that package?  I can't seem it find it.

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.3.0

**Comment by neilunderwood** [comment]
Thanks.  I'll give it a try.

**Comment by IsmaelMartinez** [comment]
Let me know how you get on.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity

**Comment by julian-alarcon** [comment]
Hi @neilunderwood . There is no need for the `--classic` flag as teams-for-linux is confined strictly. Also, some times the issue is related with misconfigurations, the best thing to do is to remove the snap and delete the conf files (~/snap/teams-for-linux folder).

Also please check the edge version of the snap, many times bugs are fixed, but please take care of new bugs as these is the edge channel.

`sudo snap install teams-for-linux --channel edge`

**Comment by wegry** [comment]
Using edge, I'm still seeing this issue

```
➜  ~ sudo snap install teams-for-linux --channel edge
Warning: /snap/bin was not found in your $PATH. If you've not restarted your
         session since you installed snapd, try doing that. Please see
         https://forum.snapcraft.io/t/9469 for more details.

teams-for-linux (edge) 0.4.0 from Julian Alarcon (alarconj) installed
➜  ~ teams-for-linux 
cannot create user data directory: /home/me/snap/teams-for-linux/24: Permission denied
```

**Comment by julian-alarcon** [comment]
Hi @wegry , your issue seems more related with Snapd than with teams-for-linux.-

How did you installed snapd? Which OS, version are you using?

Try to install another snap app, like slack, skype or similar `sudo snap install slack`

**Comment by IsmaelMartinez** [comment]
This seems to be an apparmor not recognising that as a home directory. 

You need to:

```
sudo dpkg-reconfigure apparmor
```
and add that folder to it. (`/home/local/DOMAIN` as for the reported issue) 

Check this for more info https://bugs.launchpad.net/snapcraft/+bug/1620771
