### ISSUE TITLE
Error "Fetched custom background remote configuration but failed to save ... configJSON is not iterable" in logs

### ISSUE THREAD

**Issue by SuperTux88** [IsmaelMartinez/teams-for-linux#1483]
**Describe the bug**

See: https://github.com/IsmaelMartinez/teams-for-linux/issues/1424#issuecomment-2480912442

When starting teams-for-linux, I see an error `Fetched custom background remote configuration but failed to save at '/home/myuser/.config/teams-for-linux/custom_bg_remote.json'. configJSON is not iterable` in the logs. Everything works normal and I can select my custom backgrounds, it's just the error log that confuses me.

**To Reproduce**
1. Have a working custom-background server
2. Configure teams-for-linux to use the custom-background server
3. Start teams-for-linux from a terminal (so you see logs)
4. See error logged

**Expected behavior**
If the custom backgrounds are working, I would expect no error to be logged.

**Desktop (please complete the following information):**
 - OS: Linux / Gentoo
 - Installation package: [ebuild](https://github.com/SuperTux88/gentoo-overlay/blob/860fa03bca8592a8e55e96d2bd6d2a7055ff788d/net-im/teams-for-linux/teams-for-linux-1.11.5.ebuild) based on the `deb` package
 - Version: 1.11.5 (but I noticed that the error was already logged with an older 1.11.0 version)

**Debug**

```bash
teams-for-linux --webDebug --logConfig='{}' --customBGServiceBaseUrl=http://localhost:8080
```
```
all good with appLogLevels you aren't using them
all good with onlineCheckMethod you aren't using them
Initialising logger with config: "{}"
19:45:45.164 › File logging at /home/myuser/.config/teams-for-linux/logs/main.log with level silly
19:45:45.166 › Console logging enabled with level silly
19:45:45.166 › Logger initialised
19:45:45.166 › configPath: /home/myuser/.config/teams-for-linux
19:45:45.166 › configFile: {
  optInTeamsV2: true,
  isCustomBackgroundEnabled: true,
  customBGServiceBaseUrl: 'https://my-usual-custom-bg-url.example.com',
  followSystemTheme: true
}
19:45:45.168 › Running under Wayland, switching to PipeWire...
19:45:45.332 › Fetching custom background configuration from 'http://localhost:8080/config.json'
19:45:45.370 › Custom background service url is 'http://localhost:8080'
19:45:45.370 › processArgs: [
  '/opt/teams-for-linux/teams-for-linux',
  '--webDebug',
  '--logConfig={}',
  '--customBGServiceBaseUrl=http://localhost:8080'
]
19:45:45.371 › testing RegExp processArgs false
19:45:45.371 › testing RegExp processArgs false
19:45:45.371 › testing RegExp processArgs false
19:45:45.371 › testing RegExp processArgs false
19:45:45.371 › Waiting for network...
19:45:45.371 › Testing network using net.request() for https://teams.microsoft.com
19:45:45.372 › Spellchecker is disabled!
19:45:45.476 › Fetched custom background remote configuration but failed to save at '/home/myuser/.config/teams-for-linux/custom_bg_remote.json'. configJSON is not iterable
[1428790:1117/194545.615229:ERROR:nss_util.cc(345)] After loading Root Certs, loaded==false: NSS error code: -8018
19:45:45.650 › Network test successful with method https
...
```

**Additional context**

> You need a server running to use the custom background (see the docs and the example in the custom background section. Config area). My guess is you are probably not running a server or you haven't got the right config, but I will be able to tell more by looking at the config and your logs.

So as written in the comment on the other issue, it's mostly about the error log that appears. I don't know since when this error gets logged, I just noticed it yesterday (I usually don't look at the logs), but I also checked on another computer with an older version and at least on 1.11.0 it also already gets logged.

I have a working server running, I use it since a long time (even before v2, but I then changed the json to match the v2 format). And it's working, I see my custom backgrounds from my server. But I also see above error message in the logs.

My existing server which is configured in my config is nginx based. However when I clone the repo and start `npx http-server -p 8080 --cors "*" -g` in this folder: https://github.com/IsmaelMartinez/teams-for-linux/tree/main/app/customBackground/example, and start teams with `--customBGServiceBaseUrl=http://localhost:8080` to override my own server, it also still logs the error, but it now shows me the 3 images from that folder instead of my own images. So it loads the config from the temporary localhost server (I can see it in the access log). If I start teams without that parameter again, it uses the URL from the config file again, and all my own custom backgrounds are back. So it loads the custom backgrounds, but still logs the error every time teams-for-linux gets started.

However, the error isn't about that custom backgrounds can't be loaded, but that it can't store the downloaded backgrounds config locally. But the file still exists and has the content from my usual custom background server (If I start with the localhost background server, it doesn't get changed to that new content). It was last changed on September 3rd (so that's probably since around when the error gets logged, but I just didn't notice it?). If I remove the file, it doesn't get recreated and the error is still logged. But custom-background also still work.

So, my questions are:
* Why is this file needed? Custom backgrounds seem to work perfectly even if it can't be written to that file.
* Why is the error logged? It must have worked at some point, but something is broken now (but it doesn't affect the actual usage of custom backgrounds, just storing the local file is broken)

**Comment by IsmaelMartinez** [comment]
Hi @SuperTux88 , thanks for reporting. 

This can be changed to a warning and, to be honest, I have no idea why we need to try to update the file in the local system. It is a functionality the community mostly created, but glad to hear this is working for you and is only a wrong "error level".

I will have a look to see if I can find any reason why we do need to save the file in the filesystem.

**Comment by SuperTux88** [comment]
It would maybe also be interesting to know why storing the file fails (even if it also works without the file), because I don't see a reason why it should fail. The folder is read/writable by my user and everything else is working too (at least I didn't notice any other problems yet).

**Comment by IsmaelMartinez** [comment]
can you share the equivalent to the config.json and custom_bg_remote.json you have? the error seems to indicate it can't iterate throw the records, what probably means you are not getting a custom_bg_remote.json file.

Strange you see that error with the example app, as I don't see it in there. Pretty strange

**Comment by IsmaelMartinez** [comment]
Hi @SuperTux88 , can you try https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.12.0? 

The error you reported is related to teams-v1 custom background needs, so I think that is why it is working for you that is using the v2 version, but I now wonder if in 1.12.0 the customBackgrounds aren't working.

**Comment by SuperTux88** [comment]
@IsmaelMartinez Sorry, it took me a while, was a bit busy.

So I tested with the newest 1.12.3 now, it's still the same behavior as before. So it still logs the error (and still doesn't create the file, so the error really happens), but the backgrounds still work, and if I test with the localhost example backgrounds, it shows them, and if I switch back to my own url, it shows my images again. So from a user perspective, everything looks fine and works. It's just the error that's a bit confusing.

> The error you reported is related to teams-v1 custom background needs

Is teams v1 even still a thing? I was force-migrated like already a few month ago, and I think I can't even switch back if I want to. But yes, if the error is only about teams v1, that explains why everything is still working from a users perspective.

In teams v1 the backgrounds JSON had a different format, and I needed to convert it to the new format when I was forced to migrate to v2 for it to work again. I think the old format was an array `[...]`at the top-level, while now it's an object `{...}`, which isn't iterable (as the error says), so that would explain why it fails? But interesting is, that it must have worked with the teams v2 format, as the old file that was stored at that path already has the new v2 format.

But if that logic is only required for v1 (if that even still exists?) it might be best to check if it's an array and only continue if it is, and if it's not, maybe just log an info or at max a warning, with a more meaningful text that says, that it's only relevant for v1.

**Comment by IsmaelMartinez** [comment]
I will close this as is just a 'safe' error. I will see if I can make it a warning as to not scare people off.

**Comment by SuperTux88** [comment]
@IsmaelMartinez I just tested the new 1.12.4 version with the fix for this, and I now get an error logged `Failed to fetch custom background remote configuration. console.warning is not a function`, so I think the fix kinda made it worse :grimacing:

**Comment by IsmaelMartinez** [comment]
thanks for letting me know @SuperTux88 . I will remove that release as, well, it is broken.

**Comment by SuperTux88** [comment]
Tested with 1.12.5 now, and it properly logs as warning now. :+1: Thank you
