### ISSUE TITLE
Characters not loaded

### ISSUE THREAD

**Issue by AntonioBerna** [IsmaelMartinez/teams-for-linux#1484]
**Describe the bug**

When i download any file, document, etc, i get this:

![Screenshot_2024-11-18_15-22-08](https://github.com/user-attachments/assets/60c1639f-4e77-4979-9d4f-9064e041a5d3)

**To Reproduce**
1. Select something files to download.
2. Click on 'Download' button.
3. See bug.

**Expected behavior**
I expected to see the fonts loaded correctly.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Installation package: snap
 - Version: 1.11.5

**Debug**
I use the following command:

```bash
$ teams-for-linux --webDebug --logConfig='{}'
```

and obtain:

```bash
No config file found, using default values
all good with appLogLevels you aren't using them
all good with onlineCheckMethod you aren't using them
Initialising logger with config: "{}"
15:42:48.957 › File logging at /home/berna/snap/teams-for-linux/715/.config/teams-for-linux/logs/main.log with level silly
15:42:48.960 › Console logging enabled with level silly
15:42:48.961 › Logger initialised
15:42:48.961 › configPath: /home/berna/snap/teams-for-linux/715/.config/teams-for-linux
15:42:48.962 › configFile: {}
dbus-send: /snap/teams-for-linux/715/lib/x86_64-linux-gnu/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.12.20' not found (required by dbus-send)
15:42:49.051 › App already running
Gtk-Message: 15:42:49.061: Failed to load module "xapp-gtk3-module"
Gtk-Message: 15:42:49.061: Failed to load module "xapp-gtk3-module"
```

**Comment by IsmaelMartinez** [comment]
Duplicated with https://github.com/IsmaelMartinez/teams-for-linux/issues/1105 (and a few others)

This https://github.com/IsmaelMartinez/teams-for-linux/issues/1105#issuecomment-1947728319 should sort this out.

Closing as that solution has worked many times before. If you still face an issue, let us know and we can re-open
