### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by davegod75** [IsmaelMartinez/teams-for-linux#1485]
The app is only displaying a white screen after loggin in.  I came here to try this app because the PWA on chrome is doing the same thing.

**To Reproduce**
1. log into app
![teams](https://github.com/user-attachments/assets/efa23b99-8991-483d-ad02-cfed8db5bef2)

**Desktop (please complete the following information):**
 - OS: Linux mint 22
 - Installation package: deb
 - Version latest

Not sure what to post from the debug.

**Comment by Gymnasiast** [comment]
It’s to be expected that both have the same problem, as this application is a wrapper around the PWA with a few extra features. It seems like there is an error on Microsoft’s side - I have the same problem, both in the browser and with this application.

**Comment by Dmohit** [comment]
Facing the same problem, in browser as well as the deb package. On Kubuntu 24.10. Tried deb with both 1.12.0 and 1.11.5. From the messages it appears to be a Wayland problem.

```
mohit@mohit-aspire:~/.config/teams-for-linux$ teams-for-linux 
No config file found, using default values
all good with appLogLevels you aren't using them
all good with onlineCheckMethod you aren't using them
Initialising logger with config: {"transports":{"console":{"level":"info"},"file":{"level":false}}}
22:10:07.053 › configPath: /home/mohit/.config/teams-for-linux
22:10:07.055 › Running under Wayland, switching to PipeWire...
22:10:10.424 › assignOnDidFailLoadEventHandler : {} - -3 - 
[117698:1121/221023.448257:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[117698:1121/221038.479133:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[117698:1121/221038.496810:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

```
