### ISSUE TITLE
Link handling from Firefox?

### ISSUE THREAD

**Issue by ogghi** [IsmaelMartinez/teams-for-linux#1488]
Hi, 

first of all thanks for the nice working client.
I am on Archlinux always updated and wondering if you know a way of handling links to Teams meetings from Google calendar to open in Teams app?
They always open in the browser. If I copy them in my own Teams chat (w/o Google part) nothing happens when clicking on it.

Thanks
ogghi

**Comment by IsmaelMartinez** [comment]
see https://github.com/IsmaelMartinez/teams-for-linux/issues/675 . Some people use a "redirector" plugin to be able to do that. If it is archlinux you might have better luck checking in https://aur.archlinux.org/packages/teams-for-linux . That community is pretty good at helping one another. 

Closing as the answer should be in #675
