### ISSUE TITLE
Typing becomes really slow on 0.3.0

### ISSUE THREAD

**Issue by vgeof** [IsmaelMartinez/teams-for-linux#149]
![Capture d’écran de 2019-06-14 10-51-19](https://user-images.githubusercontent.com/44399944/59496741-67d6a380-8e92-11e9-966b-ccb9a8cdfd84.png)
![Capture d’écran de 2019-06-14 10-49-37](https://user-images.githubusercontent.com/44399944/59496654-3362e780-8e92-11e9-8f4d-e4b68eecdba6.png)
**Describe the bug**
When typing a message to someone, the more words not recognized by the dictionary I type, the slower the app becomes (100 %CPU after ~20 words)

**To Reproduce**
1. Go to Conversation
2. Start writing a message to someone
3. Type words that are not recognized by the spell checker 
4. After  a dozen of non-recognized words, the app begins to hit 100 % cpu and gets slower

**Expected behavior**
Spell Checking should not have such an incidence on the typing speed. The issue doesn't occur on the web client.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation package deb
 - Version 0.3.0

**Additional context**
The issue started when I upgraded form 0.2.0 to 0.3.0. 
I haven't installed any dictionary or stuff related to the spell checker for this app, so the default language is english

This is quite annoying, since I type both in french and english, and typing more than two sentences in french becomes really hard.
EDIT : Teams seems to recognize french, so the issue occurs just because I type too many misspelled words, like without accents.

By the way, a lot of thanks for this app !! :)

**Comment by IsmaelMartinez** [comment]
Hi @vgeof ,

I can only think about adding the ability to adding an option to disable the spellchecker. 

The code is in this file:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/rightClickMenuWithSpellcheck.js

A config option might be the best compromise.  I don't know when I will be able to implement that (or when someone will be able to). 

I recommend to use version 0.2.0 until this is fix. 

Can you let me know if you got hunspell dictionaries installed? (anything under /usr/share/hunspell)

Thanks

**Comment by vgeof** [comment]
Hello, and thank you for your answer ! Here is my /etc/share/hunspell directory (attached)

![Capture d’écran de 2019-06-17 10-00-10](https://user-images.githubusercontent.com/44399944/59588051-022f2500-90e7-11e9-951c-caaaa0eb5f3a.png)

I'll have a look at this, but since I am a beginner, I am not sure I can help ! I'll downgrade to 0.2.0 in the meantime.

**Comment by IsmaelMartinez** [comment]
Hi @vgeof ,

Yeah, so then certainly is just picking up the dictionaries and using your default language settings. 

If you then write in the other language, or using not dictionary words, it just gets bananas trying to handle the amount of invalid words.

I see if I can do anything this week (I doubt). You shouldn't be missing much functionality from version 0.2.0 as most of the changes where options or snap release related.

**Comment by IsmaelMartinez** [comment]
That should be fixed in the next release... if you are brave enough you can use the snap edge channel (or build it from source in here).

You should be able to disable the rightclick menu (including the spellcheck) by using the following config option `rightClickWithSpellcheck=false`. Unfortunately the spellcheck and the right click menu are fairly tied together and I don't have much time now to decouple them.

**Comment by ruifm** [comment]
Any ETA on the next release? This is really bothering me, would be great to get notified!

**Comment by IsmaelMartinez** [comment]
Hi @ruifm , no ETA. You can subscribe to releases if you want to get notified. I recommend using version 0.2.0 until then.
