### ISSUE TITLE
URLs don't open in an external browser in Plasma 6

### ISSUE THREAD

**Issue by hendrikiseke1979** [IsmaelMartinez/teams-for-linux#1497]
**Describe the bug**
Since the latest Plasma Update in Debian Sid, external URLs won't open in the system's default browser (in my case Firefox) window anymore. The Not-Allowed cursor shorty flashes and the debug console writes:
```
08:51:48.380 › Requesting to open 'https://some.link'
```
but nothing happens. Internal links to other channels seem to work fine.

**To Reproduce**
1. Find a message with an external URL
2. Click on the URL

**Expected behavior**
The link opens in your default browser in a new tab.

**Desktop (please complete the following information):**
 - Debian Sid, KDE Plasma 6.2.3, Wayland
 - teams-for-linux 1.12.1, Debian package

If I can help out with more information, please let me know.

**Comment by IsmaelMartinez** [comment]
Hello @hendrikiseke1979, thanks for reporting. 

Can you check if this doesn't happen in the latest stable version ? (1.11.5) To see if this is a new issue due the electron upgrade or if it is something else. 

It might also be related to apparmour blocking the request. See if you can check this https://github.com/IsmaelMartinez/teams-for-linux/issues/1426#issuecomment-2453340003 

Let me know how you get on.

**Comment by hendrikiseke1979** [comment]
Hi @IsmaelMartinez,

after trying v1.11.5 with no success, I kept digging around a little. Found out, that teams-for-linux uses `xdg-open` to open URLs in the browser, which is [currently broken](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1088566) in Debian SID.

Closing this, thanks anyway and sorry for the fuzz.

**Comment by IsmaelMartinez** [comment]
no problem! Hope they sort it soon.
