### ISSUE TITLE
Issues on Share Screen

### ISSUE THREAD

**Issue by ramilani12** [IsmaelMartinez/teams-for-linux#1498]
**Describe the bug**
When you try to share your screen for the second time on the same call , the app crashes.
I am using this version of the app 
![image](https://github.com/user-attachments/assets/536d721c-7707-4fef-8bfd-e0aba2aef8f8)
The environment Ubuntu 22.04 with X11

**Comment by IsmaelMartinez** [comment]
This looks like a duplicated issue. See https://github.com/IsmaelMartinez/teams-for-linux/issues/1490
