### ISSUE TITLE
Calendar doesn't sync anymore

### ISSUE THREAD

**Issue by madzaf** [IsmaelMartinez/teams-for-linux#1499]
**Describe the bug**
Calendar in teams does not sync. 

**To Reproduce**
1. Go to Calendar View
2. Notice the Warning logo next to Last Updated time and the Try Again link
3. Click Try Again
4. Notice Last Updated doesn't change and meetings planned are not up-to-date

**Expected behavior**
Planned meetings should be present in calendar and sync should occur normally

**Screenshots**
![image](https://github.com/user-attachments/assets/af208f08-afa1-42b7-a524-3ff4fdc0d37d)
![image](https://github.com/user-attachments/assets/87a91adb-1444-4287-b654-d9382b17bb6f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.10
 - Installation package : deb
 - Version 1.11.5

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

```bash
teams-for-linux --webDebug --logConfig='{}'
```
WebDebug doesn't show anything related to the calendar. Logs are attached.
[teams-calendar-issue.txt](https://github.com/user-attachments/files/17934609/teams-calendar-issue.txt)

*IMPORTANT:* Ensure that you mask any sensitive information before posting the output.

**Additional context**
None

**Comment by IsmaelMartinez** [comment]
Have you tried clearing the cache? That looks more like a Microsoft issue, probably you get the same issue in the browser.

**Comment by madzaf** [comment]
Ok nevermind, it started working again today. I'll close this issue.

**Comment by IsmaelMartinez** [comment]
Microsoft strikes again. Glad is working. Cheers
