### ISSUE TITLE
Join meeting as Guest by using URL

### ISSUE THREAD

**Issue by TruputiGalvotas** [IsmaelMartinez/teams-for-linux#150]
**Is your feature request related to a problem? Please describe.**
I currently use windows virtual machine in order to join teams meeting as a Guest/Anonymous using a web browser. Tried the solution in #47 but that did not work (pasted the link to a chat, then tried clicking or ctrl+clicking - got a new teams windows which was forever initializing), but the point is that I'd like to join the meeting as guest instead of my teams account.
I've tried passing the url as a command like parameter (teams-for-linux -url https://teams.microsoft.com/l/meetup-join/19%3ameeting_ID%40thread.skype/0?context=SOME_CONTEXT) - the teams-for-linux opened with sign in page instead of with a 'Join on the web instead' button.

**Describe the solution you'd like**
I'd like to be able to join a meeting using url as a guest without needing to sign-in to Microsoft account. Preferably url should be entered using UI, but command line works too.

**Describe alternatives you've considered**
Changing user-agent in firefox gives me audio, but I can't see video - what others are screen sharing, so I though maybe teams-for-linux would give me video, but guest joining doesn't work so can't test that..

**Additional context**
This is how the process looks like in browser.
1. Open the url and see the screen which allos to open desktop app or join on the web (since this is firefox in ubuntu with modified user-agent it shows only one button):
![Screenshot from 2019-06-17 11-58-16](https://user-images.githubusercontent.com/19952587/59591842-71ad1080-90f7-11e9-9528-b201a31ec6a5.png)
2. By pressing join on the web, you are presented with Guest/Anonymous join window, were you enter your name and set audio/video parameters:
![Screenshot from 2019-06-17 11-58-52](https://user-images.githubusercontent.com/19952587/59591906-9903dd80-90f7-11e9-82c9-ac5c624a14b4.png)
And after pressing that join now button you are in the meeting.

**Comment by IsmaelMartinez** [comment]
Hi @TruputiGalvotas , Thanks for the request.

This improvement is already been reported as #89. 

#47 should work without the Ctrl+Click (just click).

**Comment by IsmaelMartinez** [comment]
No, in principle it should work with the copy/paste and then click. :/ I am re-reading your message and missed that part, apologies. What happens when you "click" the copy/pasted link ?

**Comment by TruputiGalvotas** [comment]
@IsmaelMartinez this happens:

![Screenshot from 2019-06-17 12-20-58](https://user-images.githubusercontent.com/19952587/59593341-6c04fa00-90fa-11e9-8bba-00ae280bf5a3.png)

**Comment by IsmaelMartinez** [comment]
Can you do Ctrl+R, or even Ctrl+D and take a screenshot?

**Comment by TruputiGalvotas** [comment]
@IsmaelMartinez Ctrl+D Console output:

![Screenshot from 2019-06-17 14-31-12](https://user-images.githubusercontent.com/19952587/59601440-9fe91b00-910c-11e9-895d-2f69d9cd4881.png)

**Comment by TruputiGalvotas** [comment]
@IsmaelMartinez After a while I get this:

![Screenshot from 2019-06-17 14-41-50](https://user-images.githubusercontent.com/19952587/59601946-379b3900-910e-11e9-9e0d-75dbfc7eac32.png)

But pressing "Try again" or trying to sign-out and sign-in back again gives me the same result as in [the comment above](https://github.com/IsmaelMartinez/teams-for-linux/issues/150#issuecomment-502645284)

**Comment by TruputiGalvotas** [comment]
I also see this in the terminal:

![Screenshot from 2019-06-17 14-44-53](https://user-images.githubusercontent.com/19952587/59602074-83e67900-910e-11e9-86e2-e521276ae689.png)

**Comment by IsmaelMartinez** [comment]
Thanks, I will see when I got some time to have a look at it. Apologies but got a pretty busy life lately !

**Comment by TruputiGalvotas** [comment]
I got teams working fine in Google Chrome for Linux with no effort - tried firefox only before, so my immediate issue is gone, though using a dedicated app might be more convenient in the future, so will be waiting for that fix :)

**Comment by IsmaelMartinez** [comment]
I think #89 might fix this. I leave it open as I am less sure this will be fixed indirectly by the implementation from #89

**Comment by IsmaelMartinez** [comment]
can you try building from source? (using develop branch) 

Might be also possible using snap edge channel. We have implemented part of the xdg-open and maybe that is enough to sort this out.

Let me know how you get on with this.

**Comment by IsmaelMartinez** [comment]
@TruputiGalvotas , I will close this. Reopen if it doesn't work and/or when you (or someone else) can test this. Thanks

**Comment by IsmaelMartinez** [comment]
removed from 0.5.0 as I don't think this can be considered done... until we get confirmation that it works.

**Comment by TruputiGalvotas** [comment]
@IsmaelMartinez I will test this tomorrow

**Comment by TruputiGalvotas** [comment]
@IsmaelMartinez oh wait, how can I do that? should I use snap channel "edge"?

**Comment by IsmaelMartinez** [comment]
Any package/channel s now the xdg-open stuff so, in theory, it should open teams with the URL. Probably best using deb or rpm
