### ISSUE TITLE
SSO doesn't work for Flathub variant

### ISSUE THREAD

**Issue by alfonder** [IsmaelMartinez/teams-for-linux#1504]
**Describe the bug**
My company uses SSO with TFA for Microsoft products. This issue occurs only for Flathub variant. Meanwhile deb variant works, it is inconvenient without auto-update.

**To Reproduce**
1. Install from Flathub
2. Run
3. Enter SSO credentials on login prompt
4. The window with TFA token request is empty (see the screenshot)

**Expected behavior**
Should successfully request thee TFA token and thus pass authentication

**Screenshots**
![Screenshot from 2024-11-29 10-04-48](https://github.com/user-attachments/assets/2fad347f-45f7-4a94-bac7-8c10a2c81775)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (x11 mode)
 - Installation package flatpak from Flathub
 - Version 1.11.5

**Comment by IsmaelMartinez** [comment]
Hi @alfonder,

Flathub (and snap) can be a pain to maintain. Have you check this docs https://github.com/IsmaelMartinez/teams-for-linux?tab=readme-ov-file#debianubuntu-and-other-derivatives for the deb package?

An alternative is to use intune for the app, then you should not need to login in as intune will do it for you. That should work in Ubuntu 22.04

Hope helps

**Comment by pezz** [comment]
SSO works for me, get the prompt from my company.

Works for about a day, then I get this:

![image](https://github.com/user-attachments/assets/dd1130cd-873e-4c4b-b016-5c6c1fcb9aad)

I can still send messages and see them from others, but this message persists until I re-auth then it's good again for a while.

**Comment by IsmaelMartinez** [comment]
@pezz , that issue is tracked in https://github.com/IsmaelMartinez/teams-for-linux/issues/1357 . Again, you can use key authentication or intune to bypass this problem, but is a company policy problem what you are having.

**Comment by pezz** [comment]
@IsmaelMartinez Thanks mate. But why is it doing this now? It never used to do this, I'd auth and it'd stay that way.

**Comment by IsmaelMartinez** [comment]
I suspect Microsoft have changed something on their side as I have a similar behavior in the official MacOS app. Nothing in particular that we have changed.

**Comment by pezz** [comment]
That sucks. I have a laptop, which has had the same session for ages that I haven't nuked the storage data on, it is not giving me this message at all. I'm actually thinking of rsyncing the data from it to this machine. Be a fun test but not sure it'll work.

**Comment by selfisch** [comment]
Good morning,
same here. SSO is working fine with Flatpak on Linux Mint 21.2 and Kubuntu 24.10.
But I also have to relogin each morning on both machines since 2 weeks or so.
I also have the suspicion, that MS changed something.
Have a nice one.

**Comment by IsmaelMartinez** [comment]
@selfisch, please follow the other issue https://github.com/IsmaelMartinez/teams-for-linux/issues/1357 .

I will close this issue as it is starting to morph into others and I haven't heard back from the original reported. Do reach out back with more info and I will happily re-open it.
