### ISSUE TITLE
How to call a secondary ringer script?

### ISSUE THREAD

**Issue by daute** [IsmaelMartinez/teams-for-linux#1505]
I am using teams-for-linux (1.11.5, installed from tar.gz; **a great project, thanks!**) and since a few days we use it as phone too. That works, but there is (neither in the web version nor in teams-for-linux (of course)) the option to use/configure a "secondary ringer" (as in the Windows version), so that the PC speakers would ring too on an incoming call. And only the headphones - if I do not wear them - are very silent.

There seems to be a perfect solution for that problem - a command line option:

`teams-for-linux --incomingCallCommand /path/to/my/secondary-ringer-program.sh`

However, it does not seem to work. Is that option not meant for that task? What is it used for?
There are some bug reports, which mention secondary ringer scripts (I saw them), but no description, how it they should be called.

Best regards, Wolfgang

**Comment by IsmaelMartinez** [comment]
hey, this is duplicated with https://github.com/IsmaelMartinez/teams-for-linux/issues/1195 that unfortunately I haven't managed to solve for the new version of teams. Closing this as duplicated.
