### ISSUE TITLE
Blank/silent audio input (Ultramarine / Fedora 41 KDE Plasma)

### ISSUE THREAD

**Issue by energy-x** [IsmaelMartinez/teams-for-linux#1520]
**Describe the bug**
On two different PCs recently upgraded to Ultramarine 41 6.11.10-300.fc41.x86_64, Teams is unable to receive any audio data. Devices are set correctly and the mixer shows audio coming in for the application, but there is no audio on the receiving end. This is confirmed when doing an echo test call.

**To Reproduce**
Launch Teams
Connect to a call
Verify audio devices
Connect, audio will show on OS mixer VU for microphone, but Teams does not receive the audio data

**Expected behavior**
Outgoing audio would be heard by meeting participants

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux (Fedora 41) Plasma Edition 6.11.10-300.fc41.x86_64
 - Installation package: Flatpak
 - Version 1.12.3
 - Issue present with Intel Alder-Lake built-in audio, ASUS Xonar SE 5.1 PCIe, Plantronics USB headset and Logitech C270 webcam.

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --logConfig='{}'
```

*IMPORTANT:* Ensure that you mask any sensitive information before posting the output.

**Additional context**
Testing works via Chrome browser to mictests.com
pavucontrol shows the application under recording when a call is live, and audio is visible on the meter
This also seems to affect the Linux Zoom application, but not Webex.

**Comment by energy-x** [comment]
UPDATE: https://learn.microsoft.com/en-us/answers/questions/2129154/microphone-does-not-work-on-teams-for-linux-(pwa)
Looks like an issue with Teams and Chrome-based browsers.

**Comment by IsmaelMartinez** [comment]
Hi @energy-x , Unfortunately this looks like a Microsoft issue, thanks for reporting and putting a link to the Microsoft question page. I will leave it open for a few days and then close it as we can't do much. Hopefully they solve the problem soon.

**Comment by energy-x** [comment]
> Anyone found any fix/workaround?
> 
> My workaround: I join the meetings from my OC as well as my phone, and use the microphone and audio of the phone, leaving only the screenshare and camera on the PC. It's very tedious, frustrating, and battery-wasting, but it's the only way I found to be able to perform my job....

Firefox seems to work. Another option is to log in using Edge or Chrome, then once connected paste this URL. It will connect you to the older version: https://teams.microsoft.com/v2/?ring=general

**Comment by energy-x** [comment]
@IsmaelMartinez This appears to be resolved with PWA version 1415/24120100207, mine just updated when I restarted it.
