### ISSUE TITLE
Mic stopped working on Ubuntu

### ISSUE THREAD

**Issue by naseebpanghal** [IsmaelMartinez/teams-for-linux#1523]
**Describe the bug**
Mic stopped working suddenly on Ubuntu OS.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04/24.04
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...]
 - Version 1.12.3

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --logConfig='{}'
```

*IMPORTANT:* Ensure that you mask any sensitive information before posting the output.

**Additional context**

**Comment by ALutz273** [comment]
is a problem at Microsoft

https://learn.microsoft.com/en-us/answers/questions/2129154/microphone-does-not-work-on-teams-for-linux-(pwa)

**Comment by kolorafa** [comment]
Looks like there is some version switch functionality in teams pwa.

I locally used this trick as a workaround, by opening `https://teams.microsoft.com/v2/?ring=general` page in the electron app using the debug (Ctrl+D)

general - did make my client switch from:

```
The client version is 1415/24120100203.

Early Access through Targeted release
```

to:
```
The client version is 1415/24110115724.
```

So It did a downgrade in that case, to a more stable release.

----
Maybe it could be a nice feature in the electron app to make it easier to 'switch' versions :D 

But overall it's a Microsoft PWA issue.

**Comment by P-de-Jong** [comment]
@kolorafa that workaround fixed it for now, thanks! :+1:

**Comment by kudjomd** [comment]
@kolorafa is there a manual on how to set client version? Looks like Microsoft's fix hasn't yet arrived to me, but I'm not familiar with how electron apps work, so I don't even know where to verify the version. 

Thanks!

**Comment by P-de-Jong** [comment]
@kudjomd you can go to Settings -> About Teams

![image](https://github.com/user-attachments/assets/8377aaba-392b-4221-a141-ce898af46e39)

You can use @kolorafa's fix by:
- pressing CTRL+D
- in the console type: `window.location = 'https://teams.microsoft.com/v2/?ring=general'`
- press enter

It should now use the other version. This worked for me :)

**Comment by aquatix** [comment]
Odd that you got the 1415/24120100203 version; I had the same issue last Friday, but at the end of that day, I got an update to 207 which fixed microphone for me.

*makes note of the workaround for next time*

**Comment by kolorafa** [comment]
> Odd that you got the 1415/24120100203 version; I had the same issue last Friday, but at the end of that day, I got an update to 207 which fixed microphone for me.

I got that version both in electron app and in chrome/chromium browser even with F5. Maybe teams app remember when it was last updated and don't update to often even if there is a new version.

**Comment by Mihai-B** [comment]
It is working for me today again

**Comment by IsmaelMartinez** [comment]
Closing this issue as this is an issue in the PWA (apparently fixed). Thanks
