### ISSUE TITLE
Cannot call and empty share tray

### ISSUE THREAD

**Issue by ooverandout** [IsmaelMartinez/teams-for-linux#153]
**Describe the bug**
I cannot call anyone, since I get asked to download .exe application, when doing so - but I can join meetings.
In the meeting I open the share tray but it is empty -hence, I cannot share my screen.

**To Reproduce**
1. Try to call someone on Teams
2. Try to share screen on Teams

**Expected behavior**
Call working properly. Share Tray showing available options.

**Desktop (please complete the following information):**
 - OS: CentOS
 - rpm
 - Version 0.3

**Comment by IsmaelMartinez** [comment]
hi @ooverandout , can you use the issues template? thanks.

**Comment by stefanovaleri** [comment]
Hi
same problem for me.

- OS: Ubuntu 18.04
- snap
- version edge (0.3.1 ?)

After removing the current "edge" (0.3.1) version and installing the "stable" snap  (0.3.0) everything works.

**Comment by IsmaelMartinez** [comment]
Hi @stefanovaleri , can you see if removing 0.3.0 and installing edge (0.3.1) again works? I updated some version numbers for dependencies and the spellchecker, but not the sharing functionality. I wonder if is just timings failing here (I have seen this happening at random but a while ago)

**Comment by pmihalcin** [comment]
@IsmaelMartinez 
I can confirm that when I install `edge` `0.3.1` version, then calls don't work. 
When I remove it and install `stable` `0.3.0` version, then calls work.

I tested it on `Ubuntu 18.04.2 LTS` using `snap`.

**Comment by uoramas** [comment]
Hi everybody. Confirming same problem

Using latest `edge` `0.3.1` exactly as @ooverandout mentioned.
Using `stable` '0.3.0` everything works except the webcam.

**Desktop (please complete the following information):**
 - OS: Fedora release 30
 - Installation package: snap
 - Version: 0.3.1 & 0.3.0

**Additional context**
Using Fedora here. Less than 1 week ago everything worked perfectly. Went on PTO and today around 15:00 I realised that sharing was showing a empty tray over a meeting. Shortly after that calling stopped to work.

**Comment by IsmaelMartinez** [comment]
Thanks, it must be an electron change then. Regarding the camera, make sure you enable it in snap. Check the known issues /how-to

**Comment by IsmaelMartinez** [comment]
can you try version 0.3.2 (edge in snap) 

I am fairly confident this was related to package updates. Thanks

**Comment by oliveuralive** [comment]
Good afternoon guys, I'm having the same problem

**Describe the bug**
I can not share my entire screen

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Botton share my screen'
2. Click on 'Entire screen'
3. My screen turns black


**Expected behavior**
I was hoping my friend could see my desktop

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Installation package rpm


Thank you for your attention, congratulations for the work.

**Comment by IsmaelMartinez** [comment]
Can you try snap edge channel? If not, you might need to wait until they next release is out as it might be fixed already . Thanks
