### ISSUE TITLE
App window fails to re-open after closure

### ISSUE THREAD

**Issue by robbybooker** [IsmaelMartinez/teams-for-linux#158]
**Describe the bug**
In ElementaryOS 5 (I can't speak for other distros) if the Teams window is closed the app window won't re-open again (when the icon is clicked absolutely nothing happens). If an app launch is attempted from the command line the following is output is sent (and the app window still fails to open)

```
mickeymouse@home:~/abc$ teams-for-linux
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
App already running

```

The app can be reopened if all the 'teams-for-linux' processes are killed. After killing them  'teams-for-linux' can be used successfully from the command line to start the app however note that the Gtk warnings appears then too (using the Teams icon will open the app too)

**To Reproduce**

From a clean boot:

1. Open the Teams for Linux app
2. Close the app using the standard window-close X in the window title bar
3. Try and restart/reopen the app by clicking the Teams icon or running 'teams-for-linux' from the command line
4. The app will fail to start/open

**Expected behaviour**
Each time the app icon is clicked the app window opens and Teams is running and functioning within it

**Desktop**
 - OS: Elementary OS 5.0 Juno
 - Installation package: snap
 - Version: 0.3.0

**Comment by IsmaelMartinez** [comment]
Hi @robbybooker ,

Can you check if using the deb package works? As a workaround, you can enable the "closeAppOnCross" option https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config

I think this is more related to your environment and configuration. Linux can be a bit annoying on that area.

**Comment by robbybooker** [comment]
Hi @IsmaelMartinez,

Do you have a link to the deb? I can't one anywhere

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.3.0

**Comment by IsmaelMartinez** [comment]
but i suspect is related to your desktop manager. Some users needs to use the "closeAppOnCross" when, for example, there isn't a task bar available/present. 

I am going to close with the "know issue/workaround" as it is something difficult/impossible to fix for everyone and the workaround is decent enough. Do write here if you need any help with the "closeAppOnCross" stuff.
