### ISSUE TITLE
White window on Linux

### ISSUE THREAD

**Issue by TommasoDb** [IsmaelMartinez/teams-for-linux#159]
**Problem**
Since 3 days teams-for-linux fails to open MS Teams and only show a white page.
This behaviour occurs by my and by other colleagues. We are using:
Ubuntu 16.04 on Lenovo P51 and Dell Alienware 17 
Ubuntu 18.04 on Lenovo P52
If we start the application from the terminal, no messages are shown.
The problem occurred by me and the other colleagues simultaneously.

**How to reproduce**
1. Install teams-for-linux on Linux using   
```
sudo snap install --edge teams-for-linux
sudo snap connect teams-for-linux:camera core:camera
``` 
2. Run the application from the menu or from terminal
3. The application shows now only a white page

**Expected behavior**
The normal ms teams user interface

**Screenshots**
![Screenshot from 2019-06-28 07-47-46](https://user-images.githubusercontent.com/11291183/60320435-00ccea80-997a-11e9-912d-10435524cc4a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04, Ubuntu 18.04
 - Linux nb-001309-linux 4.15.0-52-generic #56~16.04.1-Ubuntu SMP Thu Jun 6 12:03:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Installation package: snap
 - Version: 0.3.1

**Comment by herrenP** [comment]
Happens to me as well. Also using the edge version (currently 0.3.1) from Snap. I believe this started happening with the 25/6 update of the Snap package.

```
•100% ➜ uname -r
5.0.21-1-MANJARO
```

```
•100% ➜ cat /etc/os-release 
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
```

```
•100% ➜ xfce4-about -V
xfce4-about 4.13.5 (Xfce 4.13)
```

I have tried running this without any success:
```
•100% ➜ sudo snap revert teams-for-linux 
teams-for-linux reverted to 0.3.1
```

**Comment by herrenP** [comment]
The Flatpak version works just fine. Although I am not sure how to know what version I am using. I am very new to Flatpak.

```
•100% ➜ sudo flatpak install teams          
Looking for matches…
Found similar ref(s) for ‘teams’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: 
Similar refs found for ‘teams’ in remote ‘flathub’ (system):

   1) app/com.github.IsmaelMartinez.teams_for_linux/x86_64/stable
   2) app/com.teamspeak.TeamSpeak/x86_64/stable

Which do you want to use (0 to abort)? [0-2]: 1
```

**Comment by herrenP** [comment]
Apparently 0.3.0:
```
•100% ➜ flatpak list  
Name                                                Application ID                                       Version             Branch            Installation
teams-for-linux                                     com.github.IsmaelMartinez.teams_for_linux            0.3.0               stable            system
```

**Comment by chashemi-hdmi** [comment]
I am also experiencing this issue - running Ubuntu 16.04 on Alienware 17. Tried reverting to older version, uninstalling, and re-installing without any success.

**Comment by byroncollins** [comment]
same issue here on ubuntu 18.04 - seems to have been broken since 0.3.1

```
[~] snap info teams-for-linux
name:      teams-for-linux
summary:   Unofficial Microsoft Teams client for Linux using Electron.
publisher: Julian Alarcon (alarconj)
contact:   https://github.com/IsmaelMartinez/teams-for-linux
license:   unset
description: |
  Unofficial Microsoft Teams client for Linux using Electron. It uses the Web App and wraps it as a
  standalone application using Electron.
commands:
  - teams-for-linux
snap-id:      IIAJhVGfBhm393UTagoW5awtZlPDGqHd
tracking:     edge
refresh-date: 4 days ago, at 18:38 NZST
channels:
  stable:    0.3.0 2019-05-27 (15) 128MB -
  candidate: ↑                           
  beta:      ↑                           
  edge:      0.3.1 2019-06-25 (20)  66MB -
installed:   0.3.1            (19)  66MB -
```

**Comment by byroncollins** [comment]
Switching to the sable channel solves this problem by reverting the release to 0.3.0

`
[~] sudo snap switch --channel=stable teams-for-linux
[sudo] password for byronc: 
"teams-for-linux" switched to the "stable" channel

[~]sudo snap refresh --channel=stable teams-for-linux
teams-for-linux 0.3.0 from Julian Alarcon (alarconj) refreshed

[~] sudo snap info teams-for-linux
name:      teams-for-linux
summary:   Unofficial Microsoft Teams client for Linux using Electron.
publisher: Julian Alarcon (alarconj)
contact:   https://github.com/IsmaelMartinez/teams-for-linux
license:   unset
description: |
  Unofficial Microsoft Teams client for Linux using Electron. It uses the Web App and wraps it as a
  standalone application using Electron.
commands:
  - teams-for-linux
snap-id:      IIAJhVGfBhm393UTagoW5awtZlPDGqHd
tracking:     stable
refresh-date: today at 12:55 NZST
channels:
  stable:    0.3.0 2019-05-27 (15) 128MB -
  candidate: ↑                           
  beta:      ↑                           
  edge:      0.3.1 2019-06-25 (20)  66MB -
installed:   0.3.0            (15) 128MB -
`

**Comment by IsmaelMartinez** [comment]
I have experience a white screen for the 1st load, specially after installation and/or cleaning the cache. 

All the time, doing a simple Ctrl+R sorts it's out. Can you check that?

**Comment by IsmaelMartinez** [comment]
Closing as this looks duplicate with #157 .
