### ISSUE TITLE
No Notifications for calls 

### ISSUE THREAD

**Issue by jimpanse19** [IsmaelMartinez/teams-for-linux#16]
There are no visual Notifications for getting calls.
So you need to run Teams in the foreground to see if you get calls.

**Comment by IsmaelMartinez** [comment]
Yeah, this seems to be an issue in the Microsoft backlog:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35178040-audio-video-calls-not-working-between-team-users
also for groups
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18702130-notification-when-a-team-call-starts

**Comment by macmon** [comment]
I have the same problem with the version 1.0.0. When teams-for-linux is minimized or in background you can't see calling. With the official team client version 1.3.00.5153 a popup is displayed when an incoming call is received.

**Comment by IsmaelMartinez** [comment]
I thinks is an electron issue (https://github.com/electron/electron/issues/5900)
