### ISSUE TITLE
Alt button opens menu bar

### ISSUE THREAD

**Issue by gecharita** [IsmaelMartinez/teams-for-linux#160]
**Describe the bug**
Alt is commonly used with combination of other buttons (e.g. Alt+Shift, Alt+Space) in order to perform various actions (e.g. change languages, open launchers). 
Currently, Alt button opens the menu bar & removes focus from input text area.

**Expected behavior**
Alt buttons doesn't open the menu bar & loses focus.

**Desktop:**
 - OS: Linux Mint 19
 - Installation package: snap
 - Version 0.3.0

**Additional context**
https://electronjs.org/docs/api/frameless-window
https://stackoverflow.com/questions/39091964/remove-menubar-from-electron-app

**Comment by filipvh** [comment]
Make a shortcut to hide/show the bar, not only 'alt' ?

**Comment by IsmaelMartinez** [comment]
This might be difficult one as that is the default electron shortcut. I don't have much time but will mark it as enhancement.

**Comment by IsmaelMartinez** [comment]
Had a check around and is not possible to override the electron default shortcuts. Sorry but this is an electron issue. Report it in there if you want something done. Apologies but I can’t help on this one.
