### ISSUE TITLE
Camera not detected (while supported in Chromium)

### ISSUE THREAD

**Issue by BOFH2k** [IsmaelMartinez/teams-for-linux#161]
While the microphone (Lifecam Cinema Analog Mono) is detected fine in the device settings, the camera device of aforementioned USB webcam isn't (and thus the camera toggle is disabled).
![Bildschirmfoto von 2019-06-28 19-20-39](https://user-images.githubusercontent.com/8309571/60359643-e62a5e00-99d9-11e9-85be-8f0e86e4c231.png)
In contrast, the USB webcam works just fine in the Teams webapp with Chromium:
![Bildschirmfoto von 2019-06-28 19-22-35](https://user-images.githubusercontent.com/8309571/60359706-1d990a80-99da-11e9-8c2b-8a0f68477603.png)

Desktop (please complete the following information):
    OS: Ubuntu 18.04
    Installation package: snap
    Version: 0.3.0

**Comment by IsmaelMartinez** [comment]
Hi, can you fill the issue template? I will avoid going back and forward with simple questions about OS, version, etc. Thanks

**Comment by IsmaelMartinez** [comment]
Also, if using snap, read the docs. You need to activate the camera

**Comment by julian-alarcon** [comment]
Check the documentation to enable the camera feature here @BOFH2k  https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#use-camera-using-the-snap-build

**Comment by BOFH2k** [comment]
Thanks a lot,
that worked.
