### ISSUE TITLE
Webcam is not automatically connected in snap

### ISSUE THREAD

**Issue by sebastiaansamyn-tc** [IsmaelMartinez/teams-for-linux#162]
**Describe the bug**
When installing the snap (on ubuntu 19.04), the camera is not automatically connected, so the webcam is not available for usage during calls.

**To Reproduce**
1. snap install teams-for-linux
2. start the app
3. video calls are not available

```
➜ snap connections teams-for-linux 
Interface               Plug                                    Slot                     Notes
browser-support         teams-for-linux:browser-support         :browser-support         -
camera                  teams-for-linux:camera                  -                        -
desktop                 teams-for-linux:desktop                 :desktop                 -
desktop-legacy          teams-for-linux:desktop-legacy          :desktop-legacy          -
gsettings               teams-for-linux:gsettings               :gsettings               -
home                    teams-for-linux:home                    :home                    -
network                 teams-for-linux:network                 :network                 -
opengl                  teams-for-linux:opengl                  :opengl                  -
pulseaudio              teams-for-linux:pulseaudio              :pulseaudio              -
screen-inhibit-control  teams-for-linux:screen-inhibit-control  :screen-inhibit-control  -
unity7                  teams-for-linux:unity7                  :unity7                  -
upower-observe          teams-for-linux:upower-observe          :upower-observe          -
wayland                 teams-for-linux:wayland                 :wayland                 -
x11                     teams-for-linux:x11                     :x11                     -
```

**Expected behavior**
After installation the camera just works.

**Way to fix it manually**
```
➜ snap connect teams-for-linux:camera core:camera
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Installation package: snap
 - Version: 0.3.0

**Comment by IsmaelMartinez** [comment]
This is how snap works so not an issue. Thanks

**Comment by sebastiaansamyn-tc** [comment]
In that case it would be nice to have that documented somewhere. Now it's not obvious at all.

**Comment by IsmaelMartinez** [comment]
Is in the know issues/how-to. There was an open ticket to show a Pop up for snap but no one had the time to do it so I just close it. I got almost no time with just support plus my work and normal life.

**Comment by julian-alarcon** [comment]
Hi @sebastiaansamyn-tc . I had a pending task to improve the documentation. There is current PR for that.
https://github.com/IsmaelMartinez/teams-for-linux/pull/167

**Comment by julian-alarcon** [comment]
@sebastiaansamyn-tc I updated the Snap description and added an image where the option to enable the camera is available https://snapcraft.io/teams-for-linux
