### ISSUE TITLE
Disable call quality feedback survey page after a video/audio call has ended.

### ISSUE THREAD

**Issue by ambersariya** [IsmaelMartinez/teams-for-linux#166]
**Describe the bug**
Not so much a bug I guess but it's annoying to have to see the call quality feedback page after every single call. It would be great to either dismiss it automatically or bind the `Esc` key to dismiss it manually.

**To Reproduce**
1. Have a call with a contact
2. End the call
3. Call quality feedback page comes up with a dismiss button

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Installation package: snap
 - Version: 0.3.0

**Comment by IsmaelMartinez** [comment]
I think this might be a tricky one as I don't see a clear value in the angular settings object... but I keep it open to see if someone can have a play with it.

**Comment by rumatoest** [comment]
This is MsTeams feature. There is no reason to remove it.

**Comment by IsmaelMartinez** [comment]
Yeah, closing then as I don't really have the time at the moment.
