### ISSUE TITLE
Lunching snap app from terminal not respecting yarg arguments

### ISSUE THREAD

**Issue by speakradmin** [IsmaelMartinez/teams-for-linux#169]
**Describe the bug**
Snap app does not appear to respect yargs

**To Reproduce**

1. Fresh install of Kubuntu
2. Install teams-for-linux snap from KDE Discover
3. Run `teams-for-linux --closeAppOnCross true` from terminal
4. Try to close teams-for-linux by closing window
5. Closes to system tray but app stays open

**Expected behaviour**
If yargs are not supported in snap app, then running from terminal should return "unexpected parameter" error message.

**Desktop (please complete the following information):**
 - Kubuntu 19.04
 - snap
 - 0.30

**Additional context**
I'm not 100% sure whether yargs are only used when the app is installed from source but I assume that's the case. Either way it would be nice to be able to specify launch parameters for the snap or debian apps. Unless I'm doing something wrong?

Ideally, it would be great to have a simple preferences dialogue that lets novice users configure the launch options from there.

**Comment by IsmaelMartinez** [comment]
have you tried `teams-for-linux --closeAppOnCross=true`

otherwise, you should be able to create a config file in the snap config folder. 

I don't use snap (due company policy constrains) so I will just put it as a question/snap.

**Comment by speakradmin** [comment]
`teams-for-linux --closeAppOnCross=true` works for the deb package but not for snap. I'd be happy to test and provide feedback on the snap package if you need.

**Comment by speakradmin** [comment]
Ok the edge version does work with `--closeAppOnCross=true` Sorry about not trying that first :-P Although I also didn't think to try = instead of just a space.
