### ISSUE TITLE
Screen Sharing on Fedora 29 running in 15.1.0 build-13591040 does not work

### ISSUE THREAD

**Issue by JoeyG1973** [IsmaelMartinez/teams-for-linux#177]
**Describe the bug**
I click the screen share button, but I get no options to share in the pulled up drawer

**To Reproduce**
see above

**Expected behavior**
I should see option to share my desktop or app.

** screen shot **
![Screenshot from 2019-07-18 12-27-16](https://user-images.githubusercontent.com/10002637/61474903-9b0bc700-a957-11e9-9dae-16a3680f1643.png)

**Desktop (please complete the following information):**
 - OS: fedora 29
 - Installation package flatpack
 - Version 3.0

**Additional context**

**Comment by JoeyG1973** [comment]
RPM works but only partially... I can only share certain apps.  When I share the full screen it just shows a black screen with my mouse pointer for those viewing.

**Comment by JoeyG1973** [comment]
I am beginning to think this is an issue with wayland.

**Comment by JoeyG1973** [comment]
Yes the issue is with wayland.  I do not know exactly what the issue is but when I switched to gnome on xorg it is working fine.

**Comment by IsmaelMartinez** [comment]
Maybe modify the desktop startup as in this comment?

https://github.com/IsmaelMartinez/teams-for-linux/issues/35#issuecomment-474760816

I will close it as we can't do much in here, but keep us posted. Thanks!
