### ISSUE TITLE
On 0.1.9 we get whitescreen when redirected to organisations login page

### ISSUE THREAD

**Issue by thenewnano** [IsmaelMartinez/teams-for-linux#18]
The login from outside our intranet works, as we get redirected to an Microsoft page. 
but when inside intranet the basic auth login page works on 0.1.9 but after login a white page is shown. 
I did refresh and it didn't help, closing the app an opening it again now it is logged in. 
I can't see what really changed between 1.9 and 1.8 to cause that.

**Comment by IsmaelMartinez** [comment]
Hi @thenewnano ,

The only change that I can see that might be making this fail is the persistence, but, saying that, maybe the best is to try to disable ntlm (ntlmV2enabled) and the whitelist (authServerWhitelist).

`teams --ntlmV2enabled false --authServerWhitelist none`

 If this doesn't solve it, try removing the persistence
`teams --partition nopersist`

Hope helps,

**Comment by thenewnano** [comment]
Hi and thank you for the response, and the great work this App is! 
I'll try it tomorrow while at the office to see if it helps, turning off prescience would be sad , so I don't deploy 0.1.9 yet until we figure this out.

**Comment by thenewnano** [comment]
I can't see the issue on my computer anymore, this could be on the first setup only issue. 
Anyways... I'll close the bug and reopen it if the issue persists, I'll announce to users they should upgrade.

**Comment by IsmaelMartinez** [comment]
I think I have seen the culpit of this as sometimes the "angular" object is not present. I will see if I can get some time to strength the app, but that have lower priority as it seems to be only in rare occurrences mostly after the initial install.
