### ISSUE TITLE
Snap does not run from Wayland Session

### ISSUE THREAD

**Issue by zigford** [IsmaelMartinez/teams-for-linux#180]
**Describe the bug**
Snap package immediately exits if run from within a wayland session. Additionally, if you have had a wayland session running, then switch to Xorg, the same problem exists as described [here](https://forum.snapcraft.io/t/electron-apps-and-wayland/12315)

**To Reproduce**
1. Install the snap
2. Ensure your logged into a Wayland session over Xorg
3. Attempt to run snap
4. Nothing happens

**Expected behavior**
The app opens

**Desktop (please complete the following information):**
 - OS: Gentoo linux
 - Installation package snap
 - Version [0.3.0] and [0.4.0]

**Additional context**

**Workaround**
A workaround is to set env variable `DISABLE_WAYLAND=1 snap run teams-for-linux`
This forces the electron app to fall back to XWayland

Possibly the cause of #151

**Comment by IsmaelMartinez** [comment]
That is now building and should be soon in snap 0.4.1 (edge) - build 27 I think...

Thanks for reporting and, even better, fixing!!
