### ISSUE TITLE
Open actions from cards in system browser window

### ISSUE THREAD

**Issue by orange-buffalo** [IsmaelMartinez/teams-for-linux#182]
When there is an action in a card (like those posted by Jira, Jenkins and other connectors) 
![image](https://user-images.githubusercontent.com/4532247/61597930-05737e80-ac5a-11e9-98bc-43070854b76d.png)
and user clicks the action button (regardless if with Ctrl or without), a new Electron window is opened without a URL bar: 
![image](https://user-images.githubusercontent.com/4532247/61598051-4fa92f80-ac5b-11e9-9535-9f2513f49d3a.png)

Ideally a system browser window should be opened, but at least heaving a URL bar would be a workaround to manually copy the URL. 

I believe some work in this direction has been done by @HarlemSquirrel in https://github.com/HarlemSquirrel/teams-for-linux/commits/external-requests-made-by-js, but the pull request was not merged, I guess...

**Comment by IsmaelMartinez** [comment]
Hi @orange-buffalo ,

I don't think it is possible to share the context between electron internal browser and your other browsers. Meaning, if your are loged in one, doesn't mean you are logged in the other one. 

This is a chrome security functionality. 

I might be wrong but that is what understood when trying to fix the issue with the connectors not working.

If you click Ctrl+click, does it open it in a browser window?

**Comment by orange-buffalo** [comment]
Hi @IsmaelMartinez ,
Sure, it's not possible to share context between different browsers. The problem is that an action link opens in Electron window instead of a browser one, even if Ctrl+click is used..

**Comment by IsmaelMartinez** [comment]
I see, not sure if we will be able to change that, more as currently I got not much time... and it looks like I am again too busy. I leave it open and see if someone else can have a look.

**Comment by mweirauch** [comment]
How have other Electron based products solved that? Could it be there is OS-/Desktop-specific calls (and thus implementations) involved which intercept the URL at the Electron-level and then forward to the Desktop to "open this URL in the default URL-handler of the system"?

**Comment by IsmaelMartinez** [comment]
Hi @mweirauch , Not sure but probably something worth to investigate further (that is the reason I left it open). The approach @HarlemSquirrel might be in the right track, but it was opening everything in a new browser (images, or links loaded in the page, not just after a click).

What is not possible is to share the authentication, between the electron browser and the client browser, but I guess that is ok.

**Comment by IsmaelMartinez** [comment]
This is been merged in develop now so it should go into snap edge once the build is finished. 

Thanks again @HarlemSquirrel ! @mweirauch and @orange-buffalo , can you test it on the snap edge channel? If you can't get snap out, let me know and I get a pre-release (0.6.2) out.

**Comment by mweirauch** [comment]
I can only test flatpak or RPMs. Didn't flathub also offer beta channels of some sort?

**Comment by IsmaelMartinez** [comment]
hi @mweirauch , I have no idea, sorry. 

I just created a pre-release in here 
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.6.2

it got that and a "clean cache" to try to improve #171 ... so test it at your own risk! (not much, to be honest)

**Comment by mweirauch** [comment]
t4l: 0.6.2; Fedora 30

That did it! I can click the action button and the link opens in my main browser. (Ctrl+click does the same.) Haven't had the chance to text extensively, though.

Thanks guys!
