### ISSUE TITLE
Importing the config.json configuration file doesn't work in snap packages

### ISSUE THREAD

**Issue by jmayday** [IsmaelMartinez/teams-for-linux#183]
config.json seems to be not respected.

**To Reproduce**
1. Create .config/teams-for-linux/config.json
2. Fill it with content according to documentation https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config
```
{
	"closeAppOnCross": true
}
```
3. Run Teams for Linux then close it with 'X' button
4. See that processes are still present in system monitor or listed by running ps command
```
➜  teams-for-linux ps -a | grep teams
21084 tty2     00:02:35 teams-for-linux
21161 tty2     00:00:00 teams-for-linux
21186 tty2     00:02:19 teams-for-linux
21193 tty2     00:00:00 teams-for-linux
21271 tty2     00:07:17 teams-for-linux
➜  teams-for-linux 

```

**Expected behavior**
Application is closed, processes disappear. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Installation package: snap
 - Version: 0.4.0

**Additional context**
```
➜  teams-for-linux teams-for-linux --closeAppOnCross true
```
behaves correctly

**Comment by IsmaelMartinez** [comment]
Hi, snap stores the config in another folder. I think is `/home/$HOME/snap/teams*` . Let me know how you get on with this.

**Comment by jmayday** [comment]
moving config.json to ~/snap/teams-for/linux didn't help

**Comment by IsmaelMartinez** [comment]
can you move it to `~/snap/teams-for-linux/common` ? I can't use snap myself but googling seems to indicate that should be the location
https://docs.snapcraft.io/environment-variables

**Comment by jmayday** [comment]
Doesnt' help. Also tried moving to /var/snap/teams-for-linux/common.

**Comment by IsmaelMartinez** [comment]
I will see if I can add extra logs to the build so we can see where is that config folder been pick up. In the meantime, can you try using the deb/rpm package? I can't use snap so I rely on other people doing the job on that packaging system. apologies for that.

**Comment by IsmaelMartinez** [comment]
I have added more logs in the #186 . Can you get the 0.4.2 version (soon snap edge) and run it from the terminal? It will print where is trying to get the config file (configPath) and will try to print the configFile. 

If the path is right but the file doesn't print, check that is in a valid json format.

**Comment by IsmaelMartinez** [comment]
Closing as it works with a valid json. 

The location seems to be `~/snap/teams-for-linux/29/.config/teams-for-linux` where the number 29 will depend on your build version/number.

**Comment by jmayday** [comment]
I can only confirm, it works
```
➜  33 teams-for-linux                       
configPath = /home/<user>/snap/teams-for-linux/33/.config/teams-for-linux
configFile = { closeAppOnCross: 'true' }
```
