### ISSUE TITLE
Application is not running anymore after I lock and unlock PC

### ISSUE THREAD

**Issue by pmihalcin** [IsmaelMartinez/teams-for-linux#184]
**Describe the bug**
Application is not running anymore after I lock and unlock PC

**To Reproduce**
1. Start the application
2. win+L - lock PC
3. unlock PC
4. Application is not running anymore

**Expected behavior**
Application runs after PC unlock

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Installation package **snap**
 - Version **0.4.0**

**Additional context**
It started happening recently with latest 0.4.0 version. 0.3 was fine

**Comment by IsmaelMartinez** [comment]
Hi @pmihalcin ,

can you check if the deb package works for you? I am using it and got no problems.

This does smell like a system configuration issue, so not sure how much help I can give you.

Apologies.

**Comment by cheffe112** [comment]
I'm having the same problem with the snapcraft package on Ubuntu 18.04, but the deb package seems to work fine.

**Comment by IsmaelMartinez** [comment]
Can you try with "edge" channel? Just to see if it is something that is already been fixed. (they are not that different versions)

**Comment by cheffe112** [comment]
Yup, seems to work fine in the edge channel. Maybe wait for the OP to confirm, other than that I think the issue can be closed. Thanks for your great work, @IsmaelMartinez!

**Comment by pmihalcin** [comment]
@cheffe112 When you change channel to `edge`, how do you force installation of the snap?

**Comment by pmihalcin** [comment]
`0.4.1` is working properly. Thanks

**Comment by IsmaelMartinez** [comment]
Added to the 0.5.0 tag so I can document that in the release notes, just in case other people start reporting it, then I will release earlier.
