### ISSUE TITLE
Cannot open Teams on Fedora after installation

### ISSUE THREAD

**Issue by nikoskip** [IsmaelMartinez/teams-for-linux#187]
**Describe the bug**
I'm unable to open Teams for Linux on Fedora after installation. After clicking the app icon nothing happens. If I try to launch the app from the console I'm getting this error:

```
[nikoskip@localhost bin]$ pwd
/var/lib/snapd/snap/bin
[nikoskip@localhost bin]$ ./teams-for-linux 

(teams-for-linux:16690): Gtk-WARNING **: 22:11:15.919: cannot open display: :0
```

But **it works** if I use the binary `teams-for-linux` from `/var/lib/snapd/snap/teams-for-linux/current`.

**To Reproduce**
1. Install Teams for Linux using Snap
2. Try to launch the app from the Fedora's application list

**Expected behavior**
Teams for Linux successfully launch

**Desktop (please complete the following information):**
snap    2.39.2-1.fc30
snapd   2.39.2-1.fc30
series  16
fedora  30
kernel  5.1.19-300.fc30.x86_64

  - teams-for-linux
snap-id:      IIAJhVGfBhm393UTagoW5awtZlPDGqHd
tracking:     stable
refresh-date: today at 21:52 -04
channels:
  stable:    0.4.0 2019-07-19 (26) 64MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.4.1 2019-07-19 (30) 52MB -
installed:   0.4.0            (26) 64MB -

**Comment by IsmaelMartinez** [comment]
Hi, can you try edge channel? Also, if your home folder is a company folder (so not the standard /home/username) you need to reconfigure apparmour for snap to work. (sudo dpkg-reconfigure apparmour). Hope helps.

**Comment by nikoskip** [comment]
The edge channel is working, thank you!

**Comment by IsmaelMartinez** [comment]
Great, I might need to then speed up that release... got no time but there are a couple of issues that are already fixed! Thanks for reporting
