### ISSUE TITLE
Make animated gifs stop moving and collapsable

### ISSUE THREAD

**Issue by mschirmacher** [IsmaelMartinez/teams-for-linux#192]
Sorry, writing this request i realized it's actually two feature requests, Hope you don't mind ;-)

**Is your feature request related to a problem? Please describe.**
When someone links a moving gif, it keeps moving all the time which is really annoying, also it takes really much space in the thread

**Describe the solution you'd like**
First of all -- like with animated emojis -- gifs should stop moving after a few seconds or a few loops. 
Next they should be collapsble like minimizing the gif (and other images) so they don't  use that much space in threads.

**Describe alternatives you've considered**
For me, any of both solutions would be fine although i'd favor to get both - of course ;-)

**Additional context**
In slack that works like so:
![image](https://user-images.githubusercontent.com/298151/62276172-be4c7100-b443-11e9-9989-b53ff3656e47.png)
You click the down pointing arrow/triangle and the image collapses

**Comment by IsmaelMartinez** [comment]
Hi,

Sounds like a great idea. Unfortunately this is just a wrapper around the web version of teams.

You should report this into the microsoft uservoice channel. https://microsoftteams.uservoice.com/

Closing.
