### ISSUE TITLE
Allow for pasting text without markup

### ISSUE THREAD

**Issue by mschirmacher** [IsmaelMartinez/teams-for-linux#193]
**Is your feature request related to a problem? Please describe.**
When copying and pasting text, like 
```
Issue: Feature request
Suggest an idea for this project. If this doesn’t look right, choose a different type.
```
which i found right above this text area and paste it into teams, the resulting text has the same formatting like this website. 
While this MIGHT be handy sometimes i mostly find it very annoying. 

**Describe the solution you'd like**
I can imagine many solution but i am unable to overview possible side effects

**Describe alternatives you've considered**
Maybe possible Solutions:
- add a setting to disable formatting at all - so incoming, formatted text would be made raw, too
- add a warning when pasting text that contains markup and offer a button to paste it without markup
- Add a button in the compose box "Remove all formatting"

**Additional context**
We found out, that the resulting, formatted text is dependend of the SENDER'S theme. Is that a bug in `teams-for-linux` oder in the original code? Is it a bug at all?

**Comment by IsmaelMartinez** [comment]
Have you try the two different paste options? one is "paste" should do the raw paste, while "Paste and Match Style" should copy the style.

**Comment by mschirmacher** [comment]
Oh i wasn't aware this option exists - i always used the middle mouse button or ctrl+v to do it. 
In fact that would be enough for me .

Writing THIS i tested it and realized that pasting using the middle mouse button doesn't seem to paste the markup. Is that intended?

**Comment by IsmaelMartinez** [comment]
Hi, 

We use https://github.com/mixmaxhq/electron-editor-context-menu for the right menu. That could be modified to have other paste options.

Not sure what the middle button does in electron and if that context-menu can be changing its behaviour.

Are the current right click options enough for you or you think we need another one? Got no time now so it might take a weeeeee while to implement anything.

**Comment by mschirmacher** [comment]
i think it will be enough for me - there is enough work to do, i guess.
I will close this issue therefore. Thanks for your time :-)
