### ISSUE TITLE
0.5.0 AppImage fails to register

### ISSUE THREAD

**Issue by rojaro** [IsmaelMartinez/teams-for-linux#199]
**Describe the bug**
When trying to integrate the 0.5.0 AppImage i get the following error message: 
```
Failed to register AppImage in system via libappimage
```

**Observations**
I get no errors trying to do the same using the 0.4.0 AppImage and I also noticed, while the 0.4.0 gets deployed to my Applications folder as
```
teams-for-linux-0.4.0-x86_64_b36385964fe849cdbaf65590ab9cfc10.AppImage
```
the 0.5.0 release gets deployed as
```
teams-for-linux-0.5.0_00000000000000000000000000000000.AppImage
```

**To Reproduce**
1. Download [0.5.0 AppImage](https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v0.5.0/teams-for-linux-0.5.0.AppImage) from Github Releases and 'Open with AppImageLauncher'
2. Click on 'Integrate and run'
3. See error

**Comment by rojaro** [comment]
Running the AppImage from Terminal revealed the following messages:
```
$ ./teams-for-linux-0.5.0_00000000000000000000000000000000.AppImage 
AppImageLauncher error: appimage_shall_not_be_integrated() failed (returned -1)
AppImageLauncher error: appimage_is_terminal_app() failed (returned -1)

(AppImageLauncher:9104): GLib-CRITICAL **: 09:44:36.355: g_file_test: assertion 'filename != NULL' failed

** (AppImageLauncher:9104): WARNING **: 09:44:38.504: Key file contains line “ and wraps it as a standalone application using Electron.” which is not a key-value pair, group, or comment


(AppImageLauncher:9104): GLib-CRITICAL **: 09:44:38.504: g_key_file_has_key_full: assertion 'key_file != NULL' failed

(AppImageLauncher:9104): GLib-CRITICAL **: 09:44:38.504: g_propagate_error: assertion 'src != NULL' failed

** (AppImageLauncher:9104): CRITICAL **: 09:44:38.504: Desktop file has no Exec key
```

**Comment by IsmaelMartinez** [comment]
Same as #197 . Ca. You try the workaround suggested in that there? Thanks

**Comment by rojaro** [comment]
This is **not** the same issue - however i also have the same problem that is referenced in #197.

1. The registration of the AppImage fails upon first run.
2. The name of the deployed file does not look right as well. 

So i would assume that there is a problem with the built AppImage. It is not consistent with the 0.4.0 release.

**Comment by IsmaelMartinez** [comment]
I think is th same base issue. However, I will reopen this once I get
some time. I suggest using an alternative package in the meantime.

**Comment by IsmaelMartinez** [comment]
Can you try 0.5.1 (pre release) https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.5.1

**Comment by rojaro** [comment]
Sorry to report that the issue prevails.
After running through AppImageLauncher it is installed as `teams-for-linux-0.5.1_00000000000000000000000000000000.AppImage` in the Applications Folder and it quits with the same error message as before.

**Comment by IsmaelMartinez** [comment]
Will then need to wait until I get some time. Apologies but use another
package type.

**Comment by alfsch** [comment]
Yes, still the same.
![Screenshot from 2019-08-07 07-28-55](https://user-images.githubusercontent.com/6358461/62597133-4966b480-b8e5-11e9-9c99-d5b95c93fe38.png)

**Comment by IsmaelMartinez** [comment]
I think #201 will fix this. Hope to get something in a pre-release state this morning. Ta

**Comment by IsmaelMartinez** [comment]
You might feel this is a dejavu.. but can you try version 0.5.1? https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.5.1 That now has the #201

**Comment by rojaro** [comment]
Looks like it is working now. At least the error message went away. The filename of the integrated application still looks wrong though ("teams-for-linux-0.5.1_00000000000000000000000000000000.AppImage").

**Comment by rojaro** [comment]
Something still seems to be wrong. After having closed (quit) the application, i tried to start it again, but it just gets stuck on the initialization screen.

![image](https://user-images.githubusercontent.com/488677/62614569-fbb17280-b90b-11e9-88d9-eadb6f69d210.png)

**Comment by rojaro** [comment]
Seems it only works if i delete the `~/.config/teams-for-linux` directory before trying to start the application. If i don't delete it, the application just gets stuck at the initizliation screen.

**Comment by IsmaelMartinez** [comment]
this is the "blank" issue. https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#blank-page so not related to this issue. I will see if I can pack this at lunch time and release with 1.0.0. That blank-page issue might need to be deal better but at the moment got a workaround (unfortunately, some people suffer it more than others)

**Comment by rojaro** [comment]
Ok, then i think you can close this issue.
Should i setup a separate ticket for the naming issue?

**Comment by IsmaelMartinez** [comment]
close, release 0.6.0 coming soon.
