### ISSUE TITLE
Unable to resize text 

### ISSUE THREAD

**Issue by spstarr** [IsmaelMartinez/teams-for-linux#20]
Would be nice to be able to resize the window text since it's small.

**Comment by IsmaelMartinez** [comment]
you can do ctrl++ and ctrl+-

**Comment by spstarr** [comment]
ctrl - works, but ctrl + doesn't, so once I shrink it its not letting me resize it larger.

**Comment by IsmaelMartinez** [comment]
maybe, due your keyboard, you need to do ctrl + swift + ...

**Comment by spstarr** [comment]
Hi Ismael,

Thanks, yes ctrl + shift + works
