### ISSUE TITLE
0.5.0 shows "nag" screen

### ISSUE THREAD

**Issue by rojaro** [IsmaelMartinez/teams-for-linux#204]
When running 0.5.0 (and 0.5.1) for the first time, the user is presented with this screen after the login:

![image](https://user-images.githubusercontent.com/488677/62616002-c3f7fa00-b90e-11e9-89fd-79067903fa99.png)

This does not happen with 0.4.0.

**Comment by IsmaelMartinez** [comment]
Is that only the 1st login?

**Comment by rojaro** [comment]
Yeah, but it does not happen with 0.4.0 under the same circumstances.

**Comment by IsmaelMartinez** [comment]
yeah, not sure what ms have changed on those checks, I will leave it open
for now and see if it can go away somehow.

**Comment by alfsch** [comment]
0.6.0, too

**Comment by IsmaelMartinez** [comment]
If you just wait, does it go away? I have seen it before but normally trigger continues to the app after a few seconds (10 or so)

**Comment by whofferbert** [comment]
I am seeing the same thing, and the screen does not go away automatically, even after waiting more than 60 seconds. It does seem to only happen once, so long as nothing happens to the ~/.config/teams-for-linux/ dir

**Comment by alfsch** [comment]
Next time when I've to delete the config folder again, I will wait a bit longer to check this issue with 0.6.0 on Ubuntu 18.04.1 HWE Kernel 5.0

BR,

Alfred

**Comment by whofferbert** [comment]
I blew away the ~/.config/teams-for-linux directory again and did some more testing/waiting.

12 minutes after relaunching teams, it was still sitting on the screen, waiting for a click on "Get the Windows app / Use the web app instead"

**Comment by IsmaelMartinez** [comment]
Hi @whofferbert , @rojaro  and @alfsch . Two things:

* Can you try to register the xdg-open? (just open a link like this one in your browser)
https://teams.microsoft.com/l/meetup-join/19%3ameeting_ID%40thread.skype/0?context=SOME_CONTEXT 
That might be the thing that is making my screen disappear almost instantly.

Alternatively, It might be possible to hide that screen if we get an identifier. I can't really get it as it goes in a few seconds.

We then maybe try to add another line in here to "hide" that (not sure if that will work)
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/customCSS/index.js#L6

**Comment by whofferbert** [comment]
Hey, thanks for the ideas.

I registered the link with xdg-open, and that did not fix it.
As another test, I also copied the /usr/share/applications/teams-for-linux.desktop to ~/.local/share/applications/ , and that did not resolve it either.

I poked around a bit more, and in the --help output, I noticed the default user agent was "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3835.0 Safari/537.36" 
I added a line to my ~/.config/teams-for-linux/config.json setting the chromeUserAgent to "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36"

(primary difference above is the X11; Linux x86_64 vs Windows NT 10.0; Win64; x64)

This seems to have corrected it for me. I blew away the Cache, Service Worker, and Local Storage stuff under ~/.config/teams-for-linux , relaunched, and got no nag screen. Previously, clearing just those dirs would trigger the nag screen again the next time teams was opened

**Comment by IsmaelMartinez** [comment]
That might have sneak in as a change when trying to get the screenshare to work again. Can you have a look if screenshare still works with those settings? Thanks!

**Comment by IsmaelMartinez** [comment]
I think the sharing will work. anyone happy to do a PR? 

Changing this userAgent line:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/index.js#L56

to "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3831.6 Safari/537.36" 

And the https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md file also... that seems to be out of sink.

Thanks in advance!

**Comment by IsmaelMartinez** [comment]
@whofferbert , Thanks again for finding the fix and for the PR! You are a star. 0.6.5 should be in the edge channel. That will need a clean config otherwise some conversations might be hidden.

**Comment by IsmaelMartinez** [comment]
just pre-releases 0.6.6 so people that don't use snap can test it also. 
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.6.6

**Comment by alfsch** [comment]
works with 0.6.6 :+1:
