### ISSUE TITLE
0.6.0 stuck on "initializing..."

### ISSUE THREAD

**Issue by mattdconnell** [IsmaelMartinez/teams-for-linux#207]
**Describe the bug**

(I'm using the AppImage version)

When launched, a window appears, but connection never completes.  The title bar says "Microsoft Teams - initializing..."

I've experienced this issue in past builds, but only occassionally.  0.6.0 does this to me every time.

**To Reproduce**
1. Launch AppImage version
2. Observe blank window

**Expected behavior**

Program launch or some kind of error message

**Screenshots**

![20190807-105227](https://user-images.githubusercontent.com/11819288/62637640-8640a480-b901-11e9-956b-53d4e8ff9fcc.png)

**Desktop (please complete the following information):**
 - OS: Gentoo Linux (4.19.57), XFCE desktop (4.12)
 - Installation package: App Image
 - Version: 0.6.0

**Additional context**

As stated previously, I would get this behavior *once in a while* with other versions.  I would simply quit the application, relaunch it, and things would work fine.  I can't seem to get this to stop with the latest version.

**Comment by mattdconnell** [comment]
Perhaps I filed this bug prematurely.

I was able to resolve the issue by wiping the config directory (`~/.config/teams-for-linux/`) and when I launched the appimage, I was prompted to log in, and I was able to do so successfully.

Not sure if you want this bug to remain open or not, but there may be a configuration incompatibility between versions?

**Comment by IsmaelMartinez** [comment]
Thanks for reporting. This is a duplicated #171
