### ISSUE TITLE
Debian package uses deprecated gir1.2-gnomekeyring-1.0

### ISSUE THREAD

**Issue by jpiautinity** [IsmaelMartinez/teams-for-linux#208]
**Describe the bug**
Installing the .deb package under debian testing (bullseye) or stable (buster) fails due to not installable dependency to gir1.2-gnomekeyring-1.0 . 
libgnome-keyring is deprecated and it's use strongly discouraged [1]; hence gir1.2-gnomekeyring1.0 was removed in debian buster.
The debian and GNOME teams recommend using libsecret/gir1.2-secret-1 [2] instead.

I am reporting this as a bug as version 0.4.0 does not require gir1.2-gnomekeyring-1.0

**Steps to reproduce the behavior**
1. use either debian buster/stable or debian bullseye/testing 
2. dpkg --install teams-for-linux_0.6.0_amd64.deb
3. apt --fix-missing install
4. Get error message that gir1.2-gnomekeyring-1.0 is not  installable

**Expected behavior**
No deprecated libraries should be used.

**Desktop**
 - OS: Debian GNU/Linux
 - Installation package: teams-for-linux_0.5.0_amd64.deb, teams-for-linux_0.6.0_amd64.deb
 - Version: 0.5.0 and later

**References**
[1] https://gitlab.gnome.org/GNOME/libgnome-keyring/commit/6a5adea4aec93
[2] https://wiki.gnome.org/Projects/Libsecret

**Comment by IsmaelMartinez** [comment]
Hi @jpiautinity , Thanks for reporting! Its probably one of the package.json version updated. I will see if/when I can have a look at it, but not sure if I can do much from the electron side of things.

**Comment by IsmaelMartinez** [comment]
Seems to be fix in here:
https://github.com/develar/app-builder/commit/5768a760e60a1d3259684bb6f4636504507967b6

Comment in electron-builder in here:
https://github.com/electron-userland/electron-builder/issues/4033

unfortunately, waiting for an extra release, so blocked for the moment.
Seems to be electron-builder

**Comment by IsmaelMartinez** [comment]
Seems like 21.2.0 fixes this issue. building now and it should go to snap --edge channel... so hopefully doesn't breaks anything and I can ship it in the next release.

**Comment by IsmaelMartinez** [comment]
I just done a pre-release in here so you can test it.
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.6.7

Once confirmed, I will start preparing the proper release docs, etc.

**Comment by jpiautinity** [comment]
I just installed 0.6.7 and can confirm that the dependency has been removed and that everything installs fine now.

Thank you for taking the time to look into this.

**Comment by jlfranklin** [comment]
I have the same problem, running Debian Buster.  Installing 0.6.7 works with a warning about "glitchpeg.desktop":

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'teams-for-linux' instead of './teams-for-linux_0.6.7_amd64.deb'
The following packages will be upgraded:
  teams-for-linux
1 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.
Need to get 0 B/43.1 MB of archives.
After this operation, 61.1 MB disk space will be freed.
Get:1 /home/franklin/Downloads/teams-for-linux_0.6.7_amd64.deb teams-for-linux amd64 0.6.7-504 [43.1 MB]
(Reading database ... 325979 files and directories currently installed.)
Preparing to unpack .../teams-for-linux_0.6.7_amd64.deb ...
Unpacking teams-for-linux (0.6.7-504) over (0.4.0-419) ...
Setting up teams-for-linux (0.6.7-504) ...
Could not parse file "/usr/share/applications/screensavers/glitchpeg.desktop": Key file contains line ?several times a second.  After a while, finds a new image to corrupt. Written by Jamie Zawinski; 2018.? which is not a key-value pair, group, or comment
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for desktop-file-utils (0.23-4) ...
```

**Comment by IsmaelMartinez** [comment]
Hi @jlfranklin , That looks more like you got another desktop application called glitchpeg (https://manpages.ubuntu.com/manpages/disco/man6/glitchpeg.6x.html) installed but that desktop file got a new line character in it. 

I don't think is related to this issue nor to teams-for-linux. Thanks.

**Comment by jlfranklin** [comment]
Hmm.. indeed. dpkg reports that file comes from xscreensaver-data-extra.  Sorry for the noise.
