### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by gitdode** [IsmaelMartinez/teams-for-linux#214]
Hello Ismael, thanks so much for helping me to use a full-featured Teams :-)
Any way to buy you some coffees without PayPal?

Cheers,
Torsten

**Comment by IsmaelMartinez** [comment]
Thanks @gitdode , I think both "Sponsor" options end up with Paypal. 

You can send it to my Monzo account (https://monzo.me/ismaelmart%C3%Adnezramos) . That in theory accepts google pay and international payments (but never tried).

Thanks again and I am glad to help.
