### ISSUE TITLE
Blank window after login

### ISSUE THREAD

**Issue by paulgrove** [IsmaelMartinez/teams-for-linux#219]
After succesfully logging in I just get a blank (white) page.  The window title bar reads "Microsoft Teams - initialising...".

![image](https://user-images.githubusercontent.com/184906/62859795-1f066400-bcf6-11e9-929a-9d19539e6988.png)

Eventually after a few minutes I get his page:
![image](https://user-images.githubusercontent.com/184906/62859515-3f81ee80-bcf5-11e9-9220-3cdc24f6c9c8.png)

I've been using this application for about a month, and only today I have an issue.

I was using version 0.5.0, since getting this issue I've tried upgrading to 0.6.6 with the same result.

The webDev console has a couple of errors in it:
![image](https://user-images.githubusercontent.com/184906/62859636-97205a00-bcf5-11e9-89f1-d7db38f2d401.png)

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Installation package rpm
 - Version 0.5.0, 0.6.6

**Comment by IsmaelMartinez** [comment]
Hi @paulgrove , did you clean your config folder?

**Comment by paulgrove** [comment]
Oh ok, that did the trick!

Thanks!

**Comment by drjarno** [comment]
Hi, I have the same issue. If I clean the config folder it will work after logging in, but the next time I start Teams, I get the blank screen again. This started happening a few days ago.

The error messages that @paulgrove posted are the same for me.
![image](https://user-images.githubusercontent.com/51178010/63045874-46e4fb80-be9f-11e9-9d1d-c0b0e2036531.png)

**Comment by IsmaelMartinez** [comment]
Did you install 0.6.6? This issue is #171 (duplicated) .

**Comment by drjarno** [comment]
Doh, sorry. I looked at the commits since the last stable, 0.6.0, but I didn't notice it was fixed since. Sorry for the noise. It works fine now after clearing the config. Thanks!

**Comment by IsmaelMartinez** [comment]
I did mention in another commit that I should probably leave this sort of issues open while they aren't out of the door... learning every day...
