### ISSUE TITLE
No spell check occurring for English in 0.6.0 Snap or RPM

### ISSUE THREAD

**Issue by pnickerson-cashstar** [IsmaelMartinez/teams-for-linux#220]
**Describe the bug**
When I misspell words in a text window, they are not red underlined, and right clicking them does not bring up any corrections.

**To Reproduce**
1. Go to a chat screen.
2. Type a misspelled word in a text box.

**Expected behavior**
The word should be underlined red, and right clicking the word should show spelling corrections.

**Screenshots**
![image](https://user-images.githubusercontent.com/15981736/62881819-a48e1200-bcfe-11e9-9e0e-75fd1d067cac.png)

**Desktop (please complete the following information):**
 - OS: Fedora 30 (Workstation Edition)
 - Installation package: Snap and RPM
 - Version: 0.6.6 (Snap) and 0.6.0 (RPM)

**Additional context**
My system language is en_US.UTF-8 (from /etc/locale.conf and $LANG). I have hunspell-en-US installed. /usr/share/myspell/en_US.aff and .dic exist. I've confirmed that this bug exists for me in both the Snap and the RPM packages. I've tried clearing both ~/snap/teams-for-linux/current/.config/teams-for-linux and ~/.config/teams-for-linux .

I've looked at known issues and past bugs for this project, and they seem to apply to other languages and previous versions of teams-for-linux which used different spell check methods.

I've tried running teams-for-linux from command line and didn't see any relevant errors. I'm not specifying the "--rightClickWithSpellcheck" option. I haven't figured what what "yarn start" means, yet.

**Comment by IsmaelMartinez** [comment]
Have a look at the code in here:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/rightClickMenuWithSpellcheck.js

I suspect is not picking up the hunspell location 

Try settion the env HUNSPELL_DICTIONARIES to the /use/share/myspell and see if it does the job.

Is either that or the getLocale  from node is picking up something funny. Sorry but Tuesday's are a busy day for me.

**Comment by pnickerson-cashstar** [comment]
Oh, no worries, I definitely understand being busy. I'm actually quite impressed with your dedication and responsiveness in this project.

I've got version 0.6.7 via Snap now, and still have the issue when running regularly. The HUNSPELL_DICTIONARIES variable is indeed not set.

I tried running with your suggestion two ways:
```
HUNSPELL_DICTIONARIES=/usr/share/myspell /var/lib/snapd/snap/bin/teams-for-linux
```
and
```
export HUNSPELL_DICTIONARIES=/usr/share/myspell
echo $HUNSPELL_DICTIONARIES
/var/lib/snapd/snap/bin/teams-for-linux
```
But I still did not have any spell check happening.

I'm not sure how to test `getLocale`.

**Comment by IsmaelMartinez** [comment]
Not sure if this will be because you are using myspell instead of hunspell. 

quick google for `hunspell vs myspell` says:
```
Hunspell is based on MySpell and is backward-compatible with MySpell dictionaries. While MySpell uses a **single-byte character encoding**, Hunspell can use Unicode UTF-8-encoded dictionaries.
```

So I assume they might work but we have only implemented this to work with hunspell. 

Not the neatest of solutions but you could try installing hunspell and see if that fixes your issue.

**Comment by pnickerson-cashstar** [comment]
Hmm, I do have hunspell installed, and not myspell. It looks like the Fedora package places the hunspell dictionaries in the myspell directory.
```
$ sudo dnf repoquery --installed --list hunspell-en-US-0.20140811.1-14.fc30.noarch
/usr/share/doc/hunspell-en-US
/usr/share/doc/hunspell-en-US/README_en_US.txt
/usr/share/myspell/en_US.aff
/usr/share/myspell/en_US.dic
```

**Comment by pnickerson-cashstar** [comment]
I found the instructions for running from source in `CONTRIBUTING.md`. I'm going to try that later on today when I get a chance. That'll let me try adding some logging statements in `rightClickMenuWithSpellcheck.js` to see what `getLocale` is getting.

**Comment by IsmaelMartinez** [comment]
great! those console.log statements will appear in the chrome console. So run with `yarn start --webDebug`

**Comment by pnickerson-cashstar** [comment]
Ok, looks like the problem is that my locale is somehow getting returned as `en-US` instead of `en_US`. Here's some things I logged (after I set the `HUNSPELL_DICTIONARIES` environment variable again):
```
appLocale = en-US
process.env.HUNSPELL_DICTIONARIES = /usr/share/myspell
Running spellchecker.setDictionary with locale = en-US
And location = /usr/share/myspell
```
So, even if `setDictionary` gets called, I guess it doesn't like those options.

I don't know where `remote.app.getLocale` is getting `en-US` from. I think I've got my locale set correctly on my system:
```
$ echo $LANG
en_US.UTF-8
$ cat /etc/locale.conf
LANG="en_US.UTF-8"
```
It looks like Electron's `getLocale` uses Chromium's `l10n_util`, so I might try looking at how that works.

**Comment by pnickerson-cashstar** [comment]
`en-US` is the IETF standard and `en_US.UTF-8` is the ISO 15897 standard.

**Comment by IsmaelMartinez** [comment]
maybe do like #154 and create a symbolic link. I think is the same issue. 

A code change can be done to "force" a locale, that should not be difficult as we can provide that information as a config option. Let me know if you can bypass it with the symbolic link https://github.com/IsmaelMartinez/teams-for-linux/issues/154#issuecomment-510930924

I am surprise as en_US is packaged in the spellchecker package, so it should in theory just work :/

**Comment by pnickerson-cashstar** [comment]
Ok, a symbolic link worked:
```
ln --symbolic en_US.aff en-US.aff
ln --symbolic en_US.dic en-US.dic
```
```
lrwxrwxrwx. 1 root root      9 Aug 17 12:52 en-US.aff -> en_US.aff
-rw-r--r--. 1 root root   3115 Feb  1  2019 en_US.aff
lrwxrwxrwx. 1 root root      9 Aug 17 12:52 en-US.dic -> en_US.dic
-rw-r--r--. 1 root root 539608 Feb  1  2019 en_US.dic
```
```
HUNSPELL_DICTIONARIES=/usr/share/myspell yarn start --webDebug
```
Strangely, running the snap with the environment variable set did not work:
```
export HUNSPELL_DICTIONARIES=/usr/share/myspell
HUNSPELL_DICTIONARIES=/usr/share/myspell /var/lib/snapd/snap/bin/teams-for-linux
```
Maybe snaps don't pass variables to children processes or something?

I've got an idea for making the code more robust for my particular situation, without affecting any other situation. I'm going to try a pull request, though I'm not very familiar with how to do that, so forgive me if the process is a little off.

**Comment by pnickerson-cashstar** [comment]
Ok, I've got a pull request here: https://github.com/IsmaelMartinez/teams-for-linux/pull/234

**Comment by IsmaelMartinez** [comment]
I have put a wee change request in the PR. Thanks for contributing!

**Comment by philbyjohn** [comment]
I am trying to run teams-for-linux version 1.3.3 using snap but can't enable spellcheck with the methods explained here. I ran the code using `$ HUNSPELL_DICTIONARIES=/usr/share/myspell yarn start --inspect-brk app/mainAppWindow/index.js` but get "Spellchecker is disabled!" while stepping through the code.

Not a javascript programmer, so any help would be appriciated.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/15944367/e396c46d-74a3-40ce-ae75-861b82a4af8e)

**Comment by jijojosephk** [comment]
@philbyjohn in newer versions we're using the spellcheck included with electron. So you don't have to set the hunspel dictionaries explicitly. Once the app is launched, right click on any text boxes and you'll see `Writing Languages` menu.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/5cadd2ae-edea-41b1-b75a-8d58516dce3a)

They're listed and grouped alphabetically. You can enable as many as you can. This setting is persisted. So the next time when you start, the spellcheck languages are set back again.
