### ISSUE TITLE
Support for desktop integration

### ISSUE THREAD

**Issue by orange-buffalo** [IsmaelMartinez/teams-for-linux#221]
Currently AppImage does not integrate with the desktop environment properly. For instance, it does not create `.desktop` file to launch the application. This makes it impossible to theme the Teams icon (see PapirusDevelopmentTeam/papirus-icon-theme#1861). 

Is it possible to integrate https://github.com/TheAssassin/AppImageLauncher into the AppImage assembly?

**Comment by IsmaelMartinez** [comment]
We use electron builder to build the different packages. I will put a few labels and see if someone can have a look.

**Comment by orange-buffalo** [comment]
According to [Electron documentation](https://www.electron.build/configuration/appimage):
> Since electron-builder 21 desktop integration is not a part of produced AppImage file. AppImageLauncher is the recommended way to integrate AppImages.

So it seems there is nothing to do with the build itself. AppImageLauncher should be installed on the users machines if they prefer to have a deep desktop integration for AppImage-bases projects. I've added information about this to Readme file. Feel free to merge it, if you like. I believe there is nothing to do more in this issue and it can be closed.
