### ISSUE TITLE
App doesn't start at all

### ISSUE THREAD

**Issue by drozel** [IsmaelMartinez/teams-for-linux#222]
I had 0.4 from .deb and it stopped to work after i replaced it with the last stable 0.6.0 from .deb
I get "initializing..." 
![image](https://user-images.githubusercontent.com/6229397/62922933-e70e2800-bdac-11e9-9998-b6c9771be212.png)

 - OS: Ubuntu 19.04
 - Installation package: deb
 - Version 0.6.0

**Comment by jakefisherthg** [comment]
This same error is also present for me on Ubuntu 18.04, with both version 0.6.0 and 0.5.0 from snap.

I've started seeing this issue just today without an upgrade though, possibly a change to the way teams web is working?

**Comment by mborho** [comment]
Same for me. Using snap on Ubuntu and reverted to version 0.5.0. Now it works again.

**Comment by ambersariya** [comment]
Seeing the same thing, i uninstalled the snap package and reinstalled it and it worked for a few hours and now doing this reinstall method doesn't seem to work either.

**Comment by jakefisherthg** [comment]
I've started looking at the 0.6.6 release as mentioned in #171, this is now loading the teams page for me

**Comment by RealSkeptic** [comment]
Not working with me, even with version 0.6.6. Worked fine yesterday. I get the "Initializing..." and a blank page.

**Comment by IsmaelMartinez** [comment]
Try cleaning the config folder. Check the known issues section for more info. (Blank page)

**Comment by IsmaelMartinez** [comment]
Duplicated #171
