### ISSUE TITLE
White window or hanging in "initializing..." after some hours running or sometimes after standby

### ISSUE THREAD

**Issue by mschirmacher** [IsmaelMartinez/teams-for-linux#225]
**Describe the bug**
After a few hours running, or sometimes when the app was closes but running in the systray (or how is this called nowadays?) and the laptop woke up from stand by, the app windows is completly white or hangs in the "initializing..." screen.

When that happens removing all caches is the only way to get out of this situation. I.e.
`cd $HOME/.config/teams-for-linux && rm -r **/*Cache*`

**To Reproduce**
I'm unsure how to confidently  trigger this issue. Minifying the app and putting the laptop into stand by and wake up again several times seem to be best suited.
  
**Expected behavior**
The app keeps running in a usable state.

**Screenshots**
Not yet, sorry. But i guess the description will be enough?

**Desktop (please complete the following information):**
 - OS: Debian testing/unstable, a colleague is running Ubuntu 18.04 LTS with the same issue
 - Installation package deb
 - Version Occured the first time with 0.5.0 but persits in 0.6.0

**Comment by IsmaelMartinez** [comment]
Duplicated #171. Use 0.6.6 (cleaning cache before 1st start)

**Comment by mschirmacher** [comment]
Really 0.6.6? according to  the release page its just for testing :see_no_evil:

**Comment by IsmaelMartinez** [comment]
Yeah...

**Comment by jsdevel** [comment]
happening for me too on Fedora 29.  Using 0.6.6.  Tried deleting GPUCache.  No dice.  White "Initializing..." window on startup.

**Comment by jsdevel** [comment]
deleting my ~/.config/teams-for-linux directory entirely "fixed" it for me!!!  thanks for this package!

**Comment by streaky** [comment]
It only fixes it temporarily fixed version notwithstanding.

**Comment by IsmaelMartinez** [comment]
Hi Martin, can you confirm the version you are using? Quite a few people
have reported 0.6.6 got this issue fixed. See #171

**Comment by streaky** [comment]
Sorry ignore that post, I misread something. I'm all good right now :)

**Comment by IsmaelMartinez** [comment]
Don't worry! I will try to release that version 0.6.6 (or 0.7.0) when I get some time (maybe tonight). Quite a few duplicated issues have been reported. I will see in the future if it's best to keep the issues open and edit the initial comment or something like that. Ta

**Comment by mschirmacher** [comment]
Cool! Thanks for your work :-)
