### ISSUE TITLE
GitHub authentication

### ISSUE THREAD

**Issue by Korri** [IsmaelMartinez/teams-for-linux#23]
When trying to authenticate inside the Github app, it opens the oAuth window inside by default browser, this looks like its breaking the oAuth process as it ends up on a blank page that does nothing.

Authenticating on the web version before does not seem to solve the issue either.

**Comment by IsmaelMartinez** [comment]
Hi @Korri , sorry but I don't understand. 

You need an account with Microsoft in order to use Teams. 

Some users have previously reported that the 1st run can result in a white screen. 

I will recommend trying to "refresh" the view (click on the icon and "refresh")

Thanks

**Comment by Korri** [comment]
@IsmaelMartinez sorry I meant using the gitHub app inside Teams, screenshot:
![capture_20181205 2](https://user-images.githubusercontent.com/130747/49542578-fe9f2380-f8a3-11e8-9abd-64be9e1a6929.png)

**Comment by IsmaelMartinez** [comment]
Hi,

I have added the option to open the url links ina popup.

I am not defaulting to it as it is not fully neat (you still need to close the popup after authenticating.

Have a try at the pre-release in here and let me know how it goes.
 https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.1.10

Ta

**Comment by Korri** [comment]
@IsmaelMartinez it works with the flag, but the fact that it opens every link in this popup is not idea. Also I can't restart the app without the flag as this logs me out of the GitHub app and I'm back to the previous situation.

Enabling it only for oAuth links would be the best scenario, I'm not sure if there is an easy way to differentiate them though.

**Comment by IsmaelMartinez** [comment]
Hi @Korri , the only "easy" way that I can see of adding this option it to let the user decide.

Basically, windows will open by default in a electron browser (as for the change) but, pressing the ctrl key will open them in an external browser.

It will be quite a functional change, so I might need to revert it back and/or do the opposite (open them externally by default and in a electron window if ctrl key is press)

I have commit the code and prepare the release notes but the build might take a bit of time. I will let you know once I got another pre-release (hopefully soon)

**Comment by Korri** [comment]
@IsmaelMartinez looking at the code, it looks like you could decide to open inside an internal or external my looking at the URL, that would allow to do it only for this one no?

The URL is `https://msteams-ghub.com/auth/github` I think, I thing anything starting with `https://msteams-ghub.com/auth` could be opened inside electron, and the rest in the browser.

**Comment by IsmaelMartinez** [comment]
We will then need to do the same with any URL that fails, using oauth or
another redirects... Any plugins or redirects could have the issue, and
there are a few our there. I have seen a few showing the issue (bitbucket
and the outlook link as an example)

Feel free to add a whitelist as and option that can be enabled. Adding the
ctrl+click as an option is also not a bad idea (reverting to always
external as use to be, but been able to switch to all internal and
ctrl+click). It might be worth mentioning it in the readme (known issues
section.)

I have hardly time to look into this and will appreciate any contributions.
Thanks!

**Comment by IsmaelMartinez** [comment]
@Korri , I think I am going to invert the buttons. So, with Ctrl it will open in a electron window, without it, it opens in the external browser.

I am not sure when I am going to be able to do this, as I got a few other things going on at the moment.

**Comment by IsmaelMartinez** [comment]
Assigning it to you as you should be able to "revert" the functionality if you have the time, and or implement the whitelist

**Comment by IsmaelMartinez** [comment]
I consider this been fix in 0.1.11. You can get the current code an run `yarn start` or reopen if you see this issue in release 0.1.11 (to be release in the next few days)

**Comment by IsmaelMartinez** [comment]
Hi @Korri , 

Version 0.1.11 is ready and should have cover this issue. Can you test it and reopen if is not the case?

Thanks,
Ismael
