### ISSUE TITLE
freezing on startup

### ISSUE THREAD

**Issue by alfonz19** [IsmaelMartinez/teams-for-linux#233]
Teams-for-linux freezes on startup, with blank screen and title: "Microsoft Teams - initializing"

I know it was reported before with 'solution': "delete cache & config directory". The problem is, that for me this happens every single time. Every single time I run the teams. On fedora, installed either via snap or rpm, on debian installed either via deb or snap. In version 0.6.0 or 0.6.7.

What can be done? Our company sadly made very very uninteligent decision to use M$ product, and I need to use this and reinstalling every day at least once is really problematic.

Login is via active directory with redirects to some company page and extra bothering confirmations via sms. Can this be the source of issues?

**Comment by IsmaelMartinez** [comment]
Hi, this is duplicated #171.

Make sure you clean the full config folder and use version 0.6.7. you
should only need to do this once.

Put a message in the other issue if that doesn't work. Config location
differ between packages and all the info is in that #171.
