### ISSUE TITLE
Screenshot of app?

### ISSUE THREAD

**Issue by ghost** [IsmaelMartinez/teams-for-linux#235]
Not exactly a problem but it'd be nice if you showed screenshots in the readme.md

**Comment by IsmaelMartinez** [comment]
Hi @ewardThaine , That sounds like a great idea. Open a PR with the screenshots and I will be more than happily merge it. Thanks!!

**Comment by IsmaelMartinez** [comment]
Closing as doesn't seem to be much activity on this. An MS is building the client... so this drops priority.
