### ISSUE TITLE
Teams registers as HTML file handler

### ISSUE THREAD

**Issue by spoeschel** [IsmaelMartinez/teams-for-linux#240]
**Describe the bug**
The application registers itself as handler for HTML files i.e. to be used when in Caja (MATE's fork of Nautilus) an HTML is double-clicked.

**To Reproduce**
1. Set HTML file in Caja (MATE fork of Nautilus) to open in e.g. Firefox (if not already the case)
2. Start Teams
3. Open an HTML file in Caja via double-click: The Teams window gets the focus, instead of the HTML file being opened in the configured browser. The Caja settings also show that now Teams is registered as handler for HTML files.

**Expected behavior**
Teams shouldn't touch the handler setting for HTML files (or any other file type, if applicable).

**Desktop (please complete the following information):**
 - OS: Ubuntu MATE 16.04 AMD64
 - Installation package: deb
 - Version: 0.6.0

**Comment by IsmaelMartinez** [comment]
That is strange as we only register `teams://` not html. Can you remove the handler and add it again?

**Comment by spoeschel** [comment]
After removing the handler (i.e. setting again to Firefox) and restarting Teams, again Teams is set as handler. This also affects the (fixed) 0.7.0 release btw.

**Comment by IsmaelMartinez** [comment]
we set the handler in here:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/index.js#L11

and here:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L48

Might be worth investigating if this is a "Cargo" issue and if we can fix it somehow.

**Comment by spoeschel** [comment]
Thanks for the hints. I will try to compile myself later and play a bit with that part.

**Comment by basicmaster** [comment]
Interesting....if I use the Debian package you provide (the AMD64 .deb), the described issue occurs. However when I run it from source (`yarn start`), the issue doesn't occur.

**Comment by IsmaelMartinez** [comment]
If it works from source I will just recommend running from source. As indicated, Microsoft is working on a Linux client! (At last) so no point spending time fixing things that got a workaround. 

By the way, I will continue to support this and work on small things (and merge PRs, etc) until their client is out... And that might be a good while.
