### ISSUE TITLE
Screensharings in scheduled meetings blurred

### ISSUE THREAD

**Issue by mschirmacher** [IsmaelMartinez/teams-for-linux#241]
**Describe the bug**
Since last friday, in scheduled meetings screen sharings are blurred.
It's definitly NOT the QoS kind of bad quality! It's smoothly blurred across the whole screen like it was done intentionanlly. 
Windows user can blur their background when they are in video chats - it looks like that!
Also it's only blurred for linux users and at least some Mac users hence i'm very sure it's some change microsoft did.

**To Reproduce**
1. Schedule a meeting 
2. Join it
3. let the other attendee share their screen
 
[**Screenshots**](url)
![image](https://user-images.githubusercontent.com/298151/63255523-415c2c80-c276-11e9-8bac-ad9285453ec1.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Installation deb
 - Version 0.5.0-0.7.0

**Additional context**
It looks like when the sharing attendee is a linux user too, it works as expected so maybe this only happens if it's a windows user share their screen.

**Comment by IsmaelMartinez** [comment]
Hi,

Is problably one of the things I added a while back when trying to fix the screenshare:

https://github.com/IsmaelMartinez/teams-for-linux/commit/4595b871949e6ed17479660b4eef7e7b8af16d31#diff-d1e7980e1ecb259709292b087492f722

Probably one of the ones added from line 71.

Probably the same issue as #61. I will actually close the number 61 as is a bit polluted and is probably one of those lines.

**Comment by mschirmacher** [comment]
I really don't think it's a bug in teams-for-linux
1. it happend on mac. too
2. it happend without without installing a new version
3. it's the same behavior for all versions at least since and inculding 0.5.0

**Comment by mschirmacher** [comment]
oh and 4. it does NOT happen in one-2-one calls!

**Comment by IsmaelMartinez** [comment]
Maybe then report it in AWS. We can track it here but probably not be able to do anything more. If is happening in Mac too then they should fix it.

**Comment by mschirmacher** [comment]
Sorry, what do you mean with AWS in this case?

**Comment by IsmaelMartinez** [comment]
I am in a middle of AWS training... so it just slip into this. Apologies, I mean Microsoft.

**Comment by meonwax** [comment]
Same problem for me. I'm using manually build from commit 3bb71a4.
In my case, it's a scheduled call with a Mac use sharing screen.

**Comment by IsmaelMartinez** [comment]
Can one of you report it to Microsoft? I don't think we can do anything in here if it is a Microsoft change.

I am happy to leave this open, but block, if there is a link to the user-voice with the issue. If no one adds or links it, I will close the issue (to keep things clean).

**Comment by mschirmacher** [comment]
Good news! Microsoft fixed it!
