### ISSUE TITLE
Can't connect after updating Ubuntu 18.04 to lastest updates

### ISSUE THREAD

**Issue by LowLevelMahn** [IsmaelMartinez/teams-for-linux#243]
version: 0.5, 0.6, 0.7

i've got a relative fresh Ubuntu 18.04 installation, keep it up to date on a weekly basis - last monday a update (i think it was that) make teams not connectable anymore - i've tried to revert back to 0.5, 0.6 - but still no luck - i see a white screen with title "Microsoft Team Initializing..." for 1-2minutes then a "We're sorry - we've run into an issue" screen with a sad guy

before this update/or whatever happend - everything runs smooth with your linux port - thanks alot for your work

any tips what can i do?

**Comment by LowLevelMahn** [comment]
sorry: fixed with rm -rf ~/.config/teams-for-linux

**Comment by ingsme** [comment]
Same issue here, but for me the fix was rm -rf ~/snap/teams-for-linux

**Comment by IsmaelMartinez** [comment]
hi, each different package has a different folder where it stores the configuration. Check the know_issues section if you need further information of where to find it
