### ISSUE TITLE
Crash after Login

### ISSUE THREAD

**Issue by wagnst** [IsmaelMartinez/teams-for-linux#245]
**Describe the bug**

After typing in E-Mail and Password of our companies AAD Screen the app crashes instantly and then restarts

**To Reproduce**

Open the app, type email. After redirect to AAD Login, type Email & Password. Then Crash

**Expected behavior**

Client opening up normally.

**Desktop (please complete the following information):**
- Ubuntu 18.04.3 LTS (Bionic Beaver)
- Linux xxx 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- teams-for-linux                            0.7.0-515                                    amd64        Microsoft Teams for Linux

**Additional context**
journalctl shows:

> Aug 22 09:32:17 pc-1334 kernel: teams-for-linux[7583]: segfault at b0 ip 00005616a7d48400 sp 00007ffdfea891d8 error 4 in teams-for-linux[5616a509e000+4bfb000]
Aug 22 09:32:17 pc-1334 kernel: Code: 4c 89 ff ff 50 10 48 8b 4b 10 48 c1 e1 20 48 89 88 f4 00 00 00 48 83 c4 08 5b 41 5c 41 5d 41 5e 41 5f 5d c3 cc cc cc cc cc cc <48> 8b 87 b0 00 00 00 48 85 c0 75 2c 48 8b 8f c8 00 00 00 48 85 c9

Potentially it may have something to do with MFA? I would expect the popup for entering the Microsoft Authenticator App Token, but its not appearing at all.

**Comment by IsmaelMartinez** [comment]
Hi @wagnst, that segfault looks nasty. 

Have you tried cleaning the config folder (check the [known issues section](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#config-folder-locations)), removing the app and installing it again? 

If that still the case, can you repeat the previous steps by trying one of the other packaged versions?

Also, can you specify your package? We release in different flavours and each of them has its own peculiarities.

**Comment by wagnst** [comment]
Yes I tried that already. I removed the `.config/teams-for-linux` folder, deinstalled the package via dpkg and installed `teams-for-linux_0.7.0_amd64.deb` again via dpkg. I get the same segfaults.

**Comment by IsmaelMartinez** [comment]
I can only suggest running from source and start adding more log messages to see where it breaks. It might be the MFA pop up as you suggested, but that is a difficult one for me to test. I leave it open to see if we can help. Keep us posted with your research/investigation (if you can do it). Otherwise, you might need to use the browser until Microsoft releases the Linux client (hopefully soon as they just indicated that they are working on it). Apologies for not being more helpful.

**Comment by IsmaelMartinez** [comment]
Closing this as it doesn't seem to be much activity on it. Ping back with further information if needed. Apologies but hopefully ms will have a client soon (and I will have more time for my side projects)

**Comment by wagnst** [comment]
FYI @IsmaelMartinez with the latest version it works again... used the latest .deb package under Ubuntu 19...
