### ISSUE TITLE
Open teams meeting link

### ISSUE THREAD

**Issue by emanuelbatista** [IsmaelMartinez/teams-for-linux#253]
---
name: Join the meeting via a link outside application
---

**Is your feature request related to a problem? Please describe.**
To click in meeting link outside the application, the link redirects to Teams, therefore it just focuses the team screen and the meeting didn't start inside it.

**Describe the solution you'd like**
Open the meeting inside the Team for Linux.

**Comment by IsmaelMartinez** [comment]
Hi @emanuelbatista,

Thanks for reporting. I think this is not really a bug but a feature request.

Feel free to have a look at the code and submit a PR. Unfortunately, my only time now on this is going to be invested in automating stuff and helping around.

Hopefully at some point in the future I  can get back to do coding.

**Comment by IsmaelMartinez** [comment]
Thanks a lot @emanuelbatista. I have merged this with develop so it should go soon into the snap edge channel soon. Thanks again!! I leave this open until I create a proper release, otherwise people keep creating issues for newly closed issues.

**Comment by emanuelbatista** [comment]
Thank you very much @IsmaelMartinez by your attention, I wish to help more this project in brief.
