### ISSUE TITLE
UI will not show up upon reopening[ElementaryOS]

### ISSUE THREAD

**Issue by Eduardo1911** [IsmaelMartinez/teams-for-linux#254]
**Describe the bug**
Hello,

I just installed elementaryOS and saw that there's an app for microsoft teams on snap store.

Gave it a try but i found there is a problem. If i close the UI by clicking the x button and then i try to reopen it it will not show up.

The workaround is to manually kill the teams for linux process and then start it again.

It appears that pressing x will not terminate the process(parent process and all related child processes) it will just kill the UI.

**To Reproduce**
1. Open teams for linux
2. Close the app by clicking the x in the upper left corner
3. Try opening the app again
4. Nothing happens

**Expected behavior**
App should re open normally

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: elementary OS 5.0 Juno"
 - Installation package SNAP
 - Version Latest 0.7

**Additional context**
N/A

**Comment by IsmaelMartinez** [comment]
Check the closed issues. There is an option to make it close on cross

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/issues/144#issuecomment-500117793
