### ISSUE TITLE
Restarting After First Login Causes Login Issues

### ISSUE THREAD

**Issue by LudwigTirazona** [IsmaelMartinez/teams-for-linux#262]
**Describe the bug**
After my first login, after I either reboot or restart teams-for-linux, Teams takes several minutes to load, and then eventually fails, culminating in Teams returning "We're sorry - we've run into an issue." 

Reinstalling teams-for-linux allows me to use it again, but the issue reoccurs after the first login.

**To Reproduce**
1. Log in to Teams
2. Reboot
3. Start Teams for Linux

**Expected behavior**
Normal function; It loads me into the chat screen, or asks me to login.

**Screenshots**
I've created a video and run it in debug mode, hope this helps. Skip to the end of the video if you're looking for the error message.
https://youtu.be/AiTxEfNW9XE

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04
 - Installation package: snap (The issue also exists for me in the deb file)
 - Version:0.7.0  Rev:62 Channel: stable Publisher: alarconj

**Additional context**
I've already tried the "Try Again" button, and signing in and out, but the problem persists.

I do not experience this issue in Teams for Linux under Firefox, so I believe it is not a network issue.

**Comment by lecler-i** [comment]
You can remove the config file too, to prevent reinstalling...
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#blank-page

**Comment by IsmaelMartinez** [comment]
Thanks for reporting. This is documented in the release notes and known issues. 0.7.0 needed that config cleanup as we changed the user agent. Thanks @lecler-i for the help.
