### ISSUE TITLE
Client is stuck on Initialization step.

### ISSUE THREAD

**Issue by R-Bower** [IsmaelMartinez/teams-for-linux#264]
**Describe the bug**
Teams is stuck on initialization.  Login prompt works as expected, but then it gets stuck on initializing for about 10 minutes.  After which it reports a failure.

**To Reproduce**
Launch teams.  Login and enter 2FA code.  See white UI.  Throw laptop on ground.

**Expected behavior**
Launch teams, enter credentials, respond to 2FA, use Teams.  Keep laptop on desk.

**Screenshots**
![image](https://user-images.githubusercontent.com/11933208/63791462-68d37a80-c8b0-11e9-9ed8-0e7da7296596.png)

After about 5 minutes:
![image](https://user-images.githubusercontent.com/11933208/63791645-c8ca2100-c8b0-11e9-817c-9f05bd881c82.png)

**Desktop**
 - Linux Mint Tessa 19.1, 5.2.8-050208-generic
- XPS 15 7590
- OpenGL renderer string: GeForce GTX 1650/PCIe/SSE2
 - Installation package [deb]
 - Version [0.7.0]

**Additional context**
White UI while initializing.

**Comment by stevenc7** [comment]
Hi All, I didn't realize @R-Bower has the same issue as me. After doing the fix by clearing the config folder by @whofferbert, Teams is working perfectly. Thanks a lot @whofferbert !
