### ISSUE TITLE
Process is still running when I close the app

### ISSUE THREAD

**Issue by acourtiol** [IsmaelMartinez/teams-for-linux#265]
**Describe the bug**
When I close the main window the process is still running in the background making it impossible to reopen the app later without having to kill it myself. 

**To Reproduce**
1. Launch the app
2. Click the cross icon in the title bar
3. Try to reopen/relaunch the app

**Expected behavior**
The app should quit when the main window is closed and so the process should be killed.

**Desktop (please complete the following information):**
 - OS: ArchLinux with Gnome 3
 - Installation package: tar.gz
 - Version: 0.4.0 to 0.7.0

**Comment by acourtiol** [comment]
@whofferbert thanks, it solved the issue but isn't it weird that it isn't the default behavior ?

**Comment by IsmaelMartinez** [comment]
If you look at the close issues you will have a long explanation. TLDR, no
solution will make everybody happy.
