### ISSUE TITLE
Joining Meetup

### ISSUE THREAD

**Issue by standagh** [IsmaelMartinez/teams-for-linux#266]
Is it possible to join meetup via link?
I got a link pointing to meetup - something linke this: 'https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDdhN2YzY2MtZD...'. 

How can I joint this meetup using teams-for-linux? Is it possible?

**Comment by IsmaelMartinez** [comment]
Opening the link should focus the app or start it. To open the actual meeting you need to run from source or be in snap edge. #255
