### ISSUE TITLE
"No available camera found" error after upgrade to 0.7.0 (snap and deb)

### ISSUE THREAD

**Issue by antony2025** [IsmaelMartinez/teams-for-linux#267]
**Describe the bug**
In chat or while attending a scheduled meeting, the video camera icon appears that allows the user to either enable or disable video.
After I upgraded to 0.7.0 release using either snap or deb, this icon is disabled all the time.
**However, if I use the 0.7.0 AppImage, then the camera is enabled.**
So I believe something is broken in teams-for-linux snap and deb versions.

**To Reproduce**
1. Upgrade to version 0.7.0 using either snap or deb package.
2. Open "Microsoft Teams for Linux".
3. Start a chat with someone.
4. Notice the video camera icon at the top right is disabled all the time.

**Expected behavior**
The video camera icon should be enabled, so that the user can start a video call.

**Screenshots**
![image](https://user-images.githubusercontent.com/4309910/63838470-b10c9e80-c97d-11e9-82e9-f020272356f1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS.
 - Installation package: Teams for Linux Snap package.
 - Version: 0.7.0 snap and deb packages.

**Comment by KPS-MWT** [comment]
Can you give details about your hardware (camera or laptop) and verify it works in antoher application (e.g. cheese on Gnome or similar)?

**Comment by antony2025** [comment]
Hardware: Lenovo Thinkpad T480. I have an additional USB Logitech webcam as well.

As mentioned in the ticket, the camera does not work only when I install teams-for-linux from either snap or deb packages.
Camera is recognized and works fine when I use the AppImage binary.

Could it be that snap and deb packages are missing some setting or file?

**Comment by IsmaelMartinez** [comment]
Hi @antony2025 , in snap you need to install the camera. There is also a wee annoyance when you start the app directly in a chat. (Sometimes it doesn't trigger the hacks) moving to a group chat and then back to the one2one should just work as it normally does. I have only seen that on initial loads.

**Comment by IsmaelMartinez** [comment]
And thanks @KPS-MWT for helping!! I do really appreciate.

**Comment by antony2025** [comment]
@IsmaelMartinez thank you for the answer. I will close the ticket.

**Comment by jmurrayrs** [comment]
> Hi @antony2025 , in snap you need to install the camera. There is also a wee annoyance when you start the app directly in a chat. (Sometimes it doesn't trigger the hacks) moving to a group chat and then back to the one2one should just work as it normally does. I have only seen that on initial loads

Hello, How can I install the camera correctly? I've googled and I found this command:

```
sudo snap install instagraph
sudo snap connect instagraph:camera :camera
```

After it, I needed to configure permissions on Ubuntu to use the Camera. In software center, on Ubuntu, I looked for Teams. Clicking in Permissions, I got to enable the camera...

![Captura de tela de 2019-09-11 11-25-58](https://user-images.githubusercontent.com/4536254/64707138-f609f800-d488-11e9-9871-2190e3d36737.png)

Could you help me? Exists other way to do this?

Thanks
