### ISSUE TITLE
Infinite login loop for work/organization account

### ISSUE THREAD

**Issue by tobiasbj** [IsmaelMartinez/teams-for-linux#268]
**Describe the bug**
Infinite login loop for work/organization account.
Is this not meant to work for such accounts?

**To Reproduce**
1. sudo snap install teams-for-linux  (version 0.7.0)
2. Sign with work mail
![image](https://user-images.githubusercontent.com/7911343/63852491-af040900-c998-11e9-9fed-d091a277c3da.png)

3. Get redirected to organization and enter credentials and get redirected to step 2 for infinite loop. 
It doesn't actually matter what I enter I will always be redirected to step 2.
![image](https://user-images.githubusercontent.com/7911343/63852548-d3f87c00-c998-11e9-878c-ba0b0a120fc2.png)

**Desktop:**
 - OS: Ubuntu 19.04
 - Installation package: sudo snap install teams-for-linux
 - teams-for-linux version: 0.7.0

**Comment by IsmaelMartinez** [comment]
Hi, did you clean your config folder after installing version 0.7.0?

**Comment by tobiasbj** [comment]
Hi, I'm somewhat of a "linux noob" atm, where would I find this config file? I assume it's a config file for this app specifically of which 0.7.0 is my first install so I assume that it would need no cleaning.

Also (I'll update this above), it doesn't really matter what I enter in step 3 I will always be redirected to step 4 even if it's the wrong credentials.

**Comment by IsmaelMartinez** [comment]
Hi, check the known issues. It indicates where the config folder location
is. Are you behind a proxy? If so, have a wee search in the issues
previously reported. Some of them have info of how to make it work.
Hope this helps

**Comment by IsmaelMartinez** [comment]
For the proxy, check this: https://github.com/IsmaelMartinez/teams-for-linux/issues/269#issuecomment-526096491
The config folder location to remove can be found in here:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#config-folder-locations

**Comment by tobiasbj** [comment]
Thanks for the info!

So I've tried 
("MYWORK" is a placeholder)
teams-for-linux --proxy-server=http://smtp.MYWORK.com:80
teams-for-linux --proxy-server=http://smtp.MYWORK.com:8080

For both I just get a white app window.
![image](https://user-images.githubusercontent.com/7911343/64955679-2edf0e00-d889-11e9-9554-809f4be827d4.png)

Was this the right approach?

The *Config folder* "~/snap/teams-for-linux/current/.config/teams-for-linux/" doesn't seem to exist yet. The path "~/snap/teams-for-linux/current/" exists, but is empty. I assume it'll be created at first login.

**Comment by tobiasbj** [comment]
Update: I'm able to login at home/mobile-hotspot, so it's probably something to do with the work router/proxy (as you already indicated).

**Comment by IsmaelMartinez** [comment]
Check or even ask in the other issue, maybe is the proxy and the certificate (if the proxy uses a self sign). You should see that in the logs... Hope helps

**Comment by IsmaelMartinez** [comment]
Also, can you try a deb package? snap packages can be funny with work accounts, specially if your home folder is not /home/your.name  (https://github.com/IsmaelMartinez/teams-for-linux/issues/148#issuecomment-513114747)

**Comment by IsmaelMartinez** [comment]
Closing as there isn't much activity happening. Ping back with more info and I will reopen.

**Comment by divansantana** [comment]
Just an update for others. I had an infinite loop login issue during login due to MFA. It was resolved by contacting the exchange team admins and them marking my linux device as "trusted".

**Comment by naseemali925** [comment]
Hi, I am having the same issue with an **edu.in** account. I have tried changing the timezone to current timezone(IST) and also deleted the config just to check if it works. But nothing seems to work. Even in the web version it redirects in a loop. Not sure what is happening.
