### ISSUE TITLE
How to use teams-for-linux behind a proxy (improvement/documentation)

### ISSUE THREAD

**Issue by tlo8640** [IsmaelMartinez/teams-for-linux#269]
**Solution**
Start teams-for-linux providing the proxy details as in the following command:

```bash 
teams-for-linux --proxy-server=http://proxy-host:proxy-port
```
---

Hello,
thank you for your effort to package teams for linux. But unfortunately I can't bring it to work on my machine.

**Describe the bug**
When I try to start teams for Linux I get the following message on command line:

`configPath = /home/???????/.config/teams-for-linux`
`Failed to get the config file, using default values`
`configFile = {}`
`Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"`

The Application Windows appears, but it keeps white without any content until I press CTRL-C to stop.

**To Reproduce** (only reproducable on my machine ;-))
1. Install teams-for-linux, doesn't matter rpm or Appl Image.
2. remove config folder for teams for linux
3. start teams-for linux

**Expected behavior**
I Expected a working teams for linux ;-)

**Screenshots**
![teams4linux](https://user-images.githubusercontent.com/740897/63867997-167c8180-c9b6-11e9-9e4c-501ff589951a.png)

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Installation package rpm, AppImage
 - Version 0.70

**Comment by IsmaelMartinez** [comment]
This is pretty strange. Probably Google around for the font warning and
electron. We don't use any special font and the blank screen should not
happen again (after cleaning the config folder). Have you tried doing
Ctrl+R ? (Or tab icon/refresh option?)

**Comment by tlo8640** [comment]
Hello,
I found the root cause ;-)

The fontconfig error message showed the wrong direction. I renamed the fontconfig config file what throwed the error message and tried starten teams again. The error message disappeared, but the Teams Window stayed white. So the reason must be another one.
Then I remembered that nearly every traffic is "proxied" here but I didn't configured a proxy on command line.
Setting a proxy with the bash command "export http[s]_proxy=..." didn't helped.
But if you start a chrome you can give a proxy with the following parameter:
--proxy-server=http://proxy-host:proxy-port
at least, electron is a chrome with some sugar ( ;-)) I tried the same parameter while starting teams-for linux and it works now! 
Do you know a place, where I can configure the proxy? Somewhere in the config folder...?

Perhaps there should be a hint for User who have to use a Proxy, too?

Thanks again for packaging teams for linux for users like me!

**Comment by IsmaelMartinez** [comment]
Probably documenting this at the moment will do. A better option will be to
add a config option (check the config folder) but it will require a tiny
bit of code change. Pretty easy so do feel free to play around with it and
submit a PR. Alerting about it might a bit more difficult.

**Comment by IsmaelMartinez** [comment]
@tlo8640, can you create an enhancement with your findings and, even better, document them in the known issues? No rush but any help is very welcome

**Comment by IsmaelMartinez** [comment]
I changed the title, added a few labels and edited the top issue to show the solution.

It will be great to:
* Add some documentation in the know issue section.
* Add the proxy as a config option.

Both tasks are fairly simple. I will see if I have time to explain the second part but hopefully someone can pick up the 1st part.

Thanks for reporting and finding the solution.

**Comment by juliocebrito** [comment]
Hi @IsmaelMartinez ,

Thanks! Great job, I add confilg.josn and It works for me, but now teams does not log in when I turn off the VPN connection, so I have to comment the proxyServer variable in config.json, do you have any idea how to resolve that issue?

![image](https://user-images.githubusercontent.com/9125193/236952764-1bd62c7c-bf40-4223-a52d-4067740e1757.png)

VPN not connected:
![image](https://user-images.githubusercontent.com/9125193/236952823-7c005c60-127a-4797-8f71-d0fe0b770f9f.png)

VPN connected:
![image](https://user-images.githubusercontent.com/9125193/236952860-1faea334-f141-41ef-96fc-c706d54f32fe.png)

team for linux version:
![image](https://user-images.githubusercontent.com/9125193/236952915-d7fe06fe-89ac-4e77-8450-54634b675e64.png)

Log error:
![image](https://user-images.githubusercontent.com/9125193/236952978-f7f90251-170b-43d2-82e2-15b6d616fa45.png)


Thanks in advance.

**Comment by joakim-tjernlund** [comment]
Chrome/Edge read system policies from:
```
/etc/opt/{chrome,edge}/...
```
What would dir would it be for teams-for-linux?

I want to add my proxy like so:
```
cat /etc/opt/chrome/policies/managed/proxy.json 
{
      "ProxySettings": {
          "ProxyMode": "pac_script",
          "ProxyPacUrl": "http://proxyconf.infinera.com/proxy.pac"
      },
}
```
but for linux-for-teams
