### ISSUE TITLE
Option to start in tray

### ISSUE THREAD

**Issue by supremesyntax** [IsmaelMartinez/teams-for-linux#27]
Would be nice to have an option/switch to start the application minimized in tray.
Maybe this is helpful: https://github.com/chrisknepper/android-messages-desktop/pull/46/commits/b8c33188c3550dba6d7ca0cbedc431907cb02acf

**Comment by IsmaelMartinez** [comment]
Hi @supremesyntax, that sounds great. Feel free to implement it ;) 

I hardly have time to support it so tend to try to implement fixes that are big and easy to fix.

That might change in 2019 but it does look unlikely.

**Comment by IsmaelMartinez** [comment]
@supremesyntax , you should be able to implement this by adding an option in the config.js and adding the check (and window.hide) in the index.js (the one in the app folder).

Give it a go, you will see it doesn't take that much long ;)

**Comment by supremesyntax** [comment]
I'll give it a try at the weekend - pretty busy all week long

**Comment by IsmaelMartinez** [comment]
Closing to keep things clean. reopen if you get the time to implement it... Or if more people needs it.
