### ISSUE TITLE
Stuck on "Initialising" with a blank page - only works if starting with sudo

### ISSUE THREAD

**Issue by NuxRo** [IsmaelMartinez/teams-for-linux#270]
**Describe the bug**
On subsequent startups it gets stuck on "Initialising" with a blank page.

**To Reproduce**
1. Install RPM (0.7.0)
2. Launch - works
3. Quit application and start again
4. Stuck with a blank screen, the window title says "Initialising..."

**Expected behavior**
The application should open the Teams thing.

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Installation package: rpm
 - Version 0.7.0 (release 515)

**Additional context**
I've encountered the same behaviour with previous versions.
Launching from terminal outputs little information:
```
~]$ /opt/teams-for-linux/teams-for-linux 
configPath = /home/user/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
```

**Comment by IsmaelMartinez** [comment]
Hi, duplicated. Clean your config folder. Read the release notes (1st
sentence) or the known issues (blank page/screen)

**Comment by NuxRo** [comment]
It's clean, sorry I forgot to mention. I started all my tests with
```
rm -rf ~/.config/teams-for-linux
```

**Comment by IsmaelMartinez** [comment]
Do you run behind a proxy server? If so, check the close issues. Even the
open one with the font is related to that. You need to apply some config.
Hope helps

**Comment by NuxRo** [comment]
No proxy, switched off iptables, selinux, ipv6, nothing helped.
I'll fall back to Firefox for now.

**Comment by KPS-MWT** [comment]
Can confirm. Please try starting teams-for-linux using sudo, e.g.:
"sudo teams-for-linux" from the terminal and report back if it works.

This seems to work strangely, but I would advise against using sudo for this on a regurlar base.
@IsmaelMartinez: Do we need access to files/directories outside the home and application directory?

**Comment by IsmaelMartinez** [comment]
Strange. I don't need sudo to run it. Maybe do a proper cleanup and install
it without sudo. Alternatively try snap or any of the packaging options and
see if it works. Hope helps

**Comment by NuxRo** [comment]
I tried the rpm and appimage, both exhibit the same thing.
Thanks for the effort though. Hopefully M$ will pick up the slack and provide an official client to their shitty chat.

**Comment by IsmaelMartinez** [comment]
@NuxRo, do they run ok as sudo as @KPS-MWT suggests?

**Comment by DevLaul** [comment]
Hi, maybe nothing to see, but I encountered the blank page issue too after a several weeks of use, that I resolve by clearing the cache.
It may make sense that running it with *sudo* use a different cache file, but the problem may occur too later.
Open Debug, go to Application, and clic 'Clear storage'
Sorry for my english level...

**Comment by NuxRo** [comment]
Thanks DevLaul, but that couldn't have been the issue as I start my tests with "rm -rf" of the config directory.
Funnily enough, if I do clean the storage as you describe and hit Refresh then the application opens.

If however I quite the application, next time I start it will get stuck with "Initialising" again.

**Comment by NuxRo** [comment]
I have not tried sudo, nor am I going to. I am grateful for this application, but if it requires sudo to run, then I'll just use the browser.

**Comment by IsmaelMartinez** [comment]
No problem. It should not require sudo. I just wanted to check if the sudo is a workaround for the few people are having this issue. I think this is more of a system configuration issue.

**Comment by IsmaelMartinez** [comment]
Closing this as there is a working workaround and that script I provided should be enough. Microsoft are working on the client so there is no point improving things that got workarounds (IMO). Shout if you need it reopen.
