### ISSUE TITLE
Screen Sharing is not working !!

### ISSUE THREAD

**Issue by AhmedBHameed** [IsmaelMartinez/teams-for-linux#271]
**Describe the bug**
I tried to share screen but it won't open a screen sharing !!

**To Reproduce**
1. Meeting
2. Joined the meeting
3. Try to share my screen but nothing happend
4. I see console errors

**Screenshots**
![DeepinScreenshot_select-area_20190829155918](https://user-images.githubusercontent.com/25675361/63947174-bc8fc080-ca76-11e9-8aba-17675f3bb933.png)

**Desktop (please complete the following information):**
 - OS: Deepin (Linux code with Ubuntu flavor)
 - deb 0.7.0 also tested with internal running using "yarn start"
 - Version [0.7.0]

**Comment by IsmaelMartinez** [comment]
Hi, can you provide the full flow? Try to be as descriptive as possible.
Like if I am blind. Might be one again ms changing stuff.

Can you  try version 0.5.0 and then 0.6.0 and see if anyone works? Clean
your config folder after switching versions.

**Comment by AhmedBHameed** [comment]
Hello @IsmaelMartinez ,

Thank you for your kind respond. I confirm it's working but seems (Deepin OS) has some issues identifying screens and therefor the sharing did not work (I guess).

When running on internal screen only, it works perfectly.
Thank you for taking time replying me. You are doing a really great job.
Regards.
