### ISSUE TITLE
Update Known Issues Documentation to account for Flatpak

### ISSUE THREAD

**Issue by ssoto2** [IsmaelMartinez/teams-for-linux#272]
**Is your feature request related to a problem? Please describe.**
This is in relation to teams showing a blank and page and sitting on initializing

**Describe the solution you'd like**
the known issues files advices how to resolve for manual install and snap installs. want to make sure the documentation for flatpak is there 

(FLATPAK) remove application cache located at: 
~/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux/Partitions/teams-4-linux/Application\ Cache/

**Comment by IsmaelMartinez** [comment]
Hi @ssoto2 , Thanks for reporting. Add this to the readme (known issues page). You should be able to even edit it in the web and create the PR. Thanks !

**Comment by IsmaelMartinez** [comment]
I will just do this as I am cleaning those files a wee bit.
