### ISSUE TITLE
Broken symlinks in configuration path

### ISSUE THREAD

**Issue by michalSolarz** [IsmaelMartinez/teams-for-linux#273]
**Describe the bug**
Broken symlinks in the configuration directory.

**To Reproduce**
1. Clear configuration directory
2. After launching an app, a broken symlinks SingletonCookie and SingletonLock appears

**Expected behavior**
Symlinks with valid paths appear

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Installation package aur
 - Version 0.7.0

**Comment by IsmaelMartinez** [comment]
Hi, are u using the aur from here or the one arch people build? Can check
if works fine with another package type? Thanks

**Comment by michalSolarz** [comment]
I'm installing it from this place: https://aur.archlinux.org/packages/teams-for-linux
I've tried to install both from pacman & AppImage and both of them produces broken symlinks after first launch

**Comment by IsmaelMartinez** [comment]
I can see it now. Those links only last while the app is running. 

I don't think is affecting the app itself, so yeah, probably best close and add it to electron one.

I had a quick google and couldn't find anything. In any case, thanks for reporting!

**Comment by IsmaelMartinez** [comment]
going to close it as it seems related to electron and doesn't affect the app running.
