### ISSUE TITLE
Download to ~/Downloads, without file save pop-up

### ISSUE THREAD

**Issue by lkrms** [IsmaelMartinez/teams-for-linux#274]
I often need to save a bunch of images or attachments supplied via Teams for local manipulation. Having to (1) find the relevant dialog and (2) click "Save" is a pain. (And half the time I lose the original file name in the process too.) Being able to click Download and have files silently appear in the relevant folder would be awesome (and consistent with other incarnations of Teams).

Update: as per [this Electron documentation](https://github.com/electron/electron/blob/master/docs/api/download-item.md), it should be possible to achieve this behaviour without relying on a third-party package.

**Comment by IsmaelMartinez** [comment]
Hi @lkrms,

Yeah, that think is annoying. Have a google and see if you can put more info on how to implement it. 

Preferably just writing our own instead of using a package, as then we need to maintain the unmaintained packages... and gets messy. But I am pragmatic on that so if there is something already that does what we need and maintained, then happy to add it.

Even better if you can add it... This might be a good one for hacktoberfest

**Comment by lkrms** [comment]
Sounds like a plan. Happy to help, of course, just wanted to make sure it was tracked somewhere.

**Comment by lkrms** [comment]
It looks like we should be able to manage this without relying on third-party components:

https://github.com/electron/electron/blob/master/docs/api/download-item.md

Haven’t had a chance to experiment yet, though.

**Comment by IsmaelMartinez** [comment]
Probably best to update the issue description to be as descriptive as possible. The hacktober people then will be able to pick it up next month. (Hopefully). Thanks for looking into it!

**Comment by lkrms** [comment]
> Probably best to update the issue description to be as descriptive as possible. The hacktober people then will be able to pick it up next month. (Hopefully). Thanks for looking into it!

No worries, I've added that info to the first post.

**Comment by IsmaelMartinez** [comment]
It is probably ok to use:
https://www.npmjs.com/package/electron-download-manager 
or 
https://github.com/sindresorhus/electron-dl
if makes things easier (probably in that order)

**Comment by IsmaelMartinez** [comment]
I have created 2 branches with electron-download-manager (https://github.com/IsmaelMartinez/teams-for-linux/tree/feature/274-adding-download-manager) and electron-dl (https://github.com/IsmaelMartinez/teams-for-linux/tree/feature/274-electron-dl).

I will see if I can play with them today and choose one to close this. If some of you can have a look and let me know the prefered option, that will be great. Ta

**Comment by IsmaelMartinez** [comment]
https://github.com/sindresorhus/electron-dl seems to be the one doing what this requires. I will see when I got time to add it as a config option, but have it probably as default. Mainly, because it otherwise freezes the app until the file finishes downloading.

**Comment by IsmaelMartinez** [comment]
@lkrms , can you have a play with the branch? Thanks

**Comment by IsmaelMartinez** [comment]
if anyone is interested in this one, shout! otherwise I will pick it up, and close, soon.

**Comment by lkrms** [comment]
Sorry I haven't had a chance to play with this yet. Too little time to get on top of client work at the moment! I'll try to get to it in the next couple of days.

**Comment by IsmaelMartinez** [comment]
No problem. I might put it in snap edge soon (hopefully this week) and see
if it works.

**Comment by IsmaelMartinez** [comment]
Is in edge 0.7.7 If I don’t remember wrongly
