### ISSUE TITLE
The unknown certificate fingerprint

### ISSUE THREAD

**Issue by benedictbasa** [IsmaelMartinez/teams-for-linux#276]
Currently in our company we use teams. The application is good, however last month we started to have CA certs for our proxy and the application no longer works. What happens is it only shows a blank screen upon starting.

**To Reproduce**
1. Go to the linux console
2. Execute teams-for-linux
3. Error will show

configPath = /home/xxx/snap/teams-for-linux/62/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
Unknown cert issuer for url: https://login.microsoftonline.com/common/oauth2/authorize?response_type=id_token&client_id=5e3ce6c0-2b1f-4285-8d4b-75ee78787346&redirect_uri=https%3A%2F%2Fteams.microsoft.com%2Fgo&state=ba6078e1-05e0-4ffa-86cd-7d899e4c0816&&client-request-id=fc900571-3f82-4298-b8be-7c104e3101f5&x-client-SKU=Js&x-client-Ver=1.0.9&nonce=331b9d76-8edb-43e2-a73a-47dff910e581&domain_hint=
Issuer Name: XXX
The unknown certificate fingerprint is: sha256/XXXX

**Expected behavior**
I am not sure how to fix the issue, but the expected behaviour is to have a way to load the SSL certs to be trusted and make the application work.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Installation package: snap
 - Version: 0.7.0

**Additional context**
None.

**Comment by IsmaelMartinez** [comment]
The information is here: https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/certificate/README.md#certificate

**Comment by IsmaelMartinez** [comment]
Might be worth adding a "link" in the known issues section.
