### ISSUE TITLE
Improved Multiple Tenants

### ISSUE THREAD

**Issue by bCamba** [IsmaelMartinez/teams-for-linux#279]
I am always frustrated when changing tenants/organizations in Teams. It is really a pain.

I think Microsoft is probably working on that, but as teams-for-linux is wrapping the web app I think it should not be too hard to have an option to be able to have both organizations loaded simultaneously in order to make the switching much faster.

**Comment by IsmaelMartinez** [comment]
Hi @bCamba, can you summit a proper enhancement using the template? 

Be as specific as you can. There are many ways to archive this so many ways to get lost. It will be pointless for us to come with a solution that doesn't satisfy your needs (aka waste our time).

For example, you can have two accounts by running snap and deb/rpm (as an example). This is sufficient for most of the users as far as I can tell.

**Comment by bCamba** [comment]
@IsmaelMartinez Which enhancement template are you talking about? I could not find any.

I did not think about running snap and deb/rpm versions simultaneously. I will close the issue for now as I try this solution for a few days.

Thank you for you answer and I am also willing to help with this issue in case more people want it too

**Comment by IsmaelMartinez** [comment]
Hi @bCamba, the template is in here https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/.github/ISSUE_TEMPLATE/feature_request.md . When you open an issue, you have 3 options. Bug, feature/enhancement or other. 

Using different packages will do the job. The annoyance is you got the same icon, so you don't really know which is which... Adding something to the icon might be an easy solution to this problem, but probably pretty tricky test (depending on the solution) Hope helps.
