### ISSUE TITLE
snap 1.7.0 doesn't start anymore

### ISSUE THREAD

**Issue by mwichtowski** [IsmaelMartinez/teams-for-linux#280]
Ubuntu 18.04 with snap teams-for-linux. Yestertay it worked. Now when trying to run teams-for-linux nothing happens. No logs, no crashdumps. Only works when run by hand:
`/snap/teams-for-linux/current$ ./teams-for-linux`

**Comment by IsmaelMartinez** [comment]
Hi, I suggest you remove the app, clean the config folder and install it again. Next time please use the template to report issues. Helps finding the reason and for others to see if they are suffering the same issue

**Comment by mwichtowski** [comment]
Now it works. Thank you. As for template, OK.
