### ISSUE TITLE
Microsoft building a client for Linux

### ISSUE THREAD

**Issue by IsmaelMartinez** [IsmaelMartinez/teams-for-linux#281]
Looks like, at last, Microsoft are on it. I will keep supporting this until the Linux client is released and working. 

It is going to probably be a few months until they release anything but I will probably move more into a support mode for this project.

I will accept PRs and release them as fast as I can, but I will spend my free time with other wee projects. 

I will keep this updated. Thank you all a lot and don't worry, we aren't done in here just yet.

**Comment by christiancloudibility** [comment]
Nevertheless - Big thanks for your hard work on that project, you saved me from getting a MacBook :D

**Comment by dariopsmw** [comment]
I don't have a paypal account, how can I post-sponsor your effort?

**Comment by IsmaelMartinez** [comment]
Hi @dariopsmw,

You can send me money with transferwise. use my email address (ismaelmartinez@gmail.com)

Drop me an email if you want/need any help. If it ends up been too much bother, just give it to a local charity. It will make me as happy.

**Comment by sugarnet** [comment]
Thanks for all Ismael!

**Comment by zeitounator** [comment]
Well, seeing the current state of their from scratch electron implementation, it looks like we will still use the app for a while... How sad to see they waste time do reinvent the wheel rather that building on an existing initiative (all this to avoid releasing the source code...)

**Comment by ruifm** [comment]
@IsmaelMartinez, out of curiosity, did Microsoft had any contact with you about this?

No acknowledgement for providing a linux solution, no intention of even building on your project, no reward, nothing? That

My company forces me to use Microsoft products due to office365 enterprise contracts and I must say they are the ones that give me the most issues. I entirely subscribe to @zeitounator 's comment and say that I will keep using your app for a long time...

**Comment by IsmaelMartinez** [comment]
Thanks @ruifm and @zeitounator. Microsoft never contacted me nor I think they will ever do. I did try to approach them a couple of times but didn't get a reply. I will keep supporting this until there is no much point (aka the number of users drop considerably and ms client does do as much as this app). In any case, I learned lots and I am enjoying the community support. Thanks again to all for your support

**Comment by sebaplaza** [comment]
Thanks to you @IsmaelMartinez, you have made an amazing work with this wrapper/client.

In my work every linux user is using your app, i think you deserve some reward :1st_place_medal:

**Comment by nickelghost** [comment]
Thank you for the effort!
MS announced that Teams will be released on Linux by the end of the year here: https://microsoftteams.uservoice.com/forums/555103-public-preview/suggestions/16911565-linux-client

**Comment by jonnyguo1988** [comment]
I think we can add some interesting"New feature" which is better than microsoft, for example change the css file to get a better look, I don't like the color or styles of MSTeams UI

**Comment by IsmaelMartinez** [comment]
This client already allows you the change of CSS styles. It even includes a
few of them (not sure if they are still working).

Check the config folder. There is more info in it. Cheers!

**Comment by Surendrajat** [comment]
Looks like it's finally out.
Stable here: https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/
Preview here: https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams-insiders/

**Comment by UKSFM99** [comment]
guys its official  now:

https://teams.microsoft.com/downloads#allDevicesSection

**Comment by IsmaelMartinez** [comment]
Well, it was nice to help you all while it lasted. I will give it a try this week and, if it does do what it's supposed to do, close/lock this project.

Thanks everyone for all your contributions. It's been a great experience.

**Comment by Surendrajat** [comment]
@IsmaelMartinez Huge thanks for the project. Been using it for a while now and it still feels better than official version. So please let it be active little more.

**Comment by zeitounator** [comment]
From my very first quick test (and I'm not really surprised....) it failed connecting via SAML into my organisation from home (investigation pending). I'm afraid I will have even more problems from work when I have to encounter SSL certs signed by internal CA. I'll keep you updated.

**Comment by shellster** [comment]
I've been using it for about 24 hours.  The official release is slower, has some graphical glitches, and also doesn't show the icon in my xfce task tray, which is annoying.  I haven't tried to do a video call yet.  So far, I'm not very impressed, compared to this project.

**Comment by cronopio** [comment]
HI all. Thanks @IsmaelMartinez for all the hard work. Been using `teams-for-linux` for some months. Also other coworkers use it. Today we updated to official version but looks like some coworkers are having bad time with RAM consume. Official version seems to eat more RAM that your version, so they will keep using your version more time. If MS improve their performance on official version we'll review and test again. By now we are all attached to your version, awesome work btw.

**Comment by tardis89** [comment]
Is anyone aware of a way to override the userAgent within the official Microsoft app? If that's not a option, I will still only be able to use teams-for-linux as my company only allows Microsoft apps on Windows only.

**Comment by IsmaelMartinez** [comment]
Hi 

@tardis89, I will ask your company to look into that.  I am sure MS will NOT allow the change of user agent in their app.

@cronopio the high RAM consumption is probably related to all the metrics that they will be collecting. I suspect they will collect more than usual as this is a Beta, but don't worry that you should still be able to use teams-for-linux for as long as you want. (but will not be adding new features etc as now people get paid officialy by Microsoft to provide a client)

@shellster, don't worry that the project will still be here. But same as I said in my previous point to @cronopio .

@zeitounator, I am surprised they didn't prioritize the different authentications that companies use (specially SAML that is quite a common case). But give them time and they will provide a solution (or at least now you can probably legally ask if you got official support).

To resume, teams-for-linux will be here to stay until there is no point for it to be, it's pretty stable (that is why is number 1.0.0) so should not need any/many "maintenance".

Anything just shout, but do not send me emails as if I am MS. (I got a couple of emails about version 1.2.0 not doing stuff, etc)

**Comment by Surendrajat** [comment]
@tardis89 Not straightforward but you can reverse the binary and replace the UA string, embedded in that hopefully.

**Comment by ellepdesk** [comment]
I'm staying with your version a while longer, the official client can't handle a simple bt-headset :)

**Comment by doniks** [comment]
Anybody knows a way to know when MS updates the .deb?

**Comment by Surendrajat** [comment]
@doniks Add the repo to `source.list` and `apt update` will tell you.

**Comment by doniks** [comment]
> @doniks Add the repo to `source.list` and `apt update` will tell you.

which repo? I only see a direct link to a .deb but no ppa

**Comment by Surendrajat** [comment]
@doniks Check `Installation steps` of my first comment. The first step contains the ppa url.

**Comment by doniks** [comment]
@Surendrajat ups, yeah of course! I only looked at @UKSFM99 's comment. Thx!

**Comment by basicmaster** [comment]
For now I will also stay with your client, as the official client uses custom notification windows (instead of using the system ones) and also enables a spell check, which underlines many correct words by mistake. And the MS client is slower.

**Comment by Fmstrat** [comment]
Not to mention you can only share your whole desktop, not an individual app.

**Comment by PhlashGBG** [comment]
Just tried the official package - it has indeed got a way to go yet: meeting joins default to camera on, can only share desktop from current X screen (I have a zaphod system with two X screens), notifications do not use the desktop standard mechanism. Sticking with your excellent option for now, also incoming PP donation :)

**Comment by IsmaelMartinez** [comment]
Thanks a lot @PhlashGBG for the donation and I am glad to hear that many people are still using this client!

**Comment by doak** [comment]
Like already implied by @zeitounator: The MS client is neither free software source nor open source. Hence this project is quite important!

**Comment by lboucherpostal** [comment]
> Looks like it's finally out.
> 
> [Stable version](https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/) | [Preview version](https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams-insiders/)
> 
> **Installation steps:**
> 
> ```shell
>  echo "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main" | sudo tee /etc/apt/sources.list.d/teams.list
>  sudo apt update
>  sudo apt install teams
>  #or if you want insiders build
>  sudo apt install teams-insiders
> ```
Hi,
Before, we can install [MS gpg key](https://docs.microsoft.com/fr-fr/windows-server/administration/linux-package-repository-for-microsoft-software):
```
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
```

**Comment by bvhoesel** [comment]
Still beats the MS version. I have no screen share share on the MS version (Linux Mint Mate). And this one has a normal window border so I can see where it is. So please do not abandon it yet ;-) .

**Comment by nilsboy** [comment]
I'd rather not mess with the sources.list - can MS not snap it?

**Comment by IsmaelMartinez** [comment]
@nilsboy , I will suggest you ask them. You will not get an answer from them in here.

**Comment by aubertc** [comment]
You need to update 

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/HISTORY.md
> Ideally this project will die when Microsoft implements a desktop client for linux. Please do vote for it in the Microsoft Suggestions Forum

though!

**Comment by elhennig** [comment]
For me working share function (single windows are not supported by the MS client) and the window frame is the best reason not to use the MS version. Currently my org refuse to let Linux client in so I am more than happy with the command line option to set the user agent, too! 
There is only one issue that is quite annoying on my machine: There is a problem with the file open dialog and this will crash the tool. Only thing that works is adding files from Onedrive (good enough as workaround).
So, thanks for keeping this alive!

**Comment by IsmaelMartinez** [comment]
> You need to update
> 
> https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/HISTORY.md
> 
> > Ideally this project will die when Microsoft implements a desktop client for linux. Please do vote for it in the Microsoft Suggestions Forum
> 
> though!
If wishes were horses, beggars would ride. Feel free to open a wee PR to update that text.

**Comment by aubertc** [comment]
> If wishes were horses, beggars would ride. Feel free to open a wee PR to update that text.

Done.
https://github.com/IsmaelMartinez/teams-for-linux/pull/355

Thanks again for your work on this project.

**Comment by caroldomokos** [comment]
Screen sharing got me here too. Great work.

**Comment by AngelQC** [comment]
When the company disables the client for Linux, it affects the MS version only -- teams-for-linux still works!
I am grateful for this version :+1: 
Now if we could get the option to detach a chat window (new, from what I saw at work yesterday), that would be even better! :smiley:

**Comment by michaelmassee** [comment]
Thanks for this Project, so please keep this alive.
The MS Version sucks. No Updates.

**Comment by michaelmassee** [comment]
vote here ->

[](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40324324-keep-the-linux-client-up-to-date-with-the-latest-f?tracking_code=d9182f1ff1958c09f840db5707fb26d8)

**Comment by manuel-arguelles** [comment]
The MS version keeps pushing my cpu to 100%, @IsmaelMartinez your version works way better (at least for me), thanks! please keep it up!

**Comment by grealish** [comment]
MS build is pointless and useless for many things currently,, can't select audio reliably isn't great, but this version can like running in browser
![fuckinguseless-teams-gnome-sound from 2020-06-02 15-35-24](https://user-images.githubusercontent.com/3739376/83640737-d97c9580-a5ac-11ea-8b58-baf65e49af53.png)

**Comment by mxsteini** [comment]
@IsmaelMartinez I really love your teams version.
MS doesn't work correct in:
* screensharing on wayland
* notification to gnome-notification
* windows decoration from system-theme

Please, go on in this project

**Comment by chmduquesne** [comment]
The official MS client better supports the video for me, but the fact that they do not use standard notifications makes it an absolute nightmare to use for me. I am using a tiling WM, so I get a popup that takes half of my screen anytime somebody sends me a message. I can't work like this, so I keep using your version so far 🙂

**Comment by FredHappyface** [comment]
Still far superior to the official app for me. Thanks for bothering to make native notifications work and for all of the hard work!

Great to be able to share my screen as well

Thank you 😁

**Comment by hbarsaiyan** [comment]
Please keep continuing your unofficial client! It's far better than the official one.

**Comment by DeanKertai** [comment]
Microsoft should just give up and let this be the official version. It works much better

**Comment by jianpan** [comment]
Microsoft's official client's screen sharing is extremely slow on Elementary OS 5.1. This webapp version client works so much better.

**Comment by AngelQC** [comment]
I love this version, please keep it up!

Question: Will we be able to pop-out chat windows anytime soon?  I'd like that! :)

**Comment by beebus** [comment]
Wow, what a thread! 
This might be an updated link if you are looking for the MS version of Teams
[https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/download-app](https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/download-app)
I haven't tried either of these Linux versions out yet, but Friday I'll have a report on your desk.
![Screenshot from 2020-09-09 10-32-07](https://user-images.githubusercontent.com/3438663/92619975-c2260600-f287-11ea-8f86-348ecb7c19f8.png)

**Comment by AngelQC** [comment]
> I love this version, please keep it up!
> 
> Question: Will we be able to pop-out chat windows anytime soon? I'd like th

> I love this version, please keep it up!
> 
> Question: Will we be able to pop-out chat windows anytime soon? I'd like that! :)

Also, my organization disabled the use of the linux version (go figure...) so I'd really like for this version to stay!

**Comment by maitra** [comment]
There were several important features that do not work on the official MS Teams linux client. Notably screen-sharing of individual windows. Did this  change? Also the Microsoft client was a good 100MB+ or so bigger than this one (after installation). Perhaps there are additional MS Teams features that are in the official app. But I really like this one, and appreciate the source code that can make it eventually be packaged for the different distributions.

**Comment by zrhoffman** [comment]
Microsoft's client does not support live events, and Microsoft doesn't have a repo to report issues like they do for other proprietary projects (example: [microsoft/WSL](/microsoft/WSL)). @IsmaelMartinez's client continues to be very relevant.

**Comment by IsmaelMartinez** [comment]
I will close this ticket. Doesn't change the situation. still supported in maintenance mode only. Thanks everyone again for the kind words.
