### ISSUE TITLE
won't run after first launch

### ISSUE THREAD

**Issue by mjarret** [IsmaelMartinez/teams-for-linux#282]
All on Ubuntu 18.04:

Installed teams-for-linux via snap. First launch, everything works fine. After that, attempting to use teams-for-linux generates no output and doesn't launch. 

I reinstalled via deb and everything is fine, no problem at all with restarts though I always get the output. 

`configPath = /home/michael/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
^Cbefore-quit
window close
`

I think this (maybe) has something to do with directory permissions set by snap?

**Comment by IsmaelMartinez** [comment]
Hi @mjarret,

You should not need sudo to run teams-for-linux via snap. That seems to show the is something not right with you snap installation.

I am not an expert of snap but had a few headaches to run it myself. I will suggest using the deb package and subscribe to the releases in here. (there shouldn't be many as MS is working on a client so I am mostly in support mode)

Sorry, I will close this as know issue/workaround. Put any updates in here is you find how to fix it!
