### ISSUE TITLE
Teams for Linux snap application will not start

### ISSUE THREAD

**Issue by pehkawn** [IsmaelMartinez/teams-for-linux#285]
(This issue has also been [posted on askubuntu](https://askubuntu.com/questions/1177634/teams-for-linux-snap-application-will-not-start?noredirect=1#comment1966638_1177634).)

I recently installed Ubuntu 19.04 on my work laptop, and installed Teams for Linux snap for work purposes. Everything seemed to work perfectly at first, but at some point it stopped working. I can find the shortcut icon under Gnome's applications list, but nothing happens when I click it. Right clicking and selecting "Show details" returns the error message `Could not find "teams-for-linux_teams-for-linux.desktop"`. I tried to start the application from terminal to see if it returns any error messages, but absolutely nothing happens. When executing startup command, it simply returns to command prompt as shown below.

```
~$ teams-for-linux
~$
```

I've tried adding "verbose" (`--verbose`, `--v`, `-v`) and "help" tags (`--help`, `-h`) to see if this will return any feedback, but the result is the same. It simply returns to command prompt. Searching for through my hard drive for files named `*teams-for-linux*` in the name yields multiple locations, and I can only assume the application is installed.

```
~$ sudo find / -iname *teams-for-linux*
/tmp/snap.teams-for-linux
/tmp/snap.teams-for-linux/tmp/.snap/snap/teams-for-linux
/var/lib/snapd/apparmor/profiles/snap.teams-for-linux.teams-for-linux
/var/lib/snapd/apparmor/profiles/snap-update-ns.teams-for-linux
/var/lib/snapd/snapshots/2_teams-for-linux_0.7.0_62.zip
/var/lib/snapd/snapshots/4_teams-for-linux_0.7.0_62.zip
/var/lib/snapd/snapshots/3_teams-for-linux_0.7.0_62.zip
/var/lib/snapd/desktop/applications/teams-for-linux_teams-for-linux.desktop
/var/lib/snapd/seccomp/bpf/snap.teams-for-linux.teams-for-linux.src
/var/lib/snapd/seccomp/bpf/snap.teams-for-linux.teams-for-linux.bin
/var/lib/snapd/cookie/snap.teams-for-linux
/var/lib/snapd/mount/snap.teams-for-linux.fstab
/var/lib/snapd/mount/snap.teams-for-linux.user-fstab
/var/lib/snapd/sequence/teams-for-linux.json
/var/lib/snapd/snaps/teams-for-linux_62.snap
/var/cache/apparmor/26b63962.0/snap.teams-for-linux.teams-for-linux
/var/cache/apparmor/26b63962.0/snap-update-ns.teams-for-linux
/var/snap/teams-for-linux
/home/[user]/.cache/gnome-software/odrs/io.snapcraft.teams-for-linux-IIAJhVGfBhm393UTagoW5awtZlPDGqHd.json
/home/[user]/snap/teams-for-linux
/etc/udev/rules.d/70-snap.teams-for-linux.rules
/run/snapd/ns/snap.teams-for-linux.fstab
/run/snapd/ns/teams-for-linux.mnt
/run/snapd/ns/snap.teams-for-linux.info
/run/snapd/lock/teams-for-linux.lock
/run/user/1000/snap.teams-for-linux
find: ‘/run/user/1000/doc’: Ikke tilgang
find: ‘/run/user/1000/gvfs’: Ikke tilgang
/run/udev/tags/snap_teams-for-linux_teams-for-linux
find: ‘/proc/2621/task/2621/net’: Ugyldig argument
find: ‘/proc/2621/net’: Ugyldig argument
/root/snap/teams-for-linux
/sys/fs/cgroup/devices/snap.teams-for-linux.teams-for-linux
/sys/fs/cgroup/freezer/snap.teams-for-linux
/snap/teams-for-linux
/snap/teams-for-linux/62/meta/gui/teams-for-linux.desktop
/snap/teams-for-linux/62/teams-for-linux
/snap/bin/teams-for-linux
```

I am at a loss here. Any advice on what the issue may be is most welcome.

**Comment by IsmaelMartinez** [comment]
Have you tried to remove and install the app again? It smells snap related.

**Comment by pehkawn** [comment]
Yes, that was my first go-to solution, and I've tried that multiple times now. Last time I removed the snap and rebooted before re-installing. Still the issue persists.

**Comment by IsmaelMartinez** [comment]
Can you try another package? The deb or even the flatpack might be what you need.

**Comment by pehkawn** [comment]
Ok, I downloaded the deb package, and this one worked. =) I used the snap because that's the one I found in Ubuntu software. How can I add the deb to package to apt repo?

**Comment by IsmaelMartinez** [comment]
Hi, I don't think is possible to add it to the apt repo. MS is working on a
client so I am only doing mostly maintenance. The best option is to
subscribe to release updates. I will more than sure do one next month with
small changes. Feel free otherwise to create another feature request and/or
implement that apt repo. Ta

**Comment by julian-alarcon** [comment]
Hi @pehkawn can you test this command?
snap info teams-for-linux

Also, try to remove it using this:
sudo snap remove teams-for-linux

And delete the directory ~/snap/teams-for-linux

And the reinstall it.

Also, are you using a beta version of Ubuntu or snap?

**Comment by pehkawn** [comment]
I removed teams snap and deleted said directory and installed it again from Ubuntu software. Nothing happens when I try to start it. I already installed the deb package, so I don't know how to run it in terminal, since the `teams-for-linux` command now addresses the existing .deb install.
`snap info teams-for-linux` returns the following output:
```
name:      teams-for-linux
summary:   Unofficial Microsoft Teams client for Linux using Electron.
publisher: Julian Alarcon (alarconj)
contact:   https://github.com/IsmaelMartinez/teams-for-linux
license:   unset
description: |
  Unofficial Microsoft Teams client for Linux using Electron. It uses the Web
  App and wraps it as a standalone application using Electron.
  
  Snap uses confinement to provide more security, this restrict the access to
  hardware or data on your device to prevent security issues.
  
  You need to allow the access to the camera on Teams For Linux to be able to
  do videocalls, to do that you can use the Software Store in your Operating
  System after the installation of the snap.
commands:
  - teams-for-linux
snap-id:      IIAJhVGfBhm393UTagoW5awtZlPDGqHd
tracking:     stable
refresh-date: today at 10:30 CEST
channels:
  stable:    0.7.0 2019-08-26 (62) 52MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.7.1 2019-09-21 (69) 52MB -
installed:   0.7.0            (62) 52MB -
```
I'm on Ubuntu 19.04 and I do not believe I am running a beta of snap.
`snap --version` returns:
```
snap    2.41
snapd   2.41
series  16
ubuntu  19.04
kernel  5.0.0-29-generic
```

**Comment by julian-alarcon** [comment]
You must uninstall the deb version and then test the Snap one.
Or you can check this:
`snap run teams-for-linux`

**Comment by IsmaelMartinez** [comment]
Added the label as there is the workaround of using deb package (or flatpack TBC)... not the best but a workaround.

**Comment by IsmaelMartinez** [comment]
Closing as there is not much activity on this and there is a workaround. Ping back if you find a solution or can provide more info. Thanks

**Comment by LudwikBielczynski** [comment]
I have the same issue on Ubuntu 18.04. What was the workaround? The hyperlink is not active anymore...
`
name:      teams-for-linux
summary:   Unofficial Microsoft Teams client for Linux using Electron.
publisher: Julian Alarcon (alarconj)
store-url: https://snapcraft.io/teams-for-linux
contact:   https://github.com/IsmaelMartinez/teams-for-linux
license:   unset
description: |
  Unofficial Microsoft Teams client for Linux using Electron. It uses the Web App and wraps it as a
  standalone application using Electron.
  
  Snap uses confinement to provide more security, this restrict the access to hardware or data on
  your device to prevent security issues.
  
  You need to allow the access to the camera on Teams For Linux to be able to do videocalls, to do
  that you can use the Software Store in your Operating System after the installation of the snap.
commands:
  - teams-for-linux
snap-id:      IIAJhVGfBhm393UTagoW5awtZlPDGqHd
tracking:     latest/stable
refresh-date: today at 16:52 CET
channels:
  stable:    1.0.0 2019-11-01 (79) 58MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      1.0.0 2019-11-01 (78) 58MB -
installed:   1.0.0            (79) 58MB -
`

**Comment by julian-alarcon** [comment]
Check this @LudwikBielczynski https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#use-camera-using-the-snap-build

Run this in a terminal to allow camera access:

```
sudo snap connect teams-for-linux:camera core:camera
```
