### ISSUE TITLE
We couldn't sign you in. Please try again in loop

### ISSUE THREAD

**Issue by Kassouma** [IsmaelMartinez/teams-for-linux#286]
**Describe the bug**
Used snap package with no problem.
Ubuntu 18.04.3 LTS
One day the app wouldn't work anymore, I have a " We couldn't sign you in. Please try again"
Same thing with my browser , firefox,chrome , private navigation gives the same.
I removed the package.
I removed my ~/.config/teams* folder
Installed from deb package, last release 0.7.0.
Still the same error.
I can log in from another computer

**To Reproduce**
1. install teams through snapd or deb package
2.login

**Screenshots**

![MicrosoftTeams-image-min](https://user-images.githubusercontent.com/3705461/66033179-0866d700-e507-11e9-82c2-9098936e2e43.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Installation package deb, snap

Thanks in advance for your help :)

**Comment by IsmaelMartinez** [comment]
That sounds pretty strange. Are you going via a proxy?

**Comment by IsmaelMartinez** [comment]
probably duplicated by #268... closing as the other one still open.

**Comment by Kassouma** [comment]
No proxy at all.
Strange thing is that it started to work again just after I changed my computer TZ...(???)
I was in the philippines with a singapore TZ.

**Comment by creslinux** [comment]
> No proxy at all.
> Strange thing is that it started to work again just after I changed my computer TZ...(???)
> I was in the Philippines with a Singapore TZ.
> 
> And I had the issue since I arrived in the Philippines ...

This was a fix for me, i flew to Ukraine, my laptop in UK TZ, flipped and sprang to life. 
Also true for Official  MS Teams client for Linux.

**Comment by jdvalentini** [comment]
It happened to me as well on correct timezone but wrong time.

**Comment by abedjaber** [comment]
I still have the same problem, i changed the time zone many times, but still not solved!

**Comment by IsmaelMartinez** [comment]
hi @abedjaber , did you try the proxy options in #268 ? Thanks

**Comment by abedjaber** [comment]
actually i am new in kali linux, i could not install the rpm package because there were many missing dependencies, i installed the deb package, the same problem persist. I will try the proxy solution, but it will take a while to figure out how!!

**Comment by abedjaber** [comment]
from Terminal, i used: "google-chrome  %U --no-sandbox --proxy-server=http://proxy-host:proxy-port", but the infinite loop still persists. Is the command wrong?

**Comment by anisayari** [comment]
Same error here (France, no proxy, with custom mail from my organisation)

**Comment by IsmaelMartinez** [comment]
have you tried also checking with you company IT admins to check the other options indicated in the other ticket?

**Comment by abedjaber** [comment]
I ended up installing ie extension for chrome, it worked, and I can use teams on the web, better than nothing ;). In that case, I think if you install ie on linux, it might work on the web (didn't try it), or it might be something related to screen resolution! Thanks for help.
