### ISSUE TITLE
Login to trello app inside teams doesn't work

### ISSUE THREAD

**Issue by sezaru** [IsmaelMartinez/teams-for-linux#290]
**Describe the bug**
When I try to add a trello board to my team, I'm not able to login to it so I can see the board.

**To Reproduce**
When I try to add a trello board to my team, it will give me a button to the first login to trello as shown below:
![image](https://user-images.githubusercontent.com/279828/66704379-c5201b80-ecf1-11e9-9cda-f4c73cc47260.png)

When I click on "Log in with Trello", a chrome browser will open to this link: `https://trello.com/login?returnUrl=%2Fintegrations%2Fteams%2Ftab-config-login` and will close itself automatically 1-second latter.

Nothing will happen then and I will be still logged off from trello and unable to add it.

Note that I can log in, add the board and visualize it if I use teams directly from the browser, but I will still not be able to use it in teams-for-linux with the above issue.

**Desktop (please complete the following information):**
I'm using the latest (0.7.0) version in Gentoo linux

**Comment by IsmaelMartinez** [comment]
Have you tried doing ctrl+click? Ta

**Comment by sezaru** [comment]
It works! It will keep that window from my first post image, but now if I close it and try to readd it will get that it is already logged and work. Thanks!

**Comment by IsmaelMartinez** [comment]
yeah, is a bit of a "hack" but same happens with github and others. It's
because the way electron (an chrome) works. Glad it works.
