### ISSUE TITLE
CPU 100% Utilization

### ISSUE THREAD

**Issue by KRUXLEX** [IsmaelMartinez/teams-for-linux#293]
**Issue**
Hi,
I was install teams-for-linux on my Kali (Ubuntu) distribution via snap.
When I running app always I have 100% utilization of CPU. It's not change at all. 
![Zrzut ekranu z 2019-10-14 08-46-22](https://user-images.githubusercontent.com/22861005/66739804-ced08d00-ee71-11e9-9d17-8551c3e53379.png)

Please for help to debug this problem and fix it.

**Desktop**
 - OS: Linux ghost 5.2.0-kali3-amd64 #1 SMP Debian 5.2.17-1kali1 (2019-09-27) x86_64 GNU/Linux
 - Installation package snap
 - Version 0.7.0

**Comment by IsmaelMartinez** [comment]
Can you try another package type?

**Comment by KRUXLEX** [comment]
What you mean saying "another package type"?

**Comment by IsmaelMartinez** [comment]
Instead of snap use Deb (or rpm depending on your os). Check the release
folder

**Comment by KRUXLEX** [comment]
I was installed the .deb package. I don't experience issue. Somthing wrong with snap is. Know what?

**Comment by IsmaelMartinez** [comment]
probably os configuration. I will close this as there isn't much to do from my side. Use deb. Apologies and thanks for reporting!
