### ISSUE TITLE
Allow the middle click on URLs to open in the default browser

### ISSUE THREAD

**Issue by clero** [IsmaelMartinez/teams-for-linux#296]
**Is your feature request related to a problem? Please describe.**
When someone sends me an URL I sometimes use the middle click to open the link (habit from the browser). When doing that, an empty electron window, named `teams-for-linux` opens.

**Describe the solution you'd like**
I would like the link to open in my default browser, just like when using the right click.

**Describe alternatives you've considered**
Doesn't apply here.

**Additional context**
It is working well in teams web app.
My guess is a missing else clause in the [new window handler](https://github.com/IsmaelMartinez/teams-for-linux/blob/fda53039a445dca2ca9586ca77e6f108888a4649/app/mainAppWindow/index.js#L111)

**Comment by clero** [comment]
> might seem counterintuitive but the opening in the default browser is the default behaviour. This is how it works since it started (even before I took over the project) so making it to be the opposite will be disruptive for many people.
> 
> However, it will be possible to have a flag that implements does it work the opposite way... feel free to play around with it.

Maybe I don't understand your comment but currently, middle click does **not** open the link in the default browser. (it opens in an Electron window which does not support javascript). Is this really the desired behavior?

**Comment by IsmaelMartinez** [comment]
Apologies, I am ill so my communication might not the best. What I mean is
that normal click (no middle click) opens in the default browser.﻿

**Comment by clero** [comment]
> Apologies, I am ill so my communication might not the best. What I mean is that normal click (no middle click) opens in the default browser.

I'm okay with that and I expect the middle click to have the same behaviour.

**Comment by IsmaelMartinez** [comment]
Hi, the problem then will be that the github and other integrations will
not work. If you don't mind that, you can work on a config option that
always open the events in an external window. Have a play with it. I am
happy to help but, as MS is already working on a client, I don't feel the
eager of implementing new functionality. Sorry if is a pain, but again,
feel free to implement it and I will be more than happy to help/support you.

**Comment by IsmaelMartinez** [comment]
Hi @clero, I will close this as I don't see much activity happening. MS is implementing a client so we aren't really doing much extra work here as I got plenty of other things todo. 

If you decide to give it a go and need a hand, just shout (or well, better write something here or send me an email) and I will try to help you.
