### ISSUE TITLE
Application crash due to Adwaita GTK theme missing.

### ISSUE THREAD

**Issue by hetii** [IsmaelMartinez/teams-for-linux#297]
Hi.
Applica crash occure probably affected by bug similar to [this](https://github.com/signalapp/Signal-Desktop/issues/3447) one

I test this on Linux Mint 19.2 Tina (Cinamon)

    teams-for-linux 
    configPath = /home/dev/snap/teams-for-linux/62/.config/teams-for-linux
    Failed to get the config file, using default values
    configFile = {}
    Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
    GLib-GIO-Message: 08:59:52.861: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

    (teams-for-linux:9548): Gtk-WARNING **: 08:59:53.041: Could not load a pixbuf from icon theme.
    This may indicate that pixbuf loaders or the mime database could not be found.
    **
    Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/teams-for-linux/62/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: cannot open shared object file: No such file or directory (gdk-pixbuf-error-quark, 5)

**Comment by IsmaelMartinez** [comment]
Hi @hetii , can you use the bug report template? Also, can you try one of the other packaging options? Thanks

**Comment by hetii** [comment]
@IsmaelMartinez Ok will use template next time.
I just try teams-for-linux_0.7.0_amd64.deb and works fine, so the issue is just with snap version.

**Comment by IsmaelMartinez** [comment]
@julian-alarcon, are you able to have a look at this? Thanks in advance!

**Comment by IsmaelMartinez** [comment]
I am going to close this as it does smell like a system/snap configuration issue (and MS is building a client and deb package works). Keep us posted with what you find!
