### ISSUE TITLE
Is the notification hack still working?

### ISSUE THREAD

**Issue by DanFulger** [IsmaelMartinez/teams-for-linux#298]
Teams-for-linux 0.7.0, CentOS 7.7, KDE.

I tried to modify the notifications hack to add some sound, but it's not working, I can't even add "xx" to the end of the notification text.
Notifications are working with or without the hack.

**Comment by DanFulger** [comment]
I am getting syntax errors if I make them, I am seeing the new command line option I added in --help, so it's not deployment.
I eventually found a way to intercept notifications with dbus-monitor, so I don't really need to edit the source code anymore.

**Comment by IsmaelMartinez** [comment]
Hi @DanFulger, I haven't tried the notification hack stuff for a long time it, in theory, should still work. If/when it works, you might get two notifications (one from the HTML5 and the other from the hack). If you can point me to your branch with the changes I can have a look.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Just ping back if you need further information and I will reopen
