### ISSUE TITLE
Explain how to support the project

### ISSUE THREAD

**Issue by krichter722** [IsmaelMartinez/teams-for-linux#299]
It'd be nice to find a statement which contributions (PRs, money, reviews, all of them, none of them, etc) to the project are welcome in README or CONTRIBUTING.

**Comment by IsmaelMartinez** [comment]
Hi @krichter. All of them are more than welcome. Actually, you can add a line in the contributing 😉

**Comment by krichter722** [comment]
@IsmaelMartinez Will do. Where would I send a donation in the form of money?

**Comment by IsmaelMartinez** [comment]
Hi @krichter722 , there is the "Sponsor" button at the top. Preferred in paypal as kofi takes a wee cut from the donation.

**Comment by krichter722** [comment]
@IsmaelMartinez I didn't realize there's this new feature now in GitHub. Given that, I think that the line in CONTRIBUTING or elsewhere would be redundant. I'll close this since I think others will find the sponsor button easily.
