### ISSUE TITLE
Join Lync (Skype for Business) as Guest

### ISSUE THREAD

**Issue by Timonzimm** [IsmaelMartinez/teams-for-linux#301]
**Describe the bug**
I cannot seem to join a Skype for Business (Lync) video-conference using the link.

The link I have is of the form: `https://meet.lync.com/XYZ/AAA.BBB/ID?sl=1`

1) I tried to go on the link, using Chrome, and click `xdg-open`, but it fails with the following error:

`Failed to open URI "sfb:https://webpool..."`

2) Alternatively, I tried to use the command `teams-for-linux -url https://meet.lync.com/XYZ/AAA.BBB/ID`

But I have then to sign in, whereas I'd like to join as guest (as you can do from Windows or OSX): https://i.imgur.com/DnGjbZQ.png

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Installation package: deb
 - Version: 1.0.0

**Comment by IsmaelMartinez** [comment]
Hi @Timonzimm ,

Not sure if that is a supported feature by microsoft teams. 

Try the following. 

* Copy the link to a teams chat
* Ctrl click on it.

xdg-open will not open it as sfb is for skype for business (msteams uses another xdg-open register).

Also, check their documentation as it does look like you might be trying to do something that you should not be able to do... 
https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability
hope helps.

**Comment by Timonzimm** [comment]
Ok then I maybe misunderstood the goal of this project, I thought it was meant to help using Skype for Business also but the link you mention seems to explain Teams & SFB are still distinct initiatives.

And for your idea to copy the link to a teams chat, I am not the owner of the link nor the meeting, so I cannot really create another link.

**Comment by IsmaelMartinez** [comment]
yeah, sorry but MS still has those 2 as different products... but they are trying to move people away from SFB. I will close this. You can request the client in here https://www.skypefeedback.com/forums/299913-generally-available/suggestions/9182558-linux-desktop-client-for-skype-for-business but I think they are moving away from it...
