### ISSUE TITLE
Blank screen in first login

### ISSUE THREAD

**Issue by jroigfer** [IsmaelMartinez/teams-for-linux#302]
After new version, When I try to perform first login, appears a blank screen and can't continue the process.
I tried with .deb version and snap version, in both te same error.
I tried to clear cache folder and entire config folder,

 - Ubuntu 18.04 LTS 64

**Comment by IsmaelMartinez** [comment]
Hi @jroigfer, 

Can you use the issue/bug template? 

That will allow us to determine in more detail how can we help you.

Thanks,

**Comment by jroigfer** [comment]
Hi,

I tried today an works properly, thanks!

Regards.
