### ISSUE TITLE
Flatpak release of version 1.0.0?

### ISSUE THREAD

**Issue by mario-d-s** [IsmaelMartinez/teams-for-linux#303]
Hi,

First off thank you so much for this excellent Teams client for Linux! It's great to see it being maintained this well too. I would like to try the 1.0.0 release but I'm currently using the Flatpak version and would prefer to continue with it.

Can you please update it?

Thanks

**Comment by IsmaelMartinez** [comment]
Hi,

Create a PR in the flatpak repository. 
https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux

Check the following to get more info about it:
https://github.com/IsmaelMartinez/teams-for-linux/issues/41

I don't provide support for it, but might try to create the PR when I get sometime for it. 

Appologies but only supporting this and my life does keep me pretty busy.

Cheers!

**Comment by mario-d-s** [comment]
Thanks for the guidance!
I decided to give it a shot and opened flathub/com.github.IsmaelMartinez.teams_for_linux#11

No worries that you don't have the time for supporting it yourself, I respect that.

**Comment by IsmaelMartinez** [comment]
thanks a lot @mario-d-s ! You are a star!

**Comment by mario-d-s** [comment]
@IsmaelMartinez it's nothing, you're the star for doing the job that Microsoft isn't doing!
