### ISSUE TITLE
difference electron client <--> webclient, customizing the electron client

### ISSUE THREAD

**Issue by hglanzer** [IsmaelMartinez/teams-for-linux#305]
Hello, i am copying my question asked via gmail + answer for future reference:

----------------

>>Hi,
>>
>>First of all, thx for your work. i am trying to integrate ms teams into
>>our linux-based product, which works basically when using an up-to-date
>>chrome browser, running the web application

>>- (plz forgive me if this is a stupid question:) i dont really understand the difference between >>your client and the Ms Teams webclient. from my first perspective, running
>>https://teams.microsoft.com in my chrome v78 looks the same as your
>>client...?

The client uses Electron that runs internally a version of chromium (69 I think). Running chrome v78 will mostly look the same as the client. Chromium is only a part of Chrome (mostly just the renderer) so there are quite a few (electron) caveats.

>>- would it be possible to customize or remove certain elements from within your clients.
>>for example, remove the menu on the left, hide certain button, insert custom buttons,... ?

You can hide elements using CSS. There are a few templates in the project that can give you something to play with.

**Comment by IsmaelMartinez** [comment]
Thanks for adding this to here. 

There is a bit more info about the customCSS in here 
https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/customCSS

and here
https://github.com/IsmaelMartinez/teams-for-linux/issues/77

Hope helps!
