### ISSUE TITLE
Is it possible to request control?

### ISSUE THREAD

**Issue by gazzatav** [IsmaelMartinez/teams-for-linux#306]
Thanks for your work on this.  My company has just started using Office365.  When working from home I join meetings with teams on my laptop running Ubuntu 18.04.  In teams Video and audio is fine but it does not seem possible to request control. 

1. Join meeting
2. Move cursor to top of window

I expected to see a button appear somewhere near top allowing me to request control.  Nothing appeared and my team were unable to give control.  

 - OS: Ubuntu 18.04
 - Installation package: snap
 - Version 1.0.0

**Comment by IsmaelMartinez** [comment]
Hi, thanks for issuing a feature request.

Microsoft is building a client and releasing a beta by the end of the year so they might implement it then.

I am happy to help and encourage you to have a play around, but got not much time to dedicate to this project (a part from support and small changes) so I don't think I will be able to implement this before Microsoft does it.

Hope you understand.

**Comment by IsmaelMartinez** [comment]
Closing as I have heard nothing back from @gazzatav
