### ISSUE TITLE
Open v.1.0 under Ubuntu 18.04

### ISSUE THREAD

**Issue by dleonhartsberger-travelclick** [IsmaelMartinez/teams-for-linux#308]
After I had to restart the computer last Monday November 18th 2019, I couldn't open Teams for some reason. I took the opportunity to update v.0.7 to 1.0 under Ubuntu 18.04 and now I can't get open the app.
I followed the instructions to delete cache, remove the config folder entirely and I still cannot open it. When I right click the link of the App I see that there should be a Window to sign in to my account, but it doesn't show anywhere, as if it was showing behind the Desktop?

This is what I see: http://i.imgur.com/o4uTfjA.png (I cannot provide a screenshot when I right click on the Teams icon and I see the Windows opened for the App)

This is really strange and I cannot fix it. Can you please help? I had to go back to the Web App where I cannot make any calls :(
Thanks!

**Comment by zeitounator** [comment]
This looks like a problem with some SSO protocol. Did you launch the app with the `--webDebug` option and inspect the network tab ? Any evidence of a redirection problem ?

**Comment by dleonhartsberger-travelclick** [comment]
> This looks like a problem with some SSO protocol. Did you launch the app with the `--webDebug` option and inspect the network tab ? Any evidence of a redirection problem ?

This is what I get when I open it with that parameter (and nothing happens):

```
$ teams-for-linux --webDebug
configPath = /home/dleonhartsberger/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
processArgs [ '/opt/teams-for-linux/teams-for-linux', '--webDebug' ]
```

What do you mean with the network tab? I don't see any redirection, it's as if the App was opened, but I cannot see it anywhere.

**Comment by zeitounator** [comment]
This is basically what you should see starting with the webDebug.
![Screenshot from 2019 11 20 12 42 11](https://user-images.githubusercontent.com/176776/69236481-e2b78f00-0b93-11ea-85cd-57427757885a.png)

If even this does not display as expected, I'll let someone else comment on the case because I have no idea what could be wrong.

**Comment by dleonhartsberger-travelclick** [comment]
Since I cannot see any window for Teams (it doesn't open!), I cannot see any tab, so I'm afraid that doesn't help, thanks anyway

**Comment by IsmaelMartinez** [comment]
Hi, can you fill the bug template? It helps to use the template as then we
can determine what package type you are using, and other typical questions.

I assume you are using snap package. Can you try Deb ? (Check the released
folder).

Thanks and thanks Olivier

**Comment by dleonhartsberger-travelclick** [comment]
I'm afraid I created the issue filling all the information I can related to the bug template.
Only thing missing is thay I've tried and I currently have both versions snap and deb installed and the same happens to both. Not sure how to help you replicate and I wish I knew why this is happening as well

**Comment by IsmaelMartinez** [comment]
Can you try another desktop? (that doesn't have to be the final solution, but a check to see if it is related to a desktop update) 

It does smell like desktop libraries changes. Does other electron app work? (slack, whatsapp, visual studio code...)  Thanks

**Comment by IsmaelMartinez** [comment]
closing as there is no more answers from my last question 15 days ago.
