### ISSUE TITLE
Micosoft Teams - initializing 

### ISSUE THREAD

**Issue by martin-jamszolik** [IsmaelMartinez/teams-for-linux#309]
I cannot get the latest flatpak client to initialize

**To Reproduce**
Just start the client. 

**Expected behavior**
My account to be opened with all teams listed

**Screenshots**
see attached

**Desktop (please complete the following information):**
Fedora 30

![Screenshot from 2019-11-25 10-49-56](https://user-images.githubusercontent.com/1155998/69555715-9f816580-0f71-11ea-9acd-5f3822c4c3e8.png)

**Comment by martin-jamszolik** [comment]
I signed out and tried again.
I got rid of the 2 errors.
The screens is now stuck at Loading....

![Screenshot from 2019-11-25 10-57-37](https://user-images.githubusercontent.com/1155998/69556315-84fbbc00-0f72-11ea-8cc3-65fde52e6b8b.png)

**Comment by martin-jamszolik** [comment]
I am certainly able to login to Microsoft Teams using chrome browser.

**Comment by martin-jamszolik** [comment]
Okay, started working at some point. Closing. 
Thank you for your work and support for flatpak

**Comment by IsmaelMartinez** [comment]
Glad you got it working. I have seen sometimes it taking far too long on the  first log in after initial install...
