### ISSUE TITLE
Error on Help Menu items

### ISSUE THREAD

**Issue by homebrew79** [IsmaelMartinez/teams-for-linux#31]
When I try to use either of the menu items under the help menu, I get an error as displayed in the attached screenshot.

This is on Fedora 29 x86_64
gnome on wayland

Teams for linux version 0.1.10, installed from RPM

![image](https://user-images.githubusercontent.com/221612/50007449-97a1fe80-ff76-11e8-84e6-9ff874839afc.png)

**Comment by IsmaelMartinez** [comment]
Hi, 

Can you try this with version 0.1.9? The version 0.1.10 is a pre-release and shouldn't really be use a part from for testing. I create it to try to fix an issue with github integration but got a bit sidetrack with a few other fixes.

Let me know if you still have the issue in 0.1.9.

**Comment by IsmaelMartinez** [comment]
It might be fix in 0.1.11 as the module that it was in use has been change for the default electron one. Either get the current code an run `yarn start` or reopen if you see this issue in release 0.1.11 (to be release in the next few days)

**Comment by IsmaelMartinez** [comment]
Hi @homebrew79 ,

As with the other issue you reported, Version 0.1.11 is ready (pre-release) and should have cover this issue. Can you test it and reopen if is not the case?

Thanks,
Ismael

**Comment by homebrew79** [comment]
The menu items are now working as expected. They open a new tab in my browser.
