### ISSUE TITLE
Disable automatic adjustment of microphone level

### ISSUE THREAD

**Issue by mschirmacher** [IsmaelMartinez/teams-for-linux#310]
**Is your feature request related to a problem? Please describe.**
Since a few days, teams will constantly the input gain until, finally, nobody can understand me anymore due to the incredible distortion of my voice.

**Describe the solution you'd like**
It would be great if we'd be able to disable this behavior in teams!

**Describe alternatives you've considered**
I tried  to disable this bevaior with pulseaudio - but it seems impossible

Is this possible for you?

**Comment by IsmaelMartinez** [comment]
Hi @mschirmacher,

Check the config options on the settings when in a call. It might be picking up the wrong micro (internal vs headset or whatever you are using)

The 3 dots (...) more actions. "show device settings"

Otherwise, this one will be one for the uservoice and not here.

**Comment by dagmoller** [comment]
Maybe loading this chrome extension?
https://chrome.google.com/webstore/detail/disable-automatic-gain-co/clpapnmmlmecieknddelobgikompchkk

**Comment by enricojonas** [comment]
@dagmoller have been using this extension for quite some time now in chrome. So yes, that would be an option... must be configurable though, I guess not everyone wants to disable autogain.

**Comment by IsmaelMartinez** [comment]
hi @enricojonas , electron does allow for extensions to be added. Hopefully someone has the time to implement this. I might have some time in 2023... but can't put a ETA yet.

https://www.electronjs.org/docs/latest/api/extensions#:~:text=Electron%20supports%20a%20subset%20of,support%20some%20other%20extension%20capabilities.

Seems fairly simple to implement so probably we can add an array of extensions in the config options, and people then can configure the ones they want to use. It opens quite a few options.
