### ISSUE TITLE
Whiteboard feature doesn't work (loading forever)

### ISSUE THREAD

**Issue by sezaru** [IsmaelMartinez/teams-for-linux#312]
**Describe the bug**
When I am in a conference and someone (or me) loads the whiteboard feature, it shows this screen and never finishes loading:
![image](https://user-images.githubusercontent.com/279828/71264795-9a6ec680-2323-11ea-9e89-dd80b50a70b0.png)

**To Reproduce**
1. Start a conference;
2. Click on share button;
3. Click on Whiteboard button.

**Additional context**
I also took a screenshot of the console error messages if that can help to hint what the problem is:
![image](https://user-images.githubusercontent.com/279828/71264884-ca1dce80-2323-11ea-9d42-c79c18df4132.png)

Thanks

**Comment by IsmaelMartinez** [comment]
Hi and thanks for reporting this.

As for #281 I will not spend much time trying to implement that feature available in their client. 

Feel free to investigate further. I leave it open as bug, help wanted and enhancement. I am happy to help so shout if you got any suggestions/issues/questions.

Thanks again!

**Comment by IsmaelMartinez** [comment]
closing due inactivity. Doesn't seem to be anyone interesting into picking this up so I will close it for now. 

maybe one day I get time to do this things again and I pick this up. Feel free to ping if you are working on it.
