### ISSUE TITLE
GNOME Notifications don't display when active on another workspace

### ISSUE THREAD

**Issue by Fmstrat** [IsmaelMartinez/teams-for-linux#313]
**Describe the bug**
When Teams for Linux is open on another workspace and a chat is selected, notifications do not show up.

**To Reproduce**
0. Start Teams for Linux with `enableDesktopNotificationsHack`
1. Open any chat with a person
2. Move to another workspace
3. Have that person send a message
4. No notification

**Expected behavior**
The notification should display and the red icon should show up. If you leave the chat, and say, go to your calendar before switching workspaces, the notification displays.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation package: deb
 - Version: 1.0.0

**Comment by IsmaelMartinez** [comment]
Hi @Fmstrat , I did had this problem a long time ago and solve it by uninstalling the libnotification and installing it again. 

https://github.com/IsmaelMartinez/teams-for-linux/issues/42#issuecomment-458305097

Notice that this will probably uninstall whatever uses that libnotification (teams-for-linux included) but you will probably not have many programs using it.

hope helps

**Comment by Fmstrat** [comment]
Well, this is odd:

```
$ sudo apt-get remove libappindicator-*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libappindicator-dev' for glob 'libappindicator-*'
Note, selecting 'libappindicator-doc' for glob 'libappindicator-*'
Package 'libappindicator-doc' is not installed, so not removed
Package 'libappindicator-dev' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

These are what I have installed now:
```
$ apt list --installed |grep indicator

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gir1.2-appindicator3-0.1/bionic,now 12.10.1+18.04.20180322.1-0ubuntu1 amd64 [installed,automatic]
gnome-shell-extension-appindicator/bionic,bionic,now 18.04.1 all [installed]
libappindicator1/bionic,now 12.10.1+18.04.20180322.1-0ubuntu1 amd64 [installed,automatic]
libappindicator3-1/bionic,now 12.10.1+18.04.20180322.1-0ubuntu1 amd64 [installed]
libindicator3-7/bionic,now 16.10.0+18.04.20180321.1-0ubuntu1 amd64 [installed]
libindicator7/bionic,now 16.10.0+18.04.20180321.1-0ubuntu1 amd64 [installed,automatic]
```

And I download from `https://github.com/IsmaelMartinez/teams-for-linux/releases/download/` I'm guessing I should remove versions 1 and 3, but wanted to confirm.

**Comment by IsmaelMartinez** [comment]
I think is both, but make sure you check what is going to remove. 

In my case it did remove the brave-browser also so then you need to install it again.

**Comment by IsmaelMartinez** [comment]
Also, do they work when you minimize the app? If so, is electron not detecting the number changing. Not sure what issue was related but there is info in the issues of why is pretty difficult to fix

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Please ping back with more info if you want it reopen.
