### ISSUE TITLE
Support for proxy by url / pac file on linux

### ISSUE THREAD

**Issue by Kalyan-M** [IsmaelMartinez/teams-for-linux#315]
Currently, as far as I'm aware, teams can use a proxy but it should be started form command line with proxy-server config. It would greatly enhance the user experience if teams on linux had support for proxy url / pac file and also had an option to configure proxy via UI.

**Comment by IsmaelMartinez** [comment]
Hi @Kalyan-M ,

You can save the configuration ina config.json file as explained in the https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config/README.md file.

Having a UI to configure stuff might be great, but will require quite a lot of development. Feel free to give it a go and ask for any questions if you have.

**Comment by IsmaelMartinez** [comment]
closing due inactivity
