### ISSUE TITLE
Microphone not recognized

### ISSUE THREAD

**Issue by ladyfrauke** [IsmaelMartinez/teams-for-linux#317]
The microphone is not recognized during calls, the only microphone that works is the one in my webcam. When selecting Built-in Audio Device, no sound can be heard at all. I have tried with two different headsets, one connected via 3,5mm stereo jack and the other via bluetooth (USB bluetooth plug).

**Comment by IsmaelMartinez** [comment]
Hi @ladyfrauke , 

Can you fill the bug template? It will tell me what system, package, stuff are you using and tends to safe me lots of time to find the issue or solution.

Can you check:

* Configuring pulse audio as suggested in here:
https://github.com/IsmaelMartinez/teams-for-linux/issues/117#issuecomment-487840040
* Running `teams-for-linux --try-supported-channel-layouts` as suggested in here:
https://github.com/IsmaelMartinez/teams-for-linux/issues/277#issuecomment-529521117

Hope helps,

**Comment by ladyfrauke** [comment]
Hi @IsmaelMartinez - I resolved the mystery. It's actually MS Teams that does not recognize the 3.5 mm jack (the one my microphone connects to). I have now connected it with a 3.5mm jack-to-USB cable via a USB port and it works just fine. 
(I couldn't find the bug template - can you provide me with a link to it? I actually have one other issue that I couldn't resolve by myself and would like to post this).
