### ISSUE TITLE
Open Teams Meeting URL directly in Teams App without clicking "Open xdg-open" button

### ISSUE THREAD

**Issue by taylormia** [IsmaelMartinez/teams-for-linux#320]
When I click a Teams meeting URL in an email or meeting invitation, it opens the "Open xdg-open?" dialog in Chrome and only when I click the "Open xdg-open" button does the meeting open in the Teams application.
Is there a way to **directly** open the meeting in the Teams app when the URL is clicked without having to  go through the extra step of clicking the "Open xdg-open" button in the browser?

![image](https://user-images.githubusercontent.com/34145387/74592454-3bf25b80-4fe7-11ea-816d-b61ffdd43fd3.png)

**Comment by taylormia** [comment]
btw, I'm on the Teams App version 1.3.00.958 on Kubuntu 19.10

**Comment by IsmaelMartinez** [comment]
Hi @taylormia , 

Please report your issue to MS teams page, the version you are reporting indicates you are using the official client. 

https://microsoftteams.uservoice.com/

Hope helps,
