### ISSUE TITLE
Popup for web version appears

### ISSUE THREAD

**Issue by PhitherekReborn** [IsmaelMartinez/teams-for-linux#323]
**Describe the bug**
The popup that advertises the Windows version of Teams shows up in Teams for Linux

**To Reproduce**
1. Open Teams for Linux
2. See the popup

**Expected behavior**
The popup is not present

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Installation package deb
 - Version 1.0.0

**Additional context**
The issue did not reproduce when I restarted Teams for Linux.

**Comment by IsmaelMartinez** [comment]
Hi, I think ms have changed that pop up. Even if it is a bit of a pain, it only happens randomly and not that often in my case (once last month)

Is that the same on your cae? Thanks for reporting!

**Comment by PhitherekReborn** [comment]
It has not appeared again since the time of this report. Seems like it really is only a minor annoyance. Feel free to close this issue if you think it's not worth fixing. Thank you for the tremendous amount of work that you've put in this project.

**Comment by IsmaelMartinez** [comment]
I will close this as it is quite random and not that common. Thanks again for reporting. If it gets repetitive or common, just ping in here and I will reopen and have a look
