### ISSUE TITLE
How to avoid it starting on every session?

### ISSUE THREAD

**Issue by vejeta** [IsmaelMartinez/teams-for-linux#325]
Whenever I start a new session on my desktop, Teams auto starts, what's the way of disabling this behaviour?

Additionally, is there any way for it close when you quit it, instead for it staying working on the background?

**Comment by IsmaelMartinez** [comment]
Hi, 

The auto start will depend on your system settings (Ubuntu or whatever you are using) do a quick google and you should be able to find it.

Regarding the close, check the config options. There is a closeAppOnCross that you can use for that second question.

Hope helps.

**Comment by vejeta** [comment]
Thanks, Ismael

I created a small PR to explain it in the documention.
https://github.com/IsmaelMartinez/teams-for-linux/pull/327
