### ISSUE TITLE
Microphone audio distorted

### ISSUE THREAD

**Issue by joakim-tjernlund** [IsmaelMartinez/teams-for-linux#326]
**Describe the bug**
Getting some reports from our users that microphone audio is troublesome, when
attending an conference, other participants has trouble hearing teams-for-linux users.
Either audio is distorted and/or muted.

**To Reproduce**
Join an conference and talk, get feedback audio quality.

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...]
 - Version 1.0.0 debian pkg

**Comment by IsmaelMartinez** [comment]
Hi,

Can you check the microphone issues that are closed? It tends to be a jack, audio settings or ms settings. 

https://github.com/IsmaelMartinez/teams-for-linux/issues?q=is%3Aissue+audio+is%3Aclosed

Hope helps
