### ISSUE TITLE
100% cpu utilization

### ISSUE THREAD

**Issue by gionn** [IsmaelMartinez/teams-for-linux#328]
After every call, cpu usage of teams spike to 100% all the time.

Relaunching application fix it, untile the next call.

![image](https://user-images.githubusercontent.com/71768/76642685-fb3d2200-6553-11ea-94f2-8fc89993bd56.png)

teams 1.3.00.958 (.deb package)
Ubuntu 18.04.4 LTS

Similar to #293

**Comment by gionn** [comment]
wrong project? :dancer:

**Comment by IsmaelMartinez** [comment]
Yeah, that is an issue on the official app. This app, existen before the
official, doesn't have the high memory usage issue. Give it a try if you
want. Still supported at the moment because of that issue and other non
supported authentication. Hope helps
