### ISSUE TITLE
Windows empty blank on Ubuntu 18.04 Xubuntu XFCE

### ISSUE THREAD

**Issue by mica100** [IsmaelMartinez/teams-for-linux#330]
**Describe the bug**
After starting the teams-for-linux the window popup, but it's white, blank and empty. The usual CTRL+R isn't working.
Bevor it was working on Ubuntu 18.04 Gnome Desktop, but after login with Xubuntu session, which is an XFCE desktop, the application window is always empty. MS-teams is working in Firefox or Chrome.

**To Reproduce**
1. Start teams-for-linux from commandline or XFCE Application menu
2. see blank window

**Expected behavior**
First the login should be requested and then the MS-teams application content should be shown.

**Screenshots**
A blank window. Just that. No error output on terminal, when starting from commandline.

**Desktop**
 - OS: Ubuntu 18.04LTS, Xubuntu, XFCE session
 - Installation package deb
 - Version 1.0.0

**Additional context**
It's somehow related to my network connection. It's working if I'm directly connected to the internet. If I'm connected to a network with firewall restrictions, where I need a http proxy to access the internet, it's not working in XFCE session. In Gnome session it worked in both.

**Comment by mica100** [comment]
It's related to my http proxy setting. Somehow the Gnome environment had the correct proxy setting available. While XFCE (even with checked "start Gnome services" on Session start) didn't provide the same setting.

Specifying the proxy on commandline with --proxyServer http://myproxy.abc:8000 works.

**Comment by IsmaelMartinez** [comment]
Thanks for reporting the solution.

**Comment by compleathorseplayer** [comment]
I found an easier solution, which was to just use atom --disable-gpu

**Comment by IsmaelMartinez** [comment]
Thanks for reporting another solution or option to try to make it work!
