### ISSUE TITLE
Microsoft Teams for FreeBSD

### ISSUE THREAD

**Issue by grahamperrin** [IsmaelMartinez/teams-for-linux#331]
Might a port to FreeBSD be within scope for this repo? 

From the name – _for Linux_ – I assume not but still, I'm curious. 

Ports of Electron: 

* https://www.freshports.org/devel/electron4/
* https://www.freshports.org/devel/electron6/
* https://www.freshports.org/devel/electron7/

Thanks

----

If it's out of scope, I'm happy enough with extended Firefox 74.0: 

![image](https://user-images.githubusercontent.com/192271/77513812-9942bd80-6e6d-11ea-9753-89bc9b418785.png)

**Comment by IsmaelMartinez** [comment]
Hi, 

I am not planning to port it to FreeBSD but I am happy to help with advice, info.

Other people have created packages for arch, snap, AppImage and FlatPack. Not sure if any of those, or the way they have done it, might help you.

**Comment by IsmaelMartinez** [comment]
I will close this as no-one has shown interest on doing something about it. Sorry and I hope the  Firefox 74.0 does do the job for you.
