### ISSUE TITLE
Cannot open display

### ISSUE THREAD

**Issue by jsitarek** [IsmaelMartinez/teams-for-linux#333]
The application does not start 

when running: teams-for-linux
it only gives: 
Gtk-Message: 09:09:21.685: Failed to load module "overlay-scrollbar"

(teams-for-linux:6400): Gtk-WARNING **: 09:09:21.686: cannot open display: :0

 - OS: Ubuntu 14.04
 - Installation package: snap (tested both --edge and --stable version)
 - Version  1.0.0

**Comment by IsmaelMartinez** [comment]
Hi @jsitarek , can you try the deb package in the release folder.

https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.0

That smells like snap issues not teams issues.

**Comment by jsitarek** [comment]
Thank you for a fast feedback. 
I downloaded the .snap file and tried:
snap install ./teams-for-linux_1.0.0_amd64.snap 
but I'm getting:
error: cannot find signatures with metadata for snap "./teams-for-linux_1.0.0_amd64.snap"

looking on the net I might be missing .assert file, but I cannot find it in the webpage you provided.

**Comment by IsmaelMartinez** [comment]
have you tried the snap in https://snapcraft.io/teams-for-linux ?

**Comment by jsitarek** [comment]
this webpage does not have a package inside and tells me to do: sudo snap install teams-for-linux which is how I installed it in the first place

**Comment by IsmaelMartinez** [comment]
ok, can you try the deb package and/or AppImage?
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.0

**Comment by IsmaelMartinez** [comment]
closing due inactivity. Ping with more info if you want it re-open. Thanks

**Comment by jsitarek** [comment]
I could make it work in the end (I think using the .deb package as you suggested), sorry for not reporting that it worked.

**Comment by IsmaelMartinez** [comment]
not a problem ;) and glad to hear it works. Thanks!
