### ISSUE TITLE
Raspberry Pi Support armhf or amd64

### ISSUE THREAD

**Issue by sonicdee** [IsmaelMartinez/teams-for-linux#334]
Hi there,
I have an urgent request on - is it possible to get the teams client ready for raspbian !?

I'm not too depp in internals but there is nowhere a arm release of Teams, is it?

While there is a 64bit kernel for Raspberry, I'm not shure If it work currently,
I've activated it, try to install:

but there are missing things: (in german ;) )

sudo dpkg -i Downloads/teams-for-linux_1.0.0_amd64.deb
Vormals nicht ausgewähltes Paket teams-for-linux:amd64 wird gewählt.
(Lese Datenbank ... 161987 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../teams-for-linux_1.0.0_amd64.deb ...
Entpacken von teams-for-linux:amd64 (1.0.0-598) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von teams-for-linux:amd64:
 teams-for-linux:amd64 hängt ab von libgtk-3-0.
 teams-for-linux:amd64 hängt ab von libnotify4.
 teams-for-linux:amd64 hängt ab von libnss3.
 teams-for-linux:amd64 hängt ab von libxss1.
 teams-for-linux:amd64 hängt ab von libxtst6.
 teams-for-linux:amd64 hängt ab von libatspi2.0-0.
 teams-for-linux:amd64 hängt ab von libuuid1.
 teams-for-linux:amd64 hängt ab von libappindicator3-1.
 teams-for-linux:amd64 hängt ab von libsecret-1-0.

dpkg: Fehler beim Bearbeiten des Paketes teams-for-linux:amd64 (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für gnome-menus (3.31.4-3) werden verarbeitet ...
Trigger für desktop-file-utils (0.23-4) werden verarbeitet ...
Trigger für mime-support (3.62) werden verarbeitet ...
Trigger für hicolor-icon-theme (0.17-2) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 teams-for-linux:amd64

**Comment by IsmaelMartinez** [comment]
hi @sonicdee , 

We don't provide a raspberry Pi build package, but we are using electron-builder and that does provide a packaging for arm

https://www.electron.build/cli.html#targetconfiguration

you can play around with it and add a pull request if you want to integrate it here. 

Our build configuration lives in the package.json
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L57

to support it, you will need to add another target for arm.

let me know how you get on.

**Comment by sonicdee** [comment]
getting my hand dirty:
I installed yarn (yarnpkg in the pi)
added arm to the target:
     "target": [
        "rpm",
        "deb",
        "tar.gz",
        "snap",
        "AppImage",
        "pacman",
        "armv7l"
      ],
running, I get Failed to get the config file, nothing happens:

pi@raspberrypi:~/Documents/teams-for-linux-develop $ yarnpkg start
yarn run v1.13.0
$ yarn install && electron ./app
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder  version=22.4.1
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=spellchecker@3.7.0 platform=linux arch=armv7l
  • rebuilding native dependency  name=spellchecker version=3.7.0
configPath = /home/pi/.config/Electron
Failed to get the config file, using default values
configFile = {}
processArgs [ '/home/pi/Documents/teams-for-linux-develop/node_modules/electron/dist/electron',
  './app' ]

**Comment by IsmaelMartinez** [comment]
that seems to be ok, it should open a UI/pop up, but maybe you need chromium installed on that wee pi

**Comment by sonicdee** [comment]
chromium is there by default,
anyway there is a kind of hack making it running on arm using a other user-agent in chromium
https://github.com/elmiba/Teams

**Comment by IsmaelMartinez** [comment]
no problem. I have been playing a bit with github actions (as travis takes tooo long for any build) and might be able to produce a binary at some point... if that the case I will ping you here. 
Closing as there is a workaround...

**Comment by IsmaelMartinez** [comment]
by the way @sonicdee , can you share screens and see video with that hack? Ta
