### ISSUE TITLE
Timezone is always displayed in UTC

### ISSUE THREAD

**Issue by LiohMoeller** [IsmaelMartinez/teams-for-linux#335]
Today I have upgraded to the 1.3 version and the timezone is always displayed in UTC. e.g. a scheduled meeting for 10.30 localtime is displayed as 8.30 as we are in UTC+2 currently.

Local timezone is configured correctly and time is also correct.

**Comment by IsmaelMartinez** [comment]
Wrong project. You must be using the official ms teams. That issue is not
present in this client. Give it a try if you wish. ;)
