### ISSUE TITLE
teams-for-linux fail to open screen for share after already shared

### ISSUE THREAD

**Issue by cyrg38** [IsmaelMartinez/teams-for-linux#337]
**Describe the bug**
The bug seems to appear every time we exchange the operator sharing his screen : the pop-up for sharing does not open

**To Reproduce**
1. engage meeting
2. somebody else share his screen
3. click to share my screen
4. pop-up does not appear and nothing is shared even if status indicates the sharing

**Expected behavior**
the pop-up must always open to permit sharing

**Screenshots**
difficult

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - snap
 - Version 1.0.0

**Additional context**
The sharing pop-up appears everytime when sharing from my side only.
But I cannot say if the behavior does not appear from time to time after a long time using teams.
I also would like to say "Great great work !"

**Comment by IsmaelMartinez** [comment]
Hi, 

Just to clarify, if someone is already sharing their screen, you can't share your screen. 

I'm right? Have you check what happens if they 1st stop sharing their screen?

Thanks!

**Comment by IsmaelMartinez** [comment]
closed due inactivity. Please ping back with the answers from my previous question and I can look at it further. Thanks
