### ISSUE TITLE
Does not have webcam preview in settings

### ISSUE THREAD

**Issue by Svetlana-T** [IsmaelMartinez/teams-for-linux#338]
**Describe the bug**
Does not have webcam preview in settings

**To Reproduce**
1. Go to '...'Settings

**Expected behavior**
'Devices' section present and contains webcam preview.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...] deb
 - Version [e.g. 0.1.17] 1.0.0

**Comment by IsmaelMartinez** [comment]
Hi @Svetlana-T, thanks for reporting.

This is not a bug but an enhancement.

I will leave it open just in case someone can investigate this.

**Comment by IsmaelMartinez** [comment]
Seems like no one picks this up. I will suggest reporting it in the Microsoft user voice (preview for webcam in browsers)
