### ISSUE TITLE
Audio problems with Fedora 31

### ISSUE THREAD

**Issue by tkalfaoglu** [IsmaelMartinez/teams-for-linux#340]
For some reason neither teams nor sudo teams has sound input or output under "teams" except for the test call. The test call works fine.. But during a meeting the device settings shows the output as being muted and the microphone shows no levels.. It eventually says there is something wrong with my mike.

I maxed out things using pavucontrol and alsa mixer. Still nothing.. I tried running it as root, nothing..

I even have a webcam plugged it to see if it performs better.. Nope, same lack of input and output.

This is a Acer Nitro 5:
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Generic [HD-Audio Generic], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Generic_1 [HD-Audio Generic], device 0: ALC255 Analog [ALC255 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
[turgut@tklaptop ~] $ 

$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Generic_1 [HD-Audio Generic], device 0: ALC255 Analog [ALC255 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: USB20Camera [USB2.0_Camera], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

I tried the --try-supported-channel-layouts  trick, no change.
what shall I try?
This laptop records and plays just fine.. any of the other tool can use the mike and speakers without issues..

**Comment by tkalfaoglu** [comment]
After I disabled its piping logs I see:
$ teams
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
(node:153544) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added. Use emitter.setMaxListeners() to increase limit
[turgut@tklaptop ~] $

**Comment by tkalfaoglu** [comment]
during teams launch and starting a video meeting..

Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): EDID vendor "LGD", prod id 1496
Apr 07 16:06:21 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): Printing DDC gathered Modelines:
Apr 07 16:06:21 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): Modeline "1920x1080"x0.0  138.70  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync (66.7 kHz eP)
Apr 07 16:06:21 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): EDID vendor "LGD", prod id 1496
Apr 07 16:06:21 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): Printing DDC gathered Modelines:
Apr 07 16:06:21 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): Modeline "1920x1080"x0.0  138.70  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync (66.7 kHz eP)
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:21 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:22 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:22 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:22 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:22 tklaptop.kalfaoglu.com gnome-shell[7607]: JS WARNING: [/home/turgut/.local/share/gnome-shell/extensions/Panel_Favorites@rmy.pobox.com/extension.js 166]: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?
Apr 07 16:06:25 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): EDID vendor "LGD", prod id 1496
Apr 07 16:06:25 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): Printing DDC gathered Modelines:
Apr 07 16:06:25 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): Modeline "1920x1080"x0.0  138.70  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync (66.7 kHz eP)
Apr 07 16:06:25 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): EDID vendor "LGD", prod id 1496
Apr 07 16:06:25 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): Printing DDC gathered Modelines:
Apr 07 16:06:25 tklaptop.kalfaoglu.com /usr/libexec/gdm-x-session[7180]: (II) modeset(0): Modeline "1920x1080"x0.0  138.70  1920 1968 2000 2080  1080 1083 1088 1111 +hsync -vsync (66.7 kHz eP)
Apr 07 16:07:01 tklaptop.kalfaoglu.com kernel: usb 1-2: current rate 47872 is different from the runtime rate 48000
Apr 07 16:07:08 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Doing resync
Apr 07 16:07:08 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Playback too far ahead (103891), drop source 26592
Apr 07 16:07:08 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Doing resync
Apr 07 16:07:08 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Playback too far ahead (12389), drop source 3168
Apr 07 16:07:09 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Playback too far ahead (17369), drop source 4440
Apr 07 16:07:10 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Playback too far ahead (10006), drop source 2560
Apr 07 16:07:11 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Doing resync
Apr 07 16:07:11 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Playback too far ahead (4219), drop source 1080
Apr 07 16:07:11 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Doing resync
Apr 07 16:07:11 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Playback too far ahead (5812), drop source 1480
Apr 07 16:07:12 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Playback too far ahead (10028), drop source 2560
Apr 07 16:07:14 tklaptop.kalfaoglu.com pulseaudio[7591]: E: [alsa-source-ALC255 Analog] module-echo-cancel.c: Playback after capture (-43), drop sink 88
^C
[turgut@tklaptop ~] $

**Comment by IsmaelMartinez** [comment]
Hi, 

Can you provide the information from the bug template? you must be running an ancient version of teams as we changed the command to teams-for-linux a while ago.

Thanks

**Comment by tkalfaoglu** [comment]
Many thanks for your reply -- I hadn't realized that the version that came with Fedora 31 was outdated. I unsinstalled that, and installed the copy I obtained from you. I am pleased to report that the audio now works well.

**Comment by IsmaelMartinez** [comment]
Hi,

Didn't even know fedora packaged the app!! (nice surprise)

Thanks for using the app and hope its useful for you.

Regards,
Ismael
