### ISSUE TITLE
How to get background features?

### ISSUE THREAD

**Issue by Kalyan-M** [IsmaelMartinez/teams-for-linux#343]
**Is your feature request related to a problem? Please describe.**
I cannot find background features like blur and background change in a video call.

**Describe the solution you'd like**
Way to enable background features.

**Additional context**
Is this a limitation of the client or can it be achieved using a different user agent?

**Comment by IsmaelMartinez** [comment]
Hi, I will see how feasible this is. I believe it's not available in any of the browsers so it might be pretty difficult.

**Comment by DarkSmile92** [comment]
Would love to see this feature coming to linux also!

**Comment by IsmaelMartinez** [comment]
I will appreciate if someone can take the lead on this. I have an approximate 30 minutes a week to dedicate to this. I am happy to guide/support but canna do it all. 

To start, it will be good if someone can check if the MS uservoice has a feature request for the feature for browsers. Thanks

**Comment by ikoga** [comment]
Hi,

I found there are some requests that related to this topic in the Microsoft Teams uservoice.

* Background effects teams for linux  
  https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40247473-background-effects-teams-for-linux

* blur background for web browser  
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/38985064-blur-background-for-web-browser

* Blur for linux  
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40014109-blur-for-linux

**Comment by cpfeiffer** [comment]
I didn't try this client yet, but it might very well work with this:
https://github.com/fangfufu/Linux-Fake-Background-Webcam

**Comment by ikoga** [comment]
I've tried v4l2loopback with this way, it works well on openSUSE 15.1 my laptop!
It took heavy CPU load even if it was Core i7.

**Comment by IsmaelMartinez** [comment]
maybe someone can look into integrating it... I am happy to support/help

**Comment by IsmaelMartinez** [comment]
I am going to close this as there is a know workaround now that could be use to archive this and even more advance features.

Also, I don't think this work can easily be integrated into this client.
