### ISSUE TITLE
screen share - individual display/screen on multiple output setting

### ISSUE THREAD

**Issue by wideawakening** [IsmaelMartinez/teams-for-linux#344]
**Is your feature request related to a problem? Please describe.**
My workspace consists in two display devices.
When I need to share screen, I only get to choose one of the following options

1. Share a single window, which gives me problems when having sub-windows prompted
2. Share full desktop (both displays) which means not much readability.
---
**Describe the solution you'd like**
Teams (including Linux version), gives the option of sharing one of the screens
![image](https://user-images.githubusercontent.com/1073243/79311378-a1869980-7efd-11ea-8f7b-47d448f7860d.png)

---
**Describe alternatives you've considered**
My current workaround is use option 1, with constant checkup with my colleagues, or just remove one of the displays while in the meeting.

---
pd1: the hell, sorry for the empty feat req.. went to a beta option and lost the content
pd2: Thanks for the amazing job with the app Ismael and cheers from Spain!

**Comment by IsmaelMartinez** [comment]
Hola,

This is a bit more difficult than it looks/seems as it is a limitation in electron. 

I leave it open until I find further info or see if there is another workaround.

**Comment by IsmaelMartinez** [comment]
Its the same issue in many other tools/clients. 

you can go with the comment 73 from here... probably the neater solution. You create a bash script that "shares" your screen with xrandr
https://bugs.chromium.org/p/chromium/issues/detail?id=437507#c73

another workaround is to have vlc or another tool to capture your screen... 
http://www.baremetalcode.com/gnu_linux/2019/02/20/linux-screen-share-over-hangouts.html
you can use it from the command line as it says in this answer
https://unix.stackexchange.com/questions/152435/sharing-your-desktop-with-google-hangouts-dual-monitor-and-gnome-shell

or wait until we migrate electron to a future version that includes chrome v83... (that is not going to happen any time soon...)

hope helps, closing as we canna do much about it at the moment. Sorry!

**Comment by elkh510** [comment]
hi @IsmaelMartinez 
any updates ?
thanks!

**Comment by IsmaelMartinez** [comment]
Workaround is documented in my previous comment. Not the nicest but this client is no longer under development. Feel free to submit a PR if you find a way to sort this out. Thanks!
