### ISSUE TITLE
Trying to share screen results in being dropped from the call

### ISSUE THREAD

**Issue by matmaxgeds** [IsmaelMartinez/teams-for-linux#345]
**Describe the bug**
Trying to share screen results in being dropped from the call

**To Reproduce**
1. Join call
2. Click on share screen and select screen
3. User is dropped from the call
4. Screen is not shared

**Expected behavior**
Not to be dropped from the call, screen to be shared

**Screenshots**
Afraid it happens to fast

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Installation package: deb from https://products.office.com/en-us/microsoft-teams/download-app#allDevicesSection
 - Version : 1.3.00.xxxx

**Additional context**
Teams Preview works great otherwise

**Comment by IsmaelMartinez** [comment]
Hi @matmaxgeds ,

You are reporting at the wrong place. This is not the official MS Teams app but the much older unnoficial. 

People using the official app have been reporting issues with calls (high cpu usage) and dropping from calls due screenshare. 

Feel free to give this app a go if you have any of those issues. I will be supporting it until MS finish their tidy up work... that looks like is taking longer than I anticipated. 

More info about the packages and how to use it can be found in the base readme (https://github.com/IsmaelMartinez/teams-for-linux/) Hope helps,
