### ISSUE TITLE
Not really a bug - more a feature binary request

### ISSUE THREAD

**Issue by ArnoldSchiller** [IsmaelMartinez/teams-for-linux#347]
**Describe the bug**
The binaries are not 32bit

**To Reproduce**
1. See above 

**Expected behavior**
Microsoft Teams from the microsoft teams website are 64bit only - and your Software works with i386 - that's cool thank you very much for this.

**Screenshots**
No screenshot necessary

**Desktop (please complete the following information):**
 - ubuntu 18.04 i386
 - Installation from source with 
sudo echo deb https://deb.nodesource.com/node_8.x bionic main | sudo tee /etc/apt/sources.list.d/nodejs8.list
apt install nodejs
git clone https://github.com/IsmaelMartinez/teams-for-linux
npm install
npm start

**Additional context**
"Add any other context about the problem here." hmm you are cool and better as the hole microsoft department - something like that

**Comment by IsmaelMartinez** [comment]
Hi, had a wee search around and looks like its not supported anymore by electron.
https://www.electronjs.org/blog/linux-32bit-support

Sorry!

**Comment by ArnoldSchiller** [comment]
That are bad news for ia32 - thank's a lot for your good work!
