### ISSUE TITLE
wrong mouse cursor when using snap

### ISSUE THREAD

**Issue by josefschabasser** [IsmaelMartinez/teams-for-linux#350]
**Describe the bug**
Using flatpak the cursors from the current GTK theme are used.
Using snap, the cursors are like this: https://user-images.githubusercontent.com/13423344/29183105-b3e84b0a-7e01-11e7-879b-3d23c9f1bedb.png

**To Reproduce**
1. Install teams-for-linux snap
2. Hover over any button

**Expected behavior**
The current configured cursors should be used.

**Screenshots**
Coming soon...

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Installation package: snap
 - Version: 1.0.4

**Comment by IsmaelMartinez** [comment]
Hi, can you confirm if version 1.0.0 has the right cursors. I have seen that in the past.

Also, check if it’s not system settings (https://github.com/electron/electron/issues/10705#issuecomment-359150690)

Hope helps

**Comment by IsmaelMartinez** [comment]
Close as duplicated (and snap shenanigans )
