### ISSUE TITLE
Microsoft Teams crashes when sharing screen under Linux Ubuntu 18.04.4 TLS

### ISSUE THREAD

**Issue by danielscarvalho** [IsmaelMartinez/teams-for-linux#352]
Microsoft Teams crashes when sharing screen under Linux Ubuntu 18.04.4 TLS

Intalled package: teams_1.3.00.958_amd64.deb

I did 3 months online course successfully with MS Team on Ubuntu, but now it crashes when trying to share screen.

The mouse pointer has never worked with a shared screen.

**Comment by zeitounator** [comment]
Hi @danielscarvalho This project is the non official teams-for-linux client that was already around before MS finally released a first linux version... which is still not working so well apparently.

[You should report your bugs for the above client directly to Microsoft](https://techcommunity.microsoft.com/t5/microsoft-teams/how-to-report-a-bug-in-the-linux-client/m-p/1216524)

If you want to try the alternative implementation proposed in this github project until the Microsoft client becomes stable enough, under ubuntu it can be as easy as `sudo snap install teams-for-linux`. I'm personally using it for the last 18 months as well as several dozen colleagues in my company (after contributing some code to fix issues with SAML authentication).

Cheers.

**Comment by IsmaelMartinez** [comment]
Thanks for answering. Closing as it’s not related to the project. @danielscarvalho , give this client a try. One of my workmates had the exact same issue with the official one but screen share works fine for him with this client. Ta

**Comment by danielscarvalho** [comment]
Using teams-for-linux now. Thanks for your help! And for the good project!
