### ISSUE TITLE
Unable to sign-in, please try again

### ISSUE THREAD

**Issue by pratikv2x** [IsmaelMartinez/teams-for-linux#354]
**Describe the bug**
Whenever I try to sign in either web or app, it says that we couldn't sign you in, please try again later on UBUNTU 16.04 desktop
![Bugs](https://user-images.githubusercontent.com/48052913/82114239-180bf680-974b-11ea-9a7b-df5cff853839.png)

I am having issue in running MS teams in my linux as I cannot sign-in. I am able to sign-in using WINDOWS OS and my android , so it's not the issue from my service provider or admin. I am able to sign-in using UBUNTU 18 desktop, the issue persists on Ubuntu 16.04
  
**To Reproduce**
1. Download .deb file from Git
2. when option pops-up select using "Software launcher"
3. Click to install after download is finished
4. Give your credentials
5. The error will pop-up denying you sign-in
** For the web**
1. Open browser
2. Sign-in to your office 365 
3. From the menu select teams
4. Give your credentials.
5. The error will pop-up

I tried to check if I can debug it but couldn't.

Regards,
Pratik 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Installation package : .deb
 - Version Distributor ID:	Ubuntu
   Description:	Ubuntu 16.04.6 LTS
   Release:	16.04
   Codename:	xenial

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi, can your run in from the command line and see if you get some "missing certificate" message?

Juts run `teams-for-linux` in the terminal.

Make sure it's not already running otherwise it will only focus it.

**Comment by IsmaelMartinez** [comment]
Also, can you specify the version number you are using of the app? Thanks

**Comment by pratikv2x** [comment]
Hello Sir,

Thanks for the prompt response and sorry again to bother you like this.

I tried running MS Teams from the terminal. The issue still persists. Please find the log below:-

root@pratik-Lenovo-Flex-2-14:/home/pratik# teams-for-linux
configPath = /root/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
processArgs [ '/opt/teams-for-linux/teams-for-linux']

(teams-for-linux:13028): libappindicator-WARNING **: Unable to get the session bus: Unknown or unsupported transport 'disabled' for address 'disabled:'

(teams-for-linux:13028): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Unknown or unsupported transport 'disabled' for address 'disabled:'
^Cbefore-quit
window close

I have downloaded the latest version from the Git. Also I have tried the previous versions and the result is the same.

Sorry to bother you again and again.

Regards,
Pratik
________________________________

**Comment by IsmaelMartinez** [comment]
can you log it just using chrome/chromium? it does smell like libraries. Unfortunately Ubuntu 16.04.6 LTS reached end of life so not sure if its just an old node version, old chrome, libappindicator...
Also, check running as root, just to make sure none of this permissions are missing.

**Comment by pratikv2x** [comment]
Hello Sir,

I tried using chromium as well as firefox but still, the issue persists. I guess it must be library issues because when I tried logging-in from another system which ahs Ubuntu 18, I was able to log in.

Thanks again for all the help.

Regards,
Pratik
________________________________

**Comment by IsmaelMartinez** [comment]
closing due inactivity. please ping back with more information if you require any extra help.

**Comment by pratikv2x** [comment]
Hello Sir

You can close the issue but the fact is issue still persists and was unsolved.

Regards,
Pratik

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by IsmaelMartinez** [comment]
Hi @pratikv2x , I can only recommend upgrading your OS. Version 16.04 LTS is not supported by Ubuntu anymore. I wish I could help further but this could be a huge task. 

Check the system logs to see if there is any extra hint of why this could be happening. 

And maybe search the Microsoft Teams uservoice. Your solution might be there. Doing a quick search found this that mentions seting up the right timezone (https://techcommunity.microsoft.com/t5/microsoft-teams/microsoft-team-website-not-loading-on-chrome-latest-and-firefox/m-p/96771)  

Hope helps. I will reopen but keep me updated with your research/investigation. Thanks

**Comment by YVEF** [comment]
Hi. I'm using Arch Linux system and have the same issue. 
I checked several Teams clients on different computer with the same OS and I got the same result - "can't login, try again".
But It happened only today but worked before... 
I agree that the problem cause with library or some config files. But when we can wait for the fix or some advice?

**Comment by IsmaelMartinez** [comment]
hi @YVEF . I will suggest you ask MS in their uservoice. I think they have been having a terrible day today in terms of performance so it might be related.

**Comment by YVEF** [comment]
Hi @IsmaelMartinez Thank you for answer.
I agree, but this happens only on Linux.

**Comment by Xwzyk** [comment]
Same here. Unable to log in even with correct username and password.
Opensuse Tumbleweed.
Teams for linux ver 1.0.0

**Comment by IsmaelMartinez** [comment]
@YVEF and @Xwzyk ,
This ticket is specifically for Ubuntu 16. @pratikv2x  can't log in neither using the client nor the browser. 
You seem to be using different systems and its not clear if you can or cannot login using the browser in your systems.
Please check older tickets and/or open a new ticket following the template. 
To avoid further confusion, I am going to close this ticket and rename it to indicate is for Ubuntu 16.

**Comment by IsmaelMartinez** [comment]
the recommendation is to reach Microsoft to see if they can help on the browser issue. That might probably fix also the client. 
Ubuntu 16 is still a supported OS but reaching its end of life for maintenance updates fairly soon (next year).
![image](https://user-images.githubusercontent.com/430992/86465560-c8e54980-bd29-11ea-90e6-49a7569795fc.png)
