### ISSUE TITLE
Video/Cam-Stream Display

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#356]
Is there a way to show the cam streams from all participants of a video conference or at least a certain number of them? Currently I can only see the video stream of one (the active) user.

**Comment by IsmaelMartinez** [comment]
not possible until MS does it for browser users. I suggest you ask for it in the uservoice (MS)

Please, next time put it as a feature request if you can. Thanks!

**Comment by elhennig** [comment]
Thanks for your clarification. Your client still has some advantages like the sharing of certain windows instead of the complete desktop and being able to set the user agent.

BTW, I guess I used the feature request, but I emptied the description before writing mine.
