### ISSUE TITLE
Menu options in systray not rendering fonts correctly

### ISSUE THREAD

**Issue by rafaelBadan** [IsmaelMartinez/teams-for-linux#357]
**Describe the bug**
Menu options in systray not rendering fonts correctly
(The app works fine except for this issue)

**To Reproduce**
Not sure how to reproduce (just installed teams-for-linux via snap package).

**Expected behavior**
Correct rendering of menu options fonts

**Screenshots**
![manjaro_teams_for_linux_systray](https://user-images.githubusercontent.com/24234786/82381246-3a7a6a00-9a00-11ea-81bd-6c102eabc894.jpeg)

**Desktop (please complete the following information):**
 - OS: Manjaro Lysia 20.0.1
 - Installation package snap
 - Version 1.0.0 (Rev.79)

**Additional context**
I'm using the flat-remix theme for icons and windows, don't know if this affects the font rendering, but this is as far as I can go with the context.

**Comment by IsmaelMartinez** [comment]
Hi,

Can you try:
* using the deb image
* check the following snap "issue" to see if it helps https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/7

I think is related to snap and your system configuration and not the app itself. Hopefully the previous helps.

Cheers

**Comment by rafaelBadan** [comment]
@IsmaelMartinez thanks a lot for the help!

running: 

```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```
did the trick

**Comment by ArashTheKID** [comment]
This happens again on **Ubuntu 20.04 LTS** with gnome desktop. Though the solution helps, i need to run it again every time I (re)start the application... :-(

**Comment by IsmaelMartinez** [comment]
This is strange/annoying. Can you try with another package and see if it
works more reliably? Thanks
