### ISSUE TITLE
Show app window after it was minimized to tray

### ISSUE THREAD

**Issue by adalheid34** [IsmaelMartinez/teams-for-linux#358]
On GNOME Shell 3.34.3 (preinstalled with ubuntu)
Starting teams-for-linux from taskbar or from gnome activities, if it isn't already running, opens it in window mode. However if it is running and is in tray then you cannot open it in window mode from neither taskbar nor activities, you have to navigate tray icon menu. And so the only thing you get by typing "teams-for-linux" in terminal is response "App already running", when it should just bring it back to window mode from tray.

I use Super + N hotkey to open taskbar items but with t4l it doesn't werk. Seeing how t4l doubles as instant messenger, inability to open it in a window from tray is damaging.

**Comment by IsmaelMartinez** [comment]
I think this is related to you libnotifications of another library issues.
I can suggest to use the config option of "closeAppOnCross" to not minimize on clicking close. Not ideal but at least you will not get stuck on that situation. 
https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config
Sorry, didn't realise of this issue report until now.

**Comment by IsmaelMartinez** [comment]
closing due inactivity. please ping back with more information if you require any extra help.
