### ISSUE TITLE
I made a package for the Raspberry PI 4 but have one small issue

### ISSUE THREAD

**Issue by franz-strebel** [IsmaelMartinez/teams-for-linux#359]
Thanks for the great work on this unofficial Teams client.  npm start works well on my Pi 4 from source so I wanted to package it so other Pi owners can install it easily.  I got the package done but when I install from it, I do not have Screen sharing, which I get when running from source.

Would be great if you can point me in the right direction.  Thank you.

**Comment by IsmaelMartinez** [comment]
yeah, feel free to share. 

I now use github actions to do builds so maybe that is a way to integrate/test it?

**Comment by franz-strebel** [comment]
OK, I got it done and packaged for arm64 as I am running Ubuntu 20.04 on my Pi 4.  How do I send you the packages for posting?

**Comment by IsmaelMartinez** [comment]
I @franz-strebel , I had a play with github actions and electron-builder and maybe this also work... can you check the following version and see if the raspberry one works? https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.5

**Comment by franz-strebel** [comment]
That's great, thanks @IsmaelMartinez !  I switched back to Raspbian as I had some programs unavailable for arm64.  I just tested the deb package and AppImage you built for armv7l and I have the same issue, they work but I do not have Screen sharing.
However, when I run npm start from your source, I have that and it works very well.  Any idea why there is this difference?

**Comment by IsmaelMartinez** [comment]
There should not be a difference. My only question is, does it take a long time to start up? We enable the "screen sharing" after 4 seconds (I think). If it takes a wee bit longer it might get overwritten by MS code.
Let me know if that is the case and we can allow to tweak that number in the config.

**Comment by franz-strebel** [comment]
From the package and AppImage, I don't have the icon at all for screen sharing.  With npm start, I see the icon greyed out first and then it becomes active.

**Comment by franz-strebel** [comment]
Tried running with webDebug and I do see this at startup if it helps:

![Screenshot_2020-05-26_13-06-58](https://user-images.githubusercontent.com/13552444/82893852-f7654d00-9f51-11ea-895f-064d056de23c.png)

**Comment by IsmaelMartinez** [comment]
can you try running the packaged version without the spellchecker? 

```
teams-for-linux --rightClickWithSpellcheck=false
```

it smells like the spellchecker is not being compiled/packaged properly... (needs pre-compilation) https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/index.js#L12

Just a guess..

**Comment by franz-strebel** [comment]
Yes, that does the trick.  I gave it a go by putting the spellchecker from the pi to my other machine for the build and disabling npmRebuild but didn't have much luck. Thanks again.

**Comment by IsmaelMartinez** [comment]
well, not the end of the world I guess... but there is no right click then!

**Comment by IsmaelMartinez** [comment]
version 1.0.5 is now released
