### ISSUE TITLE
Version 0.1.11 crashes on HTTP basic auth login

### ISSUE THREAD

**Issue by vossim** [IsmaelMartinez/teams-for-linux#36]
I've just tried the 0.1.11 version, and wasn't able to login. The application kept starting and crashing, starting, crashing, and so on.

I then removed `.config/teams-for-linux`, after this, the application started. After filling in my username, it just crashed again.

This is probably related to the login method our AD uses, in a normal browser an HTTP basic auth is used, so the issue could be related to this?

**Comment by IsmaelMartinez** [comment]
Hi @vossim, could you try 0.1.9? There was quite a lot of moving code around at 0.1.11 so I might have broke something... Ignore version 0.1.10, it was a half release.

The app restarts if you don't put the right username/password so we don't persist the username and password login screen. Try with the full email as username.

**Comment by vossim** [comment]
Hi @IsmaelMartinez, version 0.1.9 worked like a charm (was running it before I upgraded today)

**Comment by IsmaelMartinez** [comment]
I will see if I can have a look at it Friday, otherwise it might need to wait after the drinking and eating days are over (in my case mid January). Apologies about that. Feel free to have a look at the code and try to fix it if you have the time. It's probably the login event callback not been in the context (this, that, self JavaScript stuff)

**Comment by vossim** [comment]
No worries, I I'll just revert back to 0.1.9 in the meantime. I might have some spare time on Thursday or Friday, haven't looked into electron yet and my JavaScript-fu is not up to snuff, but if it's something simple I might find it.

**Comment by IsmaelMartinez** [comment]
I think I found what it is... I might not be able to thoroughly test it test it until the end of the week or early January (due holidays). The solution should be in branch 0.1.12 but I haven't been able to fully test it.

**Comment by vossim** [comment]
I was able to resolve it by setting the initial value of this parameter to `true`: https://github.com/IsmaelMartinez/teams-for-linux/blob/v0.1.11/app/index.js#L16. Haven't gotten around to creating a PR though.

**Comment by IsmaelMartinez** [comment]
yep, I did move the code around a bit in the 0.1.12. I will try to release it at some point today.

**Comment by IsmaelMartinez** [comment]
merged into master and release 0.1.12 created.
