### ISSUE TITLE
Github app login does not work

### ISSUE THREAD

**Issue by alemuntoni** [IsmaelMartinez/teams-for-linux#365]
**Describe the bug**
When I try to login to the github app for microsoft teams using teams-for-linux, a browser tab opens and closes (with link https://msteams-ghub.com/close?source=undefined), and nothing else happens. Tried both default browsers chrome and firefox.
Works on microsoft temas from the browser.

**To Reproduce**
1. Go to the github app inside temas and click "Log in with GitHub"

**Screenshots**
teams-for-linux:
![image](https://user-images.githubusercontent.com/6656168/83322684-07cf3d80-a25a-11ea-8bb2-30200e49e0ee.png)
same page on teams from google chrome:
![image](https://user-images.githubusercontent.com/6656168/83322712-34835500-a25a-11ea-81af-10891e3a726f.png)

**Desktop:**
 - OS: Ubuntu 20.04
 - Installation package: tried deb and snap
 - Version 1.0.5

**Comment by IsmaelMartinez** [comment]
For this integrations you need to use ctrl+click to log in. It's because
the way electron works.

**Comment by alemuntoni** [comment]
Oh ok, it works!!
Thank you for the quick reply!
