### ISSUE TITLE
No notification sounds

### ISSUE THREAD

**Issue by kujaw** [IsmaelMartinez/teams-for-linux#366]
I don't get any notification sound when somebody sends me a message.

 - OS: Xubuntu 18.04
 - Installation package - snap
 - Version 1.0.0

**Comment by IsmaelMartinez** [comment]
Hi @kujaw , 

This is a MS issue https://techcommunity.microsoft.com/t5/microsoft-teams/audio-notifications/m-p/386653 

This was reported a while ago https://github.com/IsmaelMartinez/teams-for-linux/issues/340 so I will not hold my breath but MS needs to fix it on their end.

Thanks for using the software.
