### ISSUE TITLE
Clicked link does not do anything

### ISSUE THREAD

**Issue by tkalfaoglu** [IsmaelMartinez/teams-for-linux#370]
I recently received a link to join a group..
https://teams.microsoft.com/dl/launcher/launcher.html?url=%2f_%23%2fl%2fmeetup-join%2f19%3a55dce7a604224a9989c094d3c46064b0%40thread.tacv2%2f1591959203339%3fcontext%3d%257B%2522Tid%2522%253A%25220f12a35c-45f6-462f-bfa1-0992ccd85ff7%2522%252C%2522Oid%2522%253A%2522fdeb8350-db06-46b0-b7f0-e7242e348229%2522%257D%26anon%3dtrue&type=meetup-join&deeplinkId=4f534d8e-466a-4052-ae42-107b16fe7ba9&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true#

however clicking this link launches the app, but does not seem to do anything else..
I am not joined nor do I get a notice that a such group does not exist.

The console shows:
$ teams-for-linux 
configPath = /home/turgut/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
processArgs [ '/opt/teams-for-linux/teams-for-linux' ]
did-finish-load
did-finish-load
[2205918:0615/130009.910532:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
second-instance started
processArgs [ '/opt/teams-for-linux/teams-for-linux',
  'msteams:/l/meetup-join/19:55dce7a604224a9989c094d3c46064b0@thread.tacv2/1591959203339?context=%7B%22Tid%22%3A%220f12a35c-45f6-462f-bfa1-0992ccd85ff7%22%2C%22Oid%22%3A%22fdeb8350-db06-46b0-b7f0-e7242e348229%22%7D&anon=true&deeplinkId=4fd437fe-bf0b-4522-37bc-47fb75955d54&launchAgent=join_launcher&type=meetup-join&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true&fqdn=teams.microsoft.com' ]
meetup-join argument received with msteams protocol
second-instance started
processArgs [ '/opt/teams-for-linux/teams-for-linux',
  'msteams:/l/meetup-join/19:55dce7a604224a9989c094d3c46064b0@thread.tacv2/1591959203339?context=%7B%22Tid%22%3A%220f12a35c-45f6-462f-bfa1-0992ccd85ff7%22%2C%22Oid%22%3A%22fdeb8350-db06-46b0-b7f0-e7242e348229%22%7D&anon=true&deeplinkId=4fd437fe-bf0b-4522-37bc-47fb75955d54&launchAgent=join_launcher&type=meetup-join&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true&fqdn=teams.microsoft.com' ]
meetup-join argument received with msteams protocol

(tried it twice)

**Comment by IsmaelMartinez** [comment]
Hi, can you fill the bug report? it does ask for a few questions that can
help identify the issue.

**Comment by IsmaelMartinez** [comment]
closing due inactivity. Please ping back with more information and I will be happy to help

**Comment by lciti** [comment]
I had a similar issue. What finally worked for me was launching the client with `teams-for-linux --url "https://teams.microsoft.com/dl/launcher/launcher.html?url=%2f_%23%2fl%2fmeetup-join%2f19%3a55dce7a6042..."`.
