### ISSUE TITLE
App crashes when file dialogue should pop up

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#372]
**Describe the bug**
Selecting a file to upload or a directory to download files from teams, (i.e. when opening a file dialogue) teams crashes immediately.

**To Reproduce**
1. Go to Files
2. Click on Download file
--> Crash
1. Choose upload in Chat, team or call
2. Select from local (not onedrive)
--> Crash

**Expected behavior**
A file dialogue should pop up and I can select the source file for an upload or the dir as destination for a download.

**Desktop (please complete the following information):**
 - OS: Linux, KDE 4.14.38, Plasma Desktop 5
 - Installation package snap
teams-for-linux    1.0.5                       105   latest/stable  alarconj      -

**Comment by IsmaelMartinez** [comment]
Hi @elhennig ,

Apologies for taking that long to reply. This message got lost from my list.

I think this could be a snap issue/configuration. Could you:
* Check if installing the deb package works

If so, can you confirm if you home user in NOT under /home/username ? 

If that is the case you probably are having problems with other snap packages.

Just run:
```
sudo dpkg-reconfigure apparmor
```
and put your path in it.

Hope helps!

**Comment by elhennig** [comment]
I am on a rpm based system (opensuse leap 15.2). _What package do you mean to install? the teams-for-linux one?_

I installed the 1.0.5 rpm now, and there the file dialogue works fine. Thanks for pointing to the solution not to use snap! Updating is not so easy this way, but that is far less annoying than the crash when uploading files from the local machine ;-)

**Comment by elhennig** [comment]
I needed to revert to the snap version since the audio quality was horrible for the other attendees of meetings. This was happening with the rpm based installation but it is much better for the snap version. Anyway the app crashes again when opening the file dialogue. Any idea how to solve this in snap?

**Comment by IsmaelMartinez** [comment]
have you tried `sudo dpkg-reconfigure apparmour` ? |

More info in:
https://github.com/IsmaelMartinez/teams-for-linux/issues/187

**Comment by elhennig** [comment]
As I wrote I am on an rpm based system (opensuse leap 15.2) and there is no such command as dpkg-reconfigure. Anyway I tried reinstalling all apparmor related packages with zypper in -f <packagename>
No success, unfortinately...

**Comment by IsmaelMartinez** [comment]
sorry to hear about that. It does smell like a snap configuration issue, not just a package issue. 

maybe try AppImage? sorry for not been able to help more from here.

**Comment by elhennig** [comment]
That's ok I just did not find any solution for snap, so I asked here.
