### ISSUE TITLE
Google Drive Integration Doesn't Work

### ISSUE THREAD

**Issue by lolrepeatlol** [IsmaelMartinez/teams-for-linux#376]
**Describe the bug**
When I go to the Files section and select Connect to Google Drive, it'll open up a new tab in Firefox for accounts.google.com to authorize, then it closes really quickly. Afterwards, the integration just loads forever and doesn't do anything. Trying to tell it to disconnect and reconnect again just opens up a Firefox tab super quickly, and then closes it soon after. I assume this means it's just going through accounts.google.com and since I already authorized it just closes. Anyway, the same issue occurs. It just spins, and I can't access my files. The same thing happens if I set my default browser to Chrome.

In the normal Teams app, it works fine. Opening teams.microsoft.com in Firefox also works just fine. 

**To Reproduce**
1. Go to Files
2. Click on "Add cloud storage"
3. Sign in to Google in the browser window
4. See how it endlessly loads

**Expected behavior**
I expected to see my Google Drive files.

**Screenshots**
https://imgur.com/a/8IzFPnc

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04
 - Installation package: deb, flatpak
 - Version: 1.0.5

**Comment by IsmaelMartinez** [comment]
HI, 

Can you try doing a Ctrl+click instead of just click when clicking in the "google drive" option?

Thanks

**Comment by lolrepeatlol** [comment]
Thanks for the tip. Unfortunately, the same thing happens. I even tried logging out of Google Drive in Teams and ctrl clicking the connect button but that didn't work either.

**Comment by lolrepeatlol** [comment]
I switched to Windows (since Teams is so much better on it, unfortunately). I appreciate any help though. Closing

**Comment by IsmaelMartinez** [comment]
sad times. I had to switch to mac not because of teams, but sophos antivirus... so makes it much more difficult to support this when I am not even using it :(

**Comment by lolrepeatlol** [comment]
> sad times. I had to switch to mac not because of teams, but sophos antivirus... so makes it much more difficult to support this when I am not even using it :(

the year of the linux desktop needs to happen faster :(
