### ISSUE TITLE
Can't Share Some Windows and Dual Monitor problem

### ISSUE THREAD

**Issue by erenoglu** [IsmaelMartinez/teams-for-linux#381]
1) When in Teams meetings, I can't share application windows from "WPS Office for Linux" office suite.  It is not presented in the window list. I'm not sure why. Those windows are invisible to Teams-For-Linux. (similar when I'm using Google Chrome in Teams Web)
2) Also when I try to share my whole screen, the share window covers both monitors,  I can't choose monitor by monitor. So I can't share the whole screen neither.

1. Start a meeting and click share
2. Click share desktop/application
3. Check the window list that comes in front, see that sharing full screen shares both monitors in compressed format, and WPS Office application windows are not visible at all. 

**Expected behavior**
See monitors separately to share. See also WPS office windows in window list.

**Desktop (please complete the following information):**
Arch Linux, up to date with latest stable KDE, running on Xorg.
teams-for-linux  1.0.5

**Comment by IsmaelMartinez** [comment]
Hi,

1.- First time I hear about that. If you have the same problem with the Chrome in Teams Web, then we probably can't do much to sort it.
2.- This one is a know annoyance of electron/chrome. I think if we upgrade to the latest version there will be a way to sort it (easier said than done). In electron, the windows selection picker is not implemented, so you have to implement it yourself and selecting a single screen isn't as easy at it sounds.

**Comment by erenoglu** [comment]
1. Probably, I may file a bug report to the SW vendor, I dont know why those windows dont show up. 
2. OK, noted. Hope you'll have time for it.
thanks a lot.

**Comment by IsmaelMartinez** [comment]
sorry, there is no plan to update the version of electron. People are welcome to submit PRs but I will close this as there haven't been many contributions lately.
