### ISSUE TITLE
Cant start the app

### ISSUE THREAD

**Issue by maigke** [IsmaelMartinez/teams-for-linux#382]
**Describe the bug**
hi, the problem is i can't loggin in Teams, an invitation to download the appears.

**To Reproduce**
i used the stable an edge version the problem start today
open a terminal
$teams-for-linux

**Expected behavior**
I 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/12049771/92025729-9524a100-ed25-11ea-910c-cca5badc116a.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux Mikah 20.1 
 - Installation package: snap
 - Version 1.0.5 and 1.0.6

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi, just click "utilize la aplicacion web en su lugar" and that should do
the trick.

You should not see that screen again. Ms keeps changing the button ID so
it's a bit of an annoying issue.

**Comment by culebrasolida** [comment]
Hi, I'm using the AUR package and I'm having the exact same issue, once I click on "utilize la aplicacion web en su lugar" it redirects me to a web browser and asks me to log in, but then it won't let me get into my meeting.

**Comment by IsmaelMartinez** [comment]
sorry @culebrasolida , that sounds like a different issue. 

if you want to open a meeting in the app you need to have the handlers associated. I am not sure how that works on AUR package but you can put the meeting url as an argument in the client and it might do the trick.

again, a different issue. Dig the close issues as there are tons as this ones.
