### ISSUE TITLE
Screen Sharing and Camera don't work together

### ISSUE THREAD

**Issue by Georges1991** [IsmaelMartinez/teams-for-linux#383]
When I share the screen, the video-camera automatically gets disabled and I can't get it on again.
I'm required to have the camera on while I share the screen during an exam.
Is there a workaround to solve this problem?
Thanks a lot.

Ubuntu 18.04.4 LTS

**Comment by IsmaelMartinez** [comment]
This is a MS limitation. Please raise this with MS in their teams user voice at https://microsoftteams.uservoice.com/

**Comment by Georges1991** [comment]
They don't respond, as usual. So there isn't a known solution to this problem?

**Comment by IsmaelMartinez** [comment]
no sorry, that is how it works in the browser. check their client. it might be different but I think it does the same
