### ISSUE TITLE
When embedding an azure website through tabs in teams it doesn't show up

### ISSUE THREAD

**Issue by celvin** [IsmaelMartinez/teams-for-linux#384]
**Describe the bug**
When embedding an azure website through tabs in teams it doesn't show up

**To Reproduce**
1. Go to a team
2. Click on "Add a Tab"
3. Chose "Website"
4. Paste an azure scrum board link or any link that redirects 

**Expected behavior**
When you open that tab you will see "If your site isn't loading correctly, click here" and the website is never loaded but if you open it outside of teams it works perfectly.

**Screenshots**
![image](https://user-images.githubusercontent.com/182253/92414651-69812c80-f112-11ea-8b33-7e2367293cec.png)

**Desktop (please complete the following information):**
 - Ubuntu Linux
 - Version 20

**Additional context**
The same site in official Microsoft Teams for Linux works pretty well, but I need to use your teams edition as I have accounts in different subscriptions and want to have both accounts open at the same time.

**Comment by IsmaelMartinez** [comment]
Apologies I forgot about this. I thought I had replied. 

I had the same issue in the official client so it is not relevant to this client but to MS (I believe). I think it might be related to authentication. If you paste a public website will work fine, but if you need authentication it just gets confused and mess up. 

I will see if you get the same situation in a browser and, if so, report it in the MS user voice.

By the way, if you click in the (click here) that is a link and it will try to load the frame again. That sometimes works in my case but it might not be good enough for you.

Apologies for the delay

**Comment by celvin** [comment]
Thanks for your reply, and nope in the official client works well, that is
happening only in teams-for-linux, I thought may be related to some policy
in electron and made a small app just to embed the ms website and it worked
well there too.

**Comment by IsmaelMartinez** [comment]
Strange. is this from a VPN? Maybe you need to route all your traffic via the VPN. 

I have reproduce the same situation with some internal server (Jenkins pipelines). 

I hope helps.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Please provide further info and if you require this to be re-open. (Just trying to keep things tidy)
