### ISSUE TITLE
Spell checking only in English

### ISSUE THREAD

**Issue by vslinuxdotnet** [IsmaelMartinez/teams-for-linux#385]
Hello,
when writing messages, the spell checking only suggests English words.
Is possible to change that ?
Thank you

**Comment by vslinuxdotnet** [comment]
Get Working doing this:
1- install hunspell and lang dictionary
2- Then specifying command line to run it
 ex: LANG=pt_PT.UTF-8 LANGUAGE=pt_PT teams-for-linux

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#spellchecker-not-working explains that process. Feel free to create a wee PR to expand that documentation if you got time. PRs are more than welcomed :)

**Comment by IsmaelMartinez** [comment]
Hi @humbertaco , it is possible we don't need that library to support spellchecker, but haven't had the time to check it. 

Maybe we can add it on a feature flag/config option so we can validate this one works and doesn't break the rightclick. Put a PR if you can and I am happy to help around. Thanks for pinging ! (no worries it was closed)
