### ISSUE TITLE
Whitescreen if you add Automatic Proxy Setup in Gnome Network Settings

### ISSUE THREAD

**Issue by Cellebyte** [IsmaelMartinez/teams-for-linux#39]
* Interesting behaviour.
* If you add a proxy manually everything works fine ^^

**Comment by IsmaelMartinez** [comment]
Hello, have you tried doing refresh? (Right click on the tray icon). 

I have seen the white screen in initial installation sometimes.

**Comment by Cellebyte** [comment]
> Hello, have you tried doing refresh? (Right click on the tray icon).
> I have seen the white screen in initial installation sometimes.

After testing all of your solutions you mentionend in the other issues this was the fix. The pac script was not interpreted and therefore it was not working and a whitescreen occurs.

**Comment by IsmaelMartinez** [comment]
I have added a bit of logic to improve the online/offline check for the initial load. This, hopefully, will remove most of the white screen cases for initial load. 

Closing.
