### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by jpiedra87** [IsmaelMartinez/teams-for-linux#391]
Dear Ismael,

thanks for your snap solution for Microsoft Teams.
I have tried it with my raspi 4b and got my usb camera running right away.
But I have problems with the audio. 
I am using a Plantronics usb headset which actually works with my raspi.

After teams-for-linux is started I get a some error messages in the command-line:

ALSA lib conf.c:3916:{snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:{snd_pcm_open_noupdate) Unknown PCM default
[3028:1019/162208.12363:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.

I have installed the alsa snap module but this has not changed anything.
The raspi is running on  2020-08-20-raspios-buster-armhf.

As mentioned above the usb camera works fine.
It has an inbuilt microphone and speaker but in the system settings they are not used.

Any idea what the cause for this could be?

Thanks and best regards, John

**Comment by IsmaelMartinez** [comment]
Hi @jpiedra87 ,

Can you try https://github.com/IsmaelMartinez/teams-for-linux/issues/117#issuecomment-487840040 and provide what version of snap are you using?

Try otherwise the build version in the releases folder. It might work better. 

Hope helps

**Comment by jpiedra87** [comment]
Hi Ismael,

thanks for your quick reply! The package for pulseaudio actually solved the issue.
Works just fine!

BR, Joh
