### ISSUE TITLE
Obsolete "teams-for-linux" Flatpak for official client?

### ISSUE THREAD

**Issue by hadess** [IsmaelMartinez/teams-for-linux#392]
It would be useful to find a way to automatically migrate folks from the unofficial, and now obsolete, client to the official one (even if unofficially packaged). Not certain whether Flathub/Flatpak has a mechanism for that.

**Comment by hadess** [comment]
There's a few examples using the `eol-rebase` `flathub.json` key:
https://github.com/search?q=org%3Aflathub+eol-rebase&type=commits

**Comment by IsmaelMartinez** [comment]
I don't maintain the flatpak version so I suggest you report this into
their repo. I personally will prefer not to automatically migrate as not
everyone will want to automatically move. It's not two products from the
same company and one is open source while the other is close source.

**Comment by IsmaelMartinez** [comment]
By the way, the project still alive, open for PRs etc but I can dedicate my
time to add improvements. Just to manage them.

**Comment by hadess** [comment]
Moved to https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/issues/14

Thanks.
