### ISSUE TITLE
Cannot switch to a different org view

### ISSUE THREAD

**Issue by FoamyGuy** [IsmaelMartinez/teams-for-linux#394]
**Describe the bug**
My Teams account is a member of my main organization. But I have recently been added as a guest to a different organization. 

There is a drop down in the top right near my profile icon that I can click to get a list of all my orgs (just 2 atm) and it seems like I should be able to click on the other org (that I am a guest in) to change my view over that org and be able to see all of my chats and other activity. But when I click on the org it opens a new tab in my browser (not in the Teams local application wrapper). The tab in the browser does correctly show the context for the org that I clicked. But my local application window is still stuck in my main org, it did not change contexts to the one I clicked.

**To Reproduce**
1. Load Teams with an account that has access to 2 or more organizations
2. Click on the dropdown arrow next to the profile icon
3. Click on any org that does not have the check mark by it
4. new Tab opens in browser, but local app remains in the same org context

**Expected behavior**
Local application should switch to the context of the org that I clicked on, instead of opening a new tab in the browser. 

**Screenshots**
This is the dropdown I clicked: 
![image](https://user-images.githubusercontent.com/2406189/99694124-b148fc00-2a51-11eb-953b-0fa072d0c8b9.png)

**Desktop (please complete the following information):**
 - OS: Pop! OS
 - Installation package: snap
 - Version 1.0.0

**Additional context**
I know that microsoft has a more official teams app for linux now, but the call / video quality when I am in meetings is way worse in the offical app, whereas it's just fine in this one so I have continued to use this one.

**Comment by IsmaelMartinez** [comment]
Hi, can you try doing the click with the "ctrl" button been also been
press? Hope that helps.

**Comment by FoamyGuy** [comment]
Does not seem to make any difference. With ctrl button pressed down it will sill open up a tab in the browser instead of local app.

Thank you for making this and trying to help out though. I really appreciate it.

**Comment by IsmaelMartinez** [comment]
I am surprise that part doesn't work but the user details work (as they seem to work the same way).

I suspect is something related to this lines:

https://github.com/IsmaelMartinez/teams-for-linux/blob/7649cacecf38147cc295bace3e8b1f39b0eb0864/app/mainAppWindow/index.js#L123

Unfortunately I can't test anything as I got a different OS now at work. But I will encourage you to play around that area.

If you run it from the command line you will get further tips (logs) on what is going on.

just run `teams-for-linux` but make sure your client is already closed.

**Comment by IsmaelMartinez** [comment]
actually, I think it could be related to snap. Can you try using a deb or rpm package and see if you still got the issue? I can switch from org fine in my local environment. Ta

**Comment by IsmaelMartinez** [comment]
also, use snap version 1.0.5 if possible, there were quite a few changes in that area between version 1.0.0 and 1.0.5 (or 1.0.6)

**Comment by FoamyGuy** [comment]
It seems whatever was the issue in my case has gotten resolved. Changing team contexts is now working successfully for me. I didn't make any changes to my installation yet but it is working anyway now.
