### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by JR1994** [IsmaelMartinez/teams-for-linux#395]
I would like to see the remote control feature enabled on the Linux client. I collaborate with team members that run the Windows version. When we do a screen share there are time when we use the remote control feature to troubleshoot issues. My office PC is running windows, but at home I am running Manjaro. I would like that feature there as well if possible.

**Comment by grealish** [comment]
This isn't possible yet, even in the native Linux, OSX builds, and the web-client. Until it's possible on the web-based client then, it can be possible here to implement 

> . If you're using Linux, giving and taking control of shared content isn't available at this time.
src: https://support.microsoft.com/en-us/office/share-content-in-a-meeting-in-teams-fcc2bf59-aecd-4481-8f99-ce55dd836ce8#ID0EABAAA=Desktop 

Please post a requested on User Voice, Search first for a request very similar and link back here to it, That way others can upvote, Please don't create a new request, there are allot of requests for "remote control", e.g
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33873364-remote-control-uac
e.g 
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/39624940-remote-control-on-linux
This is a more greater scope requests, so features are release in-line with other clients
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40324324-keep-the-linux-client-up-to-date-with-the-latest-f?page=1&per_page=20

**Comment by IsmaelMartinez** [comment]
Closing. As @grealish, this request is probably best handle on the MS  uservoice
