### ISSUE TITLE
Please update - this snap is hopelessly outdated.

### ISSUE THREAD

**Issue by AndKe** [IsmaelMartinez/teams-for-linux#396]
Of course, Micro$oft will only give minimum functionality to Linux users, removing video backgrounds etc.
The Evil must go on.. 
but they have removed a ton of bugs and released new versions since this one..

**Comment by IsmaelMartinez** [comment]
There isn't much to update, to be honest, this version should get whatever the web version gets.

I am open for PRs so if there is any extra functionality, feel free to fire a PR. Happy to help with the process. 

Closing the ticket.
