### ISSUE TITLE
Electron 5.0.x?

### ISSUE THREAD

**Issue by whitpa** [IsmaelMartinez/teams-for-linux#397]
Hi Ismael,

We at ThinLinX Pty Ltd (an embedded Linux thin client startup specialising in Raspberry Pi) are very appreciative of the work you've done, which remains the only practical way to get MS Teams working on most of our platforms (which include i386 and armhf).

We have an - admittedly obscure - problem with 1.0.5 in that it pulls in a binary build of electron 4.2.8 that will not work with old Debian/Raspbian releases (specifically Debian 8, Jessie) that we use for our "long term stable" release, because its GLibC and GLib dependencies are much too high.  At the time, Electron maintainers were publicly rather unsympathetic about this issue (https://github.com/electron/electron/issues/16205), but they appear to have nonetheless corrected it in Electron 5.0.x armv7l builds.  Teams-for-Linux 1.0.5 doesn't appear to be compatible with Electron 5.0.x, however.  We tried Electron 5.0.13 and got the following:

Uncaught Exception:
Error: onBeforeRequest parameter 'filter' must have property 'urls'.
    at App.onAppReady (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/index.js:30:40)

Is there any chance you could update Teams-For-Linux to use a higher Electron baseline?

P.S. I admit to being a Yarn/NPM/Javascript-generally dunce.  Including some build instructions with your source code would be very helpful for (older) people like me, who have no clue what to do with a "package.json" and no Makefile!  I think I figured most of it out eventually, but it was a struggle.

- Paul Whittaker

**Comment by IsmaelMartinez** [comment]
Hi Paul,

Unfortunately there are quite a few issues on moving up the electron version. I tried a couple of times but I never manage to get the desktop sharing working.

https://github.com/IsmaelMartinez/teams-for-linux/issues/156

There is a branch (a wee bit behind of master but nothing too serious) where I did the trial. If you don't need screensharing (and I think the right click menu is also gone), you should be able to try it.

The HOWTO getting working is documented in the https://github.com/IsmaelMartinez/teams-for-linux/blob/feature-156-move-electron-6/CONTRIBUTING.md page. It can definitively be better described. 

Maybe another option is to use snap or Flathub but that depends how much "extra" stuff you want to have in your raspi. I will give the flathub a try (snap always add far too much stuff).

Hope helps, Ping me if you get stuck and/or if you think or another options.

**Comment by whitpa** [comment]
Thanks Ismael, I'll give that branch a try.  It's aimed at Electron 6 rather than 5, but I just checked the Electron 6 armv7l binaries, and they seem to have the lower glibc level too - it seems only Electron 4.x had that problem.

The alternative would be to recompile Electron 4.2.8 myself as per instructions at https://github.com/electron/electron/blob/master/docs/development/build-instructions-linux.md, but that sounds like an exercise in masochism best left to people far beyond my near-nonexistent NPM/Yarn/JavaScript skill level.  Going the other direction and using Electron 3.0.13 would also be an option, but I already tried that, and with the current Develop branch code, authentication fails for non-obvious reasons.

If you could include something like what's in the CONTRIBUTING.md file mentioned above in a README.md in the release tarball, or provide a link to it at the bottom of the https://github.com/IsmaelMartinez/teams-for-linux/ landing page, that would be helpful for neophytes such as myself.  At present that information is difficult to locate.

P.S. Recent versions of electron-builder are fussy about the order of command line options and want the arch string to appear before "-l", which breaks "yarn/npm run dist:linux:deb".  Editing package.json to use commands like "electron-builder --x64 --armv7l --arm64 -l deb" instead of "electron-builder -l --x64 --armv7l --arm64 deb" fixes that.

**Comment by IsmaelMartinez** [comment]
Hi @whitpa, I will close this due inactivity. Do ping me back with whatever info and/or tests you manage to do, and I will reopen. Trying to keep things tidy. Thanks!
