### ISSUE TITLE
white window on base Debian (live Raizo) distribution

### ISSUE THREAD

**Issue by Raizo62** [IsmaelMartinez/teams-for-linux#4]
Hi

I need to use teams on Debian ([Live Raizo Distribution](https://sourceforge.net/projects/live-raizo/))

On the same PC, with teams 0.1.6 : 
* Debian is the true OS : teams shows white window after to ask to stay connected.
* Win7 is the true OS. Debian is started in VirtualBox with bridge mode : teams works.

I have the same with access to teams with chromium (after disable "block third-party cookie")

I don't understand :-(

**Comment by IsmaelMartinez** [comment]
The other case, might be you are sitting on the back of a proxy server. 

I assume you are pretty expert on networking as for the distribution. I am not an expert so the following might not be even possible.

Maybe windows 7, by bridging the connection, is hiding the need to configure the proxy in Debian in the virtual box (as is already configured), but when running on its how, its required. That might just be a need so something to implement in electron.

Just a thought, let me know how you get on with the investigation. Thanks

**Comment by Raizo62** [comment]
I have tested to access to Teams with chromium.
With "Developer Tools", i see these messages :

![image](https://user-images.githubusercontent.com/7449584/47516382-a37e1800-d885-11e8-89a3-e310e87da515.png)

is it for all ? or is it perhaps the cause ?

**Comment by IsmaelMartinez** [comment]
Nothing in there of interest. Can you check the network tab? Click the checkbox that says something like "preserve log". Then clean the logs and refresh the screen.

**Comment by Raizo62** [comment]
- "refreshing the page" and "teams --userAgent edge" change nothing :-(
- with network of "developer tools" of chromium, it loops with : 
  - go 
  - prelogin
  - authorize_response

![image](https://user-images.githubusercontent.com/7449584/47613919-c08a3500-da97-11e8-85f5-1d05ad2c5fd1.png)

**Comment by IsmaelMartinez** [comment]
no idea why this could be happening. 

just to try to clarify and see if we can get to the bottom of this issue:

* are you using a business account or a personal account? 
* can you provide a detail of how your network is configured? are you sitting in the back of a proxy?

Lets see if we find what is going on with this. Thanks!

**Comment by IsmaelMartinez** [comment]
Hi @Raizo62 

It might be worth trying version [0.1.7](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.1.7) and the following:

* remove the previous configuration of teams by running `rm -rf ~/.config/teams-for-linux`
* uninstall any previous version of teams
* install the version [0.1.7](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.1.7)
* start teams with the persistence turn on by running `teams --partition persist:teams-linux`

Let me know how you get on and, if it doesn't work, please provide the information for my previous questions.

Thanks!

**Comment by Raizo62** [comment]
It is strange that Teams works if LiveRaizo is started in VirtualBox

- I am using business account (i am teacher).
- At home, i have not proxy (normally).

I have tested 0.1.7 without success
The title stays "Checking your credentials"

Perhaps could you download LiveRaizo and install it on USB Key to test ?
To install Teams on LiveRaizo, i do : 
```
sudo apt update
sudo apt install gconf2 gconf-service libnotify4 libappindicator1 
wget https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v0.1.7/teams-for-linux_0.1.7_amd64.deb
sudo dpkg -i teams-for-linux_0.1.7_amd64.deb

```

**Comment by IsmaelMartinez** [comment]
Hi @Raizo62 ,

I am afraid I don't have much time to do a full installation at this moment in time.

I will add a couple more parameters in version 0.1.8 that might help fix this issue. It might be related to ntlm but I am not sure why it will work in the virtual box. 

I will keep you posted.

**Comment by Raizo62** [comment]
Hi

LiveRaizo is not a distribution to install. It's do to use immediately (after to have to install the iso on an USB key, and to boot on it). And LiveRaizo works in memory to not modify your own disks.

But I understand.
I'm waiting the release 0.1.8

**Comment by IsmaelMartinez** [comment]
Hi @Raizo62 

Could you try installing version [0.1.8](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.1.8) and run it with the following options? (one at a time, stop if any of them work)

* `teams --authServerWhitelist false`
* `teams --partition persist:raizo`
* `teams --ntlmV2enabled false` 

if none of those works, I will recommend trying installing another similar electron program (like slack) and see if you got the same issue.

Hope helps,

**Comment by Raizo62** [comment]
Hi

Sorry, i have tested each options on 0.1.8 and 0.1.9

The screen stays white with the title "Checking your credentials"

**Comment by IsmaelMartinez** [comment]
can you try using a non work account? You can setup a hotmail account and activate teams for it.

It takes a bit of time but it should give us more of an indication about where to look at.

By the way, I tried running raizo in Virtual Box but couldn't get any network connectivity (no matter if bridge or Nat). raizo seem not to like that I was in a wifi.

**Comment by Raizo62** [comment]
> can you try using a non work account? You can setup a hotmail account and activate teams for it.
> 
> It takes a bit of time but it should give us more of an indication about where to look at.

Ok, i am going to try

> By the way, I tried running raizo in Virtual Box but couldn't get any network connectivity (no matter if bridge or Nat). raizo seem not to like that I was in a wifi.

Normally, the network must work with wifi if you use NAT in VirtualBox
But don't forget to activate the ethernet card of LiveRaizo : 
`!1`          
This command must call the command : "sudo ifup enp0s0"
But I can't know what is your "enp0s0" : you can see it with the command : 
`!3`

**Comment by Raizo62** [comment]
> can you try using a non work account? You can setup a hotmail account and activate teams for it.

It is done. I have tested again your 3 parameters. No change :-(

**Comment by IsmaelMartinez** [comment]
Hi @Raizo62 ,

Did you try the following?

* running teams in a browser. 
* trying another client for a similar product (like slack). If this one works, means it is something todo with the client and/or Microsoft. If it doesn't, it is some network configuration.

Other than that, maybe post a question with this resume in stackoverflow. I am afraid that I don't have the time nor understand what is going wrong in here.

Thanks
