### ISSUE TITLE
Opening meeting links does not work

### ISSUE THREAD

**Issue by geez0x1** [IsmaelMartinez/teams-for-linux#402]
**Describe the bug**
Opening meeting links does not work - Teams opens, however nothing else happens.

**To Reproduce**
1. Click a meeting link.
2. See Teams open and nothing else happening.

**Expected behavior**
Teams opens and joins the call.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Snap, v1.0.6

Great work otherwise, I have to use Teams for work sometimes. It's horrible but this makes it bearable ;)

**Comment by IsmaelMartinez** [comment]
Hi, can you try using another package? Other people have reported that previously using snap. Hope helps

**Comment by mikejavier** [comment]
+1 

Desktop (please complete the following information):

OS: Ubuntu 20.10
Snap, v1.0.6 and v1.0.5

**Comment by IsmaelMartinez** [comment]
@mikejavier , have you tried with another package and check the changes mention in the comment https://github.com/IsmaelMartinez/teams-for-linux/issues/173#issuecomment-521897795 ?

**Comment by mikejavier** [comment]
Hi @IsmaelMartinez, yes I did it.

1 - I remove the configs
2 - update do edge version

and it still doesn't work

**Comment by IsmaelMartinez** [comment]
have you tried `sudo dpkg-reconfigure apparmour` ? |

More info in:
https://github.com/IsmaelMartinez/teams-for-linux/issues/187

**Comment by mikejavier** [comment]
Did you mean apparmor? I tried now and nothing

**Comment by IsmaelMartinez** [comment]
Yep, typo there in the apparmor... 

To take "snap" out the equation, can you try another package? rpm or deb.

https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.5

Thanks

**Comment by hovancik** [comment]
I'm on https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.5 DEB, Ubuntu 20.04  and opening meetings is not working for me.

**Comment by IsmaelMartinez** [comment]
Hi @hovancik , can you detail what/how do you open the links? From the command line? just  click?

Also, some long time ago there was some oddities for some people that had to have chrome as default browser for some stuff to work (and I am not sure if the links was one of those)

Alternatively, it could also be the configuration for xdg-open... if you put 
`xdg-open <link>` 

what happens? 

Hope helps

**Comment by IsmaelMartinez** [comment]
also, can you check if other solutions proposed in here do work? https://github.com/IsmaelMartinez/teams-for-linux/issues/47

**Comment by hovancik** [comment]
I open the link in browser, in Firefox. I click on the link in email, Firefox asks me what app I want to use to open the link and I choose Teams.

**Comment by IsmaelMartinez** [comment]
can you check the work around in #47 ? Try copy/paste the link in a chat, post it and then click in it... Try otherwise in a channel (either use a channel that you are only or one where it doesn't matter if people know the link to the meeting)

I think it might be xdg-open configuration on the msteams link.

Hope helps

**Comment by hovancik** [comment]
Hi, I went back to Teams in broswer as sharing screen did not work in this app for me.

**Comment by IsmaelMartinez** [comment]
I will close then this ticket. There is an open ticket for the screenshare issue. I got little to no time (and no linux) so things do take time. Glad to hear you managed to find a solution. Ta

**Comment by moschlegel** [comment]
I had this very problem just today on Fedora 33 with Teams 1.3.00.30857-1 (clicking on an emailed Teams URL would not load the meeting). I had to manually log into Teams and then click the URL

**Comment by IsmaelMartinez** [comment]
Hi @moschlegel , that teams version is for the MS Teams official one. I recommend going to their uservoice and log your problem there with them. Ta

**Comment by geez0x1** [comment]
Sorry for taking a while to get back here. I've now tried:
- `sudo dpkg-reconfigure apparmor`: No difference
- `xdg-open`: Also opens the link in FF for me, which asks me to open it in Teams, i.e. same as usual.
- Pasting the link in a chat within teams and clicking that: **Works, opens the meeting.**

**Comment by IsmaelMartinez** [comment]
hey @geez0x1, then it does smell like an xdg-open configuration issue. It can be quite temperamental. xdg-open should be opening the teams client. If it is opening firefox means it is misconfigured. Hope helps.

**Comment by geez0x1** [comment]
@IsmaelMartinez: How would `xdg-open` understand to open Teams though? The meeting links are provided to me as `https://...`, not `msteams://...`. The https link are effectively: `https://teams.microsoft.com/dl/launcher/launcher.html?url=...`, where the `url` argument is an url-encoded URL that is somehow transformed into an `msteams://` link causing Firefox to try to open Teams. I tried doing the decoding myself and putting that into `xdg-open` but without success (Teams did open, but nothing happened).

**Comment by IsmaelMartinez** [comment]
You can then try doing

`teams-for-linux <your http meeting URL here>`

It should work the same way as the copy paste. 

You are correct in that your browser will open 1st if you just click on the link, as Xdg-open will have that https associated with it. 

Hope helps

**Comment by geez0x1** [comment]
Good point; I had not tried that yet. This results in Teams opening, but opening the website in it. However, I can then click 'Continue in this browser' (as it recognizes it as a supported browser, being an Electron wrapper, I suppose), after which it continues to the right meeting. Does that information help at all?

Here is my CLI output:
```
~$ teams-for-linux https://teams.microsoft.com/l/meetup-join/...
configPath = /home/user/snap/teams-for-linux/150/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
processArgs [ '/snap/teams-for-linux/150/teams-for-linux',
  'https://teams.microsoft.com/l/meetup-join/...' ]
meetup-join argument received with https protocol
/usr/share/libdrm/amdgpu.ids: No such file or directory
did-finish-load
second-instance started
processArgs [ '/snap/teams-for-linux/150/teams-for-linux' ]
did-finish-load
[83424:0211/125206.563898:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
before-quit
window close
will-quit
quit
window closed
```

**Comment by dgmvecuador** [comment]
> Good point; I had not tried that yet. This results in Teams opening, but opening the website in it. However, I can then click 'Continue in this browser' (as it recognizes it as a supported browser, being an Electron wrapper, I suppose), after which it continues to the right meeting. Does that information help at all?
> 
> Here is my CLI output:
> 
> ```
> ~$ teams-for-linux https://teams.microsoft.com/l/meetup-join/...
> configPath = /home/user/snap/teams-for-linux/150/.config/teams-for-linux
> Failed to get the config file, using default values
> configFile = {}
> processArgs [ '/snap/teams-for-linux/150/teams-for-linux',
>   'https://teams.microsoft.com/l/meetup-join/...' ]
> meetup-join argument received with https protocol
> /usr/share/libdrm/amdgpu.ids: No such file or directory
> did-finish-load
> second-instance started
> processArgs [ '/snap/teams-for-linux/150/teams-for-linux' ]
> did-finish-load
> [83424:0211/125206.563898:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
> before-quit
> window close
> will-quit
> quit
> window closed
> ```

it only works when is not running, right??

**Comment by IsmaelMartinez** [comment]
I don't remember now but I think it should work either way. If is not, it
might be possible to change that behaviour so it works for both cases.

**Comment by Thuener** [comment]
+1

Ubuntu 20.04.2 LTS
Tried different versions and can make it work

**Comment by simonflood** [comment]
> I had this very problem just today on Fedora 33 with Teams 1.3.00.30857-1 (clicking on an emailed Teams URL would not load the meeting). I had to manually log into Teams and then click the URL

@moschlegel since you appear to be using the official Microsoft Teams client for Linux you might be affected by https://docs.microsoft.com/en-us/answers/questions/298724/open-teams-meeting-link-on-linux-doens39t-work.html?childToView=309406#

HTH.

**Comment by doak** [comment]
> I don't remember now but I think it should work either way. If is not, it might be possible to change that behaviour so it works for both cases.

Yes, it just prints `App already running` and bails out.

**Comment by IsmaelMartinez** [comment]
It can be a bit confusing, but both apps will get the event. One print the `App already running`, but the other should print `second-instance started`. The way to test this is to run them both from the console. 

Code is here:
Second app will go down this route (as doesn't got the lock)
https://github.com/IsmaelMartinez/teams-for-linux/blob/7649cacecf38147cc295bace3e8b1f39b0eb0864/app/index.js#L17
While the original app will go down the else clause down to this:
https://github.com/IsmaelMartinez/teams-for-linux/blob/7649cacecf38147cc295bace3e8b1f39b0eb0864/app/mainAppWindow/index.js#L74

Is it possible for you to confirm if the initial app does print the `second-instance started` ? Thanks

**Comment by doak** [comment]
It does. I will open a PR in a few minutes.

**Comment by doak** [comment]
Here it it is, see #422.

**Comment by doak** [comment]
@IsmaelMartinez, did I miss something?

> it only works when is not running, right??

@dgmvecuador, the mentioned #422 should fix that, i.e. it opens the call within the alrady existing instance.

**Comment by dgmvecuador** [comment]
> @IsmaelMartinez, did I miss something?
> 
> > it only works when is not running, right??
> 
> @dgmvecuador, the mentioned #422 should fix that, i.e. it opens the call within the alrady existing instance.

Sorry I havent tested it, is your PR not merged??

Also -- How I build it?? I seriously want to test

**Comment by IsmaelMartinez** [comment]
I will see if I can have a look at it today. It is a bit of a tricky part as the focus, openURL and stuff like that did work

**Comment by IsmaelMartinez** [comment]
ops, wrong button. I have reviewed the PR. Only a wee comment/change requested. Once that is ready I am happy to do a pre-release so @dgmvecuador  can test it also.

**Comment by IsmaelMartinez** [comment]
@dgmvecuador , a pre-release is in here https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.7 I think the snap is, somehow, failing to build due some fancy 🍰 
![image](https://user-images.githubusercontent.com/430992/114900526-d9276a80-9e0b-11eb-9c84-f9b5d73d56e3.png)

**Comment by dgmvecuador** [comment]
> @dgmvecuador , a pre-release is in here https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.7 I think the snap is, somehow, failing to build due some fancy 
> ![image](https://user-images.githubusercontent.com/430992/114900526-d9276a80-9e0b-11eb-9c84-f9b5d73d56e3.png)

I generated a deb and its working!!! Thank you!!!

**Comment by IsmaelMartinez** [comment]
I will leave a few more days and close / release. Some (around 400) snap people are using it (the ones on the edge channel) so waiting to see if are any complaints before releasing it to the 50K.

**Comment by IsmaelMartinez** [comment]
This was released a while back so is now solved (no-one seems to complain after the change ;))

**Comment by kudlatyamroth** [comment]
@IsmaelMartinez i think that there is still problem with this...
```
teams-for-linux "msteams://teams.microsoft.com/l/message/19:32784db490664c66aaec77c596998d02@thread.skype/1669102105778?tenantId=a78c2a2a-b9d8-453e-a193-967884425b10&groupId=105874eb-070c-4fdc-9776-829fb26c9843&parentMessageId=1669102105778&teamName=G2A-ONE&channelName=General&createdTime=1669102105778&allowXTenantAccess=false" --appLogLevels=error,info,warn,debug
[DEBUG] configPath:,/home/kudlaty/.config/teams-for-linux
[INFO] Failed to get the config file, using default values
[DEBUG] configFile:,[object Object]
[INFO] Running under Wayland, switching to PipeWire...
[INFO] App already running
````

app is compiled from https://aur.archlinux.org/packages/teams-for-linux
version: 1.0.45-1

**Comment by IsmaelMartinez** [comment]
Probably ms have changed the links again. Can you check ctrl+click?

**Comment by kudlatyamroth** [comment]
```
xdg-open msteams://test
command= "teams-for-linux" args= ("teams-for-linux", "msteams://test")
kf.kio.core: Protocol Class of url QUrl("msteams://test") , isn't ':local', cancelling job.
Copying QUrl("msteams://test")  to QUrl("file:///home/kudlaty/.cache/kioexec/krun/26467_0/unnamed")
kf.kio.core: couldn't create slave: "Unknown protocol 'msteams'."
kf.kio.slaves.file: readData() returned -1
```

**Comment by kudlatyamroth** [comment]
```
xdg-mime query default x-scheme-handler/msteams
teams-for-linux.desktop
```
