### ISSUE TITLE
Refresh loop

### ISSUE THREAD

**Issue by alpharde** [IsmaelMartinez/teams-for-linux#403]
**Bug:**
After login, the application enters a refresh loop.

**How to Reproduce:**
Open the application, login

**Computer info:**
 - OS: Arch Linux
 - Installation package: Appimage
 - Version: 1.0.5

**Additional context:**
This console log is all I could get from it: https://gist.github.com/alpharde/92e4e982f393dcdcbe577365912305fe

**Comment by IsmaelMartinez** [comment]
Hi, 

A few things but can you check the comments in https://github.com/IsmaelMartinez/teams-for-linux/issues/268 and https://github.com/IsmaelMartinez/teams-for-linux/issues/269? 

It could be that:
*  you are seating behind a proxy (as the configuration is not allowing you throw) https://github.com/IsmaelMartinez/teams-for-linux/issues/269#issuecomment-526096491
* login due to MFA. https://github.com/IsmaelMartinez/teams-for-linux/issues/268#issuecomment-553700509

Hope helps,

**Comment by alpharde** [comment]
Isn't MFA an Azure thing? I don't have it nor personal 2FA.
Also I'm not using a proxy.

**Comment by IsmaelMartinez** [comment]
Did you try all the suggestions in those two previous tickets? Is this a
personal account or part of a company?

MFA is multi factor authentication. 2FA is just a type of MFA.

**Comment by IsmaelMartinez** [comment]
closing due inactivity (trying to keep things tidy). Please ping me with more information if you want it re-open.

**Comment by juliocebrito** [comment]
Hi,

Thanks! Great job, It works for me, but now teams does not log in when I off the VPN connection, so I have to comment the proxyServer variable, do you have any idea how to resolve that issue?

Thanks in advance.

**Comment by IsmaelMartinez** [comment]
Not sure. You could have 2 configs (one with the proxy and one without) and just start the one that you need. It does sound like a pain tbh. What do you get? Is this only with the newest version? It might be worth opening a new ticket instead of adding it to this one as we might be mixing info and/or making wrong assumptions.

**Comment by juliocebrito** [comment]
> Not sure. You could have 2 configs (one with the proxy and one without) and just start the one that you need. It does sound like a pain tbh. What do you get? Is this only with the newest version? It might be worth opening a new ticket instead of adding it to this one as we might be mixing info and/or making wrong assumptions.

![image](https://user-images.githubusercontent.com/9125193/236738910-b49310ef-553f-4fe7-9258-f35437e4e8fe.png)

![image](https://user-images.githubusercontent.com/9125193/236739063-d1235735-9de1-4093-b97e-1c761fcca9b8.png)


![image](https://user-images.githubusercontent.com/9125193/236737853-40589690-3cc3-4dfd-8806-dc0aa2724175.png)

**Comment by IsmaelMartinez** [comment]
It will be better to add a new ticket. If you do so, add the info you got and also the logs you get from starting the app with `appLogLevels "error,warn,info,debug"` (like `teams-for-linux --appLogLevels=error,warn,info,debug`)

As a workaround you should be able to start teams-for-linux from the terminal with the proxy options and removing them from the config file. Not ideal but it should work.

Like:

When you are in the VPN:
```
teams-for-linux --proxyServer=http://87.1.1.1:8080
```

When you are not in the VPN:
```
teams-for-linux
```

Not ideal but it should work.

**Comment by RolandRosenfeld** [comment]
What about a little wrapper script to start teams-for-linux like this:
```bash
#/bin/sh
if ip tuntap list | grep tun
then
    PROXY="--proxyServer=http://87.1.1.1:8080"
else
    PROXY=""
fi
/usr/bin/teams-for-linux "$PROXY" "$@"  
```

This is untested (don't know what type of tunnel you are using).
I'm also not sure when you need the proxy, so maybe you have to switch then/else parts.

**Comment by juliocebrito** [comment]
> It will be better to add a new ticket. If you do so, add the info you got and also the logs you get from starting the app with `appLogLevels "error,warn,info,debug"` (like `teams-for-linux --appLogLevels=error,warn,info,debug`)
> 
> As a workaround you should be able to start teams-for-linux from the terminal with the proxy options and removing them from the config file. Not ideal but it should work.
> 
> Like:
> 
> When you are in the VPN:
> 
> ```
> teams-for-linux --proxyServer=http://87.1.1.1:8080
> ```
> 
> When you are not in the VPN:
> 
> ```
> teams-for-linux
> ```
> 
> Not ideal but it should work.

Hi @IsmaelMartinez,

Thank you for the answer, This is the Log error

![Screenshot from 2023-05-08 13-42-02](https://user-images.githubusercontent.com/9125193/236951924-02cd5012-33f0-454b-9b65-c1c3032a19fd.png)


Thanks in advance.

**Comment by IsmaelMartinez** [comment]
@juliocebrito , I will recommend going down the route of a script like @RolandRosenfeld has provided (what a legend, thanks a lot). It will be pretty complex to implement this in to the app. Apologies.
