### ISSUE TITLE
Please post arm64 version on snapcraft.io

### ISSUE THREAD

**Issue by ilarrain** [IsmaelMartinez/teams-for-linux#405]
On Snapcraft there is the amd64 and the armhf versions available, but the arm64 version is not uploaded there.
Ubuntu Desktop is currently official on the Raspberry Pi 4, but only in arm64 platform. It would be nice to have the client available to download in the official software store.

**Comment by rvansoest** [comment]
Would love that. My son uses a pi400 with ubuntu for homeschooling. A arm64 version would be great.

**Comment by IsmaelMartinez** [comment]
Hi,

Feel free to create a PR with the changes. It should be fairly easy but I can't do it an test it without lots of work. (haven't got a linux machine to hand anymore)

I believe it should be just adding a new https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L33 for arm64 and add another step in the github actions similar to this one but calling the new package.json command https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/.github/workflows/build.yml#L113 

I think I didn't add it as I assumed you need to build the arm in an arm machine but I might be wrong. 

@julian-alarcon might know more about this as he did most of the initial work for Snap and is the snap expert on this. 

Hope helps!

**Comment by rvansoest** [comment]
Great. Thank you. Will have a look at it.

**Comment by julian-alarcon** [comment]
I don't have so many time this days but I could check your PRs related with Snap.

**Comment by rsun0525** [comment]
Was is determined that you need an arm64 machine to build an arm client?  I'm happy to ship someone a pi400 and they can put an arm64 OS on it to do the build, etc (or put the arm64 OS on it for you, etc.) what can I do to help make this request easier to complete?

**Comment by IsmaelMartinez** [comment]
maybe just try it. found this info online, not sure if it will do the job:

https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi

as I stated in the https://github.com/IsmaelMartinez/teams-for-linux/issues/405#issuecomment-757841164 , you might need to create another package.json step/option with something like this

```
"dist:linux:snap:arm64": "SNAPCRAFT_BUILD_ENVIRONMENT=host electron-builder --arm64 -l snap -p always",
```

If that snap package works, then we can see how to integrate it to the build environment. Again, I think github actions don't support ARM, but I might be wrong.

**Comment by IsmaelMartinez** [comment]
maybe you can use a self-hosted runner for this https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners happy to add it to the list of runners in here.

**Comment by IsmaelMartinez** [comment]
an example in here https://dev.to/l04db4l4nc3r/self-hosted-github-actions-using-raspberry-pi-212m but that means someone has to have the pi connected somewhere (I think I got a pi somewhere hidden... might see if one of this days I got time to play with this)

**Comment by rsun0525** [comment]
I'm happy to host a Raspberry Pi for this, but I'm not skilled enough to do the rest.

**Comment by rsun0525** [comment]
That's great news.  What is the next step to get it working for everyone?

pi@raspberrypi400:~ $ sudo snap install teams-for-linux
error: snap "teams-for-linux" is not available on stable for this architecture
       (arm64) but exists on other architectures (amd64, armhf).

**Comment by nicoacho** [comment]
![image](https://user-images.githubusercontent.com/81648519/113199461-0f3aeb00-925f-11eb-82f4-f2c5bee1b557.png)

**Comment by IsmaelMartinez** [comment]
I will have a look after my holidays. Apologies!

**Comment by IsmaelMartinez** [comment]
I am happy to link that raspberrypi and help on the gitactions changes. Not sure when I would have time but do ping in here. Alternatively, I am happy to setup a pi, but need to find were I left it, etc (and a bit more time)

**Comment by HenrikNyberg** [comment]
Any news on a 64bit Rpi version of the snap?

**Comment by IsmaelMartinez** [comment]
The instructions are there. We only need someone to host the pi and make the git actions changes. I can support but can do the job. Apologies.

**Comment by IsmaelMartinez** [comment]
I think the latest version of electron-builder and electron might have brough another option to make this possible. Can someone try the arm64 versions in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.8  ? They aren't for snap but if those work in a pi, then we might be able to tweak the snap build command to just build it for all (instead of for just 2 architectures). Thanks in advance

**Comment by SayidHosseini** [comment]
@IsmaelMartinez 
I tested that on Ubuntu Budgie 21.04 on RPi 4B 8GB and it is working.
