### ISSUE TITLE
Provide Flatpak packaging

### ISSUE THREAD

**Issue by kolya-ay** [IsmaelMartinez/teams-for-linux#41]
I would be cool to have flatpak build along with snap and [publish it](https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app) to flathub to distribute app updates.

**Comment by IsmaelMartinez** [comment]
feel free to add it. I don't really have the time at the moment to implement this but I am happy to support you.

**Comment by gabops** [comment]
Hello there!

I just wanted to mention that I am currently working in the Flatpak of this great Teams client. You can track the status of it in the pull request [com.github.IsmaelMartinez.teams_for_linux](https://github.com/flathub/flathub/pull/1020)

**Comment by gabops** [comment]
Hello there!

I've create a Flatpak distribution of this amazing Teams client for Linux. You can install it from the Flathub repo at https://flathub.org/apps/details/com.github.IsmaelMartinez.teams_for_linux or get the code of the flatpak itself, report issues, PRs etc at https://flathub.org/apps/details/com.github.IsmaelMartinez.teams_for_linux

Thank you for this useful tool.

**Comment by IsmaelMartinez** [comment]
Hi @gabops ,

Amazing! Thanks a lot for it. I just got a few questions for future maintenance, etc.

How do you know when to release a new version? Are you building from master? Do you want me to ping you after every release of is there some magic build in the flathub integration?

Thanks again!

**Comment by gabops** [comment]
Hi @IsmaelMartinez,

Your are very welcome! About your questions:

> How do you know when to release a new version?

currently I have a "watch" configured for new releases in your repo. Everytime you release a new version I will get a notification.

> Are you building from master?

No, I am pointing to the release by doing this in the flatpak manifest:
```yaml
      - type: git
        url: https://github.com/IsmaelMartinez/teams-for-linux.git
        tag: v0.3.0
```
So, the flow could be:
1. I get a notification of a new version from your repo.
2. I create a new branch for testing in the flatpak teams repo (https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux)
3. I will update the manifest and other changes if required. Then I will push and PR from that branch against master.
4. If everything is ok it will be merged and all the users will get the update on their systems.

Or could be as well:
1. Any user realizes there is a new release in your repo.
2. Creates a fork of the Flathub teams repo.
3. Makes a PR from the fork against the master branch in the Flathub teams repo.
4. If everything is ok, flathub developers or me approve or not the merge.

**Comment by IsmaelMartinez** [comment]
Great! Maybe worth adding a "get it in flathub" badge in the main readme... But we need to do that for snap and arch also so not needed to worry at this moment. Thanks again!! I will close this as is now done!

**Comment by bubble75** [comment]
Procedure described for new releases doesn't seem to work. flatpak is still on 0.4.0

**Comment by IsmaelMartinez** [comment]
I believe there is an open PR for it (not fully finished). I don't maintain
flatpack not aur. Once azure pipelines are in place I might look into
automating the flatpack, but I am pretty busy at the moment. Feel free to
help on the flatpack. I believe is just a command that needs run to update
a file. Let me know if you have any questions.

**Comment by IsmaelMartinez** [comment]
the issue that I am referring is this one:
https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/issues/6

**Comment by bubble75** [comment]
I actually meant human factor.
I found nice released rpm and it is enough for me, thanks!
