### ISSUE TITLE
building with podman / docker

### ISSUE THREAD

**Issue by mxsteini** [IsmaelMartinez/teams-for-linux#411]
Since I have to provide many project with many different node versions, I try to encapsulate my build processes in podman commands (should be the same in docker)
Today I built the latest version with:

podman run -it --rm --volume .:/var/mnt:z -w /var/mnt/ node:12 /bin/bash -c "apt update && apt install -y rpm && yarn install && yarn run dist:linux"

**Comment by IsmaelMartinez** [comment]
Hi @mxsteini, thanks for the suggestion. If you have the time and can add it to the contributing readme, that will be amazing. I will happily accept that PR. Thanks again!

**Comment by IsmaelMartinez** [comment]
Thanks a lot @mxsteini . I merged your change in https://github.com/IsmaelMartinez/teams-for-linux/pull/413 Thanks again!
