### ISSUE TITLE
Everything black and only mouse visible in entire screen screen share

### ISSUE THREAD

**Issue by 7RST1** [IsmaelMartinez/teams-for-linux#412]
**Describe the bug**
This might be a continuation of [this bug](https://github.com/IsmaelMartinez/teams-for-linux/issues/108) also.

When selecting what to share, the "Entire screen" option shows both screens (as mentioned in the issue above), but for me it's black and only the mouse is visible. 

**To Reproduce**
1. Join whatever meeting
2. Click on sharing shelf
3. Pick screen sharing and then entire screen.

**Expected behavior**
The ideal thing would be for both screens to be visible and selectable separately. This issue is more focused on the fact that the sharing shows black screens and mouse though.

**Screenshots**
![image](https://user-images.githubusercontent.com/16783057/106634195-d4c71180-657f-11eb-972f-1652b728b513.png)

![image](https://user-images.githubusercontent.com/16783057/106634271-eb6d6880-657f-11eb-902c-2b3695fbb261.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.10 x86_64
 - Installation package: deb
 - Version: 1.0.6

**Comment by josefschabasser** [comment]
Hi!

Please try to downgrade to v1.0.5 as it could be related to #406 .

Best regards
Josef

**Comment by 7RST1** [comment]
Oops, didn't find that one. Will follow there.
