### ISSUE TITLE
Option to load file from device not readable

### ISSUE THREAD

**Issue by mpretu** [IsmaelMartinez/teams-for-linux#414]
**Describe the bug**
The option to load a file from the device is broken, unreadable.

**To Reproduce**
1. Go to 'Assignments' > Assigned > 
2. Click on some "work" you already have
3. Below, under 'My work', click on 'Add work'
4. Below, on the following page, click on "Upload from this device"
5. See error

**Expected behavior**
I hope this is an error that can be reproduced and fixed

**Screenshots**
![screen_2021-02-11_17-26-19](https://user-images.githubusercontent.com/78922273/107669037-a0470a00-6c91-11eb-98eb-9edc99f0655b.png)

**Desktop (please complete the following information):**
 - OS: Manjaro OS, 20.2. XFCE, Kernel 5.9.
 - Installation package [snap]
 - Version [latest/stable | 1.0.6]

**Comment by IsmaelMartinez** [comment]
Hi @mpretu, that does look like a missing font. Do you get any messages if you open it with --webDebug? (or right click in the icon and something like developer tools/debugging)

**Comment by IsmaelMartinez** [comment]
closing due inactivity
