### ISSUE TITLE
Running 64 bit of Raspberry Pi OS and wanted to install teams-for-linux

### ISSUE THREAD

**Issue by rsun0525** [IsmaelMartinez/teams-for-linux#415]
pi@raspberrypi400:~/ $ sudo snap install teams-for-linux
error: snap “teams-for-linux” is not available on stable for this architecture
(arm64) but exists on other architectures (amd64, armhf).

**Comment by IsmaelMartinez** [comment]
closing as duplicated. look at https://github.com/IsmaelMartinez/teams-for-linux/issues/405
