### ISSUE TITLE
Teams not connect Error Code: 50196

### ISSUE THREAD

**Issue by HellMederimBoy** [IsmaelMartinez/teams-for-linux#417]
I get a error in my gentoo linux

The error occurs when i login in my account and says  "can not connect in the moment"

Error Code: 50196
Request Id: 836e9516-6d4a-427a-8496-f8b4dc2a1d00
Correlation Id: bd3f8fdc-f901-4427-bdc1-e83c5ddcf622
Timestamp: 2021-02-24T14:19:46.446Z

 - OS: Gentoo amd64
 - Installation package: AppImage
 - Version: 1.0.6

**Comment by IsmaelMartinez** [comment]
Hi @HellMederimBoy, are you behind a proxy? Can you try another package? Can you connect to your teams account using your browser? My guess in the proxy configuration. There is a [config option](https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config) to specify the proxy server (if that is the issue). Hope helps.

**Comment by IsmaelMartinez** [comment]
closing due inactivity
