### ISSUE TITLE
Font issue when saving attachments

### ISSUE THREAD

**Issue by FPSUsername** [IsmaelMartinez/teams-for-linux#419]
**Describe the bug**
When you want to save an attachment to your computer, a popup of the file manager opens which allows you to select the saving destination. The font on the file manager is "corrupt".

**To Reproduce**
1. Go to any message with an attachment
2. Tap the download button to save it on your computer
3. See the font issue

**Expected behavior**
A window of the file manager should popup with readable text.

**Screenshots**
Dolphin file manager when saving the attachment:
![Teams Download](https://user-images.githubusercontent.com/10143926/112725781-353c5480-8f1a-11eb-8dbd-7f2e6152af88.png)

What my actual Dolphin file manager looks like under default circumstances:
![Dolphin](https://user-images.githubusercontent.com/10143926/112725958-302bd500-8f1b-11eb-9919-240084fe146c.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - DE: KDE Plasma 5.21.3 
 - Installation package Snap
 - Version 1.0.6
 
**Additional information**
This happens under any system selected font. I tested it with the default Noto Sans and Apple's SFPro Text fonts.

**Comment by FPSUsername** [comment]
I tried the AppImage release and it works fine. Seems like the Snap package is giving this issue.

**Comment by IsmaelMartinez** [comment]
I think this is a snap configuration issue. I sort of remember something like that happening quite a while back.

Check [this comment](https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632446994) as it did solved the issue

**Comment by IsmaelMartinez** [comment]
closing due inactivity
