### ISSUE TITLE
Notification number/dot in tray icon or dock icon

### ISSUE THREAD

**Issue by vtunr** [IsmaelMartinez/teams-for-linux#42]
Hi,

I don't have any notification information in the tray or on the app icon on the dock. I checked a bit the code and it seems to be there, so I'm wondering if I'm missing something ?

I would expect a dot or the number of missed notification.

Also, the notification on the notification panel (also on the lock screen) are disappearing really quickly, even if didn't read them. Maybe it could be linked.

I'm using ubuntu 18.04

vtunr

**Comment by IsmaelMartinez** [comment]
Hi @vtunr, regarding the "number" icons, are you able to check if that also happens to you if running from source? 

The notification disappearing quickly I believe is gnome configuration. You can use gnome extensions (tweens) to change those settings.
https://linuxconfig.org/how-to-install-tweak-tool-on-ubuntu-18-04-bionic-beaver-linux

One of the extensions is "permanent notifications" , but there are a few in there.

Thanks,

**Comment by vtunr** [comment]
Hi @IsmaelMartinez, I'll check running from source, i'll let you know.
Thanks for link to the configuration tool :)

**Comment by vtunr** [comment]
Hi @IsmaelMartinez, 

Just tested from the source, and it's working fine (I have the number of notification on the tray icon).
Any idea why it doesn't work from the package ? 
Let me know if you need more test or something.

**Comment by IsmaelMartinez** [comment]
Hi @vtunr ,  I can only think is a permissions related issue. 

Lets see if installing from the terminal works. 

Can you try the following from your terminal:
* remove the installed package (if you still got one) `sudo apt-get remove teams-for-linux`
* remove the local cache/configuration. It should be located under `~/.config/teams-for-linux`
* get the latest package with `wget https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v0.1.13/teams-for-linux_0.1.13_amd64.deb`
* then try installing the package with your user using `dpkg -i teams-for-linux_0.1.13_amd64.deb`

Try if that works. I have seen this happening in my computer at work, but I normally run it from source.

Let me know how it works and I will try to check further tomorrow at lunch if I manage to get a bit of time.

**Comment by vtunr** [comment]
Unfortunately, still not working with your last solution :/

**Comment by IsmaelMartinez** [comment]
I been doing a bit of research and:
* either is an actual Ubuntu Linux appindicator issue
* is a problem with the path, the one is been pass to the pageTitleNotifications for the nativeImage.createFromPath (https://github.com/IsmaelMartinez/teams-for-linux/blob/master/app/browser/pageTitleNotifications.js#L57) because of this (https://github.com/IsmaelMartinez/teams-for-linux/blob/master/app/browser/index.js#L9)

I will see if I can work on it tomorrow but I am not sure if I will be able to.

In the meantime, probably revert running from source.

**Comment by IsmaelMartinez** [comment]
Ok, I think it must be something with Ubuntu. I tried with version 3 and 4 of electron adding plenty of logs and the path seems to be ok for all the cases... but it doesn't work if the app is packaged. 

Now, looking at the logs, I get the /var/log/syslog following in both cases:
* registering statusnotifiericon 
`Jan 25 21:27:31 --- gnome-shell[2536]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.174/org/ayatana/NotificationItem/Electron1`

but if running from source, I get also a: 
`Jan 25 21:27:39 --- gnome-shell[2536]: [AppIndicatorSupport-FATAL] unable to lookup icon for Electron1_1`

I think this might be related 
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/139

**Comment by IsmaelMartinez** [comment]
I checked the following. It did seem to work at 1st but not again:
https://github.com/electron/electron/issues/10427#issuecomment-386024975

Give it a try to see if that solution works for you.

**Comment by IsmaelMartinez** [comment]
ok, seems like it was related to the libappindicator.
https://github.com/electron/electron/issues/12791

I have done what the following commit says:
https://github.com/electron/electron/issues/12791#issuecomment-441333532

Basically, removed libappindicator-* doing a `sudo apt-get remove libappindicator-*`

That will remove also the teams app... and check as probably tries to remove other apps so just be careful.

Then, just installed the app again, that will install the libappindicator again. All working fine in here.

could you check that it works for you? I will close it if either I don't get and answer in a few days or if it works. Thanks

**Comment by fezu54** [comment]
Is there some other workaround available for this? Removing libappindicator3 would mean you can't use Google Chrome anymore, which means you'll not able to use Goto Meetings screen sharing functionality nor something like Vysor anymore. They are relying on the PNaCL plugin which is not available for Chromium.

**Comment by IsmaelMartinez** [comment]
Hi @fezu54, Is removing it to install it again... seems like the one electron installs and the one that comes with the system don't work together that well.

**Comment by fezu54** [comment]
@IsmaelMartinez I'm just curious if there is some other workaround available. Before, I was using https://github.com/ivelkov/teams-for-linux as a wrapper. There, I had the same problem and I could solve it with patching the tray-notification.js and use a smaller icon. But here, the structure is a bit different, nor?? 
[tray-notifications-patched.txt](https://github.com/IsmaelMartinez/teams-for-linux/files/2988521/tray-notifications-patched.txt)
![icon-96x96](https://user-images.githubusercontent.com/4998526/54689807-783fe200-4b20-11e9-9acf-76e4d24a040c.png)

**Comment by IsmaelMartinez** [comment]
You should be able to change those values in the `app/browser/notifications/trayIconRenderer.js` . If they work fine for you then add a PR and i will be more than happy to add it!

**Comment by pavangayakwad** [comment]
Not seeing any notification number or a dot on system when I run it on Linux Mint 22 Cinnamon. Have you guys tested this? I am running multiple instances some with custom icons. Could you please help me here?

<img width="294" height="95" alt="Image" src="https://github.com/user-attachments/assets/21f8c0a4-a8a8-463e-8819-158ab0acafde" />

**Comment by IsmaelMartinez** [comment]
Hi @pavangayakwad , can you open a new issue? The app has changed quite a bit since 2019. Provide as much info as possible (logs etc). Thanks

**Comment by pavangayakwad** [comment]
Hi @IsmaelMartinez, Its done! https://github.com/IsmaelMartinez/teams-for-linux/issues/1929

**Comment by IsmaelMartinez** [comment]
this was fixed in 2.6.6, so update your version to that version or later and it should work again. thanks for reporting it
