### ISSUE TITLE
Ability to mute audio of all meetings

### ISSUE THREAD

**Issue by the-anonymous-raven** [IsmaelMartinez/teams-for-linux#427]
Loved your project and have been a user since 1 year. Keep up the good work!

Can you add a feature to mute speaker audio in meetings or perhaps implement a way to route the audio through earphones rather than speakers?

**Comment by IsmaelMartinez** [comment]
Hi @the-anonymous-raven, I think you should be able to check those settings in the current version. Just make sure you look at the audio settings.

Also, I will appreciate if next time you can use the template. Simplifies stuff (or just use the discussions tab if just want to put generic questions). Thanks
