### ISSUE TITLE
Not able to use MS Teams using Edge user agent option

### ISSUE THREAD

**Issue by julian-alarcon** [IsmaelMartinez/teams-for-linux#43]
Using latest version, 0.1.13, I'm not able to use the service. Tried using .deb package (´teams --edgeUserAgent´) and run it directly (´yarn start --edgeUserAgent´). After this I got an error from MS Teams _Doh! Something went wrong_

![screenshot from 2019-01-25 08-07-14](https://user-images.githubusercontent.com/30119472/51747939-e2845b00-2078-11e9-8f1d-b8b5da00ac64.png)

**Comment by IsmaelMartinez** [comment]
Same as #44 , by doing that you are providing an empty user agent and I have no idea what Electron will do with that.
