### ISSUE TITLE
Install Warnings on Debian

### ISSUE THREAD

**Issue by aubertc** [IsmaelMartinez/teams-for-linux#430]
**Describe the bug**

On debian, two warnings are issued during the installation:

```
chmod: cannot access '/opt/teams-for-linux/chrome-sandbox': No such file or directory
/var/lib/dpkg/info/teams-for-linux.postinst: line 10: update-desktop-database: command not found
```

They do not seem to affect the functionality or behavior of teams.

**To Reproduce**

1. Download the [debian package](https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.0.6/teams-for-linux_1.0.6_amd64.deb)
2. As root, `dpkg -i teams-for-linux_1.0.6_amd64.deb `

**Expected behavior**

Those warnings should not be issued if they do not affect team's behavior.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 4.19.0-16-amd64 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
 - Installation package: teams-for-linux_1.0.6_amd64.deb 
 - Version 1.0.6

**Additional context**
The second warning may be related to https://github.com/electron-userland/electron-builder/issues/4341

**Comment by IsmaelMartinez** [comment]
Hi @aubertc, It looks like is that electron-builder issue. Is annoying but this project is now on support mode only and this is not affecting the usage or installation of the app so I will close this. 

Thanks for reporting the issue!

**Comment by aubertc** [comment]
Thanks, I understand!

I also opened this ticket as a way of "pinging" electron-builder about it: more than one software is affected by it.
