### ISSUE TITLE
Sign-in issue

### ISSUE THREAD

**Issue by gtr25** [IsmaelMartinez/teams-for-linux#435]
**Describe the bug**
I cannot login using my institutional mail-id.

**To Reproduce**
1. Enter the mail-id 
2. Enter the password
3. Try logging in

**Screenshots**
After displaying "Checking your credentials", It returns to the login screen with this is error message.
![Microsoft Teams for Linux - bug report snapshot](https://user-images.githubusercontent.com/63329157/122735496-b6e31a80-d29c-11eb-8251-847d9e8a7e80.png)

**Desktop :**
 - OS: Manjaro 5.10.42-1 - KDE Plasma
 - Installation package : snap
 - Version 1.0.7

**Additional context**

**Terminal:**
<div class="snippet-clipboard-content position-relative">
<pre>
<code>
[gtr@localhost ~]$ teams-for-linux
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Gtk-Message: 21:01:44.951: Failed to load module "xapp-gtk3-module"
Gtk-Message: 21:01:45.033: Failed to load module "colorreload-gtk-module"
Gtk-Message: 21:01:45.033: Failed to load module "appmenu-gtk-module"
configPath = /home/gtr/snap/teams-for-linux/156/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "msteams" setting: exit status 4
processArgs [ '/snap/teams-for-linux/156/teams-for-linux' ]
did-finish-load
did-finish-load
did-finish-load
did-finish-load
did-finish-load
...
</code></pre>

**Comment by jijojosephk** [comment]
@gtr25, This might not be problem with this application. Could you verify if the same works in Chrome browser? As far as I know teams works with office 365 accounts only unless it's a guest invite.

**Comment by gtr25** [comment]
I used an office 365 account FYI. But this seems a bit weird. My account passed through in other devices and also the other OS (Windows 10) in the same machine. But the same error `We couldn't sign you in. Please try again.` is returned when I tried logging in through a browser on the **Manjaro** that I mentioned earlier. I'll contact the MS support team for further assistance. Thank you!

**Comment by IsmaelMartinez** [comment]
Do you have a proxy configured for Windows? If so, there is a config option your I'll need to use. Check previous closed issues and/or the config folder. Hope helps

**Comment by MortenVinding** [comment]
I had the same problem on 1.0.7 (snap 156).
On the current 1.0.9 (snap 172), after entering my credentials, I get to the company's ADFS login prompt, where I can input user and password, but are unable to click on the submit button and enter is ignored.

Solution for both, for me, was to disconnect from the company network forcing Teams to do a full TOTP authentication.
That works and the session is saved so I can reconnect to the company network and continue my work.

Looks like a hidden or mishandled login prompt somewhere.
