### ISSUE TITLE
Multi-tenant feature

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#438]
### Discussed in https://github.com/IsmaelMartinez/teams-for-linux/discussions/436

<div type='discussions-op-text'>

<sup>Originally posted by **jijojosephk** June 25, 2021</sup>
I've personally suffered from missing this feature on official teams client. What are the problems?

- It only works with one organisation
- Well you can log out and login but there's a terrible bug. After log out when you try to login with another domain, it just does not work. This bug exists for a long time. Anyway..
- I work with 3 different Teams Organisations everyday. Absolutely not possible with the official client.
- I'm still unsure on why can't they do it.

What I've tried is to have multiple snaps with different names when installing. One instance itself works slowly. I imagine how it would be when there are 3.

Then, I started my own personal experiment and created a multi tenant electron wrapper. Currently I enjoy using it. I had no intentions to make it public rather I consider it as a work around for the troubles I had faced.

What are your suggestions about this feature? Is it worth?</div>

**Comment by jijojosephk** [comment]
Depends on: #441

**Comment by nursoda** [comment]
If one is logged-in [1] with a AzureAD account (typically a user of the own M365 tenant), and uses the primary email address of that account to register as guest in other tenants, then switching works fine in the official Teams client. Only if one has to log-in [2] with real/different users (of each tenant's AzureAD), then one currently has to log out from tenant A to be able to login to tenant B – while the official client remembers all users used and as such eases the re-login a bit. It's a pain if MFA is enabled in all tenants, though. I don't understand the goal of this issue: Is it about [1] or [2]? I think that the way intended / assumed by Microsoft is that one only works in one tenant as user and as guest in all other tenants. While I also suffer from that inability to easily switch between multiple real users, I don't think this is something the client can solve – either Microsoft allows for it or not. Or am I mistaken here?

**Comment by jijojosephk** [comment]
It's possible but yet to prioritise the work. The source code has to go through many lines of changes and to avoid any breaking changes it's not there yet. Probably 2.x range of versions can accommodate this feature. I think about it everyday but not finding time to implement.

**Comment by IsmaelMartinez** [comment]
Closing this as people has managed to get the multitenant working by running multiple instances.

**Comment by kitingChris** [comment]
Sad that this feature is closed. It would be such an advantage over the official teams client... 
It would make work so much better

**Comment by jijojosephk** [comment]
@kitingChris don't get disappointed. @IsmaelMartinez just closed to focus on what's more important now. I'll come back to it. Totally busy with my personal work now. Maybe spin off another branch for experimental features?

**Comment by IsmaelMartinez** [comment]
Was tidying up issues. We had over 50 open ones but there was no much noise in this one. Happy to reopen whoever people are using this client to have multiple accounts open (with different icons and titles). Not perfect but does work.

**Comment by TheOpenDevProject** [comment]
@jijojosephk ScyllaDigital (My Company) would be happy to take this work on as we deal with lots of clients throughout the day and its a horrible experience.

We will fork this and contribute it back when we have something stable

**Comment by jijojosephk** [comment]
@TheOpenDevProject thanks for the openness! I have no problem, but I'll let @IsmaelMartinez the owner the repo speak if he has something to say. Kindly contribute back, it was a long struggling journey fighting the odds having zero support from MS. I had started it but could not continue due to lack of time. https://github.com/IsmaelMartinez/teams-for-linux/discussions/436#discussioncomment-925963. It would be great if this feature gets implemented.

**Comment by IsmaelMartinez** [comment]
Thanks a million! Do let me know if you want some insights and/or early planning/ feedback. It can be a bit of a mammoth task tbh, reason why we have move it to the side. It might be possible to implement it in an easier way to what I have been playing with.

Ideally we use BrowserViews inside one single BrowserWindow (to avoid memory going up to the roof), and have some sort of tabs. 

Again thanks again and feel free to ask any questions.

**Comment by mikalai-t** [comment]
Can't wait this feature being implemented natively. Until that has anyone tried to run another instance in Docker container? I managed to do it previously with the official client, but can't build a new Docker image now as it was removed from the MS deb repos.

**Comment by IsmaelMartinez** [comment]
You have the option to run two instances of the application, each with its own unique configuration. 

Here's how to do it:

1. Create two separate `config.json` files with distinct names.
2. In each of these `config.json` files, configure the following settings:
   - `appTitle` (if you want to give each instance a different title)
   - `partition` (this is an Electron internal setting used to separate data areas; more information is available [here](https://www.electronjs.org/docs/latest/api/browser-window))
   - `appIcon` (if you want to use different icons for each Teams instance)
3. To launch each instance with the appropriate configuration, use the following command:

```bash
teams-for-linux --config ~/.config/teams-for-linux/config.json
```

Make sure to replace `~/.config/teams-for-linux/config.json` with the actual file path of the configuration you want to use for each instance.

More details of other config options in [https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config](https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config).

This way, you can run multiple instances of the application with distinct settings.

**Comment by DomGiant** [comment]
Hi @IsmaelMartinez,
I am on Debian and tried your approach but, whatever config file I use (each one with a different `partition`), I keep getting the same session on the same tenant. What am I missing? Thank you for your support.

**Comment by SecT0uch** [comment]
@DomGiant after a few trial and error here is a solution that works multi-accounts:
```
mkdir /home/user/.teams-data
teams-for-linux --appTitle "Teams - Account1" --customUserDir="/home/user/.teams-data/account1
teams-for-linux --appTitle "Teams - Account2" --customUserDir="/home/user/.teams-data/account2
```

**Comment by IsmaelMartinez** [comment]
Another example is in https://github.com/IsmaelMartinez/teams-for-linux/discussions/764#discussioncomment-5707658 

It is worth to notice that the appTitle part is not working in teams-v2

**Comment by cs96and** [comment]
I've just been given a second Teams account (same email address as first account, but as a guest on another company's Teams).  Just wondering if there is any update on support multi-tenant without having to run two instances?

**Comment by jmergy** [comment]
Same situation - love T4L and one one account, I have multiple orgs and switching is great. But, I have another login/account and would love to be able to flip over.

**Comment by jmergy** [comment]
@cs96and the option to run then from separate directories works really well. Here is what I do now in Debian 12.5

/usr/bin/teams-for-linux --customUserDir=/home/username/t4l/client1 --appTitle=Teams-Client1 &

/usr/bin/teams-for-linux --customUserDir=/home/username/t4l/client2 --appTitle=Teams-Client2 &

**Comment by IsmaelMartinez** [comment]
use the --appIcon=/(your icon full path) if you want to have a different icon (so you don't get confused by the 2 icons and don't know what org is each). The appTitle only works if you are using MS teams v1. That is currently broken for teams v2.

**Comment by jmergy** [comment]
@cs96and it'll just go through the initial login again and update files there (if  you point it at an new directory. 

My default UserDir (on Debian 12.5) is 

/home/username/.config/teams-for-linux 

But YMMV

**Comment by cs96and** [comment]
Today when I logged into teams, it now gives me the option to switch between the two accounts at the top right.

**Comment by alexschomb** [comment]
> Today when I logged into teams, it now gives me the option to switch between the two accounts at the top right.

Can't confirm this. Are you sure that the second "account" isn't just another organization you joined as a guest / connected organization with the other account? This works just fine, but switching between multiple accounts / tenants that are not connected at all (or even adding them) is not available right now, although available in the Windows version of Teams v2.

**Comment by cs96and** [comment]
> > Today when I logged into teams, it now gives me the option to switch between the two accounts at the top right.
> 
> Can't confirm this. Are you sure that the second "account" isn't just another organization you joined as a guest / connected organization with the other account? This works just fine, but switching between multiple accounts / tenants that are not connected at all (or even adding them) is not available right now, although available in the Windows version of Teams v2.

Yes it's another organisation I joined as a guest.  The weird thing is that yesterday when I first joined that organisation (which I did on a Windows PC), there was no way for me to switch between the two on my Linux machine, but today there is.

Anyway, it's working now.  I guess I don't fully understand the difference between guest accounts and multiple tennants.

**Comment by jmergy** [comment]
Sure - so if you have a single Microsoft 365 account, that account has a relationship to Microsoft 365 Organizations (tenants) and that relationship could be various levels - guest access or admin or user or whatever. You can switch between organizations that have relationships with that Microsoft 365 account. 

If you have multiple Microsoft 365 accounts, then you cannot switch easily between those accounts. Each account has relationships to organizations. The issue for some of us is we want to be able to span accounts to get to organizations which we cannot do without logging out and in to the separate accounts or, as above, we run multiple instances of teams-for-linux that each are logging into separate Microsoft 365 accounts to access the organizations connected to those accounts. 

mergy@domain.com
- Organization 1
- Organization 2
- Organization 3

mergy@otherdomain.com
- Organization 4
- Organization 5

In the above, if I login as mergy@domain.com with teams-for-linux, I can switch between Organization 1-3 which is awesome and it doesn't matter if I have guest only on some and full-on licensing or admin on others. But, I can't be logged in as mergy@domain.com and switch to go to Organization 5 or flip accounts to get to Organization 5 without exiting everything and logging back in as mergy@otherdomain.com. Then, I can't easily jump to Organizations 1-3 but can easily switch to Organization 5

BTW, Microsoft doesn't do this at all either! The solve would honestly be to have the ability to connect accounts in Microsoft 365 at the profiles level IMHO. But, bah.  

It's just a challenge for folks that serve and handle different clients and groups and have different accounts for various crazy reasons. The multiple instances and UserDir command option works well for this for now.

**Comment by My1** [comment]
is there also a way to do this on flatpak?

when I try to add the extra args so it would look like this:
`flatpak run --branch=stable --arch=x86_64 --command=teams-for-linux --file-forwarding com.github.IsmaelMartinez.teams_for_linux --appTitle="Teams - Tenant" --customUserDir="/home/my1/.config/teams-tenant"`
I get this instead:
```
[2:0311/112458.505204:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
No config file found (user or system-wide), using default values
all good with screenSharingThumbnail you aren't using them
all good with disableAutogain you aren't using them
all good with screenLockInhibitionMethod you aren't using them
all good with ssoInTuneEnabled you aren't using them
all good with ssoInTuneAuthUser you aren't using them
all good with videoMenu you aren't using them
Initialising logger with config: {"transports":{"console":{"level":"info"},"file":{"level":false}}}
11:24:58.966 › configPath: /home/[USER]/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux
LaunchProcess: failed to execvp:
xdg-settings
11:24:59.008 › App already running
[2:0311/112459.081340:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0311/112459.081415:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

I even tried to just open a normal bash inside flatpak and run the command clean

```
➜  ~  flatpak run --branch=stable --arch=x86_64 --command=sh --file-forwarding com.github.IsmaelMartinez.teams_for_linux 
[📦 com.github.IsmaelMartinez.teams_for_linux ~]$ teams-for-linux --appTitle "Teams - Tenant" --customUserDir="/home/my1/.config/teams-tenant"
[3:0311/113617.205719:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
No config file found (user or system-wide), using default values
all good with screenSharingThumbnail you aren't using them
all good with disableAutogain you aren't using them
all good with screenLockInhibitionMethod you aren't using them
all good with ssoInTuneEnabled you aren't using them
all good with ssoInTuneAuthUser you aren't using them
all good with videoMenu you aren't using them
Initialising logger with config: {"transports":{"console":{"level":"info"},"file":{"level":false}}}
11:36:17.624 › configPath: /home/[USER]/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux
LaunchProcess: failed to execvp:
xdg-settings
11:36:17.660 › [CustomNotificationManager] Initialized and listening on "notification-show-toast" channel
[3:0311/113617.727078:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0311/113617.727169:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0311/113617.829124:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0311/113617.829184:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0311/113617.829222:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
11:36:17.833 › [QuickChat] Quick Chat feature is disabled
11:36:17.834 › [AutoUpdater] Not running as AppImage, auto-updater disabled
11:36:17.834 › [IPC Security] Channel allowlisting enabled
11:36:17.834 › [IPC Security] 56 channels allowlisted

```

**Comment by IsmaelMartinez** [comment]
I don't know, but it does look like the dbus is blocked. I don't think we
can unblock it for flatpak, so just use another packaging option. Ta

**Comment by My1** [comment]
what is teams doing over the dbus? because other than the multi-account thing I havent seen issues so far with the flatpak release after I was able to sign in.

**Comment by IsmaelMartinez** [comment]
I believe is the system notifications, but I think the setting of the tray icon might also go via that area. Is internal electron stuff, not something we add on the top.
