### ISSUE TITLE
Open a Teams Meeting using x-scheme-handler

### ISSUE THREAD

**Issue by iMontouch** [IsmaelMartinez/teams-for-linux#439]
To open a meeting from the browser I pointed .config/mimeapps.list to teams-for-linux.desktop:
`x-scheme-handler/msteams=teams-for-linux.desktop`
and in the .desktop file I set the Exec entry to:
`Exec=teams-for-linux %U`

That way, the Meeting URL gets opened using teams-for-linux. In there I have to click "continue in browser" to open the meeting itself (oposed to just getting routed to the meeting directly).

Is it possible to further route the provided URL so that it gets directly opened as a meeting? Also, can the changes I made to mimeapps.list and the .desktop file be shipped by default? I copied the settings from the official teams client.

**Comment by IsmaelMartinez** [comment]
Hi @iMontouch, thanks for reporting.

Can you use the template to provide information like the package system you are using?

I have seen that issue specially with snap (been more a snap configuration). Thanks

**Comment by iMontouch** [comment]
FYI: For a feature request, the used system was not part of the template.

**Desktop**
 - Manjaro Ornara 21.0.7
 - Installation is done with yay, using this package: [aur/teams-for-linux](https://aur.archlinux.org/packages/teams-for-linux/)
 - Version 1.0.7-1

Do you need more information or do you want me to fill out the bug/feature template fully?

**Comment by IsmaelMartinez** [comment]
It might be better to ask in https://aur.archlinux.org/packages/teams-for-linux as they manage the aur packages. I believe they are better placed to help on this as it is a packaging issue (I believe)

**Comment by micwoj92** [comment]
Maintainer also has GitHub page for that package, so you might also ask there
https://github.com/frealgagu/archlinux.teams-for-linux

**Comment by IsmaelMartinez** [comment]
closing due inactivity
