### ISSUE TITLE
Stuck on purple screen using Chrome user agent option

### ISSUE THREAD

**Issue by julian-alarcon** [IsmaelMartinez/teams-for-linux#44]
Using latest version, 0.1.13, I'm not able to use the service. Tried using .deb package (´teams --chromeUserAgent) and run it directly (´yarn start --chromeUserAgent´). After this I got a purple screen and I'm not able to login or use the app. The tittle of the windows keeps saying _initializing..._

/home/julian/Pictures/Screenshot from 2019-01-25 08-08-06.png

**Comment by IsmaelMartinez** [comment]
The chromeUserAgent is to provide the userAgent long definition. 

https://github.com/IsmaelMartinez/teams-for-linux/tree/master/app/config

The application does switch user agent when it starts (after a few seconds). 

That hack is to be able to use mentions and the camera (one supported by chrome and the other by edge).

Can you try starting without the --chromeUserAgent?

**Comment by IsmaelMartinez** [comment]
Same as #43. closing as I think that is not an issue. It is not possible to change user agent as there is no need to do so (as video and mentions are working)
