### ISSUE TITLE
Losing focus during screen sharing preview

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#440]
**Describe the bug**
When the screen share preview is shown, All other running application windows get activated and Teams window goes behind them. User has to manually activate the Teams window.

**To Reproduce**
1. Stat a meeting
2. Click on share screen
3. Teams window is inactivated.

**Expected behavior**
Teams window should not lose focus.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Budgie 20.04 LTS
 - deb, snap
 - Version 1.0.8

**Additional context**

**Comment by IsmaelMartinez** [comment]
I believe this is fix and released under 1.0.9. Can you confirm @jijojosephk once you got some time? Thanks in advance

**Comment by jijojosephk** [comment]
@IsmaelMartinez It's a temporary fix to keep the teams window active. You'd see all other open windows shuffled except teams. From a user experience point of view, this makes the teams window active but not a friendly way.

**Comment by jijojosephk** [comment]
Electron version upgrade fixed this problem hence closing it.
