### ISSUE TITLE
Custom title bar

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#441]
**Is your feature request related to a problem? Please describe.**
Not related to any problem

**Describe the solution you'd like**
Custom title bar just like the official client.

**Describe alternatives you've considered**
No alternatives

**Additional context**
None

**Comment by IsmaelMartinez** [comment]
Hi @jijojosephk, do you know what to put in the custom title bar and/or how people can then customize it?

**Comment by jijojosephk** [comment]
@IsmaelMartinez We could make use of [custom-electron-titlebar](https://www.npmjs.com/package/custom-electron-titlebar). We'll make our own if this module does not satisfy our needs. This is required especially when we have multiple tabs coming in the future implementation #438 So all the tabs (BrowserView) should be inside a container (BrowserWindow). Container will have the Tab implementation. If we're using custom title bar, we can accommodate the tabs is in title bar itself that saves some space horizontaly also it would look better.

**Comment by jijojosephk** [comment]
The module mentioned above does not satisfy our requirement. So I started a new repo [here](https://github.com/jijojosephk/lintel-bar/tree/development) We'll add it as an npm module in teams repo.

**Comment by jijojosephk** [comment]
@IsmaelMartinez How does it look?
![image](https://user-images.githubusercontent.com/11662148/125079393-2d777900-e0e1-11eb-886b-62a324001150.png)

**Comment by IsmaelMartinez** [comment]
Looking good. Good job on it

**Comment by skyghis** [comment]
Hello,

Personally, I don't like the custom title bar. I totally understand why people like it, but I prefer unity between all windows.

Could you make it an option, and allow use of the default desktop manager one, like now ?

**Comment by jijojosephk** [comment]
@skyghis, Introduction of custom title bar is only to accommodate tabs #436 in a multi tenant setup. Of course, tabs can be below the title bar but it will use up extra row space which might not look good as well. This follows, google chromes's strategy. It does not follow OS's title bar. The implementation is not started yet. It's activate as a separate project as npm package [here](https://github.com/jijojosephk/lintel-bar). Appreciate your suggestion, that will keep it evolving.

**Comment by kitingChris** [comment]
Custom Titlebar would be a very nice feature. With or without the multi tennant feature
