### ISSUE TITLE
Click Share Desktop nothing happen

### ISSUE THREAD

**Issue by franva** [IsmaelMartinez/teams-for-linux#446]
**Describe the bug**
When in a meeting, click "Share Desktop" nothing happens.

**To Reproduce**
1. Have a meeting with anyone
2. Click on 'Share Desktop'

**Expected behavior**
My screen should be shared.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation package from the built-in Ubuntu Software(store)
 - Version : 1.0.7 (the Teams-For-Lunix)

**Comment by micwoj92** [comment]
Can't you see that you are not running latest version?

**Comment by franva** [comment]
hi @micwoj92  Yep, I just found that.

The version I installed is the latest version I got from the Ubuntu built-in store: Ubuntu Software.
For normal users, not developers, we assume that's the latest one.

Not sure why the latest 1.0.8 is not in the store.

**Comment by jijojosephk** [comment]
@franva, snap store is not yet updated. But you may grab the latest version from releases [here](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.8). Please choose the right package for you.

**Comment by jijojosephk** [comment]
@franva Were you able to get the latest version and it's working?

**Comment by franva** [comment]
hi @jijojosephk  yes, I was able to get the latest version.

It is partially working.

The Share Desktop function is not stable. It works for a while and then stops working.

I ended up using the Teams in my Chrome browser instead.

**Comment by micwoj92** [comment]
"For normal users, not developers, we assume that's the latest one."

I don't know how using application store relates in any way to being developer. If you end up here, you can see 1.0.8 under releases as latest.

![image](https://user-images.githubusercontent.com/45581170/125338727-d5df4480-e350-11eb-8e5d-509e5dc4ad3b.png)

**Comment by IsmaelMartinez** [comment]
snap had 1.0.7 released. Somehow I forgot to release 1.0.8 when that build and before doing the 1.0.9 build... so now, snap is a bit ahead of the pack with 1.0.9 released in there ;) 

I will see if I can release 1.0.9 to the rest. I was waiting in case @jijojosephk or someone else added something else to it. I will mark it as pre-release in here... so people can play with it if they want to. (its just the focus change that is in there)

**Comment by franva** [comment]
Hi @IsmaelMartinez  Just one more issue I found that the Share Desktop is not stable.
It works for a few seconds e.g. 30 or more and then the screen on the audience side becomes still. 

I tried to do the same in Chrome browser and it works fine without this issue.
Not sure whether you are aware of this issue, so I mention it here.

Cheers

**Comment by jijojosephk** [comment]
@franva Could you open a new issue with the details? That helps us investigate it.

**Comment by jijojosephk** [comment]
@franva Could you confirm the recipient's operating system?  I tested with Linux haven't faced any issues. We wanted to figure out if it's related to MacOS.

**Comment by franva** [comment]
hi @jijojosephk  I am not sure what is the OS for the recipients. But when I meant after 30 seconds sharing my screen, the screen becomes still from my side. Hope it helps.

**Comment by jijojosephk** [comment]
@franva Could you provide some more details?

- Your operating system, including version information
- Hardware configuration 
- Primary display resolution
- I'm assuming the problem is recipients don't get screen sharing updates from you after a certain interval.
- The between start sharing and the screen getting frozen is always fixed? Like always 30 seconds?
