### ISSUE TITLE
Zoom resets to 100% on app close or refresh

### ISSUE THREAD

**Issue by DiegoChajtur** [IsmaelMartinez/teams-for-linux#447]
**Describe the bug**
It does not keep the zoom (ctrl +), when closing the application or doing a refresh (ctrl + r)

**To Reproduce**
1. zoom in (ctrl + ) or zoom out (ctrl +-)
2. Restart app o do a refresh
3. Zoom now is in 100%

**Expected behavior**
Maintain zoom level

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Fedora 34
 - Installation package: rpm
 - Version: 1.0.9

**Additional context**
The problem is more noticeable on the Full HD screen, because texts looks very small

**Comment by jijojosephk** [comment]
@DiegoChajtur Thanks for bring this up. @IsmaelMartinez Is this new one introduced after #432 ?

**Comment by IsmaelMartinez** [comment]
I think this is more a feature request than a bug. We didn't do any work to
maintain the zoom level.

**Comment by jijojosephk** [comment]
ok. @IsmaelMartinez would you like to mark this as feature request?

**Comment by jijojosephk** [comment]
@IsmaelMartinez is yargs used only for command line arguments? Is it suitable for storing application settings? like save the settings dynamically?

**Comment by jijojosephk** [comment]
@DiegoChajtur We'll work on this and try to provide a fix.
