### ISSUE TITLE
teams-for-linux_1.0.9_amd64.deb contains a data.tar.xz that Debian 8/10 utilities can't cope with

### ISSUE THREAD

**Issue by whitpa** [IsmaelMartinez/teams-for-linux#449]
According to Debian utilities (both Debian v8 and Debian v10), release deb teams-for-linux_1.0.9_amd64.deb's content is "corrupt", although I'm able to access its contents just fine using 7-Zip on Windows.  It looks to me as though the deb's content may be triggering some obscure bug in Debian utilities (ar/ar-equivalent?), or perhaps there is some difference in handling of a sparse file(?).

Strangely, 7z.exe (x64) version 19.00 on Windows says that there is absolutely nothing wrong with teams-for-linux_1.0.9_amd64.deb (md5sum 86d5d264543c094c45f92a4e9d35ea0e, size 62136904 bytes) and can extract a data.tar.xz from it (md5sum cf7dac63e3fd8648d210af335f67934c, size 62133448 bytes) that everything I try agrees is perfectly fine.  However, if I use any Debian dpkg utility (e.g. dpkg or dpkg-deb) or ar (from binutils) on the exact same deb file, the data.tar.xz that is extracted has a different checksum and the utility declares it to be "corrupt":

```
# dpkg --version
Debian `dpkg' package management program version 1.17.27 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# dpkg -i teams-for-linux_1.0.9_amd64.deb
Selecting previously unselected package teams-for-linux.
(Reading database ... 31960 files and directories currently installed.)
Preparing to unpack teams-for-linux_1.0.9_amd64.deb ...
Unpacking teams-for-linux (1.0.9) ...
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive teams-for-linux_1.0.9_amd64.deb (--install):
 cannot copy extracted data for './opt/teams-for-linux/teams-for-linux' to '/opt/teams-for-linux/teams-for-linux.dpkg-new': unexpected end of file or stream
Processing triggers for mime-support (3.58) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Errors were encountered while processing:
 teams-for-linux_1.0.9_amd64.deb

# dpkg-deb --version
Debian `dpkg-deb' package archive backend version 1.17.27 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# dpkg-deb -x teams-for-linux_1.0.9_amd64.deb /tmp/foo
dpkg-deb (subprocess): decompressing archive member: lzma error: compressed data is corrupt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
dpkg-deb: error: subprocess tar returned error exit status 2

# ar --version
GNU ar (GNU Binutils for Debian) 2.25
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) any later version.
This program has absolutely no warranty.
# ar x teams-for-linux_1.0.9_amd64.deb data.tar.xz
# unxz --version
xz (XZ Utils) 5.1.0alpha
liblzma 5.1.0alpha
# unxz -t data.tar.xz
unxz: data.tar.xz: Compressed data is corrupt
# md5sum data.tar.xz /tmp/data.tar.xz
1f3100e6cbbf8295b92d56889a031c8d  data.tar.xz
cf7dac63e3fd8648d210af335f67934c  /tmp/data.tar.xz # <- extracted from same deb on Windows
```

**Comment by IsmaelMartinez** [comment]
Hi, that is strange. Can you check v1.0.8 and see what you get?

**Comment by whitpa** [comment]
teams-for-linux_1.0.8_amd64.deb is fine.  So are teams-for-linux_1.0.9_arm64.deb and teams-for-linux_1.0.9_armv7l.deb, BTW.  Only the 1.0.9 amd64 deb is affected.

It looks as though some fluke arrangement of bits in this particular file has triggered a bug in ... something.

**Comment by whitpa** [comment]
Hmmm ... I just re-downloaded teams-for-linux_1.0.9_amd64.deb and now get an MD5 checksum other than the one I provided above (6964aca5ad2858129120eb6b1990dcc9), and now Debian is able to decompress it OK.

I suspect that I must have been served a corrupted cached object, which has now been evicted from cache, or perhaps a particular load-balance back-end has a corrupted file.

Everything seems OK now.  I think we can safely declare this to be a temporary glitch and ignore it.

**Comment by IsmaelMartinez** [comment]
Glad to hear that. Ta
