### ISSUE TITLE
The SUID sandbox helper binary was found, but is not configured correctly

### ISSUE THREAD

**Issue by voidreamer** [IsmaelMartinez/teams-for-linux#450]
Hi I try to run on an old centos 7, I don't have root permissions.

Running on an old ` 3.10.0-862.9.1.el7.x86_64 `

`[71008:0727/102958.344169:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_teams-JgNlfL/chrome-sandbox is owned by root and has mode 4755.
Trace/BPT trap
`

Thank you

**Comment by IsmaelMartinez** [comment]
Hi, can you provide more details? Use the issue template. Are you sure this
is for teams for Linux and not the ms official one?? Thanks
