### ISSUE TITLE
Missing tray icon

### ISSUE THREAD

**Issue by LynHyper** [IsmaelMartinez/teams-for-linux#451]
**Describe the bug**
Teams successfully opens and a tray icon spawns, however, the tray icon is completely transparent with no visual icon. It can still be hovered over and clicked for a context menu.

**To Reproduce**
1. Run teams
2. See the tray icon with no visual icon; context menu is still working

**Expected behavior**
Tray icon should have the Microsoft Teams logo displayed

**Desktop**
 - OS: Arch Linux
 - Installation package: Flatpak
 - Version: 1.0.0 (As reported by Flatpak, was installed today; perhaps the Flatpak is still an older version?)

**Additional context**
This has been an issue for a while (about 1-2 months as a guess), but, I've only recently starting following projects and reporting issues for them.

**Comment by micwoj92** [comment]
Flatpak isn't really supported, package there isn't updated. I guess AUR would be good choice for you since you are on Arch.

**Comment by LynHyper** [comment]
Ah, is the Flatpak version no longer maintained?

**Comment by micwoj92** [comment]
Yes, look comments in https://github.com/IsmaelMartinez/teams-for-linux/issues/448

**Comment by LynHyper** [comment]
Alright then, I'll switch to the AUR version and report back if the issue's still present, thanks for your help!

**Comment by LynHyper** [comment]
Closing due to using an older version from Flathub.
