### ISSUE TITLE
Need for settings UI

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#462]
**Is your feature request related to a problem? Please describe.**
Not related to problem.

**Describe the solution you'd like**
I would like to make some changes which are currently done manually using user interface.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Adding this because custom title bar and multi tenant feature are under development. For those who does not want the custom title bar and need to have the system's default title bar, they can always change it through settngs.

**Comment by jijojosephk** [comment]
@IsmaelMartinez re-opening. We may have to have a GUI for adding custom backgrounds.

**Comment by IsmaelMartinez** [comment]
As for setting UI you mean another menu that has settings for the UI?

**Comment by jijojosephk** [comment]
May be from the menu->Settings that will show a window where we can add/remove custom images. Also the start up parameters can be listed and modified.

**Comment by IsmaelMartinez** [comment]
Hi @jijojosephk , if you can list the actions, I might be able to start adding them. The show/hide tray icon is fairly complex due how the code is structured.

When you mean parameters, do you mean all config options?

**Comment by IsmaelMartinez** [comment]
Closing due inactivity and not clear requirements. We have implemented some settings before so this issue might just be re-dundant
