### ISSUE TITLE
black screen while share screen in wayland base desktops

### ISSUE THREAD

**Issue by hzonuz** [IsmaelMartinez/teams-for-linux#463]
Hi! I use Arch Linux with gnome and when I share my entire screen I get a black screen because gnome is a wayland base desktop and if you want to share your screen in your app, your app must support pipewire but I think your app doesn't support it.
I'll be happy if you add this feature to your app and support pipewire too.

**Comment by sxiii** [comment]
👍🏻 for the request; I'm also in similar position and I use wayland on Arch (Garuda, Manjaro, Artix and Arch itself) as well as on Fedora. Wayland and Pipewire support for Teams is must-have.

**Comment by IsmaelMartinez** [comment]
This looks duplicated with https://github.com/IsmaelMartinez/teams-for-linux/issues/455 . Closing. Just follow the other thread . Ta
