### ISSUE TITLE
asks to install Linux App

### ISSUE THREAD

**Issue by mcarni** [IsmaelMartinez/teams-for-linux#464]
edit: 2021-09-27 corrected debian version

when i launch teams-for-linux for the first time after a fresh boot i get a strange behaviour

after typing in my credentials, I get the message below asking to download and install Linux App

![imgur link](https://i.imgur.com/5K3yxNp.png)

if i close the message about Linux App and i retry (sometimes 3-4 times) to launch teams-for-linux in the end i get it to start normally (even though sometimes i need to retype my credentials)

my systems is a debian 11 on an aspire e15

hope this helps, if logs or more info are needed please let me know

M

**Comment by jijojosephk** [comment]
@mcarni Could you add more details to it like OS, version etc? What happens when you click on 'Use the web app instead'?

**Comment by mcarni** [comment]
@jijojosephk sure, debian 11 stable (not 10 like i previously said, now corrected)
not sure about the point release, i don't have access for a couple of days (I am away for work and the wife uses it)
it is a KDE environment with pulseaudio

i have installed also the linux app from MS and dpkg -i the .deb they provide
but this has some other issues...

hope this helps

if more is needed please let me know, i will provide more info on my return
m

**Comment by jijojosephk** [comment]
Thanks @mcarni. @IsmaelMartinez what do you think the problem could be?

**Comment by IsmaelMartinez** [comment]
It's detecting it's a browser. Normally only happens on the 1st start. Just click the "use the web app" and it should not ask for it again. If it does, it will probably be permissions on `~/.config/teams-for-linux` folder

Those are my bets

**Comment by jijojosephk** [comment]
@mcarni Were you able to get it working?

**Comment by mcarni** [comment]
we have been testing it and so far it still happens even if I click on "use the web app"

i will check the permissons on the .config folder and let you know

M

**Comment by jijojosephk** [comment]
Thanks @mcarni and @mrkaczor83 for the valuable feedback. Glad to know that it works for you. If you can let us know your ideas as feature request we'll definitely try to implement. Closing this for now.
