### ISSUE TITLE
Select an application window to share from another workspace

### ISSUE THREAD

**Issue by keestux** [IsmaelMartinez/teams-for-linux#466]
With teams-for-linux it is possible to select an application window for sharing. Teams from Microsoft still can't do that. This has been on their TODO list for almost two years now.

So, teams-for-linux still has great value for Linux users.

My feature request is to be able to select an application window that is in another workspace. Right now that is not possible.

**Comment by jijojosephk** [comment]
@keestux It's a limitation with Electron at the moment. Hope that gets fixed in the future.

**Comment by jijojosephk** [comment]
@keestux, this seems impossible. Have a look [here](https://github.com/electron/electron/issues/20073)

**Comment by IsmaelMartinez** [comment]
closing due inactivity and because it seems blocked by electron. Sorry about that
