### ISSUE TITLE
wrong encoding when download dialog appears

### ISSUE THREAD

**Issue by damnms** [IsmaelMartinez/teams-for-linux#467]
**Describe the bug**
when i get a message with an attachment in teams chat (e.g. a pdf) and i try to download it, the download dialog appears but it has very strange symbols

**To Reproduce**
1. receive a message with any attachment
2. Click on download
3. the download dialog has wierd symbols instead of readable characters 

**Expected behavior**
the download dialog should have readable characters

**Screenshots**
![Bildschirmfoto_2021-10-02_11-15-16](https://user-images.githubusercontent.com/40913090/135710503-ef552afd-5090-4680-86fb-ffe03d0a005c.png)

**Desktop (please complete the following information):**
 - OS: fedora 35
 - Installation package snap
 - Version stable

**Additional context**
fedora 35 beta in snap
in the terminal i get this error/warning:
Gtk-Message: 11:14:51.625: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by IsmaelMartinez** [comment]
Hi, thanks for reporting. Check the closed issues. It's a snap
configuration issue. I will see when I am back online if I find the issue
for you.

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632002149
