### ISSUE TITLE
Open teams meeting link

### ISSUE THREAD

**Issue by vossim** [IsmaelMartinez/teams-for-linux#47]
It would be good to have an option to open web links for MS Teams meetings.

**Comment by IsmaelMartinez** [comment]
Hi, can you elaborate ?

if the links aren't working try using Ctrl+click. Some apps needs of this for it to open in the same environment.

**Comment by vossim** [comment]
Hi @IsmaelMartinez, what I meant are the links that sometimes get shared for a MS Teams meeting. They are in the form of https://teams.microsoft.com/l/meetup-join/19%3ameeting_ID%40thread.skype/0?context=SOME_CONTEXT.

These URLs give an option to launch the desktop client (which works for the official windows client), or to download the desktop client.

It would be great if these links could be pasted in teams-for-linux, to start the meeting.

**Comment by IsmaelMartinez** [comment]
Hi @vossim. Try pasting the link in the channel and then Ctrl+click it. 

That should do as in the browser, if its not supported in the browser it might not be easy/feasible to implement.

**Comment by vossim** [comment]
I'll give it a shot next time, and come back here

**Comment by IsmaelMartinez** [comment]
Yeah... there must be something failing but, at the moment, I can't really look into it. 

By the way, taht also seems to screw up my config settings for electron so, if the app stops working, just do a `rm ~/.config/teams-for-linux` and try again.

Apologies that I can't be more helpful at this moment in time. Busy life!

**Comment by IsmaelMartinez** [comment]
That stuff seems to be hard to debug as it opens in a new window. It might need a bit of a change of how we handle the new windows. Let me confirm my theory and see if I can get se tasks in here... Unfortunately it doesn't seem to be a small task so it might take a while.

**Comment by IsmaelMartinez** [comment]
Hi, 

I just commit a possible solution in the branch 0.1.14

At the end, was the solution seems to be a bit easier than I expected. 

The solution seems to be opening the meeting url in the same electron window. It does redirect you to the "download the app or open in browser" but takes you directly to the right place without needing to click anything.

Let me know how it works if you can test the branch 0.1.14. 

I will see if I can test it tomorrow at work but I will appreciate if you could also test it.

Otherwise, I might need to create a pre-release for you to test it.

Thanks!

**Comment by IsmaelMartinez** [comment]
Tested and it all seems to be fine. 

Released in version 0.1.14.

**Comment by vossim** [comment]
Tested today and it work fine now, thanks!

**Comment by wddossett** [comment]
I am on edge version 0.1.18 and I tried control click and it hangs on the initializing window... am I doing something wrong?

**Comment by IsmaelMartinez** [comment]
Hi, I am fairly sure this one should work without the Ctrl+click. Just clicking the link should work.

**Comment by emanuelbatista** [comment]
I'm not getting to open meeting link outside teams, could anyone help me with that?

**Comment by IsmaelMartinez** [comment]
Can you be more detail on the issue? The browser are you using? Linux flavour? Packaged version? and any other details? 

That helps on trying to find the issue. These issues are mostly a system configuration.

**Comment by emanuelbatista** [comment]
I tried open a link sent via Slack to me and it opened only on Chrome browser. I'm using the Chrome Version 76.0.3809.100 (Official Build) (64-bit), Ubuntu 18.04 and Team for Linux 0.7.0.

If you need anything else, just tell me.

**Comment by IsmaelMartinez** [comment]
You should try to open the following link in your chrome:
https://teams.microsoft.com/l/meetup-join/19%3ameeting_ID%40thread.skype/0?context=SOME_CONTEXT.

you should get a xdg-open dialog/question and, once you accept it, should then open the teams-for-linux app.

Otherwise, open a terminal and run:

```bash
xdg-open msteams://testme
```

That should focus your teams app or launch it.

If neither are working, I will recommend trying with another package (check the release page). I assume you are using snap and maybe didn’t register the handler. 

If not, you might need to configure your xdg-mime/open. Google around.

**Comment by emanuelbatista** [comment]
Both executions worked, but the teams' application didn't open the meeting into it, that way just has focused the teams' screen. 

I there was installed the teams' package from the Github release page.

**Comment by IsmaelMartinez** [comment]
Does it work when the app is already running? The flow is different once it is running or when is not. 

The code is in here (for the second instance/already running), in case you want to have a look: 
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L69

**Comment by emanuelbatista** [comment]
Sorry, I made a mistake.
I meant -> "Both executions worked, but the teams' application didn't open the meeting into it, that way just has focused the teams' screen."

I tested with the application opened and closed, and to both, the issue with only the focus the teams' screen continues.

**Comment by IsmaelMartinez** [comment]
hi @emanuelbatista, I am afraid then that extra work is needed in order to support that feature. Open an enhancement and describe the required solution. I am open to PRs but spend most of the time administrating this, so can't do much work on it. Thanks!

**Comment by sidhu1f** [comment]
As I had issues opening meeting links via browser and the (beta) ms teams client, I tried the teams for linux client which solves this issue. Thanks!

-sidhu1f

> Hi,
> 
> I just commit a possible solution in the branch 0.1.14
> 
> At the end, was the solution seems to be a bit easier than I expected.
> 
> The solution seems to be opening the meeting url in the same electron window. It does redirect you to the "download the app or open in browser" but takes you directly to the right place without needing to click anything.
> 
> Let me know how it works if you can test the branch 0.1.14.
> 
> I will see if I can test it tomorrow at work but I will appreciate if you could also test it.
> 
> Otherwise, I might need to create a pre-release for you to test it.
> 
> Thanks!
