### ISSUE TITLE
No meeting notifications in KDE

### ISSUE THREAD

**Issue by mrkaczor83** [IsmaelMartinez/teams-for-linux#470]
**Describe the bug**
I am receiving chat notifications but no meeting notifications. "'--enableDesktopNotificationsHack" doesn't help. Same behavior.

Also there is no sound notifications only KDE tray ones for all the events although I have turned them on.

The second issue might be related to https://github.com/wavebox/waveboxapp/issues/418

**To Reproduce**
1. Setup notification for all events – under settings, notifications
2. No notification for meetings 

**Expected behavior**
"Meetings start" notification like chat message one

**Desktop (please complete the following information):**
 - OS: Debian 11 on KDE
 - Installation package deb
 - Version 1.0.12

**Comment by mrkaczor83** [comment]
There is no sound because if electron implementation ... but maybe we can have simple GUI notification like for chat?

**Comment by IsmaelMartinez** [comment]
can you check if this is still the case in 1.0.24? thanks!

**Comment by floscher** [comment]
@IsmaelMartinez Yes, this is still an issue, in my case on Ubuntu Gnome 20.04. Other notification types (like calls and chat notifications) are working, but meeting notifications are not.

**Comment by opalmay** [comment]
I'm using Bspwm with dunst for notifications and I'm facing the same issue.
With the official client, message notifications show as native dunst ones, but meetings and calls as custom team ones. Just using the web client in any browser acts like this client, not showing meeting notifications at all. Which makes me think it was just not implemented on microsoft's side and this project probably can't do much about it... :cry:

**Comment by danielgsanz** [comment]
Hi there! Do you know when Microsoft will implement this feature? It's very annoying to no have this notification, as we have in the client. Thank you for all your effort in this project :)

**Comment by opalmay** [comment]
> Hi there! Do you know when Microsoft will implement this feature? It's very annoying to no have this notification, as we have in the client. Thank you for all your effort in this project :)

I would hope this year, because the official electron client is being deprecated in favor of the web app becoming a PWA. But there's no knowing with Microsoft

**Comment by jijojosephk** [comment]
> Hi there! Do you know when Microsoft will implement this feature? It's very annoying to no have this notification, as we have in the client. Thank you for all your effort in this project :) 

I'm breaking my head over this. 😁 Need to reverse engineer the js implementation from MS. Tired!

I wonder when they release pwa what happens to Mac and Windows clients. It could possibly break this app too. Only time will tell.

**Comment by jijojosephk** [comment]
Looks like the communication is happening through websocket. Unable to debug or find the event that updates the meeting details.

**Comment by jijojosephk** [comment]
Hooray! Finally, I've found something. It will come out soon. :smile:

**Comment by jijojosephk** [comment]
Fixed in `1.0.44`. Re-open if it's not fixed.

**Comment by jijojosephk** [comment]
I had tested this on Arch KDE. Plasma should be same for all right? Haven't tested on Kubuntu. Can you confirm if this is the scenario.

1. There's a meeting on your calendar
2. Someone starts the meeting.
3. You should see that 'Meeting started'

**Comment by mrkaczor83** [comment]
O boy, o boy, o boy,  I will test it tomorrow :) thanks!

**Comment by jijojosephk** [comment]
This is how it looks on Ubuntu Budgie. With KDE and the default setup, it should show bottom right.

![image](https://user-images.githubusercontent.com/11662148/195055249-b1a94ec8-f0ff-437a-8c49-d4a8c50dfc2c.png)

**Comment by cs96and** [comment]
It's working for me in KDE with the latest version.  However, I keep receiving meeting popups when I am not expecting them (I have no meetings scheduled at that time).  Would it be possible to at least display the name of the meeting in the popup?

**Comment by FloEdelmann** [comment]
@jijojosephk Yes, the scenario is exactly as you described. Note that it is a recurring meeting; maybe that makes a difference?

**Comment by jijojosephk** [comment]
@cs96and that's an issue. The logic does not validate the date and time. Purely based on the serviceworker message push. I've seen the problem too. But at least now we know what can be done. I had to go through each and every service objects written by Microsoft to find which event triggers for the notification. Was a herculean task.

**Comment by jijojosephk** [comment]
@cs96and can you check this when version `1.0.45` is out?

**Comment by cs96and** [comment]
Is this in the pre-release 1.0.45, or do I need to wait for a proper 1.0.45?

**Comment by jijojosephk** [comment]
@cs96and it's official release now. snap, flatpak, and here. you may try.

**Comment by FloEdelmann** [comment]
Sorry, I didn't try it with the `--enableDesktopNotificationsHack` CLI option. With that enabled, it works now. Thanks for fixing!

**Comment by jijojosephk** [comment]
@FloEdelmann This change has no connection with the flag. I wonder what's the issue at your side. Still can't figure out.

**Comment by FloEdelmann** [comment]
If there's anything I can try, let me know.

**Comment by mrkaczor83** [comment]
@FloEdelmann try maybe send any notification from CLI, for me all works perfectly but I have no big teams so additional notifications are not an issue so much :)

**Comment by FloEdelmann** [comment]
@mrkaczor83 I don't know what you mean with sending notifications from the CLI. Meeting notifications are working fine for me now with the `--enableDesktopNotificationsHack` flag enabled. So from my side, everything is fine; but apparently it should also be fixed without the flag.

**Comment by mrkaczor83** [comment]
Aa sorry, I haven't notice your last comment
