### ISSUE TITLE
Popup when opening application: Allow snap "teams-for-linux" to change "default-url-scheme-handler" subproperty "msteams" to "teams-for-linux_teams-for-linux.desktop"

### ISSUE THREAD

**Issue by GabLeRoux** [IsmaelMartinez/teams-for-linux#471]
**Describe the bug**
Every time we open this snap on Ubuntu 20.04, a popup appears with the following message:

> Allow settings change?  
> Allow snap "teams-for-linux" to change "default-url-scheme-handler" subproperty "msteams" to "teams-for-linux_teams-for-linux.desktop"

**To Reproduce**
1. `snap install teams-for-linux`
2. open Teams

**Expected behavior**
Could prompt for that window, but only once

**Screenshots**

![image](https://user-images.githubusercontent.com/1264761/138115711-85be4bc6-2acc-4a55-aec5-b47e9488bd3b.png)

**Desktop:**
 - OS: Ubuntu 20.04
 - Installation package: `snap`
 - Version: `1.0.10`

**Additional context**
This was also asked here:  
https://askubuntu.com/questions/1334691/how-to-prevent-microsoft-teams-allow-settings-change-dialog-on-startup

The provided solution is to use `teams` or `teams-insiders` snaps released by `msteam`. 

I don't expect this to really get fixed since Readme says:

> This project is in maintenance mode only.

I only created this issue to document this bug and bring visibility :)

**Comment by loris-av** [comment]
Hi, I have tested @GabLeRoux solution but, doesnt work for me, when I launch from terminal, I have this message, maybe something missing for XFCE DE ?

```
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "msteams" setting: xdg-settings: default-url-scheme-handler not implemented for xfce
Gtk-Message: 13:05:19.445: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:05:19.445: Failed to load module "xapp-gtk3-module"
```

**Comment by JanSurft** [comment]
I always get the popup each time starting `teams-for-linux`. In the terminal the following lines show up, from which only the first line seems to be relevant:

```shell
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "msteams" setting: exit status 4

(teams-for-linux:16710): Gtk-WARNING **: 07:19:00.002: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(teams-for-linux:16710): Gtk-WARNING **: 07:19:00.005: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(teams-for-linux:16710): Gtk-WARNING **: 07:19:00.005: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
```

It also keeps happening when I do:

```
~ sudo snap install --edge teams-for-linux
teams-for-linux (edge) 1.0.49 from ismael (ismaelmartinez) installed
```

**Comment by reidar-cederqvist** [comment]
I get the same issue, and if I check with xdg-settings I get that the right application is already set
```
$ xdg-settings get default-url-scheme-handler msteams
teams-for-linux_teams-for-linux.desktop
```

**Comment by Am0rphous** [comment]
Hi! I get the same error when using Kali GNU/Linux Rolling (2023.1), kernel 6.1.0-kali7-amd64 and **snap version 2.59.1**. Im using **teams-for-linux 1.0.71**.

I am not sure this is relevant, but after running  `snap run teams-for-linux &` in the terminal, I get following error messages:
````
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" subproperty "msteams" setting: xdg-settings: default-url-scheme-handler not implemented for xfce

(teams-for-linux:290242): Gtk-WARNING **: 09:02:25.118: Failed to parse /etc/xdg/xdg-kali-purple/gtk-3.0/settings.ini: Permission denied

(teams-for-linux:290242): Gtk-WARNING **: 09:02:25.118: Failed to parse /etc/xdg/gtk-3.0/settings.ini: Permission denied

(teams-for-linux:290242): Gtk-WARNING **: 09:02:25.118: Failed to parse /etc/xdg/gtk-3.0/settings.ini: Permission denied
Gtk-Message: 09:02:25.148: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 09:02:25.148: Failed to load module "colorreload-gtk-module"
[290242:0426/090225.801466:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[290242:0426/090225.801589:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[290242:0426/090225.801615:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[290242:0426/090225.801652:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[290242:0426/090225.801673:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Driver does not support the 0x46a6 PCI ID.
libGL error: failed to create dri screen
libGL error: failed to load driver: iris
Driver does not support the 0x46a6 PCI ID.
libGL error: failed to create dri screen
libGL error: failed to load driver: iris
[291254:0426/090226.321806:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Driver does not support the 0x46a6 PCI ID.
[291270:0426/090226.452186:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to se
````

I checked the three files and they all have the same permission `-rw-r--r-- ` which makes me believe the problem relies with snap(?).
