### ISSUE TITLE
Couldn't load your calendar. Let's give it another try. 

### ISSUE THREAD

**Issue by ndnihil** [IsmaelMartinez/teams-for-linux#472]
**Description**
Calendar worked flawlessly until recently, now it errors with "Couldn't load your calendar" message, and debug console throws corrupt calendar bundle errors for angular.

0.2-angular-jquery.min-eee9041.js:114 2021-10-21T02:27:55.773Z Corrupt calendar bundle
0.2-angular-jquery.min-eee9041.js:114 2021-10-21T02:27:55.773Z Parsing calendar bundle promise failed. Error: Corrupt calendar bundle
0.2-angular-jquery.min-eee9041.js:114 2021-10-21T02:27:55.775Z Error in initializing calendar-bridge: Corrupt calendar bundle

**To Reproduce**
Click on the calendar app.

**Expected behavior**
Expect calendar to load. Calendar does not load.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian
 - Installation package snap
 - Version 1.0.10/1.0.12

**Additional context**

**Comment by jijojosephk** [comment]
@ndnihil @kafene Happy that you have the working calendar with deb and AppImage. Strangely though, It's working for me in snap as well.

**Comment by jijojosephk** [comment]
Closing this issue as the reporter confirmed working in another package. @ndnihil I still recommend you to use new flatpak build. Closing this now. Feel free to re-open the problem persisits.
