### ISSUE TITLE
Event indicator in tray icon

### ISSUE THREAD

**Issue by gwozniak** [IsmaelMartinez/teams-for-linux#49]
Hi, I used to work with ivelkov's teams, by myself changed the UA to MS Edge and added boot params to chromium beneath to allow video chat. Yes I lost metioning ability  and all this topic are known and have fixes in you code. But there is one thing which I'm missing on you version of teams and it is tray icon indication of new events (new message or metions).
I ivelkov's version when new message appeared the right up corner of tray icon was turning on red.
It is very usefull feature when using fluxbox which doesn't have notification mechanism.
Could you add this improvement ?
![teams_idle](https://user-images.githubusercontent.com/848953/53413095-65c40400-39cb-11e9-829a-f84154f84ea5.png)
![teams_new_msg](https://user-images.githubusercontent.com/848953/53413096-65c40400-39cb-11e9-9292-7f69397e12f1.png)

**Comment by IsmaelMartinez** [comment]
Hi,

I think that is related to #42.

Check the following comment.

https://github.com/IsmaelMartinez/teams-for-linux/issues/42#issuecomment-458305097

It might be another closed issue, but I am fairly certain is number #42.

Hope helps
