### ISSUE TITLE
Build fail on nodejs 17

### ISSUE THREAD

**Issue by micwoj92** [IsmaelMartinez/teams-for-linux#508]
**Describe the bug**
teams-for-linux fails to build with nodejs 17. Low priority but something to address in future.

**To Reproduce**
1. get source code
2. try to build 
3. error

**Expected behavior**
successful build

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Installation package source
 - Version 1.0.20 and git

**Additional context**
```
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ electron-builder install-app-deps
  • electron-builder  version=22.13.1
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=spellchecker@3.7.1 platform=linux arch=x64
  • rebuilding native dependency  name=spellchecker version=3.7.1
  ⨯ cannot execute  cause=exit status 1
yarn run v1.22.17
$ node-gyp rebuild
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    
                    errorOut=gyp info it worked if it ends with ok
    gyp info using node-gyp@8.3.0
    gyp info using node@17.3.0 | linux | x64
    gyp info find Python using Python version 3.10.1 found at "/usr/bin/python3"
    gyp info spawn /usr/bin/python3
    gyp info spawn args [
    gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/micwoj92/teams-for-linux/src/teams-for-linux-1.0.20/node_modules/spellchecker/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/micwoj92/.electron-gyp/15.3.0/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/micwoj92/.electron-gyp/15.3.0',
    gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/home/micwoj92/.electron-gyp/15.3.0/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/home/micwoj92/teams-for-linux/src/teams-for-linux-1.0.20/node_modules/spellchecker',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:261:16)
    gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    gyp ERR! System Linux 5.15.10-arch1-1
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/micwoj92/teams-for-linux/src/teams-for-linux-1.0.20/node_modules/spellchecker
    gyp ERR! node -v v17.3.0
    gyp ERR! node-gyp -v v8.3.0
    gyp ERR! not ok 
error Command failed with exit code 1.
    
                    command=/usr/bin/node /usr/lib/node_modules/yarn/bin/yarn.js run install
                    workingDir=/home/micwoj92/teams-for-linux/src/teams-for-linux-1.0.20/node_modules/spellchecker
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by IsmaelMartinez** [comment]
spellchecker is always a pain.... I suspect either we need to wait until they upgrade to node17 or see if there is a newer implementation in node17 of the spellchecker. Thanks for reporting!

**Comment by janvanveldhuizen** [comment]
@micwoj92 You said: Low priority but something to address in future.

I am getting this issue when installing teams-for-linux using yay.
How do I resolve it?

**Comment by micwoj92** [comment]
Read pinned comments on AUR page...

Also you must have modifed PKGBUILD or something, because if you had used
yay then you should get prompt like
```
:: There are 3 providers available for nodejs<17:
:: Repositorycommunity
    1) nodejs-lts-erbium 2) nodejs-lts-fermium 3) nodejs-lts-gallium
```

which makes it not possible to use node17 this way

pt., 14 sty 2022 o 11:14 Jan van Veldhuizen ***@***.***>
napisał(a):

**Comment by CasperOng** [comment]
Same Error. Can anyone know how to install a support version of node js or how to build on the node 17 environment

**Comment by micwoj92** [comment]
> Same Error. Can anyone know how to install a support version of node js 

Read. See post above to check names of what package you need to install (on Arch Linux)....

**Comment by IsmaelMartinez** [comment]
Any luck trying to fix this? it will be good to get node17 and see if that sorts some of the issues.

Might need some code changes specially around the spellchecker . Thanks in advance

**Comment by jijojosephk** [comment]
I'm not what can be done. Looks like electron follows node LTS. Electron 18 still depend on 16 LTS.

**Comment by micwoj92** [comment]
Hello, why was this closed?


W dniu sobota, 21 maja 2022 Jijo Joseph ***@***.***>
napisał(a):

**Comment by IsmaelMartinez** [comment]
apologies, reopened. Feel free to put a PR if you can/know how to upgrade. Seems like it would require quite a bit of extra work

**Comment by micwoj92** [comment]
Thanks for the reopening. You have previously mentioned it is issue with spellchecker, it is maintained by atom team and atom will stopped being developed on 15th december of this year https://github.blog/2022-06-08-sunsetting-atom/
So probably unless someone else forks it then we are out of luck.

**Comment by jijojosephk** [comment]
@micwoj92 I had to remove spellchecker due to incompatibility. You should be able to complete the build without errors now.

**Comment by micwoj92** [comment]
Weirdly enough I tried building version 1.0.20 using nodejs 18.7.0 and it worked? Could it have been possibly a node regression or something?

What was the reason behind removal? Is it not compatible with electron 20?

**Comment by jijojosephk** [comment]
@micwoj92 after upgrading to latest electron, the build was failing and only reason was spellchecker, so removed it.
