### ISSUE TITLE
Does not terminate related processes after closing app

### ISSUE THREAD

**Issue by luis-alves** [IsmaelMartinez/teams-for-linux#509]
**Describe the bug**
After clicking x for closing the app, the related processes continue running. The official app terminates all related processes correctly.

**To Reproduce**
1. Click on close window to terminate, and not go to background.
2. open system monitor and search for teams
3. wonder why the processes are still there!

**Expected behavior**
After closing the window the processes should terminate, and no go to the background, or at least have the possibility to choose it like the official app does, in settings

**Screenshots**
No applicable

**Desktop (please complete the following information):**
 - OS: Fedora 35 - Gnome
 - Installation package: Flatpak
 - Version: 1.0.20

**Additional context**
The option to terminate all related processes running seems to be missing from settings. Is this by design?

**Comment by micwoj92** [comment]
To terminate all processes right click tray icon and close quit.

**Comment by luis-alves** [comment]
> To terminate all processes right click tray icon and chose quit.

I must use extension to show the tray icon, and it shouldn’t be that way.

**Comment by micwoj92** [comment]
Ah okay, I didnt know you use that way.

**Comment by IsmaelMartinez** [comment]
Hi, that is intended. If you prefer to close the app on clicking the cross button, you can just use the --closeAppOnCross option. More info in the Readme (under config section). It explains how to create a file etc so you don't need to pass the option always. Hope helps.

**Comment by luis-alves** [comment]
Thank you @IsmaelMartinez  for you patience with me.
