### ISSUE TITLE
Disallow multiple instances

### ISSUE THREAD

**Issue by HarlemSquirrel** [IsmaelMartinez/teams-for-linux#51]
I've noticed some issues around multiple instances of this app such as clicking links has no affect.

**Comment by HarlemSquirrel** [comment]
This should do it.
https://github.com/electron/electron/blob/v0.36.10/docs/api/app.md#appmakesingleinstancecallback

**Comment by IsmaelMartinez** [comment]
This tends to close the issues when a merge request is accepted... that most of the cases is ok but not now. 

Thanks a lot for finding the issue and fixing it! I will try to add a couple of more changes that are #21 (a neater way to have video conference) and probably also #50 (if it doesn't take much of my time) 

Thanks again and I hope you are finding this wee app useful.

**Comment by IsmaelMartinez** [comment]
Ok, its been now released as part of 0.1.15. Thanks again!!

**Comment by HarlemSquirrel** [comment]
My please! I am happy to help. Thank you for maintaining this awesome app!
