### ISSUE TITLE
Request for Pacstall Support

### ISSUE THREAD

**Issue by Zahrun** [IsmaelMartinez/teams-for-linux#510]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing [pull request](https://github.com/pacstall/pacstall-programs/pull/603) to add teams-for-linux to our repository.

Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.

**Comment by jijojosephk** [comment]
@IsmaelMartinez what do you think? I'm quite busy and I think you're too. Please confirm so that @Zahrun and co and take care of this. Thanks @Zahrun  for letting us know about it. @IsmaelMartinez is the owner of the repo and he will soon respond.

**Comment by IsmaelMartinez** [comment]
Hi @Zahrun, yes, it will be great if you guys can maintain it. Feel free to update the readme to put a link to it (like the aur one) so if people lands in here, they can get the pacstall package if they want.

**Comment by Zahrun** [comment]
Hi @IsmaelMartinez,  I've created a MR to include Pacstall `teams-for-linux` package link to the readme https://github.com/IsmaelMartinez/teams-for-linux/pull/511

Thank you for this project!
It comes handy when I have issues with the official client.
