### ISSUE TITLE
Background effects possible in Chrome

### ISSUE THREAD

**Issue by agncr** [IsmaelMartinez/teams-for-linux#518]
**Is your feature request related to a problem? Please describe.**
In Chrome/Chromium (not tested with other browsers) it's possible to change background effects (blur/pictures/...) since a time. Would it be possible to add the same functionality to this client?

**Describe the solution you'd like**
Clicking on the three dots it should show the show background effects menu.

**Describe alternatives you've considered**
The feature is working with chrome and using teams in web browser

**Comment by micwoj92** [comment]
This could be fixed by
https://github.com/IsmaelMartinez/teams-for-linux/pull/515

comment by @herbiejhopkins 
"For me this seems to enable virtual/blured background support which is nice to have. It may just be the user agent bump that did this."
