### ISSUE TITLE
Tray icon notification badge

### ISSUE THREAD

**Issue by matusaurio** [IsmaelMartinez/teams-for-linux#524]
**Describe the bug**
Tray icon notification badge only works with the default icon theme but when I choose a different one, presumably with its own teams icon, the notification badge it's not shown.

**To Reproduce**
1. Select a different icon theme (e.g., Gnome Tweaks/Appearance/Icons)
2. See the notification badge disappear because a different icon is now in place.

**Expected behavior**
Either force the default tray icon or separate the notification badge from the tray icon.

**Screenshots**
Default icon theme
![teams_default](https://user-images.githubusercontent.com/6020173/159269870-02955b93-bb4e-4c98-a9c2-2ac0695ab175.png)

Numix circle icon theme (not showing the notification badge)
![teams_numix_circle](https://user-images.githubusercontent.com/6020173/159269889-9b1d7ab3-2aee-415a-8d5e-16548a9a5178.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS x86_64
 - Installation package: snap, deb
 - Version: 1.0.24

**Comment by jijojosephk** [comment]
@matusaurio I'm not sure this can be fixed because teams-for-linux is the binary name and it's not explicitly added in the theme by the theme developer. Isn't it @IsmaelMartinez  ?

**Comment by IsmaelMartinez** [comment]
Dunno enough about that area on the os part. I suspect there might be some link missing between the two. You could try editing the icon and then packaging it. Not tried changing the icon after build. 🤔

**Comment by IsmaelMartinez** [comment]
closing due inactivity. do ping if needs re-open. Thanks
