### ISSUE TITLE
Sign-in Error.

### ISSUE THREAD

**Issue by CasperOng** [IsmaelMartinez/teams-for-linux#527]
**DISCLAIMER: IT COULD BE MY PROBLEM.**
"We couldn't sign you in. Please try again." Infinite loop.

**To Reproduce**
1. Open terminal. 
2. Type `teams-for-linux`
3. Press Enter.
4. Enter Email
5. Enter Password.
6. Click on yes
7. See the error

**Expected behavior**
Login
 
**Screenshots**
Nah I think you understand.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - AUR

**Additional context**
N/A

**Comment by IsmaelMartinez** [comment]
Can you check the known issues section? Rarely, if the app crashes, it can
leave the config folder ina odd state.

Otherwise check closed issues, some had that problem due their IT network
configuration.

Hope helps

**Comment by IsmaelMartinez** [comment]
closing due inactivity. Do ping to re-open if required
