### ISSUE TITLE
Teams often segfaults on native Wayland (electron#32436)

### ISSUE THREAD

**Issue by kon14** [IsmaelMartinez/teams-for-linux#528]
This is technically an [Electron bug](https://github.com/electron/electron/issues/32436) that's already resolved upstream (fix available in Electron 17), but I've been wishing to open up an issue about it for anyone else stumbling upon it.

Basically, there's a race condition related to certain leftover X11 code that causes the app to crash while running as a native Wayland client.

It happens mostly on start, therefore it may segfault twice or thrice before actually starting succesfully, but from then on it mostly works.
I say mostly as certain ui interactions still cause it to segfault every now and then, but it's pretty uncommon and either way it's most likely all due to that upstream issue.

I just spam restart it till it pushes through, but for anyone else experiencing it that's less patient about it, using Teams through Xwayland should work fine until there's an Electron 17 update.

**Comment by Mushoz** [comment]
Electron 17.x.y also supports Wayland window decorations (https://github.com/electron/electron/pull/29618), which is a huge improvement as well. So upgrading to Electron 17 or even 18 would be a big improvement in multiple ways :)

**Comment by IsmaelMartinez** [comment]
Hello, I invite you people to open a PR. I will happily help as much as I can to get it over the line. 

I believe the main problem will be with the spellcheck but screen-sharing might also break. Talking from previous experiences. Thanks in advance.

**Comment by jijojosephk** [comment]
@kon14 please check when the new one is released. Upgrade to v20.0.0 is complete.

**Comment by jijojosephk** [comment]
@kon14 can you check the latest version. It's been upgraded to `20.0.1`

**Comment by jijojosephk** [comment]
Now this app is based on Electron `20.0.2` and I assume this is fixed.
