### ISSUE TITLE
teams crashes at startup on newest sway (wayland) compositor

### ISSUE THREAD

**Issue by nickjwhite** [IsmaelMartinez/teams-for-linux#529]
When starting teams-for-linux with --ozone-platform=wayland with sway 1.7, it doesn't start, with this error message:
  INFO: Running under Wayland, switching to PipeWire...
  interface 'wl_output' has no event 4
  Trace/breakpoint trap

This is due to a bug with electron, fixed upstream, where it binds to whatever is the newest wayland interface available, rather than the latest one it knows how to use. The fix backporting issue is ://github.com/electron/electron/issues/32487 and hasn't been backported yet, as far as I can tell, but hopefully will be soon.

**Comment by jeremiah-miller** [comment]
Hopefully the official teams client updates to a fixed version of electron soon but if not, it would be nice if this electron wrapper used it

**Comment by IsmaelMartinez** [comment]
Hello. Unfortunately I don't have the time nor resources to update the
electron version, but would be happy to help/support any of you guys doing
the upgrade.

I suspect only the speelchecker might give some trouble, but nothing that
can't be solved.

If anyone can, just open a PR and fire any questions. Will try to
support/help as much as possible.

**Comment by jijojosephk** [comment]
@nickjwhite can you tell me which flavour of linux you're using. For me to reproduce I would like to use the same.

**Comment by jijojosephk** [comment]
@nickjwhite and @jeremiah-miller can you check the latest version? Upgraded electron to `20.0.1`

**Comment by nickjwhite** [comment]
@jijojosephk I just checked with 1.0.26, and can confirm it's working fine for me. Thanks very much for upgrading the Electron version to fix it! (Also, sorry I missed your previous message regarding what Linux I'm using).

**Comment by jijojosephk** [comment]
@nickjwhite is #585 something you can test and report?
