### ISSUE TITLE
v0.1.15: several channels + all chats + activity feed are empty

### ISSUE THREAD

**Issue by mpruefer** [IsmaelMartinez/teams-for-linux#53]
I just switched from 0.1.14 to 0.1.15 (the tag "v0.1.15" state) like this:
```
yarn run dist:linux:snap
sudo snap install dist/teams-for-linux_0.1.15_amd64.snap --dangerous

```
After starting up, several channels and all recent chats are empty, additionally my activity feed is nearly empty.
Switching back to 0.1.14 resp. using the web client resolves the problem.

Using Ubuntu 18.04 here.

**Comment by IsmaelMartinez** [comment]
Ha e you tried https://github.com/IsmaelMartinez/teams-for-linux/blob/master/README.md#no-history ?

**Comment by mpruefer** [comment]
Yes, I deleted ~/.config/teams-for-linux, but then Teams showed just a completely white window saying "Service unavailable". When I removed all files from that dir except _Preferences_, Teams is able to start again, but still all the chats etc are empty.

**Comment by IsmaelMartinez** [comment]
Can you:
* Try with the snap version in the release page
https://github.com/IsmaelMartinez/teams-for-linux/releases
* Remove the full ~/.config/teams-for-linux

If you get a white screen try "refreshing" the screen. Sometimes the 1st load is a bit temperamental (I thought I had fix that)

The "no history" issue use to present itself when changing the user agent. Version 0.1.15 has changed the user agent to only use Chrome, so it does smell that will be the case/issue. 

Let me know how you get on with it.

**Comment by mpruefer** [comment]
Did that. Now I don't get the white screen anymore, but it's the same behaviour as when I built the 0.1.15 snap by myself, the chats are empty.

**Comment by mpruefer** [comment]
And what's also suspicious: even when running Teams then, the directory ~/.config/teams-for-linux does *not* get recreated!

**Comment by IsmaelMartinez** [comment]
I don't really use snap nor can. There is a strange behaviour in my company setup that locks people out of the network is we install snap packages.

For that reason, I don't think I will be able to help you much more... might I suggest trying with another package type?

Maybe it is related to the "confinement" snap security model. https://docs.snapcraft.io/snap-confinement/6233 . Perhaps you need to add something like with the camera: https://github.com/IsmaelMartinez/teams-for-linux#use-camera-using-the-snap-build

Apologies, but I might need to wait for someone else to help as I can't debug snap. @julian-alarcon did all the snap integration so he might be able to help!?

**Comment by mpruefer** [comment]
Okay, thank you for that hint! Of course I don't depend on using the snap packaging. I now installed the deb package and everything's fine, so you can close this issue.

**Comment by julian-alarcon** [comment]
Hi @mpruefer I got the same error since version 0.1.15, master and 0.1.15 I was checking which version maybe bring the issue, version 0.1.14 is OK.
Checking the repo I found that since commit a00625330de01ec09e2bd360d854186c945a351c the error is present, BUT maybe is something related with old config files, as I removed teams, configuration files and now 0.1.15, 0.1.16 and master are working with no issues, please remove completely Teams and reinstall it.

`sudo snap remove teams && rm -rf /home/$HOME/snap/teams`
