### ISSUE TITLE
spellChecker issue / request

### ISSUE THREAD

**Issue by alfredoivan** [IsmaelMartinez/teams-for-linux#530]
**Is your feature request related to a problem? Please describe.**
spellcheck option not working:
[](https://user-images.githubusercontent.com/5880102/158060677-b5eb0e0c-ff70-4703-85a5-383e6b4187a4.png)program version:
teams-for-linux-1.0.24.AppImage

command line arguments:
"--rightClickWithSpellcheck=true"

configFile = { closeAppOnCross: false, rightClickWithSpellcheck: true }

With this configuration, right click does nothing.
_
Other test scenario:
program version:
teams-for-linux-1.0.24.AppImage

command line arguments:
"--rightClickWithSpellcheck=false"

configFile = { closeAppOnCross: false, rightClickWithSpellcheck: false }

Result: same behaviour, right click does nothing .
Also MS Teams options doesn't allow activate / deactivate spell check:
_
I know for sure the config file is being read because of debug info on terminal, and because "closeAppOnCross" works properly.

**Describe the solution you'd like**
Enable / disable spell check option.

**Additional context**
In the index.js
![image](https://user-images.githubusercontent.com/5880102/162574561-c75a5b36-852c-409b-995b-41404ccb9e8f.png)
Problem is that it could be better worded:
- enableSpellCheck
and
- enableRightClick
would be the options.
_
And in this part, an if should be added to isMisspelled:
![image](https://user-images.githubusercontent.com/5880102/162574601-451a8930-83fb-46e6-b777-4a23886e7521.png)
if (!spellcheckenabled) {
    return false;
}

**Comment by IsmaelMartinez** [comment]
Hello and thanks for reporting

Can you check if this works with another package? Like dev or rpm.

Thanks
