### ISSUE TITLE
Unable to share screen while on Fedora Silverblue 36 with wayland session

### ISSUE THREAD

**Issue by luis-alves** [IsmaelMartinez/teams-for-linux#533]
While using Fedora Silverblue 35, I was able to share my screen or window without issues. Since rebasing to Fedora Silverblue 36, still with Wayland, I can't, but with X11 session it is possible.

There a similar issue, I think, with the [Ubuntu distribution.](https://github.com/IsmaelMartinez/teams-for-linux/issues/526)

 - OS: Fedora Silverblue
 - Installation package: Flatpak 
 - Version: 1.0.24

**Comment by IsmaelMartinez** [comment]
Hi @luis-alves, thanks for reporting the issue. 

I believe this is blocked until someone upgrades the node version of this project. I invite you to try and I am happy to help, but can't lead this unfortunately due time.

**Comment by kon14** [comment]
In the meantime you could run this with `flatpak run com.github.IsmaelMartinez.teams_for_linux --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer`

Only thing is, there are still some X11 bits being expected in this version of Electron that result in a race condition, meaning it won't always be brought up in the first run and it'll sometimes crash while attempting to download files.
With that being said, if you run this twice or thrice in a row you should be capable of logging in and more or less have a decent experience with it.

**Comment by jijojosephk** [comment]
I tested on Fedora 36 GNOME it's working. Could you share some more detail?

**Comment by jijojosephk** [comment]
Sorry, I did not notice it was flatpak. I'll have a look.

**Comment by jijojosephk** [comment]
@luis-alves I still found screen sharing working on Fedora 36 GNOME (wayland) however the version you're having is 1.0.24 for that I see the popup comes twice. when you click on screen sharing. Seems like a problem with the electron version. There's a new version out `1.0.25` with the latest stable electron `v20.0.0`. Could you give try?

**Comment by jijojosephk** [comment]
Latest build (`1.0.25`) fixes the issue. Hence closing this defect.
