### ISSUE TITLE
Leaks X11 client connections, eventually causing screen sharing failure

### ISSUE THREAD

**Issue by cpfeiffer** [IsmaelMartinez/teams-for-linux#534]
I'm on X11 and screen sharing works well in general. However, every time I start and stop screen sharing, an X client connection is leaked. You can verify it with
`lsof +c0 /usr/lib/x86_64-linux-gnu/libX11.so 2>/dev/null | cut -d' ' -f1  | grep teams-for-linux  | wc -l`
(credits go [here](https://bbs.archlinux.org/viewtopic.php?pid=1611548#p1611548)). The connections counted with `wc -l` increases with every screen sharing start.

There may be further "leaks", because right after starting teams-for-linux, there are already 11 client connections by it, which is unfortunate, because I sometimes even hit the hardcoded MAXCLIENTS limit of Xorg. In this case I see the following in the output of teams-for-linux, when trying to start screen sharing:
`Maximum number of clients reached[2:0525/093349.717641:ERROR:shared_x_display.cc(38)] Unable to open display`

**To Reproduce**
1. Start teams-for-linux
2. In a terminal, run `lsof +c0 /usr/lib/x86_64-linux-gnu/libX11.so 2>/dev/null | cut -d' ' -f1  | grep teams-for-linux  | wc -l`
3. Be surprised about the high number being reported (should ideally be close to 1)
4. Start screen sharing
5. Run lsof again, number will have increased by 1
7. Stop screen sharing
8. Run lsof again, number is still initial + 1

**Expected behavior**
The number of X11 client connections should ideally close to 1, but at least not increase over time.

**Desktop:**
 - OS: Debian sid, KDE
 - Installation package: AppImage, used with firejail
 - Version: 1.0.24

Thanks a lot for providing this! :heart:

**Comment by IsmaelMartinez** [comment]
Hi @cpfeiffer , thanks for reporting. Unfortunately I have no time for this application. I think this might be related to the node version, but maybe I am wrong. Can you check if you get the same issue with another package manager? (just to rule out the AppImage) Thanks in advance

**Comment by jijojosephk** [comment]
This happens only in release versions. Need to figure out why.

**Comment by jijojosephk** [comment]
My understanding after playing with it for sometime is that AppImage works the same way as debug mode. When the app is launched the X11 connection shoots up to 8 @dev-hanz-ops and @cpfeiffer

**Comment by jijojosephk** [comment]
@cpfeiffer This is fixed in the upcoming build `1.0.29`

**Comment by jijojosephk** [comment]
This is not related to AppImage this happens for all builds. The BrowserView used for screen share preview was not destroyed properly.

**Comment by cpfeiffer** [comment]
Awesome, thank you so much! :heart:

**Comment by jijojosephk** [comment]
> Awesome, thank you so much! heart

Thank you. I'll close this. your contributions much are appreciated!
