### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by ideamoves** [IsmaelMartinez/teams-for-linux#537]
**Describe the bug**
$ sudo snap install teams-for-linux
error: snap "teams-for-linux" is not available on stable for this architecture
       (arm64) but exists on other architectures (amd64, armhf).

**Expected behavior**
Please upload a build for the arm64 aarch64 architecture. Thank you.

**Comment by IsmaelMartinez** [comment]
Hello! Sorry but somehow I wasn't able to publish to snap with arm64. You can use another package manager to use the arm64 version from the [releases section](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.24)

Feel free to try to solve the puzzle by adding a new line in https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L33. with the arm64... it might work but it might not.

**Comment by ideamoves** [comment]
Thank you, teams-for-linux-1.0.24-arm64.AppImage works well for me

**Comment by jijojosephk** [comment]
@ideamoves if you think you're problem is resolved, could you please close this defect? @IsmaelMartinez snap publish token seems to have expired. I'm not sure what can be done next.

**Comment by jijojosephk** [comment]
Closing as this is not related to application but publish issue with the snap store. Also, the work around solution works.

**Comment by IsmaelMartinez** [comment]
I will see when I can fix those tokens. Apologies but having an extremely busy life!
