### ISSUE TITLE
deb package doesn't display banner on systray icon

### ISSUE THREAD

**Issue by mpruefer** [IsmaelMartinez/teams-for-linux#54]
I'm using https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v0.1.15/teams-for-linux_0.1.15_amd64.deb. When the Teams window is closed and new messages arrive, I get a desktop notification, but the system tray icon doesn't show a banner with the number of unread messages.

When using https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v0.1.15/teams-for-linux_0.1.15_amd64.snap instead, that banner works.

Using Ubuntu 18.04 LTS.

**Comment by IsmaelMartinez** [comment]
I suspect that it is the same as the following: https://github.com/IsmaelMartinez/teams-for-linux/issues/42#issuecomment-458305097

I don't know enough about snap to understand why it works in one but not the other. Maybe is using another notification library.

Let me know how you get on with this one. Hope helps
