### ISSUE TITLE
v0.1.15 & master: One-on-one calls fail with "unsupported browser" message

### ISSUE THREAD

**Issue by theangryangel** [IsmaelMartinez/teams-for-linux#55]
First off, thank you for working on this. I really do appreciate it.

Unfortunately with both v0.1.15 and master one-on-one calls to other users results in the message;

> Try a different browser
> This feature isn’t available yet for your browser. Try the web app with Microsoft Edge or Google Chrome, or switch to the desktop app.

Unfortunately, I think the fix for #21 is causing the problem. I have verified that adding the missing `angular.element(document).injector().get('callingSupportService').oneOnOneCallingEnabled = true;` from #21 does not fix the issue, but I've not yet had the time to dig in further.

I'll try and see if I have time at some point in the next few days. Figured I'd create the issue just incase someone's already on it?

**Comment by julian-alarcon** [comment]
I confirm this issue. Same version 0.1.15

**Comment by IsmaelMartinez** [comment]
Could either of you try branch 0.1.16? There where a few extras that I missed in 0.1.15. apologies

**Comment by theangryangel** [comment]
Confirmed that 0.1.16 works great <3 

No need to apologise at all Ismael! You're single-handedly doing the job Microsoft should be doing, and I cannot thank you enough.

**Comment by IsmaelMartinez** [comment]
Thanks @theangryangel , 0.1.16 is on the making and hopefully we get desktop sharing in it thanks to the help of a few. Anything helps, from posting issues, asking for new features or, even better, fixing or implementing stuff!! Hopefully one day Microsoft will decide to support Linux properly and I can spend my time doing something else!
