### ISSUE TITLE
Open window when clicking on your launcher

### ISSUE THREAD

**Issue by rafatosta** [IsmaelMartinez/teams-for-linux#556]
**Describe the bug**
When closing the window it is no longer possible to open it or initialize it through its launcher.

**To Reproduce**
I use Fedora WorkStation 36 and without an extent for the tray icons, so when closing the window you can only open it through the tray icon.

Close the window and try to open by the launcher, you will notice that nothing will happen.

**Expected behavior**
I hope the window will open when clicking on its launcher.

**Desktop (please complete the following information):**
 - OS: Fedora WorkStation 36 
 - Installation package Flatpak
 - Version last

**Comment by rafatosta** [comment]
thank you so much. excellent job!

**Comment by jijojosephk** [comment]
@rafatosta `1.0.30` on it's way. Published from my side, it takes some time to be available officially on flathub. Thanks for reporting the issue.

**Comment by rafatosta** [comment]
> @rafatosta `1.0.30` on it's way. Published from my side, it takes some time to be available officially on flathub. Thanks for reporting the issue.

No problem.
I don't know if you know, but I'm the dev of I don't know if you know, but I'm the dev of [ZapZap - Whatsapp for linux](https://beta.flathub.org/apps/details/com.rtosta.zapzap)

**Comment by jijojosephk** [comment]
> > @rafatosta `1.0.30` on it's way. Published from my side, it takes some time to be available officially on flathub. Thanks for reporting the issue.
> 
> No problem. I don't know if you know, but I'm the dev of I don't know if you know, but I'm the dev of [ZapZap - Whatsapp for linux](https://beta.flathub.org/apps/details/com.rtosta.zapzap)

Wow! That's great! Let me know if you would like contributions.

**Comment by rafatosta** [comment]
Certainly! Any support and contribution from the community is welcome. Feel free to propose or send PR. Thanks
