### ISSUE TITLE
Add "zoom-in/out" functionnality

### ISSUE THREAD

**Issue by Normand-Nadon** [IsmaelMartinez/teams-for-linux#560]
I have a high DPI display, and the text in this electron version of the app is way too small.
The web and desktop versions both have the ctrl+scroll zoom option available, but not this electron-wrapped version.

Please enable ctrl+scroll in the app... There is documentation on the subject here: 
https://www.geeksforgeeks.org/zoom-functionality-in-electronjs/

With the iminent discontinuation of the official teams for linux app, the only viable option remains your version of the app!
Keep-on the excellent work!

Regards

**Comment by IsmaelMartinez** [comment]
Hi, the zoom in was available a while back. Try to use the web shortcut and
see if it works. Otherwise this could be something that got removed when
upgrading an electron version.

**Comment by jijojosephk** [comment]
@Normand-Nadon CTRL + keys (+,-) works and the zoom level is maintained between runs. If you're specifically looking for mouse scroll wheel + CTRL key, we can implement. If you confirm, I'll mark this as feature request. It works fine in the latest version `1.0.30`

**Comment by Normand-Nadon** [comment]
Thank you for the quick fix! I updated the app and it does not do the zooming... Can you tell me if it is now in the main code or in a future release?

**Comment by jijojosephk** [comment]
Thanks @Normand-Nadon flatpak update is being published. Should be available soon.
