### ISSUE TITLE
Since the Desktop Teams client is being discontinued will this project return?

### ISSUE THREAD

**Issue by FSKiller** [IsmaelMartinez/teams-for-linux#561]
https://www.reddit.com/r/linux/comments/x3c1sk/mircosoft_teams_desktop_client_on_linux_is_being/

From what i can tell microsoft just announced that they will be stopping developing the desktop client for Linux.

Will this return to development?

**Comment by jijojosephk** [comment]
It will be here and was never gone. The latest release was a few days ago.

**Comment by codethief** [comment]
Would it make sense then to remove the note

> This project is in maintenance mode only. Microsoft is now providing a client that, more or less works.

from the README?

**Comment by jijojosephk** [comment]
Done.
