### ISSUE TITLE
No more notification sound (when message, activity, ...)

### ISSUE THREAD

**Issue by emotiv8it** [IsmaelMartinez/teams-for-linux#565]
**Problem Description**

Since a couple versions back, I have no more sound (bell/...) when a direct chat message is received, or when another kind of activity is made. The "official"  MS linux version does have still the notification sounds.

Also, tried to install the DEB version of the latest release [**1.0.32**]
(https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.32) 

Still having sound issues (no sound when receiving messages, ...)
 (app either on top, active, focussed, or in background, minimized...)

**To Reproduce**

1. install version 1.0.32  on  ubuntu 20.04.5 - LTS
2. make chat to person -> no notification sound when chat is incoming... (either on top, active, focussed, or in background, minimized...)

**Expected behavior**

Hear a sound when chat is received, or if an activity that is related appears.

**Desktop (please complete the following information):**

- System/OS:  Linux Ubuntu 20.04.5 LTS (focal)
- Kernel: 5.4.0-125-generic 
- installation package:  teams-for-linux_1.0.32_amd64.deb   (https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.0.32/teams-for-linux_1.0.32_amd64.deb)

**Comment by jijojosephk** [comment]
Thanks for reporting. Can you confirm last version it worked?

**Comment by Normand-Nadon** [comment]
I can confirm I experience the same issue... Calls are ringning, but message notifications are not... The same issue happens on the web version of the app though.. Might be a f@ck-up from Microsoft.
(The icon in the taskbar displays the number of notifications fine BTW)

Pop-OS 22.04, Brave browser

**Comment by jijojosephk** [comment]
But I hear notification sound in Brave. This has something to do with changes by teams developers from Microsoft. I did try previous builds of this app and no sound at all. So it's not something broke by our updates. Weird!

**Comment by jijojosephk** [comment]
I can confirm it's not related to electron version. Only MS can tell why.

**Comment by jijojosephk** [comment]
Looks like notification (Browser native notification) does not have a audio play in recent versions. In browser enable notifications for the website. You'll not notice suddenly sound vanishes. I'll try for a work around.

**Comment by jijojosephk** [comment]
This fix works on Ubuntu. I had to use a library to play sound. This lib uses a few media player modules within linux system. Depends on the distributions.

Please read about this module [here](https://www.npmjs.com/package/play-sound). If notification is not working for you, please check if any of the supported players are installed in your system.

**Comment by emotiv8it** [comment]
Tested this again, with this latest release 1.0.33 and now I get a notification sound !! Works for me (ubuntu) One step closer to the best teams for linux solution ;-) 
Thx for fixing this issue !!

**Comment by Normand-Nadon** [comment]
@jijojosephk Works well now with the 1.0.33 .deb version...

Out of curiosity, do you have a PPA to auto-update the software?

Otherwise, how long does it take for Flathub to be on the latest version? I honeslty have no Idea how it is done...
Flatpak in now on 1.0.32 with the zoom in/out patch! Yay!... But not the sound fix from 1.0.33

**Comment by jijojosephk** [comment]
@Normand-Nadon currently we don't have a ppa. We can try to create one. Flatpak one's are not part of github actions in this repo. It has a separate one [here](https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux). It's a manual process and I'll have to explicitly push the changes. Notification sound does not work on the flatpak version. It has something to do with run time directory and relative path. Yet to figure out the solution. That's why it's not released.

**Comment by jijojosephk** [comment]
I think it's related to shell command execution permission within sandbox than a path issue. Fingers crossed!

**Comment by jijojosephk** [comment]
flatpak allows only pulseaudio at the moment. We need to use a library compatible with pulseaudio to fix this in all packages. I'll create a new defect for flatpak.

**Comment by jijojosephk** [comment]
@Normand-Nadon new defect opened #569

**Comment by simonvanderveldt** [comment]
I just upgraded from 1.0.24 to 1.0.45 and now I always get a notification sounds for any chat message which is very annoying. I've tried to turn everything off but I get the notification "pling". Is this caused by the fix for this?
