### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by raul-klg** [IsmaelMartinez/teams-for-linux#568]
When a holding a meeting and one of the parties share his/her screen the "Remote Control" button is not shown in the conversation bar. This button is shown when the sharing participant runs windows client and it is available when using the MS teams client.

What I would like from the teams-for-linux client is that the "Remote Control" button appear and remote control is available with client in similar conditions as it is shown with the MS teams client.

The lack of "Remote control" button has been lastly tested running version 1.0.29. Although I can update the information with latest teams-for-linux version.

If needed I can attach screenshots. Thanks for your wonderful effort in this project. Best regards,

**Comment by Normand-Nadon** [comment]
I don't want to overstep the developpers here... 
But this feature was never available on the web version.
Microsoft announced that they might add it this fall, and also they will be re-introducing custom background for the web version too (they removed it a few months ago)

**Comment by raul-klg** [comment]
For the sake of completeness here are the screenshots for a call when someone (running teams on windows) is sharing screen:

* Teams for linux (our favourite teams client)
![teams-for-linux](https://user-images.githubusercontent.com/48016314/188834753-829b5520-a430-4275-a8ae-131ed4486709.png)

* MS teams:
![MS-teams](https://user-images.githubusercontent.com/48016314/188834745-8c0959c2-59bc-4f0c-a175-b6314761bea4.png)

@Normand-Nadon I think yours is a helpful comment. I would add that custom background feature is available from teams-for-linux whereas it is *not* on MS teams. BTW, this is a feature request. I don't know if this is inside the project scope (short/mid/long term) or not. I don't know either if this is technically feasible or not.

**Comment by jijojosephk** [comment]
@raul-klg we understand the requirement but it could be difficult to implement. I mark this as an enhancement.

**Comment by Normand-Nadon** [comment]
> For the sake of completeness here are the screenshots for a call when someone (running teams on windows) is sharing screen:
> 
> * Teams for linux (our favourite teams client)
>   ![teams-for-linux](https://user-images.githubusercontent.com/48016314/188834753-829b5520-a430-4275-a8ae-131ed4486709.png)
> * MS teams:
>   ![MS-teams](https://user-images.githubusercontent.com/48016314/188834745-8c0959c2-59bc-4f0c-a175-b6314761bea4.png)
> 
> @Normand-Nadon I think yours is a helpful comment. I would add that custom background feature is available from teams-for-linux whereas it is _not_ on MS teams. BTW, this is a feature request. I don't know if this is inside the project scope (short/mid/long term) or not. I don't know either if this is technically feasible or not.

The issue is that the web version does not have the remote assistance option... and if I am not mistaken, the teams-for-linux app is wrapping the web version in an electron app packkage... but I might be mistaken too

Also, the Linux official client never had the feature (and was also an Electron app flavour)

**Comment by IsmaelMartinez** [comment]
Sorry, I will suggest you request this in the uservoice (https://support.microsoft.com/en-us/office/share-content-in-a-meeting-in-teams-fcc2bf59-aecd-4481-8f99-ce55dd836ce8#ID0EABAAA=Desktop) 

related to #395
