### ISSUE TITLE
No notification sound when installed through flatpak

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#569]
**Describe the bug**
When there is a new notification, no sound is played.

**To Reproduce**
1. Start teams-for-linux.
2. Login to the account.
3. Analyse the notifications when new ones arrive. No sound.

**Expected behavior**
Notification sound should be played.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Installation package: flatpak
 - Version: 1.0.32

**Additional context**
None.

**Comment by Normand-Nadon** [comment]
Just a thought, as I dont have the required knowlege to code it myself, but you metionnend [here](https://github.com/IsmaelMartinez/teams-for-linux/issues/565#issuecomment-1239445451) that the sound issue relies on the use of pulseaudio...
Since every distro is turning to pipewire for audio (and the permissions work differently), I heard there was a pulseaudio-like client for pipewire called "pipewire-pulse"

Might be helpfull or not... just wanted to contribute the minimum I can :)

**Comment by jijojosephk** [comment]
Thanks for the information. But I guess it's about low level implementation, commands will be the same. Anyway, I'll work on a new npm module. The current dependency for audio playback is not actively maintained.

**Comment by jijojosephk** [comment]
@Normand-Nadon  and @emotiv8it please have this tested when version `1.0.36` arrives.

**Comment by emotiv8it** [comment]
I have installed the  1.0.36 and still works fine (notification sounds) - also calling works (sound) etc.
Pretty happy with this version.

(only thing I seem to miss is to see which version nr this is  (in the application ?) )

**Comment by jijojosephk** [comment]
@Normand-Nadon It's working in flatpak. I'm closing this issue. Re-open if don't find it working.

**Comment by jijojosephk** [comment]
> I have installed the 1.0.36 and still works fine (notification sounds) - also calling works (sound) etc. Pretty happy with this version.
> 
> (only thing I seem to miss is to see which version nr this is (in the application ?) )

Please suggest where can we  have the version listed.

**Comment by Normand-Nadon** [comment]
> @Normand-Nadon and @emotiv8it please have this tested when version `1.0.36` arrives.

It works great! thanks for the nice quick work you do!
All my team is now on this version and we are happy!

I suggested two improvements and they were done in less than a week! WOW!
