### ISSUE TITLE
Package.json license field is invalid

### ISSUE THREAD

**Issue by Thaodan** [IsmaelMartinez/teams-for-linux#570]
**Describe the bug**

The package.json specifies the license as "See License.md".
The license field such match the SPDX-License value matching to the license that the project uses.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] not relevant
 - Version: master
 
**Additional context**
- https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license

**Comment by Thaodan** [comment]
Using something like "Refer to license file" is valid however this project uses a license that has a SPDX-License tag.

**Comment by jijojosephk** [comment]
@Thaodan , I've committed the changes you may verify and close this one.

**Comment by Thaodan** [comment]
LGTM.

PS: You sound like you ask me for a review on a PR but merge it before my 
comment, usually those are opened and wait for a review ;)

**Comment by jijojosephk** [comment]
Ha ha sorry :) I'll keep the PR open from next time. Thanks for reporting the issue.
