### ISSUE TITLE
Using the default configuration shouldn't be an error

### ISSUE THREAD

**Issue by Thaodan** [IsmaelMartinez/teams-for-linux#571]
**Describe the bug**
When starting the app without having a configuration file the app logs an error because it couldn't find the config.

**To Reproduce**
1. electron <app.asar>

**Expected behavior**
No error message, maybe a debug message that is only shown if loglevel is debug or higher.

**Comment by jijojosephk** [comment]
@Thaodan Is there a library that can be used or are you referring to electron framework logs?

**Comment by Thaodan** [comment]
Those are electron logs. I found out that's the error when the user has no config set.

**Comment by IsmaelMartinez** [comment]
@Thaodan , Can you put the error message in here? I checked and when the config file is not found it should log an "info" message (see https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/index.js#L8)

**Comment by jijojosephk** [comment]
Closing this a new command line argument is added to support this.
