### ISSUE TITLE
"?" character replaces "ñ" in user names since a recent electron update

### ISSUE THREAD

**Issue by kupiqu** [IsmaelMartinez/teams-for-linux#573]
**Describe the bug**
Since the recent electron updates (I think it started with version 1.0.29), characters such as `ñ` in user names (and links to user names are displayed as `?`).

Functionality is not affected but this is not only a cosmetic issue; referring to users with a wrong character in their name does not give a good impression. 

**Desktop (please complete the following information):**
 - OS: Linux KDE neon
 - Installation package: deb
 - Version: any in 1.0.29 - 1.0.33

**Comment by jijojosephk** [comment]
Can you share a screenshot please?

**Comment by kupiqu** [comment]
I would but this involves sharing other people's personal informacion. What I did instead is to test if this happens with channel names, and it doesn't:

![image](https://user-images.githubusercontent.com/3875196/189520773-c42d5c47-5e17-4eca-9d19-c35ea0c71d1f.png)

So, as far as I can tell, this only happens with usernames, where `ñ` is not displayed, instead `?` is shown. For instance if `niño` would be part of a username, it would be displayed in the capture as `ni?o, this is a test`

**Comment by jijojosephk** [comment]
How does it behave on chrome browser?

**Comment by kupiqu** [comment]
I installed chrome to test (flatpak package), and the same issue appears there. 

As it didn't happen when using previous electron versions, I guess it's some sort of regression in chrome or teams itself.

I guess there is nothing teams-for-linux can do about it

**Comment by jijojosephk** [comment]
Ok.Thank you. Could you please close this one then?

**Comment by IsmaelMartinez** [comment]
Might be unrelated but previous people had a similar issue in their OS. Maybe their solution also works for you https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632002149

**Comment by kupiqu** [comment]
> Might be unrelated but previous people had a similar issue in their OS. Maybe their solution also works for you [#357 (comment)](https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632002149)

I don't think it's the same thing, but will check it out, thanks
