### ISSUE TITLE
feature: option to hide show with a left click on the tray icon

### ISSUE THREAD

**Issue by draxil** [IsmaelMartinez/teams-for-linux#574]
**Is your feature request related to a problem? Please describe.**

I usually only use the tray menu to hide and show teams. Currently a left or right click will get this same result, and I can find the hide and show there. Although in practice I'm more likely to use my window manager short-cuts as this is a bit cumbersome.

**Describe the solution you'd like**

With an option (probably) I'd like to make a left click on the tray icon click toggle teams visibility, instead of showing the menu.

**Describe alternatives you've considered**

There's plenty of alternatives, including just using the power of my window manager. This is simply a nice piece of potential polish. If there's some other alternative I'd be interested to hear it.

**Additional context**

I'd just say this is purely extra shine, really this isn't a burning need so I don't mind if this idea goes on the rubbish tip. However I do think this would be a pretty snazzy option, and would give a bit more power rather than left and right click having the same effect.

**Comment by jijojosephk** [comment]
@draxil Thanks for reporting. But unfortunately there's a dependency over electron framework. Tray icon events do not behave correctly. I guess it's difficult to implement. The electron bug [here](https://github.com/electron/electron/issues/14941)

**Comment by kupiqu** [comment]
what follows is mentioned in that bug, but for the case some of us don't look there... at least in KDE this works if you get rid of libappindicator (libappindicator3-1:amd64 deb package in my debian derivative distribution)

**Comment by jijojosephk** [comment]
So it may not be easy unless the app detects the presence of libappindicator and act accordingly. Let's see.

**Comment by jijojosephk** [comment]
I have budgie and it does not have `libappindicator3` but I see `libayatana-appindicator3` are they related?

**Comment by kupiqu** [comment]
from [this](https://github.com/AyatanaIndicators/libayatana-appindicator), I understand that it is some sort of fork or different implementation of the same basic thing:
 
 README
# Ayatana Application Indicators (Shared Library) #

A library to allow applications to export a menu into the an Application
Indicators aware menu bar. Based on KSNI it also works in KDE and will
fallback to generic Systray support if none of those are available.

This code project was originally started by Canonical Ltd. and has been
adapted by various authors with the purpose of making this Application
Indicators available on Ubuntu and non-Ubuntu systems alike.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Ping to reopen

**Comment by sonnatager** [comment]
Hi, this would be a very nice improvement.

Here you can see how the Bitwarden Client do it:

https://github.com/bitwarden/clients/blob/35cc0da3cc5ea3d033f134c1b99c9be7835527d6/apps/desktop/src/main/tray.main.ts#L156

**Comment by jijojosephk** [comment]
@sonnatager it might be working for `darwin` and `win` but not for `linux`

**Comment by sonnatager** [comment]
I have currently running the Bitwarden Client running on Fedora 36 and it is working fine. I don't understand, why it should not working for the teams-for-linux app as they both are Electron-Apps...

**Comment by IsmaelMartinez** [comment]
Its probably using an older electron version. Hopefully electron does fix the underlying issue soon.
