### ISSUE TITLE
No window decorations when running in Wayland

### ISSUE THREAD

**Issue by RedChops** [IsmaelMartinez/teams-for-linux#576]
I noticed earlier today that by default, Teams seemed to be running in xwayland. I modified the command line to have the same flags as what I use for, ex, VSCode. Unusually, while VSCode gets a title bar, Teams will not.

I'm starting Teams using: `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=teams-for-linux --file-forwarding com.github.IsmaelMartinez.teams_for_linux --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto` which works for VSCode and Signal perfectly well. It's not the biggest deal in the world, I can still move the window around with Super+LMB, though I can't resize the window at all.

My system is running Fedora 36 on Gnome 42.4

**Comment by jijojosephk** [comment]
@RedChops can you check when version `1.0.35` is available? @herbiejhopkins had added a more flexible way to include wayland specific command line arguments. This version should be available in a few hours.

**Comment by RedChops** [comment]
@jijojosephk Hey look at that, the update ended up fixing the issue, thanks!

**Comment by jijojosephk** [comment]
Thanks 👍 Kudos to @herbiejhopkins
