### ISSUE TITLE
Crash with wayland screensharing and teams-for-linux flatpak version 1.0.36

### ISSUE THREAD

**Issue by alfsch** [IsmaelMartinez/teams-for-linux#584]
**Describe the bug**
Since flatpak updated teams-for-linux to version 1.0.36 with better wayland support teams-for-linux crashes when I try to share the screen/windows. It doesn't matter if only one window is shared or the whole screen. With version 1.0.35 both worked.

**To Reproduce**
1. install flatpak teams-for-linux version 1.0.36
2. Open call or attend to a meeting
3. share screen/window
4. crash

**Expected behavior**
teams-for-windows doesn't crash

**Desktop (please complete the following information):**
 - OS: ubnutu 22.04 jammy with wayland and pipewire
 - Installation package flatpak
 - Version 1.0.36

**Additional context**
Version 1.0.35 works perfekt, so I've downgraded with
`$ sudo flatpak update --commit=c83323945d636e5694406a8cfdb6a67e1a7608f4cdf0993da65dedbd05fb8708 com.github.IsmaelMartinez.teams_for_linux`

and prevent from updating currently with
`$ flatpak mask com.github.IsmaelMartinez.teams_for_linux`

advanced package information of working teams-for-linux
```
$ flatpak --system info com.github.IsmaelMartinez.teams_for_linux

teams-for-linux - Unofficial Microsoft Teams client for Linux using Electron

          ID: com.github.IsmaelMartinez.teams_for_linux
         Ref: app/com.github.IsmaelMartinez.teams_for_linux/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.35
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 233.9 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: c83323945d636e5694406a8cfdb6a67e1a7608f4cdf0993da65dedbd05fb8708
      Parent: ebbbc877ca3dc10c93e171087e8a1bb8a2f978683bd3aaf344c2a3d11bf022d4
     Subject: v1.0.35 (c362c0b2)
        Date: 2022-09-10 06:39:44 +0000
```
advanced package information of crashing teams-for-linux

```
 flatpak info com.github.IsmaelMartinez.teams_for_linux 

teams-for-linux - Unofficial Microsoft Teams client for Linux using Electron

          ID: com.github.IsmaelMartinez.teams_for_linux
         Ref: app/com.github.IsmaelMartinez.teams_for_linux/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.36
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 234.1 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: e63094b74a4b67dca6aadac6b39c14ffb617b24c0afd7b870df0999d9eb6d7a8
      Parent: c83323945d636e5694406a8cfdb6a67e1a7608f4cdf0993da65dedbd05fb8708
     Subject: v1.0.36_build_2 (ce44856b)
        Date: 2022-09-13 07:09:33 +0000

```

**Comment by jijojosephk** [comment]
@alfsch apologies! I'm not on wayland. So could not verify the build. I'll downgrade the freedesktop framework.

**Comment by alfsch** [comment]
@jijojosephk no problem, since I had the workaround to go to the working previous version.

Hopefully there's a flatpak developer using wayland ot test the scenario. I'm only a java dev, but if you need some debugging infos, I may be able to provide them , if you give me the right commands.

**Comment by jijojosephk** [comment]
@herbiejhopkins could you test?

**Comment by alfsch** [comment]
@yourealwaysbe 

`xdg-desktop-portal-gnome/jammy-updates,now 42.1-0ubuntu1 amd64 [installed,automatic]`

**Comment by yourealwaysbe** [comment]
> ```
> xdg-desktop-portal-gnome/jammy-updates,now 42.1-0ubuntu1 amd64 [installed,automatic]
> pipewire/jammy,now 0.3.48-1ubuntu1 amd64 [installed,automatic]
> sway/jammy 1.7-1 amd64
> ```

Ah, are you using Sway without xdg-desktop-portal-wlr? What happens if you install it? (If so, i didn't realise you could get screensharing working on Sway without it.)

We could also try packaging Pipewire 3.40 with the 21.08 Freedesktop rather than bumping to 22.08. (But i'll mess with that at home rather than at work :) )

**Comment by alfsch** [comment]
Yes my machine is setup using  xdg-desktop-portal-gnome. I fear that I may crash other working apps when switching to xdg-desktop-portal-wlr.

**Comment by alfsch** [comment]
@yourealwaysbe sorry for above missleading information 'sway' isn't installed on my machine. I'll remove it from above comment.

**Comment by jijojosephk** [comment]
@yourealwaysbe and @alfsch I've reverted to `21.08`. Just published the build. @alfsch, please install when it's available. Version number is still the same (`1.0.36`) but freedesktop at `21.08`. With this version you'll have perfectly working chat notification sound.

@yourealwaysbe, coud you please add a new defect for Sway in this repo? We'll try to include in `1.0.37`

**Comment by alfsch** [comment]
I've tested:

```
  flatpak --user info com.github.IsmaelMartinez.teams_for_linux 

teams-for-linux - Unofficial Microsoft Teams client for Linux using Electron

          ID: com.github.IsmaelMartinez.teams_for_linux
         Ref: app/com.github.IsmaelMartinez.teams_for_linux/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.36
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 234.1 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 9233b88bab4ab8f8776237aceb902655355e751df6c1d049c2e13a570635634a
      Parent: e63094b74a4b67dca6aadac6b39c14ffb617b24c0afd7b870df0999d9eb6d7a8
     Subject: Reverted org.freedesktop.Platform to previous version (db4435aa)
        Date: 2022-09-13 12:33:18 +0000
```
It works with screen-sharing and has all the pling-pling sounds....

**Comment by jijojosephk** [comment]
Thanks @alfsch, I'll close this. In the future we'll add a feature that lets user choose a different notification sound than the MS  pling-pling sound :D
