### ISSUE TITLE
Play Incoming Call Notification on second audio device

### ISSUE THREAD

**Issue by baderas** [IsmaelMartinez/teams-for-linux#590]
Hi,

compared to the official teams client, the web version for Chrome/Firefox lacks the possibility to play an incoming call sound notification on a second audio device. 

E.g. given: you have your speakers as a seperate audio device and your headset (as a usb audio device for example). In this case, its nice to have notifications played on the speakers, while the call-audio is still played on the headset.

With https://github.com/IsmaelMartinez/teams-for-linux/issues/565 and its solution https://github.com/IsmaelMartinez/teams-for-linux/pull/566 a custom nofitication for messages was added.

Is it somehow possible to extend this method to play some kind of notification sound for incoming calls on a second audio device?
That would be nice.

**Comment by jijojosephk** [comment]
Thanks @baderas for posting your suggestion. Are you referring to this?

![image](https://user-images.githubusercontent.com/11662148/190392060-1b02a51f-075e-4dc5-8f1b-9c5edd6e2eb7.png)

**Comment by baderas** [comment]
Yes, exactly.

**Comment by jijojosephk** [comment]
It's possible this one too.

**Comment by jijojosephk** [comment]
Can you confirm if this setting is present in teams-for-linux? web version has this. So it must be.

**Comment by jijojosephk** [comment]
@baderas can you confirm?

**Comment by baderas** [comment]
No, its not present in teams-for-linux, its also not presend on the web version (tried with firefox and chromium). Only the official linux teams client has these settings.

**Comment by baderas** [comment]
Can you maybe show some more screenshots of your web version? which browser are you using?
I'm a bit confused how its possible that you have device settings in your web version.

**Comment by baderas** [comment]
ah okay, didn't know that. I'm not sure if this really helps (in the original teams client, the config is named "secondary ringer" in devices), but I will try to change the overall audio device and then reset the speaker in the meetings-device-settings. maybe this helps to have it continously ring on another audio device.

**Comment by athyla** [comment]
Hello!
I think @baderas is referring to this setting, from the official MS Teams for linux:

![ksnip_20221006-100558](https://user-images.githubusercontent.com/55332841/194237304-bd203f5c-9f9d-4e89-afc2-bffae0fc7533.png)

Here you can choose an additional audio device to work as a secondary ringer.

Unfortunately, in teams-for-linux there are no device settings at all, so not sure how this setting could be accessed.

**Comment by baderas** [comment]
As stated in my first post:
Consider a setup with a onboard soundcard and a usb headset - two seperate audio devices, to the first are some speakers connected, to the second your headset. In this case, you can choose the onboard soundcard as secondary ringer, to get notifications played on the speakers and for in-call-audio your usb headset is used.

I think it is not necessary to support the whole "secondary ringer" concept. It would be enough to play some kind of notification sound for incoming calls on a second (or better: on all available) audio device(s)? Or even some kind of "run a bash script if a incoming call is detected" would be enough.

**Comment by ThomasRitter75** [comment]
@jijojosephk FYI: Another use case is wireless headsets. I do not always have my headset switched on, so I would really love to have the ringtone on the built-in laptop speaker (can do by bash script as well, if this is hard in Electron)

**Comment by ThomasRitter75** [comment]
For the developers to understand the severity: This option missing means, I miss nearly all my calls at work, because I do not hear the ringtone playing on the headset.

**Comment by ThomasRitter75** [comment]
Question to the devs - Did you change anything? When I start the app now with default audio device A (my laptop speaker in my case) and select device B (wireless headset) as in-call-headset and speaker, I can talk over the headset (B) and have Ringtones and all notifications on device A, which did not work some versions ago, but now it works.
@baderas Can you try this and check if this task can be closed?

**Comment by baderas** [comment]
@ThomasRitter75 thanks for the info, I also tried it again and it seems that this is working now. Make your Device A (for Notifications, incoming ringtone, ..) the default device and start teams. Choose your device B when making a call.
It would still be nice to have a possibility to somehow send incoming call notifications to an external application (or script or something), but for me this issue can be closed.
