### ISSUE TITLE
Blank page, tab "localhost:8989" opened in default browser

### ISSUE THREAD

**Issue by exic** [IsmaelMartinez/teams-for-linux#592]
**Describe the bug**
Starting the application, I get the blank screen and in my firefox a tab opens with the URL http://localhost:8989/

**To Reproduce**
1. Install AUR teams-for-linux or run `yarn start`
2. See blank page
3. Try all the options at https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#blank-page
4. Still blank page

**Expected behavior**
App should start correctly and not open a browser tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/242107/191045332-86546ea1-35c3-4cfe-bd7a-1c3becb5e966.png)

**Desktop (please complete the following information):**
 - OS: Arch
 - Installation package https://aur.archlinux.org/packages/teams-for-linux and latest develop
 - Version node -v: v16.17.0

**Additional context**
With the AUR package I had an issue on the first install because my node version was too old, so I ran `nvm install --lts` and it installed correctly. Now I also tried with node 14 but still the same :-(

**Comment by jijojosephk** [comment]
Thanks @exic for reporting the issue. Could you provide a screenshot of the same after installing through AUR package?
I haven't seen anything like this before. Which DE you have?

**Comment by exic** [comment]
Thanks for your reply, sure, this is the result using the AUR package:

![image](https://user-images.githubusercontent.com/242107/191176633-8c003a58-989f-470b-b872-5c9bfad4b919.png)

Window manager is i3-gaps, I'm not using an additional desktop environment.

**Comment by jijojosephk** [comment]
We need to know whether this related to window manager

**Comment by exic** [comment]
I have another PC with the same setup so I tried to compare … couldn't figure it out. Turned off VPN, looked at strace.. then I started to try all the CLI options to compare outputs and maybe find something. Turns out `teams-for-linux --url https://teams.microsoft.com/` works! :smile: I have no idea why, though.

**Comment by jijojosephk** [comment]
Interesting :)
