### ISSUE TITLE
Right click in text box does not work

### ISSUE THREAD

**Issue by docquantum** [IsmaelMartinez/teams-for-linux#594]
**Describe the bug**
Trying to right click on any text within a text box does nothing. No context menu is brought up.

**To Reproduce**
1. Go to a chat or teams channel
2. Compose a message
3. Select text within the composition section
4. Attempt to right click onto it to bring up the context menu to copy, paste, or correct spelling
6. See that nothing is brought up, as if right clicks are ignored.

**Expected behavior**
Highlighting any text within the composition box and right clicking should bring up a context menu which allows the user to copy, paste, and/or correct spelling.

**Desktop:**
 - OS: Ubuntu Linux 22.04.1
 - Installation package: snap
 - Version: 1.0.37

**Additional context**
Things like the spell checker are still operational and copy/pasting via keyboard shortcuts is possible.

**Comment by jijojosephk** [comment]
There was a spellcheck module but due to electron and node version upgrades build was failing. So Recently the module was removed. We'll sure find an alternate. Thanks for reporting.

**Comment by jijojosephk** [comment]
@docquantum version `1.0.38` will be out in some time. Unfortunately, @IsmaelMartinez has to update the snap stable version from his side. I guess you might have tried --edge because snap stable is at `1.0.29`

**Comment by IsmaelMartinez** [comment]
I have updated stable to the latest. Apologies for the delay!
