### ISSUE TITLE
Huge Huge thank you!

### ISSUE THREAD

**Issue by KlimDos** [IsmaelMartinez/teams-for-linux#60]
Ability to share screen should help me to keep using my sweet Linux as a work laptop instead of that darn mac.
It's hard to overestimate how pleased I am. 
Thank you, sir. really really appreciated.

**Comment by IsmaelMartinez** [comment]
Your welcome. I can only thank all the people that made it possible, as in not anymore me only working on this.

I invite you to help, whatever you can do. The more people supporting this, the more we can archive.

**Comment by vhakulinen** [comment]
I just found this through the user vote page for native linux client. This project is really awesome! Thank you so much!

For a software developer it is really important to be able to share a screen to a remote co-worker. I wonder what they are thinking at microsoft for not enabling this functionality for linux users.
