### ISSUE TITLE
Option closeAppOnCross not working

### ISSUE THREAD

**Issue by guikeller** [IsmaelMartinez/teams-for-linux#602]
**Describe the bug**
The config option **closeAppOnCross** is not working.

OS: Fedora Linux 36 (Workstation Edition) x86_64  
Kernel: 5.19.10-200.fc36.x86_64  
DE: GNOME 42.5  

**To Reproduce**
1. Tried
```bash 
teams-for-linux --closeAppOnCross true
teams-for-linux --closeAppOnCross=true
teams-for-linux --closeAppOnCross="true"
```
Also tried by creating a "~/.config/teams-for-linux/config.json" with:
```json
{
    "closeAppOnCross": true
}
```

3. Click on 'X' to close Teams or "Teams for Linux > Quit"

4. See process still running:
``` bash
ps auxf | grep teams
``` 

**Expected behavior**
Teams should quit and no teams process should be running after clicking on "X" or "Quitting" the app.

**Screenshots**
The same app process is there after the app is started and is closed/quit.
![Screenshot from 2022-09-26 19-05-28](https://user-images.githubusercontent.com/8213310/192238112-e6b13495-cc16-4140-bcec-50199d66139c.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Installation package [ rpm ]
 - Version [ 1.0.38 ]

**Additional context**
Gnome 42.5 has no "tray" and enabling it to be able to quit is just not an acceptable solution.

**Workaround**
Forcefully kill the app
```bash
pkill -f teams-for-linux 
```

**Comment by jijojosephk** [comment]
Thanks @guikeller for reporting this. This seems to be a regression defect. The tray is not getting closed.

**Comment by jijojosephk** [comment]
Fixed the issue. Merge auto closed the issue. Please try with `1.0.39` when it's released in some time.

**Comment by jijojosephk** [comment]
@guikeller  Just published. Thanks for the patience!
