### ISSUE TITLE
Pop out chat functionality

### ISSUE THREAD

**Issue by r-cdriscoll** [IsmaelMartinez/teams-for-linux#604]
Hello - 

The official MS client offers a "pop out chat" functionality for 1-on-1 conversations where you can right-click on a chat and there's a "Pop out chat" option to open the 1-on-1 chat in a new window.  This is helpful when multitasking between conversations.

I tried grepping through the teams-for-linux source to see if there was something I was missing, and tried searching through this project's issue history, but didn't end up finding anything.

Is this a feature that can be implemented?  Is there something I can provide to assist with this?

Thank you for your work on this client!

![image](https://user-images.githubusercontent.com/108948964/192296742-7e6e127a-99c4-4045-87bc-c6552c904561.png)

**Comment by jijojosephk** [comment]
@r-cdriscoll There's a discussion [here](https://github.com/IsmaelMartinez/teams-for-linux/discussions/601) unfortunately it's not possible.

**Comment by r-cdriscoll** [comment]
@jijojosephk Ah, my search-fu was poor.  Thank you for letting me know.
