### ISSUE TITLE
Feature Request - Red border when screen sharing

### ISSUE THREAD

**Issue by cs96and** [IsmaelMartinez/teams-for-linux#606]
**Is your feature request related to a problem? Please describe.**
The official Teams application puts a red border around your screen when you are screen sharing.  teams-for-linux doesn't do this, so it's not obvious that the screen share is working.  You may also forget that you are sharing your screen, and end up sharing private information.

**Describe the solution you'd like**
teams-for-linux should put a red border around the screen that is being shared.

**Comment by jijojosephk** [comment]
It could be really complex. But see if we can this implemented.

**Comment by jijojosephk** [comment]
Looks like a difficult take. Would a notification be enough?

**Comment by cs96and** [comment]
Ideally there should be some sort of permanent notification showing, while you are sharing your screen.

**Comment by Krychle** [comment]
At least with Wayland/Gnome, there is an orange icon in the tray indicating what is being shared. Granted, much less subtle than a full red border, like on office teams application.

**Comment by jijojosephk** [comment]
@cs96and 

As far as I know, the trick is to create browser window frame-less and transparent, and some additional tweaks. Since we're bound to use electron browser windows only, it may increase the memory usage. Also with the sharing of windows, we might not be able to track the location as the windows can be moved but the screens are not. The implementation can be gitchy.

My suggestions:

1. Visual notifications at fixed intervals when the screen/window is being shared.
2. Audio notifications at fixed intervals when the screen/window is being shared.
3. Change in tray icon when the screen/window is being shared. (This might not work for all environments, we have already an open issue regarding tray icon does not show the notification count).
4. All of the above with the flexibility to turn them on and off individually.

If we have an agreement, we can update the description of the defect and try implementing it.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Ping to reopen

**Comment by psidhu** [comment]
Just commenting here that I believe this should be re-opened so we can discuss ideas further.

**Comment by starek4** [comment]
The red border would be the best, but I understand that it is not so trivial. From bellow suggestions

> @cs96and
> 
> As far as I know, the trick is to create browser window frame-less and transparent, and some additional tweaks. Since we're bound to use electron browser windows only, it may increase the memory usage. Also with the sharing of windows, we might not be able to track the location as the windows can be moved but the screens are not. The implementation can be gitchy.
> 
> My suggestions:
> 
> 1. Visual notifications at fixed intervals when the screen/window is being shared.
> 2. Audio notifications at fixed intervals when the screen/window is being shared.
> 3. Change in tray icon when the screen/window is being shared. (This might not work for all environments, we have already an open issue regarding tray icon does not show the notification count).
> 4. All of the above with the flexibility to turn them on and off individually.
> 
> If we have an agreement, we can update the description of the defect and try implementing it.

Option 3 sounds quite promising. Options 1 and 2 could be quite disturbing during the sharing session.

**Comment by IsmaelMartinez** [comment]
can you put an screenshot as an example? Thanks!

**Comment by antimatter84** [comment]
If I may, this is a mockup of the white banner from the PWA version:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/10585451/6f2df6ff-c345-4a88-a01b-8ebfda56c116)

**Comment by starek4** [comment]
That looks great @antimatter84 ! 

And totally awesome would be if we could move with it with the mouse. That would be best.

**Comment by antimatter84** [comment]
And the actual banner:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/10585451/9e631b54-a24b-4219-9f02-267961dc23f4)

If I'm not mistaken, the left-most element looking like " | | " is probably for dragging it around with the mouse.

**Comment by jijojosephk** [comment]
Thanks @antimatter84, like I said before, this can only be achieved by creating a new BrowserWindow instance which would increase the memory used during a call. The above floating window is created by the browser itself by using native windows and they're less resource hungry than a browser instance. Probably you can relate what I'm trying to explain. Can we do this? yes most likely but it would use up a extra memory. If everyone agrees, we can try it! @IsmaelMartinez what do you think?

**Comment by IsmaelMartinez** [comment]
I will perform really badly, specially when it's during a screen sharing. 

Electron has the BrowserView that is meant to be much better, but that will require quite a rewrite.

I got a wee branch trying to add chrome extensions, and that needs tabs that sort of needs the BrowserView.

I see if I can put a branch with some of it and we can iterate, but it will be a big change (hopefully for the better)

**Comment by IsmaelMartinez** [comment]
I will perform really badly, specially when it's during a screen sharing. 

Electron has the BrowserView that is meant to be much better, but that will require quite a rewrite.

I got a wee branch trying to add chrome extensions, and that needs tabs that sort of needs the BrowserView.

I see if I can put a branch with some of it and we can iterate, but it will be a big change (hopefully for the better)

**Comment by IsmaelMartinez** [comment]
Changing the colour of the icon might be easier, but it will not be as visible.

**Comment by IsmaelMartinez** [comment]
> @IsmaelMartinez `BrowserView` requires a BrowserWindow as parent. They're helpful if the app requires multi-tab support. A use case would be multi tenant support in the app.

Yes, I mean then you use only one BrowserWindow instead of many. The BrowserWindow is most of the memory footprint we have.

**Comment by aubertc** [comment]
Another option that may not be so memory-hungry would be to edit the current notification:

![Screenshot_20230830_105007](https://github.com/IsmaelMartinez/teams-for-linux/assets/16466689/613f8ca4-f9c5-4a83-9cfc-47ec3e026d1f)

to read "Stop sharing *windows 1*", or "Stop sharing *application X*", possibly with even more information displayed when hovering.

As of now, there is no way of knowing what is currently shared, which is annoying. Anything, even subtle, would help in my opinion.

**Comment by starek4** [comment]
Today I again shared something I did not want to my colleagues :smile: 

Can we do at least a red tray icon? Or some red dot on it? Would help me. I have tried that, but I am not sure where in the code detects that sharing is active or nor.

**Comment by IsmaelMartinez** [comment]
That is the main issue, we don't know when the sharing starts and/or ends. 

Unfortunately I can't look at it in MacOS as that functionality has never worked for me.

Maybe check around the https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/activityHub.js and see if MS does publish start/end screensharing events.

**Comment by lecler-i** [comment]
Shouldn't the red border thingy be done by [xdg-desktop-portal-wlr](https://github.com/emersion/xdg-desktop-portal-wlr) ?
As is this process that is being queried by electron to perform the actual choice of what is captured, and in charge of providing the buffers with the frames...
That would make it easier to implement and useful for more use-cases ?

Just my 2cents

**Comment by starek4** [comment]
> That is the main issue, we don't know when the sharing starts and/or ends.
> 
> Unfortunately I can't look at it in MacOS as that functionality has never worked for me.
> 
> Maybe check around the https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/tools/activityHub.js and see if MS does publish start/end screensharing events.

I am trying to move forward, but I am a bit stuck on my limited knowledge of Electron and front-end development.

So I have found out, that there is some event:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2153835/97cc3141-00e8-4e10-b4fe-94b353c1d248)
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2153835/29371110-a56a-4e57-8d7b-83207880499c)

But when I try to log when the event happens, it does not log anything:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2153835/36646144-4893-480d-acab-f7bc3e01a675)

Can someone with better knowledge about this point me what I am doing wrong?

**Comment by jijojosephk** [comment]
This can't take us anywhere as the new version of the teams is in `react` and our efforts would be wasted. Hence closing this issue.
