### ISSUE TITLE
Conflict with slack package

### ISSUE THREAD

**Issue by mbert** [IsmaelMartinez/teams-for-linux#614]
Got this when running `dnf update`:

```
Error: Transaction test error:
  file /usr/lib/.build-id/2a/33b622beae8c92a691c0056e2336ec75840301 from install of slack-4.28.182-0.1.el8.x86_64 conflicts with file from package teams-for-linux-1.0.38-1.x86_64
```

After removing slack things were OK. The error is reproducable with the latest slack package from [https://slack.com/downloads/linux](https://slack.com/downloads/linux).

**Comment by jijojosephk** [comment]
I'm not sure how to replicate this one. Are you using fedora? Can you give detailed steps?

**Comment by mbert** [comment]
Yes, Fedora 36. Steps are very simple: downloaded your rpm, installed it without problems. Then, when running dnf update I got that conflict with slack. It looks like that slack version you see above has just been updated to that version, since before there had not been any conflict.

**Comment by jijojosephk** [comment]
@IsmaelMartinez any guess here?

**Comment by IsmaelMartinez** [comment]
If you uninstall both packages (clean any cache) and then install them, do you get the same problems? Strange to see both packages sharing that lib and conflict. My thoughts are around OS /package manager/electron configuration playing a bit.

Try otherwise installing teams-for-linux with another package version. Hope helps!

**Comment by mbert** [comment]
> If you uninstall both packages (clean any cache) and then install them, do you get the same problems? Strange to see both packages sharing that lib and conflict. My thoughts are around OS /package manager/electron configuration playing a bit.

Yes, this seems to make sense: electron is something big both have in common.

For now, with the latest teams-for-linux release, the problem has been resolved. But of course we know that it may occur again as long as the root cause has not been identified. 

I am leaving this open for now, feel free to close it.

**Comment by jijojosephk** [comment]
@mbert closing this for now as there's nothing much can be done from the dev. Any challenges, please re-open, we'll try our best.

**Comment by muznyo** [comment]
I have same issue, but with [caprine](https://github.com/sindresorhus/caprine/pull/1969) package.
I was able to install it with rpm --force -i package.rpm

**Comment by nerijus** [comment]
Adding `%global _build_id_links alldebug` to the rpm spec file should fix this issue. Please see https://bugzilla.redhat.com/show_bug.cgi?id=1820370#c1 for the explanation.

**Comment by mbert** [comment]
The issue has reaappeared with slack-4.29.149-0.1.el8 today. Can you please reopen?

**Comment by IsmaelMartinez** [comment]
I suspect it will be easy to open this as an issue on slack instead of here. Slack has a huge company on the back of them while here we are just a few people. I do encourage you to investigate and see if you can find a solution that can help the community. Thanks in advance!

**Comment by nerijus** [comment]
The solution was posted - adding `%global _build_id_links alldebug` to the rpm spec file should fix this issue.

**Comment by josvo** [comment]
Same issue here.
There is a workaround for installing the package anyway, that does not use the sledgehammer as the `--force` flag. 
```rpm -i --excludepath=/usr/lib/.build-id/ teams-for-linux-1.0.45.x86_64.rpm```

The clean solution however would be to adapt the spec file as mentioned by @nerijus

**Comment by IsmaelMartinez** [comment]
Hi, that solution seems to be needed to apply to the electron-builder package. I suspect they will implement that solution at some point in the future. I might be wrong, and if so, if you reader can find where to add that `%global _build_id_links alldebug` to fix this issue, create a PR and I will gladly help with getting this sorted.
