### ISSUE TITLE
No Tray Icon on Wayland

### ISSUE THREAD

**Issue by Queuecumber** [IsmaelMartinez/teams-for-linux#615]
**Describe the bug**

I don't think this is a bug with this package per say but I haven't seen people talking much about it so I wanted to find out more about what's going on

I have this installed through flathub and when I launch with the wayland options `-enable-features=WaylandWindowDecorations --ozone-platform-hint=auto` I dont get a tray icon.

I'm launching it from the command line just to test and it seems like when I close the window it stays running in the background but there's no way to get the window back (or at least I haven't figured it out).

This is on Gnome 42 arch linux, not sure if this is a flatpak issue, an electron issue, a gnome issue, or a wayland issue. 

**To Reproduce**
1. `flatpak run --branch=stable --arch=x86_64 --command=teams-for-linux --file-forwarding com.github.IsmaelMartinez.teams_for_linux --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto`
2. Observe no tray icon

**Expected behavior**
It works the same way as xwayland or a native X session

**Desktop (please complete the following information):**
 - OS: Arch
 - Installation package flatpak
 - Version 1.0.41

**Comment by jijojosephk** [comment]
Which desktop environment?

I'm on KDE plasma. Seeing no issues.

![image](https://user-images.githubusercontent.com/11662148/194738514-3dedad17-fa8f-4388-bdba-edb5119599ef.png)

**Comment by Queuecumber** [comment]
Gnome 42 on arch Linux. I have an extension that shows the tray icons

**Comment by jijojosephk** [comment]
Which extention? Issue is only with teams-for-linux?  Do you have any other app to verify if it's related to electron?

**Comment by Queuecumber** [comment]
Extension is tray icons reloaded

It's not just teams for Linux, it seems to be any electron based app that I tell to run using Wayland. I posted here to see if I could get some help isolating the failure and because this seems to be the most active of the apps I'm using

I run many non elecron Wayland apps but I'm not sure if they have tray icon support, technically the tray is deprecated on gnome. I'll try to look into this. If you know of one I could try out let me know

**Comment by jijojosephk** [comment]
@Queuecumber you may try `bitwarden`

**Comment by Queuecumber** [comment]
Bitwarden is also using electron but I was able to play with the tray icon settings that it has and it indeed doesn't show any tray icon even if that option is enabled, however, exiting the application leaves it running in my terminal as though it was using a tray icon.

**Comment by Queuecumber** [comment]
OK I guess this was just an issue with tray icons reloaded, I tried another one and I get the tray icon for wayland apps on that.

**Comment by IsmaelMartinez** [comment]
You also got the option to start it with the "closeAppOnCross" (or
something like that) and the app will close when you click the cross. Not a
full solution but at least the app will not continue running.
