### ISSUE TITLE
Show video of all calling members in Video multicall

### ISSUE THREAD

**Issue by bernalvarela** [IsmaelMartinez/teams-for-linux#62]
Hello Ismael.

Your application is great!!, i've been using the ivelkov version for a while and i've discover today yours. You have done a great job.

The only thing i miss is, when i'm in a multi video call the ivelkov version shows all the members of the conversation, your version only shows the one who's talking, i think is much better the multi view option. 
Maybe this is related with the user agent, is there any way to change this behaviour?.

Thanks in advance for your work!.

**Comment by IsmaelMartinez** [comment]
Hi, can you post some pictures? I am off until mid next week so will not be able to much with this. 

Can you also try version 0.1.14? We only removed the user agent a couple of releases ago.

**Comment by bernalvarela** [comment]
I've tried both versions, 0.1.14 and 0.1.16.

In the oldest one it works as spected, in the 0.1.16 it only shows the video the one speaking.

![0 1 14](https://user-images.githubusercontent.com/6104507/54419236-3faa9d80-4707-11e9-9d79-3d37db1f9915.png)
![0 1 16](https://user-images.githubusercontent.com/6104507/54419237-3faa9d80-4707-11e9-97c2-8309cd90abba.png)

Maybe you could try to change the user agent only in this view.

Best regards!!.

**Comment by IsmaelMartinez** [comment]
Hi,

That will require a bit of a re-architecture as, from 0.1.15, we don't change user agent and we enable quite a few flags to allow desktop sharing, etc.

Basically, will be creating a config parameter where you can choose if to use the app like in version 0.1.14 or the current 0.1.16.

I leave it open to see if someone can have a look at it. Use version 0.1.14 until then if you want to use that view.

Thanks!

**Comment by bernalvarela** [comment]
SMaybe there's an option in the api to change the video behaviour.

Someone has access to the api definition?

**Comment by IsmaelMartinez** [comment]
MS... probably. I am not sure if this is browser spec so maybe looking into Chrome own API might help...

**Comment by julian-alarcon** [comment]
This maybe will be solved by Microsoft on Chrome: https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/What-s-new-in-Microsoft-Teams-the-Enterprise-Connect-feature/ba-p/376255

> Enhancements to the Chrome browser meeting experience (coming soon) are getting richer for Windows and Mac users. A year ago, we introduced frictionless meeting join in Chrome with no client needed. Coming soon, we will enhance that zero-footprint experience by adding 3 new capabilities: the ability to see participants video, application sharing, and full desktop sharing. This enables any meeting attendees to have face to face conversations and share content easily, with zero downloads needed.

**Comment by IsmaelMartinez** [comment]
I suspect ms will be using Chrome views (or implementation) what probably means that view is what you are going to get once they implement it... But we might just need to wait and see.

**Comment by Nullfati** [comment]
Hi @IsmaelMartinez,

Any updates about this issue?

**Comment by IsmaelMartinez** [comment]
Hi @Nullfati ,

No updates. MS is currently implementing the video conferencing/sharing for Chrome so no much point playing around this in the little time I got.

If you wish to, I think that will be possible by using Edge user agent (as from before version 0.1.15) but that will more than certainly remove the ability to do screen sharing.

Feel free to play around with it. As mentioned before, that should be configurable (that part is easy) as not everyone will want to have the view like in edge and loosing the screen sharing... At least until MS finish implementing it.

**Comment by IsmaelMartinez** [comment]
closing due inactivity. trying to keep things tidy.
