### ISSUE TITLE
Cannot find how to turn off notifications for started meetings

### ISSUE THREAD

**Issue by VGalata** [IsmaelMartinez/teams-for-linux#620]
Hello!

I updated my `teams-for-linux` to the lastest release `1.0.44` and now receive a notification for each started meeting (and we have many of these as we have many teams). I cannot find an option to turn these off and would appreciate any tip for how to do this.

**Comment by jijojosephk** [comment]
It's a known issue since yesterday after bringing in meeting notifications. Are you saying you don't want meeting notifications? Currently it shows all notifications pending in the queue. There's no filter to see whether the meeting time is over or not. We'll implement that soon.

**Comment by VGalata** [comment]
I am sure, yes. ^^ We have more than 17 channels with multiple meetings inside. You can image how many notifications we are getting right now.

**Comment by jijojosephk** [comment]
Added new command line flag `--disableMeetingNotifications` which will disable the meeting notifications in version `1.0.45`.

**Comment by mrkaczor83** [comment]
I got similar issue. It looks like MS Teams sends notification even if you are not invited to the meeting but you are in the teams group with the people invited. Is this true?

**Comment by VGalata** [comment]
We were definitely getting notifications for meetings we were not invited to.
Not sure about the second point (about the people from the same team) since we have one "team" but with many channels for the actual teams.

**Comment by jijojosephk** [comment]
I'm yet to figure out what's the logic MS does. May be we can have a filter on whether the person has accepted the meeting or not which is doable. But there might be situations where you're a required attendee but didn't confirm the availability which requires further research.

**Comment by jijojosephk** [comment]
I'm closing this as the flag helps to disable the notifications. Let me know if it does not work.
