### ISSUE TITLE
(electron) The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#630]
**Describe the bug**
API deprecation warning from electron.

**To Reproduce**
Warning shown when debugging the application locally with `yarn start` and when an external link is clicked.

**Expected behavior**
This is an API deprecation warning and must be handled for the future releases.

**Screenshots**
![image](https://user-images.githubusercontent.com/11662148/196034587-d3390a58-9f00-4069-a9e3-caed54008d07.png)

**Comment by IsmaelMartinez** [comment]
I have started the work in here: 

https://github.com/IsmaelMartinez/teams-for-linux/pull/713

**Comment by IsmaelMartinez** [comment]
pre-release in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.56

**Comment by jijojosephk** [comment]
Closing this it's fixed.
