### ISSUE TITLE
Bluetooth headset not properly working

### ISSUE THREAD

**Issue by rsysadmin-com** [IsmaelMartinez/teams-for-linux#631]
**Describe the bug**
Bluetooth headset is not recognized

**To Reproduce**
1. Connect your Bluetooth headset to your computer/laptop and test they work as expected
2. Place or receive an audio or video-call
3. Un-mute your headset (in my case, I use a Jabra Evolve2 65) by rolling down the mic
4. You can hear the caller through the headphones but your voice is sent through the built-in mic on your laptop

**Expected behavior**
Mic settings should appear under "Settings > Devices". Only the speakers part shows up.
Both elements of the headset must work in optimal conditions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Installation package DEB
 - Version 1.0.45

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi @rsysadmin-com , some people reported previously issues of not recognising mics. 

Can you have a look at this comment https://github.com/IsmaelMartinez/teams-for-linux/issues/317#issuecomment-582915199 and check previous options/solutions? I suspect MS is not detecting your headsets . Hope helps

**Comment by IsmaelMartinez** [comment]
closing due inactivity. I hope you managed to sort this out. Ping us if needs re-open
