### ISSUE TITLE
Cannot place test calls

### ISSUE THREAD

**Issue by rsysadmin-com** [IsmaelMartinez/teams-for-linux#632]
**Describe the bug**
Test calls are not possible

**To Reproduce**
1. Go to the Search bar
2. type `/testcall`
3. option is not found

**Expected behavior**
The test-call option should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/20558552/197240576-9c8f1acd-6710-4df3-aa72-0dae1df0d446.png)

`/testcall` is missing.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Installation package DEB
 - Version 1.0.45

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi @rsysadmin-com , this is a limitation on the website version. I suggest you open a feature request in the microsoft uservoice channel. Sorry about that,

**Comment by IsmaelMartinez** [comment]
There is already one request https://feedbackportal.microsoft.com/feedback/idea/6a0a5801-c6e1-ec11-a81b-000d3a03dba2 (probably more)
