### ISSUE TITLE
Device settings only enabled in a call

### ISSUE THREAD

**Issue by rsysadmin-com** [IsmaelMartinez/teams-for-linux#633]
**Describe the bug**
Device settings for audio or video are only made available during a call.

**To Reproduce**
1. Open Teams for Linux
2. Click "..." on the top right corner
3. Click on "Settings"
4. Unable to find the "Device Settings" menu

**Expected behavior**
Device settings should be available outside calls.

**Screenshots**
![image](https://user-images.githubusercontent.com/20558552/197241223-ce6abab9-c944-4fce-8b9d-349bde7861a2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Installation package: DEB
 - Version 1.0.45

**Additional context**

**Comment by IsmaelMartinez** [comment]
I think this is a limitation of the website version. Can you validate if you can see those settings in the browser teams version? Otherwise this will be a feature request for microsoft (for the browser version). Thanks

**Comment by IsmaelMartinez** [comment]
related to #374. Closing as this is a ms limitation
