### ISSUE TITLE
Teams only opens the first time

### ISSUE THREAD

**Issue by tothomweb** [IsmaelMartinez/teams-for-linux#634]
Dear all,
I'm facing a problem with teams-for-linux. When I install it it works as expected. However, after the first run, I'm not able to open it again. The console command gives no output and I'm not able to see any system log or error.
I'm running an Ubuntu 22.04

Thanks

**Comment by tothomweb** [comment]
More on that, if I delete the config files it still does not work but if I delete the entire folder: ~/snap/teams-for-linux/ it does run (but I have to login again)

**Comment by tothomweb** [comment]
The .deb version seems to work! Thanks for the help and for the project!

**Comment by IsmaelMartinez** [comment]
closing the issue then. If you start having problems, just re-open
