### ISSUE TITLE
Pen support for OneNote under Wayland

### ISSUE THREAD

**Issue by miromarszal** [IsmaelMartinez/teams-for-linux#638]
**Describe the bug**
When run with flags to enable Wayland, pen input is not registered.

**To Reproduce**
1. Start the app with `flatpak run com.github.IsmaelMartinez.teams_for_linux --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer`
2. Open a OneNote notebook.
3. Try to draw something with a pen. There is no input.

**Expected behavior**
Proper pen support with pressure sensitivity and a functional eraser.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - Installation package: flatpak
 - Version: 1.0.45

**Additional context**
Without the Wayland flags pen input works, but there is no pressure sensitivity and both the eraser and the secondary button do not work. The pen is fully functional in other apps, e.g., in Xournal++.

**Comment by IsmaelMartinez** [comment]
Hi @miromarszal , 

xournal++ seems to be written in C++. Do you know of another electron app that the pen works?

Difficult for me to check and/or test as I don't have neither linux nor a Pen.

If you can find an electron app where the pen works, we can try to find how they do it. Thanks!

**Comment by miromarszal** [comment]
I could find only one Electron app, the OneNote client: https://github.com/patrikx3/onenote
It has identical issues... If you are aware of any other Electron app with pen inputs, I'll be happy to test it.

**Comment by Thaodan** [comment]
I think you should look if Electron support pen input under Wayland,  all these apps just use Eletctron for input.

The sandbox that Flatpak uses Bubblewrap might also cause some issues, try running without it.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Ping to reopen
