### ISSUE TITLE
screen sharing doesn't work on Centos

### ISSUE THREAD

**Issue by chrisgns** [IsmaelMartinez/teams-for-linux#64]
Hi, 
I am using teams-for-linux-0.1.16-181.x86_64 on Centos 7, but trying to get screen sharing working I get the message that screen sharing is not supported by the browser version. 
On the system bot chromium and google-chrome is installed, and having both extensions
https://chrome.google.com/webstore/detail/microsoft-teams-screen-sh/dhheiegalgcabbcobinipgmhepkkeidk and
https://chrome.google.com/webstore/detail/enable-teams-calling/ifgnnjhhfdpjpjokajkolhioakajhidc
the screen sharing works in google-chrome. 

Is there anything  can do, to get teams-for-linux working?

Christoph

**Comment by IsmaelMartinez** [comment]
Hi, is this on 1to1 or group chat? I have seen that the 1st page that the app loads sometimes don't get the "screensharing" enabled. Can you check if by going to another group chat and then back to the one you where trying to use it works? Might need to increase the "timeout" that waits to enable the feature.

**Comment by chrisgns** [comment]
It just doesn't work, not 1to1 not in a meeting. It works in Chrome, anyway to enable some kind of debugging?

**Comment by IsmaelMartinez** [comment]
you can start the app with --webDebug and you will get the chrome devtools

**Comment by IsmaelMartinez** [comment]
Also, if you where using a previous version, you probably need to clean the cache/history. 

https://github.com/IsmaelMartinez/teams-for-linux#no-history

Let me know how you get on with that. I had a similar issue while testing the user agent just now and had to clean the "history"

**Comment by IsmaelMartinez** [comment]
Hi @chrisgns , I assume this is sorted, so I will close the issue. Reopen otherwise.

**Comment by chrisgns** [comment]
Sorry, I was away on a business trip. It doesn't work, I tried a second computer and deleted the history completely, but the camera for starting the video calls is still greyed out and is showing the tooltip that video is not yet supported in my browser.

**Comment by IsmaelMartinez** [comment]
Have you tried running from source? or dowloading the tar.gz and running it from there..

Or installing another package type... (snap or AppImage).

**Comment by chrisgns** [comment]
I tried rpm and tar.gz, both failed, I don't know how to run it from source.

Christoph

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by julian-alarcon** [comment]
Hi, I tried the master branch today on a VM with Centos 7, I can share the screen with no issues (some warnings but nothing critical), I even made a one to one and works with good quality (maybe the bug https://github.com/IsmaelMartinez/teams-for-linux/issues/61 is related with screen resolution as the VM has lower resolution)

```
[user@server1 teams-for-linux]$ yarn start
yarn run v1.15.2
$ yarn install && electron ./app
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder version=20.38.5
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=spellchecker

[8608:0322/095728.036972:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
[OpenH264] this = 0x0x174f5d0e6660, Warning:ParamValidation(), AdaptiveQuant(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x174f5d0e6660, Warning:ParamValidation(), BackgroundDetection(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x174f5d0e6660, Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
[OpenH264] this = 0x0x174f5d0e6660, Warning:Change QP Range from(0,51) to (26,35)
[OpenH264] this = 0x0x174f5d0e6660, Warning:ParamValidation(), AdaptiveQuant(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x174f5d0e6660, Warning:ParamValidation(), BackgroundDetection(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x174f5d0e6660, Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
[OpenH264] this = 0x0x174f5d0e6660, Warning:Change QP Range from(0,51) to (26,35)
[OpenH264] this = 0x0x174f5d0e6660, Warning:Actual input framerate 6.166700 is different from framerate in setting 15.000000, suggest to use other rate control modes
[8608:0322/095810.838240:ERROR:stunport.cc(87)] Binding request timed out from 192.168.100.x:47996 (eth1)
```
But the version 0.1.16 doesn't show the screen sharing option and the voice call option pop ups a warning about browser support.

Also, packaged master (currently 0.1.17) branch on .rpm, used it and worked fine.

So, I think that this can be mark as fixed and the next build version will fix your issue @chrisgns 

BTW, @chrisgns , if you want to test the source you have to install yarn, Nodejs, gcc-c++, make and libXScrnSaver. Then run `yarn install && yarn start` on the source code folder.

**Comment by IsmaelMartinez** [comment]
Hi @chrisgns ,

Can you check if the screenshare work if you set chrome as your default browser?

It should not be needed... but is one of those things that might be the reason... hope helps,

Ismael

**Comment by chrisgns** [comment]
Sorry for the late reply, but it still does not work. I was setting Chrome as default, bus nothing changed.

**Comment by jynolen** [comment]
Hello I got the same issue on fedora, I am using cinnamon desktop and it fails.
But it tried in oopenbox and it works

**Comment by IsmaelMartinez** [comment]
You might need to start then teams with and argument to tell it to use another "desktop".

I don't have the time this week but have a look at other close issues related to the icon don't looking right. It wasn't the solution but one of those "try this".

Sorry I can't be more useful this week.

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/issues/35#issuecomment-474760816
