### ISSUE TITLE
cannot seem to get app to recognise speakers. 

### ISSUE THREAD

**Issue by astrosteph** [IsmaelMartinez/teams-for-linux#642]
no sound for notifications or calls etc. worked fine in other apps, but cannot seem to find speakers. this includes in the device settings, it just shows default constantly. doesn't work with in-built speakers or headphones through aux. 

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - deb

**Comment by IsmaelMartinez** [comment]
Hi @astrosteph ,

Sorry to hear that. Do the sound work when using the browser? 

Other people had problems in the past but is normally their individual OS configuration or MS not accepting bluetooh speakers. Check previous close issues and see if they can help 

https://github.com/IsmaelMartinez/teams-for-linux/issues?q=is%3Aissue+audio+is%3Aclosed

Not sure if Linux Mint uses pulseaudio but some users did report re-configuring it worked.

Hope helps!

**Comment by IsmaelMartinez** [comment]
closing due inactivity. Do please ping with more info if you still got problems and/or if you found a solution. Thanks !
