### ISSUE TITLE
Corporate account authentication with smart-card

### ISSUE THREAD

**Issue by KIX-RTOS** [IsmaelMartinez/teams-for-linux#645]
I work under Linux and I use Teams to communicate with my colleagues,
authentication goes with smart-card under ADFS domain.
In Google Chrome Teams web-app this feature works fine but teams-for-linux like official client from Microsoft
doesn't show certificate selection dialog and I get an authentication error.

I think the smart-card authentication feature implementation is a good idea.

**Comment by IsmaelMartinez** [comment]
I wonder if you can investigate around maybe checking if this library does the job? https://www.npmjs.com/package/smartcard Hope helps

**Comment by alexey-artyushkov** [comment]
I think it would better to use https://www.npmjs.com/package/node-ssl because it uses the NSS which gives secure and standard access to smart cards, usb-tokens and etc

**Comment by IsmaelMartinez** [comment]
@alexey-artyushkov , see if you can integrate it.

We will probably need to put it on the back of a config option if it blocks people not using/having smart-cards, but it will be a great addition.

I have no means to try/test this, nor much time, so I am unfortunately not much help.

**Comment by alexey-artyushkov** [comment]
Thanks a lot)

**Comment by IsmaelMartinez** [comment]
Open a wee PR and maybe we can see help to get it sorted and released.

**Comment by jijojosephk** [comment]
@KIX-RTOS if you're not seeing the certification selection dialog in the app but you see in browser, there must be something we can do. Could you provide some screenshots of working and not working scenario. I've never seen such a setup so don't know where to start.

**Comment by KIX-RTOS** [comment]
I realised the why this problem occured - it's not application problem but it's snap's problem. Same issue occurs in Firefox and Chromium if you install them from snaps (https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1859643)

**Comment by IsmaelMartinez** [comment]
@KIX-RTOS , it will be amazing if you can put some documentation on how you fixed this. 

Maybe a wee section in the https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md can help others with this issue. 

Really appreciate if you can spare a wee bit of time on that. It will help the community lots. Thanks in advance!

**Comment by IsmaelMartinez** [comment]
(or even a wee message here with a bit more description on how did you manage, can help a lot of people). I will leave it open for a few more days. Glad to managed to fix it. Thanks again!

**Comment by mauriziopinotti** [comment]
I had a similar need, came up with this PR to fix it: https://github.com/IsmaelMartinez/teams-for-linux/pull/688

**Comment by IsmaelMartinez** [comment]
left a wee comment (increase the package.json version) but that should be almost ready for release! Thanks for contributing!!

**Comment by IsmaelMartinez** [comment]
I will close this issue as completed. Please ask to re-open if the solution @mauriziopinotti doesn't work for you. Thanks a log @mauriziopinotti for your contribution!!

https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.50

**Comment by EvilWatermelon** [comment]
But how can I use it now? There is no way to add security devices or something similar to add my smartcard reader.
