### ISSUE TITLE
Is this app supposed to work from behind proxy?

### ISSUE THREAD

**Issue by Lancer11211** [IsmaelMartinez/teams-for-linux#647]
I've tried the flatpak version but it can't load any chat. The appimage version immediately quits after I click on "Submit" at the login. Both of those were fresh installs.

**Comment by IsmaelMartinez** [comment]
check the config options https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config . You can supply a proxyServer that might work. I haven't tried myself. Hope helps

**Comment by jijojosephk** [comment]
@Lancer11211 let us know if you were able to make it work as suggested by @IsmaelMartinez

**Comment by IsmaelMartinez** [comment]
closing due inactivity. Do ping us if you need any more help. Thanks!
