### ISSUE TITLE
`Realtime AudioW` trap int 3 (complete crash, needs restart of program)

### ISSUE THREAD

**Issue by whisperity** [IsmaelMartinez/teams-for-linux#649]
**Describe the bug**
Randomly(?) Teams decides to close itself, requiring a full restart of the program and a full re-login. The logs reveal a signal trap causing the crash.

**To Reproduce**
Inconclusive. I've been sitting in a meeting for a long time and experienced multiple crashes. The issue started happening when Teams's UI changed to the newer style (in synch with what Windows people are having) where the menu is on the top. As long as the menu was in the middle of the meeting screen (old-style UI), these crashes were not prevalent.

**Expected behaviour**
No crashes, or at least a meaningful log.

**Screenshots**
```
Dec  2 10:57:27 hostname kernel: [ 8209.886646] traps: Realtime AudioW[8627] trap int3 ip:55c4ffd1cd3f sp:7f407ffd9a90 error:0 in teams-for-linux[55c4fc83c000+7187000]
Dec  2 12:46:38 hostname kernel: [14761.026328] traps: Realtime AudioW[22448] trap int3 ip:564d7c9bfd3f sp:7fea90f9caa0 error:0 in teams-for-linux[564d794df000+7187000]
---- reboot ----
Dec  1 10:27:01 hostname kernel: [ 9657.947124] traps: Realtime AudioW[38730] trap int3 ip:55a88f3e7d3f sp:7f660c91fa90 error:0 in teams-for-linux[55a88bf07000+7187000]
Dec  1 12:28:03 hostname kernel: [16919.336019] traps: Realtime AudioW[55243] trap int3 ip:556f3528ed3f sp:7fa845e2da90 error:0 in teams-for-linux[556f31dae000+7187000]
Dec  1 14:46:15 hostname kernel: [25212.058606] traps: Realtime AudioW[102887] trap int3 ip:55703603dd3f sp:7f3f7f0b3a90 error:0 in teams-for-linux[557032b5d000+7187000]
```

In every case, the symbol offset is the same, so I'd guess the issue is in the built binary. The ip and sp registers and the map location of the executable are different, but that is very likely due to ASLR.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS "Focal Fossa" (with KDE)
 - Installation package: [DEB from GitHub releases page](http://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.45)
 - Version: [1.0.45](http://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.45)

**Additional context**
I have a wireless headset that is mounted with the A2DP (audio sink) profile, i.e. it only acts as a speaker. (Instead of HDP, where mono audio is connected in both directions with the wireless device.) For a microphone, I use a USB microphone.

Could you please advise what logs I could gather and from where to help debug this?

**Comment by IsmaelMartinez** [comment]
Hi,

Not really sure, tbh, but that sort of stuff is normally related to grphic card.

See if you can disable "acceleration" in the teams settings.

Hope helps!

**Comment by JeffDess** [comment]
I got a similar issue after connecting BT headset and changing HSP/HFP to A2DP while Teams was open. System froze completely for about 10-15 seconds, then I got the mouse back but the keyboard would not respond and whole system was overall still very slow. I managed to recover by attempting to close the session then cancelling. The app itself did not crash.

Here's an excerpt from the log (`dmesg`)

```
[12841.798001] traps: teams-for-linux[12141] trap invalid opcode ip:5580c5f85654 sp:7ffd678f15b0 error:0 in teams-for-linux[5580c2c37000+7187000]
[12862.000585] input: WH-1000XM3 (AVRCP) as /devices/virtual/input/input39
[15624.474641] br-dc8ba2742209: port 3(veth1c14c67) entered blocking state
[15624.474644] br-dc8ba2742209: port 3(veth1c14c67) entered disabled state
[15624.474697] device veth1c14c67 entered promiscuous mode
```

I disabled acceleration in Teams, restarted the app, then tried to do the same steps a couple of times and was not able to reproduce. Not quite sure Teams was the cause here, however it has much in common with this issue.

Desktop:
* OS: Arco Linux KDE
* Installation package: AUR
* Version: 1.0.45-2

**Comment by whisperity** [comment]
> I disabled acceleration in Teams

Where do you find this option? I can't seem to be able to find it. Although recently I did not have *very long* meetings so the issue did not persist.

> [12862.000585] input: WH-1000XM3 (AVRCP)

Exact same device, wow! :rocket:

**Comment by JeffDess** [comment]
@whisperity The setting is rather called "animations" https://github.com/IsmaelMartinez/teams-for-linux/issues/652#issuecomment-1340996104
