### ISSUE TITLE
Right click link -> copy not working

### ISSUE THREAD

**Issue by PauloGDPeixoto** [IsmaelMartinez/teams-for-linux#650]
**Describe the bug**
I right click a link in teams and select copy, but the link is not copied, thus, I'm not able to paste it anywhere.

**Desktop (please complete the following information):**
 - OS: Linux
 - Flatpak
 - Version 1.0.45

**Comment by IsmaelMartinez** [comment]
i @PauloGDPeixoto , can you try with another packaging system like rpm or deb? Just in case is something todo with flatpak. Thanks

**Comment by PauloGDPeixoto** [comment]
Thanks for your reply, @IsmaelMartinez :) I tried the rpm package and the behavior is the same. I've explored a little further and found that in some particular cases it works, but in others it doesn't. I'll break these down below:

Works:

- Copying from a chat, in the Chat section, but not in the chat inside a meeting;
- clicking the "copy" icon in a meeting card in the calendar.

Doesn't work:

- Copy link from inside meeting details in calendar;
- Copy link from any channel;
- Copy link from meeting chat (inside meeting).

These are the cases I was able to catch. In the chat/channel cases where it doesn't work, I'm able to select and copy with ctrl+c, but this obviously doesn't work for the meeting details, where the url is hyperlinked.

**Comment by IsmaelMartinez** [comment]
Hi @PauloGDPeixoto ,

We use this library https://github.com/mixmaxhq/electron-editor-context-menu for the right click menu. It looks it is not fully maintained and I suspect electron might provide an "out of the box" solution for this.

I am not sure when I will have time for this, but will try to investigate a bit more next week. If you can dig around "electron" and "right click menu" and see if you can find something, that will be amazing (and might make this faster to solve)

Thanks in advance!

**Comment by PauloGDPeixoto** [comment]
@IsmaelMartinez, after digging a while, it seems that electron does not, indeed, provide an out of the box solution, it is expected that everyone develops their own context menu.
That being said, I found an alternative that seems to be more up to date:
https://www.npmjs.com/package/electron-context-menu
https://github.com/sindresorhus/electron-context-menu

**Comment by MichaelGrupp** [comment]
Not sure if it's related, but when I try right-clicking to copy something via context menu the app freezes for a few seconds.

**Comment by jijojosephk** [comment]
As the current version is `1.0.71`, I would request to re-test. I'm not able to produce the issue. Please re-open if required.

**Comment by MichaelGrupp** [comment]
> As the current version is `1.0.71`, I would request to re-test. I'm not able to produce the issue. Please re-open if required.

It works now with that version on my computer, thanks!

**Comment by PauloGDPeixoto** [comment]
I'm sorry, but at least for me, it's still not solved, I'm attaching a video of the issue (running version 1.0.71):

https://user-images.githubusercontent.com/20384915/234540860-c807bcce-38f3-42ee-80a8-ec0059a36baf.mp4

**Comment by jijojosephk** [comment]
@PauloGDPeixoto so you're not able to copy the link without selecting it. I would have a look.

**Comment by PauloGDPeixoto** [comment]
Precisely, it's working better, but this bit is still lacking. Thanks!

**Comment by jijojosephk** [comment]
Also, the `Writing Languages` should not be there because it's not a place type in something.

**Comment by jijojosephk** [comment]
@PauloGDPeixoto new build on it's way.

**Comment by jijojosephk** [comment]
`1.0.72` is out.

**Comment by PauloGDPeixoto** [comment]
Thank you, @jijojosephk, now it works as expected!
