### ISSUE TITLE
Video of myself is no longer mirrored

### ISSUE THREAD

**Issue by cs96and** [IsmaelMartinez/teams-for-linux#653]
**Describe the bug**
During a video call, the window showing the video of myself is no longer mirrored (reversed).

**To Reproduce**
1. Start a video call
2. Enable the webcam
3. See that the video of yourself is no longer mirrored.

**Expected behavior**
The video of myself should be mirrored

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Installation package: deb
 - Version 1.0.45

**Additional context**
Only started happening in the last week or so.

**Comment by cs96and** [comment]
I can't see any settings to do with reversing the video.

I get the same behaviour on the PWA in a browser too.

**Comment by IsmaelMartinez** [comment]
Check then in MS feedback portal, they should be able to help you. https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

**Comment by jijojosephk** [comment]
@cs96and  This is more of a PWA issue. Closing this now. Please report if you think this can be fixed.
