### ISSUE TITLE
Linux freeze

### ISSUE THREAD

**Issue by antonio-petricca** [IsmaelMartinez/teams-for-linux#654]
A experienced many linux freezes.

The solution maybe disabling the hardware acceleration, but I don't known the options in the settings panel.

Thank you so much!

**Comment by IsmaelMartinez** [comment]
Hi @antonio-petricca , can you try if it is the same as #652 ? (disable the right click option and see if it does anything)

**Comment by antonio-petricca** [comment]
Thank you, I am trying your suggestions...

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Ping to reopen
