### ISSUE TITLE
Stuck at "checking your credentials"

### ISSUE THREAD

**Issue by amenk** [IsmaelMartinez/teams-for-linux#657]
**Describe the bug**

Out of nowhere, when loading the app, it stuck.

**To Reproduce**
1. Start teams-for-linux
2. See error

```
node:electron/js2c/renderer_init:73 Unable to load preload script: /opt/teams-for-linux/resources/app.asar/app/browser/index.js
(anonymous) @ node:electron/js2c/renderer_init:73
node:electron/js2c/renderer_init:73 TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at /opt/teams-for-linux/resources/app.asar/app/browser/index.js:55:9
    at Object.<anonymous> (/opt/teams-for-linux/resources/app.asar/app/browser/index.js:84:2)
    at Object.<anonymous> (/opt/teams-for-linux/resources/app.asar/app/browser/index.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at i._load (node:electron/js2c/renderer_init:33:356)
(anonymous) @ node:electron/js2c/renderer_init:73
3/opt/teams-for-linux/resources/app.asar/app/browser/zoom.js:41 Current zoom level: 0
/opt/teams-for-linux/resources/app.asar/app/browser/zoom.js:41 Current zoom level: 0
```

**Expected behavior**
Teams initalizes

**Screenshots**
![Checking your credentials...](https://user-images.githubusercontent.com/1087128/207605263-02242ec6-b6bd-4493-a94e-adb2954d21d4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package [deb
 - Version 1.0.46

**Additional context**

* tried apt purge teams-for-linux + reinstall `sudo dpkg -i teams-for-linux_1.0.46_amd64.deb`
* Tried to clean cookies via the web-debug tools
* Opening the Chrome PWA works fine
* Tried logout / rebooting -> no improvement

**Comment by amenk** [comment]
Okay, I realized it was never really closed. In the meantime I tried

```
teams-for-linux --clearStorage
```
but it had no effect.

Now I found that there are still active processes.

```
pkill teams-for-linux
teams-for-linux
```

and it works.

Sorry for the noise.

**Comment by badjuice** [comment]
This solved my issue, thanks @amenk

**Comment by tmkasun** [comment]
The same issue happens to me in Ubuntu 22. I was able to get the app running by doing a hard refresh using 
- Focus on the white window
- Press `Ctrl + Shift + I` (Open Dev Console)
- and then `Cttrl + Shift+R`
