### ISSUE TITLE
Snap package often asks for changing "default uri scheme handler"

### ISSUE THREAD

**Issue by MrFly** [IsmaelMartinez/teams-for-linux#658]
**Describe the bug**
On nearly every startup (at least once a day) the app asks to change the default uri scheme handler (msteams) to teams app

**To Reproduce**
- Install the app from snap
- Open the app

**Expected behavior**
The app should start without the question / dialog box once the question was accepted

**Desktop (please complete the following information):**
 - Ubuntu 20.04.1
 - Installation package: Snap
 - Version: 1.0.45

**Comment by IsmaelMartinez** [comment]
hi @MrFly , can you try with another packaging system?

**Comment by MrFly** [comment]
Hi @IsmaelMartinez,

Thanks for your fast reply. I could try, but I already know, that this message is "snap specific". The youtube music app has the same problem since months. I don't know how to fix this, or any workaround for the user, but some other apps fixed this (found in some reported and fixed issues on github). So it should be possible in any way (?).

Since this is a work pc I'm not allowed to install something like "standalone" deb packages (or use flatpak), if they are not automatically maintained (by a Ubuntu repository or something), so unfortunately it's not that easy (legal) for me to "simply use other packages".

But if I can help in any way, please let me know :-)

**Comment by IsmaelMartinez** [comment]
maybe try the flathub ? or feel free to put a PR in (or find out how others fixed this in github). It might go away when I update electron to a newer version, but I don't have an eta for it/sorry.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Ping to reopen
