### ISSUE TITLE
Devices submenu in Settings

### ISSUE THREAD

**Issue by liedekef** [IsmaelMartinez/teams-for-linux#659]
In the Settings menu, the Devices submenu is missing. While in a call, I can access/set the device settings, it would be nice to set these correct without actually needing to make a call. The "old" linux client had this present, together with the "secondary ringer" option. The current web interface on gnome does not though ...
So, if at all possible: bring back the Devices menu (and the secondary ringer option).

**Comment by IsmaelMartinez** [comment]
Hi, this is a limitation from the web client so you should request this in the ms feedback portal.

https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

Hope helps
