### ISSUE TITLE
Provide snap package on official Snapcraft/Snap Store

### ISSUE THREAD

**Issue by benyanke** [IsmaelMartinez/teams-for-linux#66]
Any thoughts of putting this in the snap store so it can be easily installed and automatically updated.

**Comment by IsmaelMartinez** [comment]
Happy to support you on that. I can't test the snap packages myself so I can't really take the task. Anyone interested?

**Comment by benyanke** [comment]
If you wire up the new-snap-on-commit CI piece, so the snap stays up to date (one of the big reasons for doing it), I can test it.

**Comment by julian-alarcon** [comment]
Right now I'm testing snaps builds, but yeah, the idea will be to publish it in the Snap Store, I just don't know if there are any issues if in the name of the snap/app we refer to an specific defined brand (Microsoft Teams / Teams For Linux).

**Comment by benyanke** [comment]
Perhaps https://twitter.com/popey might be a good person to kick this discussion off with - no doubt it would be a great add to the store, but getting in trouble and getting it removed isn't good either.

**Comment by benyanke** [comment]
@popey might tag him too

**Comment by popey** [comment]
A wild @popey appears!
I would agree that you might want to steer away from trademarked terms, if possible :) 
If you're confident that you're safe there - or indeed have permission from the trademark holder, then by all means push the snap to the store.

**Comment by benyanke** [comment]
Thanks @popey  - given those constants, is there any way to publish a tool like this (if you haven't looked closer, it's basically a native-ied web wrapper for MS teams) perhaps by naming it something else? Or is a tool like this simply off limits based on it's content?

**Comment by IsmaelMartinez** [comment]
maybe teams-for-linux will be better... anyone from MS watching can let us know otherwise. ;) 

@popey Thanks for the input.
@benyanke and @julian-alarcon , I leave it in your capable hands, while I try to fix/improve other stuff. If needed to move from Travis to Gitlab let me know. I don't have any strong attachment with travis.

**Comment by benyanke** [comment]
I think any CI system should work, but I'll dive in and see to be sure. We may have to coordinate to get it set up but I'm sure it will work fine. If it's easier, I could also fork the repo, connect that one to the store, and add you as an admin on the repo, so you don't need to worry about the CI and connection to the snap store. Whichever works for you.

**Comment by popey** [comment]
@benyanke there are a few other snaps which are essentially web wrappers in the store. That's cool beans to me.

**Comment by benyanke** [comment]
So as long as we call it something like "Teams for Linux" instead of "Microsoft Teams", we're good?

**Comment by popey** [comment]
🤷

**Comment by benyanke** [comment]
Ha - fair enough. Thanks again, @popey.

**Comment by IsmaelMartinez** [comment]
I added you and Julian as collaborators. Let me know if that does it. 1st 2 collaborators! I might have a bit of time this Saturday to play around with it.

**Comment by benyanke** [comment]
I've registered the snap name `teams-unofficial` and will begin attempting to get this set up.

**Comment by julian-alarcon** [comment]
I registered the ```teams-for-linux```. @popey / @IsmaelMartinez  which one do you think that is better to use, ```teams-unofficial``` or ```teams-for-linux```?

**Comment by IsmaelMartinez** [comment]
For consistency sake... teams-for-linux

**Comment by IsmaelMartinez** [comment]
But happy with either

**Comment by benyanke** [comment]
Sounds good - do you want to add me as a co-admin @julian-alarcon on the snap side, or do you plan to run it solo? I'm fine with either.

**Comment by benyanke** [comment]
Also, related:

https://docs.travis-ci.com/user/deployment/snaps/

**Comment by benyanke** [comment]
containerized snap builds tested and working via ./dockerBuildSnap.sh, allowing easy reproducible builds

**Comment by julian-alarcon** [comment]
Ben, what is your Snapcraft registered email to add you to the admins? Please don't release on stable/beta channel, keep it for now on `edge`

**Comment by benyanke** [comment]
Emailed you directly - sounds good about the channels.

**Comment by julian-alarcon** [comment]
Ok, I just uploaded the version 0.1.17 to make some testing (edge channel), I needed to make a little change to the executable (I will upload it to an specific branch and ask for merge on master(?) @IsmaelMartinez do you want to create a develop branch or a new 0.1.18 branch?)

```
snapcraft push --release=edge teams-for-linux_0.1.17_amd64.snap
Preparing to push 'teams-for-linux_0.1.17_amd64.snap'.
After pushing, an attempt will be made to release to 'edge'
Pushing 'teams-for-linux_0.1.17_amd64.snap' [================================================================================================================================================================] 100%
Processing...|                                                                                                                                                                                                     
Ready to release!
Revision 1 of 'teams-for-linux' created.
Track    Arch    Channel    Version    Revision
latest   amd64   stable     -          -
                 candidate  -          -
                 beta       -          -
                 edge       0.1.17     1
The 'edge' channel is now open.
```

Installation and execution worked fine (adding, for now, the edge option):

```
sudo snap install teams-for-linux
error: snap "teams-for-linux" is not available on stable but is available to install on the
       following channels:
       edge       snap install --edge teams-for-linux
       Please be mindful pre-release channels may include features not completely tested or
       implemented. Get more information with 'snap info teams-for-linux'.
1 julian@mypc:~/Code/teams-for-linux/dist$ sudo snap install teams-for-linux --edge
```
Once we have the CI/CD in place we can then deliver to other channels. Also @IsmaelMartinez , do you want to use all the channels (stable/candidate/beta/edge) or any specific for this?

Also, @benyanke I added you as collaborator for this snap, if you want to keep making test, remember to only upload to edge for now.

**Comment by IsmaelMartinez** [comment]
@benyanke  and @julian-alarcon , great work guys.

happy to be added as a collaborator to the snap. 

I normally create a branch with the next version number, make my changes, and PR to master. In this case is 0.1.17, as this still to be released.

Travis gets a bit temperamental if I update the version directly in master, but sometimes I do if I get a direct pull requests.

Happy to accommodate another structure and to move from travis to gitlab if it eases the process (travis can be a bit of a pain) 

Over the years I have learn to keep it simple, so maybe the best approach is to only have stable and edge. At least until we see the need of other channels.

But I am don't know much about snap channels and how people use them.  

Regarding what to publish to what, I will say that, if we follow the previous branching strategy, we should be able to configure the CI to publish to edge (for branches) and stable (for master) by checking the branch the build is happening.

Again, lets keep it simple, so that might be version 2 or 3. Get it release to edge and we can stabilise later. 

Happy to discuss further and to accommodate to other options. Thanks again!! 

ps: trying to help but pretty busy currently with work and life!

**Comment by julian-alarcon** [comment]
Of course @IsmaelMartinez that I can add you as a collaborator! (I can even ask to pass you the authoring if you want to).

Just give me your mail on Snapcraft https://snapcraft.io/account (You can mail me, my address is in my profile)

About the number of channels, 2 is ok (edge/stable) from my side. So, to keep things a cleaner, after a release, can you create the next branch version to push features/bugfixes to that specific branch and keep master clean?

**Comment by IsmaelMartinez** [comment]
yep, I tend to do that. 0.1.17 is, at this moment in time, a bit out of date with master. I will just do a quick refresh to it.

**Comment by IsmaelMartinez** [comment]
I have updated the 0.1.17 branch with the latest code.

I am preparing a release so I am going to close this issue and create another regarding the automation of the snap release (integrate with Travis). Also, we will stop spamming @popey. 

I will also create a wee project in here so we can track more easily what goes in version 0.1.18. Might be better not to commit to master directly but do it in the 0.1.18 (I will create a branch as soon as the 0.1.17 is out of the door).

Thanks,
