### ISSUE TITLE
Uploading a file from a non root location fails

### ISSUE THREAD

**Issue by docquantum** [IsmaelMartinez/teams-for-linux#660]
**Describe the bug**

Whenever I try to upload a file not on the root drive, it fails once it gets roughly halfway. File upload works fine if I upload a file from the root system drive.

**To Reproduce**
1. Go to a direct message.
2. Find a file that isn't on the system root drive and try to upload it.
3. It should fail with "Something went wrong while sharing. Let's try again."

**Expected behavior**
The file should upload, show up in the "Files" tab, and be accessible to whomever I send it to.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package: snap store
 - Version 1.0.47

**Additional context**
I assume this is some quirk with snaps since they're normally containerized. I will have to install the "deb" version and see if I can reproduce the issue there.

**Comment by IsmaelMartinez** [comment]
Hi @docquantum , thanks for reporting. That is strange. How did you get on with deb? I do think is snap also... but will be good to know if you managed to sort the issue by using the deb package.

**Comment by docquantum** [comment]
Hi @IsmaelMartinez, I installed the deb version and tried to upload a file from a non-root location and it uploaded with no issue. I then opened up the snap version again and tried to do the same with the same file and it failed like described in the issue.

I think it may have something to do with permissions with snaps since they are a lot more locked down with the whole sand-boxing process. I don't know if there's any way to explicitly enable permissions for a snap as part of an installation, or if the user would have to adjust some settings via command line to do so.

I would prefer to use the snap variant to make updates easier and more automatic, but I can live with manually taking care of that for now.

Let me know if there's anything I can do for testing and help if need be.

**Comment by docquantum** [comment]
Odd quirk, but it looks like the version on "snap" is 1.0.47 which has not been released or tagged on GitHub. This is likely a different issue entirely however.

**Comment by docquantum** [comment]
Looking more deeply into this, it seems as though this is an intended feature of `snap` and not really an issue here at all.

`snapd` only allows a few set locations for an application to access as part of the sandboxing process. Since all of my network and non-root drives are mounted under `/mnt`, `snapd` does not allow access. I can workaround this by modifying the `snapd` connections as part of my system/user startup so that snap applications have access to locations which are not allowed by default.

Essentially, aside from adding this to the readme as a note, I don't think it can be fixed from the application standpoint. It's a system administration issue.

References:
- [snapd launchpad bug report about hardcoded paths](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1643706)
- [SO answer that concludes paths are hardcoded](https://askubuntu.com/a/1033617)
- [SO answer with mount binding workaround](https://askubuntu.com/a/1384789)
