### ISSUE TITLE
Have a starting argument to switch to the old Teams UI

### ISSUE THREAD

**Issue by j-fraga** [IsmaelMartinez/teams-for-linux#662]
When in a meeting, Teams used to show the following floating box:

![image](https://user-images.githubusercontent.com/38435343/208399640-b9ab98e9-5a77-40f1-b104-e2b148603eb9.png)

which, not only would disappear when there was no mouse activity, it also had an option to have a true full screen (that is, without borders, bars, etc.)

At some point, Microsoft switched to a new UI which is now unable to do a true full screen. The following bar is always at the top:

![image](https://user-images.githubusercontent.com/38435343/208400122-a0eef9e7-d428-4da2-b499-453668ff04c9.png)

and there's also a bar at the left side of the screen. In other words, the screen other participants are sharing is always resized to a smaller size to make room for the permanent bars.

The official Linux Teams still uses the old UI, and the old UI also was used in teams-for-linux up until 2 months ago. 

I'm wondering if there's some option that teams-for-linux can pass to the server in order to load the old UI, which I prefer a lot more.

**Comment by IsmaelMartinez** [comment]
Hi @j-fraga , I don't think this is possible. The way to use the old ui will be to use an old browser user agent, but that then blocks the app as the browser "is not supported". I might be wrong so feel free to explore the angular UI settings. 

There might be a way to change those settings liken in here https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/browser/index.js#L32 but that has proven previously to be really flaky.

**Comment by jijojosephk** [comment]
@j-fraga, it cannot be easily controlled. MS changed something. Sorry.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Ping to reopen

**Comment by j-fraga** [comment]
Quick update. Found out that if I start **teams-for-linux** as follows:

`teams-for-linux --chromeUserAgent "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0"`

I get the old UI back with the lovely true full screen mode option!

Mind that a couple of things get missing when starting with the above option. For example:
- Speaker selectbox in "Device Settings"
- Noise suppression setting
- Reactions while in a meeting

None bother me because I have a noise suppression microphone and have always the option to select the speaker via PulseAudio's `pavucontrol`, if needed.
