### ISSUE TITLE
Option to set a custom tray icon

### ISSUE THREAD

**Issue by jonath92** [IsmaelMartinez/teams-for-linux#665]
First thanks for the app - really useful. 

I am using teams for two organisations for which teams is really bad as I can only be logged in to one organisation at a time which means that I am only getting notifications for one organisation and I need to always authenticate  when I switch. So my idea is to use two instance of this app (simply installing one with apt and one with snap) and use two different tray icons but I couldn't figure out a convenient way to do this. With `apt` I tried replacing all the images with: `sudo cat /var/lib/dpkg/info/teams-for-linux.list | grep png | sudo xargs -n1 cp ~/Downloads/my-icon.png` but in the tray still the default icon has been used.  The only way which worked for me was building it my self and replacing the icons in the `assets` dir...

**Comment by IsmaelMartinez** [comment]
I think there is a config option that you can use. I haven't tried but you can try to put a full path location to it and see it tat does the trick? 

It's called `appIcon`. it might not work in snap due the security constraints but happy for you to add another icon into the assets if that doesn't work ;)

https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config

**Comment by jonath92** [comment]
yes that's working thank you. No idea how I managed to overlook the option even though I looked at the help :laughing:

**Comment by IsmaelMartinez** [comment]
Nice! Glad is working for you.
