### ISSUE TITLE
Electron version upgrade

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#671]
**Describe the bug**
Electron version upgrade.

**To Reproduce**
NA.

**Expected behavior**
NA.

**Screenshots**
NA.

**Desktop (please complete the following information):**
 NA.

**Additional context**
NA.

**Comment by jijojosephk** [comment]
`
yarn upgrade v1.22.19
[1/4] Resolving packages...
warning electron-editor-context-menu > lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
warning electron-builder > app-builder-lib > electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
warning electron-builder > app-builder-lib > @electron/universal > asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
error An unexpected error occurred: "https://raw.githubusercontent.com/ismaelmartinez/electron-dl/9950cc6b287eab18bbb8a109f33467db37205f88/package.json: connect ECONNREFUSED 49.44.79.236:443".
info If you think this is a bug, please open a bug report with the information provided in "/home/jjoseph/Projects/teams-for-linux/teams-for-linux/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
`
@IsmaelMartinez  error at ismaelmartinez/electron-dl

**Comment by IsmaelMartinez** [comment]
I will see if i can have a look. Maybe we can remove that option

**Comment by IsmaelMartinez** [comment]
I will see if i can have a look. Maybe we can remove that option

**Comment by jijojosephk** [comment]
If it's not required, we can remove it. But I see one problem with upgrade. Tray icon missing. (Ubuntu 22.04, Budgie)

**Comment by IsmaelMartinez** [comment]
it is a feature to automatically download the files onto the download folder 

| useElectronDl | Use Electron dl to automatically download files to the download folder | false |

I had to branch that project so I can probably either unbranch it (and point to the main one if it works now) or update it. But will see when I got time (hopefully at some point today...)

**Comment by IsmaelMartinez** [comment]
hey, I have sync that project with the fork that I had and now it might work. Not sure when I will be able to test it... if you that will be amazing. Otherwise I will try to do it at some point in february!

**Comment by pezz** [comment]
Random question: is there any way to fake the user agent sent in the meantime?

I recently had to reinstall and login again. I have to use Duo for 2FA and it now blocks me due to how old the reported Chrome version is.

Cheers.

**Comment by IsmaelMartinez** [comment]
hi @pezz , check the https://github.com/IsmaelMartinez/teams-for-linux/issues/678 config options. I think the chromeuseragent is what you are looking for.

**Comment by pezz** [comment]
I ended up grepping for chromeuseragent and found references to it. I eventually worked out and made a config.json and have been able to set chromeUserAgent but Duo is still able to work it out somehow and deny me.

I'll just have to wait for the Electron update in the flatpak.

Cheers.

**Comment by jijojosephk** [comment]
Blocking upgrade to latest electron version due to missing tray icon. Logged a defect [38140](https://github.com/electron/electron/issues/38140)

**Comment by jijojosephk** [comment]
I think we need to upgrade anyway, we're not going to get the fix for [38140](https://github.com/electron/electron/issues/38140#issuecomment-1619614169).

**Comment by jijojosephk** [comment]
@IsmaelMartinez let's upgrade to latest electron. `electron-dl` seems to have problem. I think since we have multiple packages we might not need it. You can confirm.

**Comment by IsmaelMartinez** [comment]
I am not sure how many people might be using the electron-dl, but if it is not working let's upgrade but increase the version number to 2.0.0 and leave it in snap edge (as nd pre-release) for a while. Just to make sure people test it.

**Comment by jijojosephk** [comment]
Closing as it's completed. Version upgraded to `24.6.3`
