### ISSUE TITLE
OpenSUSE Buildservice webhook

### ISSUE THREAD

**Issue by Thaodan** [IsmaelMartinez/teams-for-linux#672]
**Is your feature request related to a problem? Please describe.**

No. I want to provide packaging based on the OpenSUSE buildservice. To make updating the package automatically we can add a webhook to trigger the service when ever you tag a new release.

The service can be used for any distro as long as packaging is provided e.g. Debian, Arch Linux etc.

**Describe the solution you'd like**
Add openSUSE webhook to this repository. I would setup anything else but that you have to add the url to this repository.
If possible it would make sense to store the spec files in this repository too.

**Describe alternatives you've considered**
Manual updates 

**Additional context**
OpenSUSE docs:
https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html

**Comment by Thaodan** [comment]
Sure I can do that but I have to setup the token for the webhook. I will mail you when I did so.

**Comment by Thaodan** [comment]
Hey,

I have setup the packaging now in my OBS project here:
https://build.opensuse.org/package/show/home:Thaodan:network/teams-for-linux

The package is build for OpenSUSE and Fedora, I can also try to add Debian packaging there.

The package will be updated whenever you push a new release to this repository. Please review the packaging and then I will email the token.

You have to add `https://build.opensuse.org/trigger/runservice?project=home:Thaodan:network&package=teams-for-linux` as a webhook in your project settings with the token I will send you.

**Comment by IsmaelMartinez** [comment]
ready for that token when you are. Had a wee look and looks fine. Worth doing some testing when the 1st release happens.

**Comment by Thaodan** [comment]
@ChristoSnake The hook isn't there yet I assume, I send out the email for hook instructions and token ca. a week ago.

I can trigger the build but I waited so I can see that adding the webhook works.

**Comment by IsmaelMartinez** [comment]
yeah, sorry for this. I will try to add it tomorrow. Been a few mental weeks (if not months). apologies again.

**Comment by ChristoSnake** [comment]
@Thaodan: Please be aware of the screen sharing issues I described in #687.  The OpenSUSE build service makes installation on Tumbleweed a very pleasant affair, but it might have killed screen sharing.

**Comment by ChristoSnake** [comment]
... and the latest version is available in the repository!  Whatever you gents did obviously worked:
![tfl_v50](https://user-images.githubusercontent.com/25453721/222448559-6e4dbe57-f45c-4c07-bb07-33e1761d6705.png)

**Comment by jijojosephk** [comment]
Looks like this had been addressed. Please re-open if required.
