### ISSUE TITLE
Use CSD and disable desktop window

### ISSUE THREAD

**Issue by ogarcia** [IsmaelMartinez/teams-for-linux#678]
At the moment teams-for-linux looks like this.
![image](https://user-images.githubusercontent.com/572924/218971226-7c6eee8c-0de0-4a1d-94f8-f6f71aa38289.png)

This wastes a lot of space for a window frame that doesn't add anything useful.

However, the official Microsoft Teams client has this window.
![image](https://user-images.githubusercontent.com/572924/218970858-fbb31318-b091-48ea-9bc7-558ed9586a73.png)

It would be very interesting to support (at least as an option) to be able to use CSD instead of having a system window that wastes space.

**Comment by IsmaelMartinez** [comment]
Yeah, good idea. Whoever I don't know if that is possible with the web view we have.

**Comment by RolandRosenfeld** [comment]
If you really intend to realize something like this, please make it configurable.  I personally don't like such a setup, since it doesn't cope with my window manager (fvwm) setup and breaks window decoration (especially when not running full-screen).

**Comment by jijojosephk** [comment]
This was planned here #441 but never got the time. Also many thinks the default one is better. So we might let users to choose between original and custom. That'a lot of work. I could not take up that due to personal work load. Still planned as a feature yet allow users choose between what's best for them. Hope I would get some time.

**Comment by ogarcia** [comment]
Personally what interests me the most is that there is the possibility to remove the desktop window, in fact a simple option of "start in full screen" would be enough for me, because the window decoration wastes a lot of space.

**Comment by jijojosephk** [comment]
The F11 keystroke makes it full-screen.

**Comment by ogarcia** [comment]
> @ogarcia, I'm curious to know why there is no minimize,maximize button. Only close ? I'm referring to screenshot 1.

@jijojosephk GNOME things. The maximize button is not necessary since in GNOME it is achieved either with a gesture or with a double click on the window bar or on the window decorator, the opposite effect (restore) is done in the same way.

As for minimizing, it makes no sense in GNOME. If you don't want a window you send it to a virtual desktop and forget about it.

**Comment by jijojosephk** [comment]
@ogarcia This looks difficult.

**Comment by jijojosephk** [comment]
But will git it a try.

**Comment by IsmaelMartinez** [comment]
Hi @ogarcia , I had a try on this but the full screen in electron is really a full screen (meaning, you ONLY see teams, not even clock, system bar etc). I don't think that is the desirable solution

**Comment by IsmaelMartinez** [comment]
Unfortunately that is not possible in electron as far as I am aware. All full screen and/or removing the bars seem to remove all system (but it could be related of me trying this in a MacOS device)

**Comment by IsmaelMartinez** [comment]
closing due inactivity
