### ISSUE TITLE
Flatpak Out Of Date (1.0.45 in flathub, 1.0.49 latest release)

### ISSUE THREAD

**Issue by damentz** [IsmaelMartinez/teams-for-linux#680]
**Describe the bug**
In the official flathub remote of Flatpak, **teams-for-linux** is out of date.

**To Reproduce**
1. Install flatpak (instructions vary per distro)
2. Add flathub to flatpak if not already: `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
3. Search for **teams-for-linux**: `flatpak search teams-for-linux`
4. Observe the version is **1.0.45** at time of this report

**Expected behavior**
The version in the output of `flatpak search teams-for-linux` should be **1.0.49** at time of report.

**Screenshots**
![teams-for-linux-search](https://user-images.githubusercontent.com/284931/219795685-bc3c30bd-ecaf-4d54-8918-0015cdb0deed.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by marbub** [comment]
Seems strange that there is a rpm as Fedora is pushing to flatpak.

**Comment by wshanks** [comment]
See https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/issues/27

**Comment by IsmaelMartinez** [comment]
Hey, if any of you is a flathub wizard (or just someone that can fix that tray icon), then we can update that version. No point updating it if it is going to break that icon that for many users means only been able to see teams once. :D

**Comment by damentz** [comment]
New flatpak is out for 1.0.50 and the systray icon works.  Closing this out since the issue is resolved.  Thanks!
