### ISSUE TITLE
Mac keyboard shortcuts are shown

### ISSUE THREAD

**Issue by bmaupin** [IsmaelMartinez/teams-for-linux#682]
**Describe the bug**

I hesitate to mention this because it's so minor, and something I can personally live without, but in the interest of making this more polished for other users I thought I'd report it ...

It looks like the MacOS keyboard shortcuts are being shown instead of the Linux ones. Maybe it's due to whatever browser user agent is being used?

**To Reproduce**

1. Start a meeting
2. Mute yourself
3. Blow into the microphone
4. Observe that the message that pops up shows the MacOS keyboard shortcuts

**Expected behavior**

I'd expect Linux (or I guess Windows would be fine too?) keyboard shorctuts

**Screenshots**

![mac-keyboard-shortcuts](https://user-images.githubusercontent.com/346123/220422829-2e4bc45b-4fe1-4717-b4ab-887f000b8c3d.png)

**Desktop (please complete the following information):**
 - Ubuntu 22.04
 - Installation package: deb
 - Version 1.0.49

**Additional context**

Thanks!

**Comment by IsmaelMartinez** [comment]
Hey, that is strange but the user agent is set in the config options. 

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/index.js#L75

It does say "linux" but MS might be doing something funny with it.

Maybe try another user agent on there and see how it goes? The https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md should have enough info to get you going but ping in here if you need help.

**Comment by bmaupin** [comment]
I tested with Chrome in Linux. With the default user agent, the MacOS keyboard shortcuts are shown, so this seems to be a bug with Teams itself.

I did test with the Chrome Windows user agent (`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`) and it shows the Windows shortcuts (which should be the same for Linux):
![teams-windows-user-agent](https://user-images.githubusercontent.com/346123/222452539-15d9d534-4712-4be9-bd32-6b2c3f222044.png)

I'm not sure if it would be overkill to use a Windows user agent just to fix this. Again, it doesn't personally bother me.

**Comment by IsmaelMartinez** [comment]
Maybe they have removed any references to Linux and that is now defaulting to Mac ? Just a guess. You should be able to update the config.json file to use the user agent.

**Comment by RolandRosenfeld** [comment]
I'm quite sure that this is a bug on MS side in the web, since I see different messages on the microphone button popup and when I talk while beeing muted:
![image](https://user-images.githubusercontent.com/6381171/223730672-19e74b72-1e82-4b8f-bbba-5a888df5e284.png)
These two should show the same key binding, either MAC or PC, but not mixed.

**Comment by jijojosephk** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/pull/776 would possibly fix.

**Comment by jijojosephk** [comment]
Closing as it's fixed in version `1.0.77`
