### ISSUE TITLE
Icons are not displayed

### ISSUE THREAD

**Issue by andy9a9** [IsmaelMartinez/teams-for-linux#683]
**Describe the bug**
Icons and emoticons are not displayed in channel section.

**To Reproduce**
Just start the app and open any conversation where the last message was emoticon. Or set a icon on any channel.

**Expected behavior**
It should display the icon.

**Screenshots**
- Firefox could display the icons as well
  - ![firefox-ok](https://user-images.githubusercontent.com/20794139/220645123-712c3111-239b-4729-8f29-15db7ec57ea4.png)
- application not
  - ![teams-error](https://user-images.githubusercontent.com/20794139/220645367-15e40028-f6d6-4867-b60c-8038ab08f7b8.png)

**Desktop (please complete the following information):**
 - OS: Linux Fedora
 - Installation package: rpm
 - Version: 1.0.49

**Comment by IsmaelMartinez** [comment]
I didn't know you could set up icons for a channel! I really have no idea why this can happen. Can you check if the icon's work fine on a chrome browser on your machine? I do remember long time ago some users having problems with the app but was related to their Chromium version in their environments. As you are using Firefox, that might be the case, but really a wild guess. Hopefully someone can help.

**Comment by andy9a9** [comment]
It's not just about the channels. You can send emoticon as a last message. Then it should be shown in the left panel, but it didn't. It showed the `[ ]` like you can see on picture. I tried that on the Chrome and it doesn't work too.

**Comment by jijojosephk** [comment]
Is it still a problem?

**Comment by andy9a9** [comment]
> Is it still a problem?

Can I use `1.0.72` or should I wait for next release?

**Comment by jijojosephk** [comment]
Try it and let us know. Quite unsure where the problem is. Let's find out.

**Comment by andy9a9** [comment]
> Try it and let us know. Quite unsure where the problem is. Let's find out.

I tested the version `1.0.72` and it persists.

**Comment by jijojosephk** [comment]
Can you tell me how to reproduce. I'll try at my end

**Comment by jijojosephk** [comment]
![image](https://user-images.githubusercontent.com/11662148/235108404-2895237b-b297-4f3e-9204-3a8235af2027.png)

**Comment by andy9a9** [comment]
> I see as icon. ![image](https://user-images.githubusercontent.com/11662148/235108404-2895237b-b297-4f3e-9204-3a8235af2027.png)

hmm, funny, in my case it looks like this: ![Screenshot from 2023-04-28 11-49-29](https://user-images.githubusercontent.com/20794139/235115730-e3e97316-d336-447a-a022-fe6c97e0a845.png)

Maybe which kind of agent do you have?

**Comment by jijojosephk** [comment]
What's your system locale?

**Comment by andy9a9** [comment]
> What's your system locale?

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by jijojosephk** [comment]
Thanks, but I don't get why it's happening. Did you try in google chrome?

**Comment by andy9a9** [comment]
See https://github.com/IsmaelMartinez/teams-for-linux/issues/683#issuecomment-1450881499

**Comment by storm9c1** [comment]
> I see as icon. ![image](https://user-images.githubusercontent.com/11662148/235108404-2895237b-b297-4f3e-9204-3a8235af2027.png)

Mine looks correct, like that ^^^

I cannot reproduce this problem on my system.
Ubuntu 22.04
XFCE
Teams for Linux 1.1.0

My locale has LC_* set to "en_US.UTF-8" -- except LC_TIME=C and LC_COLLATE=C (because I want my "date" and "ls" commands output what Unix originally intended).

So I have nothing to add.  Sorry.

**Comment by jijojosephk** [comment]
@andy9a9 this is something related to `chromium` build and your OS setup. Getting a solution here is less likely as we're dependent on parent projects `electron` and `chromium`
