### ISSUE TITLE
MacOS Apple Silicon build

### ISSUE THREAD

**Issue by idemche** [IsmaelMartinez/teams-for-linux#684]
**Is your feature request related to a problem? Please describe.**
Currently launching the app on MacOS m1pro/max processors we experience super slow app startup. Teams-for-linux helper renderer eats out 130% of CPU on start. On tapping chats/selecting team/opening messages or traversing through menus - it does that super slow and renderer  loads CPU up to 100% and more

**Describe the solution you'd like**
Is it possible to make m1 apple silicon optimized build please?

Screenshots:
<img width="1039" alt="Screenshot 2023-02-23 at 00 10 44" src="https://user-images.githubusercontent.com/26379095/220771401-59cfd992-5cd6-4e99-9413-926e90c593b8.png">

**Comment by IsmaelMartinez** [comment]
closing due inactivity. Please ping if you want it re-open.
