### ISSUE TITLE
Patch: Support for multiple Teams Accounts at the same time

### ISSUE THREAD

**Issue by Xathviar** [IsmaelMartinez/teams-for-linux#689]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I have to use my three different Teams Instances and managing them is quite difficult. 
I usually have my team instances managed via teams-for-linux, one with my browser, and one with the incognito tab of my browser. 
With the provided code one can run multiple teams-for-linux Instances at the same time and only has to create a different .desktop file for each of them.

**Describe the solution you'd like**
A patch is attached 

```diff
--- app/index.js    2023-03-01 21:27:11.523662698 +0100
+++ custom/app/index.js       2023-03-01 21:28:14.090371951 +0100
@@ -4,6 +4,8 @@
 const isDev = require('electron-is-dev');
 const os = require('os');
 const isMac = os.platform() === 'darwin';
+const pathName = app.commandLine.hasSwitch('customUserDir') ? app.commandLine.getSwitchValue('customUserDir') : app.getPath('userData');
+app.setPath('userData', pathName);
 const config = require('./config')(app.getPath('userData'));
 const logger = new LucidLog({
        levels: config.appLogLevels.split(',')
@@ -46,6 +48,8 @@
 const certificateModule = require('./certificate');
 const gotTheLock = app.requestSingleInstanceLock();
 const mainAppWindow = require('./mainAppWindow');
+
+
 if (config.useElectronDl) require('electron-dl')();

 if (config.proxyServer) app.commandLine.appendSwitch('proxy-server', config.proxyServer);                                                                           
```

```diff
--- app/config/index.js     2023-03-01 21:27:11.523662698 +0100
+++ custom/app/config/index.js        2023-03-01 21:08:10.490020903 +0100
@@ -48,6 +48,11 @@
                                describe: 'Proxy Server with format address:port',
                                type: 'string',
                        },
+                       customUserDir: {
+                               default: null,
+                               describe: 'Custom User Directory so that you can have multiple profiles',
+                               type: 'string',
+                       },
                        useElectronDl: {
                                default: false,
                                describe: 'Use Electron dl to automatically download
files to the download folder',
```

**Comment by IsmaelMartinez** [comment]
Thanks a lot! I will suggest to do the check if the customUserDir is provided and, if is not, then just not set the path. To avoid the risk of messing up with some people configuration (it should not be the case).

If you can create a PR with this change, that will be amazing. Only part missing will be to update the readme in the config folder with that customUserDir and increase the package.json file number... and that will be it!

Thanks for contributing!!

**Comment by Xathviar** [comment]
Done :D 
[https://github.com/IsmaelMartinez/teams-for-linux/pull/690](url)

Also thanks for providing this electron app, since the official teams client never really worked for me
