### ISSUE TITLE
Option for SSO Login Popups for certain Apps

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#695]
I tried to add an app to my teams client that will ask for "Login with Company SSO". In the MS client this will open a popup to continue to login, while the request in teams-for-linux will go to the default browser and not return to the app.

Is there any option to handle such requests (i.e. URLs) within the client?

**Comment by elhennig** [comment]
The error message from debugging is 

> (electron) The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.

**Comment by IsmaelMartinez** [comment]
Can you try doing Ctrl + Click? if it opens a separate pop up on the browser you then log in on a different context, what might be causing the problem.

**Comment by elhennig** [comment]
I did, and it behaves the same way as without CTRL: It only opens a window in my default browser. However, it seems that for this one app in Teams the authentication will not work outside the teams client's context.

**Comment by IsmaelMartinez** [comment]
This piece of logic is the one that will be determining to open it into a different screen.

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L188

MS do change how the handle the pop ups every now and then... so maybe they have changed something.

**Comment by IsmaelMartinez** [comment]
Might be related to the PWA issue with the links. I think MS changed something. There is an open issue that might help. Let me find it.

**Comment by IsmaelMartinez** [comment]
#675 might be related to this.

**Comment by IsmaelMartinez** [comment]
pre-release in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.56

**Comment by elhennig** [comment]
he behavior in 1.0.56 is still then the same as before, unfortunately

**Comment by jijojosephk** [comment]
Can you tell me which app you're trying to add? Let me try to reproduce at my end

**Comment by elhennig** [comment]
The app is Office RND Hybrid (see https://www.officernd.com)

**Comment by jijojosephk** [comment]
Thanks but it's asking for some admin rights. What I get.

1. start free trial
2. launches a new window
3. then i have admin rights error.

The above is restriction on my account.

So what is the expectation if you everything right.

**Comment by elhennig** [comment]
Well this is a app to book work places in our company. It tries to open a page with a SSO page (from the MS cloud, probably at some point this leads to login.microsoftonline.com) and opens it in a browser but looses the context and does not revert back to Teams-for-Linux. In the MS Teams Web-App this feedback returns well, of course.

**Comment by jijojosephk** [comment]
Do you face the same with GitHub also? Something like this
![image](https://user-images.githubusercontent.com/11662148/235307299-a41b5b39-a884-4032-b854-2999013e7229.png)

**Comment by IsmaelMartinez** [comment]
Have you tried doing a ctlr+click on the app? That should open it in the
same context so the credentials cab be used.

**Comment by jijojosephk** [comment]
@IsmaelMartinez it's not currently implemented. CTRL + click is having disposition `background-tab` that is currently denied. We should show a confirmation before sharing the session.

**Comment by jijojosephk** [comment]
@elhennig checkout `1.0.78`

**Comment by elhennig** [comment]
@jijojosephk Thanks a lot! The new dialogue works fine for me (tried with 1.0.80).

**Comment by foxylion** [comment]
Hey, after updating to the latest version I noticed the change made here. While this might be sometimes useful it is pretty bad UX for users that do not need this regularly. I can now no longer open links with a single click, but do need two clicks and a mouse movement. When trying to open multiple links in a row this does not take ages...
