### ISSUE TITLE
Calls no longer ring

### ISSUE THREAD

**Issue by PimpinPumpkin** [IsmaelMartinez/teams-for-linux#697]
**Describe the bug**
After an update to this app, incoming calls no longer play the incoming call notification sound. However, the call still generates an incoming call window, and upon the call not being picked up due to not noticing, the missed call sound will play. I'm not completely sure what the last version without this bug is, but I suspect 1.0.49.

**To Reproduce**
1. Receive a call
2. The incoming call will not play the ringing tone

**Expected behavior**
When someone calls you, teams should play the incoming call jingle as it has in previous versions of this app.

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Installation package Flatpak
 - Version 1.0.50

**Additional context**
To try and fix the issue, I uninstalled the app with --delete-all-data, rebooted, and installed it again, but nothing changed.

**Comment by j-fraga** [comment]
Same behavior here with:

- OS: Ubuntu 22.10
- Installation package Snap
- Version 1.0.71

**Comment by jijojosephk** [comment]
Have you changed something in settings? for all settings are present?

**Comment by PimpinPumpkin** [comment]
> @j-fraga and @PimpinPumpkin , if you can try rpm or deb from the releases page and see if they work? It might be some permissions from snap or flatpak.

Well, this issue was actually fixed for me a week or two ago with a new release. I couldn't tell you which one though. My calls and messages now ring. 

I will say that after teams-for-linux fixed the calls ringing, I reloaded my OS - and for a brief period, my calls AND messages would not make a notification sound at all. Not sure why, but I don't believe rebooting or changing the settings helped much. Things appeared to just spontaneously fix themselves. Take everything I say with a grain of salt, since I really did not take care to document the exact details of what/why these things occurred.

Thank you for your hard work, this is really an amazing project!

**Comment by jijojosephk** [comment]
@PimpinPumpkin  is it working? can we close ?

**Comment by jijojosephk** [comment]
Closing as it seems working.

**Comment by j-fraga** [comment]
> @j-fraga and @PimpinPumpkin , if you can try rpm or deb from the releases page and see if they work? It might be some permissions from snap or flatpak.

I installed the deb of v1.0.72 after a completely fresh install of Ubuntu 23.04.
Calls still don't ring. 
And I have set a ringtone in the Settings (which plays fine when I click on the play button):

![image](https://user-images.githubusercontent.com/38435343/235695742-f7c76312-6689-42a2-9246-ee9194b8d2bd.png)

**Comment by jijojosephk** [comment]
@j-fraga Is this checked for you?

![image](https://user-images.githubusercontent.com/11662148/235821351-cb15f9ed-6a79-4242-b530-0fa2f78f0d36.png)

**Comment by j-fraga** [comment]
That was exactly it! Thank you, @jijojosephk!

**Comment by jijojosephk** [comment]
So, I assume all good! Thanks.
