### ISSUE TITLE
flatpak runtime is outdated

### ISSUE THREAD

**Issue by marbub** [IsmaelMartinez/teams-for-linux#698]
**Describe the bug**
The flatpak version is using the runtime version 21.08 but the current version is 22.08.

**Expected behavior**
The most current runtime is used because otherwise disc space is increased.

**Comment by jijojosephk** [comment]
Could you test the latest build?

`flatpak install --user https://dl.flathub.org/build-repo/9786/com.github.IsmaelMartinez.teams_for_linux.flatpakref`

**Comment by marbub** [comment]
Works perfectly for me.

**Comment by jijojosephk** [comment]
Thanks @marbub, just now published to flathub hence closing this.
