### ISSUE TITLE
Mouseover actions on comments not working with some WMs

### ISSUE THREAD

**Issue by mbert** [IsmaelMartinez/teams-for-linux#700]
This is most likely not an issue of teams-for-linux but rather Microsoft's web client implementation. However maybe somebody has encountered the same thing and/or has even a workaround or fix?

This week mouseover actions on comments (emojis, the "..." submenu) have stopped working. The hover menu appears, but when I click on something, nothing happens.

I have experimented with this a bit, and it has turned out to only occur under only one window manager / desktop environment. I am using NsCDE (a retroish setup based on fvwm). I have tried running the applicatin with plain fvwm, gnome, WindowMaker and plasma, everything's fine there.

I haven't knowingly made any changes to my setup, it just "stopped working", and this across reboots, logout/login, restart of the application. Really weird.

**Comment by RolandRosenfeld** [comment]
I observe the same problem (always using plain fvwm) most of the time.
But it randomly (seldom) works as expected, no idea what makes the difference to work.
As far as I can see, the chance, that it works correct, is higher in channels than in chats.

**Comment by jijojosephk** [comment]
@mbert  Are you still facing the same issue? Can you tell us what do you see in developer tools when you click on any actions?

**Comment by mbert** [comment]
> @mbert Are you still facing the same issue? Can you tell us what do you see in developer tools when you click on any actions?

Yes, I still am. I will be at my office desk on Wednesday, I shall take a look then!

**Comment by jijojosephk** [comment]
Thanks @RolandRosenfeld. @mbert  does that help?

**Comment by jijojosephk** [comment]
Thanks I'll close it then.
