### ISSUE TITLE
Slack Conflict

### ISSUE THREAD

**Issue by jacobamey** [IsmaelMartinez/teams-for-linux#701]
Unsure if this is an issue or a byproduct of Slack also not doing any actual work for the Linux side of the house for a while.

I am running Fedora 37; Currently, when trying to install teams-for-Linux "Unofficial," I receive a conflict with Slack. Unfortunately, I do have clients that are on slack and teams. I would need to run both.

I performed a standard install after downloading the RPM.
`sudo rpm -ivh teams-for-linux-1.0.52.x86_64.rpm
`

Output:
```
file /usr/lib/.build-id/0d/9fad3f21b1e381cc66b5efcae8f3910ae0edc1 from install of teams-for-linux-1.0.52-1.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
file /usr/lib/.build-id/76/9d0269491ca2313fcd15d63059bac67bd8b1b3 from install of teams-for-linux-1.0.52-1.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
file /usr/lib/.build-id/c2/dcac7cb6a727685d10d4161a0d14988f12a0fa from install of teams-for-linux-1.0.52-1.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
file /usr/lib/.build-id/cb/dc9db5fec0e6129bddcb0c282be98be4c6966e from install of teams-for-linux-1.0.52-1.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
```

Posting here for awareness; if something can be done on this side of the house, great! if not, others who run into the issue can see this and know they are not alone.

**Comment by jacobamey** [comment]
As a work around, the AppImage seems to do just fine so far. Maybe don't use the rpm if you see same conflict.

**Comment by IsmaelMartinez** [comment]
I think there is an open PR that might solve this https://github.com/IsmaelMartinez/teams-for-linux/pull/696 but I am not sure. I will see if I can have a look at it later on or tomorrow

**Comment by jacobamey** [comment]
Very cool; it looks like that's almost ready for merge. Thanks!

**Comment by jacobamey** [comment]
i gave it a shot, same issue. But I believe I'm still using the before merge build. RPM looks to be from 2 weeks ago.

**Comment by IsmaelMartinez** [comment]
have you tried the rpm in here? https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.52

**Comment by IsmaelMartinez** [comment]
me bad :D try this one? https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.53

**Comment by jacobamey** [comment]
Works like a charm! Many thanks!

**Comment by jacobamey** [comment]
issue confirmed, closing out ticket.
