### ISSUE TITLE
Notification sounds playing even though disabled in app

### ISSUE THREAD

**Issue by nneul** [IsmaelMartinez/teams-for-linux#702]
**Describe the bug**
Receiving notification sounds for starts of meetings and incoming messages, even though they are disabled in the application.

I'm ok with notifications for _calls_, but really don't want a ding on messages or the start of meetings. 

**To Reproduce**
1. Wait for incoming notification or start of meeting - doesn't appear to be on "every notification" as well - not sure what the specific threshold is. 

**Expected behavior**
Silence if I have turned off notification sounds.

**Screenshots**
![image](https://user-images.githubusercontent.com/828492/224560631-ec68808d-6669-44a2-9985-aa86b33e9874.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 XFce running with dunst for notifications - which specifically doesn't have sound support unless you add it yourself. 
 - Installation package: deb
 - Version: 1.0.52

**Additional context**

**Comment by IsmaelMartinez** [comment]
Hi,

It looks like the default behaviour for the app is to do as you describe. If you want to disable the meeting notifications, you should use the option `disableMeetingNotifications` in here https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/index.js#L117 

More info in https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md (whoever looks like that config option is not documented in the readme)

Hope helps,

**Comment by nneul** [comment]
Thing is, I don't really want to disable the notifications outright - only the _sound_ associated with them.  Any ideas on how to do that - or is this a functional bug in the 'embedded microsoft content' for the app - and not something that can be controlled by your wrapper around it?

**Comment by nneul** [comment]
#703 fyi

**Comment by jijojosephk** [comment]
@nneul such flags are currently not respecting the app settings. We might need to find where such settings are stored. We need to look at the local storage or session storage but not sure. If you think, just the 'ding' is not required we might be able to implement something quick.

**Comment by nickcodefresh** [comment]
Yes please do implement something quick, as it's very annoying having it ding constantly. Thanks!

**Comment by IsmaelMartinez** [comment]
hi @nickcodefresh , feel free to give it a go and try to implement a solution. Happy to help but I can't dedicate much time on this project.

**Comment by jijojosephk** [comment]
@nickcodefresh and @nneul new flag added. Build `1.0.55` on the way.

**Comment by IsmaelMartinez** [comment]
promoted to stable in snap.

**Comment by jijojosephk** [comment]
Closing this as a new flag had been implemented.
