### ISSUE TITLE
App raises window and steals focus on private message

### ISSUE THREAD

**Issue by pezz** [IsmaelMartinez/teams-for-linux#704]
**Describe the bug**
Not sure if this is new behaviour or not, but I don't remember it doing this before.

Now when I receive a private message the window jumps to the front and takes focus, very annoying.

**To Reproduce**
1. Receive a private message from someone

**Expected behavior**
Show the red dot in the tray and do not show the window and take focus.

**Desktop (please complete the following information):**
 - OS: Arch Linux with GNOME Shell, all latest available
 - Latest flatpak, fresh install

**Comment by RolandRosenfeld** [comment]
I can confirm this issue with latest deb package on Debian 11 and fvwm window manager (as well as with older versions of teams-for-linux).

It's  very annoying, especially when this happens during entering a password in another window.

As a workaround it helps to _close_ the teams-for-linux window instead of _iconizing_ it.  So the teams-for-linux icon stays in the panel (allowing to show a notification that some wrote something), but the client does not jump into foreground and does not catch the focus.

**Comment by arielkuzminski** [comment]
Lucky guys.... On Ubuntu after 5 minutes my Teams set me up to "away from device" and I no longer receive notifications, even with private chat messages. So every 30 minutes or so, I have to manually (like a monkey) open Teams Client to see if nobody wrote to me.

So I would trade with You in no-time.

**Comment by jijojosephk** [comment]
@arielkuzminski this is now fixed

**Comment by pezz** [comment]
Updated to 1.0.68 and the original issue appears to be fixed.

Now get a notification instead of the window being raised.

Thanks!

**Comment by pezz** [comment]
Actually, I seem to have jumped the gun a bit on this.

It seems it was working temporarily but now the window raising behaviour on a private message has returned.

Could this be an actual Microsoft code problem? I have seen in the past where they have fixed issues but then the code gets rolled back or backed-out to an older version and old issues resurface.

**Comment by jijojosephk** [comment]
@pezz i suspect this has something to do with window manager and notification api

**Comment by jijojosephk** [comment]
@pezz `1.0.69` has a new flag `disableNotifications`.

Use this way: 

`teams-for-linux --disableNotifications true` or
`flatpak run com.github.IsmaelMartinez.teams_for_linux --disableNotifications true` and see when new message comes, window focus is stolen. With this flag, notifications will not be shown. So you would know the problem is between Desktop notifications vs Window Manager or not.

**Comment by pezz** [comment]
Ok thanks.

Flathub is still on 1.0.68 but will try it when an update happens.

**Comment by jijojosephk** [comment]
@pezz  can you confirm?

**Comment by pezz** [comment]
`--disableNotifications true` has no effect. Window still raised and focus stolen.

**Comment by jijojosephk** [comment]
> `--disableNotifications true` has no effect. Window still raised and focus stolen.

Did you receive notification?

**Comment by pezz** [comment]
No. But in general I hate the way flatpak shows a notification for "App is running in background", so I generally disable notifications in Gnome's Settings > Applications area and just rely on tray alerts.

Either way, it still does this on a private message when no other flatpak app does (e.g. Discord, Signal).

**Comment by jijojosephk** [comment]
Are you saying `teams-for-linux` is closed to system tray and when you new message comes it opens up?

**Comment by pezz** [comment]
It doesn't matter, I usually never minimise it and leave it running in its own workspace / desktop (whatever the term is in gnome), but I am chatting to someone right now and even when minimised to the tray it reopens and takes focus.

**Comment by jijojosephk** [comment]
So the problem occurs:

1. Whether the app is minimised or not.
2. Closed to system tray or not.
3. Notifications disabled or not by command line option.

Right?

**Comment by pezz** [comment]
Sums it up nicely, also - it never used to do this.

**Comment by jijojosephk** [comment]
@pezz  can you join this room https://matrix.to/#/#teams-for-linux_community:gitter.im

**Comment by pezz** [comment]
Many thanks to @jijojosephk for his generosity and time on this, especially when the issue is because of a Gnome extension.

I've used an extension for a while now called "V-Shell (Vertical Shell)" to enable some older gnome-shell behaviour. I'm not sure when the feature was added, but this extension also does a bunch of other things, including this guy:

![image](https://user-images.githubusercontent.com/372177/233637941-90635453-c90e-4642-80cb-3e7708cf519a.png)

Pretty obvious when you see it, and that option is not the default, so I have no idea why it was set. When using the default, Teams behaves as expected.

Lesson for me is, disable all extensions when you see weird behaviour and test before annoying you fine people.

Cheers.

**Comment by jijojosephk** [comment]
Thanks @pezz. You're welcome. Everyday is a learning.

**Comment by LukeDearden** [comment]
Just for reference I was having this same issue with the Just Perfection Gnome Extensions "Window Demands Attention Focus" option.

Disabling this option prevent Teams for Linux from taking focus.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6813601/0b93426b-ad84-4dda-8855-736684f8bbc2)

**Comment by Bitals** [comment]
> Disabling this option prevents Teams for Linux from taking focus.

...While also preventing user from having an adequate desktop experience. Like clicking on notifications becomes functionally useless, as it just produces another notification "$APP_name window is ready" until you manually switch to it.

Fine as a temporary workaround, but this degrades experience significantly. I have used other Electron chat clients without this problem, so unlikely to be its fault, looks like some local code triggers the focus stealing behavior.
