### ISSUE TITLE
appTitle title config option

### ISSUE THREAD

**Issue by nneul** [IsmaelMartinez/teams-for-linux#705]
**Is your feature request related to a problem? Please describe.**

Would like to be able to identify windows when running multiple instances - such as for use with x11 window resizing automation/etc. I can already do custom icon, but the window itself all still have 'Microsoft Teams' as the only common element.

**Describe the solution you'd like**

```
--appTitle="Microsoft Teams"
--appTitle="Teams -- mydomain.com"
--appTitle="Teams -- myotherdomain.com"
```

**Describe alternatives you've considered**
Rigging up a search that does xwininfo looking at the defined appIcon to distinguish - really ugly compared to just searching win titles for a known value.

**Additional context**

![image](https://user-images.githubusercontent.com/828492/224714131-90284cea-9548-408b-ad6d-bc4b83b136a9.png)

**Comment by jijojosephk** [comment]
Can you try this once the app is loaded? 

1. Select debug from tray menu
2. From the debug tools, choose console.
3. Then execute this. Replace 'Your Title' with the one you wanted. You will not see the change immediately, but when you click on some chats or any update happens to the title, your title also should be appended.

```js
const controller = typeof window.angular !== 'undefined' ? window.angular.element(document.documentElement).controller() : null;
controller.pageTitleDefault = '<Your Title>';
```

If this is what you want, we can implement. But I still don't find how to update when the page is loaded first time. The initial title update does not take this value any updates after setting this would take it.

**Comment by nneul** [comment]
![image](https://user-images.githubusercontent.com/828492/226614760-c4af545e-35c6-4130-818f-1f13700a9203.png)

Works nicely!

**Comment by jijojosephk** [comment]
I think appTitle might be a better name.

**Comment by jijojosephk** [comment]
@nneul please test in `1.0.54`. Closing this for now.

**Comment by nneul** [comment]
Been working smoothly. It _seems_ like it occasionally switches back to the 'Microsoft Teams' value, but it is actively working with the labelled windows good enough for my issue. Thank you very much!
