### ISSUE TITLE
enableDesktopNotificationsHack Throughs error and hides window on startup

### ISSUE THREAD

**Issue by OlMon** [IsmaelMartinez/teams-for-linux#706]
**Describe the bug**
While enabling the notification hack (through CLI parameter or config.json file) an error appears and the window is minimized on startup. (Not sure if notificationhack is enabled or not...)

**To Reproduce**
1. Enable notification hack (teams-for-linux --enableDesktopNotificationsHack)
2. Start teams-for-linux
3. Check stdout and notice window not showing

**Expected behavior**
No Error is thrown and window is displaying correctly.

**Desktop (please complete the following information):**
 - OS: Arch-Linux
 - Installation package tar.gz
 - Version 1.0.52

**Additional context**

Error in terminal (probably only first half is relevant):
```
(node:82725) UnhandledPromiseRejectionWarning: ReferenceError: iconPath is not defined
    at applyAppConfiguration (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/index.js:85:44)
    at Object.onAppReady (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/index.js:57:2)
(Use `teams-for-linux --trace-warnings ...` to show where the warning was created)
(node:82725) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id:
1)
```

Cheers and thanks for the project,
OlMon

**Comment by Volcommm** [comment]
Same as me 🤷‍♂️

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L85

I think changing that line for:

```
notifications.addDesktopNotificationHack(config.appIcon);
```

Will fix this issue... but I might just be wrong :D

**Comment by jijojosephk** [comment]
@OlMon and @Volcommm in new versions this flag is not required. May I know what would you try to achieve?

**Comment by OlMon** [comment]
In the readme.md the notification is still present. 

I have sometimes to problem that notification and window updates only happen when I focus the window.
So I thought maybe this will solve my problem.

**Comment by cloud81** [comment]
Hi, no desktop notifications for me on Ubuntu 22.04.2 LTS 64bit, tried even with --enableDesktopNotificationsHack still no notifications when I receive a call.

**Comment by RomanSobota44** [comment]
Hi, I use teams on Fedora 37 and dont receive notification too

**Comment by jijojosephk** [comment]
@RomanSobota44 @cloud81 @Volcommm @OlMon Is it only incoming call notifications or nothing?

**Comment by RomanSobota44** [comment]
In my case, it is only incoming call
message notification works fine - standard window in top middle of screen, but for
incoming call I see notification only If am focused on teams

**Comment by jijojosephk** [comment]
> In my case, it is only incoming call message notification works fine - standard window in top middle of screen, but for incoming call I see notification only If am focused on teams

ok. That's a known problem. To have a notification with actionable buttons is really a large work. We can only do that with another instance of browser window, which is going to use some extra memory.

**Comment by RomanSobota44** [comment]
if you can, try it please, because original pwa app is horrible

**Comment by jijojosephk** [comment]
As discussed earlier, `teams-for-linux --enableDesktopNotificationsHack` does not work and newer versions does not require this flag to be passed. Also I understand there's a feature request. Implementation would be similar to #725. Closing this for now. Any discussions related to enhancement, please refer #725

**Comment by IsmaelMartinez** [comment]
let's remove that flag then.
