### ISSUE TITLE
take/request control is missing

### ISSUE THREAD

**Issue by Volcommm** [IsmaelMartinez/teams-for-linux#707]
**Describe the bug**
you cannot take/request control of the remote client that is sharing the screen because is missing

**To Reproduce**
1. Start a call
2. remote client start sharing
3. you cant find "Take Control or Request Control"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Installation package from Snap ver 
                                            snap    2.58.2
                                            snapd   2.58.2
                                            series  16
                                            ubuntu  22.04
                                            kernel  5.19.0-35-generic
 - Version 1.0.52 (team for linux)
![image](https://user-images.githubusercontent.com/77114642/224943141-32c31114-17e1-45ed-9ce0-dd15beb3f689.png)

**Comment by IsmaelMartinez** [comment]
I believe this is a limitation on the web client.

**Comment by Volcommm** [comment]
I used Teams for Windows until last week and never had any problems... does it work for you?

**Comment by IsmaelMartinez** [comment]
This app is an electron wrapper of the web client. I don't think the web client supports "take control", but I have never needed to use that feature.

**Comment by geckolinux** [comment]
I did occasionally use the "take control" and also the "give control" feature with the official MS Teams app for Linux. But I understand that teams-for-linux is a wrapper of the PWA, so I assume that @IsmaelMartinez probably doesn't have any control over that.
This app will probably be getting a ton of new users now that MS has eliminated the DEB and RPM versions of their app during the past few days, and the Flathub version is also now referring users to use the PWA. ***Huge*** thanks to @IsmaelMartinez for this app, it's an absolute life saver. I have to use Teams for some things, and I can't function without the close-to-tray icon. The only issue I had with this unofficial app was spell checking, but the [workaround](https://github.com/IsmaelMartinez/teams-for-linux/issues/677) worked for me. And it's actually much lighter and faster and has much better voice/video meeting functionality than the deprecated MS app for Linux. Keep up the good work!

**Comment by IsmaelMartinez** [comment]
This is work of the community. I am hardly been able to do much lately. There might be ways around the request remote access, but I haven't had the time. Maybe we get it for free when MS implements it in the PWA. Thanks for your kind words and I am glad this is useful for many people.

**Comment by Volcommm** [comment]
Thanks for the clarification!
And a warm thank you in particular to @IsmaelMartinez for keeping this app 'alive', which I was unfortunately forced to use by the company ^^
I will definitely find workarounds to give and request control of the sessions

**Comment by IsmaelMartinez** [comment]
Sadly no. It depends on Ms implementing this on the PWA/browser version.

**Comment by geckolinux** [comment]
> I can confirm that take/request control **is** on the browser version at least on Windows.

Wow, interesting.

> The problem is that I've never been able to get it to work on Linux.

Did you try it with Edge for Linux?

**Comment by luckycold** [comment]
> > I can confirm that take/request control **is** on the browser version at least on Windows.
> 
> Wow, interesting.
> 
> > The problem is that I've never been able to get it to work on Linux.
> 
> Did you try it with Edge for Linux?

I have. Unfortunately it still doesn't work. It works fine even on Brave when I'm on Windows.
