### ISSUE TITLE
Click on link to external meetings is ignored

### ISSUE THREAD

**Issue by micw** [IsmaelMartinez/teams-for-linux#711]
**Describe the bug**

I have some teams meetings that are scheduled by an external organisation. I accept the meeting in outlook and see it in teams calendar.
The entry has no "Join Meeting" Button.

Normal Teams meeting scheduled in our organisation:
![grafik](https://user-images.githubusercontent.com/186753/226926936-474ccaa7-0644-4ff5-9eaf-7f7489d2cf60.png)

External Teams meeting:

![grafik](https://user-images.githubusercontent.com/186753/226927106-4a6574e1-2248-4dfb-9575-dcf3d35c8e80.png)

The external meeting has a link to the actual meeting:

![grafik](https://user-images.githubusercontent.com/186753/226927347-e8736d54-89e3-4115-b25b-bc25598f457a.png)

When I click on the link, nothing happens. When I right-click the link and click "copy", nothing is copied (clipboard has still the previous content).

When I inspect the link, it looks like a normal a-href html link:

![grafik](https://user-images.githubusercontent.com/186753/226927860-4f4eec27-5ead-464a-b9ba-0d62d2972891.png)

When I copy the link address, post it in teams to myself and then click the link in the message history, the meeting opens in teams-for-linux (so the link actually works, that's my daily workaround).

When I click the link in outlook or in teams web (office.com), it opens the browser (so the link in the invitation is in general clickable, just not in teams-for-linux).

**To Reproduce**

See above, reproducible for all my external meetings

**Expected behavior**

External meeting should open when clicking on the link.

**Desktop (please complete the following information):**
 - OS: archlinux
 - Installation package: aur
 - Version 1.0.49

**Comment by micw** [comment]
Hello @IsmaelMartinez ,

thank you for fast reply. I think this is different since nothing at all happens on my link, while the other issue is about that links are opened in the wrong application.

I took a little time to debug it. Seems that the link is delegated to a deprecated handler in electron:

```
(electron) The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
```

**Comment by IsmaelMartinez** [comment]
Had a look at the change required and the section of code, and lets say that it is due some TLC. I will see if/when I have time to sort this out. 

https://www.electronjs.org/docs/latest/breaking-changes#removed-webcontents-new-window-event

And this is the area of code that requires TLC (and the parent calls)

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L188

**Comment by IsmaelMartinez** [comment]
started the work in https://github.com/IsmaelMartinez/teams-for-linux/pull/713

**Comment by jijojosephk** [comment]
@IsmaelMartinez has this been tested and ready to be promoted? `1.0.57` is waiting with spellchecker fixes :smile:

**Comment by IsmaelMartinez** [comment]
I have no ability to test this unfortunately.

**Comment by jijojosephk** [comment]
@micw could you help with testing?

**Comment by jijojosephk** [comment]
Meeting links are opening for me. I'm not sure if there's a specific scenario I can test. I would release the build.

**Comment by micw** [comment]
Thank you a lot. Unfortunately, I currently have no external scheduled meetings. I test as soon as I have one in my calendar.
