### ISSUE TITLE
App doesn't start with "customUserDir" set

### ISSUE THREAD

**Issue by sonnatager** [IsmaelMartinez/teams-for-linux#714]
**Describe the bug**
When comandline argument "customUserDir" is set, the app doesn't start at all. There is always an javascript error.

**To Reproduce**
1. Start app as 
```
teams-for-linux --customUserDir /home/yourUser/anyCustomFolder
```

**Expected behavior**
App starts with custom folder is set.

**Screenshots**
![image](https://user-images.githubusercontent.com/37934901/227890484-e1402de6-b83d-481b-a61a-be386b7c155b.png)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Installation package: rpm
 - Version 1.0.56

**Additional information**

Also not working:
```
teams-for-linux --customUserDir "/home/yourUser/anyCustomFolder"
```

**Comment by tleepa** [comment]
I think, you need to use the equal sign: `teams-for-linux --customUserDir="/home/yourUser/anyCustomFolder"` - at least that's what is working for me on version 1.0.54

**Comment by sonnatager** [comment]
I have tried that. Works like a charm :-)
