### ISSUE TITLE
Making calls grabs multimedia keys

### ISSUE THREAD

**Issue by bmaupin** [IsmaelMartinez/teams-for-linux#716]
**Describe the bug**

Making a call in Teams binds the multimedia keys (play/pause/etc) to Teams so that they no longer work with media applications (e.g. Spotify).

**To Reproduce**

1. Open a media application (e.g. Spotify) and start playing music
2. Press the play/pause multimedia key to make sure the key works with the media application
3. Open Teams for Linux
4. Make a call in Teams
5. End the call
6. Press the play/pause multimedia key and observe that the key no longer has any effect on the media application

**Expected behavior**

Since Teams isn't a media application, it should have no impact on the multimedia keys

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package: deb
 - Version: 1.0.49

**Additional context**

Electron seems to bind to the multimedia keys by default.

It seems that this can be disabled relatively easily:

> ```js
> app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling');
> ```

(https://github.com/electron/electron/issues/18253#issuecomment-589542934)

**Comment by jijojosephk** [comment]
@bmaupin this went unnoticed. there were some merges happened. Could you pull again and also update the version in package.json?
