### ISSUE TITLE
Allow option to use to 2 or more MS Teams accounts in the same window (similar to Slack)

### ISSUE THREAD

**Issue by julian-alarcon** [IsmaelMartinez/teams-for-linux#72]
Allow option to have 2  or more MS Teams accounts in the same window, these is great for multi-account organizations when you provide service to external companies also with MS Teams.

I know that this one is a little harder, but will be great to have this feature on the client, It may require big changes in the app.

A feature request for this exists on MS Team feedback platform and is the fourth most voted: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/17750851-i-want-to-use-multiple-teams-accounts-at-the-same

This could be build using electron-tabs https://www.npmjs.com/package/electron-tabs

**Comment by IsmaelMartinez** [comment]
Hi,

It should be fairly easy... but there are a couple of things needed:
* disabling the single instance lock (with an option)
https://github.com/IsmaelMartinez/teams-for-linux/blob/master/app/index.js#L11
* use a second config partition 
https://github.com/IsmaelMartinez/teams-for-linux/tree/master/app/config

That should give the basic for this functionality. Now, that could be instrumented ina "config" option and it might be good if each instance shows itself as a different one (meaning... the icons in the desktop should be different for example)

**Comment by IsmaelMartinez** [comment]
Seems to be movement in MS regarding this issue so I will give it less priority for the moment.

**Comment by IsmaelMartinez** [comment]
ok, a simple solution to this is to use a packaged client and one build from source. This is because they use different config folder. Tried and works... you end up with two different icons. I am going to close it to keep things tidy as I don't think we are going to implement anything (mostly as MS is also on it)

**Comment by okelet** [comment]
I have a similar issue. I have been invited to a new "workspace", and the combo to select it is displayed in the top right corner:

![imagen](https://user-images.githubusercontent.com/108803/62934786-b1c20400-bdc5-11e9-971e-ea0b07b09275.png)

But when I click in one of them, the link is opened in the browser, instead of the application window. Is this a known behaviour? Could this be changed?

**Comment by IsmaelMartinez** [comment]
Have you trie Ctrl+click? Also, do open another issue instead of adding it to this one (not fully related). Thanks

**Comment by okelet** [comment]
Thanks @IsmaelMartinez, before opening a new issue, is this a new issue? Why Ctrl+Click and not just a simple click to do the same in the current window?

**Comment by IsmaelMartinez** [comment]
It's pretty complex but let's say I can't please everyone and Ctrl+Click
was the easier way to bypass the issue.

**Comment by okelet** [comment]
No problem, the solution is valid for me. Thanks!

**Comment by kitingChris** [comment]
Very sad this feature request is closed :( 

I work with 2 different organisations having 2 completely different accounts. 

Unfortunatelly the workspace solution microsoft offers does not work. 

An solution like different tabs with different accounts would be very helpful...

**Comment by IsmaelMartinez** [comment]
You can run 2 different packages versions... Like snap and deb. That will work

**Comment by kitingChris** [comment]
mh... that is more like a botchy workaround... :/

**Comment by IsmaelMartinez** [comment]
It works... the only annoying part is not knowing what icon is what... any other development will require quite a bit of work... maybe we can add the option of having another icon? will that work for you?

Feel free to open a new enhancement request and see what people say/think.

**Comment by kitingChris** [comment]
> maybe we can add the option of having another icon? will that work for you?

mh it is still a botchy workaround. Not better than my current solution: having one in a browsertab and one in your client.

**Comment by IsmaelMartinez** [comment]
If you are not using desktop share and do want tabs, use firefox and multi-accounts containers plugging. Again, having it in different tabs might be possible but will requiere re-architecture... actually, maybe not that big so open an enhancement if you require the extra stuff this client provides.

Hope helps!

**Comment by jdpiguet** [comment]
Would it be possible to have a cli parameter to select a different config directory/partition name?

**Comment by IsmaelMartinez** [comment]
There is already one. Check the config options, I think is called partition.

**Comment by jdpiguet** [comment]
Already tried, but getting message below:
jdp@amroth:~$ teams-for-linux --partition ~/.config/teams-for-linux_2
configPath = /home/jdp/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
App already running
jdp@amroth:~$

**Comment by IsmaelMartinez** [comment]
Try with --partition="persiste:teams-for-linux_2"

**Comment by jdpiguet** [comment]
Almost same problem:
`jdp@amroth:~$ teams-for-linux --partition="persiste:teams-for-linux_2"
configPath = /home/jdp/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
App already running
jdp@amroth:~$ 
`

**Comment by IsmaelMartinez** [comment]
Is there anyone in here still interested in this option? a new discussion has started at https://github.com/IsmaelMartinez/teams-for-linux/discussions/436

**Comment by abuibaid** [comment]
I came from the future to let you guys know that MS teams starts supporting many accounts in one software

**Comment by Ismas** [comment]
Raised this again because cannot use two accounts. Using one instance with two accounts initially works, switching from one to another is ok, but getting back to the first one doesn't, the blue screen  "Start session" appears and anything you enter, stays in last account.
Also, not able to start two instances or apply the --persistence= solution.
I'm resorting to one Appimage and one slap/browser isntance, but not tidy.

**Comment by IsmaelMartinez** [comment]
Hi @Ismas , have you check the docs in https://ismaelmartinez.github.io/teams-for-linux/multiple-instances ? That has been working for many users for a while. If that doesn't do the job, do open an issue and provide as much info as possible. Thanks for reaching out but normally I prefer new issues.
