### ISSUE TITLE
Teams gets unloaded after suspend

### ISSUE THREAD

**Issue by tamas646** [IsmaelMartinez/teams-for-linux#723]
**Describe the bug**
Whenever I raise my system from suspend the teams website gets unloaded: no notification badge, blank window -> a reload is required to use teams.
This behavior is confusing especially when I miss some important notifications because teams is not loaded and I don't recognize it.

**To Reproduce**
1. Open teams-for-linux
2. Hide it to the tray
3. Suspend your machine
4. Wake up your machine e.g. one day later
5. The teams app stops working
6. After reloading, everything backs to normal

**Expected behavior**
The app should reload teams on system resume (like Ferdium does), so no manual reload would be necessary.
Ferdium also allows a setting for idle time (default is 10 minutes).

Or another possible solution would be to somehow detect when teams is not loaded and automatically reload it if necessary.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Installation package: AUR (tar.gz)
 - Version: 1.0.52

**Comment by WMP** [comment]
I have this same in Microsoft Edge, i dont use IsmaelMartinez/teams-for-linux. In addition, for a week the Teams application has been running terribly slow, the process manager in the browser shows that without its active use it can consume 300% of cpu in a peak, and so every now and then....

**Comment by jijojosephk** [comment]
@tamas646 when the system resumes, do you see the tray icon?

**Comment by jijojosephk** [comment]
Thanks. Let me see what can be done.

**Comment by jijojosephk** [comment]
@tamas646 I assume you're on Arch. teams-for-linux arch repo is outdated. A possible fix for your issue is getting released in `1.0.68`. You must check with @ivelkov or @frealgagu to have the latest version updated at 
https://aur.archlinux.org/packages/teams-for-linux. If you have alternate ways, go to https://github.com/IsmaelMartinez/teams-for-linux/releases and get the latest build `1.0.68`.

**Comment by jijojosephk** [comment]
@tamas646 is it fixed? Can we close this if it is?

**Comment by tamas646** [comment]
Thanks for the quick fix. I've just upgraded the package today.
Please give me some days for testing.

**Comment by tamas646** [comment]
Unfortunately it did not solve the issue. :(

This screenshot was taken a few minutes after a resume:
![Screenshot_20230422_184009](https://user-images.githubusercontent.com/37243375/233796378-e993fb10-cfd2-41b7-9207-3e9cc2d55232.png)
and nothing happens...

I think reloading after every resume (like Ferdium does) could solve the issue.
But I'm open to any other ideas.

**Comment by jijojosephk** [comment]
can you run from the command line and see the logs?
`teams-for-linux --appLogLevels warn,info,error,debug` you should see something like `Reloading the page on system resume`

**Comment by tamas646** [comment]
There are two error messages on the console:
![image](https://user-images.githubusercontent.com/37243375/233796745-1f4d1688-2bdb-4a50-8700-d67a2f8061b9.png)

Found the problem:
![image](https://user-images.githubusercontent.com/37243375/233796901-bd702d4f-f865-4f57-81c8-03978be4f9a9.png)

**Comment by tamas646** [comment]
It fails to reload the app because the device is not yet connected to the network.

**Comment by jijojosephk** [comment]
So, we're close to closure. It has to wait for internet connection to be up.

**Comment by jijojosephk** [comment]
@tamas646  I did some changes. Please test `1.0.71` when it's out.

**Comment by jijojosephk** [comment]
Seems to be working on the latest version.

**Comment by tamas646** [comment]
Indeed. The problem solved. Thanks.
