### ISSUE TITLE
Show meeting notification as separate window with "join" button

### ISSUE THREAD

**Issue by antimatter84** [IsmaelMartinez/teams-for-linux#725]
Feature Request:

Enable teams-for-linux to open an additional window as meeting notification. The window contains the meeting title and a button for joining the meeting. The window would stay open until the user joins the meeting or dismisses the window.

The purpose is to have a more prominent reminder for the upcoming meeting and an easy way to join the meeting.

**Comment by tirolerstefan** [comment]
Appreciating this change, too!
Currently, I'm using this app, because I get a tray icon.
In addition to that I keep the PWA open to get the additional notification window.

**Comment by IsmaelMartinez** [comment]
To be able to add a "join" button we will need to create our own notification window. We use to have one, but it was a bit unreliable. I will put it on the 2.0 roadmap as, when ms moves away from angular to react, we will need to re-implement quite a few things)

**Comment by mikehaertl** [comment]
@IsmaelMartinez Before I open another issue: When this is implemented it should also be ensured, that the window is visible on all workspaces. 

I have the teams client running on a dedicated workspace and I never get any visual notification on incoming calls when I'm on another workspace. I only hear the incoming call sound.

If this can be improved without having a separate window I can also create a new ticket.

**Comment by IsmaelMartinez** [comment]
the `enableDesktopNotificationsHack` is gone now, and what this feature will need is basically something similar, but it was a bit unreliable (far too much of a hack).

I will see if at some point I can look into this, but anyone is more than welcome to have a go at it. ;)

**Comment by IsmaelMartinez** [comment]
maybe also add requests from #941 and #699

**Comment by IsmaelMartinez** [comment]
Maybe we can use https://github.com/mikaelbr/node-notifier (or find an alternative that is also maintained)

**Comment by IsmaelMartinez** [comment]
re-opening to see if we can implement this

**Comment by IsmaelMartinez** [comment]
I think this is already available behind the flag `enableIncomingCallToast`. Can one of you test it and see if it covers this? Closing to keep things tidy, but can reopen if it doesn't solve the problem. Thanks in advance!

**Comment by mikehaertl** [comment]
> I think this is already available behind the flag `enableIncomingCallToast`. Can one of you test it and see if it covers this?

@IsmaelMartinez It indeed seems to work! Thank you.

**Comment by peter1599** [comment]
Hi.

Is this the call reject and accept window thing? (Sorry, kinda new to Electron stuff)

If yes this does seem to only appear when teams open. (if its minimized its using native notification to display "Blah blah is calling you" and that's all

I found an old package called electron-custom-notifications which uses a window to display them.

I did try it outlook-for-linux (which is not maintained as of now) but managed to get a test notification outside of the application. (the package is also old)

<img width="1527" height="691" alt="Image" src="https://github.com/user-attachments/assets/63d2b3da-db94-44b6-8884-7af3edbc86b4" />

Could this be done here too or is something similar already planned?

**Comment by IsmaelMartinez** [comment]
Hi, we used to use that package (I think) but moved away from it as it wasn't maintained and had a few security vulnerabilities. 

We are always welcome to new additions and would greatly appreciate a new way to have notifications. Create a new issue and submit a PR if you got the skills and I am more than happy to give you a hand. Thanks!
