### ISSUE TITLE
Font in macbook m1 with asahi 

### ISSUE THREAD

**Issue by itsoulos** [IsmaelMartinez/teams-for-linux#726]
Hello all,
how can I change the used font size in Microsoft Teams?
I use asahi linux in a macbook pro m1 and the fonts is tiny

Giannis

**Comment by jijojosephk** [comment]
Is it just font or overall zoom level? CTRL+/- zooms in and out and maintains the state of zoom between runs. See if that helps. There are no custom fonts used. You can choose debug from tray icon menu and evaluate the HTML.

**Comment by itsoulos** [comment]
Thanks it worked perfectly!

**Comment by jijojosephk** [comment]
Shall I close if it works? Feel free to open if needed.
