### ISSUE TITLE
My avatar doesn't load

### ISSUE THREAD

**Issue by Ri0n** [IsmaelMartinez/teams-for-linux#728]
**Describe the bug**
I recently changed my avatar in ms. I see it in mobile version of Teams and at teams.microsoft.com but not in teams-for-linux.
Instead of avatar I see just "SI".
I tried to remove teams cache and click refresh but it didn't help.
My avatar is a jpeg image, so I believe it should be supported (not sure if MS converts it into anything).  

**To Reproduce**
1. Ensure updated avatar is everywhere 
2. Also check it's in teams-for-linux

**Expected behavior**
To see my avatar in right top coner

**Desktop (please complete the following information):**
 - OS: Gentoo Linux with recent updates
 - Installation package:  AppImage
 - Version 1.0.57

**Comment by jijojosephk** [comment]
I'm not familiar with gentoo. But it could be related to cache and local storage. From terminal can you launch the app with --clearStorage switch and see if a fresh session brings your avatar?

**Comment by Ri0n** [comment]
just tried. still without avatar. I also asked my colleagues if they see it. They don't. Maybe some problem on Microsoft side.

**Comment by jijojosephk** [comment]
Thanks.
