### ISSUE TITLE
Change readme file to explain MS already retired Linux Teams client

### ISSUE THREAD

**Issue by JGMelon22** [IsmaelMartinez/teams-for-linux#729]
I know, the readme file already says "This is an unofficial Microsoft Teams client. The official client for Linux is  to be retired by end of 2022.", however this rumor already is a reality. Even the AUR maintainer does not have the .deb file anymore, only the binary file. Thanks as always, Ismael and fellas. You guys are the real heroes :D

**Comment by jijojosephk** [comment]
Will update the readme. Still unaware of the future. Electron is not a memory efficient framework. But I wonder why MS continuously ignores Linux when they directly or indirectly get benefitted from open source and linux eco system. Are they being really thankless?

**Comment by JGMelon22** [comment]
Well, this ain't the first time they just ignore us. Have you ever heard of monodevelop? I'm just thankful your project do exist 🙏

**Comment by jijojosephk** [comment]
MS moving away from Angular to React. Currently the web is on angular, if they migrate the web version to react, we might have a problem. MS says webview2 is in preview for Mac and Linux but no-one really knows what's gonna happen. Macs gonna get something for sure but Linux, still doubtful.

**Comment by jijojosephk** [comment]
@JGMelon22 I've updated the readme file. Hence closing this. Please do report if you find any other outdated information. Thanks a lot for reporting.
