### ISSUE TITLE
error: snap "teams" has no plug named "camera"

### ISSUE THREAD

**Issue by pacuna** [IsmaelMartinez/teams-for-linux#73]
Hi! Thanks for the amazing project.

I'm having issues trying to connect my camera. I'm getting this error when running the command mentioned in the documentation:

    $ sudo snap connect teams:camera core:camera
    error: snap "teams" has no plug named "camera"

But when I see the interfaces for the camera I get this:

```
$ snap interface camera
name:    camera
summary: allows access to all cameras
plugs:
  - teams-for-linux
  - vlc
slots:
  - core
```

But I'm still not able to connect the camera 
![image](https://user-images.githubusercontent.com/1724136/54847035-48711580-4cab-11e9-8999-670837c26eb6.png)

Any ideas?

Thanks!

**Comment by pacuna** [comment]
Sorry I just saw (this)[https://github.com/IsmaelMartinez/teams-for-linux/pull/71] PR and used teams-for-linux instead of teams and it worked. 

Thanks!

**Comment by benyanke** [comment]
I'll update the docs as well - thanks for the quick find!
