### ISSUE TITLE
No notification if in chat but out of focus

### ISSUE THREAD

**Issue by 31337-4554551n** [IsmaelMartinez/teams-for-linux#756]
**Describe the bug**
If you have the conversation with a person open, but your window focus is on another window, notifications do not come through

**To Reproduce**
Open a conversation with a person
Start using a different program/have teams lose focus
Receive a message

**Expected behavior**
A notification tells you that the person has sent a message when focus is elsewhere.
No notification if a message comes through to that chat and teams has focus.

**Actual behaviour**
No notification appears. New notifications only appear if a message is received in a different chat while teams does not have focus

**Desktop (please complete the following information):**
 - OS: pop os 22.04
 - Installation package flatpak
 - Version 1.0.65

**Comment by jijojosephk** [comment]
@31337-4554551n That's how it is web version of the app. I'm not sure we have some control there. Notifications come only for the non-focused chats.

**Comment by jijojosephk** [comment]
@31337-4554551n this would be a very difficult thing to implement as it is how currently in the web app. Closing this but if you feel this can be addressed in any way, please re-open.
