### ISSUE TITLE
Languages other than English not available for spell-check

### ISSUE THREAD

**Issue by Normand-Nadon** [IsmaelMartinez/teams-for-linux#760]
For some time, spell check was working in french. Now it stopped working.

I am on the flatpak version 1.0.69

I don't know how I can help with this issue, but I am willing to... If you need any additional information, just say it :)

![image](https://user-images.githubusercontent.com/60982016/233704035-625141c7-56cc-49f9-b5c8-1038de7cb09f.png)

Again, this project is amazing! Thanks to the few people who maintain it while Microsoft bailed on us! 👍🏻

**Comment by Normand-Nadon** [comment]
I am sorry, I just re-read the "known issue" page and will close this issue... It is already adressed.
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md

**Comment by Normand-Nadon** [comment]
I re-checked and I have all the languages installed in hunspell... what am I missing?

![image](https://user-images.githubusercontent.com/60982016/233713994-c92f3385-3a27-4a59-bbc3-2fc851bdc496.png)

**Comment by jijojosephk** [comment]
@Normand-Nadon from the beginning the app was using Hunspell and had a nodejs library to support it. But the node library is no more maintained and the builds started failing when nodejs upgrade happened. So we switched to Electron's own dictionary. Writing language was added as a command line option than listing all the languages. The manu `Writing Languages` is built from the command-line arguments. If no values are passed, the defaults would be [`en-US`, `en-GB`]. Please have a look [here](https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config). You may use `--spellCheckerLanguages en-US` as an example. According to your locale, you can pass the argument.

**Comment by jijojosephk** [comment]
@Normand-Nadon please visit release `1.0.70`

**Comment by jijojosephk** [comment]
Fixed in the latest version.

**Comment by Normand-Nadon** [comment]
Worked right away! You are awesome @jijojosephk  !!! Thank you so much!
