### ISSUE TITLE
Screen sharing snap package

### ISSUE THREAD

**Issue by xtrondo** [IsmaelMartinez/teams-for-linux#765]
Any plans to fix  "Screen sharing" on "snap" ? Doesn't work, on new Fedora 38 Workstation, same error as Fedora 37:

Apr 24 12:56:51 hydra teams-for-linux+1_teams-for-linux.desktop[5184]: [5184:0424/125651.127004:ERROR:shared_screencast_stream.cc(402)] One of following libraries is missing on your system:
Apr 24 12:56:51 hydra teams-for-linux+1_teams-for-linux.desktop[5184]:  - PipeWire (libpipewire-0.3.so.0)
Apr 24 12:56:51 hydra teams-for-linux+1_teams-for-linux.desktop[5184]:  - drm (libdrm.so.2)
Apr 24 12:56:51 hydra teams-for-linux+1_teams-for-linux.desktop[5184]: [5184:0424/125651.127031:ERROR:base_capturer_pipewire.cc(60)] ScreenCastPortal failed: 1

The problem is not missing libraries system-wide, because "flatpak" and "rpm" works on the same machine without issues.

**Comment by IsmaelMartinez** [comment]
did you give snap the right permissions ?

**Comment by jijojosephk** [comment]
snap and wayland seems like a weird combination.

**Comment by xtrondo** [comment]
What kind of permissions ? for some context on same system, discord "screen sharing" works, I compare "snap connections" from discord to teams-for-linux and don't see something obvious missing related to screencast.

**Comment by jijojosephk** [comment]
`sudo snap connections teams-for-linux` should have these

audio-playback            teams-for-linux:audio-playback          :audio-playback                  -
browser-support           teams-for-linux:browser-support         :browser-support                 -
camera                    teams-for-linux:camera                  :camera                          -
content[gnome-3-28-1804]  teams-for-linux:gnome-3-28-1804         gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     teams-for-linux:gtk-3-themes            gtk-common-themes:gtk-3-themes   -
content[icon-themes]      teams-for-linux:icon-themes             gtk-common-themes:icon-themes    -
content[sound-themes]     teams-for-linux:sound-themes            gtk-common-themes:sound-themes   -
desktop                   teams-for-linux:desktop                 :desktop                         -
desktop-legacy            teams-for-linux:desktop-legacy          :desktop-legacy                  -
gsettings                 teams-for-linux:gsettings               :gsettings                       -
home                      teams-for-linux:home                    :home                            -
network                   teams-for-linux:network                 :network                         -
opengl                    teams-for-linux:opengl                  :opengl                          -
pulseaudio                teams-for-linux:pulseaudio              :pulseaudio                      -
screen-inhibit-control    teams-for-linux:screen-inhibit-control  :screen-inhibit-control          -
unity7                    teams-for-linux:unity7                  :unity7                          -
upower-observe            teams-for-linux:upower-observe          :upower-observe                  -
wayland                   teams-for-linux:wayland                 :wayland                         -
x11                       teams-for-linux:x11                     :x11                             -

**Comment by jijojosephk** [comment]
If you're sure the permissions are correct, then run this.

`teams-for-linux --appLogLevels error,warn,info,debug` and see what logs when you start screen-sharing.

If nothing,

you can check the developer tools console.

1. Click on the tray icon.
2. Choose debug from menu
3. Choose console tab in developer tools

Have a look at the errors logged there. Also you can share it here.

**Comment by xtrondo** [comment]
Thanks for the followup, I try to debug it before I open the issue, it's on first post, new run:

DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[26051:0424/152021.606433:ERROR:shared_screencast_stream.cc(402)] One of following libraries is missing on your system:
 - PipeWire (libpipewire-0.3.so.0)
 - drm (libdrm.so.2)
[26051:0424/152021.606451:ERROR:base_capturer_pipewire.cc(60)] ScreenCastPortal failed: 1

on flatplak I can see via find "libpipewire-0.3.so", but not on snap, libdrm found on both

**Comment by jrevillard** [comment]
Hello,

I have the same issue on Ubuntu (22.10).

```
[20381:0425/083759.554777:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.208" (uid=1000 pid=20381 comm="/snap/teams-for-linux/340/teams-for-linux --no-san" label="snap.teams-for-linux.teams-for-linux (enforce)") interface="org.freedesktop.login1.Manager" member="Inhibit" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=2091 comm="/lib/systemd/systemd-logind" label="unconfined")
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
[20381:0425/083759.701150:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
../src/intel/isl/isl.c:1988: FINISHME: ../src/intel/isl/isl.c:isl_surf_get_ccs_surf: CCS for 8BPP textures with 3+ miplevels is disabled, but support for more levels is possible.
[20599:0425/083818.533989:ERROR:ssl_client_socket_impl.cc(983)] handshake failed; returned -1, SSL error code 1, net_error -200
[ERROR] An unexpected SSL error has occurred: net::ERR_CERT_COMMON_NAME_INVALID
[20381:0425/083839.135905:ERROR:shared_screencast_stream.cc(402)] One of following libraries is missing on your system:
 - PipeWire (libpipewire-0.3.so.0)
 - drm (libdrm.so.2)
[20381:0425/083839.135936:ERROR:base_capturer_pipewire.cc(60)] ScreenCastPortal failed: 1
```

libpipewire is installed on my system.

Best,
Jerome

**Comment by xtrondo** [comment]
Fedora 38, but same issue on Fedora 37, libpipewire is installed, also installed from rpm or flatpak works on both systems.

**Comment by jijojosephk** [comment]
This is snap specific. Snap + wayland combo does not work I believe. I'm on Ubuntu Budgie 22.04 and has X11. So, unable to find the issue and fix. Someone has to come forward and try. Sorry!

**Comment by jijojosephk** [comment]
@xtrondo there's a new `--edge`  build for `1.0.73`. Can you try?

**Comment by xtrondo** [comment]
Thanks, tested with same result:

teams-for-linux    1.0.73                      343    latest/edge    ismaelmartinez  -

Apr 27 11:16:18 hydra teams-for-linux_teams-for-linux.desktop[5591]: [5591:0427/111618.141162:ERROR:shared_screencast_stream.cc(402)] One of following libraries is missing on your system:
Apr 27 11:16:18 hydra teams-for-linux_teams-for-linux.desktop[5591]:  - PipeWire (libpipewire-0.3.so.0)
Apr 27 11:16:18 hydra teams-for-linux_teams-for-linux.desktop[5591]:  - drm (libdrm.so.2)
Apr 27 11:16:18 hydra teams-for-linux_teams-for-linux.desktop[5591]: [5591:0427/111618.141183:ERROR:base_capturer_pipewire.cc(60)] ScreenCastPortal failed: 1

**Comment by jijojosephk** [comment]
Many snaps are having issues with wayland. Not sure how to fix. May be only snap team

**Comment by jijojosephk** [comment]
I tried many things and found investing time on snaps is wastage of efforts. My main focus was on how to add pipewire package to snap based on [this](https://www.electron.build/configuration/snap.html).

1. Adding `stagePackages` was throwing error in electron builder. Seems to have some logical errors in the implementation.
2. To overcome, all the plugs (defaults) should be added explicitly.
3. Then comes the multipass requirement.
4. I'm not sure how to make it run locally or in git hub actions.
5. Tried LXD too.

To try `stagePackages`, at least the build should succeeded. If that's not happening, I don't know how to proceed. To me ubuntu or electron team need to fix an underlying problem before we can at least try to add the package to the snap. Other wise snap team should fix the library access permission. I lost interest to fix this problem. My suggestion would be to use native packages or flatpak or even AppImage.

**Comment by tkalfaoglu** [comment]
How about switching to X11 while using teams? It might be a work-around until a fix is made?

**Comment by IsmaelMartinez** [comment]
that is an option, or use one of the other packaging systems. We might not be able to help much on this as it will probably related to some system configuration and/or weird dependencies between applications. Maybe use flathub if you want something closer to snap.

**Comment by jijojosephk** [comment]
@xtrondo unfortunately, we're not able to provide a solution. Hence closing this. If you're for sandboxed versions, we suggest flatpak now.
