### ISSUE TITLE
Add Some Default extra Custom CSS 

### ISSUE THREAD

**Issue by IsmaelMartinez** [IsmaelMartinez/teams-for-linux#77]
Following #50 , it will be great to provide some of the custom css found in userstyles packaged in the app:

* add the MS related custom styles available in userstyles.org. At the time of writing those are:
** https://userstyles.org/styles/164546/compact-microsoft-teams-for-dark-theme
** https://userstyles.org/styles/164545/compact-microsoft-teams-for-light-theme
** https://userstyles.org/styles/154382/microsoft-teams-tweaks
** https://userstyles.org/styles/164547/condensed-microsoft-teams-for-light-theme
** https://userstyles.org/styles/164548/condensed-microsoft-teams-for-dark-theme
* add the ability to select one of the styles in startup
* the css files must be packaged with the app. 
* a reference to the url where the style is coming from must be at the top of the css file.

To have CSS designed for Stylus working minor tweaking is needed:

* remove @-moz-document domain(teams.microsoft.com) { }
* add !important to CSS rules

As @bartebor explained in 
https://github.com/IsmaelMartinez/teams-for-linux/issues/50#issuecomment-470836961

**Comment by IsmaelMartinez** [comment]
If anyone is happy to test it, this is mostly implemented in 0.1.18. 

I still need to update the `config/README.md` file. The valid values are in the `config/index.js`...

Basically `yarn start --customCSSName compactLight`

I tested compactDark, compactLight and tweaks but then my laptop run out of battery.

**Comment by intensite** [comment]
Silly question here, 

How does one use the dark theme with the .deb release version on linux mint?  It works fine with the git source but I would prefer using the official release version.  

I tried to modify the launcher like this but the theme is ignored.
`"/opt/Teams for Linux/teams-for-linux" %U "condensedDark"`

Any suggestions?

**Comment by IsmaelMartinez** [comment]
Hi @intensite , 

Try creating a config.json file under `~/.config/teams-for-linux/` 

That file can be like this:

```
{
"customCSSName": "condensedDark"
}
```
Then kill the process and start it again. It should just work.

The folder might be `~/.config/Teams\ for\ Linux`

**Comment by intensite** [comment]
Thanks for the answer.
Tried both locations without success.  
Also tried in the installation directory /opt/Teams for Linux/.config  

Directly on the command line like this
 ./teams-for-linux --customCSSName condensedDark
did not change anything either :-( 

Is it possible the css is simply not included in the .deb archive?

**Comment by IsmaelMartinez** [comment]
I Will be surprised as the others are included. Can you check the other options? 

Worse comes to worse you can use the customCSSLocation  and download that CSS. 

Make sure you have killed the app as, if it's running in the background, it will only focus the app window without the new CSS styles

**Comment by IsmaelMartinez** [comment]
probably open it as a bug if you don;t find hwo to make it work. Thansk!
