### ISSUE TITLE
Clicking on a link always shows a popup

### ISSUE THREAD

**Issue by foxylion** [IsmaelMartinez/teams-for-linux#796]
**Describe the bug**
There is now a dialog that is shown for every link click.
![image](https://user-images.githubusercontent.com/2699280/235905089-8cd43071-2104-45c9-a3cc-d0499c323490.png)

This should not be the default behavior. Any link click does now require two clicks and an additional mouse movement. Pretty bad UX.

When you try to open multiple links in a row this task takes now ages to complete because I have to move my mouse two times instead of one and have to click two times.

**To Reproduce**
1. Go to MS Teams App
2. Click on a link
3. Dialog is shown

**Expected behavior**
The dialog should be optional (configurable).

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package snap
 - Version 1.0.80

**Comment by jijojosephk** [comment]
@elhennig come here :laughing:

**Comment by elhennig** [comment]
Well, making this behavior configurable or give an option to save the chosen way to open a URL would be fine for me. As long as my authentication problem can be solved, still, I am fine with that. Gong back I would not like, as the new dialogue solved my problem with SSO links within Teams apps.

**Comment by jijojosephk** [comment]
@elhennig CTRL+click for SSO in `1.0.82`

**Comment by jijojosephk** [comment]
@foxylion `1.0.82` is out. Click freely! :smile:

**Comment by foxylion** [comment]
Awesome, thanks a lot! Really appreciate the app. :-)

**Comment by elhennig** [comment]
I appreciate it, too. And even more so the work of @jijojosephk
