### ISSUE TITLE
Personal Package Archive (PPA) for Debian Packages

### ISSUE THREAD

**Issue by tirolerstefan** [IsmaelMartinez/teams-for-linux#801]
Hi, I really like this project and started using teams for linux since some days and I'm very happy because of the good desktop integration on Ubuntu. Also it is really fantastic how many binary packages you provide.

My wish: do you think, it is possible to host the produced debian packages on a PPA to easily download them using `apt`?

**Comment by jijojosephk** [comment]
Thanks @tirolerstefan we're yet to figure out how to have PPA. It's not so straight forward for electron based apps.

**Comment by jijojosephk** [comment]
@tirolerstefan for your ref: https://askubuntu.com/questions/794953/electron-app-as-ppa

Seems difficult. Would you use flatpak if automatic update is a concern?

**Comment by tirolerstefan** [comment]
I see - no need for flatpack, currently. Thanks for checking this!

**Comment by raul-klg** [comment]
From what I've heard, I wonder if https://build.opensuse.org/ could be of help here

**Comment by tirolerstefan** [comment]
Maybe this is worth a try:
https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html

**Comment by jijojosephk** [comment]
Thanks, I'll have look.

**Comment by jijojosephk** [comment]
> Maybe this is worth a try: https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html

This looks cool.

**Comment by jijojosephk** [comment]
`curl -s --compressed "https://jijojosephk.github.io/ppa/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/jijojosephk.github.io.gpg >/dev/null`

`sudo curl -s --compressed -o /etc/apt/sources.list.d/jijojosephk.github.io.list "https://jijojosephk.github.io/ppa/jijojosephk.github.io.list"
`

`sudo apt update`

`sudo apt install teams-for-linux`

**Comment by jijojosephk** [comment]
@tirolerstefan  can you confirm the above works and close if you're ok?

**Comment by jijojosephk** [comment]
> Maybe this is worth a try: https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html

Thanks a lot for this.

**Comment by jijojosephk** [comment]
May be its is better to cloudsmith.

**Comment by jijojosephk** [comment]
> `curl -s --compressed "https://jijojosephk.github.io/ppa/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/jijojosephk.github.io.gpg >/dev/null`
> 
> `sudo curl -s --compressed -o /etc/apt/sources.list.d/jijojosephk.github.io.list "https://jijojosephk.github.io/ppa/jijojosephk.github.io.list" `
> 
> `sudo apt update`
> 
> `sudo apt install teams-for-linux`

I'll delete this and move to cloudsmith.

**Comment by jijojosephk** [comment]
`curl -1sLf 'https://dl.cloudsmith.io/public/teams-for-linux/packages/setup.deb.sh' | sudo -E bash`
`sudo apt update`
`sudo apt install teams-for-linux`

**Comment by tirolerstefan** [comment]
Worked well - thanks a lot!

**Comment by RolandRosenfeld** [comment]
I hate complex scripts from internet, that I run as root, so I manually created an apt repo entry:
`deb [signed-by=/etc/apt/keyrings/teams-for-linux.key] https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian bullseye main`
(just ignore the modified key filename).
This downloads /var/lib/apt/lists/dl.cloudsmith.io_public_teams-for-linux_packages_deb_debian_dists_bullseye_InRelease but no Packages files.  Maybe because the Packages for debian bullseye are empty:
` d41d8cd98f00b204e9800998ecf8427e 0 main/binary-amd64/Packages`
Also downloading https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian/dists/bullseye/main/binary-arm64/Packages results in an empty file...

**Comment by jijojosephk** [comment]
> I hate complex scripts from internet, that I run as root, so I manually created an apt repo entry:
> `deb [signed-by=/etc/apt/keyrings/teams-for-linux.key] https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian bullseye main`
> (just ignore the modified key filename).
> This downloads /var/lib/apt/lists/dl.cloudsmith.io_public_teams-for-linux_packages_deb_debian_dists_bullseye_InRelease but no Packages files.  Maybe because the Packages for debian bullseye are empty:
> ` d41d8cd98f00b204e9800998ecf8427e 0 main/binary-amd64/Packages`
> Also downloading https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian/dists/bullseye/main/binary-arm64/Packages results in an empty file...
> 

Upload to cloudsmith must have a distro. I think i chose Ubuntu. But all debs should be the same. I don't know why they have such an option. Looks like I have to upload one more for debian. If that's, it looks stupid to me. Someone can correct me if I'm wrong

**Comment by jijojosephk** [comment]
@RolandRosenfeld can you try now?

**Comment by jijojosephk** [comment]
Sorry, uploaded at a different location.

**Comment by jijojosephk** [comment]
You should be able to now.


![image](https://user-images.githubusercontent.com/11662148/236791007-0b34a05c-3839-4df1-bb04-10c7551f8c2f.png)

**Comment by RolandRosenfeld** [comment]
Now the Packages file is no longer empty and now I am able to download the package.
Thanks for fixing this, so I can now get rid of my workaround that pulls the package from github (every morning) and generates a local apt repo from this on our company server :-)

**Comment by jijojosephk** [comment]
Sure, but teach me why we need to have different packages for debian and ubuntu. My knowledge is limited still can't come to terms with this.

**Comment by jijojosephk** [comment]
I'm closing this. I'll update the read me. We can have the same for rpms as well. If someone requests, I'd upload.

**Comment by RolandRosenfeld** [comment]
I'm just preparing an [extrepo ](https://packages.debian.org/sid/extrepo) recipe for teams-for-linux.
While doing so, I had another look at https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian/dists/sid/InRelease and noticed, that this lists the following architectures: amd64 arm64 armel armhf i386.
But all packages files except amd64 are currently empty.
In contrast to this, github lists deb files for the following architectures in the Releases: amd64 arm64 armv7l.
Would it be possible to fix this in cloudsmith repo?

**Comment by jijojosephk** [comment]
> I'm just preparing an [extrepo ](https://packages.debian.org/sid/extrepo) recipe for teams-for-linux. While doing so, I had another look at https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian/dists/sid/InRelease and noticed, that this lists the following architectures: amd64 arm64 armel armhf i386. But all packages files except amd64 are currently empty. In contrast to this, github lists deb files for the following architectures in the Releases: amd64 arm64 armv7l. Would it be possible to fix this in cloudsmith repo?

Probably, it was created yesterday. Many things to explore.

**Comment by jijojosephk** [comment]
Whatever produced from github releases can be uploaded straight to the cloudsmith repo when the published as stable release. Need to work on the pipeline and integrating cloudsmith CLI in github. Currenly I'm doing it manually :smile:

**Comment by lskillen** [comment]
Hi! 👋 Lee from Cloudsmith here. You can also specify `any-distro/any-version` if you don't want to keep Ubuntu and Debian separate to make a truly "works for any distro and version" package.

As for why they're separate: Although Ubuntu is Debian based, they still have very different release cadences and qualification processes for what is included in the distros. Therefore, compatibilities _can_ arise. :-)

**Comment by jijojosephk** [comment]
> Hi! wave Lee from Cloudsmith here. You can also specify `any-distro/any-version` if you don't want to keep Ubuntu and Debian separate to make a truly "works for any distro and version" package.
> 
> As for why they're separate: Although Ubuntu is Debian based, they still have very different release cadences and qualification processes for what is included in the distros. Therefore, compatibilities _can_ arise. :-)

Thanks so much  @lskillen That's a relief :smile:

**Comment by jijojosephk** [comment]
> I'm just preparing an [extrepo ](https://packages.debian.org/sid/extrepo) recipe for teams-for-linux. While doing so, I had another look at https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian/dists/sid/InRelease and noticed, that this lists the following architectures: amd64 arm64 armel armhf i386. But all packages files except amd64 are currently empty. In contrast to this, github lists deb files for the following architectures in the Releases: amd64 arm64 armv7l. Would it be possible to fix this in cloudsmith repo?

Now all the 3 architectures are uploaded. Not sure about i386 how it's listed there.  @lskillen could you please help us?

**Comment by jijojosephk** [comment]
> > Now all the 3 architectures are uploaded. Not sure about i386 how it's listed there. @lskillen could you please help us?
> 
> IIRC we always generate a few "builtin" architectures, including i386; that isn't something you can disable, but since only i386 clients will care, other than aesthetics, it shouldn't affect any functionality. Part of the issue with not including it, is that clients for that arch get an error, rather than just "no packages available", so I think we made to decision to always generate at some point.

Thank you!
