### ISSUE TITLE
Recent update adding popup to links

### ISSUE THREAD

**Issue by 31337-4554551n** [IsmaelMartinez/teams-for-linux#803]
**Describe the bug**
Every time a link is clicked it's now asking for how it should be opened

**To Reproduce**
Click on a link in a chat

**Expected behavior**
Opens in default browser (equivalent to "external" option)

**Screenshots**
![image](https://user-images.githubusercontent.com/26422914/236371670-299eb1f7-5c1b-40fa-a817-bf5734394879.png)

**Desktop (please complete the following information):**
 - OS: pop-os 22.04
 - Installation package flatpak
 - Version 1.0.83

**Additional context**
Unsure why this option was put in, but it's annoying. Can we please at least get an option to "remember choice" or something?

**Comment by jijojosephk** [comment]
Can you confirm you have latest? 1.0.83 always open without question. Questions only if CTRL + click

**Comment by jijojosephk** [comment]
`1.0.83` has this popup when CTRL+click
![image](https://user-images.githubusercontent.com/11662148/236379355-1d78bcd8-09b9-4de5-8760-cd4910cfd1e1.png)

**Comment by 31337-4554551n** [comment]
I was. But I just reinstalled and it's working fine.
Strange.
Thank you.
