### ISSUE TITLE
Teams crashes upon start-up

### ISSUE THREAD

**Issue by codethief** [IsmaelMartinez/teams-for-linux#805]
**Describe the bug**
Since this morning Teams has been crashing upon start-up, without any error message.

**To Reproduce**

```
$ teams-for-linux
$ 
```
(`teams-for-linux` exits immediately)

**Expected behavior**
Teams should be starting

**Screenshots**
N/A (nothing visible happens, the process terminates immediately)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package: snap
 - Version: 1.0.83 (updated on the evening of May 4 according to `snap info teams-for-linux`)

**Additional context**
In the afternoon of May 4, Teams was still working fine. I didn't (try to) use it again until this morning, so I assume the crashes must be related to the most recent update.

I have now downloaded the tarball of version 1.0.82 and that one seems to be working fine.

**Comment by jijojosephk** [comment]
It's a snap problem. Sadly we don't have any clue why it's happening.

**Comment by jijojosephk** [comment]
Nothing to do with latest version

**Comment by IsmaelMartinez** [comment]
can you try the snap --edge channel? maybe that release got a bit "funny". It could also be system configuration. Snap can be a bit temperamental

**Comment by codethief** [comment]
I just uninstalled the snap and then tried both `snap install --channel edge teams-for-linux` (v1.0.85) and `snap install teams-for-linux` (v1.0.84). In both cases, Teams no longer crashes. 

Looks like it was either the minor version update to 1.0.83 that caused the crash (unlikely) or (more likely) Teams arrived at an illegal state and a mere reinstallation of 1.0.83 would have fixed the issue, too. (Should have thought of this…)

Thanks so much for your help!

**Comment by codethief** [comment]
Unfortunately, the issues have re-surfaced in the past ~2 weeks (likely since the automatic update to `latest/stable:    1.1.1 2023-05-31`). Once again, both switching/updating to the edge channel (v1.1.6) or merely reinstalling v1.1.1 seem to solve the issue. This

**Comment by codethief** [comment]
Ok, will do! Thank you!

**Comment by jijojosephk** [comment]
Thanks @codethief, I suppose `flatpak` works for you. Me and @IsmaelMartinez  had tried to look into `snap` issues but could not really fix anything. I'm on Ubuntu `22.04`, and may snap apps crashes, probably for me it's really worse, as the entire system is frozen and have to do press reset button.

**Comment by jijojosephk** [comment]
Would close this, may be in the future, we can have look. In general, we're less happy about snap. We try to package this in as many formats as possible. Sadly `snap` a no go for me at least.
