### ISSUE TITLE
Microphone not being picked up during calls

### ISSUE THREAD

**Issue by codeonblocks** [IsmaelMartinez/teams-for-linux#806]
**Describe the bug**
Whenever I'm on any calls the microphone won't work and the other person can't hear anything. I tried it with the Chrome PWA and it was working perfectly, but not with this app.

**To Reproduce**
1. Join a call with anyone
2. Select head set and microphone

**Expected behavior**
It should pick up my voice.

**Desktop (please complete the following information):**
Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20-generic (64-bit)
Flathub Package: 1.0.83

**Comment by jijojosephk** [comment]
Is it when selecting during the call or before the call's started?

**Comment by codeonblocks** [comment]
> 

It's at any point. It doesn't pick it up at all.

**Comment by jijojosephk** [comment]
Was kubuntu an upgrade or fresh install?

**Comment by IsmaelMartinez** [comment]
can you try with the deb version? it might be a permissions issue with flathub with your system.

**Comment by codeonblocks** [comment]
> Was kubuntu an upgrade or fresh install?

Fresh install.

**Comment by codeonblocks** [comment]
> can you try with the deb version? it might be a permissions issue with flathub with your system.

I'll give that a try. It maybe is because I am using the Flatpak version. If I use the .deb version, would I have to manually update it when a new version is released?

**Comment by jijojosephk** [comment]
With `flatpak` you need to use `flatpak update` like `sudo apt update && sudo apt upgrade` for `apt` in debian derivatives. If you're okay with native debian package, try this:

`curl -1sLf 'https://dl.cloudsmith.io/public/teams-for-linux/packages/setup.deb.sh' | sudo -E bash`
`sudo apt update`
`sudo apt install teams-for-linux`

**Comment by jijojosephk** [comment]
Let us know if the deb solves the problem. Any `sandboxing' packages like `flatpak`, `snap` may have issues related to permissions and those varies from distro to distro. We try to provide as many packages as possible hence many challenges too. I'm always for native packages, but when people concerned about security, they look for sandboxing.

**Comment by jijojosephk** [comment]
When we put our efforts during our freetime, this is what we get in return while many find the app solving their challenges. This is from ubuntu store. No option to at least reply to those and ask for reasons or even tell them come to git hub and seek answers.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/64ad5147-ec08-4480-a2d0-2ed4c217071e)

**Comment by IsmaelMartinez** [comment]
@jijojosephk , just ignore them. It was one of the initial reasons why I didn't pursuit early on the snap complexity but there are more than 100K users in there, so its just a small number of people shouting at the wrong side. 

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/62df211d-fb3b-4be2-9805-e54a8c65258c)

I added a wee note (but I suspect half of the people will not read it) 
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/b1ca5840-d6c7-4351-aba1-068591731e37)

**Comment by jijojosephk** [comment]
@codeonblocks could you confirm?

**Comment by codeonblocks** [comment]
> sudo apt install teams-for-linux


> With `flatpak` you need to use `flatpak update` like `sudo apt update && sudo apt upgrade` for `apt` in debian derivatives. If you're okay with native debian package, try this:
> 
> `curl -1sLf 'https://dl.cloudsmith.io/public/teams-for-linux/packages/setup.deb.sh' | sudo -E bash` `sudo apt update` `sudo apt install teams-for-linux`

Will these commands add a repo that will notify me when there are new updates?

I also just tested with this and the microphone is working.

**Comment by codeonblocks** [comment]
I think it would be helpful to add some more info to the `README.md` on how to download the native package.

**Comment by jijojosephk** [comment]
> > sudo apt install teams-for-linux
> 
> > With `flatpak` you need to use `flatpak update` like `sudo apt update && sudo apt upgrade` for `apt` in debian derivatives. If you're okay with native debian package, try this:
> > `curl -1sLf 'https://dl.cloudsmith.io/public/teams-for-linux/packages/setup.deb.sh' | sudo -E bash` `sudo apt update` `sudo apt install teams-for-linux`
> 
> Will these commands add a repo that will notify me when there are new updates?
> 
> I also just tested with this and the microphone is working.

Yes `sudo apt  update` list any new versions and `sudo apt upgrade` get you the latest version. Ubuntu and other distros shows a GUI notification as well. All you need to do is to confirm updating the new versions.

**Comment by jijojosephk** [comment]
Closing this as native packages work. It's only related to `flatpak` permissions.

**Comment by jijojosephk** [comment]
> > Closing this as native packages work. It's only related to `flatpak` permissions.
> 
> Great, thank you! Last question: What's the benefit of using this package vs just using the PWA?

Well, there are many. :smile: 

1. This looks like a native app though it's a web wrapper.
2. Isolated from chrome/chromium browser storages, sessions
3. Notifications native to the OS.
4. Notification counts on the tray.
5. Many command line arguments to control the app in your own way.
6. Wayland support
7. More flexible screen sharing options.
8. Custom backgrounds.
9. Save/Restore application settings like themes, devices etc. when you need to do hard reset.
10. Many more.. may be someone else would speak :smile: 
11. A supportive community.

**Comment by codeonblocks** [comment]
Awesome, thank you!

**Comment by jijojosephk** [comment]
@codeonblocks updated README.md
