### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by nneul** [IsmaelMartinez/teams-for-linux#809]
This may seem a silly ask - but came out of a conversation sharing about this tool with a coworker. Is there any reason a build couldn't be generated for windows to allow easy use of the multiple profile support like we can do on linux side?

**Comment by jijojosephk** [comment]
Is it worth the effort? Building may not be difficult unless there's something that's written only for Linux. Someone has to come forward and do it. I'm not sure anyone would be interested take such activities. @IsmaelMartinez do you think something can be done?

**Comment by IsmaelMartinez** [comment]
I will only allow this if it is still called teams-for-linux. 

Jokes a side, if someone wants to do the development and provide the support then it is fine. But I haven't used windows in a long time so I will not be able to do much.

Electron is, in principle, built to handle different OS' but in practice each of them have their caveats.

**Comment by nneul** [comment]
100% upvote on it still being called teams-for-linux. :grinning:

**Comment by jijojosephk** [comment]
How about WSL?

https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by nneul** [comment]
It actually worked right out of the box with just trivial additional lines to the workflow and package json.

**Comment by nneul** [comment]
Haven't tried using for more than just launching and making sure the UI works, but it installed and came up just fine.
