### ISSUE TITLE
App froze after adding long string in chat.

### ISSUE THREAD

**Issue by bigkrp** [IsmaelMartinez/teams-for-linux#811]
**Describe the bug**
The application froze and didn't react to any action. It happened after I paste to chat long string, like `cUrl`.

**Screenshots**
![Screenshot from 2023-05-10 10-52-20](https://github.com/IsmaelMartinez/teams-for-linux/assets/11586744/2b5028ad-fbec-4228-8fb8-e45a031b6338)
![Screenshot from 2023-05-10 11-07-31](https://github.com/IsmaelMartinez/teams-for-linux/assets/11586744/dc2a291a-444f-43ec-82e0-36c8ea23933e)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Installation package rpm
 - Version 1.0.84

Maybe I can clear some cache? Because when I've tried run teams from Firefox it didn't show me my last message with this long string and works well.

**Comment by bigkrp** [comment]
Ok. It fixes with `Quit -> Clear Storage` and re-login.

**Comment by IsmaelMartinez** [comment]
glad that fixes it. have you tried to see what happens if you paste that curl into firefox? does it go bananas? Thanks!

**Comment by jijojosephk** [comment]
@bigkrp Probably the same might happen with google-chrome as well. If this does not require any investigation, I'll close this. Let us know if you need help.
