### ISSUE TITLE
When screen sharing, outline the window / screen being shared

### ISSUE THREAD

**Issue by psidhu** [IsmaelMartinez/teams-for-linux#812]
**Is your feature request related to a problem? Please describe.**
I've found it difficult to maintain what I'm sharing/not sharing something I thought I was sharing. The native linux app (before being deprecated) alleviated this by outlining the display being shared in red.

**Describe the solution you'd like**
Outline the window or screen being shared with a red border.

I've looked around KNOWN_ISSUES.md and searched issues, but haven't found anything relating to this, so hopefully this isn't spam.

Thank you!

**Comment by IsmaelMartinez** [comment]
I think this has been asked before (https://github.com/IsmaelMartinez/teams-for-linux/issues/606)

Unfortunately there isn't an easy way to do that, or we haven't come up with an easy solution. 

Lets think of options that could make this easier... it might be possible if we add tabs (to support multiple accounts open) but that will require quite a bit of work... I might have a bash at it and see if I can come up with something but do feel free to bring ideas!

**Comment by psidhu** [comment]
> I think this has been asked before (#606)
Ah dang, I missed it, haha. We can close this one and discuss over there if you'd like, or just start fresh here.

**Comment by jijojosephk** [comment]
@psidhu we can discuss there.
