### ISSUE TITLE
Am I the only whos Emojis stopped working completely?

### ISSUE THREAD

**Issue by Normand-Nadon** [IsmaelMartinez/teams-for-linux#816]
I am using the Flatpak version, on Pop!OS, with the latest update.

Since yesterday, I lost the ability to use emojis (either from typing, or from the menu)

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/60982016/89b24998-6b30-4f02-a386-524878fa2ea2)

Does it affect other users?

**Comment by IsmaelMartinez** [comment]
HI, can you fill the template with more info? knowing things like the version you are using, logs, etc, helps a lot.

Also, can you try with another package type to make sure if not a flatpak only issue. Thanks

**Comment by jijojosephk** [comment]
I can see. I'm having flatpak. See if you get them back with a fresh start. `Menu->Quit->ClearStorage`

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/87c8d645-65f3-4d4b-b46b-e5b4e19f603b)

**Comment by Normand-Nadon** [comment]
My version is 1.0.86

I just found-out where the issue lies... The french version!
If I put the app in english, the emojis return... There is the same behavior in Brave-browser and firefox...

Again, the team behind this unofficial app is one step faster than Microsoft! Good job!

Can someone pinpoint what causes this so I can send a detailed report to Microsoft? Like what calls are made that fail?

Thank you!

**Comment by jijojosephk** [comment]
Glad to know it's not related to `teams-for-linux`, it may take some time to understand what's causing the problem. I would say let MS team find what's reason behind. You just need to report french locale having issues. Closing this as it's not related to `teams-for-linux`
