### ISSUE TITLE
History not visible following update to 0.1.16-1

### ISSUE THREAD

**Issue by pbarber** [IsmaelMartinez/teams-for-linux#82]
I've just updated from 0.1.14 to 0.1.16 via AUR and my chat history isn't visible. I can see the full history via Firefox and Chrome. I can see some history for channels/conversations with recent notifications and all other functionality appears to be fine.

**Comment by IsmaelMartinez** [comment]
Hi, can you check the known issues section? There is an explanation on how this can be fixed. In some cases, a simple close/start again works

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/blob/master/README.md#no-history

**Comment by pbarber** [comment]
Thanks @IsmaelMartinez , apologies for unnecessarily raising the issue.

**Comment by IsmaelMartinez** [comment]
Not a problem. Is one of those that keeps popping out
