### ISSUE TITLE
External links are not opened correctly when they point to a Teams channel

### ISSUE THREAD

**Issue by ancwrd1** [IsmaelMartinez/teams-for-linux#827]
**Describe the bug**
After opening a link to a Teams channel in the browser it asks to open it using Teams app (teams-for-linux), however the application does nothing in this case. Links to meetings are opened correctly.

**To Reproduce**
1. Copy and paste channel link to the browser
2. When prompted to use the external application choose teams-for-linux
3. Application is opened but it's not navigated to the channel

**Expected behavior**
Application should navigate to the selected channel

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed with Plasma desktop
 - Installation package: flatpak
 - Version 1.0.88

**Comment by jijojosephk** [comment]
Does it start with `https://teams.microsoft.com/l/channel` ? probably not handled. Thanks for reporting.

**Comment by ancwrd1** [comment]
Yes, it starts with this URL.

**Comment by ancwrd1** [comment]
Sure, here is it:
https://teams.microsoft.com/l/channel/19%3a00000000000000000000000000000000%40thread.tacv2/GroupName?groupId=00000000-0000-0000-0000-000000000000&tenantId=00000000-0000-0000-0000-000000000000

**Comment by jijojosephk** [comment]
Are you using any extension to redirect to the app?

**Comment by ancwrd1** [comment]
Hmm no, just a Firefox browser. But the link is actually a bit different just before it opens in the app:

https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fchannel%2F19%3A00000000000000000000000000000000%40thread.tacv2%2FGroupName%3FgroupId%3D00000000-0000-0000-0000-000000000000%26tenantId%3D00000000-0000-0000-0000-000000000000&type=channel&deeplinkId=00000000-0000-0000-0000-000000000000&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true

![Screenshot_20230517_103043](https://github.com/IsmaelMartinez/teams-for-linux/assets/2361919/0b5aef1e-ce54-4926-abe6-dbe8cff5a1d4)

**Comment by jijojosephk** [comment]
Where do you have the link? In email? I guess you're sharing the link from the browser. I just want to confirm whether the link you click begins with msteams://

**Comment by jijojosephk** [comment]
Ok

**Comment by ancwrd1** [comment]
I tried also with msteams://l/channel link in the browser, but it doesn't work either, same issue (application opens but doesn't navigate).

**Comment by jijojosephk** [comment]
Can you test it with latest pre-release? `1.0.92`

**Comment by ancwrd1** [comment]
With version 1.0.92 it works, thanks for a quick fix!

**Comment by jijojosephk** [comment]
Thanks @ancwrd1 I'll mark the release stable. Appreciate your contribution to the project!
