### ISSUE TITLE
Teams live event opens in browser

### ISSUE THREAD

**Issue by ChristoSnake** [IsmaelMartinez/teams-for-linux#830]
**Describe the bug**
Live events are opened in a browser as opposed to Teams app.

**To Reproduce**
1. Double-click on link that is embedded in meeting.
2. Safe link opens in browser (starts with https://eur01.safelinks.protection.outlook.com/ap/t-59584e83/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fmeetup-join%2F19%253ameeting_MmZkMjhlZmY......). 
3. Link resolves to https://teams.microsoft.com/convene/meetings?url=%2Fl%2Fmeetup-join%2F19%3Ameeting_MmZkMjhlZmY.... in browser after a second or so.
4. Option to open meeting in app or browser is flashed in browser (presumably, because it is there for a VERY short time only!) after which live event is opened in the browser any way.

**Expected behavior**
The option to open the live event either in the desktop app or a browser.

**Screenshots**
Firefox browser settings:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/7ebb8761-3ed8-4787-95c4-e60a0db10033)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed 20230515, KDE Plasma v5.27.5
 - Installation package: rpm
 - Version: teams-for-linux-1.0.92-1.x86_64

**Additional context**
None

**Comment by IsmaelMartinez** [comment]
HI @ChristoSnake ,

Have you tried checking the close issues? I believe I have seen something similar from other users reporting. 

In the past you where able to do Ctrl+click and it will open in the same context, but I am not sure if that is an option anymore.

**Comment by jijojosephk** [comment]
@ChristoSnake My understanding is that `Join` works but `Click here to join the meeting` does not. Isn't it right? By default the later opens up in a popup but `Join` is a redirect to the meeting `url`.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/777fd458-d5fa-4514-8530-f15a8eda4fa6)

**Comment by ChristoSnake** [comment]
jijojosephk, I think the fact that the meeting is sent as a protected URL confuses things!  I do not recollect seeing any "Join" option before the time (and it won't be there now because the live event is over).  In the calendar view this is what I see now:
![Meeting calendar](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/aef1d003-f50c-41b1-8338-80fd404d4ba7)

Hovering over the meeting link shows the "safelinks.protection" URL I pasted above.  The graphic is also hidden (presumably because of the hidden URL?).
![Meeting detail](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/bf86a5ca-6220-4955-a446-e9e1d5d10362)

Clicking on the missing graphic opens the protected link in a browser, resolves its proper URL after a second or so, flashes (what I think are?) join options for a millisecond or so and then goes ahead by joining it in the browser.

**Comment by jijojosephk** [comment]
This is not really straight forward. We can of-course, take the url from safe url and redirect. But it's not a good experience. It's like any other web page redirection. It should be as same a join action which immediately shows the pre-join screen.
 
@ChristoSnake can you let us know what are those live events?

Webinar?

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/3e1072bb-8644-4e7f-a32e-ba6d7cd7baef)

**Comment by IsmaelMartinez** [comment]
It might just be needing to add the `meetup` to a conditional (similar to what we do with the meeting links). I will see if I get some time to either do it or at least link the line.

**Comment by ChristoSnake** [comment]
Thank you, I will do that for the next live event (scheduled for the 21st of July).

Testing before then is not possible - corporate policies state that I can only schedule these meeting types:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/ef4e11a1-1e20-453a-bf35-94894fd7f172)

**Comment by jijojosephk** [comment]
You may join our matrix room: https://matrix.to/#/#teams-for-linux_community:gitter.im

**Comment by ChristoSnake** [comment]
Good news and bad news - the app still launches in a browser, but theRedirector extension (as described in another post) is a workaround.

Debug log using requested startup options (apologies for the screenshot, could not grab the text):

![Meeting - no Firefox redirect debug](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/389ed9ec-dcc8-471c-a93c-0d5a0e8e1706)

Debug log using the Redirector extension:

![Meeting - Firefox redirect debug](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/4e41a5b4-1f75-47e9-b0a0-e60896920339)

When using the extension, a popup offers me the option to select an app:

![Meeting - Firefox redirect 2](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/5654affd-9006-4429-ac4f-8cf8df0b4db5)

The browser is aware of teams-for-linux:

![Meeting - Firefox redirect 3](https://github.com/IsmaelMartinez/teams-for-linux/assets/25453721/244b612e-476e-4df1-8719-969cc230c7cb)

**Comment by jijojosephk** [comment]
@ChristoSnake we can do the redirect internally instead of using extensions. But instead of having a quick transition to the meeting screen, it will be a redirect the whole page needs to be reload. The same happens with extension. I can make that change so that you don't need to use extension to get this working.

**Comment by ChristoSnake** [comment]
I have given up on the Redirector extension - it fixes one issue and creates another.

When the Live Event completes, there is no "Close" button or "Leave" option available on the window.  The only way to close it is by exiting Teams (right click tray icon -> "Quit", then reloading Teams.

It would be wonderful if your change can be the best of both worlds?

**Comment by utoddl** [comment]
Finally got Teams links working through Firefox. Posting here in case it helps anybody.

1. Firefox's "Redirect" plugin rewrites `https://teams.microsoft.com/(.*)` to `msteams://teams.microsoft.com/\1`.
2. Firefox's `handlers.json` now has a `msteams` scheme handler that passes the rewritten uri to `/opt/teams-for-linux/teams-for-linux.sh`, my own shell script.
3. `/opt/teams-for-linux/teams-for-linux.sh` rewrites the leading `msteams:` back into `https:` and passes _that_ on to `teams-for-linux`, like so:
    `teams-for-linux "${@/msteams:/https:}"`

And now, finally, when I click on Teams links, Firefox no longer tries to load the web app, and the "desktop" app (which is really the web app running under Electron) handles it correctly.

**Comment by IsmaelMartinez** [comment]
Closing this issue to clean the open issues. This is because there hasn't been activity for a few months now. If you still face this issue in versions 1.4.1 and above, and/or @utoddl solution doesn't work for you, please share it and we can re-open it. Thanks in advance!
