### ISSUE TITLE
Screen sharing by screen and window

### ISSUE THREAD

**Issue by fpl** [IsmaelMartinez/teams-for-linux#835]
Programs like Skypeforlinux or Meet are able to share by display and even a single application window within any display.  
This is currently not possible in Teams, I'm not sure if it is a Teams limitation (all editions) or an Electron one.

**Comment by RolandRosenfeld** [comment]
I cannot reproduce your issue here (with teams-for-linux 1.1.0 on Debian 11 as deb package with fvwm as window manager).
I can share complete screens as well as single windows.
Only two limitations:
1. The shared screen/window isn't marked during sharing with a special border (so you have to remember which screen/window you are currently sharing).
2. The windows are named "Window 1",...,"Windows 34" (seems I currently have 34 windows open) instead of using the window titles which makes it hard to select the correct window (especially xterms, I usually have tons of them open and they look quite similar in the thumbnail view).

But except this limitations sharing works very well here.

**Comment by fpl** [comment]
Uhm I'm just trying with the latest 1.1.0 and Debian 11 under Gnome. I can only see and share 1 window that is the Teams' one. One would expect to possibly share any of the desktops and applications running.

**Comment by RolandRosenfeld** [comment]
On my system it looks like this:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6381171/ba82020d-2021-42dd-b1ab-40dbf66ae748)
and
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/6381171/9fead9e1-246a-49b0-a7b5-6e4d24d00b80)
Are you using the .deb or the snap package? Seems that the latter often has problems with permissions...

**Comment by fpl** [comment]
Here I'm using the .deb package.

**Comment by RolandRosenfeld** [comment]
Let me compare this with my system:
> ```
> libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed

This is unknown to me, maybe you should deeper investigate this.

> ```
> [ERROR] connect ECONNREFUSED 127.0.0.1:80
I think that is an unsuccessful try to access an local webserver to handle individual background images, this doesn't hurt here.

> ```
> [15530:0527/103901.187211:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [15530:0527/103901.187530:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [15530:0527/103901.187686:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [15530:0527/103901.187846:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
> [15530:0527/103901.192076:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
I can observe these on my system, too.  Currently I ignore them, they don't have to do with this issue here.

> ```
> [15530:0527/103901.269902:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018
Never seen this message, maybe interesting to analyze deeper.

> ```
> [15530:0527/103901.497279:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
I observe a similar, but different error (UnknownMethod instead of Unsupported):
```
[17269:0527/105021.501267:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.UnknownMethod: Unknown method GetActive or interface org.freedesktop.ScreenSaver.
```

**Comment by fpl** [comment]
This 
```
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
```
is probably due to the type of processor of this box, which is an i5 Haswell, not supported by that lib. I can re-check on other systems with different GPUs, anyway.

**Comment by fpl** [comment]
Ah, I see that essentially Teams seems able to share any window only within the same Gnome desktop where it is running, and only those already running in that desktop at start time (any app moved in the desktop after startup is not listed), which is sub-optimal.
![Schermata da 2023-05-27 11-22-41](https://github.com/IsmaelMartinez/teams-for-linux/assets/53651/17b95719-ae5f-4058-8300-13f78171e38d)

**Comment by jijojosephk** [comment]
@fpl, the current electronjs API does not list open windows from other workspaces. It's a known issue. Not sure in future if they implement something to fix this. I'll close for now and pin it.

**Comment by fpl** [comment]
It is a feature, not a bug :-D

**Comment by jijojosephk** [comment]
> It is a feature, not a bug :-D Someone on SO suggested an hack, which is of course not the cleanest solution. https://stackoverflow.com/questions/71970574/how-to-get-other-windows-list-in-electron

I don't think SO suggestion would work.
