### ISSUE TITLE
White Screen with title "Checking your credentials..." if using autostart

### ISSUE THREAD

**Issue by 0verEngineer** [IsmaelMartinez/teams-for-linux#839]
**Describe the bug**
I have teams-for-linux autostarting with the OS, i used the KDE System Settings to do so. But the app does only show a white screen with the app title in the titlebar "Checking your credentials...". I have to quit and reopen it.

**To Reproduce**
1. Install teams-for-linux as flatpak
2. Search for autostart in the KDE System Settings and add it
3. Restart
4. See problem

**Expected behavior**
The app should work normally

**Desktop (please complete the following information):**
 - OS: Kubuntu 23.04
 - Installation package: Flatpak
 - Version: 1.0.92

**Comment by jijojosephk** [comment]
@0verEngineer we have not implemented autostart as a feature with the app. So not sure what's going on. The app does not have file based logs only on console. If you can get the logs and paste it here, we'd be able to find something. Since it's start up, you can add command line parameter `--appLogLevels error,warn,info,debug > tfl_log.txt` in the start up settings. Replace `tfl_log.txt` with what ever path you like to have. You must see something like this.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/19d37467-93a6-4fb7-bfe3-5d226de661dc)

**Comment by 0verEngineer** [comment]
@jijojosephk Afaik every OS has a option to autostart apps, as i mentioned above i use KDE System Settings for it.

I was not able to get the logs with the argument you posted, i use the flatpak version of teams-for-linux and i tried to put the argument inbetween `--command=teams-for-linux` and `--file-forwarding` but then teams did not start at all.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/105462605/9e1a8ed4-272f-4e75-abf0-42b79525cb22)

**Comment by jijojosephk** [comment]
Should be at the end. But I guess you won't get the log file. @IsmaelMartinez any idea how can we get the logs?

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/8ff0f8bd-cabd-4176-8c80-0a8aa912ac3b)

**Comment by jijojosephk** [comment]
Well, I'm using budgie no issue for me.  I did log off and log in. Also restart and log in. It works.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/605c7c7f-e015-46dc-85a5-b754256d81f6)

**Comment by jijojosephk** [comment]
Can you try this?

After a successful login to the app, log off and log in.

**Comment by 0verEngineer** [comment]
I was not able to trigger it, it happens not every time. But on restart i had it happen 3 times last week

**Comment by jijojosephk** [comment]
I suspect internet line is down for a few seconds and Microsoft's code does something and hangs. Are you on WiFi or Ethernet?

**Comment by 0verEngineer** [comment]
Ethernet over a Docking Station

**Comment by IsmaelMartinez** [comment]
maybe you can just delay the start? It is probably some library (or the network) that is trying to startup. The app does have some logic to re-connect when network goes up/down so maybe just see what happens when you unplug the cable and plug it again (not as a solution, but as do determine if is network related)

**Comment by 0verEngineer** [comment]
I will try unplug and replugging the next time it happens

**Comment by IsmaelMartinez** [comment]
Not a solution as such, it's more curiousity. I think adding a delay on the starting will also do. A simple `sleep 20 &` at the beginning might do. Pure hack but sometimes simple is best

**Comment by jijojosephk** [comment]
@0verEngineer did @IsmaelMartinez's suggestion help?

**Comment by jijojosephk** [comment]
I would work on a file based log. Then we might get lucky to understand what's going on.

**Comment by IsmaelMartinez** [comment]
I think trying the sleep option is the best next step. There must be a library or something that hasn't started yet. 

Alternatively, try to make teams-for-linux the last thing that starts-up. Not sure how to do that in KDE.

**Comment by jijojosephk** [comment]
> I think trying the sleep option is the best next step. There must be a library or something that hasn't started yet.
> 
> Alternatively, try to make teams-for-linux the last thing that starts-up. Not sure how to do that in KDE.

Yes, we'd wait for @0verEngineer to confirm.

**Comment by 0verEngineer** [comment]
I did some testing:
- It happens only with the docking station (wifi and ethernet over usb-adapter works)
- A delay in the startup does fix the issue
- A replug or reconnect when the issue has occurred does not fix it.

**Comment by IsmaelMartinez** [comment]
I think any work in here will require a lot of crazy engineering to solve this issue. I will recommend just to stick with the delay. Maybe 20 seconds is too much and 10 can do... hope helps!

**Comment by jijojosephk** [comment]
@0verEngineer good with work around? shall we close this one?

**Comment by 0verEngineer** [comment]
Yes

**Comment by jijojosephk** [comment]
Closing as work around solution provided.
