### ISSUE TITLE
Commit Style and Merges

### ISSUE THREAD

**Issue by Thaodan** [IsmaelMartinez/teams-for-linux#842]
Not directly a bug but: the current style of commit messages is hard to read, especially with the Github WebUi as if you call a commit #<bugnumber> you can only can click on the issue but not the commit itself.
The next issue with this is that the message isn't that descriptive, yes the issue explains the original intent somewhat but issues aren't always resolved in one big commit and a commit message should be more detailed.

The second issue I have is that almost every PR gets a merge commit even when the PR just had one commit. Creating merge commits when they aren't needed makes the history harder to follow and requires to rebase the branch that the PR is inside to have a clean history when a branch is behind master/the HEAD of the target branch.

**Comment by IsmaelMartinez** [comment]
Hi @Thaodan ,

While I agree that descriptive commit messages are part of a good code/repository higine, and can be really helpful for other contributors, we rarely have many contributions, so it's never been a big problem.

Adding processes and/or enforcing things rarely work.

I will suggest you lead this area and suggest a formatting and tools, and help in that area that way.

Ideally adding commitizen (or similar) so we enforced it. I am happy to help and do have a fair amount of experience, but I would love to hear what suggestions you can bring on this.

Thanks again!

**Comment by IsmaelMartinez** [comment]
closing due inactivity
