### ISSUE TITLE
No sound of the shared window

### ISSUE THREAD

**Issue by yolobnb** [IsmaelMartinez/teams-for-linux#847]
**Describe the bug**
I can share the screen using the application, but the sound of the shared windows doesn't go through. The official version of the Teams app for Windows had a toggle for whether to transmit the screen sound.

For example, if I play a youtube video in a browser window and share that window, the participant can see the video but the audio of the video is not shared. This is also the case for sharing the whole screen. Am I missing something here? Are there some settings that need to be tweaked for this to work?

**To Reproduce**
1. Go to the application/software
2. Click on 'Start a meeting.'
3. Share a window or the whole screen with audio playback.
4. The meeting can be recorded to see the error, or the meeting participant can be asked if they can hear the audio.

**Expected behavior**
Typically, the audio should also be shared when sharing the screen. An ideal option is to include the toggle, like the official client, whether or not to transfer the screen audio.

**Desktop (please complete the following information):**
 - OS: Linux (Arch with KDE)
 - Installation package: AUR
 - Version: 1.1.1-1

**Comment by IsmaelMartinez** [comment]
Hi @yolobnb ,

Thanks for reporting. Can you check if this is the same issue in the browser (chrome or similar will do) and with another packaging system?

Aur gets maintained somewhere else, but it might just be a browser / ms thing.

Thanks!!

**Comment by jijojosephk** [comment]
@yolobnb It might be a known problem, looks difficult to fix.

**Comment by jijojosephk** [comment]
Sorry @yolobnb seems it's impossible. 

https://github.com/electron/electron/issues/10515

**Comment by jijojosephk** [comment]
@yolobnb I don't think so. We depend on `electron` and it depends on `chromium`, if these projects can't fix we're helpless. Sorry :cry:

**Comment by yolobnb** [comment]
If that becomes possible, it would be an awesome addition and a fix for the issue.
