### ISSUE TITLE
Endless re-login loop after the app is up for a certain time

### ISSUE THREAD

**Issue by aed2fe** [IsmaelMartinez/teams-for-linux#850]
**Describe the bug**
Once the App is running for a certain time a popup window appears and ask for a re-login. Re-login will fail and immediately the same popup window appears. This is running in an endless loop. It can only be solved by clearing the storage of teams-for-linux. Than you'll get prompted to enter your full credentials once again.

Additional hint: I'm using teams-for-linx in a company network with full office365 and SSO.

**To Reproduce**
1. Start teams-for-linux
2. sign in with company account (SSO)
3. keep the application open for more than a day

**Expected behavior**
re-login run through successfully

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation package deb
 - Version 1.1.1

**Comment by jijojosephk** [comment]
@aed2fe it's a known limitation. The behaviour varies based on the security setup by the individual organisations. I'm not sure we can help much.

This might help you: https://github.com/IsmaelMartinez/teams-for-linux/issues/740#issuecomment-1534115693
