### ISSUE TITLE
Calls opened via Prospect are opened in the Chrome

### ISSUE THREAD

**Issue by seba7667** [IsmaelMartinez/teams-for-linux#851]
When I am trying to join the call via the Prospect mail I am redirected to Chrome. The link is starting with https://teams.m$.com/....
I installed the newest teams for linux version available in the snap store.
I am using Ubuntu 22.04

**Comment by jijojosephk** [comment]
@seba7667 we may not be able to handle this issue. Could you post in https://github.com/julian-alarcon/prospect-mail/issues

**Comment by IsmaelMartinez** [comment]
@julian-alarcon did do a lot of work in here, so he might be able to find out why this is not working and maybe help with this integration.

**Comment by jijojosephk** [comment]
Closing this as we won't be able to fix this one.
