### ISSUE TITLE
File save dialog is opened behind the main window

### ISSUE THREAD

**Issue by xhpohanka** [IsmaelMartinez/teams-for-linux#852]
When I want to download and save a file through teams the dialog is always opened behind the main window. I have to move the window or select the dialog from taskbar.
This happens in Cinnamon desktop environment on Arch Linux.

**Comment by jijojosephk** [comment]
@xhpohanka This is a know problem with electron apps. The same issue present in vscode as well.

**Comment by jijojosephk** [comment]
Closing this as we can't much about this. Sorry @xhpohanka
