### ISSUE TITLE
libuuid is missing on openSUSE when imstalling rpm

### ISSUE THREAD

**Issue by KottV** [IsmaelMartinez/teams-for-linux#858]
**Describe the bug**
libuuid is missing on openSUSE

**To Reproduce**
1. Add teams-for-linux repo via zypper
2. Install teams-for-linux with `zypper in teams-for-linux`

**Expected behavior**
Package should be installed without errors.

**Screenshots**
```zypper in teams-for-linux
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'libuuid' needed by the to be installed teams-for-linux-1.1.6-1.x86_64
 Solution 1: do not install teams-for-linux-1.1.6-1.x86_64
 Solution 2: break teams-for-linux-1.1.6-1.x86_64 by ignoring some of its dependencies
```

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Installation package: rpm
 - Version: 1.1.6

**Additional context**
It's safe to install as libuuid is present in the `libuuid1` package.
So it has to be changed to `libuuid1` in requirements for openSUSE (or simply removed, as libuuid is mandatory for the system)

**Comment by jijojosephk** [comment]
@KottV `openSUSE` build is maintained by @Thaodan.

**Comment by KottV** [comment]
Yeah, I saw his OBS repo. If that problem is not relevant for others systems - I can close it.

**Comment by jijojosephk** [comment]
@KottV let us know how did you install.

Grabbed rpm from releases? https://github.com/IsmaelMartinez/teams-for-linux/releases
or this
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/037a449a-64ce-4d36-970a-65e5f4abcb80)

**Comment by jijojosephk** [comment]
@thaodan Could you help?

**Comment by Thaodan** [comment]
> Yeah, I saw his OBS repo. If that problem is not relevant for others systems - I can close it.

Where did you install the rpm from? My build doesn't depend on anything but `nodejs-electron` and `/bin/sh`.

**Comment by KottV** [comment]
For this issue I install from this repo: https://dl.cloudsmith.io/public/teams-for-linux/packages/rpm/any-distro/any-version/$basearch

@Thaodan package form your repo doesn't has such problem. It works fine.

**Comment by jijojosephk** [comment]
@KottV I don't have much knowledge why it isn't working from the cloudsmith repo. Good to know that it's working with @Thaodan's repo. I would close this.

**Comment by Thaodan** [comment]
It doesn't work because you build with a Fedora/Red Hat builder when
building the electron that is bundled inside the package.

Can I see the spec file that is used here?

**Comment by KottV** [comment]
@Thaodan I looked for the spec too a haven't find. I think it's made with https://www.npmjs.com/package/rpm-builder
