### ISSUE TITLE
Popout window for chats

### ISSUE THREAD

**Issue by donjan** [IsmaelMartinez/teams-for-linux#859]
**Problem statement**
When participating in a presentation, reading and answering to chat messages from other channels requires minimising the presentation, writing in the other chat, then maximising the presentation again. This single-window approach is tedious when there is a continuous message flow.

**Desired solution**
The old, official client allowed to double click a chat and have it pop out as a separate window. Replicating this behaviour would streamline multi-channel communication.

**Alternatives**
Being able to launch multiple teams-for-linux windows (not necessarily instances) would also solve this problem.
`/opt/teams-for-linux/teams-for-linux --help` doesn't indicate this capability, and running it just raises the existing window.
Right-click & "New Window" in gnome-shell also just raises the existing window.

**Additional context**
I hope I'm missing some obvious way to get separate/popout windows.

**Comment by jijojosephk** [comment]
Sorry @donjan this is requirement almost impossible as this is a wrapper around `https://teams.microsoft.com`. You'd not see the popout feature on web version and similarly here too.

**Comment by jijojosephk** [comment]
I'm closing this if Microsoft implements the same in PWA, we can have a re-look. Thanks for posting your query.

**Comment by donjan** [comment]
Too bad. Thanks for your reply.

Just for the sake of completeness: is there a way of elegantly running two separate processes/instances of teams-for-linux? Double the RAM usage could be a worthwhile tradeoff.
I'm tempted to just duplicate the `/opt` directory to have `teams-for-linux2`, but I worry about the sockets, user config etc.

**Comment by zeitounator** [comment]
@jijojosephk Just for the record: the official teams client for linux (which is also electron based) allows to open chats in separate windows. So it seems doable although I have no idea of how exactly and how hard it is.

**Comment by IsmaelMartinez** [comment]
For info, the now deprecated official client was a full client calling the
APIs etc. Meaning they had more "power" to deviate from the browser
version. This client is mostly a wrapper of the browser client. We could
implement something but will require quite a lot of work/effort.

**Comment by donjan** [comment]
Just to report a workaround: I've currently installed it from the apt repo and the flatpak repo, which allows running two distinct Teams instances that don't interfere.\
The resource usage is not ideal, but this enables a better workflow.

**Comment by c0d3z3r0** [comment]
I wonder if it would be possible to provide the possibility for opening another teams-for-linux window?

**Comment by IsmaelMartinez** [comment]
We had a look at it but that will require a re-work of the whole application. Not easier to solve tbh.
