### ISSUE TITLE
on version 1.1.2 I don't see a way to set what's presented as full screen

### ISSUE THREAD

**Issue by je-vv** [IsmaelMartinez/teams-for-linux#860]
On Teams it's important to be able to go into full screen mode, since the rendering makes it hard to look at what's presented.  Official no longer provided Teams (by MS) had that option, but at least on 1.1.2 version of teams-for-linux I don't see it, :(

I hope it can be added, or brought back if it was removed.

**Comment by jijojosephk** [comment]
@je-vv please use the template if you're raising a defect. Otherwise kindly open a discussion. I'm not sure what feature, `teams-for-linux` never had the full screen option. I mean `https://teams.microsoft.com` website has that feature, you must see it here too. Nothing is removed. Could you explain your problem in detail?

**Comment by je-vv** [comment]
![2023_06_16__15_26_13](https://github.com/IsmaelMartinez/teams-for-linux/assets/10799432/b90b9e24-0338-43db-b535-15474d87d132)

See how teams offer "enter full screen", but teams-for-linux doesn't, :(  At least not 1.1.2.  It depends on the presenter that I really require it or not, and I can't remember if prior team-for-linux versions did offer it.  That's why I originally created the issue as feature request, and not as a defect.  There are people presenting from monitors with such high resolution, and worst so high DPI, that what gets rendered by teams is pretty small, and the only work around, and not good enough btw, I've found, is to go full screen.

**Comment by jijojosephk** [comment]
This used to be there. MS did something I suppose.

**Comment by jijojosephk** [comment]
Seems like we can't do much about it now. Sorry, only MS did something.
