### ISSUE TITLE
Option to not show tray icon

### ISSUE THREAD

**Issue by flying-sheep** [IsmaelMartinez/teams-for-linux#861]
**Is your feature request related to a problem? Please describe.**
I have too many symbols in my tray, and the tray icon fullfills no purpose that a menu bar or so can’t fullfill.

**Describe the solution you'd like**
A Settings dialog as requested in https://github.com/IsmaelMartinez/teams-for-linux/issues/462 should be available with and without the tray icon, and have an option to hide the tray icon.

**Describe alternatives you've considered**
None, I can’t hide the tray icon using my system.

**Additional context**
Since https://github.com/IsmaelMartinez/teams-for-linux/issues/844 was interpreted as “Close app with ×”, and converted into a discussion, this issue is not a duplicate of it.

**Comment by IsmaelMartinez** [comment]
Added a `trayIconEnabled` config option feature into release [1.5.0](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.5.0). Defaults to true but if you use `false` it should disable the tray icon. Closing as completed

**Comment by flying-sheep** [comment]
awesome, thanks!
