### ISSUE TITLE
Blur background option is suddenly missing

### ISSUE THREAD

**Issue by martintvarog** [IsmaelMartinez/teams-for-linux#862]
**Describe the bug**
Blur your background option is suddenly missing.

**To Reproduce**
1. Go to meeting 
2. Click on join

**Expected behavior**
Blur you background option should be visible and possible to choose in a meeting

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/63610399/9f310edf-2c82-4e2e-a0e2-c807c34474f8)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation package -> snap
 - Version 1.1.1

**Additional context**

**Comment by saskra** [comment]
Same here with Ubuntu 22.04.2 LTS.

**Comment by netkat** [comment]
Yep same here. However, it's missing directly from the browser (Edge - running Linux Mint) too.

**Comment by jijojosephk** [comment]
The background effects gone! :laughing: I think they're killing slowly.

**Comment by jijojosephk** [comment]
Sorry, this can't be fixed I believe! MS deliberately removed it.

**Comment by jijojosephk** [comment]
You can't see the feature web app. Hence, sadly I'll have to close this.

**Comment by saskra** [comment]
It's back, what is MS up to again.... :-D

**Comment by martintvarog** [comment]
The've must have heard our prayers
