### ISSUE TITLE
Newly-connected BT audio devices are not noticed

### ISSUE THREAD

**Issue by karlkleinpaste** [IsmaelMartinez/teams-for-linux#864]
**Describe the bug**
TfL does not notice new bluetooth devices, so they do not become available selections. That is, if I start TfL when my BT headset is off, then TfL knows only the built-in audio devices. When I later turn on and connect my headset, TfL takes no notice of this so that I cannot choose a new configuration using the headset.

**To Reproduce**
1. Start TfL without a BT device active.
2. Note configuration available in Calls audio device selection shows only built-in devices (as expected).
3. Connect BT headset.
4. No new configuration becomes available.

**Expected behavior**
I would like TfL to take note of available devices whenever the audio device selector becomes visible. A simple re-scan of available devices would be in order.

**Screenshots**
This is how things look, after restarting TfL due to having connected headset. Without restart, the "custom setup" element is not  available.
![screenshot1](https://github.com/IsmaelMartinez/teams-for-linux/assets/7548920/edcafbc7-b898-4110-ab48-816fa162815b)

**Desktop (please complete the following information):**
 - Fedora 37.
 - teams-for-linux-1.1.6.x86_64.rpm

I've filed this as a bug because I think it's something that should always have been available, but if you want to re-class it as a feature request, that would be fine.

**Comment by jijojosephk** [comment]
The challenge is that neither `electron` nor `node` has an event publish/subscribe mechanism to let the app know that new Bluetooth devices are added/removed. All we can do is poll the device list at certain intervals, but I think that's going to use OS resources less effectively. You can test it this way:

Pre-condition: `teams-for-linux` is running and no Bluetooth devices are connected.

Steps to follow:

1. Go to calendar view.
2. Click on `Meet Now`.
3. Click `Start Meeting`.
4. Connect your Bluetooth device. (You can do it before step 1 as well)
5. Click on the settings icon under `Customised Setup` 
7. Click on `Speaker` drop down. You would not see the device connected.
8. Now open developer tools by clicking tray icon menu `Debug`
9. Go to `Console` tab and execute the code below:

```js
var controller = window.angular.element(document.documentElement).controller();
controller.callingService._deviceManagerService.getApplicationDevices();

```
Now the `Speaker` drop down must be refreshed and you must see the newly connected device.

Let us know the result.

**Comment by karlkleinpaste** [comment]
![screenshot1](https://github.com/IsmaelMartinez/teams-for-linux/assets/7548920/733f344a-51f7-4616-afa9-4439962d0115)

The MDR device is my Sony BT headset, turned on/connected while TfL was showing the speaker dropdown.

In any event, I wasn't suggesting an asynchronous, dynamic, or event-driven announcement/discovery; rather, I was suggesting rescan as a step immediately prior to displaying an audio device selector. TfL doesn't need to learn about devices literally as they come and go, but could (re-)learn about what's then available, as the user is about to make a decision about them.

**Comment by jijojosephk** [comment]
Not sure how to catch that click event.

**Comment by jijojosephk** [comment]
This is the button:
```html
<button type="button" id="prejoin-devicesettings-button" data-tid="toggle-devicesettings-computeraudio" class="fui-Button rsawnvh ___91x5cg0 f1c21dwh f1p3nwhy f11589ue f1q5o8ev f1pdflbu fkfq4zb fjxutwb f1s2uweq fr80ssc f1ukrpxl fecsdlb f139oj5f fwiml72 f1h0usnq fs4ktlq f16h9ulv fx2bmrt f1fg1p5m f1sbtcvk fwiuce9 fdghr9 f15vdbe4 fwbmr0d f44c6la" aria-label="Open device settings" aria-labelledby="computer-audio-content-aria-description-id prejoin-devicesettings-button" data-track-action-gesture="click" data-track-action-outcome="closeDialog" data-track-action-scenario-type="devicesPanel" data-track-action-scenario="closeDevicesPanel" data-track-module-name="toggleDevices" data-track-databag-id="5a33b7ee-c9f9-43ea-b64e-520942df97dc" data-track-context-work-loads="callType" aria-describedby="tooltip-11">
    <span class="fui-Button__icon rywnvv2">
        <svg class="fui-Icon-filled ___1vjqft9 fjseox fez10in fg4l7m0" fill="currentColor" aria-hidden="true" width="1em" height="1em" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path d="M17.25 5h-2.36a2.5 2.5 0 0 0-4.78 0H2.75a.75.75 0 0 0 0 1.5h7.36a2.5 2.5 0 0 0 4.78 0h2.36a.75.75 0 0 0 0-1.5Zm-14.5 8.5a.75.75 0 0 0 0 1.5h2.36a2.5 2.5 0 0 0 4.78 0h7.36a.75.75 0 0 0 0-1.5H9.89a2.5 2.5 0 0 0-4.78 0H2.75Z" fill="currentColor"></path>
        </svg>
        <svg class="fui-Icon-regular ___12fm75w f1w7gpdv fez10in fg4l7m0" fill="currentColor" aria-hidden="true" width="1em" height="1em" viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg">
            <path d="M14.95 5a2.5 2.5 0 0 0-4.9 0H2.5a.5.5 0 0 0 0 1h7.55a2.5 2.5 0 0 0 4.9 0h2.55a.5.5 0 0 0 0-1h-2.55ZM12.5 7a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm-2.55 7a2.5 2.5 0 0 0-4.9 0H2.5a.5.5 0 0 0 0 1h2.55a2.5 2.5 0 0 0 4.9 0h7.55a.5.5 0 0 0 0-1H9.95ZM7.5 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Z" fill="currentColor"></path>
        </svg>
    </span>
</button>
```

**Comment by jijojosephk** [comment]
```js
navigator.mediaDevices.ondevicechange
```
is not working as expected.

**Comment by jijojosephk** [comment]
This seems extremely difficult.

**Comment by jijojosephk** [comment]
I'm might now work this. Someone who's free, please have a try.

**Comment by karlkleinpaste** [comment]
Can you say what makes it hard? Conceptually, to me, TfL must do a scan at startup for the set of available audio & video devices, and it seemed (in my ignorance, perhaps) that re-running that scan to re-populate the set any time a device selector was about to appear would be straightforward. No?

**Comment by jijojosephk** [comment]
> Can you say what makes it hard? Conceptually, to me, TfL must do a scan at startup for the set of available audio & video devices, and it seemed (in my ignorance, perhaps) that re-running that scan to re-populate the set any time a device selector was about to appear would be straightforward. No?

How the device settings panel is loaded is still not known. We can have a script running to check when the HTML element becomes visible but that is less efficient. All we need is the method written by Microsoft which shows this panel. Then we can override the same and add our custom code. But that seems extremely difficult to identify.

**Comment by IsmaelMartinez** [comment]
Closing this issue to clean the open issues. This is because there hasn't been activity for a few months now. If you still face this issue in versions 1.4.1 and above, please share it and we can re-open it. Thanks in advance!

**Comment by jijojosephk** [comment]
It's a known problem. Though it works sometimes, not consistent. There is no known solution so far. Some part of it is dependent on Microsoft's code. How often does it check for hardware changes. IDK.
