### ISSUE TITLE
Don't use alt to show the menu

### ISSUE THREAD

**Issue by Kommynct** [IsmaelMartinez/teams-for-linux#866]
Currently if you push the alt key, it pops up the menu, I understand this is standard across electron, but this is a major usability issue on tiling WM's, for example, I use alt+# to switch between workspaces, if switch to a workspace with this app, it'll popup the menu, I find this to be so exceedingly annoying that I have been using the default app, but that no longer works for me, gtk apps often use alt+m to pull down the menu for that reason.

In this case, the menu isn't even useful, alt+m makes way more sense here, I think.

**Comment by jijojosephk** [comment]
But this happens only after releasing ALT key right?

**Comment by Kommynct** [comment]
It happens even if you've pushed alt and a number, so, that doesn't really matter. It's still extremely annoying. It'd be better if it didn't happen with alt+anything, significantly so, if it only happened with alt by itself it'd be much much better, but it currently does not, so, that isn't much help.

**Comment by jijojosephk** [comment]
I don't think we can change the key for the menu. We can probably have a flag to remove the menu bar itself.

**Comment by Kommynct** [comment]
I would be fine with an option to make it permanently visible too.

**Comment by Kommynct** [comment]
Thank you!

**Comment by jijojosephk** [comment]
Will be released in `1.1.7`. Build on the way!

**Comment by jijojosephk** [comment]
Please specify which package you're using. flatpak, deb, rpm, snap.

**Comment by jijojosephk** [comment]
Aur is manged by @frealgagu, I'm not sure you can build your own. Or may be you have another method. Sorry, I don't know how it works for Arch.

**Comment by jijojosephk** [comment]
Closing as it's implemented in `1.1.7`.

**Comment by jijojosephk** [comment]
I think it broke the tray icon.

**Comment by jijojosephk** [comment]
`teams-for-linux --menubar hidden` broke the tray icon. Fixed in `1.1.8`

**Comment by Alexander-Shevchenko** [comment]
Dear @jijojosephk , thanks for implementing this!
Can this option be set through some config file (to take effect on automatic start of Teams with the system)?

**Comment by jijojosephk** [comment]
@Alexander-Shevchenko yes, you can use `config.json`. You may read about it here: https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md

You need to create the `config.json` at the right path and have an entry like this

```js
{
    "menubar": "<value>"
}
```

Hope it helps!
