### ISSUE TITLE
Unfork or continue as it is?

### ISSUE THREAD

**Issue by IsmaelMartinez** [IsmaelMartinez/teams-for-linux#87]
Hi,

Time has arrive to decide if to unfork or continue as we are.

Please tell me what you thing.
👍 for unfork
👎  for keep as we are.

The main reason for the unfork are:
* almost a year since last message from ivelkov. James repo is also archived now.
* this repo has now not much in common with ivelkov one nor with James one.
* there are a few features in github that are only available for main projects (no forks)

And reasons to keep as we are:
* there are a lot of links in Internet pointing to ivelkov and then, indirectly to our repo.
* Once MS does the Linux client, this repo will become obsolete. So what is the point of the extra “work”.
* unexpected consequences... in principle, by using the same name, there should not be issues with regards links to the repo, etc, but experience tell me  expect issues in any change.

In any case, I will keep the history section on this repo, but probably move it to a separate HISTORY.md file (just to keep things tidy.)

**Comment by docsmooth** [comment]
Regarding MS doing the work on the Linux client - I've been keeping that teams' PM up-to-date with the work on *this* fork of the teams-for-linux product, and can continue that line of communication, so that they are "in the loop", or even just keep pointing customers here.  So i think that point is less important in this decision than you stated above.

**Comment by IsmaelMartinez** [comment]
@docsmooth thanks a lot. It will be great to let the PM know we are happy to help/get help. The main goal here is for people to be able to get the best experience possible using teams, no matter what OS they are using.

**Comment by IsmaelMartinez** [comment]
Ok, I think 15 people saying yes and 0 people saying no means yes wins... 

Unforking request has been submitted to github so that we keep history etc. 

I will close this as soon as it is done. Thanks to all of you that did read/comment and/or :+1:

**Comment by IsmaelMartinez** [comment]
Ok, that is now down. When I got time I will create a couple of tasks, mainly for me, to add the Contibutors file and others. cheers!
