### ISSUE TITLE
Add "custom browser for hyperlinks" option/arguement

### ISSUE THREAD

**Issue by vvyushmanov** [IsmaelMartinez/teams-for-linux#871]
**Is your feature request related to a problem? Please describe.**
I use my laptop both for personal and work needs. My personal browser is Firefox (set as default browser in the system), and my work browser is Chrome. Every time I need to open a link from the work chat, I have to copy-paste it manually to chrome.

**Describe the solution you'd like**
I would like to have an option to override the default browser, so that links clicked in teams open in the browser I set.

**Comment by jijojosephk** [comment]
Looks like there is no in-built API to do this. There's a `shell` module that only works with default apps.

**Comment by jijojosephk** [comment]
`1.2.3` has this feature added. Please checkout. In case of doubt, you can quickly reach us in this chat room: https://matrix.to/#/#teams-for-linux_community:gitter.im
