### ISSUE TITLE
Double listing as background app in Gnome 44.2

### ISSUE THREAD

**Issue by qdrop17** [IsmaelMartinez/teams-for-linux#872]
The app is listed twice as a Gnome Background App in the respective menu. See screenshot. Force-Closing does not work reliable. I didn't manage to reproduce a clear pattern except closing both entries closes the app for sure.

**Expected behavior**
I expect that Teams for Linux is listed just once.

**Screencast**
[Screencast from 2023-06-28 16-56-10.webm](https://github.com/IsmaelMartinez/teams-for-linux/assets/42340241/7bed0ade-b1e2-48f8-98b3-5d00c5f04f6a)

**Desktop**
 - OS: Fedora 38 (up to date)
 - Installation package: Flathub
 - Version: 1.1.6

**Comment by jijojosephk** [comment]
Do you see any other electron based apps behaving in similar way under GNOME desktop?

**Comment by qdrop17** [comment]
> Do you see any other electron based apps behaving in similar way under GNOME desktop?

Yes, WebCord for instance behaves the same. Where should I open this bug then?

**Comment by jijojosephk** [comment]
> > Do you see any other electron based apps behaving in similar way under GNOME desktop?
> 
> Yes, WebCord for instance behaves the same. Where should I open this bug then?

GNOME. But probably they won't consider it as a defect :smile: 

I suspect the reason behind this behaviour is multiple processes with the same name `teams-for-linux`. All electron apps will have multiples like this.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/9ca78868-9a09-44a9-b634-225276512287)


May be this: https://www.electronjs.org/docs/latest/tutorial/process-model
