### ISSUE TITLE
aarch64 rpm package fails to install

### ISSUE THREAD

**Issue by as400l** [IsmaelMartinez/teams-for-linux#873]
aarch64 fails to install because of wrong architecture. It is set in rpm to arm64 while it should be aarch64.

It would be also nice of you publish spec file for rpm or src.rpm package.

**Comment by jijojosephk** [comment]
Let us know how did you try to install the package?

**Comment by Thaodan** [comment]
> It would be also nice of you publish spec file for rpm or src.rpm package.

The spec file is generated by electron-builder.

**Comment by as400l** [comment]
> Let us know how did you try to install the package?

I did "rpm -i teams-for-linux-1.1.8.aarch64.rpm". Effect:

`package teams-for-linux-1.1.8-1.arm64 is intended for a different architecture`

This is probably a bug in electron-builder.
I built it with latest version and now rpm is ok and it has aarch64 instead of arm64.

**Comment by jijojosephk** [comment]
Thanks. Could you confirm the version you used to build?

**Comment by as400l** [comment]
Soo, I digged around more and it might be fpm problem.
I am using gem installed fpm-1.15.1 ('gem install fpm') and then ('export USE_SYSTEM_FPM=true') before running yarn.

Don't know whether my versions are relevant since I am building natively on aarch64 machine. BUT:

electron-builder  version=23.3.3

**Comment by jijojosephk** [comment]
Thanks, to me this is more or less resolved. But is it a pure electron builder issue? Then we can close it and open an issue there.

**Comment by jijojosephk** [comment]
Could you check the latest pre-release `1.2.0` and confirm? If still there, would report as a defect in electron-builder repo?

**Comment by as400l** [comment]
I just installed prerelease without any problems.

**Comment by jijojosephk** [comment]
So, guess the problem was with `electron-builder`
