### ISSUE TITLE
The app no longer works through proxy

### ISSUE THREAD

**Issue by Lancer11211** [IsmaelMartinez/teams-for-linux#874]
**Describe the bug**
Previously, having the proxy config in config.json helped but from today, it no longer works. I've updated from 1.0.46 to 1.1.8 but it didn't help. Then I reinstalled again, cleared all cache/config and the login screen is just a white page loading forever.

**To Reproduce**
1. Open the app from behind proxy with the right proxy config.

**Expected behavior**
The login screen should work.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package: deb
 - Version 0.1.18

**Comment by Lancer11211** [comment]
Update: it seems like ms teams just stopped working on linux in general. Their official app barely works and the browser versions either can't load the chat or any meeting. Now it feels unlikely to be an issue with this app, I'll get back later.

**Comment by jijojosephk** [comment]
I would like to study the problem. Never tried the proxy setup. Could you explain? I may try to understand and provide a solution if possible. There had been issues with teams due to an outage. The entire world suffered :laughing: Kindly have a look at #870

We can continue discussion of the proxy thing.

**Comment by Lancer11211** [comment]
@jijojosephk at `~/.config/teams-for-linux/config.json` I've this:

```
{
    "proxyServer": "$IP:$PORT"
}
```

Nothing needed for teams to work.

**Comment by jijojosephk** [comment]
Can you try the latest `pre-release` version? https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.2.0
We've just upgraded electron version from `21.0.1` to `25.2.0`

**Comment by Lancer11211** [comment]
Forgot to mention that it works fine now, sorry. I think it was a server issue.

**Comment by jijojosephk** [comment]
Thanks. I'll close it to then.
