### ISSUE TITLE
Camera does not work unless restarting teams

### ISSUE THREAD

**Issue by 0verEngineer** [IsmaelMartinez/teams-for-linux#883]
**Describe the bug**
In the last few days i experienced the problem that the camera stays black when joining a meeting with camera, the indicator light on the camera itself does also not turn on. If i restart teams and try to join again it works.

I do not really know the exact reproduce steps for now. If i try to join a meeting with camera after the first one where i had to restart it works, so it does not happen every time.

**To Reproduce**
1. Join Meeting
2. coming soon...

**Expected behavior**
Camera should work

**Desktop (please complete the following information):**
 - OS: Linux Kubuntu 23.04 with Plasma 5.27.4
 - Installation package: Flatpak
 - Version 1.1.8

**Additional context**
- X11

**Comment by jijojosephk** [comment]
Are you saying you're not able to find a pattern?

**Comment by jijojosephk** [comment]
To confirm if it's related to flatpak, can you use any other package and see if you can reproduce though random.

**Comment by jijojosephk** [comment]
Can you join this room: https://matrix.to/#/#teams-for-linux_community:gitter.im

**Comment by IsmaelMartinez** [comment]
I have seen this same issue in the official MacOS app. Also only been able
to see 1 person from the all meetings. I think is a blip from MS.

**Comment by jijojosephk** [comment]
@0verEngineer are you facing this issue still?

**Comment by 0verEngineer** [comment]
@jijojosephk Hey, no it did not happen anymore. I will report and test around if it happens again.

**Comment by jijojosephk** [comment]
Thanks! I'll close this for now. By the way are you on the latest version `1.2.5` ? Do you see tray icon?

**Comment by 0verEngineer** [comment]
I am not on the latest atm. i will update later and report if i cannot see it.
