### ISSUE TITLE
Support opening meeting links via xdg-open

### ISSUE THREAD

**Issue by benjamincburns** [IsmaelMartinez/teams-for-linux#89]
Visiting a teams meeting link in my browser doesn't automatically open it in `teams-for-linux`. Issue #47 provides a workaround to this, but it'd be much better if simply clicking the link worked.

`xdg-open` provides a mechanism for this, and I believe the "download the app or open in browser" page that you see when you first visit the link already attempts to open the official Teams app via a similar mechanism (though I could be mistaken). If this assumption is correct, it's simply a matter of `teams-for-linux` registering itself via `xdg-mime` or `xdg-settings`.

**Comment by IsmaelMartinez** [comment]
I agree that this will be great. 

I am happy to help. I got a pretty busy month ahead so can't take ownership of the improvement.

Do you think you can do a bit of investigation? Electron probably provides and interface for this. 

Thanks!

**Comment by benjamincburns** [comment]
I'm in similar shape right now but I might have some time this weekend. If I do, I'll report back here before taking it on. If anybody else wants to pick this up in the interim, please feel free!

**Comment by IsmaelMartinez** [comment]
Hi @benjamincburns , did you manage to have a look at this? any info shared might be usable for other to implement it (if you don't have the time). Thanks

**Comment by IsmaelMartinez** [comment]
Maybe related info https://github.com/electron/electron/issues/6440

**Comment by IsmaelMartinez** [comment]
https://electronjs.org/docs/api/app#appsetasdefaultprotocolclientprotocol-path-args

**Comment by IsmaelMartinez** [comment]
if that documentation is right, then the branch feature/set-default-prot-provider should do the job. I will check the built version to see if that is true or need to work on the electron-builder part.

**Comment by IsmaelMartinez** [comment]
This should be available in version 0.4.0. If you want to try it, use the snap package in edge. Be aware of is edge.

**Comment by leandro-lucarella-sociomantic** [comment]
Trying it now:
```
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
```

**Comment by leandro-lucarella-sociomantic** [comment]
The getting stuck seems unrelated, I rolled back to 0.3.0 and it still gets stuck... :(

**Comment by lgladysz** [comment]
Can't login on edge 0.4.0:
![image](https://user-images.githubusercontent.com/959998/61119615-859c2600-a49b-11e9-8e33-fb4865cbfeec.png)

**Comment by leandro-lucarella-sociomantic** [comment]
I clicked on **signing out** and signed in again, that fixed the issue, then upgraded again to 0.4.0 and I it worked too. The error about `"default-url-scheme-handler": not allowed` remains though.

**Comment by IsmaelMartinez** [comment]
@leandro-lucarella-sociomantic and @lgladysz , can you either create or comment in  the appropriate bug? This is xdg-open that might be or not related to your issues.

`"default-url-scheme-handler": not allowed` smells like snap permission, but again, open the other issue. @lgladysz , remember to clean your cache and see if that does it. Again, create a proper bug or things get mess up. Thanks

**Comment by julian-alarcon** [comment]
Error in snapd reported and being managed here:
https://forum.snapcraft.io/t/dbus-error/4969
https://github.com/snapcore/snapd/pull/7129

But still I have no issues with the app.

**Comment by maymage** [comment]
@IsmaelMartinez 

This works now from the snap installation, but not for the flatpak one.
