### ISSUE TITLE
Token/auth requests get sent to external browser

### ISSUE THREAD

**Issue by nneul** [IsmaelMartinez/teams-for-linux#890]
Intermittent requests to elements within teams (files, tasks, etc.) trigger some additional authentication (likely getting a service specific token). SOMETIMES this seems to happen transparently, but others it winds up opening in external browser, which presents this error.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/828492/d9d9157c-6fbe-47a7-b177-61cc435195ef)

It's impossible to get past this since it's missing the content of the request. Additionally, depending on what you try to then do in the teams window, it will rapid fire create new/additional tabs with the same request. 

This usually appears after teams app has been open for a while. (Next day?)

It seems like there is maybe some additional logic needed for 'when to open internally' vs 'when to open in external browser'.

The particular target URL in my case:

https://login.microsoftonline.com/e3fefdbe-f7e9-401b-a51a-355e01b05a89/oauth2/v2.0/token

https://login.microsoftonline.com/<tenant>/oauth2/v2.0/token

**Desktop (please complete the following information):**
 - OS: Ubuntu 20 x64
 - Installation package: deb from repo
 - Version: 1.1.11

**Comment by nneul** [comment]
Example of a dialog that triggers it:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/828492/abf3f6e6-b57d-48da-bf37-7b5059f29bb4)

**Comment by IsmaelMartinez** [comment]
are you still experiencing this issue?

**Comment by ChristoSnake** [comment]
I have not seen this in a while...

My company enforces re-authentication every two weeks, I will keep update here if it happens again.

**Comment by nneul** [comment]
I  regularly still see this. Org doesn't have any 'frequent relogin' requirement (might be /30). Very often triggered if I go to any files tab or similar, but it doesn't do it every time - usually if I've been logged in for 24h or more.

**Comment by nneul** [comment]
Note that I almost daily see the 'Interaction required' dialog, but I think that's a separate issue. 

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/828492/264eed6a-83f1-47fe-b8b6-31a5f560c8e0)

**Comment by vpess** [comment]
I solved this problem clearing Microsoft Teams cache. [Clear cache Microsoft Teams on Linux](https://gist.github.com/mrcomoraes/c83a2745ef8b73f9530f2ec0433772b7)

OS: Fedora Linux 38 (Workstation Edition)
Installation package: flatpak
Version: 1.2.9

**Comment by Stav88** [comment]
I had same problem on version 1.3.6. Upgrading on 1.3.13 fix it on my side.
Does upgrading clear cache ?

OS : Ubuntu 22.04
Installation package : snap

**Comment by rjeq** [comment]
Exact same dialog as  @nneul  here triggers it as well

**Comment by IsmaelMartinez** [comment]
Can you clean the cache and check if it still happens?

**Comment by nneul** [comment]
Unless you've added something within past few weeks - I definitely still see this, and I've done full resets and cache clean.

However, to clarify the symptom - I do NOT see this on "just the interaction required" - i.e. when the session sits. I only see it when accessing secondary pages/tabs within Teams. If it is just a regular "need to log back in", I see that even on plain browser session. (I usually have one of those open as well just for better meeting isolation and being able to have a second window.)

What _usually_ triggers it for me is if the session is at all old, and I go to access something like the org tree for a person, or the files tab, or similar. The shared files one is particularly messy since it gets into a state where it's trying to "get additional permissions" and often winds up flooding my other active browser window with additional tabs -- and since those tabs are trying to open via a 'GET' since it's an external browser load, they don't work - they have to be a POST according to the target server.

That may be a possible avenue to explore --- do you have any means to say "Only open in external browser if the originating request is a GET/plain url, and force to open in internal browser if they are a POST or any other verb?"

**Comment by jijojosephk** [comment]
This could be related to #1045

**Comment by jijojosephk** [comment]
@nneul can you follow #1045. we'll discuss possible solution there. A lot of people commented there.

**Comment by desmi** [comment]
I have this same issue, for me, it gets triggered when I'm in a meeting and want to send something in the meeting chat. Have been experiencing this for a while and when it happens I get about 5 windows opened in my external browser (Firefox).

**Comment by jijojosephk** [comment]
Try in `1.4.13`
