### ISSUE TITLE
Provide SHA256 hashes for all downloadable assets

### ISSUE THREAD

**Issue by normoes** [IsmaelMartinez/teams-for-linux#893]
**Is your feature request related to a problem? Please describe.**
I like to validate a downloaded asset against its hash.
I am using a script that downloads the AppImage asset and automatically also (prior to version 1.2) downloads  the file `latest-linux.yml` which always contained the AppImage's SHA256 file hash.
This is not the case anymore. As of version 1.2, it seems,  `latest-linux.yml` contains various file hashes, e.g. for `deb` or for `rpm` but always only one - changing from release to release.

This situation leads to an invalid checksum check on my side as I am downloading the AppImage but trying to check its SHA256 hash aginst some other asset's hash..

**Describe the solution you'd like**
I am missing a file that contains all the file hashes.
* Maybe also a hash file per asset.

That would be great and would benefit security in general.
Also it would improve automaion like the script I am using.

**Describe alternatives you've considered**
Because the hash, users want to check against, needs to be provided by the creator of the asset I can only imagine ignoring the checksum check, which I would really like to avoid.

**Additional context**

**Comment by jijojosephk** [comment]
As I understand from the `electron-builder` command-line, we don't have any option to change the name of the `latest-linux.yml` to something else. We might be able to do something by making some changes to `.github/workflows/build.yml` and `package.json` not sure.

**Comment by jijojosephk** [comment]
Done what's possible with `electron-builder` in version `1.2.6`. Can you check?

**Comment by normoes** [comment]
Perfect, that's exactly what I was looking for.
That helps everyone, I think.

Thanks a lot - Very fast.
