### ISSUE TITLE
Sharing Windows / Apps not working

### ISSUE THREAD

**Issue by bss-markus-schulze** [IsmaelMartinez/teams-for-linux#896]
In 1.2.5 screen sharing is working again, despite the screen picker is not located in the picker area on the bottom of the t4l window, but a gnome window comes up to choose the screen.

Window or app sharing does not work.

I asume the place to pick the screen should have been in this new bottom area, but the Gnome windows still appears:
![Bildschirmfoto vom 2023-07-18 07-41-17](https://github.com/IsmaelMartinez/teams-for-linux/assets/78405591/97a78fdd-7cab-4be4-b886-ec3d20a2b891)

Clicking on Windows doesn't show any option to pick:
![Bildschirmfoto vom 2023-07-18 07-41-30](https://github.com/IsmaelMartinez/teams-for-linux/assets/78405591/4e2574db-c0a7-4458-ae92-00a137512dca)

I'm on Fedora 38 Gnome Wayland Pipewire, if that's relevant.

_Originally posted by @bss-markus-schulze in https://github.com/IsmaelMartinez/teams-for-linux/issues/886#issuecomment-1639523242_

**Comment by LeeRoyManea** [comment]
Same for me.  Also Fedora 38. Wayland.

**Comment by RomanSobota44** [comment]
Hi, I have meeting today in the morning with share screen, share screen works but not re-fresh. On Fedora 38, Wayland

**Comment by jijojosephk** [comment]
> Hi, I have meeting today in the morning with share screen, share screen works but not re-fresh. On Fedora 38, Wayland

What do you mean by no `re-fresh` ?

**Comment by RomanSobota44** [comment]
> > Hi, I have meeting today in the morning with share screen, share screen works but not re-fresh. On Fedora 38, Wayland
> 
> What do you mean by no `re-fresh` ?

Yes, I started session, other users saw my screen, but they dont saw any re-fresh of my screen, only mouse pointer moving

**Comment by AcidWindsurf** [comment]
Hello, in my case Teams for Linux crashes a couple of minutes after starting screen-sharing. No option to share app/window, only full screen. (Ubuntu 22.04.2 LTS, Wayland)

**Comment by r-cdriscoll** [comment]
In my testing with 1.2.6 on Ubuntu 22.04.2, amd64 deb, and Wayland I just get a black screen when attempting to share.

When launching from a terminal, the output complains about EGL things:

```
[4520:0718/113356.467351:ERROR:egl_dmabuf.cc(604)] Failed to get image from DMA buffer.
[4520:0718/113356.537199:ERROR:egl_dmabuf.cc(569)] Failed to record frame: Error creating EGLImage - EGL_NOT_INITIALIZED
[4520:0718/113356.537213:ERROR:shared_screencast_stream.cc(791)] Dropping DMA-BUF modifier: 72057594037927935 and trying to renegotiate stream parameters
[4520:0718/113356.537230:ERROR:egl_dmabuf.cc(569)] Failed to record frame: Error creating EGLImage - EGL_NOT_INITIALIZED
```

**Comment by jijojosephk** [comment]
Can you guys join this room: https://matrix.to/#/#teams-for-linux_community:gitter.im

I'm on `X11` within `wayland` many face different issues. To address the problems we can have quicker communications through chat.

**Comment by Geroldin** [comment]
Hi all,
i'm using Ubuntu 22.04.02 LTS  with GNOME Version 42.9 and Wayland. 
Can't screenshare anymore since T4L Version 1.2.4 (now using 1.2.7)
When I click the sharing button it starts normal but after a few seconds or after I click "stop sharing" the whole app crashes without further notice. 
Please let me know if I can provide any more details and how ;) 
Still new to Linux / Ubuntu and therefor not so knowledgeable how to provide them.

**Comment by Geroldin** [comment]
Made it with the help from @bss-markus-schulze  to create a debug log from the process. Looks to me like 

> [DEBUG] configPath:,/home/X@Y.net/.config/teams-for-linux
[INFO] No config file found, using default values
[DEBUG] configFile:,[object Object]
[INFO] Running under Wayland, switching to PipeWire...
[DEBUG] Fetching custom background configuration from 'http://localhost/config.json'
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--appLogLevels,error,warn,info,debug
[DEBUG] Spellchecker is disabled!
[ERROR] connect ECONNREFUSED 127.0.0.1:80
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[42102:0720/110946.966031:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[42102:0720/110947.117385:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[DEBUG] did-finish-load
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-finish-load
[DEBUG] Badge count set to '0'
[DEBUG] User status changed to '2'
[DEBUG] User status changed to '2'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] Power save is disabled using Electron API.
[DEBUG] User status changed to '5'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[OpenH264] this = 0x0x13a81c5d0990, Warning:ParamValidationExt(), eSpsPpsIdStrategy setting (2) with iUsageType (1) not supported! eSpsPpsIdStrategy adjusted to CONSTANT_ID
[OpenH264] this = 0x0x13a81c5d0990, Warning:ParamValidation(), AdaptiveQuant(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x13a81c5d0990, Warning:ParamValidation(), BackgroundDetection(1) is not supported yet for screen content, auto turned off
[42229:0720/111033.396116:ERROR:socket_tcp.cc(317)] Error when reading from TCP socket: -101
[42229:0720/111033.438812:ERROR:socket_tcp.cc(317)] Error when reading from TCP socket: -101
[DEBUG] User status changed to '13'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[42102:0720/111040.222443:ERROR:egl_dmabuf.cc(569)] Failed to record frame: Error creating EGLImage - EGL_NOT_INITIALIZED
[42102:0720/111040.224530:ERROR:shared_screencast_stream.cc(791)] Dropping DMA-BUF modifier: 72057594037927935 and trying to renegotiate stream parameters

Looks to me like some kind of EGL Issue. Not sure what that is tbh. Will try to google for it.

**Comment by jijojosephk** [comment]
Can you try `pre-release` `1.2.8` ?

**Comment by RomanSobota44** [comment]
I try version 1.2.8 and all works fine !!!

-----Original Message-----
From: Jijo Joseph ***@***.******@***.***%3e>>
Reply-To: IsmaelMartinez/teams-for-linux ***@***.******@***.***%3e>>
To: IsmaelMartinez/teams-for-linux ***@***.******@***.***%3e>>
Cc: RomanSobota44 ***@***.******@***.***%3e>>, Comment ***@***.******@***.***%3e>>
Subject: Re: [IsmaelMartinez/teams-for-linux] Sharing Windows / Apps not working (Issue #896)
Date: 20.7.2023 13:59:56


Can you try pre-release 1.2.8 ?

**Comment by jijojosephk** [comment]
Thanks everyone please test and report. The app currently shows a `js` confirmation dialog to choose between `windows` and `screens`. It's due to the current implementation of `getDisplayMedia`. We'll see what can be improved in the future.

**Comment by Geroldin** [comment]
Hi,
this seems to have fixed it. I now can share screen and dedicated windows again. However when testing with Markus he reported that he can hear me double/twice. We could identify that there are two inputs used. One from my laptop and one from my Headset. When i disabled the notebook input the double audio was gone. 
This is how it's displayed in the settings of Ubuntu:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/86980264/dd290c8a-c4b9-4665-a170-929b99ed67c6)

**Comment by herbiejhopkins** [comment]
For me with 1.2.8 I get the confirmation "Press OK for windows and Cancel for monitors". Regardless of whether I click Ok or Cancel my xdg-portal dialogue then pops up which allows me to choose a screen or a window
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/56479007/85a6e4f0-da3e-4d8d-a5f2-6fbf4cb5ee28)

So it works but not sure what the point of the confirmation is.

**Comment by jijojosephk** [comment]
My understanding is that different desktop environments behave differently. Finding a universal fix for this issue seems difficult.

**Comment by jijojosephk** [comment]
> Hi, this seems to have fixed it. With 1.2.8 I can now share screen and dedicated windows again. However when testing with Markus he reported that he can hear me double/twice. We could identify that there are two inputs used. One from my laptop and one from my Headset. When i disabled the notebook input the double audio was gone. This is how it's displayed in the settings of Ubuntu: ![image](https://user-images.githubusercontent.com/86980264/254882901-dd290c8a-c4b9-4665-a170-929b99ed67c6.png)

May be this is due to screen-sharing picks the audio channel as well. I'll have a look.

**Comment by AccaliaDeElementia** [comment]
upgraded to 1.2.7 today, only gives me the ability to share my screen not just one window.

downgrading to 1.1.8 to restore this functionality via the flatpak command listed her: https://github.com/IsmaelMartinez/teams-for-linux/issues/886#issuecomment-1632423065

KDE Plasma on Archlinux using flatpack version. Happy to test builds if this configuration would produce helpful results to bring this issue to a successful close.

**Comment by hrk** [comment]
> May be this is due to screen-sharing picks the audio channel as well. I'll have a look.

I can attest that the "double-input" bug was introduced with 59e554d9db4d8641f7d78b9062d0eae8a0d0487d (determined via git bisect)

**Comment by PocketSam** [comment]
Today I tried to share a screen but my teammate said he could see only the initial image and my mouse moving around leaving traces. Unfortunately I don't have a screenshot. 
I'll join the chat and try to be helpful to investigate the issue.

**Comment by jijojosephk** [comment]
Kindly test [1.2.9](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.2.9)

**Comment by herbiejhopkins** [comment]
Works for me! I don't see the additional mic capture source when screen-sharing so seems this has fixed the double input issue. Thanks for adding the bypassWaylandSourceSelection parameter to save the extra click.

**Comment by jijojosephk** [comment]
Thanks @herbiejhopkins !

@bss-markus-schulze was not able to get it working. I wonder why because I'm having the same `kernel` and `fedora` version as his. No idea. @bss-markus-schulze could you update if `1.2.9` fixes?

**Comment by r-cdriscoll** [comment]
> Kindly test [1.2.9](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.2.9)

I know my black screen issue (where the other party sees a black screen with mouse cursor) when sharing probably isn't the primary issue, but 1.2.9 still results in the black screen problem, and the application segfaults if I attempt to share a second time during the same 'session'.

When run from a terminal I still see the same `egl_dmabuf.cc` messages.

**Comment by jijojosephk** [comment]
> > Kindly test [1.2.9](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.2.9)
> 
> I know my black screen issue (where the other party sees a black screen with mouse cursor) when sharing probably isn't the primary issue, but 1.2.9 still results in the black screen problem, and the application segfaults if I attempt to share a second time during the same 'session'.
> 
> When run from a terminal I still see the same `egl_dmabuf.cc` messages.
> 
> But also, thank you for your work on this project! :)

Are you on `Ubuntu GNOME`?

**Comment by jijojosephk** [comment]
> > May be this is due to screen-sharing picks the audio channel as well. I'll have a look.
> 
> I can attest that the "double-input" bug was introduced with [59e554d](https://github.com/IsmaelMartinez/teams-for-linux/commit/59e554d9db4d8641f7d78b9062d0eae8a0d0487d) (determined via git bisect)

Must be solved with `1.2.9`

**Comment by r-cdriscoll** [comment]
> > > Kindly test [1.2.9](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.2.9)
> > 
> > 
> > I know my black screen issue (where the other party sees a black screen with mouse cursor) when sharing probably isn't the primary issue, but 1.2.9 still results in the black screen problem, and the application segfaults if I attempt to share a second time during the same 'session'.
> > When run from a terminal I still see the same `egl_dmabuf.cc` messages.
> > But also, thank you for your work on this project! :)
> 
> Are you on `Ubuntu GNOME`?

Yes, I am - 22.04.2 GNOME amd64, Wayland.

**Comment by jijojosephk** [comment]
> Today I tried to share a screen but my teammate said he could see only the initial image and my mouse moving around leaving traces. Unfortunately I don't have a screenshot. I'll join the chat and try to be helpful to investigate the issue.

Kindly share your system details.

**Comment by jijojosephk** [comment]
> > > > Kindly test [1.2.9](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.2.9)
> > > 
> > > 
> > > I know my black screen issue (where the other party sees a black screen with mouse cursor) when sharing probably isn't the primary issue, but 1.2.9 still results in the black screen problem, and the application segfaults if I attempt to share a second time during the same 'session'.
> > > When run from a terminal I still see the same `egl_dmabuf.cc` messages.
> > > But also, thank you for your work on this project! :)
> > 
> > 
> > Are you on `Ubuntu GNOME`?
> 
> Yes, I am - 22.04.2 GNOME amd64, Wayland.

OK, I'll setup a machine with `Ubuntu GNOME 22.0.4.2` tomorrow and set up a development environment. Let me know if you have upgraded or downgraded `kernel`, I want to have the same `kernel` just like yours.

**Comment by r-cdriscoll** [comment]
> > > > > Kindly test [1.2.9](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.2.9)
> > > > 
> > > > 
> > > > I know my black screen issue (where the other party sees a black screen with mouse cursor) when sharing probably isn't the primary issue, but 1.2.9 still results in the black screen problem, and the application segfaults if I attempt to share a second time during the same 'session'.
> > > > When run from a terminal I still see the same `egl_dmabuf.cc` messages.
> > > > But also, thank you for your work on this project! :)
> > > 
> > > 
> > > Are you on `Ubuntu GNOME`?
> > 
> > 
> > Yes, I am - 22.04.2 GNOME amd64, Wayland.
> 
> OK, I'll setup a machine with `Ubuntu GNOME 22.0.4.2` tomorrow and set up a development environment. Let me know if you have upgraded or downgraded `kernel`, I want to have the same `kernel` just like yours.

I'm using `6.4.3-060403-generic` currently, but I'd be happy to revert to a different kernel for testing.  Would it be helpful if I joined that Matrix chat?

**Comment by jijojosephk** [comment]
> For me with 1.2.8 I get the confirmation "Press OK for windows and Cancel for monitors". Regardless of whether I click Ok or Cancel my xdg-portal dialogue then pops up which allows me to choose a screen or a window ![image](https://user-images.githubusercontent.com/56479007/254898610-85a6e4f0-da3e-4d8d-a5f2-6fbf4cb5ee28.png)
> 
> So it works but not sure what the point of the confirmation is.
> 
> Note this is on Hyprland using xdg-desktop-portal-hyprland.

Well, I'm curious about this thing. Why would it behave differently?

**Comment by jijojosephk** [comment]
> > > > > > Kindly test [1.2.9](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.2.9)
> > > > > 
> > > > > 
> > > > > I know my black screen issue (where the other party sees a black screen with mouse cursor) when sharing probably isn't the primary issue, but 1.2.9 still results in the black screen problem, and the application segfaults if I attempt to share a second time during the same 'session'.
> > > > > When run from a terminal I still see the same `egl_dmabuf.cc` messages.
> > > > > But also, thank you for your work on this project! :)
> > > > 
> > > > 
> > > > Are you on `Ubuntu GNOME`?
> > > 
> > > 
> > > Yes, I am - 22.04.2 GNOME amd64, Wayland.
> > 
> > 
> > OK, I'll setup a machine with `Ubuntu GNOME 22.0.4.2` tomorrow and set up a development environment. Let me know if you have upgraded or downgraded `kernel`, I want to have the same `kernel` just like yours.
> 
> I'm using `6.4.3-060403-generic` currently, but I'd be happy to revert to a different kernel for testing. Would it be helpful if I joined that Matrix chat?

I'll setup the machine and we'll compare. Yes please join the room.

**Comment by ManarArabi** [comment]
This problem happened with me after upgrading to Ubuntu 22.04

**Comment by jijojosephk** [comment]
> This problem happened with me after upgrading to Ubuntu 22.04

Could you share the `kernel` version?

**Comment by herbiejhopkins** [comment]
> Well, I'm curious about this thing. Why would it behave differently?

xdg-desktop-portal is a standard interface but has a different backend depending on your environment. There's a xdg-desktop-portal-gnome and xdg-desktop-portal-kde etc that look and can behave a little differently.

For the people reporting black screen when sharing, might be worth confirming that screen sharing works in a browser. You can use https://mozilla.github.io/webrtc-landing/gum_test.html as a quick test.

**Comment by jijojosephk** [comment]
> Good Morning, just tested V.1.2.9 with Markus. Sharing is working and Dual-Audio is not happening anymore so looks good for me! Thanks for digging through this!

But Markus seems having issue.

**Comment by bss-markus-schulze** [comment]
> > Good Morning, just tested V.1.2.9 with Markus. Sharing is working and Dual-Audio is not happening anymore so looks good for me! Thanks for digging through this!
> 
> But Markus seems having issue.

But not related to this. Sharing in general is working with 1.2.9

**Comment by jijojosephk** [comment]
I believe `1.2.9` works. Closing this. Please comment if someone needs help.

Try to join the matrix chat room https://matrix.to/#/#teams-for-linux_community:gitter.im
