### ISSUE TITLE
Stuck on purple screen, no user agent changes

### ISSUE THREAD

**Issue by LukeStonehm** [IsmaelMartinez/teams-for-linux#90]
Good day.

Thank you very much for this, it's an extreme help for those that use Linux.

The first few days using this went well, it worked wonderfully.

However, at this point, upon opening the app, I am stuck with the purple background (no loading image). The title bar says "initialising teams". 

Is there anything I can do to get past this, I've tried refreshing the app using the menu option, but sadly that did not help. Is there config I could remove to start over? I've looked in the typical places such as ~/.config

For context, I'm running a System76 machine with Pop! OS (which is a lightly skinned Ubuntu Gnome).

Thanks everyone for the big effort here :smile:

**Comment by nickelby** [comment]
One way for me to bypass this is if you left click on the systray icon (at least for me in Mint) is to click on the option "refresh". That should solve the problem.

**Comment by IsmaelMartinez** [comment]
Hi,

I had this sometimes after installation. I tend to do `ctrl+r` to refresh (is the shortcut for that @nickelby recommends)

Make sure you don't provide an invalid userAgent (if you are providing anything in there). If doing that, do not provide an empty one (as that is invalid). 

Also, changing the user agent sometimes create that situation (I think there is some persistence in the .config section that messes up with this). 

After changing the userAgent, most of the times you need to remove the content under `~/.config/teams-for-linux`.

Other than that... not sure how else I can help. Hope helps

**Comment by LukeStonehm** [comment]
Hey @IsmaelMartinez & @nickelby thanks for the response. I've tried the `ctrl+r` refresh, that hasn't had any effect.

Secondly, I looked in `~/.config` and could not find the "teams-for-linux" folder :thinking: Any ideas?

**Comment by LukeStonehm** [comment]
Ok well, I uninstalled it (I've been using snap) and reinstalled it, and it seems to be working again :smile: 

Honestly should have tried that in the beginning, but whatever. Thanks for all the hard work chaps :+1:

**Comment by IsmaelMartinez** [comment]
Hi @LukeStonehm , snap has the config stored in `/home/$HOME/snap/teams-for-linux` so that will be why you didn't see your config folder.

**Comment by LukeStonehm** [comment]
Hey @IsmaelMartinez thanks. I'll keep that in mind if I encounter the issue again. :+1:
