### ISSUE TITLE
login with sso certificat

### ISSUE THREAD

**Issue by Proliecan** [IsmaelMartinez/teams-for-linux#900]
**Describe the bug**
At my org we use sso certificates to log into teams enterprise.
The loginpage loads, but electron doesn't give me the option to select my certificate...

**Expected behavior**
When I need to be verified by certificate, electron should ask like every other browser, what certificate to use and then answer the request.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Installation package  https://repo.teamsforlinux.de/debian stable/main
 - Version 22.04 LTS

**Comment by jijojosephk** [comment]
This may be difficult. But would be great if you can provide some screenshots.

**Comment by Proliecan** [comment]
unfortunately due to NDA, I cannot...

**Comment by jijojosephk** [comment]
You could obfuscate the sensitive information.
