### ISSUE TITLE
Notification when someone is available not working directly

### ISSUE THREAD

**Issue by user858753257** [IsmaelMartinez/teams-for-linux#903]
**Describe the bug**
Only displayed when teams for Linux is active in foreground . When app in background there is no notification 

**To Reproduce**
1. Enable “notification” for a user
2. Out the app in background 
3. Wait for a notification 

**Expected behavior**
While in background there should be a notification 

**Screenshots**

**Desktop (please complete the following information):**
 - OS:EndavorOS (based on Arch Linux) 
- Kernel : 6.4.4

**Additional context**

**Comment by jijojosephk** [comment]
Would be great if you can elaborate a bit more.

**Comment by F3000** [comment]
Teams has a function to get a notification when somebody (own company) set his status on “available” 
To enable right click on a chat -> turn on notification 

This type of notification teams for Linux only displays when the app is open . 

Other notifications (new message) I will receive and see it in notification area when teams for Linux is in background

**Comment by jijojosephk** [comment]
I think these are getting added to the queue. Once the app is in focus, it will be shown. It's something with MS code. May be difficult to find a solution.

**Comment by NgoHuy** [comment]
I turn on blocked when desktop is active, but no effect, it still notified on mobile. It worked on mac with official app. so strange

**Comment by IsmaelMartinez** [comment]
For info, I am seeing the same issue with the official MacOS app and the Android App installed in my mobile. I think this one is for the ms forum. Extremely annoying.

**Comment by F3000** [comment]
On mobile (iOS) there is no option to turn this feature on for a specific user

**Comment by IsmaelMartinez** [comment]
Are you using the official app or the 'teams-for-linux'? In any case, I
think this one is with MS.

**Comment by IsmaelMartinez** [comment]
Closing this issue to clean the open issues. This is because there hasn't been activity for a few months now. If you still face this issue in versions 1.4.1 and above, please share it and we can re-open it. Thanks in advance!
