### ISSUE TITLE
apparmor=DENIED messages in syslog

### ISSUE THREAD

**Issue by pplu** [IsmaelMartinez/teams-for-linux#91]
Hi,

   We're using the teams-for-linux snap and we're getting these messages in /var/log/syslog from time to time:
```
Apr  2 11:34:34 l001199 kernel: [13270.865560] audit: type=1107 audit(1554197674.529:2527): pid=1144 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/UPower" interface="org.freedesktop.UPower" member="EnumerateDevices" mask="send" name="org.freedesktop.UPower" pid=9244 label="snap.teams-for-linux.teams-for-linux" peer_pid=1910 peer_label="unconfined"
```
Just wanted to give you guys a heads-up, since this may be causing some feature to not work correctly.

**Comment by IsmaelMartinez** [comment]
Its strange, I don't think we are looking at the battery or any power devices. 

We do check for network connectivity, to see if you are online/offline, and that might be related.

Could you check, if possible, if this happens with and without network cable, and with or without Wifi enabled?

**Comment by IsmaelMartinez** [comment]
Could either @benyanke or @julian-alarcon have a look at this? Might be ok to just close it. We don't do any power management that I am aware, but the checking the online/offline status might be indirectly doing this.

**Comment by IsmaelMartinez** [comment]
closing but @benyanke and @julian-alarcon might want to check if it affects snap apps. Reopen if needed. Thanks for the info @pplu

**Comment by julian-alarcon** [comment]
Ok I check this yesterday and you were right @pplu . Snap packaging uses AppArmor to isolate apps.

I found 3 kind of messages, 2 are solved in my last commit:

`May  6 16:11:10 MYPC dbus-daemon[2611]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/gnome/SessionManager" interface="org.gnome.SessionManager" member="Inhibit" mask="send" name="org.gnome.SessionManager" pid=29097 label="snap.teams-for-linux.teams-for-linux" peer_pid=2722 peer_label="unconfined"
This one is related with screen-inhibit-control interface on snap, I added this to inhibit the dim or lock screen on a presentation.

and 

`May  6 15:43:37 MYPC kernel: [31320.970451] audit: type=1107 audit(1557175417.199:164): pid=1369 uid=103 auid=4294967295 ses=4294967295 subj==unconfined msg='apparmor="DENIED" operation="dbus_method_call" bus="system" path="/org/freedesktop/UPower" interface="org.freedesktop.UPower" member="GetDisplayDevice" mask="send" name="org.freedesktop.UPower" pid=29097 label="snap.teams-for-linux.teams-for-linux" peer_pid=
1723 peer_label="unconfined"`

This is related to obtain info of the power status of the device. Also added on my last commit.

I'm still getting one warning, but I don't think that it's necessary to look for it, it's related with devices with no common use on MS Teams. I'll keep checking and if I don't see any use of those devices then I will close this bug. 

```
May  6 16:39:05 MYPC kernel: [34649.005965] audit: type=1400 audit(1557178745.234:855): apparmor="DENIED" operation="file_inherit" profile="snap-update-ns.teams-for-linux" name="/dev/pts/4" pid=27369 comm="5" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=1000

May  6 16:39:05 MYPC kernel: [34649.005983] audit: type=1400 audit(1557178745.234:857): apparmor="DENIED" operation="file_inherit" profile="snap-update-ns.teams-for-linux" name="/apparmor/.null" pid=27369 comm="5" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0

May  6 16:39:05 MYPC kernel: [34649.005985] audit: type=1400 audit(1557178745.234:858): apparmor="DENIED" operation="file_inherit" profile="snap-update-ns.teams-for-linux" name="/snap/code/6/usr/share/code/icudtl.dat" pid=27369 comm="5" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by pplu** [comment]
With `0.2.1` I'm not getting the `DENIED` messages from teams for linux :dancer:

**Comment by IsmaelMartinez** [comment]
Perfect, @julian-alarcon , maybe then this can be closed

**Comment by luigimannoni** [comment]
I am very sorry to bump this issue but it seems this appeared again in the latest version. on ubuntu 22.04

```
Apr 04 15:45:49 phobos kernel: audit: type=1400 audit(1649083549.751:12842): apparmor="DENIED" operation="open" profile="snap.teams.teams" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/charge_full" pid=27169 comm="teams" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Apr 04 15:45:49 phobos kernel: audit: type=1400 audit(1649083549.751:12843): apparmor="DENIED" operation="open" profile="snap.teams.teams" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/capacity" pid=27169 comm="teams" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Apr 04 15:45:50 phobos audit[27169]: AVC apparmor="DENIED" operation="open" profile="snap.teams.teams" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/charge_full" pid=27169 comm="teams" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Apr 04 15:45:50 phobos audit[27169]: AVC apparmor="DENIED" operation="open" profile="snap.teams.teams" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/capacity" pid=27169 comm="teams" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

**Comment by IsmaelMartinez** [comment]
Hi, can you try another package system? Do you have any issues or it's just
an annoying warning? Thanks

**Comment by xorinzor** [comment]
What @luigimannoni says, same issue here.
Installed via "Ubuntu Software" as snap.

**Comment by MathiasDeRoover** [comment]
Hey @IsmaelMartinez, was a solution found for these messages in the end:
```
[58420.683875] audit: type=1400 audit(1661328812.819:2311): apparmor="DENIED" operation="open" profile="snap.teams.teams" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/charge_full" pid=226271 comm="teams" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[58420.683883] audit: type=1400 audit(1661328812.819:2312): apparmor="DENIED" operation="open" profile="snap.teams.teams" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/capacity" pid=226271 comm="teams" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[58421.683913] audit: type=1400 audit(1661328813.819:2313): apparmor="DENIED" operation="open" profile="snap.teams.teams" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/charge_full" pid=226271 comm="teams" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[58421.683924] audit: type=1400 audit(1661328813.819:2314): apparmor="DENIED" operation="open" profile="snap.teams.teams" name="/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0A:00/power_supply/BAT0/capacity" pid=226271 comm="teams" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```
They are completely flooding out any other logs.
```
teams              1.5.00.10453                7      latest/stable  msteams✓              -
```

**Comment by IsmaelMartinez** [comment]
No solution found. Sorry. But I suspect is related to the snap configuration rather than the app itself

**Comment by MathiasDeRoover** [comment]
Do you know who I can contact regarding the snap configuration?

**Comment by jijojosephk** [comment]
@MathiasDeRoover I think you're looking at the official teams client from Microsoft. This is different.
