### ISSUE TITLE
White screen after wakeup from suspend mode

### ISSUE THREAD

**Issue by mikehaertl** [IsmaelMartinez/teams-for-linux#913]
**Describe the bug**

When I wake up my system from suspend mode the teams window shows a white screen. Pressing `<CTRL-r>` refreshes the window and seems to fix the issue.

**To Reproduce**
1. Start teams
2. Send the system to suspend mode
3. Press a key to wake up the system

**Expected behavior**
The app should show the normal window after wakeup. This worked fine until the latest release.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2 Victoria
 - Installation package deb
 - Version 1.3.0

**Additional context**

When started from the command line it immediately shows this message. Not sure if it's related:

```
$ teams-for-linux 
[ERROR] connect ECONNREFUSED 127.0.0.1:80
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[4144649:0807/191322.207646:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
```

**Comment by jijojosephk** [comment]
Are you having the same problem as #723 ?

**Comment by mikehaertl** [comment]
It shows the same symptoms, yes. Here's the debug log output:

```
[DEBUG] configPath:,/home/mike/.config/teams-for-linux
[INFO] No config file found, using default values
[DEBUG] configFile:,[object Object]
[DEBUG] Fetching custom background configuration from 'http://localhost/config.json'
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--appLogLevels,warn,info,error,debug
[DEBUG] Spellchecker is disabled!
[ERROR] connect ECONNREFUSED 127.0.0.1:80
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[4165423:0808/075503.469032:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[DEBUG] did-finish-load
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-finish-load
[DEBUG] Badge count set to '0'
[DEBUG] User status changed to '1'
[DEBUG] User status changed to '1'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 4s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'

[... suspend ...]

[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 3s, IdleState: 'active'
[DEBUG] Waiting for network
[DEBUG] Waiting for network
[DEBUG] Reloading the page on system resume
[DEBUG] Reloading the page on system resume
[DEBUG] render-process-gone
```

**Comment by jijojosephk** [comment]
> [DEBUG] render-process-gone

Yeah this `[DEBUG] render-process-gone` is the new problem introduced in electron version `25.x`. You can reproduce the same problem even without suspending the system.

- Quit the app
- Launch again
- From the tray icon  or app menu choose `Refresh`
- See the result. You'd see a white screen. Only the second refresh works. It's a new bug introduced in electron.

**Comment by mikehaertl** [comment]
>  You can reproduce the same problem even without suspending the system.

Confirmed.

I've searched for a related issue at electron but didn't find any. Do you know if this is worked on or when to expect a fix?

**Comment by jijojosephk** [comment]
I'll work on a solution. Hopefully in a few hours :laughing: I got too much on my personal work list. Will see if this can be quick. Thanks for reporting.

**Comment by jijojosephk** [comment]
Tried to upgrade to latest electron `25.4.0`, but the problem persists. So we need to find some work arounds.

**Comment by jijojosephk** [comment]
Merge closed it automatically. Kindly check when version `1.3.1` is available.

**Comment by mikehaertl** [comment]
Cool, thanks

**Comment by jijojosephk** [comment]
@mikehaertl  What's done is a work-around. Created a defect here: https://github.com/electron/electron/issues/39476

**Comment by mikehaertl** [comment]
> What's done is a work-around. 

Yeah, I've also now seen it sometimes reload when it should not. Anyhow it's better than before.

**Comment by jijojosephk** [comment]
We'll downgrade the electron. Check out version `1.3.2` when it's available.
