### ISSUE TITLE
Spell check not working

### ISSUE THREAD

**Issue by manishjvora** [IsmaelMartinez/teams-for-linux#916]
Hello,
Spell check not working!
I cleared the storage and reset the teams, but still not working

**Comment by jijojosephk** [comment]
Can you share some logs? Launching from terminal. Also please follow the template to create an issue. Providing the package, distribution, windowing system etc.

**Comment by jijojosephk** [comment]
@manishjvora can you update?

**Comment by manishjvora** [comment]
@jijojosephk Thank you. After recent (yesterday) update, it started working, so did not shared update. Thanks!
