### ISSUE TITLE
using TZ=":/etc/localtime" Teams is off by 1 hour

### ISSUE THREAD

**Issue by harridu** [IsmaelMartinez/teams-for-linux#917]
**Describe the bug**
Not a big thing, but if I set the TZ environment variable to 
```
% ls -l /etc/localtime 
lrwxrwxrwx 1 root root 23 Aug  8 06:57 /etc/localtime -> /usr/share/zoneinfo/CET
% export TZ=:/etc/localtime
% teams-for-linux
```
(which is an extension of the GNU C library, see https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html), then the clock shown in Teams is off by one hour. For CET I get 5:21 instead of 6:21 . GMT is 4.21. DST is on.

Obviously Teams doesn't understand $TZ. In this case it should fall back to system time zone (eg. CET) or GMT.

**Desktop (please complete the following information):**
 - Debian 12
 - teams-for-linux 1.3.1 debian package
 - 1.3.1

I understand that this is super-low priority.

**Comment by jijojosephk** [comment]
Time & date is in control of `chromium`. Not sure we can do much.

**Comment by IsmaelMartinez** [comment]
maybe is related to https://github.com/electron/electron/issues/37972

**Comment by IsmaelMartinez** [comment]
can you verify if this is still an issue using 1.4.1 an above? Closing to keep things tidy. Hopefully it is now sorted
