### ISSUE TITLE
Auto refresh app if internet is available

### ISSUE THREAD

**Issue by kkmaslowski** [IsmaelMartinez/teams-for-linux#918]
**Is your feature request related to a problem? Please describe.**
When there is no internet app starts with blank white page and nothing changes when internet is available.

**Describe the solution you'd like**
Auto refresh, load app if internet is available.

![Zrzut ekranu z 2023-08-09 08-36-18](https://github.com/IsmaelMartinez/teams-for-linux/assets/910243/29ac8b5c-7ac8-4c2c-807d-8538d3cfe4e2)

**Describe alternatives you've considered**
Now I need to click app icon in tray and select 'Refresh'.

**Comment by jijojosephk** [comment]
This is happening when the system state changes from `Stand-by` to `Active`. Are you looking for the at start up?

**Comment by kkmaslowski** [comment]
@jijojosephk Yes, on latest version 1.3.1 it's happening on every boot, even if I have laptop connected to LAN. I have teams-for-linux in Autostart. It starts normally if I disable autostart and starti it manually after system loads.
I'm using Fedora 37.
