### ISSUE TITLE
Getting an Annoying pop up window for JavaScript Failure

### ISSUE THREAD

**Issue by KhudadadKhawari** [IsmaelMartinez/teams-for-linux#920]
**Describe the bug**
After the latest Updated of Teams I am getting an Error pop up window for JavaScript Failure

**To Reproduce**
This happens automatically whenever the app is open or I recieve a message or I send a message

**Expected behavior**

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/54738188/850ab355-f696-4dc3-b785-b2cd0b2becfe)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.0.4 
 - Installation package Ubuntu Software
 - Version [the one release in August 2023]

**Comment by jijojosephk** [comment]
Is it random?

**Comment by jijojosephk** [comment]
Can you run `teams-for-linux --appLogLevels error,warn,info,debug` from terminal and share the logs?

**Comment by jijojosephk** [comment]
This was introduced when electron version was upgraded. I created a defect here https://github.com/electron/electron/issues/39476

**Comment by jijojosephk** [comment]
We'll downgrade the electron. Check out version `1.3.2` when it's available.

**Comment by jijojosephk** [comment]
This should now be gone after the `electron' downgrade. Closing this as I expect this be fixed. Re-open if required.
