### ISSUE TITLE
Flatpak not reading config.json from ~/.config/teams-for-linux

### ISSUE THREAD

**Issue by dicamarques14** [IsmaelMartinez/teams-for-linux#925]
**Describe the bug**
I need to toggle some settings and I read I could use the config.json file
I explicitily added "menubar" visible so I could know if it was reading the file or not, and its ignoring it
I even tried placing in the "/var/lib/flatpak/app/com.github.IsmaelMartinez.teams_for_linux/current/active/files/teams-for-linux/config.json" with some success but it's no longer working.

**To Reproduce**
1. Create a file called "config.json" in ~/.config/teams-for-linux
2. Insert these values `{
    "disableAutogain": true,
    "disableNotificationSound": true,
    "menubar": "visible"
}`
3. Open teams for linux

**Expected behavior**
Expected to get the values applied in the app (menubar is still not visible for example)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04 with plasma DE
 - Installation package: flatpak
 - Version 1.3.2

**Comment by jijojosephk** [comment]
For `flatpak` it's different `~/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux `

**Comment by dicamarques14** [comment]
> For `flatpak` it's different `~/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux `

Thanks, maybe it should be in the readme next to the snap pack path

**Comment by jijojosephk** [comment]
@dicamarques14 is it working for you now? I'll have it updated in the read me.

**Comment by dicamarques14** [comment]
Yes I can see the menubar so it must be working
