### ISSUE TITLE
App Reloading During Active Call due to Brief Internet Disconnection

### ISSUE THREAD

**Issue by sknetl** [IsmaelMartinez/teams-for-linux#926]
**Describe the bug**

The app reloads during an active call if the internet connection goes down for just a second.

**To Reproduce**
1. Initiate a call.
2. Intentionally disconnect the internet connection.
3. Swiftly restore the internet connection.
4. Microsoft Teams successfully re-establishes the call without any complications.
5. Unexpectedly, after 10 seconds the reload mechanism is activated, resulting in the WebApp being reloaded. This occurrence is particularly annoying as the brief disconnections I experience do not interrupt the ongoing call.
https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/onlineOffline

**Expected behavior**

No reload if there's an active call or improved reload mechanism. (I actually don't know why we need this at all?). I guess there's a valid reason.

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Installation package: Flatpak
 - Version 1.3.0

**Comment by jijojosephk** [comment]
Are you using `--onlineOfflineReload` flag? If so, please avoid it. It's an old code and we haven't done anything there. Without that setting, things are working fine for me. I have not faced anything like this.

**Comment by sknetl** [comment]
Nope I just run

`flatpak run com.github.IsmaelMartinez.teams_for_linux`

I installed it from Flathub. But I'm pretty sure it's the code I mentioned above. There's a timeout set to 10 seconds. You can see the call continues real quick and I can count to 10. Then the reload happens.

**Comment by jijojosephk** [comment]
okay, I believe the default value for `--onlineOfflineReload` is true.

**Comment by sknetl** [comment]
Starting it with ` com.github.IsmaelMartinez.teams_for_linux --onlineOfflineReload false`  solved it! Thanks @jijojosephk

**Comment by sknetl** [comment]
(still not sure why this feature was implemented).

> I guess the flag --onlineOfflineReload should be removed. 

+1 for that

**Comment by jijojosephk** [comment]
Just merged a PR. Some changes are for future implementations also default for `onlineOfflineReload` set to false. You can ignore this flag in version `1.3.4`

**Comment by jijojosephk** [comment]
> (still not sure why this feature was implemented).
> 
> > I guess the flag --onlineOfflineReload should be removed.
> 
> +1 for that

That's an old implementation. We don't need that anymore. Future versions will have the code removed.

**Comment by sknetl** [comment]
Thank you!
