### ISSUE TITLE
Seamless single sign on failed

### ISSUE THREAD

**Issue by dhensen** [IsmaelMartinez/teams-for-linux#927]
**Describe the bug**

**To Reproduce**
1. Login into teams via MS SSO
2. work for about 8-9 hours, then it behaviour is triggered:

```
Error Code: interaction_required|Seamless single sign on failed for the user. This can happen if the user is unable to access on premises AD or intranet zone is not configured correctly
```

**Expected behavior**
I want to stay logged in, but this popup makes me unable to continue without Signing in again.
In the meanwhile in the background I see new messages coming in.

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2786295/fe639b81-488c-4b00-af56-7ca95e8fb488)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Installation package: AUR teams-for-linux (https://aur.archlinux.org/packages/teams-for-linux)
 - Version 1.2.4-1

**Additional context**
As I'm writing this bug, I see https://aur.archlinux.org/packages/teams-for-linux has been flagged out of date. I will instead install https://aur.archlinux.org/packages/ms-teams-for-linux-bin and report back tomorrow as this has been consistently happening for the past week weeks.

**Comment by jijojosephk** [comment]
Sadly, this is not in our control. Web version behaves the same across all the web browsers running under Linux. Helpless, sorry.

**Comment by dhensen** [comment]
Ok, good to know. Thanks for looking into this.
