### ISSUE TITLE
Electron regularly crashing while the app is in background

### ISSUE THREAD

**Issue by victornoel** [IsmaelMartinez/teams-for-linux#928]
**Describe the bug**

From time to time, teams crashes while I'm not using it. See the attached core dump.

Also it has a tendency to refresh and reload the whole app when I start it, and sometimes by itself while I am using it.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Archlinux, Xorg
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...]: AUR
 - Version [e.g. 0.1.17] 1.3.2

**Additional context**

[teams-crash.log](https://github.com/IsmaelMartinez/teams-for-linux/files/12357586/teams-crash.log)

**Comment by victornoel** [comment]
@jijojosephk right, this is the one I am using: https://aur.archlinux.org/packages/teams-for-linux

I didn't even notice there were multiple such package, I will try a few of them to see if the issue happens all the time or not. Thanks!

**Comment by jijojosephk** [comment]
Can you try this? https://aur.archlinux.org/packages/ms-teams-for-linux-bin

**Comment by victornoel** [comment]
@jijojosephk haha, my bad, actually that's the one I'm using, I was just coming back to change my comment ^^

I will try https://aur.archlinux.org/packages/teams-for-linux instead now which does not rely on a debian package

**Comment by jijojosephk** [comment]
I guess, then you'll have to build it dynamically using the other package.

https://aur.archlinux.org/packages/teams-for-linux

**Comment by victornoel** [comment]
I also downgraded nodejs to v16 (I was using v20). Is that correct? I couldn't find any recommended version apart from what's in the Github CI files :)

**Comment by jijojosephk** [comment]
> I also downgraded nodejs to v16 (I was using v20). Is that correct? I couldn't find any recommended version apart from what's in the Github CI files :)

Tested up to `18 LTS`

**Comment by jijojosephk** [comment]
Any progress :smile:  ?

**Comment by jijojosephk** [comment]
You can join the chat room here: https://matrix.to/#/#teams-for-linux_community:gitter.im

**Comment by victornoel** [comment]
@jijojosephk I'm testing it out, if it doesn't crash for a day I will consider it solved (and I suspect the cause would have been the nodejs version ^^)

**Comment by victornoel** [comment]
@jijojosephk it seems to work correctly now, thank you again for your help and sorry for the noise here :)

**Comment by jijojosephk** [comment]
> @jijojosephk it seems to work correctly now, thank you again for your help and sorry for the noise here :)

No worries. You may join the matrix chat room: https://matrix.to/#/#teams-for-linux_community:gitter.im you might get immediate responses there.
