### ISSUE TITLE
Network never detected, app does not start

### ISSUE THREAD

**Issue by zeitounator** [IsmaelMartinez/teams-for-linux#933]
**Describe the bug**
New feature "waiting for network" does not give expected result in my environment. The application never starts and always hangs on a blank page showing "no internet connection" in the title bar. I tried multiple times and cleared storage without success. 

Of course, I made sure network was available prior to filling this issue which is the case: I can browse any external site from my browser including the teams web site and downgrading the app to 1.3.3 works as expected for now.

**To Reproduce**
1. Start the app (either with or without clearing storage)
2. Watch the title bar showing "waiting for network"
3. Wait until the title bar changes to "no internet connection"
4. The app stays frozen on a blank page and does not start

**Expected behavior**
The app detect network correctly and starts normally

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package deb (via apt channel)
 - Version 1.3.5

**Additional context**
Possibly interfering:
- I run a local squid proxy forwarding requests to my company proxy. It runs on a local IP on port 8080
- I have 2 network interfaces enabled on my machine (although leaving only one enabled did not change anything).

**Comment by jijojosephk** [comment]
I guess the problem is proxy. Thanks for pointing that out.

**Comment by jijojosephk** [comment]
Are you using `proxyServer` parameter?

**Comment by zeitounator** [comment]
No, I'm entirely relying on the system/shell environment variables. As an example:
```
https_proxy=http://172.17.0.1:8080/
NO_PROXY=
HTTPS_PROXY=http://172.17.0.1:8080/
HTTP_PROXY=http://172.17.0.1:8080/
http_proxy=http://172.17.0.1:8080/
```

**Comment by jijojosephk** [comment]
> No, I'm entirely relying on the system/shell environment variables. As an example:
> 
> ```
> $ env | grep -i prox
> no_proxy=
> https_proxy=http://172.17.0.1:8080/
> NO_PROXY=
> HTTPS_PROXY=http://172.17.0.1:8080/
> HTTP_PROXY=http://172.17.0.1:8080/
> http_proxy=http://172.17.0.1:8080/
> ```
> 
> FYI: 172.17.0.1 points to an interface on my machine (i.e. docker veth) if this has any importance.

Apologies, I didn't see this coming. Till I find a suitable fix, you may have to continue with `1.3.3`

**Comment by jijojosephk** [comment]
@zeitounator can you share the details about the vETH docker image. So, that I can use the same to test locally.

**Comment by zeitounator** [comment]
There's actually no docker image involved. Squid is running directly on my machine and listening on the docker bridge IP. The idea is to have a single proxy that can be configured with the same parameters either on my machine or from a docker container. The squid configuration goes beyond scope and honnestly, I don't think there is anything different than setting any proxy in the environment.

You can probably reproduce by simply installing squid and keep the default config (listening on localhost on port 3128). But If you really want to reproduce something similar to my situation, here is a minimal setup:
1. Make sure docker is installed and running (the docker daemon is enough, you don't need any running container). Check the ip of the default docker bridge (`ip a list docker0`)
2. Install squid. In `/etc/squid/squid.conf`, set `http_port <docker_bridge_ip>:3128`. Restart squid. At this point squid should listen on docker bridge ip and forward request directly on your internet connection
3. Set the proxy in your environment to point to squid:
    ```bash
    export http_proxy="http://<docker_bridge_ip>:3128/"
    export https_proxy="${http_proxy}"
    export HTTP_PROXY="${http_proxy}"
    export HTTPS_PROXY="${http_proxy}"
    ```
   (FYI: this is set in my session on my machine)
4. Check that you can access the outside world from your configured terminal
   ```bash
    curl https://www.qwant.com
    ```
5. Start teams-for-linux in that same terminal and network detection should  fail.

**Comment by jijojosephk** [comment]
`curl https://www.qwant.com` gives `curl: (7) Couldn't connect to server` but `teams-for-linux` launches without problem. :confused:

**Comment by zeitounator** [comment]
This is going to be hard to reproduce as you will always be in a situation where dns resolution will work whereas it does not in my environment. The issue is quite easy to understand just looking at the code:

https://github.com/IsmaelMartinez/teams-for-linux/blob/e5bac9882741bfb8476f680eea223429ba31a3e8/app/menus/connectivity.js#L24C1-L34C2

The resolveDNS function will never ever return true when behind a company proxy as you have to go through the proxy to connect and a dns lookup will not answer. I only see a few solutions here:
1. stop relying on dns resolution to make your test. Make a direct http call and check for a 200 status for example. This will work with or without a proxy
2. allow users to disable that feature by configuration
3. disable that feature or adapt it when you detect a proxy is in use
4. remove that feature all together (maybe I missed something but I don't really get its value compared to restarting teams anyway if network has a problem...)

**Comment by jijojosephk** [comment]
> This is going to be hard to reproduce as you will always be in a situation where dns resolution will work whereas it does not in my environment. The issue is quite easy to understand just looking at the code:
> 
> https://github.com/IsmaelMartinez/teams-for-linux/blob/e5bac9882741bfb8476f680eea223429ba31a3e8/app/menus/connectivity.js#L24C1-L34C2
> 
> The resolveDNS function will never ever return true when behind a company proxy as you have to go through the proxy to connect and a dns lookup will not answer. I only see a few solutions here:
> 
> 1. stop relying on dns resolution to make your test. Make a direct http call and check for a 200 status for example. This will work with or without a proxy
> 2. allow users to disable that feature by configuration
> 3. disable that feature or adapt it when you detect a proxy is in use
> 4. remove that feature all together (maybe I missed something but I don't really get its value compared to restarting teams anyway if network has a problem...)
> 
> I have about a hundred users impacted by this problem here and told them to stick to version 1.3.3. for now.


This feature was added to support users who add `teams-for-linux` to system start up. Where it can take a while to detect the network during system start up, this feature avoids showing a blank page.

Regarding proxy, I guess `http` should help instead of `dns` like you suggested. Thanks! There are 2 ways users use proxy 

- The way you use
- And by using `proxyServer` parameter.

The solution should support both. I don't have much knowledge with proxy servers so, testing can be difficult at my side. Let's see.

**Comment by jijojosephk** [comment]
Can you try with `1.3.7` ?

**Comment by IsmaelMartinez** [comment]
Putting it under a feature flag (config option) should be possible. If you have time to make that change I would be happy to find some pointers (but you probably know how to do it)

**Comment by zeitounator** [comment]
> Can you try with `1.3.7` ?

@jijojosephk I'm afraid I cannot test that thoroughly until I'm at the office tomorrow but I'll still give it a try today. I might be able to be in the same situation using a vpn connection. I'll report test progress by updating this comment. Thanks for your dedication !

**Comment by thomasgl-orange** [comment]
I've proposed a solution in #945. It uses HTTPS (not DNS) for the connectivity check, but does it with [Electron `net`]() module, thus using the same proxy settings (if any) as the rest of the Electron application. I think it's a reliable way to test that we'll actually be able to later load the app from `https://teams.microsoft.com`.

@zeitounator, I've published a test build (1.3.8-tgl2) with this change, if you want to try it, here: https://github.com/thomasgl-orange/teams-for-linux/releases/tag/untagged-140ffa4264ef18eee6ed

**Comment by thomasgl-orange** [comment]
Ah, sorry, draft release. Now it's published: https://github.com/thomasgl-orange/teams-for-linux/releases/tag/v1.3.8-tgl2

**Comment by jijojosephk** [comment]
> I tested with the amd64.deb package. I did the test with my current `~/.config/teams-for-linux` populated from previous run and an other wiping it totally. The result is the same. My proxy is set through environment variables as shown in my above messages.
> 
> The app gets in a totally crazy loop. The window shows up, the title of the window changes to "checking your credentials" then the window closes and this starts other again and again. Since the app window captures focus when it starts it is almost impossible to do anything. Fortunatelly, the app eventually crashes on a random iteratiion with (sorry there was absolutely no way to capture this modal dialog as text...)
> 
> ![image](https://user-images.githubusercontent.com/176776/265120676-36944235-13e5-4571-8daa-15743cf7fde6.png)
> 
> At this point, leaving the dialog opened, I am able to get the focus on a terminal and issue a `killall teams-for-linux` command before clicking ok. And this is when I finally gain control of my machine again.
> 
> If this has any importance, my login is supposed to bring me to my company saml page. At least this should have been the case on my first try. But once I cleared out the storage, I'm supposed to see the teams login page to enter my email and it never shows up.
> 
> Let me know if I can do any other test to debug this. Thanks.

@zeitounator did you try with `--proxyServer` option in @thomasgl-orange's build?

**Comment by Schinnerl-at** [comment]
I have/had the same problem, because we use a proxy. I have set it in the environment and also in the config.json, with the fix from @thomasgl-orange it works now without a problem. My "workaround" was staying at 1.3.3.

I started it with `--appLogLevels="error,warn,info,debug"` and the only thing that showed up was:
`[ERROR] net::ERR_CONNECTION_REFUSED`

My config.json:
`{
    "proxyServer": "proxy-ip:8080",
    "customCSSName": "compactDark",
    "closeAppOnCross": true
}
`

Thank you for the fix @thomasgl-orange .

@jijojosephk  what does your config.json say? Do you use a custom url? That is just a hunch.

**Comment by thomasgl-orange** [comment]
Thanks @zeitounator and @Schinnerl-at for testing this.

@Schinnerl-at:
> I started it with `--appLogLevels="error,warn,info,debug"` and the only thing that showed up was:
> `[ERROR] net::ERR_CONNECTION_REFUSED`

This error is scary but not a real issue: by default, there's always a request to the default "custom background server" URL, `http://localhost:80` (which is likely to fail in most environments). There's an option to change this URL (`--customBGServiceBaseUrl`), but not to deactivate it. I personally think it would be better if the default was to not try to reach a custom backgrounds server, if none is explicitly configured, but changing that would be for a different issue and PR.

@zeitounator: 
> The app gets in a totally crazy loop. The window shows up, the title of the window changes to "checking your credentials" then the window closes and this starts other again and again.

With the "*checking your credentials*" title, I think that's already past the initial online check, and loading of the Teams URL, so an issue which comes after the code modified by this PR. But of course, there might be something subtle, it's hard to say. I'm glad you've have better success on your next test of my build.

I've uploaded a new version (updated the PR): https://github.com/thomasgl-orange/teams-for-linux/releases/tag/v1.3.8-tgl3

It adds a `--checkOnlineMethod` option with this possible values:
- `https` (default - similar to build 1.3.8-tgl2): uses the `net` API to make an HTTPS request to the main URL (the one from `--url`, or `https://teams.microsoft.com` - I had previously hard-coded `https://teams.microsoft.com`, but maybe some companies use something else somehow and would block this default URL, who knows, so it's better this way I guess...)
- `dns`: uses the `net` API to make a DNS query on the hostname from the main URL (it's a variation of the old, pre-1.3.4, test); not reliable for some use-case involving proxy)
- `native`: uses the Electron `net.isOnline()` method (works for me if directly connected to internet, but it's too optimistic to check that the mandatory proxy, if any, is ready for use)
- `none`: just assume we're online (that's more for testing, or unblocking situations we would not have anticipated)

It also have a few debug logs now in the code involved, so in case of an issue running with `--appLogLevels="error,warn,info,debug"` could help.
