### ISSUE TITLE
Screen sharing again stops working after a while

### ISSUE THREAD

**Issue by andreaippo** [IsmaelMartinez/teams-for-linux#934]
Version 1.3.2, some journalctl here, hope it's useful

https://pastebin.com/5Fyc66At

**Comment by jijojosephk** [comment]
Assume you're on `Wayland`. Could you share some system info?

**Comment by andreaippo** [comment]
Sorry, you're right, I'm on Wayland. Running opensuse Tumbleweed with KDE.

I will be able to provide more info once I'm back at my PC. Is there
anything specific I need to include?

Thanks! 😊

Il mar 22 ago 2023, 07:08 Jijo Joseph ***@***.***> ha scritto:
