### ISSUE TITLE
Taskbar system tray icon

### ISSUE THREAD

**Issue by tawmoto** [IsmaelMartinez/teams-for-linux#937]
Hi,

It will be nice to have a taskbar icon which shows the notification with a red dot, like the official Teams has.
Not sure if it's possible.

See left icon in the photo.
Thanks
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/35702340/62dbcd61-ffe1-4705-b1ab-af6848bbd8e0)

**Comment by IsmaelMartinez** [comment]
please use the enhancement template. The icon might have stopped working when we upgraded the electron version but without filling the template I can only but guess what version/os/packaging you are using. It can also be your packaging system,  OS info, etc.

**Comment by tawmoto** [comment]
Sorry that I did not fill the template, I am on Xubuntu 22.04, Numix theme.
I am using the version installed with "apt ", version 1.3.5

**Comment by IsmaelMartinez** [comment]
Can you try version 1.1.11? It is older but is just to confirm if it was the electron version upgrade. Thanks

**Comment by jijojosephk** [comment]
@tawmoto the tray icon might now show on all desktop environments. Are you seeing the tray icon but no update when there are notifications?

**Comment by tawmoto** [comment]
> @tawmoto the tray icon might now show on all desktop environments. Are you seeing the tray icon but no update when there are notifications?

No, there is no tray icon at all.

@IsmaelMartinez on 1.1.11 it works great

**Comment by IsmaelMartinez** [comment]
Unfortunately this is then an issue with electron. We did decide to go ahead (after asking the community) knowing some OS tray icon would not work. I would say stick with 1.1.11 until we get the electron version that has got the fix. 

@jijojosephk , do you know what was the issue electron needed fixed for support the tray icon? I can't find it now. Thanks!

**Comment by jijojosephk** [comment]
@IsmaelMartinez Unfortunately this won't be fixed as far as I know. Because the `chromium` project permanently switched to `KStatusNotifierItem` with no backward compatibility. So, unless the desktop environments support `KSNI`, users won't see the tray icon. @tawmoto you may try some extensions to achieve the same. But it depends on which desktop desktop environment are you having. I assume it's `XFCE`. Kindly have a look at this https://github.com/mullvad/mullvadvpn-app/issues/4861
I know sometimes things get broken, but we need to keep moving along with `electron` version changes. The tray icon issue was identified and the upgrade was delayed. Then later decided to upgrade when we identified that `chromium` wont' go back or fix it.

**Comment by NeilsC** [comment]
@jijojosephk I can't find any info on KSNI in relation to chromium and/or electron. Can you point me to any other discussions on this topic?

**Comment by andyrozman** [comment]
So like mentioned above, taskbar is no longer visible, but if you follow "mulvad" link you should be able to fix it.. 

So in short you need to fix: /usr/share/applications/teams-for-linux.desktop

And change Exec line to look like this:

`
Exec=env XDG_CURRENT_DESKTOP='' "/opt/teams-for-linux/teams-for-linux" %U
`

You might need to restart computer afterwards if it doesn't work at once. I tested this on Ubuntu 22.04 with Unity interface.

**Comment by IsmaelMartinez** [comment]
Thanks @andyrozman. Hopefully the latest version of electron fixes the issue, but I dunno when we will get it in here. Thanks again for providing a solution!

**Comment by IsmaelMartinez** [comment]
can you verify if this is still an issue using 1.4.1 an above? Closing to keep things tidy. Hopefully it is now sorted

**Comment by emotiv8it** [comment]
This is still an issue. The only version where it works is currently version 1.1.11 
All higher versions have this same issue...

**Comment by IsmaelMartinez** [comment]
unfortunately we can't fix it, as we depend on electron fixing it. apologies

**Comment by andyrozman** [comment]
Can't you just fix the .desktop file that is supplied with the application.
It wouldn't be fixed, but it would still work...

Andy
