### ISSUE TITLE
Teams shortcuts

### ISSUE THREAD

**Issue by tawmoto** [IsmaelMartinez/teams-for-linux#938]
Hi, it would be nice to have Teams original shortcuts, for example ctr+1, ctr+2, ctr+2 to switch between Notifications/Chat/Teams.
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/35702340/55e9823c-5703-4b22-a5cb-75e8865a0cc1)

**Comment by IsmaelMartinez** [comment]
Hi @tawmoto , this client uses the browser shortcuts.  

If you go to ... and the Key shortcuts you will find the ones Microsoft provides. 
<img width="237" alt="image" src="https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/daf86940-0c19-4915-9767-3b9ccf3006ec">

Thanks

**Comment by jijojosephk** [comment]
@tawmoto like @IsmaelMartinez mentioned, it uses browser version shortcuts and it works. Hence closing this.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/209cb516-0654-4dc1-b5ea-5f478ca053f5)
