### ISSUE TITLE
Font colors are greyish and small instead of black on the left toolbar

### ISSUE THREAD

**Issue by tawmoto** [IsmaelMartinez/teams-for-linux#939]
Hi, fonts look a bit strange on Xubuntu 22.04, it's grey, in smaller size and a bit hard to read. Looks somehow "disabled"
In the original Teams they are black and a bit bigger (seems +1)

Here is a comparision, thanks
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/35702340/0d555be3-905f-4dbc-b370-dc4a4513ac9d)

**Comment by IsmaelMartinez** [comment]
That is strange as I can see the right tone on my computer (but using MacOS) I suspect is something to do with your installation and/or OS configuration. Lets see if others has this problem.

If you can use the template to fill issues, that would be great as saves us going back and forward asking questions about, what package are you using, version, etc.  Thanks

**Comment by tawmoto** [comment]
Sorry that I did not fill the template, I am on Xubuntu 22.04, Numix theme.
I am using the version installed with "apt ", version 1.3.5

**Comment by tawmoto** [comment]
> That is strange as I can see the right tone on my computer (but using MacOS) I suspect is something to do with your installation and/or OS configuration. Lets see if others has this problem.
> 
> If you can use the template to fill issues, that would be great as saves us going back and forward asking questions about, what package are you using, version, etc. Thanks

I tested version 1.1.11 and it looks great, almost exactly like MS one.
So it's not my installation and OS configuration, it's more Electron thing, dunno.

**Comment by IsmaelMartinez** [comment]
So this is an issue with the electron version, and I suspect it will be fixed next time we do an electron upgrade. @jijojosephk , do you remember why we didn't do the last electron upgrade ? I believe it broke something but I was on holidays so just saw it going out and been reverted. Thanks!

**Comment by jijojosephk** [comment]
@IsmaelMartinez We did upgrade to version `25.x.x` but there were many issues we had to go back to `24.x.x`

**Comment by IsmaelMartinez** [comment]
can you verify if this is still an issue using 1.4.1 an above? Closing to keep things tidy. Hopefully it is now sorted
