### ISSUE TITLE
Share screen error

### ISSUE THREAD

**Issue by jerome-cui** [IsmaelMartinez/teams-for-linux#943]
**Describe the bug**
When I tried to share screen, a popup window with title 'type of source' appears but all character are boxes and nothing happens if I click any button. With teams web app I could do share screen successfully.

**To Reproduce**
1. In voice call
2. click share screen

**Screenshots**
![Screenshot_20230829_085429](https://github.com/IsmaelMartinez/teams-for-linux/assets/3302222/93f0b9d9-493e-4c40-9a41-8b3cd31ac5de)

**Desktop (please complete the following information):**
 - OS: Kubuntu 23.04
 - KDE: 5.27.7
 - Graphics platform: Wayland
 - Teams version: 1.3.8

**Comment by IsmaelMartinez** [comment]
It is probably related to OS installation and/or configuration. 

Check https://github.com/IsmaelMartinez/teams-for-linux/issues/865 and https://github.com/IsmaelMartinez/teams-for-linux/issues/467, and/or try https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632002149

Hope helps!

**Comment by benyaminl** [comment]
@IsmaelMartinez seems it's not the same errors. I will try download the deb first.

**Comment by jerome-cui** [comment]
> It is probably related to OS installation and/or configuration.
> 
> Check #865 and #467, and/or try [#357 (comment)](https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632002149)
> 
> Hope helps!

That does resolve the 'character in box' issue, but I still can't share screen, with the error in image below

![Screenshot_20230902_072808](https://github.com/IsmaelMartinez/teams-for-linux/assets/3302222/45b0ae4f-fa13-41c1-9067-f4fe45e0789e)

**Comment by IsmaelMartinez** [comment]
Can you check with version 1.1.11? That was the last one before the electron upgrade (1.2.0).

If that works then we know it is the electron upgrade and where to look. Thanks

**Comment by benyaminl** [comment]
> Can you check with version 1.1.11? That was the last one before the electron upgrade (1.2.0).
> 
> If that works then we know it is the electron upgrade and where to look. Thanks

https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.1.11

Yeah as you suspect, it works with share screen 
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/2817332/30291bc5-b2a5-41f4-9e96-24aa98251102)

This is quite strange, but, does version 1.1.11 have known issue that fixed with after release? It's quite troublesome I seen

**Comment by jijojosephk** [comment]
I'm not sure whom to blame for. Is it `wayland` or specific distributions or even `chromium` or `electron`. The trouble we have is the `wayland` related issues vary from disto to distro. Make sure you don't set the `userAgent` parameter. App will automatically set based on the `chromium/electron` version.

**Comment by jerome-cui** [comment]
> > Can you check with version 1.1.11? That was the last one before the electron upgrade (1.2.0).
> > If that works then we know it is the electron upgrade and where to look. Thanks
> 
> https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.1.11
> 
> Yeah as you suspect, it works with share screen ![image](https://user-images.githubusercontent.com/2817332/265160364-30291bc5-b2a5-41f4-9e96-24aa98251102.png) ![image](https://user-images.githubusercontent.com/2817332/265161015-3be166f5-14b6-47cc-9170-0f9b8fae56c2.png)
> 
> This is quite strange, but, does version 1.1.11 have known issue that fixed with after release? It's quite troublesome I seen (Chrome 106)
> 
> Strangely V1.3.7 works.. what kind of sorcery is this...
> 
> 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.204 Safari/537.36'
> 
> I will double check and try again the appImage. I guess that it's permission Issue with snap/deb. Hmm..

I have tried deb version, not works too.

**Comment by benyaminl** [comment]
Could you share more detail of the log using right t click on the icon
teams, and debug. Then export the log or run via cli to look if there any
error dumped




Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium

**Comment by ijaouani** [comment]
Hello, I'm also facing this issue.

Screen sharing is working when using offical PWA in Chrome for example but not when using teams-for-linux :

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/27200712/4958dbc5-1c59-486c-9a9c-61c455204536)

Platform:
- Ubuntu 22.04 LTS
- Wayland (by default on Ubuntu)
- Snap version 1.3.6

**Comment by jijojosephk** [comment]
Check if snap has camera permission

**Comment by ijaouani** [comment]
Already did. The camera itself works well. It's the share that is failing.

Permissions :

```
sudo snap connections teams-for-linux
Interface                 Plug                                     Slot                             Notes
audio-playback            teams-for-linux:audio-playback           :audio-playback                  -
audio-record              teams-for-linux:audio-record             -                                -
browser-support           teams-for-linux:browser-support          :browser-support                 -
camera                    teams-for-linux:camera                   :camera                          -
content[gnome-3-28-1804]  teams-for-linux:gnome-3-28-1804          gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     teams-for-linux:gtk-3-themes             gtk-common-themes:gtk-3-themes   -
content[icon-themes]      teams-for-linux:icon-themes              gtk-common-themes:icon-themes    -
content[sound-themes]     teams-for-linux:sound-themes             gtk-common-themes:sound-themes   -
desktop                   teams-for-linux:desktop                  :desktop                         -
desktop-legacy            teams-for-linux:desktop-legacy           :desktop-legacy                  -
gsettings                 teams-for-linux:gsettings                :gsettings                       -
hardware-observe          teams-for-linux:hardware-observe         -                                -
home                      teams-for-linux:home                     :home                            -
network                   teams-for-linux:network                  :network                         -
network-bind              teams-for-linux:network-bind             :network-bind                    -
network-manager-observe   teams-for-linux:network-manager-observe  -                                -
opengl                    teams-for-linux:opengl                   :opengl                          -
pulseaudio                teams-for-linux:pulseaudio               :pulseaudio                      -
screen-inhibit-control    teams-for-linux:screen-inhibit-control   :screen-inhibit-control          -
system-observe            teams-for-linux:system-observe           -                                -
unity7                    teams-for-linux:unity7                   :unity7                          -
upower-observe            teams-for-linux:upower-observe           :upower-observe                  -
wayland                   teams-for-linux:wayland                  :wayland                         -
x11                       teams-for-linux:x11                      :x11                             -
```

**Comment by jijojosephk** [comment]
The screenshot said camera isn't working that's why

**Comment by ijaouani** [comment]
> > It is probably related to OS installation and/or configuration.
> > Check #865 and #467, and/or try [#357 (comment)](https://github.com/IsmaelMartinez/teams-for-linux/issues/357#issuecomment-632002149)
> > Hope helps!
> 
> That does solve the 'character in box' issue, but I still can't share screen, with the error in image below
> 
> ![Screenshot_20230902_072808](https://user-images.githubusercontent.com/3302222/265143714-45b0ae4f-fa13-41c1-9067-f4fe45e0789e.png)

Im basically reproducing this.

**Comment by jerome-cui** [comment]
I found that share screen works in version 1.3.11. 
Great works! Thanks you!!!
