### ISSUE TITLE
Custom video background option disappeared

### ISSUE THREAD

**Issue by sbmueller** [IsmaelMartinez/teams-for-linux#949]
**Describe the bug**
Adding custom camera background images option missing.
A few weeks ago, when selecting a background in a video call, besides the default Teams backgrounds there was a "+" tile which allowed to select custom images as background. That option was there for a few weeks and now disappeared again. Do you have any idea why? 

**To Reproduce**
1. Join a video call
2. Click on "Background Effects"
3. Search for "+" tile (which is not there)

**Expected behavior**
There is a "+" tile which allows selecting a custom image from the file system as video background.

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/7465688/24235a03-29e1-4f13-bc0f-624e076e31f7)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Installation package deb
 - Version 1.3.8

**Comment by IsmaelMartinez** [comment]
duplicated with #950
