### ISSUE TITLE
Custom video background option disappeared

### ISSUE THREAD

**Issue by sbmueller** [IsmaelMartinez/teams-for-linux#950]
**Describe the bug**
Adding custom camera background images option missing.
A few weeks ago, when selecting a background in a video call, besides the default Teams backgrounds there was a "+" tile which allowed to select custom images as background. That option was there for a few weeks and now disappeared again. Do you have any idea why? 

**To Reproduce**
1. Join a video call
2. Click on "Background filters"
3. Search for "+" tile (which is not there)

**Expected behavior**
There is a "+" tile which allows selecting a custom image from the file system as video background.

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/7465688/24235a03-29e1-4f13-bc0f-624e076e31f7)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Installation package deb
 - Version 1.3.8

**Comment by hyegeek** [comment]
This is also true under gentoo. No update to the teams-for-linux software, so this might be something on Microsoft's end.

**Comment by IsmaelMartinez** [comment]
I am afraid this is another Microsoft change. Worth asking on their feedback portal:

https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

If you ask it and put a link in here, other users might be able to keep track of it.

**Comment by jonatasrs** [comment]
Any news on this. I have the same problem.

AppImage package
OS: Debian Sid
Desktop: Sway
Version: 1.3.11

**Comment by hyegeek** [comment]
News seems unlikely as Microsoft has no particular reason to make Linux particularly usable.

That said, if you need this feature, check out obs-studio and create a virtual camera. Teams uses the virtual camera without issue. Now I have custom animated backgrounds.

**Comment by IsmaelMartinez** [comment]
can you verify if this is still an issue using 1.4.1 an above? Closing to keep things tidy. Hopefully it is now sorted
