### ISSUE TITLE
Secondary ringing device

### ISSUE THREAD

**Issue by Flofler** [IsmaelMartinez/teams-for-linux#957]
**Is your feature request related to a problem? Please describe.**
I have a bluetooth headset and it turns off when not using it. So I don't get any acoustic notifications when getting a call.

**Describe the solution you'd like**
So it would be nice if I could configure a second audio device just for ringing. But I'm not sure if this is even possible.

**Comment by IsmaelMartinez** [comment]
I think this might be a bit tricky to implement. We are only wrapping around the webpage.

**Comment by storm49152** [comment]
I see. I hate to hijack this thread, but I think it is related. Is it also hard to make it possible to _always_ be able to change the input/output audio device, instead of only when Teams is using it?

I'm on Fedora 38 + KDE Plasma. I don't know how this works for others, but I can only change the audio device when an application (not just Teams) is actually using it. But that means for Teams that I cannot change the audio device when e.g. I go to another room and want to be notified via the speaker set instead of the headset.

**Comment by karloff10** [comment]
Maybe it is possible to indicate incoming calls in a new child window?
Currently it is a kind of a popup inside the main window.
If the call is inside another window with an different WM_NAME or WM_CLASS, it maybe would be possible to add some logic from the running window manager, which could be used for a better notification.

**Comment by IsmaelMartinez** [comment]
Hi,

I am not sure if you can maybe try with the Pre-release 1.3.21:

https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.21

I have created also a discussion page in https://github.com/IsmaelMartinez/teams-for-linux/discussions/1019

Thanks again!

**Comment by Flofler** [comment]
Hi,

thank you so much. It works very well :)

**Comment by IsmaelMartinez** [comment]
Can't you not kill before run? In the script

**Comment by Flofler** [comment]
Hey @IsmaelMartinez Sorry for my late response. Yes, I can kill it before run, but this does not solve the problem. If the person which calls me does hang up before my answer, none of the 2 events "incoming-call-connecting","incoming-call-disconnecting" is called. That means the variable "incomingCallCommandProcess" in index.js won't be set to null and therefore the script won't be started anymore for the next call.

What we need is probably another event when the incoming call is not answered at all. But I'm not sure if this is possible. 

Another idea is to look up if the spawned process is still running instead of only testing if "incomingCallCommandProcess" is null.

I would do it myself but I'm not sure if my javascript knowledge is good enough for this.

**Comment by IsmaelMartinez** [comment]
Can you put the script in here? someone might have come up with an alternative script.

Maybe we need to tweak this part of the code https://github.com/IsmaelMartinez/teams-for-linux/blob/82f7d6de52038b77bd9fd2e1c307104fe1bea946/app/mainAppWindow/index.js#L515 to kill the process each time, but that depends on how many times we get that event. 

something like:

```
async function handleOnIncomingCallCreated() {
        incomingCallCommandKill()
	if (config.incomingCallCommand) {
		let commandParts = config.incomingCallCommand.match(commandSplitRegex);
		incomingCallCommandProcess = spawn(commandParts.shift(), commandParts);
	}
}
```

**Comment by IsmaelMartinez** [comment]
version 1.3.27 now terminates the command running before starting it again. Your issue should be, in theory, fixed

**Comment by Flofler** [comment]
Thank you very much. I will test this tomorrow!

**Comment by Flofler** [comment]
Sorry, I forgot to respond to you. Everything works fine now. Thank you very much.
