### ISSUE TITLE
unable to add apt repo

### ISSUE THREAD

**Issue by coolian1337** [IsmaelMartinez/teams-for-linux#962]
I attempted it using the commands given in this repository however the path (/etc/apt/keyrings) doesnt exist so i got an error about it from wget. then i found a keyrings directory (/usr/share/keyrings) using the find command, then i replaced paths in the command leading to the missing with this new path but it still doesnt work. when doing apt update i get
```
Err:19 https://repo.teamsforlinux.de/debian stable InRelease
  Unknown error executing apt-key
```
and a bit later
```
W: GPG error: https://repo.teamsforlinux.de/debian stable InRelease: Unknown error executing apt-key
E: The repository 'https://repo.teamsforlinux.de/debian stable InRelease' is not signed.
```

I am on ubuntu Ubuntu 20.04.6 LTS

**Comment by jijojosephk** [comment]
@nils could you please help?

**Comment by epagone** [comment]
Works for me with the path modification suggested by @coolian1337 .
```bash
$ sudo wget -qO /usr/share/keyrings/teams-for-linux.asc /usr/share/keyrings/teams-for-linux.asc https://repo.teamsforlinux.de/teams-for-linux.asc
$ echo "deb [signed-by=/usr/share/keyrings/teams-for-linux.asc arch=$(dpkg --print-architecture)] https://repo.teamsforlinux.de/debian/ stable main" | sudo tee /etc/apt/sources.list.d/teams-for-linux-packages.list
$ sudo apt update
```
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

**Comment by coolian1337** [comment]
those exact commands produce the same errors i described
![Screenshot from 2023-10-04 09-40-09](https://github.com/IsmaelMartinez/teams-for-linux/assets/31437161/9313e7a2-3247-4d61-9739-1da928e8c400)

**Comment by IsmaelMartinez** [comment]
That do look like a key error. I would check if keyrings is working, the key is configured in there, assuming the key is valid. 

As an alternative, and if you just need to get it working, you can download the deb package and subscribe to the notifications in github. Not the best but at least you can still use the app. 

Sorry for not been able to help more. Work uses now MacOS.
