### ISSUE TITLE
Actual teams-for-linux-<VERSION>.AppImage doesn't have any update information

### ISSUE THREAD

**Issue by althaser** [IsmaelMartinez/teams-for-linux#967]
Currently the package **teams-for-linux-<VERSION>.AppImage** doesn't have any update information.

For instance:
```
$ ./appimageupdatetool-x86_64.AppImage -j teams-for-linux-1.3.12.AppImage
Could not find update information in the AppImage. Please contact the author of the AppImage and ask them to embed update information.
Error checking for changes!

$ ./appimageupdatetool-x86_64.AppImage -d teams-for-linux-1.3.12.AppImage 
Parsing file: teams-for-linux-1.3.12.AppImage
AppImage type: 2
Raw update information: <empty>
Update information invalid: | not found
Failed to parse AppImage. See above for more information
```

it would be nice to have such update information to be able o update the AppImage automatically.

https://docs.appimage.org/packaging-guide/optional/updates.html#making-appimages-updateable

thanks

**Comment by IsmaelMartinez** [comment]
Hi, 

Fell free to open a PR if you have the time. 

I leave it open in case someone has capacity to investigate this further.

We use electron-builder, so It might be something to do with it's configuration. If I don't remember wrongly, all config for electron-builder is in the package.json file.

Hope helps!

**Comment by IsmaelMartinez** [comment]
Closing to keep things tidy.
