### ISSUE TITLE
No audio playback on arch Linux

### ISSUE THREAD

**Issue by user858753257** [IsmaelMartinez/teams-for-linux#969]
**Describe the bug**
 When logging in a meeting I have no audio (no beep beep / waiting tone etc..) 
When I'm in a meeting I don't hear others.

**To Reproduce**
1. Login into meeting 
2. when in camera preview screen or in meeting there is no sound.

**Expected behavior**
Have audio in all circumstances 

**Desktop (please complete the following information):**
 - OS: EndavorOS Arch Linux
 - Installation package: AuR repository 

**Additional context**
Laptop : Thinkpad T14S Gen1 wo the Jabra 380 audio receiver

**Comment by IsmaelMartinez** [comment]
Hi, 

Aur is managed in their repo. There is a link in the main readme. They should be able to give you a hand.

Otherwise check the closed issues to ensure this wasn't answered before. 

Hope helps!

**Comment by F3000** [comment]
@IsmaelMartinez  Ok . But the app should be the same or ?

What is your recommended method to install on arch ?

**Comment by IsmaelMartinez** [comment]
The app should be the same, whoever as arch is a DIY distro, you might be missing some audio modules/libraries. We aren't in charge of that packaging system (snap and others give us enough headaches)

If I was you, I will check previous releases and see if it is related to an electron upgrade. I dunno enough of arch to help much, apologies, but the arch community should be able to help. 

I would recommend giving them more details logs.

**Comment by IsmaelMartinez** [comment]
can you verify if this is still an issue using 1.4.1 an above? Closing to keep things tidy. Hopefully it is now sorted
