### ISSUE TITLE
Many channels are empty when running with "yarn start"

### ISSUE THREAD

**Issue by jsteel44** [IsmaelMartinez/teams-for-linux#97]
**Describe the bug**
I've been running with "yarn start" to get the spell checking working for some time, but just recently I've noticed a lot of my channels are empty. I've deleted my .config/teams-for-linux but it didn't help, and after restarting teams-for-linux that directory isn't created, so I wonder if running via "yarn start" doesn't use that directory.

**To Reproduce**
1. Notice channels are emtpy
2. Close teams-for-linux
3. Delete ~/.confg/teams-for-linux (if it's there)
4. Open teams-for-linux

**Expected behavior**
Channel history should return

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Installation package: source
 - Version 0.1.18

**Additional context**
Hopefully it's just a case of clearing the cache somehow but I cannot see where that may be. Thanks

**Comment by IsmaelMartinez** [comment]
Hi,

When running from source the config folder is located under `~/.Electron`

Try removing that folder (or renaming it if you run other apps from source).

Let me know how you get on with it.

**Comment by jsteel44** [comment]
Thanks for your reply. Unfortunately I have no ~/.Electron directory. I have a ~/.electron-gyp directory but closing teams, deleting that and re-launching doesn't help I'm afraid.

**Comment by IsmaelMartinez** [comment]
probably just add a console.log(configPath) in this line and start again, that should tell you what folder to clean-up ;)

https://github.com/IsmaelMartinez/teams-for-linux/blob/master/app/config/index.js#L5

**Comment by jsteel44** [comment]
Ah thanks, it was .confg/Electron. Deleted and it's fine now, thanks for your help!
