### ISSUE TITLE
Unable to use Security Key to sign in

### ISSUE THREAD

**Issue by elestedt** [IsmaelMartinez/teams-for-linux#972]
**Describe the bug**
When signing in to teams using security key the dialog that's supposed to open never does

**To Reproduce**
1. Open a fresh installation (tried both AppImage and deb installs)
2. Click on 'Sign-in options'
3. Select 'Sign in with a security key'
5. In deb install it's a never ending loading, for AppImage it failed after a few seconds.

**Expected behavior**
Popup to enter pin code and proceed with the login

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package deb & AppImage
 - Version 1.3.13

**Comment by IsmaelMartinez** [comment]
There have been similar requests in the past. Worth having a wee browse through the closed issues.

**Comment by elestedt** [comment]
Then it might be time to reopen that https://github.com/electron/electron/issues/24573

**Comment by IsmaelMartinez** [comment]
have you check https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/certificate/README.md 
 ? Might be completely unrelated but thought worth sharing.

**Comment by IsmaelMartinez** [comment]
closing due inactivity
