### ISSUE TITLE
Open chat, teams and meetings in separate windows.

### ISSUE THREAD

**Issue by jkrysakowski** [IsmaelMartinez/teams-for-linux#973]
Switching between tabs kills productivity. I know that's how microsoft designed it, but the question is if it's possible to hack it somehow to open tabs like chat, team channels and current meeting in separate windows?

**Comment by jijojosephk** [comment]
It's very difficult. Only MS can do something.

**Comment by IsmaelMartinez** [comment]
You will need to ask Microsoft to implement this in the browser version. Closing as we can't implement
