### ISSUE TITLE
access to microsoft's echo bot

### ISSUE THREAD

**Issue by karlkleinpaste** [IsmaelMartinez/teams-for-linux#975]
**Is your feature request related to a problem?**
In the old world of original Teams from Microsoft itself, there was an audio echo service available via settings, by which one could test audio. The bot would say a few sentences, then wait for the user to speak for a few seconds, then play back whatever was recorded. Access to the echo service would be welcome.

**Describe the solution you'd like**
A means to reach Microsoft's echo service. For example, there doesn't seem to be a way to search for this pseudo-user.

**Describe alternatives you've considered**
Currently, the only way to test audio is to start a conversation with another human, which is rather an imposition for personal testing purposes.

**Comment by jijojosephk** [comment]
Seems impossible. We're dependant on Microsoft.
