### ISSUE TITLE
[Bug] ? Takes HTML file association

### ISSUE THREAD

**Issue by awilkins** [IsmaelMartinez/teams-for-linux#976]
**Describe the bug**

Installed teams-for-linux as snap on Ubuntu 20.04

Replied "yes" to the dialog about the protocol handler.

Now when I use the help option in LibreOffice (either through the menu or pressing F1), Teams opens instead.

**Expected behavior**

F1 opens the help in LibreOffice

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Installation package : snap
 - Version 1.3.13

**Additional context**

Has the application accidentally (or intentionally) become the handler for `mshelp://` URLs?

**Comment by jijojosephk** [comment]
It uses `msteams`

**Comment by awilkins** [comment]
Ah, yeah, it may be because it's taken the .html file association.

.. yeah, confirmed, after setting it back to a browser, LibreOffice help works fine again.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/368399/0044539c-e807-404f-99dc-bacf49aa579d)
