### ISSUE TITLE
Control during screen sharing not available

### ISSUE THREAD

**Issue by Burneygamble** [IsmaelMartinez/teams-for-linux#977]
When a user is sharing the screen with me, they can't grant me control, neither is available on my side a button to "request control".

I'm using Ubuntu 22.04.

Thanks

**Comment by jijojosephk** [comment]
This is controlled by Microsoft. I don't think we can do much about it.

**Comment by jijojosephk** [comment]
You may join the chat room here https://matrix.to/#/#teams-for-linux_community:gitter.im

some questions can be answered by the members there.

**Comment by IsmaelMartinez** [comment]
You will need to ask Microsoft for this feature to be available on the browser version. Closing as we can't implement it. Apologies

**Comment by raul-klg** [comment]
I have always asked about this in the past and I fully agree with the point in closing. BTW, if someone is aware about this being reported to M$ or somewhere where the issue can be tracked there I would appreciate the pointer. Thanks

**Comment by azrdev** [comment]
Apparently controlling shared screens works now (at least on the "official" PWA client, version 1415/24120100213 ) -- i just used it

**Comment by IsmaelMartinez** [comment]
If it works on the pwa, we might get it here. Takes a few weeks for some features to reach all users

**Comment by mbanck-cd** [comment]
Shouldn't this (or one of the duplicate) issues be reopened now that it seems theoretically possible to have it?

**Comment by IsmaelMartinez** [comment]
Still not possible between browsers. If one has a desktop client then you can take control but they can take it back form you (as far as I know)

**Comment by mbanck-cd** [comment]
Ah I see - I was under the impression that there would be more work needed to make it work between this project and somebody with a desktop client. If that works right now and browser-to-browser is not possible without further changes upstream, then sure, this issue should stay closed.
