### ISSUE TITLE
Add support for Governement-Secured MS Teams

### ISSUE THREAD

**Issue by Maltergate** [IsmaelMartinez/teams-for-linux#978]
**Describe the solution you'd like**
When working in sensible areas, that are subject to ITAR regulations (such as a rocket company), they use a governement-based MS teams. This version of teams is a somewhat more secure version of the classical one. The URL for access is gov.teams.microsoft.us

**Describe alternatives you've considered**
I'm currently using the Edge Webapp, which works fine.

This feature request has the lowest priority. More a nice-to-have feature rather than something that will really expand the user base. I thought like suggesting it, leaving it to the maintainer to decide :smile: .

Keep up the awesome work!

**Comment by jijojosephk** [comment]
You can try with `--url` param from command line. This will override the default `https://teams.microsoft.com`. If you don't want command line parameters, you may use a config file called `config.json`, Please have a look at the configuration documentation [here](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md)

**Comment by jijojosephk** [comment]
You may join the chat room here: https://matrix.to/#/#teams-for-linux_community:gitter.im

**Comment by Maltergate** [comment]
It works like a charm.

Thank you
