### ISSUE TITLE
Blank screen (404) on Ubuntu 22.04

### ISSUE THREAD

**Issue by mauriziopinotti** [IsmaelMartinez/teams-for-linux#981]
**Describe the bug**
Version 1.3.14 doesn't work on Ubuntu 22.04, the screen just stays blank and the console shows:
```
$ teams-for-linux 
[ERROR] Server returned error code '404'
[2071771:1018/094436.347976:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
```

I also tried clearing the cache and removing the config folder but nothing helps.
Also, `teams-for-linux --webDebug true` doesn't do anything.

**To Reproduce**
1. Run the app
2. See error

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/4000539/d46662e3-d360-4bf3-ba7f-0097bc4da2c9)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - Installation package: deb
 - Version: 1.3.14

**Comment by jijojosephk** [comment]
Thanks for reporting and looking into the `pre-release`. Is it `wayland` or `xorg` ?

**Comment by mauriziopinotti** [comment]
X11 and gnome shell:

```
$ echo $XDG_SESSION_TYPE
x11
$ dpkg -l | grep gnome-shell
ii  gnome-shell                                                 42.9-0ubuntu2                           amd64        graphical shell for the GNOME desktop
```

**Comment by jijojosephk** [comment]
Can you try removing `GPUCache` folder as well?

**Comment by mauriziopinotti** [comment]
I actually removed the `~/.config/teams-for-linux` folder altogether, so `GPUCache` is gone as well.
Also tried removing `~/.config/Electron`, which has a `GPUCache` folder too... didn't help.

**Comment by jijojosephk** [comment]
This is mine. How about yours? I face no problem with the build. We'll figure out what's causing.
```
OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 6.2.0-34-generic
DE: GNOME 42.9
WM: Mutter
```

**Comment by mauriziopinotti** [comment]
I have

```
OS: Ubuntu 22.04.3 LTS x86_64
Kernel: 5.15.0-86-generic
DE: GNOME 42.9-0ubuntu2
WM: Mutter 42.9-0ubuntu5
SM: X11
```

and it does not work.

On another laptop I have

```
OS: Ubuntu 23.10 x86_64
Kernel: 6.5.0.9-generic
DE: GNOME 45.0-1ubuntu2
WM: Mutter 45.0-2ubuntu1
SM: Wayland
```

here it works, although the 404 error I've mentioned in the issue description is still present, so I guess that's not the root cause of the error.

I will try to dig deeper to understand if it's an issue of my specific setup.

**Comment by mauriziopinotti** [comment]
Also, same issue cloning the project and running with `yarn start` from `develop` branch.

**Comment by mauriziopinotti** [comment]
For the sake of curiosity: starting electron with `--disable-gpu` flag shows some progress: the title changes to "Waiting for connection" and "Checking credentials" but the content window is still blank.

**Comment by mauriziopinotti** [comment]
Nailed it! This works:

```javascript
	app.commandLine.appendSwitch('disable-gpu');
	app.commandLine.appendSwitch('disable-software-rasterizer');
```

PR submitted.
