### ISSUE TITLE
USB camera lost during call

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#982]
If I use the USB camera on my machine, it can happen within a call, that the image freezes or - even worse -the camera is lost completely. Anyone else encountering this problem?

**Comment by jijojosephk** [comment]
Can you report the version please?

**Comment by elhennig** [comment]
Ups, sorry! It is the AppImage 1.3.13
Today with 1.3.14 it was ok today for an hour lasting call.

**Comment by jijojosephk** [comment]
We're facing more issue with sandboxed versions like `appImage`, `snap`, `flatpak`, though they're to be addressed, we're not finding time to do so. I find `flatpak` generally working fine. I suggest to use native packages. `1.3.14` is pre-release. Kindly test it.

You may join the chat room: https://matrix.to/#/#teams-for-linux_community:gitter.im

We can have some quick discussions.

**Comment by jijojosephk** [comment]
@elhennig I assume things are ok and would close it.
