### ISSUE TITLE
3rd party app integration is not working as expected; example Jira integration

### ISSUE THREAD

**Issue by holle** [IsmaelMartinez/teams-for-linux#983]
**Describe the bug**
When attempting to copy/transfer the contents of a chat to a Jira ticket it is possible to use a Jira plugin for MS Teams.
This requires a session token to be generated for the current Teams window to be able to make the appropriate REST API Calls against the selected Jira instance.
In order to do so MS Teams will trigger the "system web browser" where you can login using your MS Account.
The token will then be passed back to MS Teams and subsequent calls will use this token until it expires.

**To Reproduce**
1. Connect MS Teams with a Jira (Server/DC in our case) instance (done by our admin so I am doing a wild guess here) using this Jira app: https://marketplace.atlassian.com/apps/1217836/microsoft-teams-for-jira?tab=overview&hosting=datacenter and the documented MS Teams App as well
2. Configure your personal account by obtaining the "Jira Server ID" (a guid) from your MS Teams admin
3. Click on the context menu item "..." -> "More Actions" -> "Create Comment" (or "Create Issue")
4. You may be prompted with a field requesting the above "Jira Server ID" from step 2
5. You will be asked to authenticate by clicking on a button "Sign in with Microsoft account" (sometimes needs to be triggered twice)
6. This opens a Tab/Window in your "system web browser" pointing to "https://jira-server.msteams-atlassian.com/login.html"
7. After a successful authentication the generated session token will be passed (should be passed) back to the MS Teams window
8. The dialog does not switch to the "next" page and simply keeps on displaying the "Sign in with Microsoft account" button

**Expected behavior**
You are able to reproduce this buy using the MS Teams Chrome PWA, this triggers a google chrome window from "itself" and that seems to work:
1. Connect MS Teams with a Jira (Server/DC in our case) instance (done by our admin so I am doing a wild guess here) using this Jira app: https://marketplace.atlassian.com/apps/1217836/microsoft-teams-for-jira?tab=overview&hosting=datacenter and the documented MS Teams App as well
2. Configure your personal account by obtaining the "Jira Server ID" (a guid) from your MS Teams admin
3. Click on the context menu item "..." -> "More Actions" -> "Create Comment" (or "Create Issue")
4. You may be prompted with a field requesting the above "Jira Server ID" from step 2
5. You will be asked to authenticate by clicking on a button "Sign in with Microsoft account" (sometimes needs to be triggered twice)
6. This opens a Tab/Window in your "system web browser" pointing to "https://jira-server.msteams-atlassian.com/login.html"
7. After a successful authentication the generated session token will be passed (should be passed) back to the MS Teams window
8. A search dialog for Jira Issues or a create issue dialog should appear.
9. You are able to fill in the form an submit the text to either an existing or a new Jira ticket

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Installation package rpm
 - Version 1.13.3

**Additional context**

**Comment by jijojosephk** [comment]
> Hi @jijojosephk,
> 
> thanks, that actually worked 🥇 Is that documented somewhere or do I need to know this ❓ 😁
> 
> I will go ahead and close this ticket, thanks for your help

Glad to know it worked! Sorry, it is not documented anywhere. It was done as part of a feature request #695. This must be there in the readme. I'll have it updated sometime soon.

**Comment by holle** [comment]
@jijojosephk 

Don't worry, you made my day!
