### ISSUE TITLE
Missing notification icon

### ISSUE THREAD

**Issue by NeilsC** [IsmaelMartinez/teams-for-linux#984]
**Describe the bug**
There is no notification icon visible in the desktop environment.

**To Reproduce**
1. Start "Teams for Linux" using the application launcher.
2. Application starts as expected
3. Observe that there is no notification icon displayed in the notification area.

**Expected behavior**
Notification icon appears in the notification area.

**Screenshots**
Notification area:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/1214412/0e940e60-7681-44fb-ab79-c63fffd37172)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Desktop Environment: Xfce 4.18
 - Installation package: deb (from APT repository)
 - Version: 1.3.13

**Comment by jijojosephk** [comment]
It's partly due to your desktop environment and partly due to `chromium` and `electron` dropped support for legacy icons. Can you try if this thread helps ? https://github.com/mullvad/mullvadvpn-app/issues/4861

**Comment by jijojosephk** [comment]
But I can see the icon. I quickly ran a VM `Xubuntu 23.10`

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/de0906f0-b322-450e-a736-e9e36e9e5033)

**Comment by NeilsC** [comment]
That's interesting that it's working in Xubuntu. I'm running on Ubuntu, where I installed XFCE separately, so there must be some differences between the two. I will try to figure out what the difference is.

I did try the fix from the Mullvad issue, with no luck.

Thanks for your time.

**Comment by jijojosephk** [comment]
Thanks @NeilsC you may update here when you have a resolution. Probably something with `libappindicator` not sure though.
