### ISSUE TITLE
Enhance zooming in and out controls

### ISSUE THREAD

**Issue by mahmoudbahaa** [IsmaelMartinez/teams-for-linux#987]
1. Since zooming in is `ctrl` and `+` key and `+` needs `shift` on many keyboard layouts so it make effectively` ctrl` + `shift` + `+` key for zoom in but only `ctrl` in case of zoom out. need to be consistent and make it work with or without `shift` like in real browsers
2. When reaching zoom limits (min or max) it visually stop zooming in/out but the actual zoom level keep on decreasing/increasing make it hard to recover from it unless you press `ctrl` + `0` or press the corresponding opposite key multiple times. so need to stop the zoom level when reaching the min/max
3. Add mouse wheel support for zooming in and out

**Comment by harridu** [comment]
Having zoom in and out via scroll wheel would be a highly appreciated improvement.

**Comment by IsmaelMartinez** [comment]
Hi @harridu , are you able to test the PR @mahmoudbahaa created in here? https://github.com/IsmaelMartinez/teams-for-linux/pull/988 I got a mac from work now so my work helping on this is... limited.

**Comment by harridu** [comment]
I'd love to help, but I haven't found a new binary on github yet. There is no build guideline, either. How can I build the improved version?

**Comment by IsmaelMartinez** [comment]
The info on how to build it from source should be in the [CONTRIBUTORS.md ](https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/CONTRIBUTING.md) file. If you can't manage to do it, I can try to create a per-release. 

@mahmoudbahaa made some changes but I am not sure if it is a WIP or a finish solution.

**Comment by harridu** [comment]
That was easy. I have applied the patch de05e34d054c296a72c99a6aea4a408c2ba852d1 to befound on @mahmoudbahaa outlook-for-linux project to the develop branch and gave it a try (on Debian 12): Zooming in and out with the scroll wheel seems to work. The old way (Ctrl-+ and Ctrl--) still worked.

**Comment by IsmaelMartinez** [comment]
I will give another day to the pre-release that is currently open, and then create a pre-release for this one. Just to ensure we aren't breaking functionality. Thanks for testing!

**Comment by IsmaelMartinez** [comment]
Created a pre-release in here https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.3.22 .If no-one complains, I will release it early next week. Thanks again!
