### ISSUE TITLE
The snap package installation shows a different cursor in the application

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#99]
**Describe the bug**
The application shows a different cursor than the system default when we install it through snap. It's working fine in .deb package. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open terminal.
2. Install teams-for-linux through beta or edge channels.
3. Open teams-for-linux and login to your account.
4. Hover over the links in the application.

**Expected behavior**
Hovering over links should show system default cursor as we see in the web browsers.

**Screenshots**
The complete video of the testing. Which shows .deb installation as well as snap installations (edge, beta).
[teams-for-linux-snap-issue.zip](https://github.com/IsmaelMartinez/teams-for-linux/files/3058878/teams-for-linux-snap-issue.zip)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Package: snap
 - Version: 0.1.17 or 0.1.18

**Additional context**
Nil

**Comment by IsmaelMartinez** [comment]
Hi, I leave it with @julian-alarcon and @benyanke as they are the snap experts.

**Comment by IsmaelMartinez** [comment]
And, in the meantime, could you use the deb package? this might take a while to fix as we don't really have much time in our hands. (and I can't test it as every time I try to install a snap package I get quick out of the company network).

Alternatively, investigating the logs and see if other electron snap apps have the same problem can also help! (if you got the time).

Thanks for reporting the bug and apologies. I/we don't get paid for this work so sometimes life gets on the way!

**Comment by jijojosephk** [comment]
Absolutely yes @IsmaelMartinez, from today I'm using the deb package and it works well. I understand the challenge in the open source community. You're dong a great job when Microsoft Continuously ignore the Linux platform.

Regarding the electron apps, Do you remember any? with a snap package so that I can install and test it.

Have good day!

**Comment by jijojosephk** [comment]
@IsmaelMartinez your assumption is right. It's the problem with electron builds in snap. I confirmed this with an application called **electronplayer** (https://snapcraft.io/electronplayer) which is built on electron. Please see the test results in the attached video below:

[SnapCursorIssue.zip](https://github.com/IsmaelMartinez/teams-for-linux/files/3061920/SnapCursorIssue.zip)

There are a lot of people talking about this problem and the solution (https://github.com/onivim/oni/issues/2307#issuecomment-403482830) provided by @LeonB might work.

@julian-alarcon and @benyanke you may try the solution. I know you are really busy on other work so I'm trying to be your helping hand even though I know nothing about electron and snap :) Because I want this application to fly high. I'm having a work break to take care of our infant. So when she sleeps I'll get some time to google and help people like you.

**Until the issue is resolved you may mention this on the home screen and suggest people to use the .deb package because the cursor looks really weird in snap builds** 

Have a blessed day to all!

**Comment by IsmaelMartinez** [comment]
Enjoy the time with your infant! They grow really fast and start bossing around pretty soon. (I know it from experience). Thanks a lot for your help.

IMO having the issue open should be enough. Might be ok to put it in the known issues section (but I am not sure how many people gets that far)

For what I see, that ties up with other "build" work that @julian-alarcon and @benyanke are working on.

Thanks again!

**Comment by jijojosephk** [comment]
Thanks @IsmaelMartinez, children do grow fast. She's started crawling and picks up everything on her way :) 

You may mark it as known issue. I guess @julian-alarcon and @benyanke should be able to fix that in the build.

Good day to all of you!

**Comment by IsmaelMartinez** [comment]
Can you check the edge channel? Thanks

**Comment by jijojosephk** [comment]
Sorry for the delayed response. I tested it, the issue persists.
Version: 0.2.1
Package: Snap (edge channel)
OS: Ubuntu 18.04 LTS.

**Comment by julian-alarcon** [comment]
Hi guys. Not so easy as you may think. I attach some doc about this.

https://forum.snapcraft.io/t/supporting-desktop-themes-via-the-content-interface/4122
https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
https://forum.snapcraft.io/t/desktop-improvements-report-and-plans/3510/1
https://forum.snapcraft.io/t/layouts-re-mapping-snap-directories/1471
https://forum.snapcraft.io/t/snap-layouts/7207/1

I will keep checking how can this be made.

**Comment by IsmaelMartinez** [comment]
I am surprise that electron-builder doesn't deal with this issue... maybe worth checking in their "issues"

**Comment by jijojosephk** [comment]
@julian-alarcon @IsmaelMartinez @benyanke 

Sorry friends, I'm on vacation that's why the delay in my responses. As it's a problem with the builder. Let's not break hour heads to fix it. Leave this issue here and let's focus on other issues and improvements we can make.

Shall we look at the possibility of having a PPA for Ubuntu based systems? At least a apt-get upgrade will have the latest version of app for the users. I don't think the theme issue will be attended anytime soon by electron. I don't know why they're not. The cursor looks really weird.

Meantime please let me know which other areas I can test the application. My responses will be slow as I'm on vacation, but I'll do my best to help you guys. I'll be much quicker after 5 days when I'm back from vacation.

Have a pleasant day to all.

**Comment by jijojosephk** [comment]
@julian-alarcon @IsmaelMartinez @benyanke Why don't we start a new group for chatting? Like Telegram?

**Comment by IsmaelMartinez** [comment]
Seems like electron builder 20.44 has a fix for this.

**Comment by IsmaelMartinez** [comment]
https://github.com/electron-userland/electron-builder/issues/3035#issuecomment-502153860

**Comment by IsmaelMartinez** [comment]
This branch has the builder with an updated version.
https://github.com/IsmaelMartinez/teams-for-linux/tree/feature/update-some-version-packages

@jijojosephk or any of you snap users, can you test it and see if that solves the issue? Thanks

**Comment by IsmaelMartinez** [comment]
PR created

**Comment by jijojosephk** [comment]
@IsmaelMartinez, I tested the "electronplayer" snap. I don't see that issue which had earlier. Have a look at this [comment](https://github.com/IsmaelMartinez/teams-for-linux/issues/99#issuecomment-481526056) above. So we can consider it as fixed in electron builder. Once you integrate it in the new build, it should be fixed.

**Comment by IsmaelMartinez** [comment]
merged to master to 0.3.3 should have it (edge to be pretty soon)

**Comment by jijojosephk** [comment]
@IsmaelMartinez  Oh yeah! I just tested 0.3.3 edge. It's fixed. Awesome!

**Comment by IsmaelMartinez** [comment]
> @julian-alarcon @IsmaelMartinez @benyanke Why don't we start a new group for chatting? Like Telegram?

Gitter account created:
https://gitter.im/teams-for-linux/community
