### ISSUE TITLE
[question] Am I supposed to select "use web app" after logging in? 

### ISSUE THREAD

**Issue by zilexa** [IsmaelMartinez/teams-for-linux#990]
After installing the Flatpak on Fedora, I can login to Teams.
But then I get the screen that says "install the app" or, in very tiny letters, "continue with the web version".

Is this normal? 
Because after I select the web version (which still opens in the same screen), go to calendar and try to join, nothing happens. Absolutely nothing..

**Comment by jijojosephk** [comment]
What happens when you do that?

**Comment by zilexa** [comment]
Do what?

**Comment by IsmaelMartinez** [comment]
What happens if you restart the app? The "continue with the web browser" is something I have seen in the pass, but mostly only on the 1st app start. 

If the calendar ain't working, can you try ctrl+click?

**Comment by zilexa** [comment]
In the end I stopped using the Flatpak version. It's just not clear how to use it.
I recommend making a very clear note that due to the design, users need to ignore the message and "continue in webbrowser" otherwise they will simply think something is wrong.

Additionally I was unable to open links in the app. No clue how to make that happen. 
I wish there was a way to drop copy/paste an URL in Teams. Zoom also doesn't have this options. 

Luckily, Teams nowadays seems to work well in Firefox. Having to do job interview, this saved me.

The only thing that almost messed up the interview: my laptop has Windows Hello. In Fedora 38, apparently it recognises 2 different webcams.
I saw my face in the preview, but when joining nobody saw me. Eventually after rejoining a couple of times I realised I could select a secondary camera in Settings, which was the actual webcam. Not some Hello IR sensor.

**Comment by IsmaelMartinez** [comment]
Sorry to hear about having troubles with it, specially during an interview. Hopefully the interview when well.

Flatpak (and snap) are a bit of a nightmare to use. When they work, they are great, but when they don't... 

Regarding the "continue in web browser", that is controlled by Microsoft. We have tried multiple times to work around it (by clicking in the button automatically, changing some settings, and others) but Microsoft do tend to change that page a lot, making it a continuously chasing situation.

**Comment by IsmaelMartinez** [comment]
Closing to keep things tidy and because we have limited options on this use case/problem
