### ISSUE TITLE
Screen sharing does not always consider window scaling

### ISSUE THREAD

**Issue by tervor** [IsmaelMartinez/teams-for-linux#993]
**Describe the bug**
I use Desktop scaling in Wayland (150%). Teams for Linux works fine with sharing my screen and also most windows. But, there are some issues when I try to share other Flatpack applications. It seems to only share the top left part of the window, cutting off from the right and the bottom. I also noticed some issues when rapidly switching the size of the shared window (with the Super+Left/Right Arrow short-cuts). But they recovered after changing the size of the window again.
I tested 3 different Flatpack applications to share (Teams-for-Linux, Signal and Discord), who all had the same issue. A bunch of native applications (Gnome Files, Firefox, Gnome Settings, ...) worked fine, apart from the fast size changing issue (which is a real edge-case and not important in my opinion).

**To Reproduce**
Steps to reproduce the behaviour:
1. Set your display scaling option to 150% (have not tested other scaling) in Gnome.
2. Join or set up a Teams meeting using Teams for Linux.
3. Use the share functionality to share a window from a Flatpack installed program (i.e. Teams itself).
4. See the result on another device in the call.

**Expected behaviour**
Both native and Flatpack installed applications should be shared in the correct resolution without parts of the application cutted away.

**Screen-shots**
From sharing a Flatpack application window:
![Screenshot_20231023-124923](https://github.com/IsmaelMartinez/teams-for-linux/assets/1598708/eec941a9-0499-49df-b6b3-528ce8da124b)
![Screenshot_20231023-124939](https://github.com/IsmaelMartinez/teams-for-linux/assets/1598708/502d5aaa-1932-4fb5-964f-74167c1659b2)
From rapidly switching window size (as mentioned before, not really relevant):
![Screenshot_20231023-125114](https://github.com/IsmaelMartinez/teams-for-linux/assets/1598708/14189669-a759-4ca1-86fd-23ec54f1ac6e)

**Desktop:**
 - OS: Fedora 38 (Wayland and Gnome 44.5)
 - Installation package Flatpack
 - Version 1.3.13

**Additional context**
From my limited knowledge of the underlying technologies, this could be an issue with Electron or Chrome screen sharing in combination with Wayland and desktop scaling, but I lack the knowledge, of addressing this at Electron or somewhere else with the adequate information.

**Comment by BlueCase** [comment]
Same Issue here

**Comment by IsmaelMartinez** [comment]
Strange, are you changing the zoom level or just using the default one? random question, I know.

**Comment by tervor** [comment]
@IsmaelMartinez do you mean the zoom level of the other client in the call?
I have not used any zoom level that I am aware of.

**Comment by jijojosephk** [comment]
@tervor This is problem with `Wayland` and `Electron`. We may have a fix at least immediately, we'll have to rely on the upstream projects to come up with some fixes.

**Comment by tervor** [comment]
@jijojosephk is there a particular Electron issue which describes this? Or are we depending on the Teams web client here?

**Comment by jijojosephk** [comment]
@tervor sorry, I updated the comment.

**Comment by IsmaelMartinez** [comment]
can you verify if this is still an issue using 1.4.1 an above? Closing to keep things tidy. Hopefully it is now sorted

**Comment by BlueCase** [comment]
Seems to be fixed with the latest build. Will test in the next weeks.

**Comment by IsmaelMartinez** [comment]
@demanuPL , have you tried version 1.4.3 ?  It might have another issue (echo) but screensharing might work. Is a pre-release
