### ISSUE TITLE
Password starting with special character not saving

### ISSUE THREAD

**Issue by AccaliaDeElementia** [IsmaelMartinez/teams-for-linux#994]
**Describe the bug**
When using the app a password that begins with the special character ` (backtick) the user authentication is not preserved between session requiring re-authentication each launch.

**To Reproduce**
1. Set your Microsoft password to something beginning with ` (backtick)
2. Authenticate to teams-for-linux
3. Exit teams-for-linux
4. Relaunch and observe that you are asked to re-authenticate

**Expected behavior**
Password and/or login token should be preserved to avoid need to re-authenticate on each launch.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: archlinux
 - Installation package: flatpak
 - Version: teams-for-linux@1.13.3

**Additional context**
It's not the end of the world, especially since work has the paranoia settings cranked to the max on 2FA so i have about a 1 in 3 chance of needing to reenter 2FA on each launch of teams-for-linux anyway. But it seems a particularly odd bug...

**Comment by jijojosephk** [comment]
If you see the same behaviour with `https://teams.microsoft.com` on `chrome`/`firefox`/`edge`, we'll not able to do anything much. Kindly let us know the test results.

**Comment by AccaliaDeElementia** [comment]
Tested using Firefox on the same system to log into the team website directly as directed. No issues. behavior is as expected, i just have to reenter my 2FA code on relaunch not my password and 2FA code.

Left it overnight and through a reboot as well to eliminate the possibility that it was caused just by too quick a relog and behavior of firefox continued to be as expected while the flatpack is not.

**Comment by IsmaelMartinez** [comment]
can you check if this is still an issue in 1.4.1? maybe is an electron issue that is now fixed
